'use strict';
// Actual old saved-fight victory in the new engine, with no forced settlement.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const H=require('./audit_protagonist_v01618.cjs'),N=require('../tests/test_enemy_balance_v01627.cjs');
const ROOT=path.resolve(__dirname,'..'),arg=k=>{const i=process.argv.indexOf(k);return i<0?null:process.argv[i+1];},OUT=path.resolve(arg('--out')||path.join(ROOT,'reports/abyss_difficulty_v01627/final_independent_review_talent90/loaded_026_actual_ledger.json')),cp=x=>JSON.parse(JSON.stringify(x));
const before=N.productionBootstrap(N.loadBefore(ROOT)),current=N.productionBootstrap(H.load(ROOT));current.c.Date=before.c.Date;
const native=H.setup(before,{level:60,team:['MOND_DILUC','MOND_JEAN','LIYUE_ZHONGLI'],route:'ROUTE_ISEKAI',map:'MAP_D163_TAISHAN_MANSION',gear:'craft',enhance:10,talent:10,seed:717});
native.action('DOMAIN_START',{domain:'TAISHAN_MANSION:60'});const saved=JSON.parse(native.serialize()),legacy=new before.R(before.db,cp(saved)),loaded=new current.R(current.db,cp(saved));
assert.equal(saved.runtime.growthDomain.talentRewardVersion,3);assert.equal(saved.runtime.enemyBalanceRevision,undefined);assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(legacy.serialize()));
const rows=[];for(const[e,r,label]of[[before,legacy,'genuine_026_replay'],[current,loaded,'current_loaded_genuine_026']]){const books=r.itemCount('GROWTH_TALENT_LIYUE'),meter=H.observe(e,r),result=H.play(r);assert(result.victory,'native normal fight must win to verify old saved reward');assert.equal(result.domain.items.GROWTH_TALENT_LIYUE,80);assert.equal(r.itemCount('GROWTH_TALENT_LIYUE')-books,80);rows.push({engine:label,result:cp(result),addedBooks:80,inputs:meter.inputs,finalNativeBattle:r._auditLast,afterSave:JSON.parse(r.serialize())});}
assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(legacy.serialize()));assert.equal(H.load(ROOT).fingerprint,current.fingerprint);
const report={passed:true,scope:'Actual complete genuine 0.16.26 TALENT60 saved fight replayed through a normal victory in both old and current engines; two final complete saves equal. No enemy edits, forced wins, food, artifacts, exclusive gear, midbattle healing reset or controlled settlement.',fixture:'Owned Lv60 Isekai + Diluc/Jean/Zhongli C0, ordinary craft+10/cap10 and legal max base talents; declared story access and one initial full HP. Input/ownership preparation is granted, not a natural acquisition-time promise.',currentFingerprint:current.fingerprint,beforeFingerprint:before.fingerprint,oldVersion:3,addedBooks:80,saved,rows};
fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:true,oldVersion:3,books:80,rows:rows.map(r=>({engine:r.engine,rounds:r.result.rounds,inputs:r.inputs})),fingerprint:current.fingerprint}));
