'use strict';
// Read-only native public combat probe. Preparation is granted and reported;
// there is no forced victory, enemy mutation or refill between chambers.
const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto');
const H=require('./audit_protagonist_v01618.cjs'),ROOT=path.resolve(process.argv[2]||path.join(__dirname,'..')),OUT=path.resolve(process.argv[3]||path.join(ROOT,'reports/abyss_difficulty_v01627/baseline')),env=H.load(ROOT),P='PLAYER_CUSTOM',cp=x=>JSON.parse(JSON.stringify(x));
const FLOORS={6:{level:45,team:['MOND_EULA','LIYUE_XIAO','LIYUE_BAIZHU'],formation:'DIAMOND',roles:['균형','공격우선','지원우선']},9:{level:55,team:['MOND_DAHLIA','LIYUE_XINYAN','LIYUE_LANYAN'],formation:'DOUBLE_LINE',roles:['지원우선','균형','지원우선']},12:{level:60,team:['MOND_DILUC','MOND_JEAN','LIYUE_ZHONGLI'],formation:'DOUBLE_LINE',roles:['연계우선','공격우선','지원우선']}};
Object.assign(FLOORS,{1:{level:15,team:['MOND_AMBER','MOND_KLEE','MOND_ALBEDO'],formation:'LINE_AHEAD',roles:['공격우선','공격우선','균형']},2:{level:20,team:['MOND_FISCHL','LIYUE_XINGQIU','MOND_DIONA'],formation:'DOUBLE_LINE',roles:['균형','연계우선','지원우선']},3:{level:25,team:['LIYUE_XIANGLING','MOND_NOELLE','MOND_LISA'],formation:'DOUBLE_LINE',roles:['연계우선','균형','연계우선']},4:{level:30,team:['LIYUE_GAMING','LIYUE_YUNJIN','MOND_ROSARIA'],formation:'LINE_AHEAD',roles:['공격우선','균형','공격우선']},5:{level:35,team:['MOND_VENTI','LIYUE_CHONGYUN','LIYUE_YAOYAO'],formation:'DOUBLE_LINE',roles:['연계우선','균형','지원우선']},7:{level:45,team:['LIYUE_YANFEI','MOND_MIKA','LIYUE_BEIDOU'],formation:'DOUBLE_LINE',roles:['연계우선','균형','공격우선']},8:{level:50,team:['MOND_RAZOR','LIYUE_TARTAGLIA','LIYUE_XIANYUN'],formation:'DOUBLE_LINE',roles:['연계우선','연계우선','균형']}});if(process.env.ABYSS_SAME_LEVEL==='1')FLOORS[6].level=40;
const FOODS=['FOOD_SWEET_MADAME','FOOD_HASH_BROWN','FOOD_ADEPTUS_TEMPTATION','FOOD_JADE_PARCELS','FOOD_SATISFYING_SALAD','TRPG_MEDKIT','TRPG_HEALING_POTION'];
const hp=r=>r.abyssParty().map(id=>{const a=id===P?r.player():r.character(id);return{source:id,hp:a.hp,maxHp:a.maxHp};});
function gear(r,id,e,enh){const slot=r.giveEquipment(e),i=r.s.inventory.find(v=>v.slot===slot);i.enhance=enh;i.enhancementCap=enh>10?12:10;r.action('EQUIP',{slot,owner:id});}
function art(r,id,mode,floor){let best=null,bestScore=-1,tries=0,qual=false;const limit=floor===12&&mode!=='LOW'?4000:mode==='HIGH'?300:mode==='MID'?20:1;
 for(;tries<limit;tries++){const d=r.rollArtifact(),i=r.artifactInstance(d.slot);i.artifact.level=mode==='LOW'?0:5;const st=r.artifactStats(i);qual=i.artifact.quality>=900&&(id==='LIYUE_ZHONGLI'?st.MAX_HP>=200&&st.DEF>=20:id==='MOND_JEAN'?st.ATK>=25&&st.MAX_HP>=100:st.ATK>=35&&st.CRIT>=2);const score=(st.ATK||0)+(st.DEF||0)*.5+(st.MAX_HP||0)*.05;if(floor===12&&mode!=='LOW'){if(qual){best=i;tries++;break;}r.s.inventory=r.s.inventory.filter(v=>v!==i);}else if(score>bestScore){if(best)r.s.inventory=r.s.inventory.filter(v=>v!==best);best=i;bestScore=score;}else r.s.inventory=r.s.inventory.filter(v=>v!==i);}
 if(!best)throw Error('No naturally qualifying artifact within limit '+id);r.action('EQUIP',{slot:best.slot,owner:id});return{owner:id,attempts:tries,instance:cp(best),stats:r.artifactStats(best),selection:floor===12&&mode!=='LOW'?'first qualifying natural roll':'best natural roll in declared sample'};}
function prepare(f,mode,seed){const s=FLOORS[f],enh=mode==='LOW'?6:mode==='MID'&&f!==12?(f<=3?7:10):12,r=H.setup(env,{level:s.level,team:s.team,seed,map:'MAP_V141_MUSK_REEF',gear:'craft',enhance:enh,talent:mode==='LOW'?5:10}),arts=[];
 r.s.constellations??={};for(const id of r.abyssParty())r.s.constellations[id]=0;
 if(mode==='HIGH'&&process.env.ABYSS_CONST!=='C0')for(const id of r.abyssParty()){const n=process.env.ABYSS_CONST==='C2'?2:(f===12||id===P||r.rarityOf(id)===4?6:0);if(n){r.giveItem('STELLA_'+id,n);for(let j=0;j<n;j++)r.action('CONSTELLATION_UNLOCK',{char:id});}}
 if(mode!=='LOW')for(const id of r.abyssParty()){gear(r,id,'EQ_FB_ARMOR_JADE_BULWARK',enh);if(mode==='HIGH'&&id!==P)gear(r,id,'EQ_EX_'+id,enh);}
 for(const id of r.abyssParty()){if(f===5)gear(r,id,'EQ_LY_ACC_STARGAZER',6);if(f===9)gear(r,id,'EQ_ACC_STEADFAST',mode==='LOW'?6:9);arts.push(art(r,id,mode,f));}
 r.action('FORMATION_SET',{formation:s.formation});s.roles.forEach((t,i)=>r.action('PARTY_TACTIC',{slot:i+2,tactic:t}));const abs=r.ensureAbyss();for(let n=1;n<f;n++)abs.clears[n]={rounds:1,chambers:[1,1,1],party:[],run:abs.run};
 if(mode!=='LOW'&&process.env.ABYSS_ITEMS!=='NONE')for(const item of FOODS)r.giveItem(item,item.startsWith('TRPG_')?3:12);r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;for(const id of s.team)r.s.chars[id].hp=r.character(id).maxHp;r.s.global.PRNG_STATE=seed;return{r,arts,enh};}
function eat(r,mode){if(mode==='LOW')return;for(const id of r.abyssParty()){for(let n=0;n<6;n++){const a=hp(r).find(v=>v.source===id);if(a.hp<=0||a.hp>=a.maxHp*.8)break;const last=id===P?r.s.global.LAST_RECOVERY_MEAL_ITEM_ID:r.s.chars[id].lastRecoveryMeal,item=FOODS.slice(0,2).find(v=>v!==last&&r.itemCount(v)>0);if(!item)break;r.action('USE_ITEM',{item,owner:id});}if(hp(r).find(v=>v.source===id).hp>0)for(const item of FOODS.slice(2,5))if(r.itemCount(item)>0)r.action('USE_ITEM',{item,owner:id});}}
function act(r,mode){const b=r.s.runtime,room=env.api.abyssConfig.floors[b.abyss.floor-1].rooms[b.abyss.chamber-1],cards=r.combatCards().filter(v=>!v.reason),find=id=>cards.find(v=>v.id===id),me=b.actors.find(v=>v.source===P);let foes=b.actors.filter(v=>v.side==='ENEMY'&&v.hp>0);if(room.alternate&&foes.length>1)foes=foes.filter(v=>v.abyssIndex===(b.round%2?0:1));foes.sort((a,b)=>Number(b.abyssHealer)-Number(a.abyssHealer)||a.hp-b.hp);let card,target;
 if(mode!=='LOW'&&me.hp<me.maxHp*.8){card=cards.find(v=>v.id==='ITEM:TRPG_MEDKIT'&&v.targets.some(t=>t.id===me.id))||cards.find(v=>v.id==='ITEM:TRPG_HEALING_POTION'&&v.targets.some(t=>t.id===me.id));if(card)target=me;}
 if(!card&&(b.abyss.floor===12||me.hp<me.maxHp*.3))card=find('PLAYER_BASIC_GUARD');
 if(!card){const e=find('PLAYER_ISEKAI_E');if(e){target=foes.find(v=>e.targets.some(t=>t.id===v.id)&&!v.statuses.some(s=>s.id==='STATUS_ISEKAI_EXPOSED'&&(s.rounds==null||s.rounds>0)));if(target)card=e;}}
 card??=find('PLAYER_ISEKAI_Q')||find('PLAYER_ISEKAI_E')||find('PLAYER_BASIC_ATTACK')||find('PLAYER_BASIC_GUARD');if(!card)throw Error('No public usable action');target??=foes.find(v=>card.targets.some(t=>t.id===v.id));target??=card.targets.map(t=>b.actors.find(a=>a.id===t.id)||t).sort((a,b)=>(a.hp??Infinity)-(b.hp??Infinity))[0];r.action('COMBAT',{card:card.id,...(target?{target:target.id}:{})});return card.id;}
function run(f,mode,seed){const row={floor:f,prep:mode,constellationPolicy:process.env.ABYSS_CONST||'REFERENCE',itemPolicy:process.env.ABYSS_ITEMS||'FINITE',seed,state:'PREPARE',rooms:[],errors:[]};let r,last,meter;try{const prep=prepare(f,mode,seed);r=prep.r;row.enh=prep.enh;row.artifacts=prep.arts;row.talents=Object.fromEntries(r.abyssParty().map(id=>[id,r.talentLevels(id)]));row.constellations=Object.fromEntries(r.abyssParty().map(id=>[id,r.constellationLevel(id)]));row.equipment=cp(r.s.inventory.filter(v=>v.equipped));row.before=hp(r);function track(){const b=r.s.runtime;if(!meter||!b)return;for(const a of b.actors.filter(a=>a.side==='ALLY')){const ratio=a.hp/a.maxHp;meter.minHpBySource[a.source]=Math.min(meter.minHpBySource[a.source]??1,ratio);}const allies=b.actors.filter(a=>a.side==='ALLY');meter.minPartyHp=Math.min(meter.minPartyHp,allies.reduce((n,a)=>n+a.hp,0)/allies.reduce((n,a)=>n+a.maxHp,0));}const dmg=r.applyDamage;r.applyDamage=function(a,t,n,o){const before=t.hp,sh=(t.shields||[]).reduce((n,s)=>n+(s.value||0),0),v=dmg.call(this,a,t,n,o);if(meter&&t.side==='ALLY'){meter.hpDamage+=Math.max(0,before-t.hp);meter.shieldSpent+=Math.max(0,sh-(t.shields||[]).reduce((n,s)=>n+(s.value||0),0));meter.hits++;track();}else track();return v;};const heal=r.heal;r.heal=function(...args){const target=args[0],before=target?.hp,v=heal.apply(this,args);if(meter&&target?.side==='ALLY'){meter.healActual+=Math.max(0,target.hp-before);meter.healCalls++;track();}return v;};const shield=r.shield;r.shield=function(...args){const target=args[0],before=(target?.shields||[]).reduce((n,s)=>n+(s.value||0),0),v=shield.apply(this,args);if(meter&&target?.side==='ALLY')meter.shieldAdded+=Math.max(0,(target.shields||[]).reduce((n,s)=>n+(s.value||0),0)-before);return v;};for(const name of ['roundEnd','aiTurn']){const native=r[name];r[name]=function(...args){const actors=this.s.runtime?.actors.filter(a=>a.side==='ALLY')||[],before=actors.reduce((n,a)=>n+Math.max(0,a.hp),0),oldDamage=meter?.hpDamage||0,oldHeal=meter?.healActual||0,v=native.apply(this,args);if(meter){const after=actors.reduce((n,a)=>n+Math.max(0,a.hp),0),inferred=Math.max(0,before+(meter.healActual-oldHeal)-after-(meter.hpDamage-oldDamage));meter.hpDamage+=inferred;meter.directHpDamage+=inferred;}track();return v;};}const finish=r.finishBattle;r.finishBattle=function(...args){track();last=cp(this.s.runtime);return finish.apply(this,args);};
 for(let ch=1;ch<=3;ch++){const room={chamber:ch,before:hp(r)},stock=Object.fromEntries(FOODS.map(id=>[id,r.itemCount(id)]));eat(r,mode);if(f===8&&ch<3)for(const id of r.abyssParty())gear(r,id,'EQ_LY_SPECIAL_LEYLINE_STAKE',10);if(f===8&&ch===3)for(const a of prep.arts)r.action('EQUIP',{slot:a.instance.slot,owner:a.owner});if(f===9&&ch===2)for(const id of r.abyssParty())gear(r,id,'EQ_LY_ACC_STARGAZER',0);if(f===9&&ch===3)for(const id of r.abyssParty())gear(r,id,'EQ_ACC_STEADFAST',9);const reason=r.abyssFloorReason(f);if(reason){room.state='ENTRY_BLOCKED';room.reason=reason;row.rooms.push(room);row.state=room.state;break;}r.action('ABYSS_ENTER',{floor:f});room.initial=cp(r.s.runtime.actors);room.gate=Object.fromEntries(r.s.runtime.actors.filter(v=>v.side==='ALLY').map(v=>[v.source,r.abyssBlock(v,r.s.runtime.actors.find(v=>v.side==='ENEMY'),{critical:true})]));room.mastery=f===12?r.abyssMasteryReady():null;last=null;meter={hpDamage:0,directHpDamage:0,shieldSpent:0,shieldAdded:0,healActual:0,healCalls:0,hits:0,minPartyHp:1,minHpBySource:{}};track();r.action('COMBAT_BEGIN');let n=0;for(;r.s.runtime&&n<300;n++)act(r,mode);room.inputs=n;room.metrics=cp(meter);meter=null;const res=JSON.parse(r.s.global.LAST_BATTLE_RESULT_JSON||'{}');room.state=r.s.runtime?'INPUT_LIMIT':res.abyss?.outcome||'NO_RESULT';room.result=res;room.native=last?{round:last.round,actors:last.actors,log:last.log}:null;room.rounds=last?.round||r.s.runtime?.round;room.ko=(last?.actors||[]).filter(v=>v.side==='ALLY'&&v.hp<=0).map(v=>v.source);room.preHp=last?last.actors.filter(v=>v.side==='ALLY').reduce((n,v)=>n+v.hp,0)/last.actors.filter(v=>v.side==='ALLY').reduce((n,v)=>n+v.maxHp,0):null;room.immune=(last?.log||[]).filter(v=>v.immune).length;room.after=hp(r);room.consumed=Object.fromEntries(FOODS.map(id=>[id,stock[id]-r.itemCount(id)]).filter(([,n])=>n>0));row.rooms.push(room);row.state=room.state;if(room.state!=='NEXT')break;r.action('MENU',{screen:'LOCATION'});}
 row.after=hp(r);row.finalHp=row.after.reduce((n,v)=>n+v.hp,0)/row.after.reduce((n,v)=>n+v.maxHp,0);row.rounds=row.rooms.reduce((n,v)=>n+(v.rounds||0),0);row.totalKo=row.rooms.reduce((n,v)=>n+(v.ko?.length||0),0);row.gateBlocked=row.rooms.some(v=>v.mastery===false||Object.values(v.gate||{}).some(x=>x==='무적입니다.'));}catch(e){row.state='ERROR';row.errors.push(e.stack);if(r)row.errorRuntime=cp(r.s.runtime);}return row;}
fs.mkdirSync(OUT,{recursive:true});const sourceHash=crypto.createHash('sha256').update(fs.readFileSync(ROOT+'/source/runtime_abyss.js')).digest('hex'),data={fingerprint:env.fingerprint,sourceHash,assumptions:{prep:'Granted ownership, legal growth/talents, native finite artifact rolls, real public gear/constellation/entry/actions. One initial full HP; no forced victory or chamber refills.',low:'craft+6, talent5 clamped legal, first unenhanced natural artifact, no constellation or foods',mid:'craft+10 (F12+12), boss armour, capped maximum legal talents, best20 natural artifact rolls +5 (F12 first natural gate-qualified artifact), no constellations, finite meal/medicine stock',high:'craft/exclusive+12, boss armour, max legal talents, best300 natural artifact rolls+5 (F12 first natural gate-qualified), protagonist/4star C6 (F12 all C6), finite meal/medicine stock',policy:'Native E/Q targeting healer/open lowHP enemy; guard below30%, permanent F12 guard, healing medicines below80% when stock exists. Actual companion AI.',limitations:'Isolated granted prerequisite floor clears do not prove natural account full ascent or acquisition. Gate failures separated from numeric combat losses.'},rows:[]};
const floors=(process.env.ABYSS_FLOORS||'6,9,12').split(',').map(Number),modes=(process.env.ABYSS_MODES||'LOW,MID,HIGH').split(','),seeds=(process.env.ABYSS_SEEDS||'717').split(',').map(Number);
for(const f of floors)for(const mode of modes)for(const seed of seeds){const row=run(f,mode,seed);data.rows.push(row);fs.writeFileSync(OUT+'/native.json.gz',zlib.gzipSync(JSON.stringify(data)));const summary=data.rows.map(v=>({floor:v.floor,prep:v.prep,constellationPolicy:v.constellationPolicy,itemPolicy:v.itemPolicy,seed:v.seed,state:v.state,rounds:v.rounds,finalHp:v.finalHp,ko:v.totalKo,gateBlocked:v.gateBlocked,rooms:v.rooms.map(c=>({chamber:c.chamber,state:c.state,rounds:c.rounds,preHp:c.preHp,ko:c.ko,immune:c.immune,mastery:c.mastery,metrics:c.metrics,consumed:c.consumed})),errors:v.errors}));fs.writeFileSync(OUT+'/summary.json',JSON.stringify({fingerprint:env.fingerprint,sourceHash,rows:summary},null,2)+'\n');console.log(JSON.stringify(summary.at(-1)));if(global.gc)global.gc();}
