"""Build the authored ensemble edition; no original node, branch or effect is deleted.

JSON is the editable story source. purpose/payoff are reviewer notes and are not
shipped as player-facing exposition. Empty episodes bypass obsolete compulsory
errands for fresh play, while their old gates remain valid saved cursors.
"""
import json
from pathlib import Path

def main():
    root=Path(__file__).resolve().parents[2]
    episodes=json.loads((root/'tools/editorial/liyue_ensemble.json').read_text(encoding='utf-8'))
    for anchor,e in episodes.items():
        assert e.get('purpose'), anchor
        assert not e['steps'] or e.get('payoff'), anchor
    edits=[]
    for line in (root/'tools/editorial/liyue_v0141.tsv').read_text(encoding='utf-8').splitlines():
        if not line.strip() or line.startswith('#'): continue
        key,speaker,opening,beat,closing=line.split('|')
        chapter,scene=key.split(':',1)
        edits.append(dict(quest='Q_ISK_LIYUE_'+chapter,scene=scene,speaker=speaker,opening=opening,beat=beat,closing=closing))
    shipped={k:{a:v for a,v in e.items() if a not in ['purpose','payoff']} for k,e in episodes.items()}
    out={'version':1,'episodes':shipped,'sceneEdits':edits}
    (root/'source/runtime_local_story_content.js').write_text('/* Original CRPG ensemble edition; generated by tools/editorial/liyue_ensemble.py. */\nglobalThis.CRPGLocalStory='+json.dumps(out,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8',newline='\n')
    print(f'Authored {sum(bool(e["steps"]) for e in episodes.values())} field episodes; obsolete errands bypassed with legacy gates retained')
if __name__=='__main__': main()
