const {fresh,cast,card,root}=require('./audit_liyue_cards.cjs'),fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');
const tests=[];function test(id,fn){try{tests.push({id,ok:true,evidence:fn()});}catch(e){tests.push({id,ok:false,error:e.message});}};
test('qiqi_talisman_one_heal_per_ally_per_round',()=>{const f=fresh('LIYUE_QIQI');cast(f,'LIYUE_QIQI_Q');const ally=f.allies[1];ally.hp=100;const before=f.b.log.length;f.foes.forEach(t=>f.r.damage(ally,t,.5,'PHYSICAL'));const heals=f.b.log.slice(before).filter(v=>v.target===ally.name&&v.heal);assert.equal(heals.length,1,'Expected 1 heal, actual '+JSON.stringify(heals));return heals;});
test('zhongli_petrify_locks_normal_enemy',()=>{const f=fresh('LIYUE_ZHONGLI');cast(f,'LIYUE_ZHONGLI_Q');assert(f.r.combatActionLocked(f.foes[0]),'No lock. statuses='+JSON.stringify(f.foes[0].statuses));});
test('zibai_recast_while_age_gap_should_be_denied',()=>{const f=fresh('LIYUE_ZIBAI');cast(f,'LIYUE_ZIBAI_E');const age=f.a.statuses.find(s=>s.id==='AGE_GAP');age.uses=4;age.light=100;f.a.cooldowns.LIYUE_ZIBAI_E=0;assert(f.r.cardReason(f.a,card(f.r,'LIYUE_ZIBAI_E')),'E has empty reason while AGE_GAP active; execute resets uses and resource.');});
test('chongyun_retains_diluc_pyro_infusion',()=>{const f=fresh('LIYUE_CHONGYUN');cast(f,'LIYUE_CHONGYUN_E');const ally=f.allies[1];ally.source='MOND_DILUC';f.r.addCombatStatus(ally,'DILUC_INFUSION',2);f.foes[0].auras=[];const before=f.b.log.length;f.r.basicHit(ally,f.foes[0]);const packets=f.b.log.slice(before).filter(v=>v.damage);assert.equal(packets[0]?.element,'불','Actual packets '+JSON.stringify(packets));});
test('icy_quill_not_consumed_on_miss',()=>{const f=fresh('LIYUE_SHENHE');cast(f,'LIYUE_SHENHE_E');const quill=f.b.fields.find(x=>x.kind==='ICY_QUILL');f.r.die=()=>100;f.r.damage(f.allies[1],f.foes[0],.7,'CRYO');assert.equal(quill.stacks,4,'Actual stacks '+quill.stacks);});
test('yunjin_flag_not_consumed_on_miss',()=>{const f=fresh('LIYUE_YUNJIN');cast(f,'LIYUE_YUNJIN_Q');const flag=f.b.fields.find(x=>x.kind==='FLYING_CLOUD_FLAG');f.r.die=()=>100;f.r.basicHit(f.allies[1],f.foes[0]);assert.equal(flag.counts?.['1:ALLY_1']||0,0,'Actual '+JSON.stringify(flag.counts));});
test('lunar_conversion_must_replace_ordinary_shield',()=>{const f=fresh('LIYUE_ZIBAI');cast(f,'LIYUE_ZIBAI_E');f.r.setAura(f.foes[0],'HYDRO');f.r.basicHit(f.a,f.foes[0]);assert(!f.a.shields.some(s=>s.source==='RX_CRYSTALLIZE'),'Ordinary Crystallize shield remains '+JSON.stringify(f.a.shields));});
test('dedicated_lunar_damage_triggers_full_moon_resource',()=>{const f=fresh('LIYUE_ZIBAI');cast(f,'LIYUE_ZIBAI_E');const age=f.a.statuses.find(s=>s.id==='AGE_GAP');f.b.moonsignState='FULL';cast(f,'LIYUE_ZIBAI_Q');assert.equal(age.light,35,'Q dedicated lunar damage gives '+age.light+' instead of35');});
test('jade_screen_uses_card_range',()=>{const f=fresh('LIYUE_NINGGUANG');cast(f,'LIYUE_NINGGUANG_E');const enemy=f.foes[0],target=f.allies[1];enemy.range='근접';const hp=target.hp;f.r.damage(enemy,target,1,'PHYSICAL',{range:'원거리'});const damage=hp-target.hp;assert.equal(damage,30,'Expected50 pre jade ×.6=30; actual '+damage);});
test('zibai_charge_no_resource_underflow',()=>{const f=fresh('LIYUE_ZIBAI');cast(f,'LIYUE_ZIBAI_E');const age=f.a.statuses.find(s=>s.id==='AGE_GAP');age.light=100;cast(f,'LIYUE_ZIBAI_E_CHARGE');assert.equal(age.light,65);assert.equal(age.uses,1);assert(f.r.cardReason(f.a,card(f.r,'LIYUE_ZIBAI_E_CHARGE')));});
fs.writeFileSync('/tmp/audit_liyue_targeted_results.json',JSON.stringify({sourceHash:crypto.createHash('sha256').update(fs.readFileSync(root+'/source/runtime_liyue_cards.js')).digest('hex'),tests},null,2));console.log(JSON.stringify(tests,null,2));

if(tests.some(t=>!t.ok))process.exitCode=1;
