'use strict';
const {fresh,cast,card,ctx,db,root}=require('./audit_liyue_cards.cjs');
const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto'),tests=[];
const hash=()=>crypto.createHash('sha256').update(fs.readFileSync(root+'/source/runtime_liyue_cards.js')).digest('hex'),sourceHash=hash();
const test=(id,fn)=>{try{tests.push({id,ok:true,evidence:fn()});}catch(e){tests.push({id,ok:false,error:e.message});}};
const age=f=>f.a.statuses.find(s=>s.id==='AGE_GAP');
function lunarFixture(){const f=fresh('LIYUE_ZIBAI');cast(f,'LIYUE_ZIBAI_E');return f;}
function restore(f){const saved=f.r.serialize(),r=new ctx.CRPGRuntime.Runtime(db,JSON.parse(saved));r.random=()=>.5;r.die=()=>50;const b=r.s.runtime,a=b.actors.find(a=>a.id===f.a.id);return{r,b,a,allies:b.actors.filter(a=>a.side==='ALLY'),foes:b.actors.filter(a=>a.side==='ENEMY'),saved};}
test('charge_100_minus70_plus35_is65_once_same_round',()=>{const f=lunarFixture();age(f).light=100;cast(f,'LIYUE_ZIBAI_E_CHARGE');assert.equal(age(f).light,65);assert.equal(age(f).uses,1);f.b.actionSequence++;cast(f,'LIYUE_ZIBAI_Q');assert.equal(age(f).light,65);assert.equal(age(f).used['MOON:1'],true);return{light:age(f).light,uses:age(f).uses,moonLevel:f.r.liyueMoonLevel('ALLY')};});
test('lunar_counter_survives_validated_save_and_constructor_restore',()=>{const f=lunarFixture();age(f).light=100;cast(f,'LIYUE_ZIBAI_E_CHARGE');const g=restore(f);assert.equal(age(g).light,65);assert.equal(age(g).uses,1);assert.equal(age(g).used['MOON:1'],true);g.b.actionSequence++;cast(g,'LIYUE_ZIBAI_Q');assert.equal(age(g).light,65);g.r.setAura(g.foes[0],'물');g.r.basicHit(g.a,g.foes[0]);assert.equal(age(g).light,80);return{chargeSaved:65,afterQ:65,afterBasic:age(g).light,lunarRound:g.b.lunarRounds.ALLY};});
test('next_round_has_one_new35_and_turn_start25_is_idempotent',()=>{const f=lunarFixture();age(f).light=100;cast(f,'LIYUE_ZIBAI_E_CHARGE');f.r.roundEnd();assert.equal(f.b.round,2);f.a.turns++;f.r.onCombatTurnStart(f.a);assert.equal(age(f).light,90);f.r.onCombatTurnStart(f.a);assert.equal(age(f).light,90);cast(f,'LIYUE_ZIBAI_Q');assert.equal(age(f).light,100);assert(age(f).used['MOON:2']);f.r.liyueLunarDamage(f.a,f.foes[0],10);assert.equal(age(f).light,100);return{light:100,used:age(f).used};});
test('enemy_lunar_packet_does_not_grant_ally_time_light',()=>{const f=lunarFixture();f.r.liyueLunarDamage(f.foes[0],f.allies[1],10);assert.equal(age(f).light,0);assert.equal(f.b.lunarRounds.ALLY,undefined);assert.equal(f.b.lunarRounds.ENEMY,1);});
test('dead_zibai_does_not_enable_hydro_conversion',()=>{const f=lunarFixture();f.a.hp=0;f.r.setAura(f.foes[0],'물');f.r.damage(f.allies[1],f.foes[0],1,'바위');assert(f.allies[1].shields.some(s=>s.source==='RX_CRYSTALLIZE'));assert(!f.b.log.some(p=>p.reaction==='RX_LUNAR_CRYSTALLIZE'));});
test('pyro_crystallize_stays_ordinary',()=>{const f=lunarFixture();f.r.setAura(f.foes[0],'불');f.r.damage(f.a,f.foes[0],1,'바위');assert(f.a.shields.some(s=>s.source==='RX_CRYSTALLIZE'));assert.equal(age(f).light,0);});
test('fresh_breakthrough_from_second_yelan_e_is_retained',()=>{const f=fresh('LIYUE_YELAN');cast(f,'LIYUE_YELAN_E');assert(f.a.statuses.some(s=>s.id==='BREAKTHROUGH'));f.b.actionSequence++;cast(f,'LIYUE_YELAN_E');assert(f.a.statuses.some(s=>s.id==='BREAKTHROUGH'),'Second E hits3 and gains a NEW BREAKTHROUGH but cleanup removed it; statuses='+JSON.stringify(f.a.statuses));});
test('jade_screen_reduces_entire_first_ranged_attack_action',()=>{const f=fresh('LIYUE_NINGGUANG');cast(f,'LIYUE_NINGGUANG_E');const enemy=f.foes[0],t=f.allies[1];f.b.actionSequence++;f.b.log=[];for(let i=0;i<3;i++)f.r.damage(enemy,t,.4,'물리',{range:'원거리',card:'AUDIT_MULTIHIT'});const packets=f.b.log.filter(p=>p.target===t.name&&p.damage);assert.deepEqual(packets.map(p=>p.damage),[12,12,12],'Base20 per hit must all be×.6. Actual '+JSON.stringify(packets));});
test('yanfei_q_gains_new_three_seals_after_spending_old_ones',()=>{const f=fresh('LIYUE_YANFEI');cast(f,'LIYUE_YANFEI_E');f.b.actionSequence++;f.r.actorCards=()=>[card(f.r,'LIYUE_YANFEI_Q')];f.r.aiTurn(f.a,f.foes);assert.equal(f.a.statuses.find(s=>s.id==='SCARLET_SEAL')?.stacks,3);});
test('boss_petrify_next_action_multihit_is_reduced_once_as_an_action',()=>{const f=fresh('LIYUE_ZHONGLI'),enemy=f.foes[0];enemy.grade='보스';f.b.order=[{id:f.a.id,score:120},{id:enemy.id,score:100}];f.b.cursor=0;cast(f,'LIYUE_ZHONGLI_Q');assert.equal(f.b.order.find(v=>v.id===enemy.id).score,70);f.b.actionSequence++;f.b.log=[];enemy.turns++;f.r.executeCard(enemy,card(f.r,'MOND_DILUC_E'),f.allies[1].id);const packets=f.b.log.filter(p=>p.target===f.allies[1].name&&!p.sourceKind&&p.damage);assert.deepEqual(packets.map(p=>p.damage),[20,23,29]);assert(!enemy.statuses.some(s=>s.id==='LIYUE_BOSS_PETRIFY'));return packets.map(p=>p.damage);});
test('pending_opening_preserves_exact_prepared_order',()=>{const f=fresh('LIYUE_ZHONGLI');f.b.opening={state:'PENDING'};f.b.order=[{id:f.foes[0].id,score:77,first:false},{id:f.a.id,score:12,first:false}];const before=JSON.stringify(f.b.order);f.a.liyueNextScoreFactor=.7;f.r.newRound();assert.equal(JSON.stringify(f.b.order),before);assert.equal(f.a.liyueNextScoreFactor,.7);});
const report={sourceHash,afterHash:hash(),total:tests.length,passed:tests.filter(t=>t.ok).length,tests};fs.writeFileSync('/tmp/liyue_final_semantic_results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.passed<report.total)process.exitCode=1;
