'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto');
const {c,fs,root,db,R}=require('../helpers_v011.cjs');
c.CRPGRelationships.install(c.CRPGRuntime,{events:c.CRPGRelationships.catalogFromDB(db),activities:c.CRPGRelationships.activitiesFromDB(db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});
const cp=x=>JSON.parse(JSON.stringify(x));let seq=0;
const report={scope:'All 85 authored legend definitions. Main completion/branch prerequisites and initial provisioning are synthetic fixtures. All tested legend/rejoin transitions use runtime actions. Random field encounters suppressed; actual MOVE edges still used. No source writes.',source:root,dbSha256:crypto.createHash('sha256').update(fs.readFileSync(root+'/content/db.json')).digest('hex'),results:[]};
const path=process.env.QA_REPORT||'/tmp/recruitment_v013_qa.json';
function save(){fs.writeFileSync(path,JSON.stringify(report,null,2));}
function snapshot(r){return cp({cursor:r.storyActiveNodeId(),main:r.s.global.STORY_CURSOR_NODE_ID,context:r.s.storyContext,stack:r.s.storyReturnStack,mora:r.s.global.MORA,inventory:r.s.inventory,bond:r.s.relations,cost:r.s.storyCostReceipts,event:r.s.storyEventReceipts,flags:r.s.flags});}
function reload(r,rec){const before=snapshot(r),after=new R(db,JSON.parse(r.serialize()));after.rollEncounter=()=>null;assert.deepEqual(snapshot(after),before,'Save reload changed cursor/economy/bond/flags/receipts');rec.reloads++;return after;}
function own(r,char){return JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON||'{}')[char]?.state;}
function provision(def){let r=new R(db);r.newGame({name:'QA개인임무',route:def.ROUTE_SCOPE,seed:7733,saveId:'V013-RECRUIT-'+(++seq)});const g=r.s.global,f=r.s.flags;
 Object.assign(g,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:r.storyDefinition(def.id).MAP_ID,STORY_MENU_POLICY:'',STORY_WAITING:true,STORY_NEXT_PREPARED:'',SCREEN_MODE:'LOCATION',WORLD_TIME:'12:00',MORA:100000,PLAYER_LEVEL:20});
 for(const k of ['storyJourney','storyBreak','storyArrival','storyMenuFrame','storyContext','battlePreparation','storyRecovery'])delete r.s[k];
 Object.assign(f,{FLAG_TRV_MON_CH2_CLEAR:true,FLAG_ISK_M05_CLEAR:true,FLAG_ISK_MON_PROLOGUE_CLEAR:true,FLAG_ISK_MAIN_UNLOCKED:true,FLAG_TRV_LIYUE_CLEAR:true,FLAG_ISK_L04_REGION_CLEAR:true,FLAG_ACCESS_REGION_LIYUE:true,FLAG_MOND_MIKA_RETURNED:true,FLAG_MOND_MONA_PRESENT:true,FLAG_WORLD_ZIBAI_RETURNED:true,FLAG_ISK_META_KNOWLEDGE:'UNKNOWN',FLAG_ISK_MOND_BRANCH:'EXPEDITION',FLAG_ISK_EXPEDITION_FORK:'RETURN',FLAG_ISK_A_SUBBRANCH:'AB',FLAG_ISK_L01_LEAF:'AB1',FLAG_ISK_L02_LEAF:'AB1',FLAG_ISK_L03_LEAF:'AB1',FLAG_ISK_L04_LEAF:'AB1',FLAG_TRV_LY_GOLDEN_ROUTE:'B',FLAG_TRV_LY_GOLDEN_EVIDENCE_SENT:true});
 for(const m of String(def.START_CONDITION||'').matchAll(/(FLAG_\w+)\s*=TRUE/g))if(m[1]!==def.COMPLETE_FLAG_ID)f[m[1]]=true;
 for(const q of ['Q_ISK_MOND_01','Q_ISK_MOND_02','Q_ISK_MOND_03','Q_TRV_MOND_01','Q_TRV_MOND_02','Q_ISK_LIYUE_01','Q_ISK_LIYUE_02','Q_ISK_LIYUE_03','Q_ISK_LIYUE_04','Q_TRV_LIYUE_01','Q_TRV_LIYUE_02','Q_TRV_LIYUE_03','Q_TRV_LIYUE_04'])Object.assign(r.questState(q),{state:'완료',claimed:true,completedTurn:0,acceptedTurn:0});
 const l=r.ensureLiyue();l.access={phase:'OPEN'};
 if(def.ROUTE_SCOPE==='ROUTE_ISEKAI'){const e=r.liyueDefinitions().get('EVT_ISK_L04_AB1_END');const receipt={event:e.EVENT_ID,resolvedNode:e.SOURCE_ID_OR_FILTER,saveId:g.SAVE_ID,route:g.STORY_ROUTE_ID,quest:e.p.quest_id,branch:'AB',leaf:'AB1',kind:'gate',day:g.WORLD_DAY,turn:0};l.events[e.EVENT_ID]=receipt;l.regionReceipt=cp(receipt);}
 r.s.guildLegends={[def.id]:{day:g.WORLD_DAY}};
 if(def.RECRUIT_MODE==='STORY_ALREADY_JOINED')r.unlockCharacter(def.CHAR_ID);
 for(const [id,n]of Object.entries(JSON.parse(def.COST_ITEMS_JSON||'{}')))r.giveItem(id,Number(n)*2);
 r.rollEncounter=()=>null;r.prepareStory();return r;
}
function act(r,type,p,rec){rec.actions++;if(rec.actions>800)throw Error('ACTION_LIMIT');const node=type==='STORY_CHOICE'?r.storyChoices().find(n=>n[4]===p?.node):type==='STORY_NEXT'?r.storyNode():null,replay=node&&/LEGEND_ACCEPT_AND_PAY|COMPLETE_LEGEND|UNLOCK_CARD_ONCE|JOIN_ACCEPTED/.test(node[12]),envelope={id:r.s.global.SAVE_ID+':'+(r.s.global.LAST_COMMITTED_ACTION_SEQ+1),revision:r.s.global.SAVE_REVISION,type,...(p||{})};let result;try{result=r.action(type,p||{});if(replay){const saved=r.serialize();assert.deepEqual(cp(r.transact(envelope)),cp(result),'Repeated action receipt changed');assert.equal(r.serialize(),saved,'Repeated action receipt duplicated effects');rec.duplicateReceipts=(rec.duplicateReceipts||0)+1;}}catch(e){e.qa={type,p,node:r.storyActiveNodeId(),context:r.s.storyContext,phase:r.playPhase(),choices:r.storyChoices().map(n=>({id:n[4],label:n[10],condition:n[11],effects:n[12]}))};throw e;}if(result?.ok===false)throw Error(JSON.stringify(result));return result;}
function walk(r,target,rec){let guard=0;while(r.s.global.CURRENT_MAP_ID!==target){assert(++guard<35,'map walk loop');let queue=[[r.s.global.CURRENT_MAP_ID,[]]],seen=new Set([r.s.global.CURRENT_MAP_ID]),found;
 while(queue.length){const [at,edges]=queue.shift();if(at===target){found=edges;break;}for(const e of r.rows('47_MAP_EDGE_DB').filter(e=>e[1]===at&&e[11]==='ACTIVE'&&e[8]==='Y')){if(e[6]&&e[6]!=='FLAG_TRUE'&&!r.storyCondition(e[6]))continue;if(!seen.has(e[2])){seen.add(e[2]);queue.push([e[2],[...edges,e[0]]]);}}}assert(found?.length,'No path to '+target);act(r,'MOVE',{edge:found[0]},rec);}}
function select(r,mode,rec){const cs=r.storyChoices();if(!cs.length)return null;const pay=cs.find(n=>/LEGEND_ACCEPT_AND_PAY/.test(n[12]));if(pay)return pay;
 const group=String(cs[0][14]||''),joinGroup=/JOIN|RECRUIT|G_CARD/.test(group);let choice;
 if(mode==='defer'&&joinGroup&&!['MOND_VENTI','LIYUE_ZHONGLI'].includes(rec.character)&&rec.initialOwned!=='JOINED'){choice=cs.find(n=>/COMPANION_ELIGIBLE/.test(n[12]))||cs.find(n=>/_(DEFER|LATER|NO)$/.test(n[4]))||cs.find(n=>/보류|나중|미루|약속하지|재회 때|않는다|각자의|다른 날/.test(n[10]||''));if(choice)rec.declines.push(choice[4]);else throw Error('QA_SELECTOR_NO_DECLINE '+group);}
 if(!choice&&mode==='accept'&&joinGroup)choice=cs.find(n=>/JOIN_ACCEPTED|UNLOCK_CARD_ONCE/.test(n[12]))||cs.find(n=>/_(ACCEPT|YES)$/.test(n[4]))||cs.find(n=>/수락/.test(n[10]||''));
 return choice||cs.find(n=>/PREP_(YES|ACCEPT)$/.test(n[4]))||cs[0];
}
function run(r,mode,rec){let costReload=false,choiceReload=false,guard=0;while(r.s.storyContext&&guard++<600){
 if(r.s.storyJourney){if(r.s.storyJourney.scripted)act(r,'STORY_SCRIPTED_TRAVEL',{},rec);else{walk(r,r.s.storyJourney.target,rec);act(r,'JOURNEY_RESUME',{},rec);}continue;}
 if(r.s.storyBreak){act(r,'JOURNEY_RESUME',{},rec);continue;}
 assert(!r.s.runtime,'Unexpected personal combat');let choice=select(r,mode,rec);
 if(choice){if(!choiceReload){r=reload(r,rec);choiceReload=true;choice=r.storyChoices().find(n=>n[4]===choice[4]);}act(r,'STORY_CHOICE',{node:choice[4]},rec);}else{const n=r.storyNode();assert(n,'No active story node '+r.storyActiveNodeId());act(r,'STORY_NEXT',{node:n[4]},rec);}
 if(!costReload&&r.s.storyCostReceipts?.[rec.quest]){r=reload(r,rec);costReload=true;}
 }
 assert(guard<600,'Story loop');return r;}
const probe=new R(db);probe.newGame({name:'QA색인',route:'ROUTE_TRAVELER',seed:8833,saveId:'QA-INDEX'});const defs=[...probe.storyIndex().legends.values()].filter(d=>d.STATUS==='ACTIVE'&&(!process.env.QA_IDS||process.env.QA_IDS.split(',').includes(d.id)));console.log('START',defs.length);save();
for(const def of defs){const rec={id:def.id,quest:def.QUEST_ID,route:def.ROUTE_SCOPE,character:def.CHAR_ID,actions:0,reloads:0,declines:[],passed:false};try{let r=provision(def),startMora=r.s.global.MORA,startItems=Object.fromEntries(Object.keys(JSON.parse(def.COST_ITEMS_JSON||'{}')).map(id=>[id,r.itemCount(id)])),startBond=r.storyBond(def.PROFILE_ID),initialOwned=own(r,def.CHAR_ID);rec.initialOwned=initialOwned;act(r,'LEGEND_ENTER',{quest:def.id},rec);r=run(r,'defer',rec);assert(r.storyDone(def.id),'Legend did not complete');assert(r.s.quests[def.QUEST_ID]?.claimed,'No quest claim receipt');assert.equal(startMora-r.s.global.MORA,Number(def.COST_MORA||0),'Mora cost mismatch');for(const [id,n]of Object.entries(JSON.parse(def.COST_ITEMS_JSON||'{}')))assert.equal(startItems[id]-r.itemCount(id),Number(n),'Item cost mismatch '+id);assert.equal(r.storyBond(def.PROFILE_ID)-startBond,10,'Bond reward mismatch');assert.deepEqual(cp(r.s.party.filter(p=>p.active).map(p=>p.source)),['PLAYER_CUSTOM'],'Autoparty');
 const isArchon=['MOND_VENTI','LIYUE_ZHONGLI'].includes(def.CHAR_ID),preRejoin=snapshot(r);r=reload(r,rec);
 if(!isArchon&&initialOwned!=='JOINED'){assert.notEqual(own(r,def.CHAR_ID),'JOINED','Decline auto-recruited');const entry=r.recruitmentRejoinEntry(def);assert(entry,'Missing rejoin entry');walk(r,entry.map,rec);act(r,'RECRUIT_REJOIN',{quest:def.id},rec);r=run(r,'accept',rec);assert.equal(own(r,def.CHAR_ID),'JOINED','Rejoin did not recruit');assert.equal(r.s.global.MORA,preRejoin.mora,'Rejoin cost charged');for(const [id]of Object.entries(JSON.parse(def.COST_ITEMS_JSON||'{}')))assert.equal(r.itemCount(id),startItems[id]-JSON.parse(def.COST_ITEMS_JSON)[id],'Rejoin item charge');assert.equal(r.storyBond(def.PROFILE_ID),startBond+10,'Rejoin duplicated bond');const before=r.serialize();assert.throws(()=>r.action('RECRUIT_REJOIN',{quest:def.id}),'Second rejoin accepted');assert.equal(r.serialize(),before,'Rejected duplicate rejoin mutated');rec.rejoin=true;}else{assert.equal(own(r,def.CHAR_ID),initialOwned,'Archon/story-owned changed');rec.rejoin='not_applicable';}
 r=reload(r,rec);const before=r.serialize();assert.throws(()=>r.action('LEGEND_ENTER',{quest:def.id}),'Completed legend entered twice');assert.equal(r.serialize(),before,'Rejected repeat legend mutated');rec.passed=true;
 }catch(e){rec.error=e.message;rec.code=e.code;rec.details=e.qa;rec.stack=e.stack?.split('\n').slice(0,6);console.log('FAIL',JSON.stringify(rec));}
 report.results.push(rec);save();if(report.results.length%5===0)console.log('PROGRESS',report.results.length,'passed',report.results.filter(r=>r.passed).length);}
report.summary={total:defs.length,passed:report.results.filter(r=>r.passed).length,failed:report.results.filter(r=>!r.passed).length};save();console.log('DONE',JSON.stringify(report.summary),path);

if(report.summary.failed)process.exitCode=1;
