'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const repo=process.env.CRPG_PROJECT_ROOT||require('node:path').resolve(__dirname,'../..'),db=JSON.parse(fs.readFileSync(repo+'/content/db.json'));
let timer=0;const timers=[],errors=[];
class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.tag=tag;this.className='';this.children=[];this.parentNode=null;this.dataset={};this.attributes={};this.style={setProperty(k,v){this[k]=v}};this._text='';this.value='';this.id='';this.disabled=false;this.open=false;this.isConnected=true;this.scrollTop=0;this.scrollWidth=1000;this.classList={add:(...xs)=>{this.className=[...new Set([...this.className.split(/\s+/).filter(Boolean),...xs])].join(' ')},remove:(...xs)=>{this.className=this.className.split(/\s+/).filter(x=>!xs.includes(x)).join(' ')},contains:x=>this.className.split(/\s+/).includes(x),toggle:(x,b)=>{const v=b===undefined?!this.classList.contains(x):b;v?this.classList.add(x):this.classList.remove(x);return v;}};}
 get textContent(){return this._text+this.children.map(c=>c.textContent??String(c)).join('');}set textContent(s){this.children.forEach(c=>{if(c instanceof Element)c.parentNode=null;});this.children=[];this._text=String(s??'');}
 get firstChild(){return this.children[0]||null}get lastChild(){return this.children.at(-1)||null}get lastElementChild(){return this.children.filter(c=>c instanceof Element).at(-1)||null}get childNodes(){return this.children;}
 detach(c){if(c.parentNode){const p=c.parentNode;p.children=p.children.filter(v=>v!==c);}c.parentNode=this;c.isConnected=true;return c;}
 append(...cs){this.children.push(...cs.map(c=>c instanceof Element?this.detach(c):c));}prepend(...cs){this.children.unshift(...cs.map(c=>c instanceof Element?this.detach(c):c));}appendChild(c){this.append(c);return c;}replaceChildren(...cs){this.textContent='';this.append(...cs);}insertBefore(c,b){const i=this.children.indexOf(b);this.detach(c);this.children.splice(i<0?this.children.length:i,0,c);return c;}
 replaceWith(c){if(!this.parentNode)return;this.parentNode.insertBefore(c,this);this.remove();}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(c=>c!==this);this.parentNode=null;this.isConnected=false;}before(c){this.parentNode?.insertBefore(c,this);}
 setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')this.id=String(v);if(k==='class')this.className=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);}getAttribute(k){return k==='id'?this.id:k==='class'?this.className:this.attributes[k]??null;}removeAttribute(k){delete this.attributes[k];}
 addEventListener(){}removeEventListener(){}focus(){}setPointerCapture(){}scrollIntoView(){}scrollTo(){}click(){this.onclick?.({target:this,preventDefault(){}});}showModal(){this.open=true;}close(){this.open=false;}getBoundingClientRect(){return{top:100,bottom:200,left:0,width:100,height:100};}
 matches(q){q=q.trim();if(q==='*')return true;const attrs=[...q.matchAll(/\[([^\]=]+)(?:=['"]?([^\]'"]+)['"]?)?\]/g)];q=q.replace(/\[[^\]]+\]/g,'');for(const a of attrs){const value=a[1].startsWith('data-')?this.dataset[a[1].slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]:this.getAttribute(a[1])??this[a[1]];if(a[2]!==undefined?String(value)!==a[2]:value===undefined||value===null)return false;}const id=q.match(/#([\w-]+)/)?.[1];if(id&&this.id!==id)return false;for(const [,c]of q.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(c))return false;const tag=q.match(/^[a-zA-Z][\w-]*/)?.[0];return !tag||this.tagName===tag.toUpperCase();}
 querySelectorAll(q){return q.split(',').flatMap(s=>{const parts=s.trim().split(/\s+/);let nodes=[this];for(const part of parts)nodes=nodes.flatMap(n=>walk(n).slice(1).filter(x=>x.matches(part)));return nodes;}).filter((x,i,a)=>a.indexOf(x)===i);}querySelector(q){return this.querySelectorAll(q)[0]||null;}closest(q){let n=this;while(n){if(n.matches(q))return n;n=n.parentNode;}return null;}
}
function walk(n){return[n,...n.children.filter(c=>c instanceof Element).flatMap(walk)]}
const body=new Element('body'),html=new Element('html');html.append(body);
for(const id of ['root','notice','quick-actions','modal','modal-body','modal-close']){const x=new Element(id==='modal'?'dialog':'div');x.id=id;body.append(x);}const wordmark=new Element('a');wordmark.className='wordmark';body.append(wordmark);
const document={body,documentElement:html,hidden:false,createElement:t=>new Element(t),getElementById:id=>walk(html).find(n=>n.id===id)||null,querySelector:q=>html.querySelector(q),querySelectorAll:q=>html.querySelectorAll(q),addEventListener(){},removeEventListener(){}};
const ctx=vm.createContext({console,Date,Math,JSON,URL,Blob,structuredClone,document,HTMLElement:Element,Element,Node:Element,navigator:{},location:{protocol:'file:',href:'file:///ui-test',replace(){}},innerHeight:900,scrollY:0,performance:{now:()=>0},crypto:{getRandomValues:a=>{a.fill(123456);return a;}},localStorage:{getItem(){return null;},setItem(){},removeItem(){}},setTimeout:(fn,ms)=>{timers.push({fn,ms});return++timer;},clearTimeout(){},setInterval:()=>++timer,clearInterval(){},requestAnimationFrame:()=>++timer,cancelAnimationFrame(){},queueMicrotask:fn=>timers.push({fn,ms:0}),matchMedia:()=>({matches:true,addEventListener(){}}),addEventListener(){},removeEventListener(){},fetch:async()=>({ok:false,json:async()=>({})}),Audio:class extends Element{constructor(){super('audio');this.paused=true;}pause(){this.paused=true;}play(){this.paused=false;return Promise.resolve();}},CRPG_DATA:db,CRPG_ASSETS:{},CRPG_MANIFEST:JSON.parse(fs.readFileSync(repo+'/content/asset-manifest.json'))});ctx.Option=class extends Element{constructor(text,value){super('option');this.textContent=text;this.value=value;}};ctx.window=ctx;ctx.globalThis=ctx;
const loaded=[];for(const [,file]of fs.readFileSync(repo+'/source/index.html','utf8').matchAll(/<script src="([^"]+)"/g)){if(['data.js','assets.js'].includes(file))continue;try{vm.runInContext(fs.readFileSync(repo+'/source/'+file,'utf8'),ctx,{filename:file});loaded.push(file);}catch(e){errors.push({stage:'load',file,error:e.stack});break;}}
const run=code=>vm.runInContext(code,ctx),copy=x=>JSON.parse(JSON.stringify(x)),results=[];
function test(name,fn){try{const details=fn();results.push({name,ok:true,details});console.log('PASS',name);}catch(e){results.push({name,ok:false,error:e.stack});console.log('FAIL',name,e.message);}}
function setGame(route='ROUTE_TRAVELER',stage='pre',map='MAP_LIYUE_HARBOR'){
 const r=new ctx.CRPGRuntime.Runtime(db);r.newGame({name:'UI 읽기 전용 검증',route,seed:1234,saveId:'UI-READONLY-'+route+'-'+stage});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,STORY_MENU_POLICY:'',WORLD_TIME:'12:00',SCREEN_MODE:'QUEST'});r.prepareStory();
 if(stage==='post'){
 Object.assign(r.s.flags,{FLAG_TRV_MON_CH2_CLEAR:true,FLAG_ISK_M05_CLEAR:true,FLAG_ISK_MON_PROLOGUE_CLEAR:true,FLAG_ISK_MAIN_UNLOCKED:true,FLAG_TRV_LIYUE_CLEAR:true,FLAG_ISK_L04_REGION_CLEAR:true,FLAG_ACCESS_REGION_LIYUE:true,FLAG_ISK_META_KNOWLEDGE:'UNKNOWN',FLAG_ISK_MOND_BRANCH:'EXPEDITION',FLAG_ISK_EXPEDITION_FORK:'RETURN',FLAG_ISK_A_SUBBRANCH:'AB',FLAG_ISK_L01_LEAF:'AB1',FLAG_ISK_L02_LEAF:'AB1',FLAG_ISK_L03_LEAF:'AB1',FLAG_ISK_L04_LEAF:'AB1',FLAG_TRV_LY_GOLDEN_ROUTE:'B',FLAG_TRV_LY_GOLDEN_EVIDENCE_SENT:true});
 for(const q of ['Q_ISK_MOND_01','Q_ISK_MOND_02','Q_ISK_MOND_03','Q_TRV_MOND_01','Q_TRV_MOND_02','Q_ISK_LIYUE_01','Q_ISK_LIYUE_02','Q_ISK_LIYUE_03','Q_ISK_LIYUE_04','Q_TRV_LIYUE_01','Q_TRV_LIYUE_02','Q_TRV_LIYUE_03','Q_TRV_LIYUE_04'])Object.assign(r.questState(q),{state:'완료',claimed:true,completedTurn:0,acceptedTurn:0});
 const l=r.ensureLiyue();l.access={phase:'OPEN'};
 if(route==='ROUTE_ISEKAI'){const e=r.liyueDefinitions().get('EVT_ISK_L04_AB1_END');const receipt={event:e.EVENT_ID,resolvedNode:e.SOURCE_ID_OR_FILTER,saveId:r.s.global.SAVE_ID,route,quest:e.p.quest_id,branch:'AB',leaf:'AB1',kind:'gate',day:r.s.global.WORLD_DAY,turn:0};l.events[e.EVENT_ID]=receipt;l.regionReceipt=copy(receipt);}
 assert(r.liyuePersonalReady());
 }
 ctx.fixtureGame=r;run('game=fixtureGame;settings.uiTutorialVersion=1;settings.audioEnabled=false;recruitmentRegion="전체";recruitmentOnlyMissing=false;missionTab="동료 획득";');return r;
}
function screen(code){ctx.testPanel=new Element('section');run(code);return ctx.testPanel;}
function plain(p){return p.textContent;}function notBroken(p){assert(!/\b(?:undefined|NaN)\b/.test(plain(p)),plain(p).slice(0,600));assert(plain(p).trim().length>0);}
async function main(){for(let i=0;i<8;i++)await Promise.resolve();if(errors.length)throw Error(JSON.stringify(errors));
 for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI'])for(const stage of ['pre','post'])test(route+' '+stage+' recruitment catalog/red requirements',()=>{
 const r=setGame(route,stage),p=screen('quests(testPanel,game.view())');notBroken(p);const cards=p.querySelectorAll('.acquisition-card');assert.equal(cards.length,43);const entries=r.recruitmentEntries();assert.equal(entries.length,43);assert.equal(entries.filter(e=>e.region==='리월').length,23);const unmet=p.querySelectorAll('.requirement-unmet');assert(unmet.length>0);for(const e of entries){assert(e.name&&e.method);assert(e.requirements.every(q=>q.label));}
 return{cards:cards.length,mond:entries.filter(e=>e.region==='몬드').length,liyue:entries.filter(e=>e.region==='리월').length,redNodes:unmet.length,headers:p.querySelectorAll('h1,h2').map(e=>e.textContent),liyueReady:r.liyuePersonalReady(),sampleRequirements:entries.filter(e=>['LIYUE_ZIBAI','LIYUE_ZHONGLI','MOND_VENTI'].includes(e.character)).map(e=>({id:e.character,requirements:copy(e.requirements)}))};});
 test('catalog filters/collapsed conditions/owned visibility',()=>{const r=setGame();r.unlockCharacter('LIYUE_XINGQIU');run('recruitmentRegion="리월";');let p=screen('recruitmentScreen(testPanel)');assert.equal(p.querySelectorAll('.acquisition-card').length,23);const cards=p.querySelectorAll('.acquisition-card');assert(cards.every(c=>c.querySelector('summary')));assert(cards.filter(c=>!c.textContent.includes('합류 완료')).every(c=>c.querySelector('summary .requirement-unmet')));run('recruitmentOnlyMissing=true;');p=screen('recruitmentScreen(testPanel)');assert.equal(p.querySelectorAll('.acquisition-card').length,22);notBroken(p);return{liyue:23,missing:22,collapsedRedRequirements:true};});
 test('unmet condition CSS is visibly red',()=>{const css=fs.readFileSync(repo+'/source/style.css','utf8');assert(/\.requirement-unmet\{color:#ff9b9b!important\}/.test(css));return{color:'#ff9b9b',important:true};});
 for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI'])test(route+' Liyue guild dialogue + journal entries',()=>{const r=setGame(route,'post');const guild=r.placeEntries().find(e=>e.entity==='NPC_LIYUE_KATHERYNE');assert(guild);r.action('PLACE_ENTER',{place:guild.id,mode:'TALK'});assert(r.atGuild());const p=screen('dialogue(testPanel,game.view())');notBroken(p);assert(/개인 임무|의뢰/.test(plain(p)));const qs=screen('missionTab="개인 임무";quests(testPanel,game.view())');notBroken(qs);return{guildId:guild.id,dialogueText:plain(p).slice(0,1000),journalCards:qs.querySelectorAll('.acquisition-objective').length,unmet:qs.querySelectorAll('.requirement-unmet').length};});
 test('all mission tabs and party acquisition entry render',()=>{setGame('ROUTE_TRAVELER','post');const tabs={};for(const tab of ['진행 중','동료 획득','개인 임무','완료']){ctx.tab=tab;const p=screen('missionTab=tab;quests(testPanel,game.view())');notBroken(p);tabs[tab]={length:plain(p).length,cards:p.querySelectorAll('.card').length};}const p=screen('partyScreen(testPanel)');notBroken(p);assert(p.querySelector('.recruitment-link'));return tabs;});
 for(const [map,label]of [['MAP_LIYUE_JUEYUN','바위 눈동자 공양'],['MAP_LIYUE_MOUNTAINS','지역 이야기 · 귀환 확인'],['MAP_LIYUE_GOLDEN_HOUSE','황금옥의 금빛 실내']])test('location '+map,()=>{const r=setGame('ROUTE_TRAVELER','post',map);r.s.global.SCREEN_MODE='LOCATION';const p=screen('drawLocation(testPanel,game.view())');notBroken(p);if(map==='MAP_LIYUE_GOLDEN_HOUSE'){const s=screen('testPanel.append(scenePanel(game.view()))');assert(s.querySelector('.golden-house-scene'));}else assert(plain(p).includes(label));return{text:plain(p).slice(-1400)};});
 test('real normal battle + Liyue objective/interlude/evacuation rendering',()=>{const r=setGame('ROUTE_TRAVELER','post','MAP_LIYUE_PLAINS');r.s.global.PLAYER_BASE_HP=100000;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;r.startBattle('EG_MOND_SLIME_SMALL','EXPLICIT');assert(r.s.runtime);const outputs={};for(const mode of ['ordinary','objective','interlude','evacuation']){delete r.s.runtime.liyueObjective;delete r.s.runtime.liyueInterlude;delete r.s.runtime.liyueEvacuation;if(mode==='objective')r.s.runtime.liyueObjective={hp:2300,maxHp:3000,charge:3,target:8};if(mode==='interlude')r.s.runtime.liyueInterlude={lines:[{speaker:'페이몬',text:'적의 태세가 변했어!'}]};if(mode==='evacuation')r.s.runtime.liyueEvacuation={completedRounds:2,target:4};const p=screen('combat(testPanel)');notBroken(p);const t=plain(p);if(mode==='objective')assert(t.includes('진법 HP 2300 / 3000 · 충전 3 / 8'));if(mode==='interlude')assert(t.includes('대화를 확인하고 전투 계속'));if(mode==='evacuation')assert(t.includes('완료 라운드 2 / 4'));outputs[mode]={text:t.slice(0,1000),nodes:walk(p).length};}return outputs;});
 test('full production render across four main screens',()=>{const r=setGame('ROUTE_TRAVELER','post','MAP_LIYUE_HARBOR'),out={};for(const mode of ['QUEST','PARTY','LOCATION','SYSTEM']){r.s.global.SCREEN_MODE=mode;run('render()');const p=document.getElementById('root');notBroken(p);out[mode]={characters:plain(p).length,nodes:walk(p).length};}return out;});
 const report={createdAt:new Date().toISOString(),scope:'All current index source scripts loaded in order into mock DOM; DB actual content; browser/media/network APIs mocked; no files or saves in checkout touched',limitations:['DOM mock assertions validate actual app functions, generated structure, condition labels, and absence of runtime exceptions.','No real browser, visual layout, computed style, media loading, IndexedDB persistence, accessibility-tree, or animation-timing validation.','Red requirement styling was checked from actual CSS selector/value; pixel appearance was not assessed.','Main-completion prerequisites are synthetic but satisfy actual runtime receipt validation. Guild entry and ordinary battle creation use actual runtime actions.'],sourceHashes:Object.fromEntries(['source/app_recruitment.js','source/runtime_recruitment.js','source/app_adventure.js','source/runtime_liyue.js','source/runtime_geo_oculi.js','source/style.css','content/db.json'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(repo+'/'+p)).digest('hex')])),loaded,errors,total:results.length,passed:results.filter(x=>x.ok).length,results};fs.writeFileSync('/tmp/recruitment_ui_readonly_results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({total:report.total,passed:report.passed,failures:results.filter(x=>!x.ok)},null,2));if(report.passed!==report.total)process.exitCode=1;
}
main().catch(e=>{fs.writeFileSync('/tmp/recruitment_ui_readonly_results.json',JSON.stringify({loaded,errors,fatal:e.stack},null,2));console.error(e.stack);process.exitCode=1;});
