'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto');
const {c,fs,root,db,R}=require('../helpers_v011.cjs');
const catalog=c.CRPGRelationships.catalogFromDB(db);
c.CRPGRelationships.install(c.CRPGRuntime,{events:catalog,activities:c.CRPGRelationships.activitiesFromDB(db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});
const cp=x=>JSON.parse(JSON.stringify(x));let seq=0;
const path=process.env.QA_REPORT||'/tmp/relationship_305_v013_qa.json';
const report={scope:'305 ordinary H01-H05 scenes: 230 Liyue across both routes,75 new Mond Isekai. Synthetic already-joined, bond, main completion and prior affection prerequisites; actual runtime AFFECTION_ENTER/STORY_NEXT/STORY_CHOICE entry/completion. First and second choice paths where present. Entry/choice/completion save reload and exact last-action replay. No H110/H120 and no checkout writes.',source:root,dbSha256:crypto.createHash('sha256').update(fs.readFileSync(root+'/content/db.json')).digest('hex'),sourceSha256:Object.fromEntries(['runtime_relationships.js','runtime_nodes.js','runtime_recruitment.js'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(root+'/source/'+f)).digest('hex')])),results:[]};
function save(){fs.writeFileSync(path,JSON.stringify(report,null,2));}
function snapshot(r){return cp({cursor:r.storyActiveNodeId(),main:r.s.global.STORY_CURSOR_NODE_ID,context:r.s.storyContext,stack:r.s.storyReturnStack,mora:r.s.global.MORA,inventory:r.s.inventory,bond:r.s.relations,cost:r.s.storyCostReceipts,event:r.s.storyEventReceipts,flags:r.s.flags,companions:r.s.global.COMPANION_ELIGIBILITY_JSON,effects:r.s.global.STORY_NODE_EFFECTS_JSON});}
function reload(r,rec){const before=snapshot(r),rr=new R(db,JSON.parse(r.serialize()));rr.rollEncounter=()=>null;assert.deepEqual(snapshot(rr),before,'Save reload changed cursor/economy/bond/flags/receipts');rec.reloads++;return rr;}
function provision(def){const r=new R(db);r.newGame({name:'QA일상교류',route:def.ROUTE_SCOPE,seed:8844,saveId:'V013-AFFECTION-'+(++seq)});const g=r.s.global,f=r.s.flags;
 Object.assign(g,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:r.storyDefinition(def.id).MAP_ID,STORY_MENU_POLICY:'',STORY_WAITING:true,STORY_NEXT_PREPARED:'',SCREEN_MODE:'LOCATION',WORLD_TIME:'12:00',MORA:100000});
 for(const k of ['storyJourney','storyBreak','storyArrival','storyMenuFrame','storyContext','battlePreparation','storyRecovery'])delete r.s[k];
 Object.assign(f,{FLAG_TRV_MON_CH2_CLEAR:true,FLAG_ISK_M05_CLEAR:true,FLAG_ISK_MON_PROLOGUE_CLEAR:true,FLAG_ISK_MAIN_UNLOCKED:true,FLAG_TRV_LIYUE_CLEAR:true,FLAG_ISK_L04_REGION_CLEAR:true,FLAG_ACCESS_REGION_LIYUE:true,FLAG_MOND_MIKA_RETURNED:true,FLAG_MOND_MONA_PRESENT:true,FLAG_WORLD_ZIBAI_RETURNED:true,FLAG_ISK_META_KNOWLEDGE:'UNKNOWN',FLAG_ISK_MOND_BRANCH:'EXPEDITION',FLAG_ISK_EXPEDITION_FORK:'RETURN',FLAG_ISK_A_SUBBRANCH:'AB',FLAG_ISK_L01_LEAF:'AB1',FLAG_ISK_L02_LEAF:'AB1',FLAG_ISK_L03_LEAF:'AB1',FLAG_ISK_L04_LEAF:'AB1',FLAG_TRV_LY_GOLDEN_ROUTE:'B',FLAG_TRV_LY_GOLDEN_EVIDENCE_SENT:true});
 for(const flag of JSON.parse(def.REQUIRED_FLAGS||'[]'))f[flag]=true;
 for(const q of ['Q_ISK_MOND_01','Q_ISK_MOND_02','Q_ISK_MOND_03','Q_TRV_MOND_01','Q_TRV_MOND_02','Q_ISK_LIYUE_01','Q_ISK_LIYUE_02','Q_ISK_LIYUE_03','Q_ISK_LIYUE_04','Q_TRV_LIYUE_01','Q_TRV_LIYUE_02','Q_TRV_LIYUE_03','Q_TRV_LIYUE_04',def.REQUIRED_QUEST_ID].filter(Boolean))Object.assign(r.questState(q),{state:'완료',claimed:true,completedTurn:0,acceptedTurn:0});
 const l=r.ensureLiyue();l.access={phase:'OPEN'};
 if(def.ROUTE_SCOPE==='ROUTE_ISEKAI'){const e=r.liyueDefinitions().get('EVT_ISK_L04_AB1_END');const receipt={event:e.EVENT_ID,resolvedNode:e.SOURCE_ID_OR_FILTER,saveId:g.SAVE_ID,route:g.STORY_ROUTE_ID,quest:e.p.quest_id,branch:'AB',leaf:'AB1',kind:'gate',day:g.WORLD_DAY,turn:0};l.events[e.EVENT_ID]=receipt;l.regionReceipt=cp(receipt);}
 const char=def.CHAR_ID||r.row('04_CHAR_DB',def.PROFILE_ID)[1];r.unlockCharacter(char);r.markContact(def.PROFILE_ID);r.changeBond(def.PROFILE_ID,Number(def.BOND_SCORE_MIN));
 r.s.storyEventReceipts||={};let prev=def.PREV_EVENT_ID;while(prev){r.s.storyEventReceipts[prev]={turn:0,day:1};const relation=r.relation(def.PROFILE_ID);relation.events[prev]='COMPLETE';relation.events[prev.match(/_(H0[1-5])$/)[1]]='COMPLETE';prev=r.storyDefinition(prev)?.PREV_EVENT_ID;}
 r.rollEncounter=()=>null;r.prepareStory();return r;
}
function act(r,type,p,rec){rec.actions++;if(rec.actions>180)throw Error('ACTION_LIMIT');const g=r.s.global,envelope={id:g.SAVE_ID+':'+(g.LAST_COMMITTED_ACTION_SEQ+1),revision:g.SAVE_REVISION,type,...p};try{const receipt=r.transact(envelope);return {envelope,receipt};}catch(e){e.qa={type,p,node:r.storyActiveNodeId(),context:r.s.storyContext,phase:r.playPhase(),choices:r.storyChoices().map(n=>({id:n[4],label:n[10],condition:n[11],effects:n[12]}))};throw e;}}
function walk(r,target,rec){let guard=0;while(r.s.global.CURRENT_MAP_ID!==target){assert(++guard<35,'map walk loop');let queue=[[r.s.global.CURRENT_MAP_ID,[]]],seen=new Set([r.s.global.CURRENT_MAP_ID]),found;while(queue.length){const [at,edges]=queue.shift();if(at===target){found=edges;break;}for(const e of r.rows('47_MAP_EDGE_DB').filter(e=>e[1]===at&&e[11]==='ACTIVE'&&e[8]==='Y')){if(e[6]&&e[6]!=='FLAG_TRUE'&&!r.storyCondition(e[6]))continue;if(!seen.has(e[2])){seen.add(e[2]);queue.push([e[2],[...edges,e[0]]]);}}}assert(found?.length,'No path to '+target);act(r,'MOVE',{edge:found[0]},rec);}}
function duplicate(r,action,rec){const before=r.serialize(),again=r.transact(action.envelope);assert.deepEqual(cp(again),cp(action.receipt),'Action replay changed receipt');assert.equal(r.serialize(),before,'Action replay changed state');rec.duplicateReplays++;}
function run(def,variant){const rec={variant,actions:0,reloads:0,duplicateReplays:0,choices:[],passed:false};let r=provision(def);const entry=r.storyIndex().nodes.get(def.ROUTE_SCOPE+':'+def.ENTRY_NODE_ID);if(/AFTER_PRIOR_DAILY/.test(entry?.[11]||'')){const activity=r.relationshipActivityEntries().find(a=>a.profileId===def.PROFILE_ID&&!a.reason);assert(activity,'Missing prerequisite daily activity');act(r,'WAIT',{minutes:0},rec);const daily=act(r,'RELATION_ACTIVITY',{activityId:activity.id},rec);duplicate(r,daily,rec);rec.prerequisiteDaily=activity.id;}const before=snapshot(r);assert.equal(r.storyEntryReason(r.storyDefinition(def.id)),'','Entry unavailable with prerequisites');let a=act(r,'AFFECTION_ENTER',{event:def.id},rec);duplicate(r,a,rec);r=reload(r,rec);let guard=0,choiceReload=false,completionReplay=false;
 while(r.s.storyContext&&guard++<90){if(r.s.storyJourney){if(r.s.storyJourney.scripted)act(r,'STORY_SCRIPTED_TRAVEL',{},rec);else{walk(r,r.s.storyJourney.target,rec);act(r,'JOURNEY_RESUME',{},rec);}continue;}if(r.s.storyBreak){act(r,'JOURNEY_RESUME',{},rec);continue;}assert(!r.s.runtime,'Unexpected ordinary scene combat');const cs=r.storyChoices();if(cs.length){let n=cs[Math.min(variant,cs.length-1)];if(!choiceReload){r=reload(r,rec);choiceReload=true;n=r.storyChoices().find(x=>x[4]===n[4]);}rec.choices.push(n[4]);a=act(r,'STORY_CHOICE',{node:n[4]},rec);}else{const n=r.storyNode();assert(n,'No active story node');a=act(r,'STORY_NEXT',{node:n[4]},rec);}
 if(r.storyDone(def.id)){duplicate(r,a,rec);r=reload(r,rec);duplicate(r,a,rec);completionReplay=true;}
 }
 assert(guard<90,'Story loop');assert(r.storyDone(def.id),'Missing story completion');assert.equal(r.relation(def.PROFILE_ID).events[def.id],'COMPLETE','Missing relationship completion');assert.equal(r.relation(def.PROFILE_ID).events[def.id.match(/_(H0[1-5])$/)[1]],'COMPLETE','Missing stage completion');assert(r.s.storyEventReceipts?.[def.id],'Missing completion receipt');assert(completionReplay,'Completion was not transaction-replayed');assert.equal(r.storyBond(def.PROFILE_ID),Number(def.BOND_SCORE_MIN),'Scene changed current bond model');assert.equal(r.s.global.MORA,before.mora,'Scene changed mora');assert.deepEqual(cp(r.s.inventory),before.inventory,'Scene changed inventory');assert.equal(r.s.global.COMPANION_ELIGIBILITY_JSON,before.companions,'Scene changed recruitment');assert.equal(r.s.storyReturnStack.length,0,'Scene left return frame');r=reload(r,rec);const completed=r.serialize();assert.throws(()=>r.action('AFFECTION_ENTER',{event:def.id}),'Completed scene reentered');assert.equal(r.serialize(),completed,'Rejected reentry changed state');rec.passed=true;return rec;
}
const probe=new R(db);probe.newGame({name:'QA색인',route:'ROUTE_TRAVELER',seed:1,saveId:'QA-AFF-INDEX'});
const missing=new Set(['ALBEDO','BARBARA','BENNETT','DIONA','DAHLIA','KAEYA','KLEE','MIKA','MONA','NOELLE','FISCHL','LISA','RAZOR','ROSARIA','SUCROSE']);
const defs=[...probe.storyIndex().affections.values()].filter(d=>d.STATUS==='ACTIVE'&&/H0[1-5]$/.test(d.id)&&(d.id.includes('_LIYUE_')||d.ROUTE_SCOPE==='ROUTE_ISEKAI'&&missing.has(d.PROFILE_ID.replace('PROFILE_MOND_','')))&&(!process.env.QA_IDS||process.env.QA_IDS.split(',').includes(d.id))&&(!process.env.QA_IDS_FILE||JSON.parse(fs.readFileSync(process.env.QA_IDS_FILE)).includes(d.id)));
if(process.env.QA_MOD){const selected=defs.filter((d,i)=>i%Number(process.env.QA_MOD)===Number(process.env.QA_INDEX));defs.splice(0,defs.length,...selected);}console.log('START',defs.length,report.dbSha256);save();
for(const def of defs){const rec={id:def.id,dbSha256:report.dbSha256,route:def.ROUTE_SCOPE,category:catalog[def.id]?.category,paths:[],passed:false};try{for(let v=0;v<2;v++)rec.paths.push(run(def,v));rec.passed=true;}catch(e){rec.error=e.message;rec.code=e.code;rec.details=e.qa;rec.stack=e.stack?.split('\n').slice(0,5);console.log('FAIL',JSON.stringify(rec));}report.results.push(rec);save();if(report.results.length%10===0)console.log('PROGRESS',report.results.length,'passed',report.results.filter(x=>x.passed).length);}
report.summary={total:defs.length,passed:report.results.filter(r=>r.passed).length,failed:report.results.filter(r=>!r.passed).length,paths:report.results.reduce((n,r)=>n+r.paths.filter(p=>p.passed).length,0),unverified:report.results.filter(r=>r.category==='UNVERIFIED').length};save();console.log('DONE',JSON.stringify(report.summary),path);

if(report.summary.failed||report.summary.unverified)process.exitCode=1;
