'use strict';
const {fresh,ctx,db,root}=require('./audit_liyue_cards.cjs');
const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');
const sourceHash=crypto.createHash('sha256').update(fs.readFileSync(root+'/source/runtime_liyue_combat.js')).digest('hex'),tests=[];
const ids=['ECARD_FATUI_CRYO_SPRAY','ECARD_FATUI_CRYO_ARMOR','ECARD_FATUI_PYRO_AIM','ECARD_FATUI_ANEMO_GUARD'];
function ec(r,id){return r.cardDefinition(r.row('12_ENEMY_CARD_DB',id),true);}
function fixture(source='MON_FATUI_CRYO'){
 const f=fresh('LIYUE_BAIZHU',0);const row=f.r.row('09_MONSTER_DB',source);const enemy={id:source+'#TEST',source,name:row[1],side:'ENEMY',control:'AI',hp:1000,maxHp:1000,atk:100,def:0,crit:0,critDmg:50,hit:100,eva:0,level:5,spd:70,range:row[23],resist:0,statuses:[],shields:[],cooldowns:{},turns:0,position:{x:3,y:1},grade:'정예',tags:[],hasDedicatedCards:true};f.b.actors.push(enemy);f.foes=[enemy];f.enemy=enemy;f.target=f.allies[1];f.target.hp=f.target.maxHp=10000;f.target.def=0;return f;
}
function cast(f,id,target){return f.r.executeCard(f.enemy,ec(f.r,id),target||f.target.id);}
const packet=(f,pred=()=>true)=>f.b.log.filter(p=>('damage'in p||'absorbed'in p)&&pred(p));
function test(id,fn){try{tests.push({id,ok:true,evidence:fn()});}catch(e){tests.push({id,ok:false,error:e.message,stack:e.stack});}}
function addBuddy(f){const buddy={...f.enemy,id:'BUDDY',source:'MON_FATUI_PYRO',name:'방벽 동료',hp:500,maxHp:1000,statuses:[],shields:[],cooldowns:{},position:{x:3,y:2}};f.b.actors.push(buddy);return buddy;}
function barrier(t){return t.shields.find(s=>s.source==='ECARD_FATUI_ANEMO_GUARD');}
const retaliations=f=>packet(f,p=>p.actor===f.enemy.name&&p.element==='바람');

test('all_four_cards_supported',()=>{const f=fixture();const result=ids.map(id=>({id,reason:f.r.cardSupport(ec(f.r,id))}));assert(result.every(x=>!x.reason),JSON.stringify(result));return result;});
test('public_patrol_start_is_not_blocked_and_armor_is_visible_before_begin',()=>{const f=fresh();f.r.s.runtime=null;Object.assign(f.r.s.global,{MODE:'NORMAL',ACTIVE_BATTLE_ID:'',SCREEN_MODE:'LOCATION',CURRENT_MAP_ID:'MAP_LIYUE_PLAINS',CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END'});f.r.startBattle('EG_FATUI_PATROL','READONLY_PATROL');const b=f.r.s.runtime;assert(b);const cryo=b.actors.find(a=>a.source==='MON_FATUI_CRYO');assert(cryo);assert.equal(cryo.shields.find(s=>s.source==='ECARD_FATUI_CRYO_ARMOR')?.value,Math.round(cryo.maxHp*.3));return{opening:b.opening?.state,actors:b.actors.map(a=>a.source),armor:cryo.shields};});
test('cryo_spray_three_hits_slow_and_single_aura_application',()=>{const f=fixture();let auraCalls=0;const old=f.r.applyCombatAura;f.r.applyCombatAura=function(a,t,...args){if(a.id===f.enemy.id&&t.id===f.target.id)auraCalls++;return old.call(this,a,t,...args);};cast(f,'ECARD_FATUI_CRYO_SPRAY');const p=packet(f,x=>x.card==='ECARD_FATUI_CRYO_SPRAY');assert.deepEqual(p.map(p=>p.damage),[30,30,30]);assert.equal(auraCalls,1);assert.equal(f.target.statuses.find(s=>s.id==='STATUS_SLOW')?.rounds,1);assert.equal(f.enemy.cooldowns.ECARD_FATUI_CRYO_SPRAY,0);return{damage:p.map(p=>p.damage),auraCalls,slow:f.target.statuses};});
test('cryo_spray_first_miss_preserves_one_later_aura_and_no_slow',()=>{const f=fixture();const rolls=[100,50,50,50,50];f.r.die=()=>rolls.shift()??50;let auraCalls=0;const old=f.r.applyCombatAura;f.r.applyCombatAura=function(a,t,...args){if(a.id===f.enemy.id)auraCalls++;return old.call(this,a,t,...args);};cast(f,'ECARD_FATUI_CRYO_SPRAY');const p=packet(f,x=>x.card==='ECARD_FATUI_CRYO_SPRAY');assert.equal(p.length,2);assert.equal(auraCalls,1);assert(!f.target.statuses.some(s=>s.id==='STATUS_SLOW'));return{damage:p.map(p=>p.damage),auraCalls};});
test('cryo_spray_existing_hydro_reacts_once',()=>{const f=fixture();f.r.setAura(f.target,'물');cast(f,'ECARD_FATUI_CRYO_SPRAY');const rx=f.b.log.filter(p=>p.reactionName);assert.equal(rx.length,1,JSON.stringify(rx));return rx;});
test('cryo_armor30percent_and_pyro2x_only_consumes_shield',()=>{const f=fixture();f.r.newRound();const armor=f.enemy.shields.find(s=>s.source==='ECARD_FATUI_CRYO_ARMOR');assert.equal(armor?.value,300);f.r.applyDamage(f.target,f.enemy,100,{element:'불'});assert.equal(armor.value,100);assert.equal(f.enemy.hp,1000);f.r.applyDamage(f.target,f.enemy,100,{element:'불'});assert.equal(f.enemy.hp,950);assert.equal(f.enemy.shields.length,0);f.b.round++;f.r.newRound();assert.equal(f.enemy.shields.length,0,'Broken combat-start armor regenerated');return{hpAfterTwo100Pyro:950,shields:f.enemy.shields};});
test('cryo_armor_nonpyro_consumes_normally',()=>{const f=fixture();f.r.newRound();f.r.applyDamage(f.target,f.enemy,100,{element:'물리'});assert.equal(f.enemy.shields.find(s=>s.source==='ECARD_FATUI_CRYO_ARMOR')?.value,200);assert.equal(f.enemy.hp,1000);});
test('pyro_aim_damage_and_single15_hit_bonus',()=>{const f=fixture('MON_FATUI_PYRO');const observed=[],old=f.r.damage;f.r.damage=function(a,t,k,e,o={}){observed.push({k,e,range:o.range,hitBonus:o.hitBonus});return old.call(this,a,t,k,e,o);};cast(f,'ECARD_FATUI_PYRO_AIM');assert.equal(packet(f,p=>p.card==='ECARD_FATUI_PYRO_AIM')[0]?.damage,135);assert.equal(observed[0].hitBonus,15);assert.equal(observed[0].range,'원거리');assert.equal(f.enemy.cooldowns.ECARD_FATUI_PYRO_AIM,2);return observed;});
test('anemo_guard_low_hp_same_side_uses_caster18percent',()=>{const f=fixture('MON_FATUI_ANEMO'),buddy=addBuddy(f);cast(f,'ECARD_FATUI_ANEMO_GUARD',buddy.id);assert.equal(barrier(buddy)?.value,180);assert.equal(f.enemy.cooldowns.ECARD_FATUI_ANEMO_GUARD,2);return buddy.shields;});
test('anemo_guard_self_target_allowed',()=>{const f=fixture('MON_FATUI_ANEMO');cast(f,'ECARD_FATUI_ANEMO_GUARD',f.enemy.id);assert.equal(barrier(f.enemy)?.value,180);});
test('anemo_guard_direct_depletion_counters_once',()=>{const f=fixture('MON_FATUI_ANEMO'),buddy=addBuddy(f);cast(f,'ECARD_FATUI_ANEMO_GUARD',buddy.id);f.r.applyDamage(f.target,buddy,200,{element:'물리',card:'AUDIT_DIRECT'});assert.equal(retaliations(f).length,1);assert.equal(retaliations(f)[0].damage,55);f.r.applyDamage(f.target,buddy,20,{element:'물리',card:'AUDIT_DIRECT_2'});assert.equal(retaliations(f).length,1);return retaliations(f);});
test('anemo_guard_partial_hit_does_not_counter',()=>{const f=fixture('MON_FATUI_ANEMO'),buddy=addBuddy(f);cast(f,'ECARD_FATUI_ANEMO_GUARD',buddy.id);f.r.applyDamage(f.target,buddy,179,{element:'물리'});assert.equal(retaliations(f).length,0);assert.equal(barrier(buddy)?.value,1);});
test('anemo_guard_reaction_depletion_does_not_counter',()=>{const f=fixture('MON_FATUI_ANEMO'),buddy=addBuddy(f);cast(f,'ECARD_FATUI_ANEMO_GUARD',buddy.id);f.r.applyDamage(f.target,buddy,200,{element:'불',sourceKind:'REACTION'});assert.equal(retaliations(f).length,0);});
test('anemo_guard_next_caster_turn_disarms_counter',()=>{const f=fixture('MON_FATUI_ANEMO'),buddy=addBuddy(f);cast(f,'ECARD_FATUI_ANEMO_GUARD',buddy.id);f.enemy.turns++;f.r.onCombatTurnStart(f.enemy);f.r.applyDamage(f.target,buddy,200,{element:'물리'});assert.equal(retaliations(f).length,0);});
test('anemo_guard_cannot_select_a_side_where_all_living_units_shielded',()=>{const f=fixture('MON_FATUI_ANEMO');f.r.shield(f.enemy,400,'AUDIT_EXISTING',2);const c=ec(f.r,'ECARD_FATUI_ANEMO_GUARD');assert(f.r.cardReason(f.enemy,c),'Card has no gate when no shieldless teammate exists');});
test('osial_wave_one_cryo_has_armor_and_dedicated_spray',()=>{const f=fixture('MON_FATUI_ANEMO');f.b.actors=f.allies;f.b.storyConfig={liyue:true,route:'ROUTE_TRAVELER',objective:{kind:'PROTECT_FORMATION',formation_hp:3000,formation_def:120,charge_rounds:8,wave_hp_multiplier:.4}};f.r.newRound();const cryo=f.b.actors.find(a=>a.source==='MON_FATUI_CRYO');assert(cryo);assert.equal(cryo.shields.find(s=>s.source==='ECARD_FATUI_CRYO_ARMOR')?.value,Math.round(cryo.maxHp*.3));assert(f.r.actorCards(cryo).some(c=>c.id==='ECARD_FATUI_CRYO_SPRAY'&&!f.r.cardReason(cryo,c)));cryo.siege=false;f.r.aiTurn(cryo,[f.target]);assert(f.b.log.some(p=>p.card==='ECARD_FATUI_CRYO_SPRAY'));return{hp:cryo.maxHp,armor:cryo.shields,spawned:f.b.liyueObjective.spawned};});

test('spray_three_hits_still_obeys_status_resistance_roll',()=>{const f=fixture();f.target.resist=95;const rolls=[50,50,50,50,50,50,99];f.r.die=()=>rolls.shift()??99;cast(f,'ECARD_FATUI_CRYO_SPRAY');assert.equal(packet(f,p=>p.card==='ECARD_FATUI_CRYO_SPRAY').length,3);assert(!f.target.statuses.some(s=>s.id==='STATUS_SLOW'),'SLOW bypassed CE020 resistance roll');});
test('anemo_guard_has_authored_one_round_duration',()=>{const f=fixture('MON_FATUI_ANEMO'),buddy=addBuddy(f);cast(f,'ECARD_FATUI_ANEMO_GUARD',buddy.id);assert.equal(barrier(buddy)?.rounds,1);f.r.roundEnd();assert(barrier(buddy));f.r.roundEnd();assert(!barrier(buddy),'One-round shield did not expire after next round end');});
test('anemo_guard_nested_bubble_depletion_is_not_direct_break',()=>{const f=fixture('MON_FATUI_ANEMO'),buddy=addBuddy(f);cast(f,'ECARD_FATUI_ANEMO_GUARD',buddy.id);f.a.atk=300;f.r.addCombatStatus(buddy,'ILLUSORY_BUBBLE',2,{actor:f.a.id});f.r.applyDamage(f.target,buddy,1,{element:'물리',card:'AUDIT_TINY_DIRECT'});assert.equal(retaliations(f).length,0,'1 damage direct did not deplete180 shield; nested Mona bubble did: '+JSON.stringify(f.b.log));});
test('all_osial_wave_cards_supported_and_spawn_once',()=>{const f=fixture();f.b.actors=f.allies;f.b.storyConfig={liyue:true,route:'ROUTE_TRAVELER',objective:{kind:'PROTECT_FORMATION',formation_hp:3000,formation_def:120,charge_rounds:8,wave_hp_multiplier:.4}};const checked=[];for(const round of[1,3,5,7]){f.b.round=round;f.r.newRound();const count=f.b.actors.length;f.r.newRound();assert.equal(f.b.actors.length,count);for(const a of f.b.actors.filter(x=>x.side==='ENEMY'))for(const row of f.r.combatRows('12_ENEMY_CARD_DB').filter(c=>c[1]===a.source&&c[35]==='READY')){const c=f.r.cardDefinition(row,true);assert.equal(f.r.cardSupport(c),'',c.id);checked.push(c.id);}}assert.equal(f.b.actors.filter(a=>a.side==='ENEMY').length,7);return{spawned:f.b.liyueObjective.spawned,checked:[...new Set(checked)]};});
test('electro_armor30percent_cryo2x_and_no_regeneration',()=>{const f=fixture('MON_FATUI_ELECTRO');f.r.newRound();assert.equal(f.enemy.shields.find(s=>s.source==='ECARD_FATUI_ELECTRO_ARMOR')?.value,300);f.r.applyDamage(f.target,f.enemy,200,{element:'얼음'});assert.equal(f.enemy.hp,950);assert.equal(f.enemy.shields.length,0);f.b.round++;f.r.newRound();assert.equal(f.enemy.shields.length,0);});
test('hydro_heal_uses_target_hp_lowest_ratio_and70percent_gate',()=>{const f=fixture('MON_FATUI_HYDRO'),buddy=addBuddy(f);buddy.maxHp=2000;buddy.hp=600;cast(f,'ECARD_FATUI_HYDRO_HEAL');assert.equal(buddy.hp,1000);assert.equal(f.enemy.cooldowns.ECARD_FATUI_HYDRO_HEAL,2);buddy.hp=1500;f.enemy.cooldowns.ECARD_FATUI_HYDRO_HEAL=0;assert(f.r.cardReason(f.enemy,ec(f.r,'ECARD_FATUI_HYDRO_HEAL')));f.enemy.hp=700;assert.equal(f.r.cardTargets(f.enemy,ec(f.r,'ECARD_FATUI_HYDRO_HEAL'))[0].id,f.enemy.id);});
test('geo_barrier_uses_caster20percent_and_self_allowed',()=>{const f=fixture('MON_FATUI_GEO'),buddy=addBuddy(f);buddy.maxHp=2000;cast(f,'ECARD_FATUI_GEO_BARRIER',buddy.id);assert.equal(buddy.shields.find(s=>s.source==='ECARD_FATUI_GEO_BARRIER')?.value,200);f.enemy.cooldowns.ECARD_FATUI_GEO_BARRIER=0;cast(f,'ECARD_FATUI_GEO_BARRIER',f.enemy.id);assert.equal(f.enemy.shields.find(s=>s.source==='ECARD_FATUI_GEO_BARRIER')?.value,200);});
test('agent_stealth_single_target_evades_aoe_does_not',()=>{const f=fixture('MON_FATUI_AGENT');cast(f,'ECARD_FATUI_AGENT_STEALTH',f.enemy.id);f.target.hit=80;f.r.die=()=>80;assert.equal(f.r.damage(f.target,f.enemy,1,'물리',{card:'PLAYER_BASIC_ATTACK'}),false,'80 roll should miss70 single-target chance');assert.equal(f.r.damage(f.target,f.enemy,1,'물리',{card:'LIYUE_QIQI_Q'}),true,'80 roll should hit90 AoE chance');assert(f.enemy.statuses.some(s=>s.id==='AGENT_STEALTH'),'Receiving attack should not consume stealth');});
test('agent_blade_stealth_bonus_once_and_removed_after_miss',()=>{const f=fixture('MON_FATUI_AGENT');cast(f,'ECARD_FATUI_AGENT_STEALTH',f.enemy.id);cast(f,'ECARD_FATUI_AGENT_BLADE');assert.equal(packet(f,p=>p.card==='ECARD_FATUI_AGENT_BLADE')[0]?.damage,150);assert(!f.enemy.statuses.some(s=>s.id==='AGENT_STEALTH'));f.b.log=[];cast(f,'ECARD_FATUI_AGENT_BLADE');assert.equal(packet(f,p=>p.card==='ECARD_FATUI_AGENT_BLADE')[0]?.damage,120);cast(f,'ECARD_FATUI_AGENT_STEALTH',f.enemy.id);f.r.die=()=>100;cast(f,'ECARD_FATUI_AGENT_BLADE');assert(!f.enemy.statuses.some(s=>s.id==='AGENT_STEALTH'));});
test('agent_stealth_hit_bonus_ten_and_followup_not_consuming',()=>{const f=fixture('MON_FATUI_AGENT');cast(f,'ECARD_FATUI_AGENT_STEALTH',f.enemy.id);f.r.damage(f.enemy,f.target,1,'불',{sourceKind:'FOLLOWUP'});assert(f.enemy.statuses.some(s=>s.id==='AGENT_STEALTH'));f.b.log=[];f.enemy.hit=60;f.r.die=()=>85;cast(f,'ECARD_FATUI_AGENT_BLADE');assert.equal(packet(f,p=>p.card==='ECARD_FATUI_AGENT_BLADE').length,1,'Blade60+base10+card8+stealth10=88 should hit85');});


test('agent_stealth_does_not_amplify_secondary_reaction_packet',()=>{const f=fixture('MON_FATUI_AGENT');cast(f,'ECARD_FATUI_AGENT_STEALTH',f.enemy.id);f.r.setAura(f.target,'번개');cast(f,'ECARD_FATUI_AGENT_BLADE');const reaction=packet(f,p=>p.target===f.target.name&&p.reaction==='RX_OVERLOADED'&&p.sourceKind==='REACTION');assert.equal(reaction.length,1);assert.equal(reaction[0].damage,170,'Reaction should be(25+12*5)*2=170 with no direct-stealth bonus; actual '+reaction[0].damage);return reaction;});
test('sky_ladder_aoe_followup_bypasses_stealth_evasion',()=>{const f=fresh('LIYUE_XIANYUN',2),agent=f.foes[1];agent.source='MON_FATUI_AGENT';agent.position={x:3,y:2};f.foes[0].position={x:3,y:1};f.a.hit=80;f.r.addCombatStatus(agent,'AGENT_STEALTH',null);f.r.executeCard(f.a,f.r.cardDefinition(f.r.row('08_SKILL_CARD_DB','LIYUE_XIANYUN_E')),f.allies[1].id);f.r.die=()=>85;f.r.basicHit(f.allies[1],f.foes[0]);const hit=f.b.log.find(p=>p.actor===f.a.name&&p.target===agent.name&&p.sourceKind==='FOLLOWUP'&&p.damage);assert(hit,'85 should hit90 AoE chance, not use70 stealth-evasion chance: '+JSON.stringify(f.b.log));});


test('agent_stealth_formation_attack_consumes_and_applies_hit_damage_bonus',()=>{const f=fixture('MON_FATUI_AGENT');f.b.liyueObjective={hp:3000,maxHp:3000,def:120,charge:0,target:8,spawned:[],settled:[],waveHp:.4};f.enemy.siege=true;f.enemy.hit=60;cast(f,'ECARD_FATUI_AGENT_STEALTH',f.enemy.id);f.r.random=()=>0;f.r.die=()=>85;f.r.aiTurn(f.enemy,[f.target]);assert(!f.enemy.statuses.some(s=>s.id==='AGENT_STEALTH'));assert.equal(f.b.liyueObjective.hp,2936,'Hit60+formation15+stealth10=85; damage round100*.9/2.2*1.25*1.25=64');});
test('agent_stealth_missed_formation_attack_still_consumes',()=>{const f=fixture('MON_FATUI_AGENT');f.b.liyueObjective={hp:3000,maxHp:3000,def:120,charge:0,target:8,spawned:[],settled:[],waveHp:.4};f.enemy.siege=true;f.enemy.hit=60;cast(f,'ECARD_FATUI_AGENT_STEALTH',f.enemy.id);f.r.random=()=>0;f.r.die=()=>100;f.r.aiTurn(f.enemy,[f.target]);assert(!f.enemy.statuses.some(s=>s.id==='AGENT_STEALTH'));assert.equal(f.b.liyueObjective.hp,3000);});

const report={sourceHash,relatedHashes:Object.fromEntries(['runtime_liyue_combat.js','runtime_liyue_cards.js','runtime_combat.js'].map(name=>[name,crypto.createHash('sha256').update(fs.readFileSync(root+'/source/'+name)).digest('hex')])),total:tests.length,passed:tests.filter(t=>t.ok).length,tests};fs.writeFileSync('/tmp/fatui_cards_readonly_results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.passed<report.total)process.exitCode=1;
