'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
function opt(name,fallback){const at=process.argv.indexOf('--'+name);return at>=0?process.argv[at+1]:fallback;}
const ROOT=path.resolve(opt('root',process.env.CRPG_ROOT||(fs.existsSync('source/index.html')?'.':'game'))),INPUT=path.resolve(opt('fixture',process.env.CRPG_GEO_FIXTURE||path.join(ROOT,'tests/fixtures/geo-collected-v013.json'))),OUT=path.resolve(opt('output',process.env.CRPG_QA_OUTPUT||'/tmp/geo-offerings-zibai-results.json'));
const h=require(path.join(ROOT,'tests/helpers_v011.cjs')),{R,db,c,advance}=h,copy=x=>JSON.parse(JSON.stringify(x)),results=[];
let r=new R(db,JSON.parse(fs.readFileSync(INPUT,'utf8')));
const metadata={root:ROOT,input:INPUT,prerequisites:['Input fixture is a previously executed 16-source Geo collection run, with no offerings.','Traveler Liyue main completion is explicitly injected only before final offering and Zibai checks: FLAG_TRV_LIYUE_CLEAR=true plus Q_TRV_LIYUE_04 claimed=true.','No runtime methods are modified. Movement encounter roll is suppressed on the test instance while using public MOVE actions.','Two Anemo points are collected through actual WORLD_WORK_START/FINISH actions to test currency separation.']};
function test(name,fn){try{const detail=fn()||{};results.push({name,ok:true,...detail});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function reject(type,args){const before=r.serialize();let error;try{r.action(type,args);}catch(e){error=e;}assert(error,type+' should reject');assert.equal(r.serialize(),before,'rejected action changed state');return error.code;}
function reload(){const before=r.serialize();r=new R(db,JSON.parse(before));assert.equal(r.serialize(),before,'valid save roundtrip changed state');}
function move(target){if(r.s.placeVisit)r.action('PLACE_LEAVE');const start=r.s.global.CURRENT_MAP_ID,q=[[start,[]]],seen=new Set([start]);let route;while(q.length){const [map,edges]=q.shift();if(map===target){route=edges;break;}for(const e of r.rows('47_MAP_EDGE_DB').filter(e=>e[1]===map&&e[8]==='Y'&&e[11]==='ACTIVE')){const f=Object.create(r);f.s={...r.s,global:{...r.s.global,CURRENT_MAP_ID:map}};if(f.edgeReason(e)||seen.has(e[2]))continue;seen.add(e[2]);q.push([e[2],[...edges,e[0]]]);}}assert(route,'No route to '+target);for(const edge of route){r.s.global.ENCOUNTER_COOLDOWN=1;r.die=()=>100;r.action('MOVE',{edge});}assert.equal(r.s.global.CURRENT_MAP_ID,target);}
function completeAnemo(id){const p=r.oculusPoint(id);move(p.map);for(let i=0;i<p.steps.length+1&&!r.s.exploration.oculi[id];i++){const s=r.oculusStep(id);r.action('WORLD_WORK_START',{kind:'OCULUS',point:id,...(s.options?{answer:s.answer}:{}),...(s.sequence?{sequence:s.sequence}:{})});if(r.s.worldJob){const j=copy(r.s.worldJob);reload();advance(j.duration);r.action('WORLD_WORK_FINISH',{job:j.id});}}assert(r.s.exploration.oculi[id]);}
function separateSnapshot(){return copy({exploration:r.s.exploration,anemoProgress:r.s.worldProgress.oculi,anemoBalance:r.itemCount('KEY_CRPG_ANEMOCULUS')});}
function setReadyFixture(){r.s.flags.FLAG_TRV_LIYUE_CLEAR=true;r.s.quests.Q_TRV_LIYUE_04={...(r.s.quests.Q_TRV_LIYUE_04||{}),state:'완료',claimed:true,node:'COMPLETE'};assert(r.liyuePersonalReady());}
const GEO='KEY_CRPG_GEOCULUS',ANEMO='KEY_CRPG_ANEMOCULUS';let anemoSnapshot,geoAfterOffers;
test('actual Geo collection fixture loads with all 16 sources and independent empty Anemo ledger',()=>{assert.equal(r.s.global.STORY_ROUTE_ID,'ROUTE_TRAVELER');assert.equal(r.geoOculusSummary().collected,16);assert.equal(r.itemCount(GEO),16);assert.equal(r.s.geoOculi.tiers.length,0);assert.equal(r.itemCount(ANEMO),0);reload();return {summary:r.geoOculusSummary()};});
test('two real Anemo collections leave Geo currency and receipts unchanged',()=>{const geo=copy(r.s.geoOculi);completeAnemo('ANEMO_PLAINS_CART');completeAnemo('ANEMO_WINDRISE_ROOT');assert.equal(r.itemCount(ANEMO),2);assert.equal(r.itemCount(GEO),16);assert.deepEqual(copy(r.s.geoOculi),geo);move('MAP_LIYUE_JUEYUN');anemoSnapshot=separateSnapshot();return {anemo:2,geo:16};});
for(const [tier,cost,remaining]of [['GEO_TIER_1',4,12],['GEO_TIER_2',5,7]])test(tier+' consumes exact cost, grants exact reward, rejects duplicate and restores save',()=>{const before={mora:r.s.global.MORA,book:r.itemCount(tier==='GEO_TIER_1'?'MAT_CHAR_EXP_ADVENTURER':'MAT_CHAR_EXP_HERO'),party:copy(r.s.party)},action={type:'GEO_OCULUS_OFFER',tier,id:r.s.global.SAVE_ID+':'+(r.s.global.LAST_COMMITTED_ACTION_SEQ+1),revision:r.s.global.SAVE_REVISION},receipt=r.transact(action),after=r.serialize();assert.deepEqual(copy(r.transact(action)),copy(receipt));assert.equal(r.serialize(),after,'same exact action replay must be idempotent');assert.equal(r.itemCount(GEO),remaining);assert.equal(r.s.global.MORA-before.mora,tier==='GEO_TIER_1'?400:600);assert.equal(r.itemCount(tier==='GEO_TIER_1'?'MAT_CHAR_EXP_ADVENTURER':'MAT_CHAR_EXP_HERO')-before.book,tier==='GEO_TIER_1'?2:1);assert.deepEqual(copy(r.s.party),before.party);assert.deepEqual(separateSnapshot(),anemoSnapshot);reject('GEO_OCULUS_OFFER',{tier});reload();return {cost,remaining};});
test('final 7-token offering is gated by main completion then joins Zhongli without auto-party',()=>{assert(!r.liyuePersonalReady());reject('GEO_OCULUS_OFFER',{tier:'GEO_TIER_FINAL'});setReadyFixture();const party=copy(r.s.party),mora=r.s.global.MORA;r.action('GEO_OCULUS_OFFER',{tier:'GEO_TIER_FINAL'});assert.equal(r.itemCount(GEO),0);assert.equal(r.s.global.MORA,mora);assert.equal(JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON).LIYUE_ZHONGLI.state,'JOINED');assert(r.s.flags.FLAG_CRPG_ZHONGLI_OCULUS_OWNED);assert.deepEqual(copy(r.s.party),party);assert(!r.s.party.some(p=>p.active&&p.source==='LIYUE_ZHONGLI'));assert.deepEqual(separateSnapshot(),anemoSnapshot);for(const tier of ['GEO_TIER_1','GEO_TIER_2','GEO_TIER_FINAL'])reject('GEO_OCULUS_OFFER',{tier});reload();assert.equal(r.geoExchangeEntry(),null);geoAfterOffers=copy(r.s.geoOculi);return {geoBalance:0,anemoBalance:r.itemCount(ANEMO),owned:'JOINED',autoParty:false};});
test('Anemo offering consumes only Anemo tokens after all Geo offerings',()=>{move('MAP_MOND_WINDRISE');r.action('OCULUS_OFFER',{tier:'TIER_1'});assert.equal(r.itemCount(ANEMO),0);assert.equal(r.itemCount(GEO),0);assert.deepEqual(copy(r.s.geoOculi),geoAfterOffers);reject('OCULUS_OFFER',{tier:'TIER_1'});reload();return {anemoOffering:r.s.exploration.tiers[0].id,geoOfferings:r.s.geoOculi.tiers.length};});
test('Zibai return requires main completion, correct location and a free phase',()=>{move('MAP_LIYUE_MOUNTAINS');const s=copy(r.s);delete r.s.flags.FLAG_TRV_LIYUE_CLEAR;reject('ZIBAI_RETURN_CHECK',{step:0});r.s=s;move('MAP_LIYUE_HARBOR');reject('ZIBAI_RETURN_CHECK',{step:0});move('MAP_LIYUE_MOUNTAINS');const freeState=r.serialize();r.s.global.ENCOUNTER_COOLDOWN=0;r.die=()=>1;r.action('WAIT',{minutes:60});assert(r.s.runtime);reject('ZIBAI_RETURN_CHECK',{step:0});r=new R(db,JSON.parse(freeState));assert.equal(r.actionReason('ZIBAI_RETURN_CHECK',{step:0}),'');assert(!r.s.flags.FLAG_WORLD_ZIBAI_RETURNED);return {location:'MAP_LIYUE_MOUNTAINS',combatOpeningBlocked:true};});
for(let step=0;step<3;step++)test('Zibai return step '+step+' rejects out-of-order input and resumes exactly after reload',()=>{for(const wrong of [-1,step+1,step+2,99,NaN])reject('ZIBAI_RETURN_CHECK',{step:wrong});if(step>0)reject('ZIBAI_RETURN_CHECK',{step:step-1});const party=copy(r.s.party),owned=JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON),out=r.action('ZIBAI_RETURN_CHECK',{step}).result;assert.equal(out.step,step+1);assert.equal(out.complete,step===2);assert.equal(r.s.liyueSideStories.zibai.step,step+1);assert.equal(r.s.liyueSideStories.zibai.visited.length,step+1);assert.deepEqual(copy(r.s.party),party);assert.deepEqual(JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON),owned,'return check must not recruit');if(step<2)assert(!r.s.flags.FLAG_WORLD_ZIBAI_RETURNED);else{assert(r.s.flags.FLAG_WORLD_ZIBAI_RETURNED);assert(r.s.relations.PROFILE_LIYUE_ZIBAI);assert.equal(r.s.liyueSideStories.zibai.completed.saveId,r.s.global.SAVE_ID);}reload();return {nextStep:step+1,completed:step===2};});
test('Zibai completed return cannot replay; full save restores contacts and both oculus ledgers',()=>{for(const step of [0,1,2,3])reject('ZIBAI_RETURN_CHECK',{step});reload();assert.equal(r.s.liyueSideStories.zibai.step,3);assert.equal(r.s.geoOculi.tiers.length,3);assert.equal(r.s.exploration.tiers.length,1);assert(!r.s.party.some(p=>p.active&&p.source==='LIYUE_ZIBAI'));return {visitedSteps:r.s.liyueSideStories.zibai.visited.map(v=>v.step)};});
test('Zibai provenance and malformed progression imports reject with SIDE_STORY_SAVE',()=>{const valid=JSON.parse(r.serialize()),cases=[
 ['route',s=>s.liyueSideStories.zibai.route='ROUTE_ISEKAI'],['saveId',s=>s.liyueSideStories.zibai.saveId='OTHER_SAVE'],
 ['negative step',s=>s.liyueSideStories.zibai.step=-1],['step above limit',s=>s.liyueSideStories.zibai.step=4],['fractional step',s=>s.liyueSideStories.zibai.step=1.5],
 ['visited null',s=>s.liyueSideStories.zibai.visited=null],['visited missing record',s=>s.liyueSideStories.zibai.visited.pop()],['visited null record',s=>s.liyueSideStories.zibai.visited[0]=null],
 ['visited step order',s=>s.liyueSideStories.zibai.visited[0].step=2],['visited wrong map',s=>s.liyueSideStories.zibai.visited[0].map='MAP_LIYUE_HARBOR'],
 ['visited day below zero',s=>s.liyueSideStories.zibai.visited[0].day=0],['visited future day',s=>s.liyueSideStories.zibai.visited[0].day=s.global.WORLD_DAY+1],
 ['visited negative turn',s=>s.liyueSideStories.zibai.visited[0].turn=-1],['visited future turn',s=>s.liyueSideStories.zibai.visited[0].turn=s.global.TURN+1],['visited fractional turn',s=>s.liyueSideStories.zibai.visited[0].turn=.5],
 ['completion route',s=>s.liyueSideStories.zibai.completed.route='ROUTE_ISEKAI'],['completion saveId',s=>s.liyueSideStories.zibai.completed.saveId='OTHER_SAVE'],['completion flag missing',s=>s.flags.FLAG_WORLD_ZIBAI_RETURNED=false]];
 const details=[];for(const [name,mutate]of cases){const input=copy(valid);mutate(input);let error;try{new R(db,input);}catch(e){error=e;}details.push({name,code:error?.code||error?.name,message:error?.message});}const wrong=details.filter(e=>e.code!=='SIDE_STORY_SAVE');if(wrong.length)throw Error('Unexpected invalid-save handling: '+JSON.stringify(wrong));reload();return {rejected:details.length,cases:details};});
const report={...metadata,total:results.length,passed:results.filter(x=>x.ok).length,results};fs.writeFileSync(OUT,JSON.stringify(report,null,2));console.log(JSON.stringify({total:report.total,passed:report.passed,output:OUT}));if(report.passed!==report.total)process.exitCode=1;
