/* Growth screens use the same previews and reason strings as authoritative actions. */
(function(){
'use strict';
const fmt=n=>Number(n||0).toLocaleString('ko-KR'),name=id=>safeName('14_ITEM_DB',id);
function costs(box,cost){const list=el('ul','growth-costs');list.append(el('li',game.s.global.MORA<cost.mora?'lack':'','모라 '+fmt(game.s.global.MORA)+' / '+fmt(cost.mora)));for(const [id,n]of Object.entries(cost.items))list.append(el('li',game.itemCount(id)<n?'lack':'',name(id)+' '+game.itemCount(id)+' / '+n));box.append(list);}
function close(){document.getElementById('modal').close();}
window.openCharacterAscension=function(owner='PLAYER_CUSTOM'){const d=game.ascensionInfo(owner),box=el('div','growth-dialog');box.append(el('p','',d.name+' · Lv. '+d.level+' / '+d.cap),el('h3','','돌파 후 Lv. '+d.nextCap+'까지 성장'),el('p','','돌파 단계 '+d.phase+' → '+Math.min(6,d.phase+1)+' · 능력치와 특성 상한 증가'),el('p','',d.gate.label+' · '+(d.gate.ready?'완료':'미완료')));costs(box,d.cost);if(d.reason)box.append(el('p','choice-note',d.reason));const why=game.actionReason('CHAR_ASCEND',{owner});box.append(button('캐릭터 돌파',()=>{close();act('CHAR_ASCEND',{owner});},busy||!!why,true));showModal('캐릭터 돌파 · '+d.name,box);};
window.openCharacterTalent=function(owner='PLAYER_CUSTOM'){const box=el('div','growth-dialog');for(const [kind,label]of [['na','일반 공격'],['e','원소전투 스킬'],['q','원소폭발']]){const d=game.talentUpgradeInfo(owner,kind),card=el('section','card');card.append(el('h3','',label+' · Lv. '+d.level+' / '+d.cap));costs(card,d.cost);if(d.reason)card.append(el('p','choice-note',d.reason));card.append(button('특성 강화',()=>{close();act('TALENT_UPGRADE',{owner,kind});},busy||!!game.actionReason('TALENT_UPGRADE',{owner,kind}),true));box.append(card);}showModal('특성 강화 · '+game.growth(owner).name,box);};
const priorGrowth=growthScreen;growthScreen=function(p,...args){priorGrowth(p,...args);for(const card of p.querySelectorAll('.gear-member[data-owner]')){const owner=card.dataset.owner,g=game.growth(owner),line=el('div','growth-controls');line.append(el('small','','Lv. '+g.level+' / '+g.cap+' · 돌파 '+g.phase+' / 6'),button('캐릭터 돌파',()=>openCharacterAscension(owner)),button('특성 강화',()=>openCharacterTalent(owner)));card.append(line);}};
window.openGrowthDomain=function(selected){const entries=game.growthDomainEntries(),box=el('div','domain-picker');if(!entries.length){box.append(el('p','','몬드성이나 리월항의 비경 입구로 이동해 주세요.'));showModal('성장 비경',box);return;}
 const kind=el('select'),level=el('select'),element=el('select'),preview=el('section','domain-preview'),party=el('p','domain-party');kind.setAttribute('aria-label','비경 종류');level.setAttribute('aria-label','비경 단계');element.setAttribute('aria-label','돌파 원소');
 for(const [id,label]of [['EXP','경험치'],['ASCENSION','돌파'],['TALENT','특성'],['GEAR','장비']])kind.append(new Option(label+' 비경',id));for(const l of [...new Set(entries.map(d=>d.level))])level.append(new Option('Lv. '+l,String(l)));for(const [ko,[id]]of Object.entries(CRPGRuntime.growthV01522.gems))element.append(new Option(ko==='물리'?'주인공 돌파 재료':ko+' 원소',id));
 if(selected){const [k,l]=selected.split(':');kind.value=k;level.value=l;}
 const enter=button('비경 입장',()=>{const params={domain:kind.value+':'+level.value,element:element.value};close();act('DOMAIN_START',params);},false,true);enter.dataset.tutorial='domain-enter';
 const draw=()=>{const d=entries.find(x=>x.id===kind.value+':'+level.value),rw=game.growthDomainRewards(d,element.value),group=game.growthDomainGroup(d,element.value),members=game.rows('49_ENCOUNTER_MEMBER_DB').filter(x=>x[1]===group);element.hidden=kind.value!=='ASCENSION';preview.replaceChildren(el('h3','',d.name+' · 고정 Lv. '+d.level),el('p','','적: '+members.map(m=>safeName('09_MONSTER_DB',m[3])+' '+m[4]+(m[4]!==m[5]?'–'+m[5]:'')+'마리').join(' · ')),el('p','','승리 재료: '+Object.entries(rw.items).map(([id,n])=>name(id)+' ×'+n).join(' · ')),el('p','','추가 모라 '+fmt(rw.mora)+' · 전투 경험치와 전리품 별도'),el('p','',rw.bonus?'오늘 첫 3승 재료·추가 모라 2배 · '+rw.remaining+'회 남음':'오늘의 추가 보상 완료 · 기본 보상으로 계속 도전 가능'));if(d.reason)preview.append(el('p','choice-note',d.reason));enter.disabled=busy||!!game.actionReason('DOMAIN_START',{domain:d.id});party.textContent='출전: '+game.s.party.filter(x=>x.active).map(x=>game.growth(x.source).name+' Lv.'+game.growth(x.source).level).join(' · ');};
 kind.onchange=level.onchange=element.onchange=draw;box.append(el('p','','종류·단계를 고르고 편성을 확인하세요. 적 레벨과 수는 파티를 따라 오르지 않습니다.'),kind,level,element,preview,party,button('편성·프리셋 바꾸기',()=>{close();act('MENU',{screen:'PARTY'});}),enter);draw();showModal('성장 비경 준비',box);};
const priorLocation=drawLocation;drawLocation=function(p,...a){priorLocation(p,...a);if(game.s.placeVisit||game.s.runtime)return;const entries=game.growthDomainEntries();if(entries.length){const box=el('section','card growth-domains');box.append(el('h2','','성장 비경'),el('p','','경험치 · 돌파 · 특성 · 장비 · 하루 첫 3승 추가 보상'),button('비경 종류·단계 선택',()=>openGrowthDomain(),busy,true));p.append(box);}const elite=game.growthEliteEntry();if(elite){const box=el('section','card growth-elite');box.append(el('h2','','지역 정예 토벌 · Lv. '+elite.level),el('p','',elite.reason||'한국 시간 하루 한 번 승리 보상'),actionButton('정예 토벌','ELITE_START',{},true));p.append(box);}};
const priorReward=reward;reward=function(p,...a){priorReward(p,...a);const last=game.s.lastGrowthDomain,r=parseUI(game.s.global.LAST_BATTLE_RESULT_JSON);if(!last||r.origin!=='DOMAIN:'+last.domain)return;const box=el('section','domain-retry');if(r.domain)box.append(el('p','','비경 재료 지급 완료'+(r.domain.bonus?' · 오늘의 2배 보상':'')));box.append(actionButton('같은 비경 다시 도전','DOMAIN_START',{domain:last.domain,element:last.element},true),button('편성·육성 후 도전',()=>act('MENU',{screen:'PARTY'})));p.append(box);};
})();
