/* Online actions commit on the server before combat playback. Local journeys stay separate. */
(function(){
'use strict';
const key='crpg-online-session-v1',pendingKey='crpg-online-pending-v1',base=String(window.CRPG_ONLINE_CONFIG?.apiBase||'').replace(/\/$/,'');
let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}');}catch{}
const O=window.CRPGOnline={account:saved.account||null,token:saved.token||'',revision:0,ranked:false,active:false,configured:!!base,pending:null};
try{O.pending=JSON.parse(localStorage.getItem(pendingKey)||'null');}catch{}
const persist=()=>localStorage.setItem(key,JSON.stringify({account:O.account,token:O.token}));
async function request(path,data){if(!base)throw Error('계정 서버 연결 준비 중입니다. 기존 자동저장 여정은 계속 이용할 수 있습니다.');const res=await fetch(base+path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(O.token?{Authorization:'Bearer '+O.token}:{})},...(data===undefined?{}:{body:JSON.stringify(data)}),cache:'no-store'});let out;try{out=await res.json();}catch{throw Error('계정 서버 응답을 확인하지 못했습니다. 연결 후 다시 시도해 주세요.');}if(!res.ok)throw Object.assign(Error(out.error||'요청을 완료하지 못했습니다.'),{status:res.status});return out;}
function install(out){O.account=out.account;O.revision=out.revision||0;O.ranked=out.ranked===true;O.active=!!out.state;if(out.state){game=new Runtime(DB,out.state);activeSaveSlot=null;applySettings();restoreUIState();sceneHistory.length=0;}persist();return out;}
O.sync=async()=>{const out=await request('/me');install(out);if(!out.state)game=null;render();return out;};
O.execute=async(type,params)=>{
 if(!O.active){const before=game.serialize();try{const result=game.action(type,params);await storeSave();return result;}catch(e){game=new Runtime(DB,JSON.parse(before));throw e;}}
 let p=O.pending;if(p&&p.account!==O.account.id)throw Error('다른 계정의 미확정 행동이 있습니다. 해당 계정으로 로그인해 주세요.');
 if(!p){p={account:O.account.id,requestId:crypto.randomUUID(),revision:O.revision,version:MANIFEST.appVersion,type,params};localStorage.setItem(pendingKey,JSON.stringify(p));O.pending=p;}
 try{const out=await request('/game/action',p);install(out);localStorage.removeItem(pendingKey);O.pending=null;return out.result;}catch(e){if(e.status&&e.status<500&&e.status!==429){O.pending=null;localStorage.removeItem(pendingKey);if(e.status===409)await O.sync();}throw e;}
};
const originalStore=storeSave;storeSave=function(){if(O.active){saveFailed=false;lastSaveError='';updateQuick();return Promise.resolve({revision:O.revision});}return originalStore();};
storeStoryCheckpoint=async()=>{};
manualSave=()=>say('모든 행동은 자동저장됩니다.');
loadFile=()=>say('저장 파일 가져오기는 공식 여정에서 지원하지 않습니다.');
function field(p,label,type='text',value=''){const l=el('label','form-label',label),input=el('input');input.type=type;input.value=value;l.append(input);p.append(l);return input;}
function select(p,label,rows){const l=el('label','form-label',label),s=el('select');for(const [id,name]of rows){const o=el('option','',name);o.value=id;s.append(o);}l.append(s);p.append(l);return s;}
async function safely(task){if(busy)return;busy=true;render();try{await task();say('');}catch(e){say(e.message);}finally{busy=false;render();}}
function auth(signup=false){
 const p=el('form','account-form'),banner=el('div','account-banner'),img=el('img');img.src=assetPath('bg_mondstadt_windrise_day.png')||assetPath('bg_mondstadt_city_day.png');img.alt='';banner.append(img,el('span','','✦  '+(signup?'새로운 인연의 시작':'다시, 모험 속으로')));p.append(banner);
 p.append(el('p','account-intro',signup?'당신의 여정을 담을 계정을 만드세요. 외부 인증은 필요하지 않습니다.':'아이디와 비밀번호를 입력하고, 함께하던 여정을 이어가세요.'));
 if(!base)p.append(el('p','account-service-note','계정 서비스 준비 중입니다. 기기 여정은 지금 바로 플레이할 수 있습니다.'));
 const u=field(p,'아이디'),pw=field(p,'비밀번호','password');u.autocomplete='username';u.autocapitalize='none';u.spellcheck=false;u.minLength=3;u.maxLength=24;u.required=true;u.placeholder='아이디를 입력하세요';pw.autocomplete=signup?'new-password':'current-password';pw.minLength=8;pw.maxLength=128;pw.required=true;pw.placeholder=signup?'8자 이상 입력하세요':'비밀번호를 입력하세요';
 const confirm=signup?field(p,'비밀번호 확인','password'):null;if(confirm){confirm.autocomplete='new-password';confirm.required=true;confirm.placeholder='비밀번호를 한 번 더 입력하세요';}
 const status=el('p','account-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');p.append(status);
 const b=button(signup?'계정 만들고 모험하기':'로그인하고 이어가기',()=>{},!base,true);b.type='submit';p.append(b);
 const switcher=button(signup?'이미 계정이 있나요? 로그인':'처음 오셨나요? 계정 만들기',()=>auth(!signup));switcher.type='button';switcher.className='account-switch';p.append(switcher);
 p.onsubmit=async e=>{e.preventDefault();if(busy)return;if(confirm&&confirm.value!==pw.value){status.textContent='비밀번호가 서로 다릅니다.';return;}busy=true;b.disabled=true;status.textContent='연결하고 있습니다…';try{const out=await request(signup?'/register':'/login',{username:u.value,password:pw.value});pw.value='';if(confirm)confirm.value='';O.token=out.token;O.account=out.account;persist();await O.sync();document.getElementById('modal').close();say('');}catch(err){status.textContent=err.message;}finally{busy=false;b.disabled=!base;render();}};
 showModal(signup?'회원가입':'로그인',p);
}
function accountPanel(){const p=el('div');if(!O.account){auth();return;}p.append(el('p','',O.account.username+' · '+(O.account.admin?'운영자':'모험가')),el('small','', '계정 ID: '+O.account.id));p.append(button('로그아웃',()=>safely(async()=>{if(O.pending)throw Error('미확정 행동을 먼저 서버와 동기화해 주세요.');await request('/logout',{});O.token='';O.account=null;O.active=false;game=null;persist();document.getElementById('modal').close();})));p.append(button('계정 삭제',()=>{const box=el('div');box.append(el('p','','계정, 자동저장, 랭킹 기록이 영구 삭제됩니다. 복구할 수 없습니다.'));const user=field(box,'삭제할 아이디'),password=field(box,'비밀번호','password');password.autocomplete='current-password';box.append(button('계정과 기록 영구 삭제',()=>safely(async()=>{await request('/account/delete',{confirm:user.value,password:password.value});O.token='';O.account=null;O.active=false;O.pending=null;localStorage.removeItem(pendingKey);persist();game=null;document.getElementById('modal').close();}),false,true));showModal('계정 삭제 확인',box);}));showModal('계정 관리',p);}
async function ranking(){const p=el('div');p.append(el('p','','최고 정복 층 → 누적 소요 라운드 → 입장 횟수 순으로 1~20위만 표시합니다. 운영 도구를 사용한 여정은 집계하지 않습니다.'));showModal('나선비경 · 상위 20위',p);try{const out=await request('/ranking');if(!out.entries.length)p.append(el('p','muted','아직 등록된 정복 기록이 없습니다.'));const table=el('table','ranking-table');const head=el('tr');for(const x of ['순위','모험가','층','라운드','입장'])head.append(el('th','',x));table.append(head);for(const x of out.entries.slice(0,20)){const tr=el('tr');for(const v of [x.rank,x.name,x.floor,x.rounds,x.attempts])tr.append(el('td','',String(v)));table.append(tr);}p.append(table);}catch(e){p.append(el('p','muted',e.message));}}
function abyss(){if(!game)return;const p=el('div','abyss-list'),v=game.abyssView();p.append(el('p','','네 명의 파티로 도전합니다. 4~12층은 입장 순간 동료에게 해당 층의 출전 딱지가 붙습니다. 같은 층 재도전은 가능하며 주인공은 딱지에서 제외됩니다.'));p.append(el('p','muted',O.active&&O.ranked?'공식 랭킹 집계 중':'연습 기록 · 공식 랭킹 집계 제외'));for(const f of v.floors){const c=el('section','card');c.append(el('h2','',f.floor+'층 · '+f.name),el('p','', '권장 Lv. '+f.level+' · 제한 '+f.roundLimit+'라운드'+(f.cleared?' · 정복':'')));const b=button(f.cleared?'다시 도전':'입장',async()=>{document.getElementById('modal').close();await act('ABYSS_ENTER',{floor:f.floor});},!!f.reason);b.title=f.reason;c.append(b);if(f.reason)c.append(el('small','muted',f.reason));if(f.cleared&&!f.claimed){if(f.floor===12)c.append(button('이나즈마 성유물 받기',async()=>{await act('ABYSS_REWARD',{floor:12});abyss();}));else{const s=select(c,'첫 정복 보상',CRPGRuntime.abyssConfig.rewards.map(id=>[id,safeName('16_EQUIP_DB',id)]));c.append(button('선택한 장비 받기',async()=>{await act('ABYSS_REWARD',{floor:f.floor,equipment:s.value});abyss();}));}}p.append(c);}
 const tags=Object.entries(v.progress.tags);if(tags.length)p.append(el('p','',tags.map(([id,n])=>safeName('07_CHAR_DB',id)+': '+n+'층').join(' · ')));p.append(button('도전 초기화',()=>{const box=el('div');box.append(el('p','','이번 도전의 층 진행과 동료 딱지가 모두 초기화됩니다. 이미 받은 첫 정복 보상은 다시 받을 수 없습니다. 최고 랭킹 기록은 유지됩니다.'));box.append(button('초기화 확정',async()=>{await act('ABYSS_RESET',{confirm:true});abyss();},false,true));showModal('도전 초기화',box);}));showModal('나선비경',p);}
function debug(){if(!O.active||O.account?.admin!==true){say('운영자 계정으로 로그인해 주세요.');return;}const p=el('div','operator-tools');p.append(el('p','','도구를 한 번이라도 사용한 여정은 영구적으로 랭킹에서 제외됩니다.'));const run=async params=>{await act('OPERATOR_DEBUG',params);debug();};const lv=field(p,'전체 레벨 (1~20)','number','20');p.append(button('레벨 적용',()=>run({op:'level',value:Number(lv.value)})),button('전체 회복',()=>run({op:'heal'})),button('모든 동료 해금',()=>run({op:'recruit',char:'ALL'})));const mora=field(p,'모라 (0~10,000,000)','number','1000000');p.append(button('모라 적용',()=>run({op:'mora',value:Number(mora.value)})));const maps=select(p,'이동 위치',game.rows('32_MAP_DB').filter(x=>x[0]).map(x=>[x[0],x[2]||x[0]]));p.append(button('자유행동으로 이동',()=>run({op:'travel',map:maps.value})));const gear=select(p,'지급 장비',game.rows('16_EQUIP_DB').filter(x=>x[0]).map(x=>[x[0],x[1]]));const enh=field(p,'강화 (0~12)','number','10');p.append(button('장비 지급',()=>run({op:'equipment',equipment:gear.value,value:Number(enh.value)})),button('성유물 10개 생성',()=>run({op:'artifact',value:10})));const floor=field(p,'시험할 나선비경 층 (1~12)','number','1');p.append(button('앞선 층 정복 처리',()=>run({op:'abyss_unlock',value:Number(floor.value)})));const node=field(p,'메인 스토리 장면 ID');p.append(button('장면으로 이동',()=>run({op:'story',node:node.value})));if(game.s.runtime)p.append(button('현재 전투 승리 처리',()=>run({op:'battle_end',win:true})),button('현재 전투 패배 처리',()=>run({op:'battle_end',win:false})));showModal('운영자 디버그',p);}
const localBegin=begin;begin=async function(name,route){if(O.account&&O.token){await safely(async()=>{const out=await request('/game/new',{name,route});install(out);});return;}await localBegin(name,route);};
const localLoad=loadSlot;loadSlot=async function(id){O.active=false;await localLoad(id);};
async function latestLocal(){if(!saveStore)return null;const list=await saveStore.list();return list.filter(x=>!['checkpoint:','test:'].some(prefix=>String(x.slotId||x.id).startsWith(prefix))).sort((a,b)=>new Date(b.updatedAt||b.savedAt)-new Date(a.updatedAt||a.savedAt))[0];}
setup=function(){
 const wrap=el('section','online-hub'),hero=el('div','hub-hero'),photo=el('img','hub-landscape');
 photo.src=assetPath('bg_mondstadt_windrise_day.png')||assetPath('bg_mondstadt_city_day.png');photo.alt='푸른 하늘 아래 펼쳐진 초원과 커다란 나무';photo.fetchPriority='high';hero.append(photo);
 const copy=el('div','hub-hero-copy');copy.append(el('span','hub-mark','✦'),el('div','eyebrow','GENSHIN CRPG'),el('h1','','낯선 세계,\n당신의 이야기.'),el('p','hub-intro','바람이 이끄는 초원에서 바위의 나라까지.\n동료를 만나고, 당신만의 길을 선택하세요.'),el('p','hub-worlds','몬드  ·  리월  ·  나선비경'));hero.append(copy);
 const card=el('div','hub-card');card.append(el('div','eyebrow','YOUR ADVENTURE'),el('h2','','모험을 이어갈까요?'),el('p','hub-lead','다음 이야기가 당신을 기다립니다.'));
 const controls=el('div','hub-account-actions');if(O.account)controls.append(button('계정 여정 이어가기',()=>safely(()=>O.sync()),false,true),button('계정 관리',accountPanel));else controls.append(button('로그인',()=>auth(),false,true),button('회원가입',()=>auth(true)));card.append(controls);
 if(!base)card.append(el('p','hub-service-note','계정 서비스 준비 중 · 지금은 기기 여정으로 시작하세요.'));
 const local=el('section','hub-local');local.append(el('div','hub-divider','이 기기의 여정'));
 const cont=button('자동저장 확인 중…',()=>{},true);cont.className='hub-continue';local.append(cont);
 const f=el('details','hub-new');f.append(el('summary','','새 여정 시작'));
 const form=el('form'),name=field(form,'주인공 이름');name.maxLength=24;name.required=true;name.placeholder='어떤 이름으로 불릴까요?';name.autocomplete='off';
 const route=select(form,'출발할 이야기',['ROUTE_ISEKAI','ROUTE_TRAVELER'].map(id=>[id,routeName(id)]));const start=button(O.account?'새 계정 여정 시작':'모험 시작하기',()=>{},false,true);start.type='submit';form.append(start,el('small','hub-save-note','진행은 행동마다 자동저장됩니다. 기기 여정은 공식 랭킹에 등록되지 않습니다.'));form.onsubmit=e=>{e.preventDefault();begin(name.value,route.value);};f.append(form);local.append(f);card.append(local);
 latestLocal().then(rec=>{if(!cont.isConnected)return;if(rec){cont.textContent='이어서 모험하기 →';cont.disabled=false;cont.onclick=()=>loadSlot(rec.slotId||rec.id);}else{cont.textContent='아직 저장된 여정이 없어요';f.open=true;}}).catch(()=>{cont.textContent='자동저장소를 열지 못했습니다.';});
 const footer=el('div','hub-footer');footer.append(button('나선비경 랭킹 ↗',ranking),el('span','','선택하고, 탐험하고, 함께 싸우세요.'));card.append(footer);wrap.append(hero,card);root.append(wrap);
};
const onlineQuick=updateQuick;updateQuick=function(){onlineQuick();for(const b of document.querySelectorAll('#quick-actions button'))if(b.textContent==='저장')b.textContent='자동저장·계정';};
system=function(p){p.append(el('h1','','자동저장·계정'),el('p','',O.active?'모든 행동이 서버에 확정된 뒤 진행됩니다.':'모든 행동이 이 기기에 자동저장됩니다. 공식 랭킹은 계정 여정에서 이용할 수 있습니다.'));p.append(button('제목 화면',fresh),button('상위 20위',ranking),button(O.account?'계정 관리':'로그인',()=>O.account?accountPanel():auth()));if(O.active)p.append(button('서버 기록 동기화',()=>safely(async()=>{if(O.pending)await O.execute(O.pending.type,O.pending.params);else await O.sync();})));if(O.active&&O.account?.admin)p.append(button('운영자 디버그',debug));p.append(el('h2','','표시 설정'));settingsControls(p);};
const side=sidebar;sidebar=function(...args){const out=side(...args),nav=out.querySelector('nav');const sys=out.querySelector('[data-screen="SYSTEM"]');if(sys)sys.lastChild.textContent='자동저장·계정';nav?.append(button('나선비경',abyss,!!game.s.runtime));if(O.active&&O.account?.admin)nav?.append(button('디버그',debug));return out;};
// Cached scripts can finish after the asynchronous save-store boot has rendered.
// Refresh once all final hub overrides are installed, regardless of that ordering.
render();
if(new URLSearchParams(location.search).get('view')==='ranking')ranking();
})();
