/* A situation-led lesson. Only real successful actions advance it; opening/closing the guide grants nothing. */
(function(root){
'use strict';const api=root.CRPGRuntime,P=api.Runtime.prototype,copy=x=>JSON.parse(JSON.stringify(x)),old=Object.fromEntries(['newGame','validateSave','apply','finishBattle','actionReason'].map(k=>[k,P[k]]));
const fail=m=>{throw new api.RuleError('TUTORIAL',m);};
P.tutorialState=function(){return this.s.tutorialV2??={version:2,enabled:false,done:{}};};
P.tutorialDirective=function(){
 const t=this.tutorialState(),d=t.done,g=this.s.global,b=this.s.runtime,phase=this.playPhase();const learned=this.s.learningGuide?.done||{};if(!t.enabled)return null;
 if(b?.tutorialDrill)return {id:b.tutorialDrill.step,title:{guard:'먼저 한 번 방어하세요',attack:'적을 골라 일반 공격을 실행하세요',skill:'원소전투 스킬을 실행하세요',win:'남은 적을 쓰러뜨리세요'}[b.tutorialDrill.step],text:b.opening?.state==='PENDING'?'훈련 전투를 시작하세요. 다음 차례마다 필요한 조작을 안내합니다.':'행동을 고르고 적 카드를 눌러 대상을 정한 뒤 실행하세요.',battle:true};
 if(b)return {id:'fight',title:b.growthDomain?'비경의 적을 쓰러뜨리세요':'적의 행동을 살피며 전투하세요',text:'부착 원소와 재사용 대기 시간을 확인하세요. 승리하면 보상이 자동으로 지급됩니다.',battle:true};
 if(phase!=='FREE')return {id:'story',title:'현재 이야기를 마치세요',text:'대화와 선택을 마치면 다음 실습을 시작합니다.',screen:'STORY'};
 const journey=this.s.storyJourney;if(journey){const here=this.row('32_MAP_DB',g.CURRENT_MAP_ID)[2],there=this.row('32_MAP_DB',journey.target)[2];if(g.CURRENT_MAP_ID===journey.target)return {id:'arrival',title:there+'에 도착했습니다',text:'이동을 마쳤습니다. 이곳에서 기다리는 이야기를 이어가세요.',command:'resume'};if(journey.scripted||journey.special)return {id:'storyTravel',title:there+'(으)로 이동하세요',text:'이번 이야기는 안내된 이동 수단을 이용합니다. 이동 버튼을 눌러 출발하세요.',command:journey.scripted?'scripted':'ride'};return {id:d.move?'journey':'move',title:d.move?there+'까지 길을 따라가세요':'먼저 지도로 이동해 보세요',text:'현재 위치는 '+here+'입니다. 목적지는 '+there+'입니다. 목적지를 고른 뒤 이어지는 길의 이동 버튼을 누르세요.',screen:'LOCATION',target:'.terrain-destination-list',destination:journey.target};}
 if(!d.move){const edges=this.view().edges||[],edge=edges.find(x=>!x.reason)?.row,map=this.row('32_MAP_DB',g.CURRENT_MAP_ID);return {id:'move',title:'먼저 지도로 이동해 보세요',text:'현재 위치는 '+map[2]+'입니다. 지도에 표시된 목적지 카드에서 연결된 길을 누르세요. 실제로 다른 구역에 도착하면 다음 안내가 열립니다.',screen:'LOCATION',target:'.terrain-destination-list',destination:edge?.[2]};}
 if(!d.facility){if(g.CURRENT_MAP_ID!=='MAP_MOND_CITY')return {id:'firstTown',title:'몬드성으로 이동하세요',text:'도시에서는 시설의 인물에게 말을 걸거나 상점·제작을 이용할 수 있습니다. 지도에서 몬드성으로 가는 길을 따라가세요.',screen:'LOCATION',destination:'MAP_MOND_CITY',target:'.terrain-destination-list'};return {id:'facility',title:'주변 시설에서 캐서린을 만나세요',text:'메인 화면의 시설에서 모험가 길드의 캐서린을 골라 말을 걸어 보세요.',command:'guild',target:'.location-places'};}
 // Resource and town lessons use actual map/facility actions, with a destination when away.
 const travel=(id,title,text,map)=>({id,title,text,screen:'LOCATION',target:'#journey-map',destination:map});
 if(!learned.commission){if(g.CURRENT_MAP_ID!=='MAP_MOND_CITY')return travel('guildTravel','몬드성 모험가 길드로 돌아가세요','의뢰를 받고 현장에 다녀온 뒤 보상을 받는 과정을 익힙니다.','MAP_MOND_CITY');return {id:'commission',title:'길드에서 의뢰를 받으세요',text:'캐서린에게 말을 걸고 오늘의 의뢰 하나를 수락하세요.',command:this.atGuild()?'quest':'guild',screen:'QUEST',target:'.commission-card'};}
 if(!learned.pin)return {id:'pin',title:'받은 의뢰를 지도 목표로 고정하세요',text:'임무에서 의뢰를 열어 「이 임무 고정」을 누르세요. 지도에 다음 목적지가 연결됩니다.',screen:'QUEST',target:'.objective-pin-actions'};
 if(!d.gather)return g.CURRENT_MAP_ID==='MAP_MOND_PLAINS'?{id:'gather',title:'이번에는 돌파에 쓸 채집 자원을 모으세요',text:'세 번의 선택 중 두 번 이상 맞히세요. 재료는 가방에 들어가며 하루 자원 한도가 줄어듭니다.',command:'life',kind:'GATHER'}:travel('gatherTravel','몬드 외곽 초원으로 이동하세요','채집을 직접 해 보고 지역 자원과 돌파 재료를 알아봅니다.','MAP_MOND_PLAINS');
 if(!d.mine)return g.CURRENT_MAP_ID==='MAP_CRPG_MOND_QUARRY'?{id:'mine',title:'광석을 직접 캐 보세요',text:'움직이는 표시가 금색 구간 안에 있을 때 내려치세요. 세 번 중 두 번 성공하면 광석을 얻습니다.',command:'life',kind:'MINE'}:travel('mineTravel','몬드 동쪽 광산으로 이동하세요','채광으로 장비 제작과 강화에 쓸 광석을 얻습니다.','MAP_CRPG_MOND_QUARRY');
 if(!learned.claim)return {id:'claim',title:'의뢰 현장을 해결하고 보상을 받으세요',text:'고정한 목표의 길을 따라 이동해 현장 행동을 완료하고, 길드로 돌아와 보상을 받으세요.',screen:'QUEST',target:'.commission-card'};
 if(!d.wish&&this.premiumFighters().length<2)return {id:'wish',title:'함께 싸울 동료를 기원으로 만나세요',text:'시작 인연 20개가 준비되어 있습니다. 상시 기원에서 10회를 진행하세요.',command:'wish'};
 if(this.s.party.filter(x=>x.active).length<2)return {id:'party',title:'만난 동료를 편성에 넣으세요',text:'편성에서 동료를 선택해 빈 자리에 배치하세요. 주인공과 최대 세 동료가 함께 싸웁니다.',screen:'PARTY',target:'.formation-grid'};
 if(!this.s.inventory.some(i=>i.equipped&&i.owner==='PLAYER_CUSTOM'&&i.category==='WEAPON'))return {id:'equip',title:'주인공에게 무기를 장착하세요',text:'무기 칸을 누르고 사용할 무기의 장착 버튼을 누르세요.',screen:'STATUS',target:'.gear-slot[data-category="WEAPON"]'};
 if(!d.drill&&g.STORY_ROUTE_ID==='ROUTE_TRAVELER'&&!this.protagonistUnlocked())return {id:'firstElement',title:'이야기에서 바람 원소를 배우세요',text:'여행자의 원소전투 스킬을 익힌 뒤 방어·공격·스킬 훈련을 시작합니다.',screen:'STORY'};
 if(!d.drill)return {id:'drill',title:'전투 훈련을 시작하세요',text:'주인공 혼자 방어 → 일반 공격 → 스킬을 차례로 연습합니다. 첫 승리 보상: 영웅의 경험 3개, 통통 연꽃 2개, 부서진 가면 2개.',command:'drill'};
 if(!d.book)return {id:'book',title:'훈련 보상으로 레벨을 올리세요',text:'캐릭터 화면 아래의 경험치 책에서 주인공과 사용할 수량을 고르세요.',screen:'STATUS',target:'.gear-books'};
 if(!d.domain){const available=this.growthDomainEntries();return available.length?{id:'domain',title:'경험치 비경 Lv. 5에 도전하세요',text:'비경 종류와 적 편성, 승리 보상을 확인하고 입장하세요. 이번에는 편성한 동료도 함께 싸웁니다.',command:'domain',domain:'EXP:5'}:{id:'travel',title:'몬드성의 비경 입구로 이동하세요',text:'지도에서 몬드성으로 가는 길을 선택하세요.',screen:'LOCATION',target:'#journey-map',destination:'MAP_MOND_CITY'};}
 if(!learned.craft){if(g.CURRENT_MAP_ID!=='MAP_MOND_CITY')return travel('craftTravel','몬드성 대장간으로 이동하세요','모아 온 재료로 장비나 도구를 직접 제작합니다.','MAP_MOND_CITY');return {id:'craft',title:'대장간에서 첫 제작을 하세요',text:'만들 물건을 고르고 재료·모라를 확인한 뒤 제작하세요. 부족한 재료는 구입하거나 채광할 수 있습니다.',command:'smith',target:'.craft-card'};}
 if(!learned.enhance)return {id:'enhance',title:'실제로 쓰는 장비를 한 번 강화하세요',text:'대장간의 강화에서 장비를 고르고 비용과 확률을 확인하세요. 강화 결과와 능력치 변화를 확인하면 실습이 이어집니다.',command:g.CURRENT_MAP_ID==='MAP_MOND_CITY'?'smith':null,screen:'LOCATION',destination:'MAP_MOND_CITY'};
 if(this.growth().level<10)return {id:'level',title:'경험치 비경과 책으로 Lv. 10까지 성장하세요',text:'모은 책은 대기 동료에게도 사용할 수 있습니다. 비경 보상 화면에서 같은 단계를 다시 도전할 수 있습니다.',command:this.growthDomainEntries().length?'domain':null,domain:'EXP:5',screen:'STATUS'};
 if(this.growth().phase===0){const asc=this.ascensionInfo();if(!asc.gate.ready)return {id:'storyGate',title:'첫 돌파를 위해 본편을 진행하세요',text:asc.gate.label+'을 마치면 첫 돌파가 열립니다.',screen:'STORY'};
  if(this.itemCount('GROWTH_GEM_NEUTRAL')<3)return {id:'gem',title:'돌파 비경에서 주인공 재료를 모으세요',text:'돌파 비경 Lv. 5에서 주인공 돌파 재료를 선택하세요. 3개가 필요합니다.',command:this.growthDomainEntries().length?'domain':null,domain:'ASCENSION:5',screen:'LOCATION'};
  return {id:'ascend',title:'첫 캐릭터 돌파를 실행하세요',text:asc.reason||'돌파하면 레벨 상한이 20으로 열리고 능력치가 크게 오릅니다.',command:'ascend',screen:'STATUS'};}
 if(!d.talent){const info=this.talentUpgradeInfo('PLAYER_CUSTOM','na');if(this.itemCount('GROWTH_TALENT_MOND')<2)return {id:'talentBook',title:'특성 비경에서 수련서를 모으세요',text:'일반 공격 Lv. 2에는 몬드 특성 수련서 2개와 모라가 필요합니다.',command:this.growthDomainEntries().length?'domain':null,domain:'TALENT:5',screen:'LOCATION'};return {id:'talent',title:'일반 공격의 특성을 강화하세요',text:info.reason||'특성 강화는 실제 피해량을 올립니다. 각 특성의 상한은 캐릭터 돌파로 열립니다.',command:'talent'};}
 return {id:'complete',title:'첫 육성 과정을 마쳤습니다',text:'새 지역에서 막히면 비경 → 책·돌파·특성 → 장비·편성을 준비하고 다시 도전하세요.',command:'complete'};
};
P.startTutorialDrill=function(){const t=this.tutorialState();if(t.done.drill)fail('첫 훈련을 이미 마쳤습니다. 비경에 도전해 주세요.');if(this.playPhase()!=='FREE')fail('현재 장면을 먼저 마쳐 주세요.');const out=this.startBattle('EG_MOND_HILI_PATROL','TUTORIAL:DRILL'),b=this.s.runtime;if(!b)fail('전투를 시작하지 못했습니다.');b.actors=b.actors.filter(a=>a.side==='ENEMY'||a.source==='PLAYER_CUSTOM');b.enemyReserve=[];const enemies=b.actors.filter(a=>a.side==='ENEMY');for(const a of enemies){a.hp=a.maxHp=280;a.atk=10;a.def=8;a.level=1;a.spd=20;a.shields=[];a.statuses=[];}b.actors=b.actors.filter(a=>a.side==='ALLY'||enemies.indexOf(a)<2);b.order=b.order.filter(o=>b.actors.some(a=>a.id===o.id));b.fields=[];b.tutorialDrill={step:'guard'};delete b.enemyTiers;delete b.mondBalance;b.opening.initialOrder=copy(b.order);return out;};
P.actionReason=function(type,a={}){const why=old.actionReason.call(this,type,a);if(why&&type!=='TUTORIAL_GUIDE')return why;if(type==='TUTORIAL_GUIDE')return typeof a.enabled==='boolean'?'':'안내 표시 여부를 선택해 주세요.';if(type==='TUTORIAL_DRILL')return this.playPhase()!=='FREE'||this.tutorialState().done.drill?'현재 장면을 마치거나 비경에 도전해 주세요.':this.s.global.STORY_ROUTE_ID==='ROUTE_TRAVELER'&&!this.protagonistUnlocked()?'이야기에서 바람 원소를 먼저 배워 주세요.':'';if(type==='COMBAT'&&this.s.runtime?.tutorialDrill){const step=this.s.runtime.tutorialDrill.step;if(step==='guard'&&a.card!=='PLAYER_BASIC_GUARD')return '첫 차례에는 방어를 골라 실행하세요.';if(step==='attack'&&a.card!=='PLAYER_BASIC_ATTACK')return '이번에는 일반 공격과 대상을 골라 실행하세요.';if(step==='skill'&&!/_E(?:_CHARGE)?$/.test(a.card)&&this.combatCards().some(c=>/_E(?:_CHARGE)?$/.test(c.id)&&!c.reason))return '이번에는 원소전투 스킬을 골라 실행하세요.';}return '';};
P.apply=function(a){if(a.type==='TUTORIAL_GUIDE'){this.tutorialState().enabled=a.enabled;return {enabled:a.enabled};}if(a.type==='TUTORIAL_DRILL')return this.startTutorialDrill();const b=this.s.runtime,drill=b?.tutorialDrill,prev=drill?.step,fromMap=this.s.global.CURRENT_MAP_ID,learningMove=a.type==='MOVE'&&this.tutorialState().enabled&&this.playPhase()==='FREE';if(a.type==='COMBAT'&&drill){const why=this.actionReason(a.type,a);if(why)fail(why);drill.step={guard:'attack',attack:'skill',skill:'win',win:'win'}[prev];}let out;try{out=old.apply.call(this,a);}catch(e){if(drill)drill.step=prev;throw e;}const d=this.tutorialState().done;if(learningMove&&this.s.global.CURRENT_MAP_ID!==fromMap)d.move=true;if(a.type==='PLACE_ENTER')d.facility=true;if(a.type==='WISH')d.wish=true;if(a.type==='USE_ITEM'&&api.localRevision.books[a.item])d.book=true;if(a.type==='TALENT_UPGRADE')d.talent=true;if(a.type==='LIFE_FINISH'&&out?.caught){if(out.kind==='GATHER')d.gather=true;if(out.kind==='MINE')d.mine=true;}return out;};
P.finishBattle=function(win){const b=this.s.runtime,out=old.finishBattle.call(this,win);if(win&&b){const d=this.tutorialState().done;if(b.growthDomain)d.domain=true;if(b.tutorialDrill&&!d.drill){d.drill=true;const reward={MAT_CHAR_EXP_HERO:3,ING_CALLA_LILY:2,MAT_DAMAGED_MASK:2};for(const [id,n]of Object.entries(reward)){this.giveItem(id,n);out.loot[id]=(out.loot[id]||0)+n;}out.tutorialReward=true;this.s.combatReceipts[b.id]=copy(out);this.s.global.LAST_BATTLE_RESULT_JSON=JSON.stringify(out);}}return out;};
P.newGame=function(o){old.newGame.call(this,o);this.s.tutorialV2={version:2,enabled:true,done:{}};return copy(this.s);};
P.validateSave=function(s){old.validateSave.call(this,s);const t=s.tutorialV2;if(t&&(t.version!==2||typeof t.enabled!=='boolean'||!t.done||Array.isArray(t.done)||Object.values(t.done).some(x=>x!==true)))fail('실습 안내 기록을 확인해 주세요.');const d=s.runtime?.tutorialDrill;if(d&&(s.runtime.origin!=='TUTORIAL:DRILL'||!['guard','attack','skill','win'].includes(d.step)))fail('훈련 전투 기록을 확인해 주세요.');return s;};
})(globalThis);
