(function(root){
'use strict';
const api=typeof module!=='undefined'&&module.exports?require('./runtime.js'):root.CRPGRuntime;
const {Runtime:R,RuleError,condition}=api, P=R.prototype;
const cp=x=>JSON.parse(JSON.stringify(x)), json=(s,d={})=>{try{return JSON.parse(s)}catch{return d}}, clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const fail=(c,m)=>{throw new RuleError(c,m)}, rnd=Math.round;
const priorNew=P.newGame, priorApply=P.apply, priorFinish=P.finishBattle, priorMove=P.move, priorEquip=P.equip;
const priorCharacter=P.character;P.character=function(id){const a=priorCharacter.call(this,id),prof=2+Math.floor((a.level-1)/4);a.hit=Math.min(95,75+prof*2);a.eva=Math.max(3,5+Math.round((a.spd-60)/10));a.resist=5+prof*2;return a};
P.newGame=function(o){priorNew.call(this,o);this.s.global.LAST_SAFE_MAP_ID='MAP_MOND_CITY';this.s.global.ENCOUNTER_COOLDOWN=1;this.s.global.WEAPON_PROFICIENCIES_JSON='["한손검"]';return cp(this.s)};
P.apply=function(a){if(a.type==='USE_ITEM')return this.useItem(a.item,a.quantity??1,a.owner||'PLAYER_CUSTOM');if(a.type==='BOSS_ROUTE')return this.bossRoute(a.route,a.entry||'DIRECT');if(a.type==='BATTLE_START')fail('DIRECT_BATTLE','현재 장소의 이동·의뢰·보스 메뉴로 전투를 시작해 주세요.');return priorApply.call(this,a)};
P.move=function(id){const result=priorMove.call(this,id),g=this.s.global,m=this.row('32_MAP_DB',g.CURRENT_MAP_ID);g.LOCATION=m[2];g.LOCATION_PROFILE=m[5];g.LAST_MAP_EDGE_ID=id;g.LAST_MOVE_TIME_COST_MIN=result.minutes;if(m[12]==='Y')g.LAST_SAFE_MAP_ID=m[0];result.encounter=this.rollEncounter(m);return result};
// Select only from this map's currently eligible authored bands. Relative weights
// survive conditional gaps and no-repeat filtering; no unbounded reroll is needed.
P.encounterPoolRows=function(m){
 const authored=this.rows('34_MAP_ENCOUNTER_POOL').filter(r=>r[1]===m[0]);
 if(!authored.length)fail('POOL','이 맵에 연결된 조우 편성이 없습니다.');
 const rows=authored.filter(r=>!r[6]&&!r[7]&&condition(r[8],this.vars()));
 for(const r of rows){
  if(r[2]!=='d100'||!Number.isInteger(Number(r[3]))||!Number.isInteger(Number(r[4]))||Number(r[3])<1||Number(r[4])>100||Number(r[3])>Number(r[4]))fail('POOL','조우 확률 구간이 잘못되었습니다.');
  if(!this.tables['33_ENCOUNTER_GROUP_DB'].has(r[5]))fail('POOL','조우 편성의 대상을 찾을 수 없습니다.');
 }
 return rows;
};
P.rollEncounter=function(m){
 const g=this.s.global;if(m[8]!=='Y'||m[12]==='Y')return null;
 if(Number(g.ENCOUNTER_COOLDOWN)>0){g.ENCOUNTER_COOLDOWN--;return null;}
 g.LAST_ENCOUNTER_TRIGGER_ROLL=this.die();
 if(g.LAST_ENCOUNTER_TRIGGER_ROLL>Number(m[9]))return null;
 const eligible=this.encounterPoolRows(m);if(!eligible.length)return null;
 const alternatives=eligible.filter(r=>r[5]!==g.LAST_ENCOUNTER_GROUP_ID||r[9]!=='N');
 // A single-group map must not become permanently empty after its first fight.
 const rows=alternatives.length?alternatives:eligible;
 const weight=r=>Number(r[4])-Number(r[3])+1;
 let roll=this.die(rows.reduce((sum,r)=>sum+weight(r),0)),selected;
 for(const r of rows){if(roll<=weight(r)){selected=r;break;}roll-=weight(r);}
 if(!selected)fail('POOL','조우 주사위 값이 유효한 범위를 벗어났습니다.');
 // Record a face in the selected original band, not a face in a removed band.
 g.LAST_ENCOUNTER_POOL_ROLL=Number(selected[3])+roll-1;
 const group=selected[5];this.startBattle(group,'RANDOM');g.LAST_ENCOUNTER_GROUP_ID=group;return group;
};
P.equip=function(slot,owner){const hpBefore=this.s.global.PLAYER_HP_CURRENT;const inv=this.s.inventory.find(i=>i.slot===slot&&i.equip);if(!inv)fail('EQUIP','소지 장비를 선택해 주세요.');const e=this.row('16_EQUIP_DB',inv.equip);if(['한손검','양손검','장병기','활','법구'].includes(e[2])){let proficiency=owner==='PLAYER_CUSTOM'?json(this.s.global.WEAPON_PROFICIENCIES_JSON,[]):this.rows('08_SKILL_CARD_DB').filter(c=>c[2]===owner).flatMap(c=>['한손검','양손검','장병기','활','법구'].filter(t=>String(c[5]).includes(t)));const explicit={MOND_AMBER:['활'],MOND_KAEYA:['한손검'],MOND_LISA:['법구']};if(owner!=='PLAYER_CUSTOM')proficiency=explicit[owner]||proficiency;if(!proficiency.includes(e[2]))fail('PROFICIENCY','이 무기를 사용하는 장착 대상이 아닙니다.');}const result=priorEquip.call(this,slot,owner);this.s.global.PLAYER_HP_CURRENT=Math.min(hpBefore,this.s.global.PLAYER_HP_MAX);return result};
P.useItem=function(id,n,owner){if(this.s.runtime)fail('COMBAT','전투 밖에서 사용해 주세요.');if(!Number.isInteger(n)||n<1||this.itemCount(id)<n)fail('QUANTITY','보유 수량 안에서 선택해 주세요.');const xp={MAT_CHAR_EXP_WANDERER:50,MAT_CHAR_EXP_ADVENTURER:250,MAT_CHAR_EXP_HERO:1000}[id];if(!xp)fail('ITEM_HANDLER','이 아이템의 사용 효과는 아직 실행 범위 밖입니다.');if(owner!=='PLAYER_CUSTOM'&&!['JOINED'].includes(json(this.s.global.COMPANION_ELIGIBILITY_JSON)[owner]?.state))fail('OWNER','합류한 캐릭터를 선택해 주세요.');const level=owner==='PLAYER_CUSTOM'?this.s.global.PLAYER_LEVEL_STATE:this.s.chars[owner].level;if(level>=20)fail('LEVEL','최대 레벨에는 사용할 수 없습니다.');this.pay({items:{[id]:n}});this.addXp(owner,xp*n);return{item:id,quantity:n,xp:xp*n,owner}};
P.craftReason=function(r){if(this.s.runtime)return'전투를 먼저 해결해 주세요.';if(r[1]==='강화')return'강화할 개별 장비를 선택해 주세요.';if(/레거시|사용 금지/.test(r[18]||''))return'사용하지 않는 예시 제작법입니다.';const facilities=this.schedules().map(x=>x.facility+' '+x.merchant_id).join(' ');if(r[1]==='요리'&&!facilities.includes('조리시설'))return'조리시설이 필요합니다.';if(r[2]==='EQUIP'&&!/대장|EQUIP/.test(facilities))return'대장간이 필요합니다.';if(!facilities)return'작업 시설이 필요합니다.';const req=String(r[18]||'');if(!['','없음','기본','기본 해금','전투 중 아님'].includes(req)){const purchased=req.match(/^(STK_\w+) 구매완료$/);if(purchased){if(!Object.keys(json(this.s.global.SHOP_STOCK_USAGE_STATE)).some(k=>k.startsWith(purchased[1]+'|')))return'제작법을 먼저 구매해 주세요.';}else if(!condition(req,this.vars()))return'제작법의 추가 해금 조건을 확인해야 합니다.';}return''};
P.craft=function(id){const r=this.row('17_RECIPE_DB',id),reason=this.craftReason(r);if(reason)fail('CRAFT',reason);const cost={mora:Number(r[15]||0),items:{}};for(const i of this.rows('48_RECIPE_INGREDIENT_DB').filter(x=>x[1]===id))cost.items[i[3]]=(cost.items[i[3]]||0)+Number(i[4]);if(!Object.keys(cost.items).length)fail('RECIPE','제작 재료 정의를 확인해야 합니다.');this.pay(cost);if(r[2]==='ITEM')this.giveItem(r[3],Number(r[4]));else if(r[2]==='EQUIP')for(let n=0;n<r[4];n++)this.giveEquipment(r[3]);else fail('RECIPE','지원되지 않는 제작 결과입니다.');const duration=String(r[19]||''),n=Number(duration.match(/\d+/)?.[0]||0);this.advanceTime(duration.includes('시간')?n*60:n);return{recipe:id,result:r[3],quantity:Number(r[4])};};
P.finishBattle=function(victory){const b=cp(this.s.runtime),result=priorFinish.call(this,victory),g=this.s.global;g.ENCOUNTER_COOLDOWN=1;const counts=json(g.WORLD_VISIT_COUNTS_JSON);if(victory&&this.row('32_MAP_DB',g.CURRENT_MAP_ID)[1]==='몬드')counts.MON_D_ENCOUNTERS=(counts.MON_D_ENCOUNTERS||0)+1;g.WORLD_VISIT_COUNTS_JSON=JSON.stringify(counts);for(const [pid,r]of Object.entries(this.s.relations)){const char=this.row('04_CHAR_DB',pid)[1];if(json(g.COMPANION_ELIGIBILITY_JSON)[char]?.state==='DEPARTED')r.companion='DEPARTED';}if(!victory){g.CURRENT_MAP_ID=g.LAST_SAFE_MAP_ID||'MAP_MOND_CITY';g.LOCATION=this.row('32_MAP_DB',g.CURRENT_MAP_ID)[2];if(b.origin.startsWith('QUEST:'))this.questState(b.origin.slice(6)).node='INVESTIGATE';}if(b.origin.startsWith('BOSS:')){const route=this.row('35_BOSS_ROUTE_DB',b.origin.slice(5));if(victory&&this.rows('50_BOSS_ROUTE_STEP_DB').find(r=>r[1]===route[0]&&r[4]===b.group)?.[3]==='BOSS'){this.s.flags[route[13]]=true;g.ACTIVE_BOSS_ROUTE_ID='';}else if(victory)g.BOSS_ROUTE_STEP++;}return result;};
P.bossRoute=function(id,entry){if(this.s.runtime)fail('COMBAT','이미 전투 중입니다.');const r=this.row('35_BOSS_ROUTE_DB',id);if(this.s.global.CURRENT_MAP_ID!==r[2])fail('LOCATION','해당 보스의 진입 장소가 아닙니다.');if(r[12]&&!this.s.flags[r[12]])fail('LOCKED','보스 진입 조건을 충족하지 않았습니다.');if(!['DIRECT','GAUNTLET'].includes(entry))fail('ENTRY','진입 방식을 선택해 주세요.');if(entry==='DIRECT'&&(r[8]!=='Y'||r[9]==='Y'))fail('ENTRY','전초전이 필요한 루트입니다.');const steps=this.rows('50_BOSS_ROUTE_STEP_DB').filter(x=>x[1]===id).sort((a,b)=>a[2]-b[2]);const step=entry==='DIRECT'?steps.find(x=>x[3]==='BOSS'):steps[0];if(!step)fail('ROUTE','보스 단계 정의가 없습니다.');this.s.global.ACTIVE_BOSS_ROUTE_ID=id;this.s.global.BOSS_ROUTE_STEP=step[2];this.s.global.BOSS_ENTRY_MODE=entry;return this.startBattle(step[4],'BOSS:'+id)};

// Audited encounter construction: use child rows, unique instances, explicit scale rules.
P.startBattle=function(group,origin){if(!this.s.party.some(p=>p.active&&(p.type==='PLAYER'?this.s.global.PLAYER_HP_CURRENT:this.s.chars[p.source]?.hp)>0))fail('PARTY_DOWN','파티가 전투불능입니다. 먼저 숙박·회복을 이용해 주세요.');if(this.s.runtime)fail('COMBAT','이미 전투 중입니다.');const gr=this.row('33_ENCOUNTER_GROUP_DB',group),members=this.rows('49_ENCOUNTER_MEMBER_DB').filter(x=>x[1]===group),party=this.s.party.filter(p=>p.active);if(!members.length)fail('GROUP','적 편성 정보가 없습니다.');if(party.some(p=>p.type==='CHAR'&&!['MOND_AMBER','MOND_KAEYA','MOND_LISA'].includes(p.source)))fail('CONTENT_CAPABILITY','이 동료의 전용 카드 실행은 아직 검증 범위 밖입니다.');const actors=party.map(p=>p.type==='PLAYER'?this.player():this.character(p.source));const targetLevel=gr[6]==='PARTY_BANDED'?clamp(rnd(actors.reduce((n,a)=>n+a.level,0)/actors.length)+this.die(3)-2,Number(gr[4]),Number(gr[5])):null;const seq={};for(const member of members){const r=this.row('09_MONSTER_DB',member[3]);if(this.rows('12_ENEMY_CARD_DB').some(c=>c[1]===r[0]&&c[35]==='READY')&&r[0]!=='BOSS_DVALIN')fail('CONTENT_CAPABILITY','이 적의 전용 카드 실행은 아직 검증 범위 밖입니다.');const level=targetLevel||Number(r[18]);if(!level)fail('LEVEL','적 레벨 정의가 없습니다.');const base=this.row('26_LEVEL_RULES',Number(r[18])),lv=this.row('26_LEVEL_RULES',level),tier=targetLevel?({'일반':[2,1.1,1.05],'정예':[2.8,1.15,1.15],'강적':[4,1.25,1.2]}[r[3]]||[1,1,1]):[1,1,1];const count=Number(member[4])+Math.floor(this.random()*(Number(member[5])-Number(member[4])+1));for(let n=0;n<count;n++){const id=r[0]+'#'+(seq[r[0]]=(seq[r[0]]||0)+1), hp=rnd(Number(r[6])*(targetLevel?lv[4]/base[4]:1)*tier[0]*(r[3]!=='보스'&&actors.filter(a=>a.side==='ALLY').length>=3?(party.length>=4?1.2:1.1):1));actors.push({id,source:r[0],name:r[1],side:'ENEMY',control:'AI',hp,maxHp:hp,atk:rnd(Number(r[7])*(targetLevel?lv[5]/base[5]:1)*tier[1]),def:rnd(Number(r[8])*(targetLevel?lv[5]/base[5]:1)*tier[2]),crit:Number(r[9]),critDmg:Number(r[10]),level,spd:Number(r[19])+(targetLevel?lv[6]-base[6]:0),hit:targetLevel?Math.min(95,75+Number(lv[3])*2):Number(r[20]),eva:targetLevel?Math.max(3,5+rnd((Number(r[19])+lv[6]-base[6]-60)/10)):Number(r[21]),resist:targetLevel?5+Number(lv[3])*2:Number(r[22]),range:r[23],aura:null,statuses:[],cooldowns:{},airborne:r[0]==='BOSS_DVALIN'});}}
 const id=this.s.global.SAVE_ID+':B'+(this.s.global.LAST_COMMITTED_ACTION_SEQ+1);this.s.runtime={id,group,origin,round:1,actors,order:[],cursor:0,phase:'START',ticks:{},log:[],fields:[],terrain:actors.some(a=>a.source==='BOSS_DVALIN')?4:null};Object.assign(this.s.global,{ACTIVE_BATTLE_ID:id,MODE:'COMBAT',SCREEN_MODE:'COMBAT'});this.newRound();this.autoUntilPlayer();return{battle:id,group};};
P.damage=function(a,t,k,element='PHYSICAL',opts={}){const b=this.s.runtime;if(t.hp<=0)return false;if(t.airborne&&!['원거리','전장'].includes(opts.range||a.range)&&!opts.antiAir)fail('AIRBORNE','이 공격은 공중의 대상을 지정할 수 없습니다.');if(this.die()>clamp(a.hit-t.eva+10+(opts.hitBonus||0),65,98)){b.log.push({actor:a.name,target:t.name,miss:true});return false;}const reaction=this.rows('37_ELEMENTAL_REACTION_DB').find(r=>r[4]==='증폭'&&r[2]===t.aura&&r[3]===element);let mult=Number(reaction?.[6]||1);const crit=this.die()<=a.crit;const damage=rnd(Math.max(1,a.atk*k*100/(100+t.def*(t.statuses?.some(s=>s.id==='STATUS_DEF_DOWN')?.85:1))*(crit?1+a.critDmg/100:1)*(.95+.1*this.random())*(t.guard?.5:1)*mult));t.hp=Math.max(0,t.hp-damage);if(element!=='PHYSICAL')t.aura=reaction?null:element;b.log.push({actor:a.name,target:t.name,damage,critical:crit,reaction:reaction?.[0]||null});return true;};
P.basicHit=function(a,t,k=.65){return this.damage(a,t,k,'PHYSICAL')};
P.aiTurn=function(a,targets){const b=this.s.runtime,available=id=>(a.cooldowns[id]||0)===0&&a.level>=Number(this.row('08_SKILL_CARD_DB',id)[22]||1);const use=(id)=>{a.cooldowns[id]=Number(this.row('08_SKILL_CARD_DB',id)[9]||0)+1;b.log.push({actor:a.name,card:id});};if(a.source==='BOSS_DVALIN'){const dive=(a.cooldowns.DIVE||0)===0;if(!dive&&(a.cooldowns.BREATH||0)>0){this.basicHit(a,targets[0]);return;}const coef=dive?1.6:1.25;for(const t of targets.slice(0,dive?2:3))if(this.damage(a,t,coef,'바람',{range:'전장',hitBonus:dive?8:5})&&!dive)t.nextScorePenalty=8;a.cooldowns[dive?'DIVE':'BREATH']=3;return;}
 if(a.source==='MOND_AMBER'){if(available('MOND_AMBER_Q')){use('MOND_AMBER_Q');for(const t of targets.slice(0,4))for(let n=0;n<5;n++)this.damage(a,t,.28,'불',{range:'전장'});return;}if(available('MOND_AMBER_E')){use('MOND_AMBER_E');b.fields.push({kind:'BUNNY',actor:a.id,side:a.side,hp:Math.floor(a.maxHp*.25),def:a.def,round:b.round+1});return;}}
 if(a.source==='MOND_KAEYA'){if(available('MOND_KAEYA_Q')){use('MOND_KAEYA_Q');b.fields.push({kind:'ICE',actor:a.id,start:b.round+1,end:b.round+3});return;}if(available('MOND_KAEYA_E')){use('MOND_KAEYA_E');this.damage(a,targets[0],1.25,'얼음');return;}}
 if(a.source==='MOND_LISA'){if(available('MOND_LISA_Q')){use('MOND_LISA_Q');for(const t of targets.slice(0,4)){this.damage(a,t,.6,'번개',{range:'전장'});t.statuses.push({id:'STATUS_DEF_DOWN',rounds:3});}b.fields.push({kind:'ROSE',actor:a.id,end:b.round+1});return;}if(available('MOND_LISA_E')){use('MOND_LISA_E');if(this.damage(a,targets[0],.5,'번개'))targets[0].conduction=Math.min(3,(targets[0].conduction||0)+1);return;}}
 const bunny=b.fields.find(f=>f.kind==='BUNNY'&&f.side!==a.side&&f.hp>0);if(bunny){const proxy={id:'BUNNY',name:'폭탄 인형',hp:bunny.hp,maxHp:bunny.hp,def:bunny.def,eva:0,range:'근접',statuses:[]};this.damage(a,proxy,.65,'PHYSICAL');bunny.hp=proxy.hp;if(bunny.hp<=0)this.explodeBunny(bunny);return;}const legal=targets.filter(t=>!t.airborne||['원거리','전장'].includes(a.range));if(legal.length)this.basicHit(a,legal[0]);else {a.guard=true;b.log.push({actor:a.name,guard:true,reason:'공중 접근 불가'});}};
P.explodeBunny=function(f){const b=this.s.runtime,a=b.actors.find(x=>x.id===f.actor);if(!a||f.done)return;for(const t of b.actors.filter(x=>x.side!==a.side&&x.hp>0&&!x.airborne).slice(0,3))this.damage(a,t,1.2,'불');f.done=true;};
P.roundEnd=function(){const b=this.s.runtime;for(const f of b.fields){const a=b.actors.find(x=>x.id===f.actor);if(f.kind==='ROSE'&&a&&a.hp>0&&b.round<=f.end)for(const t of b.actors.filter(x=>x.side!==a.side&&x.hp>0).slice(0,4))this.damage(a,t,.35,'번개',{range:'전장'});}if(b.terrain!==null&&b.round%2===0){b.terrain--;if(b.terrain===0){for(const a of b.actors.filter(a=>a.side==='ALLY'))a.hp=0;this.finishBattle(false);return false;}}for(const a of b.actors){a.statuses=a.statuses.filter(s=>--s.rounds>0);for(const k of Object.keys(a.cooldowns))a.cooldowns[k]=Math.max(0,a.cooldowns[k]-1);}b.round++;for(const f of b.fields){if(f.kind==='BUNNY'&&!f.done&&f.round<=b.round)this.explodeBunny(f);if(f.kind==='ICE'&&b.round>=f.start&&b.round<=f.end){const a=b.actors.find(x=>x.id===f.actor&&x.hp>0);if(a)for(const t of b.actors.filter(x=>x.side!==a.side&&x.hp>0&&!x.airborne).slice(0,3))this.damage(a,t,.45,'얼음');}}b.fields=b.fields.filter(f=>!f.done&&(f.end===undefined||f.end>=b.round));return true;};
P.newRound=function(){const b=this.s.runtime;b.order=b.actors.filter(a=>a.hp>0).map(a=>({id:a.id,score:a.spd+(a.statuses.some(s=>s.id==='STATUS_SLOW')?-10:0)-(a.nextScorePenalty||0)+this.die(10)-1})).sort((a,c)=>c.score-a.score||a.id.localeCompare(c.id));for(const a of b.actors)a.nextScorePenalty=0;b.cursor=0;};
P.autoUntilPlayer=function(){for(let safety=0;safety<1000;safety++){const b=this.s.runtime;if(!b)return;let alive=b.actors.filter(a=>a.hp>0);if(!alive.some(a=>a.side==='ENEMY')){this.finishBattle(true);return;}if(!alive.some(a=>a.side==='ALLY')){this.finishBattle(false);return;}if(b.cursor>=b.order.length){if(!this.roundEnd())return;this.newRound();continue;}const a=b.actors.find(x=>x.id===b.order[b.cursor].id);if(!a||a.hp<=0){b.cursor++;continue;}a.guard=false;if(a.control==='PLAYER'){b.phase='WAIT_PLAYER';this.s.global.COMBAT_ACTION_PHASE='WAIT_PLAYER';return;}const targets=alive.filter(x=>x.side!==a.side).sort((x,y)=>x.hp-y.hp||x.id.localeCompare(y.id));this.aiTurn(a,targets);b.cursor++;}fail('COMBAT_LOOP','전투 자동 진행 한도에 도달했습니다.');};
api.Runtime=R;if(typeof module!=='undefined'&&module.exports)module.exports=api;root.CRPGRuntime=api;
})(typeof globalThis!=='undefined'?globalThis:this);
