(function(root){'use strict';const api=typeof module!=='undefined'&&module.exports?require('./runtime_extensions.js'):root.CRPGRuntime,{Runtime:R,RuleError,condition}=api,P=R.prototype;const j=(x,d={})=>{try{return JSON.parse(x)}catch{return d}},fail=(c,m)=>{throw new RuleError(c,m)},val=x=>x==='TRUE'?true:x==='FALSE'?false:/^[-+]?\d+(\.\d+)?$/.test(x)?Number(x):x;
const oldPrep=P.prepareStory,oldNew=P.newGame,oldApply=P.apply,oldMenu=P.menu;
P.newGame=function(o){if(typeof o.name!=='string'||Array.from(o.name.trim()).length>24||/[\x00-\x1f\x7f]/.test(o.name))fail('NAME','이름은 줄바꿈 없이 1~24자로 입력해 주세요.');oldNew.call(this,o);this.s.global.PLAYER_CARD_ID='PLAYER_CUSTOM';this.s.global.STORY_CURSOR_NODE_ID=this.s.global.CURRENT_STORY_NODE_ID;const quest=o.route==='ROUTE_TRAVELER'?'Q_TRV_MOND_01':'Q_ISK_MOND_01';Object.assign(this.questState(quest),{state:'진행중',acceptedTurn:1});return JSON.parse(this.serialize())};
P.quote=function(){const ids=['STK_MOND_EQ_001','STK_MOND_EQ_005'];return {stock:ids.map(id=>({id,price:Number(this.row('19_SHOP_STOCK_DB',id)[5])})),total:ids.reduce((sum,id)=>sum+Number(this.row('19_SHOP_STOCK_DB',id)[5]),0)}};
P.prepareStory=function(){const g=this.s.global;if(String(g.CURRENT_STORY_NODE_ID).startsWith('SCREEN:')){g.CURRENT_STORY_NODE_ID=g.STORY_CURSOR_NODE_ID;g.SCREEN_MODE='MAIN_MENU';return;}oldPrep.call(this);g.STORY_CURSOR_NODE_ID=g.CURRENT_STORY_NODE_ID;const n=this.storyNode();if(n?.[5]==='MENU_GATE')g.SCREEN_MODE='MAIN_MENU';if(n?.[4]==='ISK_M01_T_END'&&this.s.flags.FLAG_ISK_MAIN_UNLOCKED)g.SCREEN_MODE='MAIN_MENU';if(g.PENDING_CHOICE_GROUP_ID==='ISK_M01_G_U_KIT'){const pending=j(g.PENDING_INPUT_JSON);pending.quote=this.quote();g.PENDING_INPUT_JSON=JSON.stringify(pending);}};
P.menu=function(screen){if(screen==='STORY'&&['MENU_GATE','CHAPTER_END'].includes(this.storyNode()?.[5])&&this.s.global.SCREEN_MODE!=='STORY'){this.s.global.SCREEN_MODE='STORY';return;}return oldMenu.call(this,screen)};
P.apply=function(a){if(a.type==='STORY_NAME'){const name=String(a.name||'').trim();if(!name||Array.from(name).length>24||/[\x00-\x1f\x7f]/.test(name))fail('NAME','이름은 줄바꿈 없이 1~24자로 입력해 주세요.');if(this.storyNode()?.[5]!=='INPUT_TEXT')fail('INPUT','이름 입력 대기 장면이 아닙니다.');if(this.s.flags.FLAG_ISK_NAME_SET&&name!==this.s.global.PLAYER_NAME)fail('NAME','이미 확정한 이름은 이 장면에서 다시 쓰지 않습니다.');this.s.global.PLAYER_NAME=name;return this.storyNext(this.storyNode()[4]);}return oldApply.call(this,a)};
P.unlockCharacter=function(id){this.row('07_CHAR_DB',id);const owned=j(this.s.global.COMPANION_ELIGIBILITY_JSON);owned[id]={state:'JOINED',event:this.s.global.CURRENT_STORY_NODE_ID};this.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(owned);const p=this.rows('04_CHAR_DB').find(p=>p[1]===id);if(p){const rel=this.s.relations[p[0]];if(rel)rel.companion='JOINED';}};
P.storyEvent=function(id){const g=this.s.global,f=this.s.flags,n=this.storyNode(),e=this.row('51_EVENT_DB',id);if(e[11]!=='Y'||e[3]!==n?.[4]||g.STORY_ROUTE_ID!=='ROUTE_ISEKAI')fail('EVENT_SOURCE','현재 루트·장면에서 호출할 수 없는 사건입니다.');const progress=j(g.EVENT_PROGRESS_JSON),extra={VALID_USER_NAME:!!g.PLAYER_NAME,QUOTE_ACCEPTED:!!progress.starterQuote,STOCK_AND_MORA_VALID:true,CE_133_TUTORIAL_GUARDS_PASS:true};if(!condition(e[5],{...this.vars(),...extra}))fail('EVENT_CONDITION','사건의 선행 조건을 충족하지 않았습니다.');switch(id){
 case'EVT_ISK_SET_NAME':if(!g.PLAYER_NAME||Array.from(g.PLAYER_NAME.trim()).length>24||/[\x00-\x1f\x7f]/.test(g.PLAYER_NAME))fail('NAME','유효한 이름을 직접 입력해 주세요.');f.FLAG_ISK_NAME_SET=true;break;
 case'EVT_ISK_REGISTER_KNOWN':case'EVT_ISK_REGISTER_UNKNOWN':f.FLAG_ISK_ADVENTURER_REGISTERED=true;g.PLAYER_AFFILIATION='모험가 길드';break;
 case'EVT_ISK_AID':if(!f.FLAG_ISK_AID_RECEIVED){g.MORA+=1000;f.FLAG_ISK_AID_RECEIVED=true;}break;
 case'EVT_ISK_STARTER_KIT':if(!f.FLAG_ISK_STARTER_KIT_BOUGHT){const quote=this.quote();if(JSON.stringify(quote)!==JSON.stringify(progress.starterQuote))fail('QUOTE','견적이 바뀌었습니다. 구매 선택부터 다시 확인해 주세요.');if(this.s.inventory.some(i=>i.equipped&&i.owner==='PLAYER_CUSTOM'&&i.category==='ARMOR'))fail('ARMOR_REPLACE','이미 장착한 방어구가 있습니다. 교체를 먼저 확인해 주세요.');for(const s of quote.stock){const reason=this.stockReason(this.row('19_SHOP_STOCK_DB',s.id));if(reason)fail('STOCK',reason);}if(g.MORA<quote.total)fail('MORA','모라가 부족합니다.');for(const s of quote.stock)this.buy(s.id,1);const coat=this.s.inventory.find(i=>i.equip==='EQ_ARMOR_TRAVEL_COAT'&&!i.equipped);this.equip(coat.slot,'PLAYER_CUSTOM');g.PLAYER_EQUIP_ARMOR='EQ_ARMOR_TRAVEL_COAT';f.FLAG_ISK_STARTER_KIT_BOUGHT=true;}break;
 case'EVT_ISK_RECRUIT_AMBER':f.FLAG_ISK_RECRUIT_AMBER=true;this.unlockCharacter('MOND_AMBER');break;
 case'EVT_ISK_TUTORIAL_COMPLETE':{const common=['FLAG_ISK_NAME_SET','FLAG_ISK_ADVENTURER_REGISTERED','FLAG_ISK_DVALIN_EVENT_SEEN','FLAG_ISK_RECRUIT_AMBER'];if(!common.every(k=>f[k]===true)||!f.FLAG_ISK_JOIN_TONE||f.FLAG_ISK_JOIN_TONE==='UNSET')fail('TUTORIAL_GUARD','튜토리얼의 필수 절차가 남아 있습니다.');if(f.FLAG_ISK_META_KNOWLEDGE==='KNOWN'){if(f.FLAG_ISK_CITY_ACTION!=='CATTAIL_SHELTER'||!f.FLAG_ISK_AFTER_TONE||f.FLAG_ISK_AFTER_TONE==='UNSET')fail('TUTORIAL_GUARD','알고 있는 루트의 마무리 선택이 남아 있습니다.');}else if(f.FLAG_ISK_META_KNOWLEDGE==='UNKNOWN'){if(f.FLAG_ISK_CITY_ACTION!=='HQ_SHELTER'||!f.FLAG_ISK_AID_RECEIVED||!f.FLAG_ISK_STARTER_KIT_BOUGHT)fail('TUTORIAL_GUARD','보호 지원·장비 구매 절차가 남아 있습니다.');}else fail('TUTORIAL_GUARD','세계 인지 선택 기록이 없습니다.');Object.assign(this.questState('Q_ISK_MOND_01'),{state:'완료',claimed:true,completedTurn:g.TURN,node:'TUTORIAL_COMPLETE'});Object.assign(f,{FLAG_ISK_MON_PROLOGUE_CLEAR:true,FLAG_ISK_MAIN_UNLOCKED:true});g.CURRENT_MAP_ID='MAP_MOND_CITY';g.LOCATION_PROFILE=this.row('32_MAP_DB',g.CURRENT_MAP_ID)[5];g.SCREEN_MODE='MAIN_MENU';break;}
 default:fail('EVENT_HANDLER','이 사건은 실행기에 아직 연결되지 않았습니다.');}progress[id]={resolvedNode:n[4],turn:g.TURN};g.EVENT_PROGRESS_JSON=JSON.stringify(progress);};
P.storyNext=function(id,choice=false){const g=this.s.global,r=choice?this.storyChoices().find(r=>r[4]===id):this.storyNode();if(!r||r[4]!==id||!condition(r[11],this.vars()))fail('STORY_CHOICE','현재 장면에서 선택할 수 없는 행동입니다.');if(choice&&g.PENDING_CHOICE_GROUP_ID==='ISK_M01_G_U_KIT'){const prog=j(g.EVENT_PROGRESS_JSON);prog.starterQuote=j(g.PENDING_INPUT_JSON).quote;g.EVENT_PROGRESS_JSON=JSON.stringify(prog);}if(r[5]==='COMBAT_GATE'){const won=String(r[12]).match(/ON_VICTORY:(FLAG_\w+)=TRUE/);if(won&&this.s.flags[won[1]]){g.CURRENT_STORY_NODE_ID=r[13];this.prepareStory();return{resolved:id,alreadyWon:true};}const m=String(r[12]).match(/START_FIXED_COMBAT:(\w+)/);if(!m)fail('COMBAT_GATE','고정 전투 정의가 없습니다.');return this.startBattle(m[1],'STORY:'+id);}
 const applied=j(g.STORY_NODE_EFFECTS_JSON);if(!applied[id]){for(const fx of String(r[12]||'').split(';').map(x=>x.trim()).filter(Boolean)){let m;if(fx.startsWith('EVENT:'))this.storyEvent(fx.slice(6));else if(fx.startsWith('UNLOCK_CARD:')){if(g.STORY_ROUTE_ID!=='ROUTE_TRAVELER')fail('ROUTE','여행자 합류 규칙은 다른 루트에 적용하지 않습니다.');this.unlockCharacter(fx.slice(12));}else if(fx.startsWith('ENSURE_PLAYER_CARD:')){if(!g.PLAYER_CARD_CREATED||g.PLAYER_CARD_ID!=='PLAYER_CUSTOM')fail('PLAYER_CARD','주인공 카드가 아직 생성되지 않았습니다.');this.s.flags.FLAG_TRV_CARD_TRAVELER=true;}else if(fx.startsWith('ENSURE_PLAYER_PARTY_SLOT:')){if(!this.s.party.some(p=>p.active&&p.source==='PLAYER_CUSTOM'))fail('PARTY','주인공을 파티에 편성해 주세요.');}else if(fx.startsWith('COMPLETE_QUEST:')){if(id==='TRV_M02_N422')for(const k of ['ACT3_ABYSS_WON','LAIR_GATE_WON','LAIR_OUTER_BARRIER_OPEN','LAIR_CENTER_LIGHT','LAIR_NORTH_LIGHT','LAIR_WEST_WON','LAIR_WEST_LIGHT','LAIR_EAST_LIGHT','LAIR_INNER_SEAL_OPEN','DVALIN_PURIFIED','GNOSIS_TAKEN'])if(!this.s.flags['FLAG_TRV_'+k])fail('CHAPTER_GUARD','최종 완료 조건을 충족하지 않았습니다.');Object.assign(this.questState(fx.slice(15)),{state:'완료',claimed:true,completedTurn:g.TURN});}else if((m=fx.match(/^(\w+)=(.+)$/))){const k=m[1],v=val(m[2]);if(k.startsWith('FLAG_')){this.row('23_FLAG_DB',k);this.s.flags[k]=v;}else if(k==='PLAYER_ENTITY_ID')g.PLAYER_NARRATIVE_ENTITY_ID=v;else if(k==='STORY_ROUTE_ID'&&v===r[0])g.STORY_ROUTE_ID=v;else if(k.startsWith('Q_')&&v==='COMPLETED')Object.assign(this.questState(k),{state:'완료',claimed:true,completedTurn:g.TURN});else fail('STORY_EFFECT','처리하지 않은 효과: '+k);}else fail('STORY_EFFECT','처리하지 않은 효과: '+fx);}applied[id]=true;g.STORY_NODE_EFFECTS_JSON=JSON.stringify(applied);}
 if(r[5]==='DIALOGUE'&&String(r[6]).startsWith('PROFILE_'))this.markContact(r[6]);g.PENDING_CHOICE_GROUP_ID='';g.PENDING_INPUT_JSON='{}';if(r[13]==='SCREEN:CRPG_MAIN'){g.CURRENT_STORY_NODE_ID=id;g.STORY_CURSOR_NODE_ID=id;g.SCREEN_MODE='MAIN_MENU';return{resolved:id,next:'MAIN_MENU'};}g.CURRENT_STORY_NODE_ID=r[13];this.prepareStory();return{resolved:id,next:g.CURRENT_STORY_NODE_ID};};
const oldPersonal=P.personal;P.personal=function(id,choice){const owned=JSON.parse(this.s.global.COMPANION_ELIGIBILITY_JSON||'{}'),result=oldPersonal.call(this,id,choice),p=JSON.parse(this.row('51_EVENT_DB',id)[13]);if(owned[p.char_id]?.state==='JOINED'){const o=j(this.s.global.COMPANION_ELIGIBILITY_JSON);o[p.char_id]=owned[p.char_id];this.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(o);this.s.relations[p.profile_id].companion='JOINED';}return result};

const originalValidate=P.validateSave;P.validateSave=function(s){originalValidate.call(this,s);const g=s.global;if(!Number.isInteger(g.MORA)||g.MORA<0||!Number.isInteger(g.PLAYER_LEVEL_STATE)||g.PLAYER_LEVEL_STATE<1||g.PLAYER_LEVEL_STATE>20||!Number.isFinite(g.PLAYER_HP_CURRENT)||g.PLAYER_HP_CURRENT<0||g.PLAYER_HP_CURRENT>g.PLAYER_HP_MAX)fail('SAVE_INVALID','저장된 재화·레벨·HP 값이 올바르지 않습니다.');if(g.STORY_CURSOR_NODE_ID&&g.STORY_CURSOR_NODE_ID!==g.CURRENT_STORY_NODE_ID)fail('SAVE_CURSOR','두 진행 커서가 일치하지 않습니다.');for(const i of s.inventory)if(!Number.isInteger(i.quantity)||i.quantity<1||(i.equip&&((!Number.isInteger(i.enhance)||i.enhance<0||i.enhance>12)||i.quantity!==1)))fail('SAVE_INVENTORY','소지품 수량 또는 강화 단계가 올바르지 않습니다.');return s};
const oldAsset=P.assetFor;P.assetFor=function(id,variant=1){if(id==='PLAYER_TRAVELER')id=this.s.flags.FLAG_TRV_AVATAR==='MALE'?'PLAYER_TRAVELER_MALE':this.s.flags.FLAG_TRV_AVATAR==='FEMALE'?'PLAYER_TRAVELER_FEMALE':id;if(id==='ENTITY_KATHERYNE')id='NPC_MOND_KATHERYNE';return oldAsset.call(this,id,variant)};

const priorSetParty=P.setParty;P.setParty=function(id,slot){const occupied=this.s.party[slot-1];if(occupied?.active&&occupied.source!==id)fail('PARTY_SLOT_OCCUPIED','이미 편성한 슬롯입니다. 빈 동료 슬롯을 선택해 주세요.');return priorSetParty.call(this,id,slot)};
const priorStoryFinish=P.finishBattle;P.finishBattle=function(victory){const result=priorStoryFinish.call(this,victory);this.s.global.STORY_CURSOR_NODE_ID=this.s.global.CURRENT_STORY_NODE_ID;return result};
const priorEnhance=P.enhance;P.enhance=function(slot){const inv=this.s.inventory.find(x=>x.slot===slot&&x.equip);if(inv){const profile=j(this.row('16_EQUIP_DB',inv.equip)[32]),ms=profile.milestones?.[inv.enhance+3];if(Object.keys(ms?.effect_override||{}).length)fail('UNSUPPORTED_EFFECT','이 단계의 고유효과는 아직 전투 실행기에 연결되지 않았습니다. 비용은 소비하지 않았습니다.');}return priorEnhance.call(this,slot)};
const priorQuestChoice=P.questChoice;P.questChoice=function(id,choice){if(this.s.global.PLAYER_HP_CURRENT<=0&&choice!=='leave')fail('PLAYER_DOWN','먼저 숙박·회복으로 전투불능에서 벗어나 주세요.');return priorQuestChoice.call(this,id,choice)};
if(typeof module!=='undefined'&&module.exports)module.exports=api;root.CRPGRuntime=api;
})(typeof globalThis!=='undefined'?globalThis:this);
