/* Audited combat adapter. Load after legacy runtime extensions; no source DB mutations. */
(function(root){'use strict';
const api=root.CRPGRuntime;if(!api)throw new Error('CRPGRuntime must be loaded first');
const {Runtime:R,RuleError}=api,P=R.prototype,copy=x=>JSON.parse(JSON.stringify(x)),j=(x,d={})=>{try{return JSON.parse(x)}catch{return d}},clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),round=Math.round;
const fail=(c,m)=>{throw new RuleError(c,m)},E={PYRO:'불',HYDRO:'물',CRYO:'얼음',ELECTRO:'번개',ANEMO:'바람',GEO:'바위',DENDRO:'풀',PHYSICAL:'물리'},element=e=>E[e]||e||'물리';
const oldApply=P.apply,oldView=P.view,oldFinish=P.finishBattle,oldCharacter=P.character,oldPlayer=P.player,oldValidate=P.validateSave;
const active=s=>s&&(!Number.isFinite(s.rounds)||s.rounds>0),status=(a,id)=>a.statuses?.find(s=>s.id===id&&active(s));
const special=new Set(['PLAYER_BASIC_ATTACK','PLAYER_BASIC_GUARD','MOND_AMBER_E','MOND_AMBER_Q','MOND_KAEYA_E','MOND_KAEYA_Q','MOND_LISA_E','MOND_LISA_Q','MOND_BARBARA_E','MOND_BARBARA_Q','MOND_DILUC_E','MOND_DILUC_Q','MOND_ALBEDO_E','MOND_ALBEDO_Q','MOND_DIONA_E','MOND_DIONA_Q','MOND_VENTI_Q','MOND_NOELLE_E','MOND_NOELLE_Q','MOND_MIKA_E','MOND_MIKA_Q','MOND_FISCHL_E','MOND_FISCHL_Q','MOND_RAZOR_E','MOND_RAZOR_Q','MOND_BENNETT_Q','MOND_DAHLIA_Q','MOND_KLEE_Q','MOND_MONA_Q','MOND_JEAN_E','MOND_JEAN_Q']);
const enemySpecial=new Set(['ECARD_DVALIN_AIRBORNE','ECARD_DVALIN_TERRAIN_CLOCK','ECARD_DVALIN_BREATH','ECARD_DVALIN_DIVE','ECARD_ABYSS_PYRO_SHIELD','ECARD_ABYSS_PYRO_RING','ECARD_MITA_AXE_SWEEP','ECARD_MITA_AXE_LEAP','ECARD_CICIN_ELECTRO_SUMMON','ECARD_CICIN_ELECTRO_BURST','ECARD_FATUI_GENERIC_DEVICE']);
P.character=function(id){const a=oldCharacter.call(this,id);a.statuses=copy(this.s.chars[id]?.statuses||[]);a.tags=String(this.row('07_CHAR_DB',id)[3]||'').match(/\[[^\]]+\]/g)||[];return a;};
P.player=function(){const a=oldPlayer.call(this);a.statuses=copy(this.s.playerStatuses||[]);return a;};
P.combatRows=function(n){return this.db[n]?this.rows(n):[]};
P.cardDefinition=function(r,enemy=false){const rawName=r[enemy?2:3],name=!enemy&&r[0]==='MOND_AMBER_E'?'토끼 백작':rawName;return{row:r,id:r[0],owner:r[enemy?1:2],name,kind:r[enemy?3:4],target:r[31]||'',script:String(r[32]||''),cooldown:Number(r[enemy?8:9]||0),level:Number(r[enemy?23:22]||1),range:r[enemy?20:19],weight:Number(r[enemy?15:20]||0),hit:Number(r[26]||0),condition:r[enemy?22:21]||'',trigger:r[30]||'',ready:r[35]==='READY',enemy};};
const authorBlockers={MOND_BENNETT_E:'자신의 밀려남을 처리할 이동 거리·목적지·효과 규칙이 없습니다.',MOND_DAHLIA_E:'설치물 접촉과 튀어오르기를 판정할 전장 위치 규칙이 없습니다.',MOND_KLEE_E:'지뢰 설치 위치·진입 범위·폭발 대상 범위 규칙이 없습니다.',MOND_MONA_E:'도발 허상의 내구도와 파괴 조건 값이 없습니다.',MOND_ROSARIA_E:'후방 이동 위치와 대형 대상 분류 규칙이 없습니다.',MOND_SUCROSE_E:'끌어당김의 이동 위치와 대상 분류 규칙이 없습니다.',MOND_SUCROSE_Q:'흡수 원소의 추가 피해 계수와 끌어당김 위치 규칙이 없습니다.',MOND_VENTI_E:'부유의 지속시간과 바람 내성 감소를 계산할 능력치 규칙이 없습니다.'};
P.cardSupport=function(c){if(!c.ready)return'이 카드의 실행 정의가 아직 준비되지 않았습니다.';if((c.enemy?enemySpecial:special).has(c.id))return'';if(authorBlockers[c.id])return authorBlockers[c.id];if(c.enemy&&/^DMG(?:_AOE)?:ATK\*[\d.]+:(?:[A-Z]+|ELEMENT=POWER_TAGS_ELEMENT):(?:ALLY_1|MAX[1-4]|ALLY_ALL)(?:;ON_HIT:NEXT_ACTION_SCORE-\d+)?$/.test(c.script))return'';return'이 카드의 전용 효과는 아직 구현되지 않았습니다.';};
P.combatSupportReport=function(){return ['08_SKILL_CARD_DB','12_ENEMY_CARD_DB'].flatMap((n,i)=>this.combatRows(n).filter(r=>r[0]&&r[0]!=='CARD_ID').map(r=>{const c=this.cardDefinition(r,!!i);return{id:c.id,owner:c.owner,supported:!this.cardSupport(c),reason:this.cardSupport(c),constraint:['MOND_JEAN_E','MOND_JEAN_Q'].includes(c.id)?'All living opponents must be explicit movement-immune bosses.':c.id==='MOND_MONA_Q'?'All living opponents must be explicit bosses; weak-target classification missing.':null,script:c.script}}));};
P.actorCards=function(a){if(a.source==='PLAYER_CUSTOM'){const owned=new Set(String(this.s.global.PLAYER_SKILL_CARD_IDS||'').split(';'));return this.combatRows('08_SKILL_CARD_DB').filter(r=>owned.has(r[0])&&r[1]==='PLAYER').map(r=>this.cardDefinition(r));}return this.combatRows(a.side==='ENEMY'?'12_ENEMY_CARD_DB':'08_SKILL_CARD_DB').filter(r=>r[a.side==='ENEMY'?1:2]===a.source&&r[a.side==='ENEMY'?3:4]!=='패시브'&&r[30]?.startsWith('ACTIVE')).map(r=>this.cardDefinition(r,a.side==='ENEMY'));};
P.combatActor=function(id='PLAYER_CUSTOM'){return this.s.runtime?.actors.find(a=>a.id===id)};
P.addCombatStatus=function(a,id,rounds,extra={}){a.statuses=a.statuses||[];const s={id,rounds:Number.isFinite(rounds)?rounds:null,createdRound:this.s.runtime?.round||0,...extra},old=a.statuses.find(x=>x.id===id);if(old)Object.assign(old,s);else a.statuses.push(s);return s;};
P.combatTags=function(a){const removed=(a.statuses||[]).filter(active).flatMap(s=>s.removeTags||[]);return(a.tags||[]).filter(t=>!removed.includes(t));};
P.combatStat=function(a,key){let n=Number(a[key]||0);for(const s of a.statuses||[]){if(!active(s))continue;if(s.mods?.[key]){const m=s.mods[key];n=n*(1+(m.pct||0)/100)+(m.flat||0);}if(key==='def'&&s.id==='STATUS_DEF_DOWN')n*=1-Number(s.value||15)/100;if(key==='spd'&&s.id==='STATUS_SLOW')n+=Number(s.value??-10);if(key==='spd'&&s.id==='BOSS_CONTROL')n-=20;}return n;};
P.shield=function(a,value,source,rounds,extra={}){a.shields=a.shields||[];const amount=round(value),old=a.shields.find(x=>x.source===source);if(old){old.value=Math.max(old.value,amount);old.initialValue=Math.max(Number(old.initialValue||0),amount);old.rounds=rounds;old.createdRound=this.s.runtime.round;Object.assign(old,extra);}else a.shields.push({source,value:amount,initialValue:Number(extra.initialValue||amount),rounds,createdRound:this.s.runtime.round,...extra});};
P.heal=function(a,amount,source=''){if(a.hp<=0)return 0;let n=Math.max(0,round(amount)),bond=status(a,'STATUS_BOND_OF_LIFE');if(bond){const used=Math.min(n,Number(bond.value||bond.bondValue||0));n-=used;bond.value=Number(bond.value||bond.bondValue||0)-used;}const applied=Math.min(a.maxHp-a.hp,n);a.hp+=applied;this.s.runtime?.log.push({actor:source,target:a.name,heal:applied});return applied;};
P.hasAirAccess=function(a,t,range){return !t.airborne||['원거리','전장','대공','부유'].includes(range||a.range)||!!status(a,'LEVITATION')||!!status(a,'STATUS_TACTICAL_LEVITATION')||(t.source==='BOSS_DVALIN'&&!!status(a,'EXPLICIT_ACCESS_TO_BOSS_DVALIN'));};
P.cardTargets=function(a,c){const b=this.s.runtime;if(!b)return[];let ts=b.actors.filter(x=>x.hp>0);if(c.target==='SELF')return ts.filter(x=>x.id===a.id);if(c.kind==='지원'&&/^HEAL_ALL/.test(c.script))return ts.filter(x=>x.side===a.side);return ts.filter(x=>x.side!==a.side&&this.hasAirAccess(a,x,c.id==='PLAYER_BASIC_ATTACK'?a.range:c.range));};
P.cardReason=function(a,c){if(!this.s.runtime)return'전투 중에 사용할 수 있습니다.';if(a.hp<=0)return'전투불능 상태입니다.';if(this.s.runtime.interlude)return'현재 대화를 마친 뒤 행동할 수 있습니다.';if(this.s.runtime.subduedPending)return'마지막 행동을 선택해 주세요.';let support=this.cardSupport(c);if(support)return support;if(a.level<c.level)return`${c.level}레벨부터 사용할 수 있습니다.`;if((a.cooldowns[c.id]||0)>0)return`재사용까지 ${a.cooldowns[c.id]}턴 남았습니다.`;if(status(a,'STATUS_FREEZE'))return'빙결 상태로 행동할 수 없습니다.';if(c.id==='ECARD_CICIN_ELECTRO_SUMMON'&&(a.cicinCount||0)>1)return'소환물이 이미 유지 중입니다.';if(c.id==='ECARD_FATUI_GENERIC_DEVICE'&&(a.hp/a.maxHp>.7||status(a,'FATUI_DEVICE')))return'장비 강화 조건이 충족되지 않았습니다.';if(c.id==='ECARD_ABYSS_PYRO_RING'&&this.s.runtime.actors.filter(t=>t.side!==a.side&&t.hp>0).length<2)return'광역 공격 대상이 부족합니다.';if(c.id==='MOND_BARBARA_E'&&status(a,'STATUS_BARBARA_MELODY_LOOP'))return'노래의 고리가 이미 유지 중입니다.';if(c.id==='MOND_FISCHL_E'&&this.s.runtime.fields.some(f=>f.kind==='OZ'&&f.actor===a.id))return'소환물이 이미 유지 중입니다.';const attack=/DMG|MULTIHIT|BUNNY|LIGHTNING_ROSE|ICE_BLADES/.test(c.script);if(attack&&!this.cardTargets(a,c).length&&c.id!=='MOND_AMBER_E')return'현재 사거리로 공격할 수 있는 대상이 없습니다.';return'';};
P.combatCards=function(owner='PLAYER_CUSTOM'){const b=this.s.runtime,a=this.combatActor(owner);if(!b||!a)return[];let cards=this.actorCards(a).map(c=>({id:c.id,name:c.name,row:c.row,description:c.row[c.enemy?17:16],targetMode:c.target,reason:this.cardReason(a,c),cooldown:a.cooldowns[c.id]||0,targets:this.cardTargets(a,c).map(t=>({id:t.id,name:t.name,hp:t.hp,maxHp:t.maxHp})),branches:c.id==='MOND_LISA_E'?['TAP','CHARGE']:c.id==='MOND_RAZOR_E'?['TAP','HOLD']:[]}));
 const system=(id,name,reason,targets=[a])=>cards.push({id,name,reason,targets:targets.map(t=>({id:t.id,name:t.name,hp:t.hp,maxHp:t.maxHp})),cooldown:0,system:true});
 const living=b.actors.filter(x=>x.side===a.side&&x.hp>0);for(const id of ['TRPG_HEALING_POTION','TRPG_BANDAGE','TRPG_MEDKIT'])if(this.itemCount(id)>0){const self=id==='TRPG_HEALING_POTION',lock=self?'STATUS_COMBAT_POTION_LOCK':'STATUS_RECENTLY_BANDAGED',ts=(self?[a]:living).filter(t=>!status(t,lock)&&t.hp<t.maxHp);system('ITEM:'+id,this.row('14_ITEM_DB',id)[1],b.interlude?'현재 대화를 마쳐 주세요.':b.subduedPending?'마지막 행동을 선택해 주세요.':!ts.length?'사용 가능한 회복 대상이 없습니다.':'',ts);}
 if((b.toolCharges?.TRPG_TACTICAL_LEVITATOR||0)>0)system('TOOL:TRPG_TACTICAL_LEVITATOR',this.row('14_ITEM_DB','TRPG_TACTICAL_LEVITATOR')[1],b.interlude?'현재 대화를 마쳐 주세요.':b.subduedPending?'마지막 행동을 선택해 주세요.':'',living);
 if(b.storyConfig?.field_access_action){const f=b.storyConfig.field_access_action;system(f.id,f.label,b.interlude?'현재 대화를 마쳐 주세요.':b.subduedPending?'마지막 행동을 선택해 주세요.':status(a,f.effect)?'발판의 효과가 이미 적용 중입니다.':'');}
 if(b.storyConfig?.orb_action&&a.source==='PLAYER_CUSTOM'){const f=b.storyConfig.orb_action,t=b.actors.find(x=>x.source==='BOSS_DVALIN');system(f.id,f.label,b.interlude?'현재 대화를 마쳐 주세요.':b.orbChannel?'이미 구슬의 빛을 비췄습니다.':a.hp<=0?'전투불능 상태입니다.':!this.itemCount(f.requires_item)||!this.s.flags[f.requires_flag]?'필요한 물건을 가지고 있지 않습니다.':t.hp/t.maxHp>f.hp_ratio_lte?'아직 적을 더 제압해야 합니다.':'',t?[t]:[]);}
 return cards;};
P.combatStoryConfig=function(group){const p=this.combatRows('51_EVENT_DB').map(r=>j(r[13])).find(p=>p.handler==='isk_m04_combat'&&p.kind==='battle_result'&&p.group_id===group);return p?{...copy(p.config),eventId:this.combatRows('51_EVENT_DB').find(r=>j(r[13]).config?.group_id===group&&j(r[13]).kind==='battle_result')[0]}:null;};
P.battlePreparation=function(group){const cfg=this.combatStoryConfig(group);if(!cfg)return null;return{group,node:cfg.node_id,max:cfg.party_max,active:this.s.party.filter(x=>x.active).map(x=>x.source),guests:cfg.guest_char_ids.map(id=>({id,name:this.row('07_CHAR_DB',id)[1],owned:['JOINED'].includes(j(this.s.global.COMPANION_ELIGIBILITY_JSON)[id]?.state)}))};};
P.confirmBattlePreparation=function(group,companions){const cfg=this.combatStoryConfig(group),pending=this.s.battlePreparation;if(!cfg||!pending||pending.group!==group||this.s.global.CURRENT_STORY_NODE_ID!==cfg.node_id)fail('PREPARATION','현재 전투 준비 장면이 아닙니다.');if(!Array.isArray(companions)||companions.length>3||new Set(companions).size!==companions.length)fail('PARTY','동료는 중복 없이 최대 3명까지 선택해 주세요.');const owned=j(this.s.global.COMPANION_ELIGIBILITY_JSON);for(const id of companions)if(!cfg.guest_char_ids.includes(id)&&!['JOINED'].includes(owned[id]?.state))fail('OWNER','참가할 수 없는 인물입니다.');return this.startBattle(group,'STORY:'+cfg.node_id,{confirmed:true,companions});};
P.initCombatActor=function(a,slot){a.statuses=copy(a.statuses||[]);a.shields=[];a.cooldowns={};a.turns=0;a.slot=slot;a.tactic=this.s.party.find(p=>p.source===a.source)?.tactic||'균형';if(slot===2)a.crit+=5;if(slot===3){a.maxHp=round(a.maxHp*1.05);}if(slot===4)a.slotDamageMultiplier=.8;const pending=this.s.pendingCombatEffects?.[a.source]||[];for(const s of pending){const id=s.id;let mods;if(id==='STATUS_FOOD_ATK')mods={atk:{pct:8}};if(id==='STATUS_FOOD_FEAST')mods={atk:{pct:12},crit:{flat:5}};if(id==='STATUS_FOOD_RESIST')mods={resist:{flat:5}};if(id==='STATUS_FOOD_SPEED')mods={spd:{flat:4}};if(!mods)fail('FOOD_EFFECT','아직 처리할 수 없는 식사 효과입니다.');a.statuses.push({id,rounds:null,createdRound:0,mods,sourceItem:s.sourceItem});}return a;};
// v0.13.2 stage 1: one field-party policy, applied once at construction.
// These preserve the small-party assistance, not a final combat rebalance.
// HP is based on the monster's level-scaled authored value; the old tier HP
// multiplication and additional 3/4-member HP boosts do not stack on this path.
P.fieldBattlePolicy=function(groupRow,origin,allies,members){
 if(groupRow[6]!=='PARTY_BANDED'||!(origin==='RANDOM'||origin.startsWith('QUEST:')))return null;
 const present=members.filter(m=>Number(m[5])>0).map(m=>this.row('09_MONSTER_DB',m[3]));
 if(!present.length||present.some(r=>r[3]==='보스'))return null;
 const party=Math.max(1,Math.min(4,allies.filter(a=>a.hp>0).length));
 const ordinary=present.every(r=>r[3]==='일반');
 return {version:4,kind:'PARTY_BANDED_FIELD',party,maxEnemies:party,
  hpFactor:[.30,.50,.75,1][party-1],
  atkFactor:(ordinary?[.4725,.845,.9775,1.15]:[.35,.65,.85,1])[party-1]};
};
P.limitFieldBattle=function(b,policy){
 if(!policy)return;
 const enemies=b.actors.filter(a=>a.side==='ENEMY');
 const ranked=enemies.map((a,index)=>({a,index,weight:({일반:1,정예:2,강적:3}[a.grade]||1)})).sort((a,c)=>c.weight-a.weight||a.index-c.index);
 // Keep an authored elite first; then retain different existing enemy types
// before duplicates. This never imports a monster from a different map/group.
 const unique=[],duplicates=[],seen=new Set();
 for(const entry of ranked){if(seen.has(entry.a.source))duplicates.push(entry);else{seen.add(entry.a.source);unique.push(entry);}}
 const keep=new Set([...unique,...duplicates].slice(0,policy.maxEnemies).map(x=>x.a.id));
 b.actors=b.actors.filter(a=>a.side==='ALLY'||keep.has(a.id));
 b.order=b.order.filter(turn=>b.actors.some(a=>a.id===turn.id));
 if(b.opening)b.opening.initialOrder=copy(b.order);
 b.balanceProfile={...policy,authoredEnemies:enemies.length,spawnedEnemies:keep.size};
};
P.startBattle=function(group,origin='EXPLICIT',options={}){if(this.s.runtime)fail('COMBAT','이미 전투 중입니다.');const cfg=this.combatStoryConfig(group);if(cfg){if(origin!=='STORY:'+cfg.node_id||this.s.global.STORY_ROUTE_ID!==(cfg.route||'ROUTE_ISEKAI')||this.s.global.CURRENT_STORY_NODE_ID!==cfg.node_id||this.s.global.CURRENT_MAP_ID!==cfg.map_id)fail('BATTLE_SOURCE','현재 이야기 장면과 전투가 일치하지 않습니다.');const orb=cfg.orb_action;if(orb&&(!this.itemCount(orb.requires_item)||!this.s.flags[orb.requires_flag]))fail('ORB_STATE','전투에 필요한 물건의 소유 기록이 일치하지 않습니다.');if(!options.confirmed){this.s.battlePreparation={group,origin,node:cfg.node_id};this.s.global.SCREEN_MODE='COMBAT_PREP';return{pendingPreparation:true,...this.battlePreparation(group)};}}
 const gr=this.row('33_ENCOUNTER_GROUP_DB',group),members=this.combatRows('49_ENCOUNTER_MEMBER_DB').filter(r=>r[1]===group);if(!members.length)fail('GROUP','적 편성 정의가 없습니다.');const owned=j(this.s.global.COMPANION_ELIGIBILITY_JSON),party=cfg?[{source:'PLAYER_CUSTOM',type:'PLAYER'},...options.companions.map(source=>({source,type:'CHAR'}))]:this.s.party.filter(p=>p.active);if(party.length>4||!party.some(p=>p.source==='PLAYER_CUSTOM')||new Set(party.map(p=>p.source)).size!==party.length)fail('PARTY','주인공을 포함한 최대 4명의 파티가 필요합니다.');const snapshots=this.s.guestSnapshots||(this.s.guestSnapshots={}),gate=cfg?.node_id;if(gate&&!snapshots[gate])snapshots[gate]={};
 const actors=party.map((p,i)=>{const guest=p.type!=='PLAYER'&&cfg&&cfg.guest_char_ids.includes(p.source)&&!['JOINED'].includes(owned[p.source]?.state);let a;if(p.type==='PLAYER')a=this.player();else if(guest&&snapshots[gate][p.source])a=copy(snapshots[gate][p.source]);else{a=this.character(p.source);if(guest){const r=this.row('07_CHAR_DB',p.source),lv=this.row('26_LEVEL_RULES',Number(r[4]||1));a.level=Number(r[4]||1);a.maxHp=round(Number(r[7])*Number(lv[4]));a.hp=a.maxHp;a.atk=round(Number(r[8])*Number(lv[5]));a.def=round(Number(r[9])*Number(lv[5]));a.spd=Number(r[10])+Number(lv[6]);const prof=2+Math.floor((a.level-1)/4);a.crit=Number(r[16]);a.critDmg=Number(r[17]);a.hit=Math.min(95,75+prof*2);a.eva=Math.max(3,5+Math.round((a.spd-60)/10));a.resist=5+prof*2;a.statuses=[];a.cooldowns={};a.guest=true;snapshots[gate][p.source]=copy(a);}}a.guest=!!guest;return this.initCombatActor(a,cfg?i+1:Number(String(p.slot||'PARTY_'+(i+1)).split('_').pop()));});if(!actors.some(a=>a.hp>0))fail('PARTY_DOWN','파티가 전투불능입니다. 회복 후 다시 준비해 주세요.');
 const fieldPolicy=this.fieldBattlePolicy(gr,origin,actors,members),mapRow=this.tables['32_MAP_DB']?.get(this.s.global.CURRENT_MAP_ID),liyueRecommended=gr[6]==='PARTY_BANDED'&&(origin==='RANDOM'||origin.startsWith('QUEST:'))&&mapRow?.[1]==='리월'&&mapRow?.[12]!=='Y',levelMin=liyueRecommended?Number(mapRow[6]):Number(gr[4]),levelMax=liyueRecommended?Number(mapRow[7]):Number(gr[5]),targetLevel=gr[6]==='PARTY_BANDED'?clamp(round(actors.reduce((v,a)=>v+a.level,0)/actors.length)+this.die(3)-2,levelMin,levelMax):null,seq={};for(const m of members){const r=this.row('09_MONSTER_DB',m[3]),cards=this.combatRows('12_ENEMY_CARD_DB').filter(c=>c[1]===r[0]&&c[35]==='READY');if(r[3]==='보스'&&!['BOSS_DVALIN','BOSS_ANDRIUS'].includes(r[0])&&!this.supportsLiyueBoss?.(r[0]))fail('UNSUPPORTED_BOSS','이 보스의 전용 전투 규칙은 아직 구현되지 않았습니다.');const unsupported=cards.filter(c=>this.cardSupport(this.cardDefinition(c,true)));if(unsupported.length)fail('UNSUPPORTED_ENEMY','이 적의 전용 카드가 아직 구현되지 않았습니다: '+unsupported[0][2]);const level=targetLevel||Number(r[18]);if(!level)fail('LEVEL','적 레벨 정의가 없습니다.');const base=this.row('26_LEVEL_RULES',Number(r[18])),lv=this.row('26_LEVEL_RULES',level),tier=targetLevel?({'일반':[2,1.1,1.05],'정예':[2.8,1.15,1.15],'강적':[4,1.25,1.2]}[r[3]]||[1,1,1]):[1,1,1],count=Number(m[4])+Math.floor(this.random()*(Number(m[5])-Number(m[4])+1));for(let k=0;k<count;k++){const hp=round(Number(r[6])*(targetLevel?lv[4]/base[4]:1)*(fieldPolicy?fieldPolicy.hpFactor:tier[0]*(r[3]!=='보스'&&actors.filter(x=>x.side==='ALLY').length>=3?(party.length>=4?1.2:1.1):1)));const elems=[...String(r[5]).matchAll(/\[(불|물|얼음|번개|바람|바위|풀)\]/g)].map(x=>x[1]);actors.push({id:r[0]+'#'+(seq[r[0]]=(seq[r[0]]||0)+1),source:r[0],name:r[1],side:'ENEMY',control:'AI',hp,maxHp:hp,atk:round(Number(r[7])*(targetLevel?lv[5]/base[5]:1)*tier[1]*(fieldPolicy?fieldPolicy.atkFactor:1)),def:round(Number(r[8])*(targetLevel?lv[5]/base[5]:1)*tier[2]),crit:Number(r[9]),critDmg:Number(r[10]),level,spd:Number(r[19])+(targetLevel?lv[6]-base[6]:0),hit:targetLevel?Math.min(95,75+Number(lv[3])*2):Number(r[20]),eva:Number(r[21]),resist:Number(r[22]),range:r[23],grade:r[3],tags:String(r[5]||'').match(/\[[^\]]+\]/g)||[],tactic:r[24],nativeAura:r[0].startsWith('MON_SLIME_')&&elems.length===1?elems[0]:null,aura:r[0].startsWith('MON_SLIME_')&&elems.length===1?elems[0]:null,statuses:[],cooldowns:{},shields:[],turns:0,airborne:r[0]==='BOSS_DVALIN',element:elems.length===1?elems[0]:'물리',hasDedicatedCards:cards.length>0});}}
 const id=this.s.global.SAVE_ID+':B'+(this.s.global.LAST_COMMITTED_ACTION_SEQ+1),b=this.s.runtime={combatVersion:1,id,group,origin,round:1,actors,order:[],cursor:0,phase:'START',ticks:{},log:[],fields:[],terrain:actors.some(a=>a.source==='BOSS_DVALIN')?4:null,storyConfig:cfg,interludeSeen:{},pendingInterludes:[],toolCharges:{},actionSequence:0};b.relationshipTarget=this.relationshipBattleTarget?.(b)||null;if(typeof this.tacticalCapacity==='function'&&(this.s.preparedTools||[]).length>this.tacticalCapacity())fail('TOOL_CAPACITY','현재 파티의 전술 도구 준비 한도를 초과했습니다.');for(const item of this.s.preparedTools||[])if(this.itemCount(item)>0&&item==='TRPG_TACTICAL_LEVITATOR')b.toolCharges[item]=3;for(const a of actors)if(a.side==='ALLY'&&this.s.pendingCombatEffects)delete this.s.pendingCombatEffects[a.source];for(const a of actors)if(a.source==='MON_ABYSS_MAGE_PYRO')this.shield(a,a.maxHp*.35,'ECARD_ABYSS_PYRO_SHIELD',null,{element:'불',damageMultipliers:{물:2,얼음:1.5}});delete this.s.battlePreparation;Object.assign(this.s.global,{ACTIVE_BATTLE_ID:id,MODE:'COMBAT',SCREEN_MODE:'COMBAT'});this.newRound();this.limitFieldBattle(b,fieldPolicy);this.autoUntilPlayer();return{battle:id,group};};
P.applyDamage=function(a,t,amount,details={}){const b=this.s.runtime;let n=Math.max(0,round(amount)),absorbed=0;const broken=[];for(const sh of (t.shields||[]).sort((x,y)=>y.value-x.value)){const multiplier=Number(sh.damageMultipliers?.[details.element]||1)*(Number.isFinite(details.shieldDamageMultiplier)&&details.shieldDamageMultiplier>0?details.shieldDamageMultiplier:1),hit=Math.min(sh.value,n*multiplier);sh.value-=hit;n-=hit/multiplier;absorbed+=hit;if(sh.value<=0)broken.push(copy(sh));}t.shields=(t.shields||[]).filter(s=>s.value>0);n=round(Math.max(0,n));t.hp=Math.max(0,t.hp-n);b.log.push({actor:a.name,target:t.name,damage:n,absorbed:round(absorbed),...(broken.length?{brokenShields:broken.map(s=>s.source)}:{}),...details});for(const sh of broken)if(sh.hymnSide&&t.hp>0&&(b.hymn?.[sh.hymnSide]||0)>0){b.hymn[sh.hymnSide]--;t.shields.push({...sh,value:round(sh.initialValue*.5)});b.log.push({target:t.name,reshield:round(sh.initialValue*.5),hymnRemaining:b.hymn[sh.hymnSide]});}return n;};
P.reactionFor=function(t,el){return this.combatRows('37_ELEMENTAL_REACTION_DB').filter(r=>r[0]&&!String(r[0]).includes('LUNAR')&&!String(r[0]).includes('STELLAR')&&String(r[2]).split('/').includes(t.aura)&&String(r[3]).split('/').includes(el)&&t.aura!==el).sort((a,b)=>Number(b[12])-Number(a[12]))[0]||null;};
P.reactionSupportReason=function(a,t,el){const rx=this.reactionFor(t,element(el));if(!rx)return'';const neighbors=this.s.runtime.actors.filter(x=>x.side===t.side&&x.id!==t.id&&x.hp>0);if(['TRANSFORM','TRANSFORM_STATUS','TRANSFORM_AREA'].includes(rx[17])&&neighbors.length)return'범위 원소 반응의 인접 대상 규칙이 아직 정의되지 않았습니다.';if(rx[0]==='RX_OVERLOADED'&&t.grade!=='보스')return'과부하의 약한 적 밀치기 규칙이 아직 정의되지 않았습니다.';if(rx[0]==='RX_ELECTROCHARGED'&&neighbors.some(n=>n.aura==='물'))return'감전 전이의 인접 대상 규칙이 아직 정의되지 않았습니다.';if(!['AMPLIFY','TRANSFORM','TRANSFORM_STATUS','TRANSFORM_AREA','CONTROL','DOT_STATE','SHIELD_CREATE'].includes(rx[17]))return'이 원소 반응의 실행 효과는 아직 구현되지 않았습니다.';return'';};
P.combatDamageMultiplier=function(){return 1;};
P.damage=function(a,t,k,el='PHYSICAL',o={}){const b=this.s.runtime;if(!t||t.hp<=0)return false;el=element(el);const reactionReason=!o.noAura?this.reactionSupportReason(a,t,el):'';if(reactionReason)fail('UNSUPPORTED_REACTION',reactionReason);const range=o.range||a.range;if(!this.hasAirAccess(a,t,range))return false;if(status(t,'LEVITATION')&&range==='근접'&&!a.airborne){b.log.push({actor:a.name,target:t.name,miss:true,reason:'부양'});return false;}const shieldEva=(t.shields||[]).some(s=>s.evaBonus)?Math.max(...t.shields.map(s=>s.evaBonus||0)):0;if(!o.sureHit&&this.die()>clamp(this.combatStat(a,'hit')-this.combatStat(t,'eva')-shieldEva+10+(o.hitBonus||0),65,98)){b.log.push({actor:a.name,target:t.name,miss:true});return false;}const attach=['불','물','얼음','번개','바람','바위','풀'].includes(el)&&!o.noAura,rx=attach?this.reactionFor(t,el):null;let mult=Number(rx?.[6]||1)*(t.slotDamageMultiplier||1)*(t.guard?.5:1)*(status(t,'FALLBACK_DEFENSE')?.damageMultiplier||1),raw=this.combatStat(a,o.stat||'atk')*k+(o.rawAdd||0);if(t.airborne&&!['원거리','전장','대공','부유'].includes(range)&&!status(a,'LEVITATION')&&(status(a,'STATUS_TACTICAL_LEVITATION')||status(a,'EXPLICIT_ACCESS_TO_BOSS_DVALIN')))mult*=.85;if(status(a,'SKILL_COEFF'))raw*=1.3;if(status(a,'DILUC_INFUSION')&&el==='불')mult*=1.2;if((a.cicinCount||0)>0&&el==='번개'&&!o.sourceKind)mult*=1.1;if(status(t,'PHYS_VULN')&&el==='물리')mult*=1.25;const bubble=status(t,'ILLUSORY_BUBBLE');if(bubble)mult*=1.3;if(status(t,'OMEN'))mult*=1.15;if(status(a,'BOSS_CONTROL'))mult*=.9;mult*=this.combatDamageMultiplier(a,t,el,o);if(bubble)t.statuses=t.statuses.filter(s=>s!==bubble);const crit=!o.noCrit&&this.die()<=this.combatStat(a,'crit'),dmg=round(Math.max(1,raw*100/(100+this.combatStat(t,'def'))*(crit?1+this.combatStat(a,'critDmg')/100:1)*mult*(.95+.1*this.random())));this.applyDamage(a,t,dmg,{element:el,critical:crit,reaction:rx?.[0]||null,card:o.card||null,sourceKind:o.sourceKind||null});
 if(attach){if(rx){const base=25+12*a.level,kind=rx[17];if(['TRANSFORM','TRANSFORM_STATUS','TRANSFORM_AREA'].includes(kind)){const damage=round(base*Number(rx[7]));/* Multi-target area reactions are preflight-rejected until adjacency is authored. */this.applyDamage(a,t,damage,{element:element(rx[5]==='흡수 원소'?t.aura:rx[5]),reaction:rx[0],sourceKind:'REACTION'});if(kind==='TRANSFORM_STATUS')this.addCombatStatus(t,'PHYS_VULN',2);}else if(kind==='CONTROL'){if(t.grade==='보스')this.addCombatStatus(t,'BOSS_CONTROL',1);else this.addCombatStatus(t,'STATUS_FREEZE',Number(rx[9]));}else if(kind==='DOT_STATE')this.addCombatStatus(t,rx[22],Number(rx[9]),{tickDamage:round(base*Number(rx[7])),actor:a.id,element:rx[5]});else if(kind==='SHIELD_CREATE')this.shield(a,base*Number(rx[7]),'RX_CRYSTALLIZE',Number(rx[9]));if(rx[20]==='CONSUME_EXISTING_AURA')t.aura=t.nativeAura||null;}else if(!t.nativeAura)t.aura=el;}
 if(bubble&&t.hp>0){const source=b.actors.find(x=>x.id===bubble.actor);if(source){this.damage(source,t,.9,'HYDRO',{range:'전장',sourceKind:'BUBBLE'});this.addCombatStatus(t,'OMEN',2);}}if((a.cicinCount||0)>0&&!o.sourceKind&&t.hp>0)this.damage(a,t,.20,'ELECTRO',{range:'원거리',sourceKind:'ASSIST'});return true;};
P.basicHit=function(a,t,k){const noCards=a.side==='ENEMY'&&!a.hasDedicatedCards;let coef=k??(noCards?({일반:.85,정예:1,강적:1.15}[a.grade]||.65):.65),el=a.side==='ENEMY'?a.element:'물리';if(status(a,'DILUC_INFUSION'))el='불';let add=0;if(status(a,'NOELLE_SWEEP')){el='바위';add=this.combatStat(a,'def')*.6;}const hit=this.damage(a,t,coef,el,{rawAdd:add,range:status(a,'NOELLE_SWEEP')?({근접:'중거리',중거리:'원거리'}[a.range]||a.range):a.range});if(hit){if(status(a,'STATUS_BARBARA_MELODY_LOOP'))for(const ally of this.s.runtime.actors.filter(x=>x.side===a.side))this.heal(ally,a.maxHp*.06,a.name);if((a.shields||[]).some(s=>s.source==='MOND_NOELLE_E')&&a.noelleHealRound!==this.s.runtime.round&&this.die()<=50){a.noelleHealRound=this.s.runtime.round;for(const ally of this.s.runtime.actors.filter(x=>x.side===a.side))this.heal(ally,this.combatStat(a,'def')*.25,a.name);}if(status(a,'THUNDERWOLF'))this.damage(a,t,.45,'ELECTRO',{sourceKind:'FOLLOWUP'});const feather=status(a,'HAWK_FEATHER');if(feather&&a.featherHealRound!==this.s.runtime.round){a.featherHealRound=this.s.runtime.round;this.heal(a,feather.sourceMaxHp*.04,'매의 깃털');}}return hit;};
P.addField=function(kind,a,rounds,extra={}){const b=this.s.runtime,f={kind,actor:a.id,side:a.side,rounds,createdRound:b.round,...extra};const prior=b.fields.find(x=>x.kind===kind&&x.actor===a.id);if(prior)Object.assign(prior,f);else b.fields.push(f);return f;};
P.executeCard=function(a,c,target,branch){const b=this.s.runtime,allies=b.actors.filter(x=>x.side===a.side&&x.hp>0),enemies=b.actors.filter(x=>x.side!==a.side&&x.hp>0),legal=enemies.filter(t=>this.hasAirAccess(a,t,c.range)),picked=legal.find(t=>t.id===target),ts=this.combatOrderedTargets?this.combatOrderedTargets(a,legal,target):(picked?[picked,...legal.filter(t=>t!==picked)]:legal),ally=allies.find(t=>t.id===target)||allies.slice().sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0];const damage=(t,k,el,o={})=>this.damage(a,t,k,el,{range:c.range,hitBonus:c.hit,card:c.id,...o}),many=(k,el,max=4)=>ts.slice(0,max).forEach(t=>damage(t,k,el)),multi=(coeffs,el,max=1)=>ts.slice(0,max).forEach(t=>{let applied=false;for(const k of coeffs){if(t.hp<=0)break;const h=damage(t,k,el,{noAura:applied});if(h)applied=true;}}),healAll=(stat,k)=>allies.forEach(t=>this.heal(t,this.combatStat(a,stat)*k,a.name));
 switch(c.id){
 case'PLAYER_BASIC_ATTACK':if(!picked)fail('TARGET','공격할 대상을 선택해 주세요.');this.basicHit(a,picked,j(c.row[36]).coefficient||.65);break;
 case'PLAYER_BASIC_GUARD':a.guard=true;b.log.push({actor:a.name,guard:true});break;
 case'MOND_AMBER_E':this.addField('BUNNY',a,1,{hp:Math.floor(a.maxHp*.25),def:a.def,explodeAt:b.round+1});break;
 case'MOND_AMBER_Q':multi(Array(5).fill(.28),'PYRO',4);break;
 case'MOND_KAEYA_E':if(ts[0])damage(ts[0],1.25,'CRYO');break;
 case'MOND_KAEYA_Q':this.addField('ICE',a,3);break;
 case'MOND_LISA_E':if(branch==='CHARGE'){a.charging={card:c.id,resolveTurn:a.turns+1};}else if(ts[0]&&damage(ts[0],.5,'ELECTRO'))ts[0].conduction=Math.min(3,(ts[0].conduction||0)+1);break;
 case'MOND_LISA_Q':for(const t of ts.slice(0,4))if(damage(t,.6,'ELECTRO'))this.addCombatStatus(t,'STATUS_DEF_DOWN',2,{value:15});this.addField('ROSE',a,2);break;
 case'MOND_BARBARA_E':this.addCombatStatus(a,'STATUS_BARBARA_MELODY_LOOP',2);break;
 case'MOND_BARBARA_Q':healAll('maxHp',.25);break;
 case'MOND_DILUC_E':multi([.45,.5,.65],'PYRO');break;
 case'MOND_DILUC_Q':many(1.8,'PYRO');this.addCombatStatus(a,'DILUC_INFUSION',2);break;
 case'MOND_ALBEDO_E':if(ts[0])damage(ts[0],.9,'GEO');this.addCombatStatus(ally,'LEVITATION',1);break;
 case'MOND_ALBEDO_Q':many(1.4,'GEO');for(const t of allies)this.addCombatStatus(t,'SKILL_COEFF',1);break;
 case'MOND_DIONA_E':if(ts[0])damage(ts[0],.8,'CRYO');this.shield(ally,a.maxHp*.18,c.id,2,{evaBonus:5});break;
 case'MOND_DIONA_Q':many(.7,'CRYO',3);this.addField('FROST_MIST',a,2);break;
 case'MOND_VENTI_Q':for(const t of ts){const absorbed=['불','물','얼음','번개'].includes(t.aura)?t.aura:'바람';let applied=false;for(let i=0;i<5;i++){const hit=damage(t,.3,absorbed,{noAura:applied});if(hit)applied=true;}}const player=allies.find(t=>t.source==='PLAYER_CUSTOM');if(player)player.firstNextRound=b.round+1;break;
 case'MOND_NOELLE_E':for(const t of ts.slice(0,3))damage(t,.6,'GEO',{stat:'def'});this.shield(a,this.combatStat(a,'def')*1.6,c.id,2);break;
 case'MOND_NOELLE_Q':for(const t of ts.slice(0,4))damage(t,.9,'GEO',{stat:'def'});this.addCombatStatus(a,'NOELLE_SWEEP',2);break;
 case'MOND_MIKA_E':if(ts[0])damage(ts[0],.8,'CRYO');for(const t of ts.slice(1,4))damage(t,.3,'CRYO');for(const t of allies)this.addCombatStatus(t,'MIKA_SPEED',2,{mods:{spd:{flat:10}}});break;
 case'MOND_MIKA_Q':healAll('maxHp',.12);for(const t of allies)this.addCombatStatus(t,'HAWK_FEATHER',2,{sourceMaxHp:a.maxHp});break;
 case'MOND_FISCHL_E':many(.8,'ELECTRO',3);this.addField('OZ',a,2);break;
 case'MOND_FISCHL_Q':many(1.1,'ELECTRO',4);this.addField('OZ',a,2);break;
 case'MOND_RAZOR_E':if(branch==='HOLD'){many(1.4,'ELECTRO',3);if((a.razorSigils||0)>=2)a.cooldowns.MOND_RAZOR_Q=Math.max(0,(a.cooldowns.MOND_RAZOR_Q||0)-1);a.razorSigils=0;}else {if(ts[0])damage(ts[0],.9,'ELECTRO');a.razorSigils=Math.min(3,(a.razorSigils||0)+1);}break;
 case'MOND_RAZOR_Q':many(.8,'ELECTRO',3);this.addCombatStatus(a,'THUNDERWOLF',2,{mods:{spd:{flat:10}}});break;
 case'MOND_BENNETT_Q':this.addField('ENCOURAGEMENT',a,2);for(const t of allies)if((t.tags||[]).includes('[불]'))this.addCombatStatus(t,'ENCOURAGEMENT_ATK',2,{mods:{atk:{pct:20}}});for(const t of enemies)this.addCombatStatus(t,'ENCOURAGEMENT_TAG',2,{removeTags:['[광계]']});break;
 case'MOND_DAHLIA_Q':many(.9,'HYDRO',Infinity);b.hymn=b.hymn||{};b.hymn[a.side]=2;for(const t of allies)this.shield(t,a.maxHp*.16,c.id,2,{hymnSide:a.side,initialValue:round(a.maxHp*.16)});break;
 case'MOND_KLEE_Q':this.addField('BOMBARD',a,2);break;
 case'MOND_MONA_Q':for(const t of ts.slice(0,4)){if(!t.nativeAura)t.aura='물';this.addCombatStatus(t,'ILLUSORY_BUBBLE',1,{actor:a.id});}break;
 case'MOND_JEAN_E':many(1.2,'ANEMO',3);break;
 case'MOND_JEAN_Q':healAll('atk',1.2);many(.7,'ANEMO',4);this.addField('DANDELION',a,2);break;
 case'ECARD_DVALIN_BREATH':for(const t of ts.slice(0,3))if(damage(t,1.25,'ANEMO'))t.nextScorePenalty=Math.max(8,t.nextScorePenalty||0);break;
 case'ECARD_DVALIN_DIVE':many(1.6,'ANEMO',2);a.airborne=true;break;
 case'ECARD_ABYSS_PYRO_RING':multi([.4,.4],'PYRO',2);break;
 case'ECARD_CICIN_ELECTRO_SUMMON':a.cicinCount=2;break;
 case'ECARD_CICIN_ELECTRO_BURST':many(.7,'ELECTRO',2);break;
 case'ECARD_FATUI_GENERIC_DEVICE':this.addCombatStatus(a,'FATUI_DEVICE',2,{mods:{atk:{pct:10}}});break;
 default:{const m=c.script.match(/^DMG(_AOE)?:ATK\*([\d.]+):([A-Z]+|ELEMENT=POWER_TAGS_ELEMENT):(ALLY_1|MAX([1-4])|ALLY_ALL)/);if(!m)fail('CARD_IMPLEMENTATION','전용 효과 실행기가 연결되지 않았습니다.');for(const t of ts.slice(0,m[4]==='ALLY_ALL'?Infinity:Number(m[5]||1)))if(damage(t,Number(m[2]),m[3].startsWith('ELEMENT=')?(a.element==='물리'?'미분류':a.element):m[3])){const score=c.script.match(/NEXT_ACTION_SCORE-(\d+)/);if(score)t.nextScorePenalty=Math.max(Number(score[1]),t.nextScorePenalty||0);}break;}}
 a.cooldowns[c.id]=c.cooldown;b.log.push({actor:a.name,card:c.id,cardName:c.name});};
P.executeCombatSystem=function(a,id,target){const b=this.s.runtime;if(id==='TOOL:TRPG_TACTICAL_LEVITATOR'){if(!(b.toolCharges.TRPG_TACTICAL_LEVITATOR>0))fail('CHARGES','장치의 사용 횟수가 남아 있지 않습니다.');b.toolCharges.TRPG_TACTICAL_LEVITATOR--;for(const ally of b.actors.filter(x=>x.side===a.side&&x.hp>0))this.addCombatStatus(ally,'STATUS_TACTICAL_LEVITATION',3);return;}
 if(id.startsWith('ITEM:')){const item=id.slice(5),factor={TRPG_HEALING_POTION:.2,TRPG_BANDAGE:.15,TRPG_MEDKIT:.25}[item];if(!factor||this.itemCount(item)<1)fail('ITEM','사용할 수 없는 치료품입니다.');const t=b.actors.find(x=>x.id===(target||a.id)&&x.side===a.side&&x.hp>0),lock=item==='TRPG_HEALING_POTION'?'STATUS_COMBAT_POTION_LOCK':'STATUS_RECENTLY_BANDAGED';if(!t||(item==='TRPG_HEALING_POTION'&&t.id!==a.id)||status(t,lock)||t.hp>=t.maxHp)fail('ITEM_TARGET','해당 대상에게 사용할 수 없습니다.');this.pay({items:{[item]:1}});this.heal(t,t.maxHp*factor,a.name);this.addCombatStatus(t,lock,null);if(item!=='TRPG_HEALING_POTION'){const bleed=status(t,'STATUS_BLEED');if(bleed){bleed.stacks=Math.max(0,(bleed.stacks||1)-1);if(!bleed.stacks)t.statuses=t.statuses.filter(s=>s!==bleed);}}return;}
 const cfg=b.storyConfig;if(id===cfg?.field_access_action?.id){const f=cfg.field_access_action;this.addCombatStatus(a,f.effect,f.duration_rounds);return;}if(id===cfg?.orb_action?.id){if(a.source!=='PLAYER_CUSTOM')fail('MANUAL_ONLY','주인공이 직접 선택해야 합니다.');b.orbChannel=true;b.variables={...(b.variables||{}),ISK_M04_ORB_CHANNEL_READY:true};return;}fail('CARD','지원되지 않는 전투 행동입니다.');};
P.resolveDecoyAction=function(a,targets){
 const b=this.s.runtime,bunny=b?.fields?.find(f=>f.kind==='BUNNY'&&f.side!==a.side&&f.hp>0&&!f.done);
 if(!bunny||a.side!=='ENEMY'||a.enemyCharge||a.charging)return false;
 const cards=this.actorCards(a).filter(c=>!this.cardReason(a,c)).filter(c=>
  /DMG_AOE|MULTIHIT_AOE|HEAL|SHIELD|SUMMON|SELF_BUFF/.test(c.script)||/ALLY_ALL|ALLY_MAX[234]|MAX[234]|SELF/.test(c.target));
 cards.sort((x,y)=>y.weight-x.weight||x.id.localeCompare(y.id));
 if(!cards.length)return false;
 const c=cards[0],legal=this.cardTargets(a,c);
 if(!legal.length&&!/HEAL|SHIELD|SUMMON|SELF_BUFF/.test(c.script)&&c.target!=='SELF')return false;
 this.executeCard(a,c,legal[0]?.id,'TAP');return true;
};
P.aiTurn=function(a,targets){const b=this.s.runtime;if(a.charging&&a.turns>=a.charging.resolveTurn){const c=this.cardDefinition(this.row('08_SKILL_CARD_DB',a.charging.card));for(const t of targets.filter(t=>this.hasAirAccess(a,t,c.range)).slice(0,4)){this.damage(a,t,1.6+.3*(t.conduction||0),'ELECTRO',{range:c.range,card:c.id});t.conduction=0;}delete a.charging;return;}
 if(this.resolveDecoyAction?.(a,targets))return;
 const bunny=b.fields.find(f=>f.kind==='BUNNY'&&f.side!==a.side&&f.hp>0);if(bunny&&a.grade!=='보스'){const proxy={id:'BUNNY',name:'토끼 백작',hp:bunny.hp,maxHp:bunny.hp,def:bunny.def,eva:0,statuses:[],shields:[]};this.damage(a,proxy,a.side==='ENEMY'&&!a.hasDedicatedCards?({일반:.85,정예:1,강적:1.15}[a.grade]||.65):.65,a.element||'PHYSICAL');bunny.hp=proxy.hp;if(bunny.hp<=0)this.explodeBunny(bunny);return;}
 const cards=this.actorCards(a).filter(c=>!this.cardReason(a,c)).filter(c=>{if(c.id==='MOND_BARBARA_Q'||c.id==='MOND_MIKA_Q')return b.actors.some(x=>x.side===a.side&&x.hp>0&&x.hp<x.maxHp);if(c.id==='MOND_LISA_E')return true;return true;});
 const weight=c=>{let w=c.weight;const support=/HEAL|SHIELD|LEVITATION/.test(c.script);if(['생존우선','지원우선'].includes(a.tactic)&&support)w+=100;if(a.tactic==='공격우선'&&/DMG|MULTIHIT/.test(c.script))w+=100;if(a.tactic==='연계우선'&&targets.some(t=>this.reactionFor(t,element(c.row[13]))))w+=100;return w;};cards.sort((x,y)=>weight(y)-weight(x)||x.id.localeCompare(y.id));
 if(cards.length){const c=cards[0],legal=targets.filter(t=>this.hasAirAccess(a,t,c.range)),branch=c.id==='MOND_LISA_E'&&legal.some(t=>(t.conduction||0)>=2)?'CHARGE':c.id==='MOND_RAZOR_E'&&(a.razorSigils||0)>=2?'HOLD':'TAP';this.executeCard(a,c,legal[0]?.id,branch);return;}
 const legal=targets.filter(t=>this.hasAirAccess(a,t,a.range));if(!legal.length){if(b.storyConfig?.field_access_action&&!status(a,b.storyConfig.field_access_action.effect)){this.executeCombatSystem(a,b.storyConfig.field_access_action.id,a.id);b.log.push({actor:a.name,card:b.storyConfig.field_access_action.id});return;}a.guard=true;b.log.push({actor:a.name,guard:true,reason:'현재 사거리에서 공격할 수 없음'});return;}
 if(a.side==='ENEMY'&&!a.hasDedicatedCards&&a.turns%2===0){const spec={일반:[1.1,1],정예:[1.4,2],강적:[1.7,2]}[a.grade]||[.65,1];for(const t of legal.slice(0,spec[1])){const hit=this.damage(a,t,spec[0]*(a.tactic==='공격우선'?1.15:1),a.element||'PHYSICAL');if(hit&&/지원|제어/.test(a.tactic))t.nextScorePenalty=Math.max(10,t.nextScorePenalty||0);}if(a.tactic==='생존우선')this.addCombatStatus(a,'FALLBACK_DEFENSE',null,{untilTurn:a.turns+1,damageMultiplier:.85});b.log.push({actor:a.name,card:'FALLBACK_SPECIAL'});return;}
 this.basicHit(a,legal[0]);};
P.explodeBunny=function(f){const b=this.s.runtime,a=b.actors.find(x=>x.id===f.actor);if(!a||f.done)return;for(const t of b.actors.filter(x=>x.side!==a.side&&x.hp>0).filter(t=>this.hasAirAccess(a,t,'원거리')).slice(0,3))this.damage(a,t,1.2,'PYRO',{range:'원거리',sourceKind:'OBJECT'});f.done=true;};
P.tickFields=function(timing){const b=this.s.runtime;for(const f of b.fields){const a=b.actors.find(x=>x.id===f.actor&&x.hp>0);if(!a||f.done)continue;const enemies=b.actors.filter(x=>x.side!==a.side&&x.hp>0),allies=b.actors.filter(x=>x.side===a.side&&x.hp>0);const hit=(k,el,max,range)=>enemies.filter(t=>this.hasAirAccess(a,t,range)).slice(0,max).forEach(t=>this.damage(a,t,k,el,{range,sourceKind:'FIELD',card:f.sourceCardId}));
 if(timing==='START'){if(f.kind==='BUNNY'&&f.explodeAt<=b.round)this.explodeBunny(f);if(f.kind==='ICE'&&b.round>f.createdRound)hit(.45,'CRYO',3,'근접');}
 if(timing==='END'){if(f.kind==='ROSE'){for(const t of enemies.filter(t=>this.hasAirAccess(a,t,'중거리')).slice(0,4))if(this.damage(a,t,.35,'ELECTRO',{range:'중거리',sourceKind:'FIELD',card:f.sourceCardId}))this.addCombatStatus(t,'STATUS_DEF_DOWN',2,{value:15});}if(f.kind==='FROST_MIST'){hit(.45,'CRYO',3,'중거리');allies.forEach(t=>this.heal(t,a.maxHp*.08,a.name));}if(f.kind==='OZ')hit(.45,'ELECTRO',1,'원거리');if(f.kind==='DANDELION')allies.forEach(t=>this.heal(t,this.combatStat(a,'atk')*.35,a.name));if(f.kind==='BOMBARD'){const targets=enemies.filter(t=>this.hasAirAccess(a,t,'중거리')).slice(0,4),applied=new Set();for(let i=0;i<4&&targets.some(t=>t.hp>0);i++){const living=targets.filter(t=>t.hp>0),t=living[i%living.length];if(this.damage(a,t,.35,'PYRO',{range:'중거리',sourceKind:'FIELD',card:f.sourceCardId,noAura:applied.has(t.id)}))applied.add(t.id);}}}}
 b.fields=b.fields.filter(f=>!f.done);};
P.roundEnd=function(){const b=this.s.runtime;this.tickFields('END');for(const a of b.actors)for(const st of a.statuses||[])if(st.tickDamage&&a.hp>0){const source=b.actors.find(x=>x.id===st.actor);if(source)this.applyDamage(source,a,st.tickDamage,{element:element(st.element),sourceKind:'REACTION_DOT'});}/* A lethal attack already wins; the terrain timer never undoes a concluded battle. */
 if(!b.actors.some(a=>a.side==='ENEMY'&&a.hp>0)&&!b.liyueEvacuation){return true;}if(b.terrain!==null&&b.round%2===0){b.terrain--;b.log.push({terrain:b.terrain,round:b.round});if(b.terrain<=0){b.defeatReason='TERRAIN_COLLAPSE';b.defeatMessage='지형이 모두 무너져 전멸했습니다.';for(const a of b.actors.filter(a=>a.side==='ALLY'))a.hp=0;this.finishBattle(false);return false;}}
 for(const a of b.actors){a.statuses=(a.statuses||[]).filter(s=>{if(Number.isFinite(s.rounds)&&s.createdRound<b.round)s.rounds--;return active(s);});a.shields=(a.shields||[]).filter(s=>{if(Number.isFinite(s.rounds)&&s.createdRound<b.round)s.rounds--;return s.value>0&&(!Number.isFinite(s.rounds)||s.rounds>0);});}b.fields=b.fields.filter(f=>{if(f.createdRound<b.round)f.rounds--;return f.rounds>0;});b.round++;this.tickFields('START');return true;};
P.newRound=function(){const b=this.s.runtime;b.order=b.actors.filter(a=>a.hp>0).map(a=>({id:a.id,first:a.firstNextRound===b.round,score:this.combatStat(a,'spd')-(a.nextScorePenalty||0)+this.die(10)-1})).sort((a,c)=>Number(c.first)-Number(a.first)||c.score-a.score||a.id.localeCompare(c.id));for(const a of b.actors)a.nextScorePenalty=0;b.cursor=0;b.turnStarted=null;};
P.checkBattleInterludes=function(){const b=this.s.runtime;if(!b?.storyConfig)return false;const boss=b.actors.find(a=>a.source==='BOSS_DVALIN');if(!boss)return false;for(const entry of b.storyConfig.interludes||[])if(boss.hp/boss.maxHp<=entry.hp_ratio_lte&&!b.interludeSeen[entry.scene_id]){b.interludeSeen[entry.scene_id]='QUEUED';b.pendingInterludes.push(copy(entry));}if(b.interlude)return true;if(!b.pendingInterludes.length)return false;const p=b.pendingInterludes.shift();b.interlude={...p,battleId:b.id};b.phase='WAIT_PLAYER';this.s.global.COMBAT_ACTION_PHASE='INTERLUDE';if(typeof this.startCombatInterlude==='function')this.startCombatInterlude(p.root_node_id,p.scene_id);else{this.s.global.SCREEN_MODE='COMBAT_INTERLUDE';b.interludeUnavailable='이 전투 대화의 장면 실행기가 아직 연결되지 않았습니다.';}return true;};
P.resumeCombatInterlude=function(){const b=this.s.runtime;if(!b?.interlude)fail('INTERLUDE','복귀할 전투 대화가 없습니다.');b.interludeSeen[b.interlude.scene_id]='COMPLETE';delete b.interlude;delete b.interludeUnavailable;b.pendingInterlude='';b.phase='RESOLVING';this.s.global.SCREEN_MODE='COMBAT';this.autoUntilPlayer();return{battle:b.id,round:b.round,finished:!this.s.runtime};};
P.autoUntilPlayer=function(){for(let limit=0;limit<2000;limit++){const b=this.s.runtime;if(!b)return;const objective=this.liyueBattleOutcome?.(b);if(objective==='HOLD')return;if(typeof objective==='boolean'){this.finishBattle(objective);return;}if((!b.actors.some(a=>a.side==='ALLY'&&a.hp>0)&&!b.liyueObjective)||b.terrain===0){this.finishBattle(false);return;}if(b.storyConfig?.orb_action&&!b.orbChannel&&b.actors.every(a=>a.side!=='ENEMY'||a.hp<=0)&&this.combatActor()?.hp<=0){this.finishBattle(false);return;}if(this.resolveEnemyPhases)this.resolveEnemyPhases();if(this.checkBattleInterludes())return;if(!b.actors.some(a=>a.side==='ENEMY'&&a.hp>0)&&!b.liyueEvacuation){if(b.storyConfig?.orb_action&&!b.orbChannel){b.subduedPending=true;b.phase='WAIT_PLAYER';this.s.global.COMBAT_ACTION_PHASE='SUBDUED_PENDING_FINISH';this.s.global.SCREEN_MODE='COMBAT';return;}this.finishBattle(true);return;}
 if(b.cursor>=b.order.length){if(!this.roundEnd()||!this.s.runtime)return;if(this.checkBattleInterludes())return;if(!b.actors.some(a=>a.side==='ENEMY'&&a.hp>0)&&!b.liyueEvacuation)continue;this.newRound();continue;}
 const a=b.actors.find(x=>x.id===b.order[b.cursor].id);if(!a||a.hp<=0){b.cursor++;continue;}const turn=b.round+':'+a.id;if(b.turnStarted!==turn){b.turnStarted=turn;a.turns=(a.turns||0)+1;a.guard=false;for(const id of Object.keys(a.cooldowns))a.cooldowns[id]=Math.max(0,a.cooldowns[id]-1);a.statuses=(a.statuses||[]).filter(s=>!s.untilTurn||s.untilTurn>a.turns);if(this.onCombatTurnStart)this.onCombatTurnStart(a);if(a.hp<=0){b.cursor++;continue;}}
 if(this.combatActionLocked?this.combatActionLocked(a):status(a,'STATUS_FREEZE')){b.log.push({actor:a.name,skipped:'행동 제한'});b.cursor++;continue;}if(a.control==='PLAYER'){b.phase='WAIT_PLAYER';this.s.global.COMBAT_ACTION_PHASE='WAIT_PLAYER';return;}const targets=b.actors.filter(x=>x.hp>0&&x.side!==a.side).sort((x,y)=>x.hp-y.hp||x.id.localeCompare(y.id));const actions=this.combatActionsPerTurn?this.combatActionsPerTurn(a):1;for(let n=0;n<actions&&a.hp>0;n++){const current=targets.filter(t=>t.hp>0);if(!current.length&&!b.liyueObjective)break;this.aiTurn(a,current);b.actionSequence++;if(this.resolveEnemyPhases)this.resolveEnemyPhases();}b.cursor++;}fail('COMBAT_LOOP','자동 전투 진행 한도를 초과했습니다.');};
P.combatAction=function(card,target,branch){const b=this.s.runtime;if(!b||b.phase!=='WAIT_PLAYER'||b.interlude)fail('COMBAT_INPUT','주인공 행동을 기다리는 전투 화면이 아닙니다.');const a=this.combatActor(),entry=this.combatCards().find(x=>x.id===card);if(!entry||entry.reason)fail('CARD',entry?.reason||'소유하지 않은 카드입니다.');if(entry.targets.length&&target&&!entry.targets.some(t=>t.id===target))fail('TARGET','현재 카드에 맞는 대상을 선택해 주세요.');const logStart=b.log.length;if(entry.system)this.executeCombatSystem(a,card,target);else this.executeCard(a,this.actorCards(a).find(x=>x.id===card),target,branch);b.lastManualAction={id:this.s.global.SAVE_ID+':'+(this.s.global.LAST_COMMITTED_ACTION_SEQ+1),card,actor:a.id,round:b.round};if(!b.subduedPending)b.cursor++;b.actionSequence++;b.phase='RESOLVING';this.autoUntilPlayer();return{battle:b.id,round:b.round,events:b.log.slice(logStart),finished:!this.s.runtime};};
P.liyueFieldMoraPlan=function(b=this.s.runtime){
 if(!b||b.origin!=='RANDOM'||b.storyConfig?.noRewards)return null;
 const map=this.tables['32_MAP_DB']?.get(this.s.global.CURRENT_MAP_ID);
 if(!map||map[1]!=='리월'||map[12]==='Y')return null;
 const grade={'일반':1,'정예':1.35,'강적':1.75},enemies=b.actors.filter(a=>a.side==='ENEMY'&&grade[a.grade]);
 if(!enemies.length)return null;
 const min=Math.max(1,Number(map[6]||1)),max=Math.max(min,Number(map[7]||min)),risk=Math.max(1,Math.min(6,Math.ceil(((min+max)/2)/2)));
 const riskMult=[0,1,1.03,1.06,1.10,1.15,1.20][risk],group=this.tables['33_ENCOUNTER_GROUP_DB']?.get(b.group),groupMult=Math.max(.5,Math.min(2,Number(group?.[24]||1)));
 const parts=enemies.map(a=>({source:a.source,level:a.level,grade:a.grade,mora:round((4+2*a.level)*grade[a.grade]*riskMult*groupMult)}));
 return {version:2,map:map[0],risk,groupMult,mora:parts.reduce((n,x)=>n+x.mora,0),parts};
};
P.liyueLootConditionAllowed=function(b,a,d){
 if(!b||!(b.origin==='RANDOM'||b.origin?.startsWith('QUEST:'))||b.storyConfig)return false;
 const map=this.tables['32_MAP_DB']?.get(this.s.global.CURRENT_MAP_ID);if(!map||map[1]!=='리월')return false;
 const monster=this.row('09_MONSTER_DB',a.source);if(d[0]!==monster[14])return false;
 const c=String(d[6]||'');
 if(d[0]==='LT_TREASURE')return c==='보물 사냥단';
 if(d[0]==='LT_RUIN'||d[0]==='LT_RUIN_ELITE')return ['유적 기계','강적 유적 기계'].includes(c);
 if(d[0]==='LT_HILICHURL')return a.grade==='일반'&&['일반 츄츄족 희귀 드랍','일반 츄츄족 매우 희귀'].includes(c);
 if(d[0]==='LT_HILICHURL_ELITE')return a.grade!=='일반'&&c==='정예 츄츄족';
 if(d[0]==='LT_VISHAP')return c==='용 도마뱀'||(c==='강한 용 도마뱀'&&a.grade!=='일반');
 if(d[0]==='LT_ABYSS_KNIGHT')return c==='흑 뱀 기사';
 if(d[0]==='LT_ABYSS_MAGE')return c==='심연 메이지';
 if(d[0]==='LT_FATUI')return c==='우인단';
 return false;
};
P.finishBattle=function(victory){const b=this.s.runtime;if(!b)return;const node=b.origin.startsWith('STORY:')?this.storyNode():null;if(this.s.combatReceipts?.[b.id])fail('BATTLE_SETTLED','이미 결과를 기록한 전투입니다.');let xp=0,loot={};if(victory&&!b.storyConfig?.noRewards){for(const a of b.actors.filter(a=>a.side==='ENEMY')){const m=this.row('09_MONSTER_DB',a.source),mult={일반:1,정예:3,강적:6,보스:12}[m[3]]||1;xp+=round((30+15*(b.mondBossBalance?.bosses?.includes(a.source)?a.rewardLevel:a.level))*mult);if(!b.storyConfig)for(const drop of this.combatRows('20_LOOT_TABLE').filter(x=>x[0]===m[14]&&(!x[1]||x[1]===a.source||this.mondLootSourceMatches?.(b,a,x)))){if(!['','없음','일반 슬라임 희귀 드랍','일반 슬라임 매우 희귀'].includes(drop[6]||'')&&!this.mondLootConditionAllowed?.(b,a,drop)&&!this.liyueLootConditionAllowed?.(b,a,drop))continue;if(this.die()<=Number(drop[5])){const n=Number(drop[3])+Math.floor(this.random()*(Number(drop[4])-Number(drop[3])+1));this.giveItem(drop[2],n);loot[drop[2]]=(loot[drop[2]]||0)+n;}}}}
 const mondRewards=this.mondRewardPlan?.(b),liyueMora=!mondRewards?this.liyueFieldMoraPlan?.(b):null;if(victory&&!b.storyConfig?.noRewards&&mondRewards)xp=mondRewards.xp;
 for(const a of b.actors.filter(x=>x.side==='ALLY')){if(a.guest){if(b.storyConfig){const base=this.s.guestSnapshots[b.storyConfig.node_id][a.source];base.hp=Math.min(a.hp,base.maxHp);if(victory){let level=base.level,total=(base.xp||0)+xp;while(level<20&&total>=Number(this.row('26_LEVEL_RULES',level)[2])){total-=Number(this.row('26_LEVEL_RULES',level)[2]);level++;}const before=this.row('26_LEVEL_RULES',base.level),after=this.row('26_LEVEL_RULES',level);if(level>base.level){base.maxHp=round(base.maxHp*Number(after[4])/Number(before[4]));base.hp=base.maxHp;base.atk=round(base.atk*Number(after[5])/Number(before[5]));base.def=round(base.def*Number(after[5])/Number(before[5]));base.spd+=Number(after[6])-Number(before[6]);}base.level=level;base.xp=level===20?0:total;}}continue;}const persistent=(a.statuses||[]).filter(st=>this.tables['13_STATUS_EFFECT_DB']?.get(st.id)?.[16]==='PERSISTENT');if(a.source==='PLAYER_CUSTOM'){this.s.global.PLAYER_HP_CURRENT=Math.min(a.hp,this.s.global.PLAYER_HP_MAX);this.s.playerStatuses=copy(persistent);}else {this.s.chars[a.source].hp=Math.min(a.hp,this.character(a.source).maxHp);this.s.chars[a.source].statuses=copy(persistent);}if(victory)this.addXp(a.source,xp);}
 const bond=victory?this.awardBattleBond?.(b)||null:null;
 const mora=victory&&!b.storyConfig?.noRewards?(mondRewards?.mora??liyueMora?.mora??0):0;if(mora)this.s.global.MORA+=mora;
 const result={...(mondRewards?{mora,rewardPolicy:'MOND_BALANCE_V1'}:liyueMora?{mora,rewardPolicy:'LIYUE_FIELD_MORA_V2',moraMap:liyueMora.map,moraRisk:liyueMora.risk,moraGroupMultiplier:liyueMora.groupMult,moraParts:copy(liyueMora.parts)}:{}),bond,id:b.id,battleId:b.id,saveId:this.s.global.SAVE_ID,group:b.group,origin:b.origin,gate:b.storyConfig?.node_id||b.origin.replace(/^STORY:/,''),branch:b.storyConfig?.branch||null,victory,xp,loot,rounds:b.round,result:victory?(b.storyConfig?.result||'VICTORY'):'DEFEAT',...(b.defeatReason?{defeatReason:b.defeatReason,defeatMessage:b.defeatMessage||''}:{}),unsupportedEffects:b.unsupportedEffects||[]};this.s.combatReceipts=this.s.combatReceipts||{};this.s.combatReceipts[b.id]=copy(result);this.s.lastBattleConfig=b.storyConfig?copy(b.storyConfig):null;this.s.global.LAST_BATTLE_RESULT_JSON=JSON.stringify(result);this.s.lastCombatLog=copy(b.log);this.s.runtime=null;Object.assign(this.s.global,{MODE:'NORMAL',ACTIVE_BATTLE_ID:'',COMBAT_ACTION_PHASE:'NONE',SCREEN_MODE:'REWARD',ENCOUNTER_COOLDOWN:1});this.s.log.push(result);
 const counts=j(this.s.global.WORLD_VISIT_COUNTS_JSON);if(victory&&this.row('32_MAP_DB',this.s.global.CURRENT_MAP_ID)[1]==='몬드')counts.MON_D_ENCOUNTERS=(counts.MON_D_ENCOUNTERS||0)+1;if(victory&&b.origin==='RANDOM'&&this.row('32_MAP_DB',this.s.global.CURRENT_MAP_ID)[1]==='리월')counts.LIYUE_ENCOUNTERS=(counts.LIYUE_ENCOUNTERS||0)+1;this.s.global.WORLD_VISIT_COUNTS_JSON=JSON.stringify(counts);if(b.origin.startsWith('QUEST:'))this.questState(b.origin.slice(6)).node=victory?'READY_TO_CLAIM':'INVESTIGATE';
 const eligibility=j(this.s.global.COMPANION_ELIGIBILITY_JSON);for(const [id,v]of Object.entries(eligibility))if(v.state==='TEMPORARY'&&v.expires==='NEXT_COMBAT_END'){v.state='DEPARTED';for(const p of this.s.party)if(p.source===id)p.active=false;}this.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(eligibility);
 if(b.origin.startsWith('BOSS:')){const route=this.row('35_BOSS_ROUTE_DB',b.origin.slice(5)),steps=this.combatRows('50_BOSS_ROUTE_STEP_DB').filter(r=>r[1]===route[0]).sort((x,y)=>x[2]-y[2]),step=steps.find(r=>r[4]===b.group);if(victory&&step?.[3]==='BOSS'){this.s.flags[route[13]]=true;this.s.global.ACTIVE_BOSS_ROUTE_ID='';}else if(victory)this.s.global.BOSS_ROUTE_STEP=steps.find(r=>r[2]>step[2])?.[2]||step[2];}
 if(node){if(typeof this.storyBattleResolved==='function')this.storyBattleResolved(victory,node);else if(victory){const flag=String(node[12]).match(/ON_VICTORY:(FLAG_\w+)=TRUE/);if(flag)this.s.flags[flag[1]]=true;if(b.storyConfig){this.storyCombatEvent({id:b.storyConfig.eventId}, {handler:'isk_m04_combat',kind:'battle_result',config:b.storyConfig,branch:b.storyConfig.branch,group_id:b.group,gate_node_id:b.storyConfig.node_id});}this.s.global.CURRENT_STORY_NODE_ID=node[13];this.s.global.STORY_CURSOR_NODE_ID=node[13];}}
 return result;};
P.storyCombatEvent=function(eventRecord,payload){const id=Array.isArray(eventRecord)?eventRecord[0]:eventRecord.id||eventRecord.EVENT_ID||eventRecord.eventId||this.s.lastBattleConfig?.eventId;if(payload.kind==='battle_result'){const r=j(this.s.global.LAST_BATTLE_RESULT_JSON),cfg=payload.config;if(!r.victory||!this.s.combatReceipts?.[r.battleId]||r.group!==payload.group_id||r.gate!==payload.gate_node_id||r.branch!==payload.branch||r.result!==cfg.result)fail('BATTLE_RECEIPT','이야기에 필요한 실제 전투 결과가 확인되지 않았습니다.');const progress=j(this.s.global.EVENT_PROGRESS_JSON);if(progress[id]?.battleId===r.battleId)return progress[id];const receipt={resolvedNode:r.gate,saveId:r.saveId,branch:r.branch,gate:r.gate,victory:true,turn:this.s.global.TURN,day:this.s.global.WORLD_DAY,group:r.group,result:r.result,battleId:r.battleId};progress[id]=receipt;const q=progress[payload.quest_id||'Q_ISK_MOND_02']||(progress[payload.quest_id||'Q_ISK_MOND_02']={});q.m04=q.m04||{};q.m04[r.branch]=q.m04[r.branch]||{};q.m04[r.branch].battle_result=copy(receipt);this.s.global.EVENT_PROGRESS_JSON=JSON.stringify(progress);if(cfg.victory_flag)this.s.flags[cfg.victory_flag]=true;return receipt;}
 const b=this.s.runtime;if(!b||b.group!==payload.group_id||b.storyConfig?.node_id!==payload.gate_node_id)fail('BATTLE_EVENT','현재 전투의 사건이 아닙니다.');if(payload.kind==='interlude'){if(!b.interlude||b.interlude.scene_id!==payload.phase.scene_id)fail('INTERLUDE','현재 전투 대화가 아닙니다.');return{scene:b.interlude.scene_id,battleId:b.id};}if(['field_action','orb_action'].includes(payload.kind)){if(b.lastManualAction?.card!==payload.action.id)fail('MANUAL_ACTION','실제 전투 행동을 먼저 선택해 주세요.');return copy(b.lastManualAction);}fail('BATTLE_EVENT','정의되지 않은 전투 사건입니다.');};
P.apply=function(a){if(a.type==='COMBAT_PREPARE')return this.confirmBattlePreparation(a.group,a.companions||a.guests||[]);return oldApply.call(this,a);};
P.view=function(){const v=oldView.call(this);v.combatCards=this.combatCards();v.battlePreparation=this.s.battlePreparation?this.battlePreparation(this.s.battlePreparation.group):null;return v;};
P.validateSave=function(s){oldValidate.call(this,s);if(s.runtime){const b=s.runtime;if(b.combatVersion!==1)fail('COMBAT_VERSION','이전 전투 실행기의 진행 중 저장은 자동 변환하지 않습니다. 원본 파일을 보존하고 전투 이전 저장을 불러와 주세요.');if(!Array.isArray(b.actors)||!Array.isArray(b.order)||!Number.isInteger(b.cursor)||!Number.isInteger(b.round)||new Set(b.actors.map(a=>a.id)).size!==b.actors.length)fail('COMBAT_SAVE','전투 저장 상태가 손상되었습니다.');for(const a of b.actors){if(a.source?.startsWith('MON_SLIME_')&&a.element&&a.element!=='물리'){a.nativeAura=a.element;a.aura=a.element;}if(!Number.isFinite(a.hp)||a.hp<0||a.hp>a.maxHp||!Number.isFinite(a.atk)||!Number.isFinite(a.def)||!Number.isFinite(a.spd))fail('COMBAT_SAVE','전투 능력치가 손상되었습니다.');}}return s;};
api.combatVersion='mond-combat-20260924-1';if(typeof module!=='undefined'&&module.exports)module.exports=api;root.CRPGRuntime=api;
})(typeof globalThis!=='undefined'?globalThis:this);
