const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/tmp/crpg-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true}),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));const path=__dirname;await page.goto('file://'+path+'/CRPG_player.html');await page.getByRole('textbox',{name:'주인공 이름'}).fill('화면 검증');await page.getByRole('button',{name:'여정 시작',exact:true}).click();await page.screenshot({path:path+'/ui_desktop.png',fullPage:true});assert.equal(await page.locator('.story').count(),1);results.push('새 게임 입력→실제 이야기');
const saves=JSON.parse(fs.readFileSync(path+'/qa_saves.json'));await page.evaluate(s=>CRPG_APP.loadState(s),saves.flow);
for(const label of ['장소·이동','상점','소지품·장비','제작·강화','의뢰·관계','보스 도전','저장·시스템']){await page.getByRole('button',{name:label,exact:true}).click();assert.equal(await page.locator('main').count(),1);results.push(label);assert.equal(await page.locator('#notice').innerText(),'');}
await page.getByRole('checkbox').check();await page.evaluate(s=>CRPG_APP.loadState(s),saves.ROUTE_ISEKAI);await page.getByRole('button',{name:'장소·이동',exact:true}).click();await page.locator('.card').filter({has:page.getByRole('heading',{name:'캐서린',exact:true})}).getByRole('button',{name:'찾아가기'}).click();assert.equal(await page.locator('img.art').count(),1);assert.ok(await page.locator('img.art').evaluate(i=>i.naturalWidth>0));results.push('NPC 실제 이미지');await page.screenshot({path:path+'/ui_npc.png',fullPage:true});
await page.evaluate(s=>CRPG_APP.loadState(s),saves.battle);assert.ok(await page.getByRole('button',{name:'공격 대상으로 선택'}).count());await page.getByRole('button',{name:'방어하고 다음 행동까지 버틴다'}).click();assert.equal(await page.locator('#notice').innerText(),'');results.push('전투 입력→다음 행동 경계');await page.screenshot({path:path+'/ui_combat.png',fullPage:true});
await page.evaluate(s=>CRPG_APP.loadState(s),saves.flow);await page.getByRole('button',{name:'저장·시스템',exact:true}).click();const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'저장 파일 내보내기'}).click();const download=await downloading;await download.saveAs(path+'/ui_export_save.json');const saved=JSON.parse(fs.readFileSync(path+'/ui_export_save.json'));assert.equal(saved.global.SAVE_ID,saves.flow.global.SAVE_ID);results.push('실제 SAVE 파일 내보내기');const selecting=page.waitForEvent('filechooser');await page.getByRole('button',{name:'저장 파일 불러오기',exact:true}).click();const chooser=await selecting;await chooser.setFiles(path+'/ui_export_save.json');await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('복원했습니다'));assert.equal(await page.evaluate(()=>CRPG_APP.game.s.global.SAVE_ID),saved.global.SAVE_ID);results.push('실제 파일 입력으로 SAVE 복원');
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'소지품·장비',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.getByRole('button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=48)));await page.screenshot({path:path+'/ui_mobile.png',fullPage:true});results.push('390px 모바일 · 가로 넘침 없음 · 버튼 최소48px');
assert.deepEqual(errors,[]);fs.writeFileSync(path+'/ui_test_results.json',JSON.stringify({screens:8,checks:results.length,results,errors},null,2));console.log({checks:results.length,errors});await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
