'use strict';
// Read-only native audit; declared ownership, legal growth/gear preparation only.
const fs=require('node:fs'),path=require('node:path'),H=require('./audit_protagonist_v01618.cjs');
const args=process.argv.slice(2),arg=k=>args.includes(k)?args[args.indexOf(k)+1]:null;
const root=path.resolve(arg('--root')||path.resolve(__dirname,'..')),env=H.load(root),out=arg('--out')||'/tmp/crpg_v01627_ordinary/baseline.json';
const teams={story4:H.TEAMS.story4,heal4:H.TEAMS.support4,heal5:['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN']};
const spec=[];
const levels=(arg('--levels')||'5,10,20,35,50,60').split(',').map(Number);
for(const level of levels)for(const [key,d]of Object.entries(env.api.growthV01522.domains))if(d.levels?.includes(level))spec.push({name:d.kind+':'+level,level,domain:key+':'+level,element:'NEUTRAL'});
const rows=[],errors=[],data={schema:1,sourceRoot:root,fingerprint:env.fingerprint,assumptions:{gear:'Starter +0 <Lv5; ordinary craft +0 <Lv10, +3 Lv10-29, +6 Lv30+, no artifacts/exclusive/boss gear.',talents:'Legal per-level maximum base talent; declared ascension. C0 characters.',timing:'Displayed 2x: native presentationMs/1000 + 3 seconds per player input + 6 seconds settlement/reentry. Native travel and lodging included if needed.',hp:'One initial full HP; three fights carry native HP and PRNG. Native lodging before a fight if any owner HP<50% or KO. Diagnostic funding is not an income claim.'},rows,errors};
fs.mkdirSync(path.dirname(out),{recursive:true});const save=()=>fs.writeFileSync(out,JSON.stringify(data,null,2)+'\n');
for(const s of spec)for(const [name,team]of Object.entries(teams))try{const row=H.campaign(env,{...s,team,name:s.name+':'+name,talent:10,route:'ROUTE_ISEKAI',seed:717},{runs:Number(arg('--runs')||3)});const first=row.battles[0],party=row.fixtureHp.reduce((n,a)=>n+a.maxHp,0),pre=first?.hpBeforeReward||[];row.firstPreRewardHpRatio=pre.reduce((n,a)=>n+Math.max(0,a.hp),0)/pre.reduce((n,a)=>n+a.maxHp,0);const rt=H.setup(env,{...s,team,talent:10,route:'ROUTE_ISEKAI',seed:717,map:env.api.growthV01522.domains[s.domain.split(':')[0]].map});row.nativeQuote=rt.innRecoveryQuote(rt.row('19_SHOP_STOCK_DB','STK_INN_MOND'));const f=first?.initial||[];rows.push(row);console.log(JSON.stringify({case:row.name,wins:row.wins,losses:row.losses,firstRound:first?.rounds,firstSeconds:first?.seconds,firstPreHp:+row.firstPreRewardHpRatio.toFixed(3),meanSeconds:row.seconds/Math.max(1,row.battles.length),finalHp:+row.finalHpRatio.toFixed(3),lodging:row.lodgingMora,enemies:f.filter(a=>a.side==='ENEMY').map(a=>({id:a.source,l:a.level,hp:a.maxHp,atk:a.atk,def:a.def})),talents:row.talents}));save();}catch(e){errors.push({spec:s,team:name,code:e.code||e.name,message:e.message,stack:e.stack});console.error(JSON.stringify(errors.at(-1)));save();}
data.counts={conditions:rows.length,battles:rows.reduce((n,r)=>n+r.battles.length,0),wins:rows.reduce((n,r)=>n+r.wins,0),losses:rows.reduce((n,r)=>n+r.losses,0),errors:errors.length};save();
