'use strict';
// Read-only product audit: run shipped LIFE/BUY/CRAFT/MEAL actions from zero
// ingredient/food inventory. No new prices, monsters, forced drops or free food.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),zlib=require('node:zlib');
const root=path.resolve(__dirname,'..'),copy=x=>JSON.parse(JSON.stringify(x));
const runtimeRoot=process.argv.includes('--runtime-root')?path.resolve(process.argv[process.argv.indexOf('--runtime-root')+1]):root;
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const CLOCK=Date.parse('2026-10-09T07:00:00Z');let clock=CLOCK,seq=0;
const c=vm.createContext({console,Date:class extends Date{static now(){return clock;}},setTimeout,clearTimeout});
const loaded=[];
for(const [,f]of fs.readFileSync(path.join(runtimeRoot,'source/index.html'),'utf8').matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)){
 const code=fs.readFileSync(path.join(runtimeRoot,'source',f),'utf8');loaded.push({file:f,sha256:sha(code)});vm.runInContext(code,c,{filename:f});
}
const presentation=fs.readFileSync(path.join(runtimeRoot,'source/presentation.js'),'utf8');vm.runInContext(presentation,c,{filename:'presentation.js'});loaded.push({file:'presentation.js',sha256:sha(presentation)});
const rawDb=fs.readFileSync(path.join(runtimeRoot,'content/db.json'),'utf8'),db=JSON.parse(rawDb),R=c.CRPGRuntime.Runtime,api=c.CRPGRuntime,L=api.lifeScene,G=api.growthV01522;
const PARTY=['PLAYER_CUSTOM','MOND_AMBER','MOND_KAEYA','MOND_LISA'];
const SOURCES={MOND:{city:'MAP_MOND_CITY',shop:'EVT_SCHEDULE_MRC_MOND_GENERAL',merchant:'MRC_MOND_GENERAL',cook:'EVT_SCHEDULE_SERVICE_MOND_COOK',cookMap:'MAP_MOND_CITY',inn:'EVT_SCHEDULE_MRC_MOND_INN',stock:'STK_INN_MOND',region:'몬드'},LIYUE:{city:'MAP_LIYUE_HARBOR',shop:'EVT_SCHEDULE_MRC_LIYUE_GENERAL',merchant:'MRC_LIYUE_GENERAL',cook:'EVT_SCHEDULE_SERVICE_LIYUE_COOK',cookMap:'MAP_LY_DETAIL_CHIHU',inn:'EVT_SCHEDULE_MRC_LIYUE_INN',stock:'STK_INN_LIYUE',region:'리월'}};
function fresh(map='MAP_MOND_CITY',level=55,route='ROUTE_TRAVELER',seed=717){
 const r=new R(db);r.newGame({name:'요리 수급 감사',route,seed,saveId:'FOOD-SUPPLY-V01617-'+(++seq)});
 Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,STORY_MENU_POLICY:'',WORLD_TIME:'12:00',MORA:200000});
 delete r.s.storyJourney;delete r.s.storyBreak;r.prepareStory();
 for(const id of ['FLAG_TRV_ANEMO_UNLOCKED','FLAG_TRV_MON_CH1_CLEAR','FLAG_TRV_MON_CH2_CLEAR','FLAG_ISK_M03_CLEAR','FLAG_ISK_M05_CLEAR','FLAG_ACCESS_REGION_LIYUE'])r.s.flags[id]=true;
 for(const region of ['MOND','LIYUE'])for(let n=1;n<=4;n++){const id='Q_TRV_'+region+'_0'+n;if(r.tables['22_QUEST_DB'].has(id))r.questState(id).claimed=true;}
 r.s.inventory=[];r.s.party=[r.s.party[0],...PARTY.slice(1).map((source,i)=>({slot:'PARTY_'+(i+2),type:'CHAR',source,control:'AI',active:true,tactic:'균형'}))];
 r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(Object.fromEntries(PARTY.slice(1).map(id=>[id,{state:'JOINED'}])));
 r.s.talents??={};for(const id of PARTY){if(id==='PLAYER_CUSTOM')r.s.global.PLAYER_LEVEL_STATE=level;else r.s.chars[id].level=level;r.s.ascensions[id]=G.phaseFor(level);const cap=r.growth(id).talentCap,t=Math.max(1,Math.floor(cap*.65));r.s.talents[id]={na:t,e:t,q:t};}
 const weapons={'한손검':'EQ_SWORD_RANCOUR','활':'EQ_BOW_CRESCENT','법구':'EQ_CATALYST_MAPPA'};
 for(const id of PARTY)for(const equip of [weapons[r.equipmentProficiencies(id)[0]],'EQ_ARMOR_REINFORCED_LEATHER','EQ_ACC_HEALER_BROOCH']){if(!equip||Number(r.row('16_EQUIP_DB',equip)[19])>level)continue;const slot=r.giveEquipment(equip);r.action('EQUIP',{slot,owner:id});r.s.inventory.find(x=>x.slot===slot).enhance=level<30?3:6;}
 r.recalculate();for(const id of PARTY){const hp=id==='PLAYER_CUSTOM'?r.s.global.PLAYER_HP_MAX:r.character(id).maxHp;if(id==='PLAYER_CUSTOM')r.s.global.PLAYER_HP_CURRENT=hp;else r.s.chars[id].hp=hp;}
 Object.assign(r.tutorialState().done,{combatAttack:true,combatGuard:true,combatSkill:true,combatBurst:true});r.s.global.PRNG_STATE=seed;
 return r;
}
function pricedCityCatalog(r,region){
 const spec=SOURCES[region],stocks=r.rows('19_SHOP_STOCK_DB').filter(s=>s[1]===spec.merchant&&s[2]==='ITEM'&&!/SYSTEM_DISABLED|레거시|사용 금지/.test(s[8]||''));const out={};
 for(const s of stocks)if(Number(s[5])>0&&(!out[s[3]]||Number(s[5])<out[s[3]].unitMora))out[s[3]]={item:s[3],stock:s[0],unitMora:Number(s[5]),stockQuantity:Number(s[6]),period:s[7],condition:s[8]};
 return out;
}
function purchaseLowerBounds(r,region){
 const prices=Object.fromEntries(Object.values(pricedCityCatalog(r,region)).map(s=>[s.item,{unitMora:s.unitMora,route:'NPC_BUY',stock:s.stock}]));
 for(let i=0;i<r.rows('17_RECIPE_DB').length;i++){let changed=false;for(const raw of r.rows('17_RECIPE_DB')){const q=r.recipeDefinition(raw[0]);if(q[2]!=='ITEM')continue;const cost=r.recipeCost(q),items=Object.entries(cost.items);if(items.some(([id])=>!prices[id]))continue;const value=(cost.mora+items.reduce((n,[id,k])=>n+prices[id].unitMora*k,0))/Number(q[4]);if(!prices[q[3]]||value<prices[q[3]].unitMora){prices[q[3]]={unitMora:value,route:'CRAFT_LOWER_BOUND',recipe:q[0],ingredients:copy(cost.items),fee:cost.mora};changed=true;}}if(!changed)break;}
 return prices;
}
const purchaseLowerBound=(r,item,region)=>purchaseLowerBounds(r,region)[item]||null;
function foodCatalog(r){
 const lowers=Object.fromEntries(Object.keys(SOURCES).map(region=>[region,purchaseLowerBounds(r,region)])),directs=Object.fromEntries(Object.keys(SOURCES).map(region=>[region,pricedCityCatalog(r,region)]));
 const out=[];for(const raw of r.rows('17_RECIPE_DB')){const f=r.tables['14_ITEM_DB'].get(raw[3]);if(f?.[2]!=='음식'||!(Number(f[8])>0))continue;const q=r.recipeDefinition(raw[0]),cost=r.recipeCost(q),regional={};
  for(const region of Object.keys(SOURCES)){const lower=lowers[region],direct=directs[region],missing=Object.keys(cost.items).filter(id=>!lower[id]);regional[region]={directIngredientPurchase:Object.entries(cost.items).every(([id])=>direct[id])?cost.mora+Object.entries(cost.items).reduce((n,[id,k])=>n+k*direct[id].unitMora,0):null,purchaseAndProcessLowerBound:missing.length?null:cost.mora+Object.entries(cost.items).reduce((n,[id,k])=>n+k*lower[id].unitMora,0),missingPurchasable:missing};}
  out.push({recipe:q[0],food:f[0],name:f[1],baseHealing:Number(f[8]),cost:copy(cost),output:q[4],gameTime:q[19],unlock:q[18],unlockStocks:r.rows('19_SHOP_STOCK_DB').filter(s=>s[2]==='RECIPE'&&s[3]===q[0]).map(s=>({stock:s[0],merchant:s[1],mora:Number(s[5]),condition:s[8]})),ingredientNpcOpportunityMora:cost.mora+Object.entries(cost.items).reduce((n,[id,k])=>n+k*r.saleUnitPrice({item:id}),0),npcResaleMora:r.saleUnitPrice({item:f[0]}),readyFoodStocks:r.rows('19_SHOP_STOCK_DB').filter(s=>s[2]==='ITEM'&&s[3]===f[0]).map(s=>({stock:s[0],merchant:s[1],mora:Number(s[5]),quantity:Number(s[6]),condition:s[8]})),regional});
 }return out;
}
const tenth=n=>Math.round(n*10)/10;
function sceneInputs(scene){
 if(scene.kind==='GATHER')return scene.nodes.map((n,i)=>({at:600+i*450,node:n.i}));
 if(scene.kind==='HUNT')return scene.nodes.map(n=>{const at=n.start+Math.round(n.duration/2),p=L.animalAt(n,at);return {at,node:n.i,x:tenth(p.x),y:tenth(p.y)};}).sort((a,b)=>a.at-b.at);
 const out=[];let at=500;for(const n of scene.nodes)for(let k=0;k<n.hits;k++){out.push({at,node:n.i});at+=250;}return out;
}
function fishingInputs(job){const controls=[];let held=false;for(let t=2000;t<=job.duration;t+=100){const s=c.CRPGFishing.simulate(job,controls,t);if(s.caught)return {controls,elapsed:t};const hold=s.cursor<s.target;if(held!==hold){controls.push({at:t,hold});held=hold;}}return {controls,elapsed:job.duration};}
function harvest(r,kind){
 const before=Object.fromEntries(r.s.inventory.filter(x=>x.item).map(x=>[x.item,x.quantity]));const started=r.action('LIFE_START',{kind}).result,scene=r.lifeScene(),inputs=scene?sceneInputs(scene):null,args=scene?{inputs,elapsed:Math.min(started.duration,(inputs.at(-1)?.at||0)+400)}:fishingInputs(started);
 clock+=args.elapsed;const result=r.action('LIFE_FINISH',{job:started.id,...args}).result;
 const expected=scene?L.resolve(scene,inputs).items:result.items;assert.deepEqual(copy(result.items),copy(expected));for(const [id,n]of Object.entries(result.items))assert(r.itemCount(id)>=Number(before[id]||0)+n);
 return {map:started.map,kind,seed:started.scene?.seed??started.fishing?.seed,inputs:inputs||args.controls,inputCount:(inputs||args.controls).length,elapsedMs:args.elapsed,upperBoundMs:started.duration,scene:scene?copy(scene):null,items:copy(result.items),encounter:!!r.s.runtime,gameMinutes:result.minutes};
}
function supplySamples({count=32,maps=['MAP_MOND_PLAINS','MAP_MOND_FOREST','MAP_MOND_DAWN_WINERY','MAP_MOND_SPRINGVALE','MAP_MOND_WOLVENDOM','MAP_CRPG_WHISPER_HUNT','MAP_LIYUE_PLAINS','MAP_LIYUE_JUEYUN','MAP_LY_DETAIL_QINGCE_FIELDS','MAP_LY_DETAIL_NANTIANMEN','MAP_LY_DETAIL_YAOGUANG','MAP_CRPG_CIDER_BANK']}={}){
 const rows=[];for(const map of maps){const template=fresh(map),kind=template.lifeKindAt(map),samples=[];for(let i=0;i<count;i++){
   const r=Object.create(template);r.s=copy(template.s);r.s.global.PRNG_STATE=((i+1)*2654435761)>>>0;r.s.global.SAVE_ID='FOOD-SUPPLY-SAMPLE-'+map+'-'+i;r.s.global.LAST_COMMITTED_ACTION_ID='';
   if(kind==='FISH'){r.giveItem('TRPG_FISHING_ROD',1);r.giveItem(api.lifeCatalog.bait,1);}samples.push(harvest(r,kind));
  }
  const totals={};for(const s of samples)for(const [id,n]of Object.entries(s.items))totals[id]=(totals[id]||0)+n;
  rows.push({map,name:template.row('32_MAP_DB',map)[2],region:template.row('32_MAP_DB',map)[1],kind,resourceLimit:template.lifeEntries().find(x=>x.kind===kind)?.limit,pool:copy(template.lifePool(kind,map)),sampleCount:samples.length,meanElapsedSeconds:samples.reduce((n,s)=>n+s.elapsedMs/1000,0)/samples.length,meanInputs:samples.reduce((n,s)=>n+s.inputCount,0)/samples.length,meanNpcOpportunityMora:samples.reduce((n,s)=>n+Object.entries(s.items).reduce((m,[id,k])=>m+k*template.saleUnitPrice({item:id}),0),0)/samples.length,meanItems:Object.fromEntries(Object.entries(totals).map(([id,n])=>[id,n/samples.length])),encounterStarts:samples.filter(s=>s.encounter).length,samples});
 }return rows;
}
function persistentHp(r){return PARTY.map(owner=>{const a=owner==='PLAYER_CUSTOM'?r.player():r.character(owner);return {owner,level:a.level,hp:a.hp,maxHp:a.maxHp};});}
function policy(r){
 if(r.s.runtime&&r.combatOpening?.())r.action('COMBAT_BEGIN');for(let n=0;r.s.runtime&&n<400;n++){
  const b=r.s.runtime;if(b.liyueInterlude){r.action('LIYUE_INTERLUDE_ACK');continue;}if(b.interlude){r.action('STORY_NEXT',{node:r.storyActiveNodeId()});continue;}
  const cards=r.combatCards().filter(x=>!x.reason),enemies=b.actors.filter(a=>a.side==='ENEMY'&&a.hp>0);
  let card=cards.find(x=>x.id==='SYS_MOND_WIND_ROUTE')||cards.find(x=>/PLAYER_(?:TRAVELER_ANEMO|ISEKAI)_Q$/.test(x.id))||cards.find(x=>x.id==='PLAYER_TRAVELER_ANEMO_E');
  if(!card&&enemies.some(a=>a.hp>a.maxHp*.8))card=cards.find(x=>x.id==='PLAYER_ISEKAI_E');card??=cards.find(x=>x.id==='PLAYER_BASIC_ATTACK')||cards.find(x=>x.id==='PLAYER_BASIC_GUARD');if(!card){r.autoUntilPlayer();continue;}
  const target=(card.targets||[]).map(x=>enemies.find(a=>a.id===x.id)||x).sort((a,b)=>(a.hp??Infinity)-(b.hp??Infinity))[0];r.action('COMBAT',{card:card.id,...(target?{target:target.id}:{}),...(card.id==='PLAYER_TRAVELER_ANEMO_E'?{branch:'HOLD'}:{})});
 }if(r.s.runtime)throw Error('SUPPLY_TRAVEL_STALEMATE');const result=JSON.parse(r.s.global.LAST_BATTLE_RESULT_JSON||'{}');if(!result.victory)throw Error('SUPPLY_TRAVEL_DEFEAT');return result;
}
function campaign({recipe,region='MOND',seed=717,level=55,route='ROUTE_TRAVELER',loss=.25,quantity=4,maxHarvests=60}={}){
 const spec=SOURCES[region],start=region==='MOND'?'MAP_MOND_PLAINS':'MAP_LIYUE_PLAINS',r=fresh(start,level,route,seed),q=r.recipeDefinition(recipe),cost=r.recipeCost(q,quantity),item=q[3],startingMora=r.s.global.MORA;
 for(const x of persistentHp(r)){const hp=Math.floor(x.maxHp*(1-loss));if(x.owner==='PLAYER_CUSTOM')r.s.global.PLAYER_HP_CURRENT=hp;else r.s.chars[x.owner].hp=hp;}
 const row={recipe,food:item,region,level,route,seed,quantity,initialFoodAndIngredientInventory:{},syntheticInitialGear:r.s.inventory.filter(x=>x.equip).map(x=>({equip:x.equip,owner:x.owner,enhance:x.enhance})),initialHp:persistentHp(r),startingMora,syntheticFunding:true,rawRequirements:copy(cost.items),craftMora:cost.mora,harvests:[],actions:[],encounters:[],crafts:[],purchases:[],seconds:0,upperBoundSeconds:0,inputs:0,failed:false};
 const initial=copy(r.s),nativeAction=r.action;let frameMs=0,battleInputs=0;
 r.action=function(type,args){const before=c.CRPGPresentation.snapshot(this.s),out=nativeAction.call(this,type,args);for(const f of c.CRPGPresentation.actionFrames(c.CRPGPresentation.delta(before,this.s))){if(f.kind==='state'&&f.silent)continue;frameMs+=f.kind==='action'?460+(f.attemptCount>1?520:650):1400;}if(type==='COMBAT')battleInputs++;return out;};
 function act(type,args={},visual=0){row.inputs++;row.seconds+=visual+3;row.upperBoundSeconds+=visual+3;const frameBefore=frameMs,inputBefore=battleInputs;const out=r.action(type,args).result;row.actions.push({type,...args,map:r.s.global.CURRENT_MAP_ID,cost:out?.cost??null,gameMinutes:out?.minutes??null});if(r.s.runtime){const result=policy(r),seconds=(frameMs-frameBefore)/1000+(battleInputs-inputBefore)*3+6;row.encounters.push({result:copy(result),seconds,hp:persistentHp(r)});row.seconds+=seconds;row.upperBoundSeconds+=seconds;}return out;}
 function move(map){if(r.s.placeVisit)act('PLACE_LEAVE',{},1);const nav=r.navigationRoute(map);if(!nav)throw Error('NO_SUPPLY_ROUTE:'+map);for(const edge of nav.edges)act('MOVE',{edge:edge[0]},1);}
 function waitOpen(place,mode){let reason=r.placeEntryReason(place,mode),tries=0;while(reason&&tries++<25){act('WAIT',{minutes:60},3);reason=r.placeEntryReason(place,mode);}if(reason)throw Error('FACILITY_BLOCKED:'+reason);}
 function enter(place,mode){if(r.s.placeVisit)act('PLACE_LEAVE',{},1);waitOpen(place,mode);act('PLACE_ENTER',{place,mode},1);}
 function buyRaw(id,n){move(spec.city);enter(spec.shop,'SHOP');const s=pricedCityCatalog(r,region)[id];if(!s)throw Error('NO_NATIVE_SHOP_INGREDIENT:'+id);let need=n;while(need>0){const stock=r.row('19_SHOP_STOCK_DB',s.stock),available=r.stockRemaining?r.stockRemaining(stock):Math.min(need,s.stockQuantity);let amount=Math.min(need,s.stockQuantity,available);if(amount<=0){act('WAIT',{minutes:1440},3);continue;}let reason=r.stockReason(stock,amount);if(reason&&/재고/.test(reason)){act('WAIT',{minutes:1440},3);continue;}if(reason)throw Error('INGREDIENT_PURCHASE_BLOCKED:'+reason);const out=act('BUY',{stock:s.stock,quantity:amount});row.purchases.push({item:id,quantity:amount,mora:out.cost,stock:s.stock});need-=amount;}}
 function needIngredient(id,n,stack=[]){if(r.itemCount(id)>=n)return;if(stack.includes(id))throw Error('RECIPE_CYCLE');
  const maps=r.rows('32_MAP_DB').filter(m=>m[1]===spec.region&&r.lifeKindAt(m[0])&&r.lifePool(r.lifeKindAt(m[0]),m[0]).some(x=>x.item===id)).map(m=>{const kind=r.lifeKindAt(m[0]),pool=r.lifePool(kind,m[0]),p=pool.find(x=>x.item===id),weight=pool.reduce((n,x)=>n+x.weight,0);return {map:m[0],kind,mean:(kind==='GATHER'?6.75:kind==='HUNT'?6.25:3)*p.weight/weight};}).sort((a,b)=>b.mean-a.mean);
  if(maps.length){let loop=0;while(r.itemCount(id)<n){if(row.harvests.length>=maxHarvests)throw Error('HARVEST_LIMIT');let next=maps.find(m=>{const p=r.s.lifeResources?.[m.map+':'+m.kind];return !(p?.day===r.s.global.WORLD_DAY&&p.used>=4);});if(!next){act('WAIT',{minutes:1440},3);continue;}move(next.map);if(next.kind==='FISH'){if(!r.itemCount('TRPG_FISHING_ROD'))buyRaw('TRPG_FISHING_ROD',1);if(!r.itemCount(api.lifeCatalog.bait))buyRaw(api.lifeCatalog.bait,1);move(next.map);}const frameBefore=frameMs,inputBefore=battleInputs,h=harvest(r,next.kind);row.harvests.push(h);row.inputs+=2+h.inputCount;row.seconds+=6+h.elapsedMs/1000;row.upperBoundSeconds+=6+h.upperBoundMs/1000;if(r.s.runtime){const result=policy(r),seconds=(frameMs-frameBefore)/1000+(battleInputs-inputBefore)*3+6;row.encounters.push({result:copy(result),seconds,hp:persistentHp(r)});row.seconds+=seconds;row.upperBoundSeconds+=seconds;}if(++loop>maxHarvests)throw Error('INGREDIENT_NEVER_DROPPED');}return;}
  const process=r.rows('17_RECIPE_DB').map(x=>r.recipeDefinition(x[0])).find(x=>x[2]==='ITEM'&&x[3]===id&&['식재료 가공','가공'].includes(x[1]));
  if(process){const count=Math.ceil((n-r.itemCount(id))/process[4]),p=r.recipeCost(process,count);for(const [child,k]of Object.entries(p.items))needIngredient(child,k,[...stack,id]);move(spec.cookMap);enter(spec.cook,'CRAFT');const out=act('CRAFT',{recipe:process[0],quantity:count},1.4);row.crafts.push(copy(out));return;}
  buyRaw(id,n-r.itemCount(id));
 }
 try{
  for(const [id,n]of Object.entries(cost.items))needIngredient(id,n);
  const purchased=String(q[18]||'').match(/^(STK_\w+(?: 또는 STK_\w+)*) 구매완료$/);if(purchased){const id=purchased[1].split(' 또는 ').find(id=>r.tables['19_SHOP_STOCK_DB'].has(id)),stock=r.row('19_SHOP_STOCK_DB',id),place=r.placeCatalog().find(p=>p.merchant===stock[1]&&p.modes.includes('SHOP'));if(!place)throw Error('NO_RECIPE_SHOP');move(place.maps[0]);enter(place.id,'SHOP');const out=act('BUY',{stock:id,quantity:1});row.purchases.push({recipe:q[0],stock:id,mora:out.cost,firstUnlock:true});}
  move(spec.cookMap);enter(spec.cook,'CRAFT');row.hpBeforeCook=persistentHp(r);const out=act('CRAFT',{recipe,quantity},1.4);row.crafts.push(copy(out));row.hpBeforeMeal=persistentHp(r);row.remainingBeforeMeal=Object.fromEntries(r.s.inventory.filter(x=>x.item).map(x=>[x.item,x.quantity]));
  const meals=PARTY.map(owner=>({owner,item})).filter(x=>{const a=r.economyOwner(x.owner);return a.hp>0&&a.hp<a.maxHp;});if(meals.length)row.meal=copy(act('MEAL_BATCH',{meals}));row.finalHp=persistentHp(r);move(start);row.finalHpAfterReturn=persistentHp(r);row.stop='PREPARED_AND_ONE_MEAL';
 }catch(e){row.failed=true;row.reason=e.code||e.message;row.stop='FAILED';row.finalHp=persistentHp(r);}
 row.finalMap=r.s.global.CURRENT_MAP_ID;row.finalMora=r.s.global.MORA;row.netMora=r.s.global.MORA-startingMora;row.purchasedMora=row.purchases.reduce((n,p)=>n+p.mora,0);row.firstUnlockMora=row.purchases.filter(p=>p.firstUnlock).reduce((n,p)=>n+p.mora,0);row.processCraftMora=row.crafts.filter(x=>x.recipe!==recipe).reduce((n,x)=>n+x.cost.mora,0);row.foodCraftMora=row.crafts.filter(x=>x.recipe===recipe).reduce((n,x)=>n+x.cost.mora,0);row.leftoverItems=Object.fromEntries(r.s.inventory.filter(x=>x.item).map(x=>[x.item,x.quantity]));row.leftoverNpcMora=Object.entries(row.leftoverItems).reduce((n,[id,k])=>n+r.saleUnitPrice({item:id})*k,0);row.harvestedNpcOpportunityMora=row.harvests.reduce((n,s)=>n+Object.entries(s.items).reduce((m,[id,k])=>m+r.saleUnitPrice({item:id})*k,0),0);row.inputIngredientNpcOpportunityMora=Object.entries(cost.items).reduce((n,[id,k])=>n+r.saleUnitPrice({item:id})*k,0);row.rngEnd=r.s.global.PRNG_STATE;row.worldDaysAdvanced=r.s.global.WORLD_DAY-initial.global.WORLD_DAY;
 // Equal initial damaged state, no food preparation: actual native inn round trip.
 const inn=Object.create(r);inn.s=copy(initial);delete inn.action;let seconds=0;const innActions=[],innEncounters=[];
 function innAct(type,args,visual){const before=c.CRPGPresentation.snapshot(inn.s);const result=nativeAction.call(inn,type,args).result;seconds+=visual+3;innActions.push({type,...args,map:inn.s.global.CURRENT_MAP_ID,cost:result?.cost??null});if(inn.s.runtime){let frames=0,inputs=0;inn.action=function(t,a){const b=c.CRPGPresentation.snapshot(this.s),o=nativeAction.call(this,t,a);for(const f of c.CRPGPresentation.actionFrames(c.CRPGPresentation.delta(b,this.s))){if(f.kind==='state'&&f.silent)continue;frames+=f.kind==='action'?460+(f.attemptCount>1?520:650):1400;}if(t==='COMBAT')inputs++;return o;};const battle=policy(inn),duration=frames/1000+inputs*3+6;seconds+=duration;innEncounters.push({result:copy(battle),seconds:duration});delete inn.action;}return result;}
 try{for(const e of inn.navigationRoute(spec.city).edges)innAct('MOVE',{edge:e[0]},1);innAct('PLACE_ENTER',{place:spec.inn,mode:'SHOP'},1);const quote=copy(inn.innRecoveryQuote(inn.row('19_SHOP_STOCK_DB',spec.stock))),receipt=innAct('BUY',{stock:spec.stock,quantity:1},3);for(const e of inn.navigationRoute(start).edges)innAct('MOVE',{edge:e[0]},1);row.innCounterfactual={seconds,quote,receipt,actions:innActions,encounters:innEncounters,finalHp:persistentHp(inn),netMora:inn.s.global.MORA-startingMora};}catch(e){row.innCounterfactual={failed:true,reason:e.code||e.message,seconds,actions:innActions,encounters:innEncounters};}
 return row;
}
function economyAudit(r){
 const active=r.rows('19_SHOP_STOCK_DB').filter(s=>!/SYSTEM_DISABLED|레거시|사용 금지/.test(s[8]||'')),prices={},definitions=[];
 for(const s of active)if(['ITEM','EQUIP'].includes(s[2])&&Number(s[5])>0){const key=s[2]+':'+s[3];prices[key]=Math.min(prices[key]??Infinity,Number(s[5]));}
 const discounted=Object.create(r);discounted.s=copy(r.s);discounted.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(Object.fromEntries(['MOND_ALBEDO','MOND_LISA','MOND_MONA'].map(id=>[id,{state:'JOINED'}])));discounted.s.party=[r.s.party[0],...['MOND_ALBEDO','MOND_LISA','MOND_MONA'].map((source,i)=>({slot:'PARTY_'+(i+2),type:'CHAR',source,control:'AI',active:true,tactic:'균형'}))];
 for(const raw of r.rows('17_RECIPE_DB')){const q=r.recipeDefinition(raw[0]);let cost=r.recipeCost(q),discount;try{discount=discounted.recipeCost(q);}catch(e){if(e.code!=='PASSIVE_RECIPE_CLASS')throw e;}if(discount)cost=discount;const item=q[2]==='ITEM'?r.tables['14_ITEM_DB'].get(q[3]):null,extra=q[2]==='ITEM'&&r.passiveRecipeKind(q)==='COOK'&&['STATUS_FOOD_ATK','STATUS_FOOD_FEAST'].includes(item?.[9])?1:0;definitions.push({id:q[0],kind:q[2],item:q[3],cost:copy(cost),output:Number(q[4])+extra,unlock:q[18]});}
 let loops=0;for(;loops<=definitions.length;loops++){let changed=false;for(const d of definitions){const p=(d.cost.mora+Object.entries(d.cost.items).reduce((n,[id,k])=>n+(prices['ITEM:'+id]??Infinity)*k,0))/d.output,key=d.kind+':'+d.item;if(p<(prices[key]??Infinity)){prices[key]=p;changed=true;}}if(!changed)break;}
 const rows=Object.entries(prices).map(([key,buy])=>{const [kind,id]=key.split(':'),sell=r.saleUnitPrice(kind==='ITEM'?{item:id}:{equip:id});return {kind,id,minimumCatalogMora:buy,npcResaleMora:sell,profit:sell-buy};});const violations=rows.filter(x=>x.profit>1e-8);assert.equal(violations.length,0,'NPC purchase/craft/resale loop');
 return {stockRows:active.length,recipeRows:definitions.length,pricedRoutes:rows.length,iterations:loops+1,violations,prices:rows,recipes:definitions,limits:['Global future/locked NPC routes are conservative lower bounds, not current reachable shops.','Includes eligible material discount and Xiangling attack-food bonus output.','No live market quotes, transactions or liquidity; not a proof of player market inflation.'],market:{minimumListingTotal:10,maximumListingTotal:9999999,fee:.05,minimumFee:1,maxListings:8,priceIsWholeBundle:true,tradeMinLevel:api.tradeRules.minLevel}};
}
function audit({samples=32,seeds=[717,4242,9031],campaigns=true}={}){
 const r=fresh(),data={schema:1,tool:'tools/audit_food_supply_v01617.cjs',packageVersion:JSON.parse(fs.readFileSync(path.join(runtimeRoot,'package.json'))).version,runtimeRoot,clock:CLOCK,loadedSource:loaded,loadedSourceDigest:sha(JSON.stringify(loaded)),dbSha256:sha(rawDb),toolSha256:sha(fs.readFileSync(__filename)),assumptions:{synthetic:['Initial four-member ownership, stated level/phase/talents/+6 equipment and story region unlocks.','Initial 200000 Mora is funding, excluded from income.','Initial HP is 25% damaged before each independent representative campaign.','Independent resource samples start already at map; travel and combat settlement excluded from rate averages.','Deterministic virtual clock advances by replayed inputs; elapsed is a timing model, not wall-clock user observation.'],noFreeIngredientsOrFood:true,noForcedDrops:true,noOpponentsOrBattleOverrides:true,realisticInputSeconds:3,sceneTapGapSeconds:.45,earlySceneCompletion:true,upperBoundSceneWaitSensitivity:true,nativeGameTimeDistinctFromRealElapsed:true,perfectSceneTaps:true,humanMissesAndNetworkLatencyExcluded:true,meals:'Representative one batch per four-party, not universal full recovery; actual missing/healed HP explicitly reported.',catalog:'All catalog rows retained; future region goods remain identified, not presumed reachable.'},cityPrices:Object.fromEntries(Object.keys(SOURCES).map(region=>[region,pricedCityCatalog(r,region)])),foods:foodCatalog(r),supply:supplySamples({count:samples}),campaigns:[],economy:economyAudit(r)};
 if(campaigns)for(const seed of seeds)for(const [region,recipe]of [['MOND','REC_FOOD_EGG_FRY'],['MOND','REC_FOOD_CHICKEN_SKEWER'],['MOND','REC_FOOD_HASH_BROWN'],['MOND','REC_FOOD_MATSUTAKE_ROLL'],['LIYUE','REC_FOOD_VEGETARIAN_ABALONE'],['LIYUE','REC_FOOD_PERCH_STEW']]){const row=campaign({region,recipe,seed});data.campaigns.push(row);console.log(JSON.stringify({kind:'campaign',recipe,region,seed,seconds:row.seconds,upperBoundSeconds:row.upperBoundSeconds,harvests:row.harvests.length,mora:row.purchasedMora+row.processCraftMora+row.foodCraftMora,firstUnlock:row.firstUnlockMora,innMora:row.innCounterfactual.receipt?.cost,failed:row.failed,reason:row.reason}));}
 data.counts={foods:data.foods.length,resourceConditions:data.supply.length,resourceSamples:data.supply.reduce((n,x)=>n+x.sampleCount,0),campaigns:data.campaigns.length,failedCampaigns:data.campaigns.filter(x=>x.failed).length,nativeCampaignHarvests:data.campaigns.reduce((n,x)=>n+x.harvests.length,0),campaignEncounters:data.campaigns.reduce((n,x)=>n+x.encounters.length,0),npcArbitrageViolations:data.economy.violations.length};return data;
}
function saveAudit(out,data){
 const compactBattle=e=>({seconds:e.seconds,result:{victory:e.result.victory,rounds:e.result.rounds,xp:e.result.xp,mora:e.result.mora,group:e.result.group},hp:e.hp});
 const full=JSON.stringify(data)+'\n',gzip=zlib.gzipSync(full,{level:9}),summary={...data,supply:data.supply.map(({samples,...row})=>({...row,exactReplaySamplesInFullEvidence:true})),campaigns:data.campaigns.map(({actions,encounters,innCounterfactual,...row})=>({...row,actionCount:actions.length,actionTypes:actions.reduce((n,a)=>(n[a.type]=(n[a.type]||0)+1,n),{}),encounters:encounters.map(compactBattle),harvests:row.harvests.map(({scene,inputs,...h})=>({...h,exactSceneAndInputsInFullEvidence:true})),innCounterfactual:{...innCounterfactual,encounters:innCounterfactual.encounters.map(compactBattle)}})),economy:{...data.economy,recipes:undefined,recipeCostsInFullEvidence:true},fullEvidence:{file:path.basename(out)+'.gz',uncompressedSha256:sha(full),gzipSha256:sha(gzip),uncompressedBytes:Buffer.byteLength(full),gzipBytes:gzip.length,deterministicGzip:true}};
 fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(summary,null,2)+'\n');fs.writeFileSync(out+'.gz',gzip);return summary;
}
if(require.main===module){const args=process.argv.slice(2),number=name=>args.includes(name)?Number(args[args.indexOf(name)+1]):undefined;const out=args.includes('--out')?args[args.indexOf('--out')+1]:path.join(root,'docs/data/food_supply_v01617_baseline.json'),data=audit({samples:number('--samples')||32,campaigns:!args.includes('--no-campaigns')});saveAudit(out,data);console.log(JSON.stringify({out,...data.counts}));}
module.exports={audit,foodCatalog,pricedCityCatalog,purchaseLowerBounds,purchaseLowerBound,supplySamples,sceneInputs,harvest,campaign,economyAudit,persistentHp,saveAudit,SOURCES,PARTY,loaded};
