'use strict';
// Observational material audit. No opponent, damage, shield, AI, HP, speed or
// between-fight healing overrides. Optional candidate tables replace only the
// awarded material quantities. Fresh native starts must have no 0.16.15 budget.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib');
const {setup,observe,G,api,PLAYER}=require('./audit_balance_v01522.cjs');
const {policy,REFERENCE_TEAM}=require('./audit_balance_v0161.cjs');
const {c,root,advance}=require('../tests/helpers_v011.cjs');
const AUDIT_CLOCK_MS=Date.parse('2026-10-09T05:00:00Z');advance(AUDIT_CLOCK_MS-c.Date.now());
const PARTY=[PLAYER,...REFERENCE_TEAM],STAGES=[5,10,15,20,25,30,35,40,45,50,55,60],ELEMENTS=['NEUTRAL','PYRO','HYDRO','ANEMO','ELECTRO','CRYO','GEO','DENDRO'];
const DEFAULT_OUT=path.join(root,'docs/data/material_rewards_v01616_baseline.json');
const copy=x=>JSON.parse(JSON.stringify(x)),digest=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');
function fingerprint(){const hash=crypto.createHash('sha256');for(const file of fs.readdirSync(path.join(root,'source')).filter(x=>x.endsWith('.js')).sort()){hash.update(file);hash.update(fs.readFileSync(path.join(root,'source',file)));}return hash.digest('hex');}
const SOURCE_SNAPSHOT={sourceFingerprint:fingerprint(),growthSourceSha256:digest('source/runtime_growth_v01522.js'),innSourceSha256:digest('source/runtime.js'),dbSha256:digest('content/db.json'),toolSha256:digest('tools/audit_material_rewards_v01616.cjs'),packageVersion:require('../package.json').version,auditClockMs:AUDIT_CLOCK_MS};
const persistentHp=r=>PARTY.map(owner=>({owner,level:r.growth(owner).level,phase:r.growthPhase(owner),hp:owner===PLAYER?r.s.global.PLAYER_HP_CURRENT:r.s.chars[owner].hp,maxHp:owner===PLAYER?r.s.global.PLAYER_HP_MAX:r.character(owner).maxHp}));
const itemCount=(r,id)=>r.s.inventory.filter(x=>x.item===id).reduce((n,x)=>n+Number(x.quantity||0),0);
const needRest=r=>persistentHp(r).some(x=>x.hp<=0||x.hp/x.maxHp<.5);
function trimDiagnosticHistory(r){if(r.s.log.length>30)r.s.log=r.s.log.slice(-30);const receipts=Object.entries(r.s.combatReceipts||{});if(receipts.length>30)r.s.combatReceipts=Object.fromEntries(receipts.slice(-30));}
function tablePayout(tables,kind,region,stage){const table=kind==='TALENT'?(tables.TALENT?.[region==='몬드'?'MOND':'LIYUE']||tables.TALENT):tables.ASCENSION;const value=table?.[stage];if(!Number.isSafeInteger(value)||value<=0)throw Error('Candidate material quantity must be a positive safe integer: '+kind+' '+region+' '+stage);return value;}
function campaign({kind='TALENT',level=20,stage=20,route='ROUTE_TRAVELER',element='NEUTRAL',seed=717,limit=12,target=0,recovery=true,settleFinalRecovery=false,rewardTables=null,startingMora=200000,enhance=level<30?3:6,talent='mid',onProgress=()=>{}}={}){
 const match=Object.entries(G.domains).find(([,x])=>x.kind===kind&&x.levels.includes(stage));if(!match)throw Error('Missing material domain stage');const [key,site]=match,domain=key+':'+stage;
 const r=setup({level,route,team:REFERENCE_TEAM,map:site.map,gear:'craft',enhance,talent,saveId:'MATERIAL-V01616-'+route+'-L'+level+'-S'+seed});Object.assign(r.tutorialState().done,{combatAttack:true,combatGuard:true,combatSkill:true,combatBurst:true});
 r.s.global.PRNG_STATE=seed;r.s.global.MORA=startingMora;r.s.domainDaily={day:G.dayOf(r.leyLineNow()),wins:3};observe(r);
 if(rewardTables){const nativeRewards=r.growthDomainRewards;r.growthDomainRewards=function(d,e,...args){const reward=nativeRewards.call(this,d,e,...args);if(['TALENT','ASCENSION'].includes(d.kind)){const id=d.kind==='TALENT'?'GROWTH_TALENT_'+(d.region==='몬드'?'MOND':'LIYUE'):'GROWTH_GEM_'+e;reward.items[id]=tablePayout(rewardTables,d.kind,d.region,d.level)*(reward.bonus?2:1);}return reward;};}
 const nativeAction=r.action;let presentationMs=0,inputs=0;
 r.action=function(type,args){const before=c.CRPGPresentation.snapshot(this.s),out=nativeAction.call(this,type,args);for(const frame of c.CRPGPresentation.actionFrames(c.CRPGPresentation.delta(before,this.s))){if(frame.kind==='state'&&frame.silent)continue;presentationMs+=frame.kind==='action'?460+(frame.attemptCount>1?520:650):1400;}if(type==='COMBAT')inputs++;return out;};
 const item=kind==='TALENT'?'GROWTH_TALENT_'+(site.region==='몬드'?'MOND':'LIYUE'):'GROWTH_GEM_'+element;
 const row={saveId:r.s.global.SAVE_ID,auditClockMs:AUDIT_CLOCK_MS,kind,level,phase:G.phaseFor(level),stage,region:site.region,domain,route,element,seed,enhance,talent,limit,target,recovery,settleFinalRecovery,rewardMode:rewardTables?'MATERIAL_QUANTITY_CANDIDATE':'NATIVE_SOURCE',rewardTables:rewardTables?copy(rewardTables):null,item,party:PARTY,initialHp:persistentHp(r),startingMora,syntheticFunding:true,wins:0,losses:0,materials:0,experiencePerParticipant:0,seconds:0,battles:[],recoveries:[],nativeFreshCombatBudgetAbsent:true};
 function nativeRest(){
  const before=persistentHp(r),wallet=r.s.global.MORA,actions=[],encounters=[],city=site.region==='몬드'?'MAP_MOND_CITY':'MAP_LIYUE_HARBOR',stock=site.region==='몬드'?'STK_INN_MOND':'STK_INN_LIYUE',place=site.region==='몬드'?'EVT_SCHEDULE_MRC_MOND_INN':'EVT_SCHEDULE_MRC_LIYUE_INN';let seconds=0,lodgingCost=0,quote=null,receipt=null;
  function act(type,args,visual){const startMs=presentationMs,startInputs=inputs;seconds+=visual+3;const out=r.action(type,args);actions.push({type,...args,map:r.s.global.CURRENT_MAP_ID});if(r.s.runtime){const result=policy(r),duration=(presentationMs-startMs)/1000+(inputs-startInputs)*3+6+Number(result.defeatPenalty?.seconds||0);seconds+=duration;encounters.push({result:copy(result),seconds:duration,hpAfter:persistentHp(r),rngAfter:r.s.global.PRNG_STATE});if(!result.victory)throw Error('RECOVERY_TRAVEL_DEFEAT');}return out;}
  try{
   const outward=r.navigationRoute(city);if(!outward)throw Error('NO_LODGING_ROUTE');for(const edge of outward.edges)act('MOVE',{edge:edge[0]},1);
   act('PLACE_ENTER',{place,mode:'SHOP'},1);quote=copy(r.innRecoveryQuote(r.row('19_SHOP_STOCK_DB',stock)));const costBefore=r.s.global.MORA;receipt=copy(act('BUY',{stock,quantity:1},3));lodgingCost=costBefore-r.s.global.MORA;
   if(lodgingCost!==quote.cost)throw Error('LODGING_QUOTE_RECEIPT_MISMATCH');const afterLodging=persistentHp(r);if(afterLodging.some(x=>x.hp!==x.maxHp))throw Error('LODGING_HP_MISMATCH');
   const backward=r.navigationRoute(site.map);if(!backward)throw Error('NO_RETURN_ROUTE');for(const edge of backward.edges)act('MOVE',{edge:edge[0]},1);
   return {before,afterLodging,after:persistentHp(r),actions,encounters,seconds,lodgingCost,quote,receipt,mora:r.s.global.MORA-wallet};
  }catch(error){return {failed:true,reason:error.code||error.message,before,after:persistentHp(r),actions,encounters,seconds,lodgingCost,quote,receipt,mora:r.s.global.MORA-wallet};}
 }
 for(let index=0;index<limit;index++){
  if(recovery&&needRest(r)){const trip=nativeRest();row.recoveries.push(trip);row.seconds+=trip.seconds;row.finalHp=persistentHp(r);if(trip.failed){row.stop='RECOVERY_FAILED';row.reason=trip.reason;break;}}
  const reason=r.actionReason('DOMAIN_START',{domain,element});if(reason){row.stop='ENTRY_BLOCKED';row.reason=reason;break;}
  const hpBefore=persistentHp(r),rngBefore=r.s.global.PRNG_STATE,countBefore=itemCount(r,item),walletBefore=r.s.global.MORA;presentationMs=0;inputs=0;r.action('DOMAIN_START',{domain,element});
  if(r.s.runtime.materialBudget||r.s.runtime.growthDomain?.materialBudgetVersion!==undefined)throw Error('Fresh material combat is still using v15 difficulty tuning; refusing native measurement.');
  const enemies=[...r.s.runtime.actors,...(r.s.runtime.enemyReserve||[])].filter(a=>a.side==='ENEMY').map(a=>({source:a.source,hp:a.maxHp,atk:a.atk,def:a.def,spd:a.spd,shield:(a.shields||[]).reduce((n,s)=>n+s.value,0)}));
  const result=policy(r),materials=itemCount(r,item)-countBefore,seconds=presentationMs/1000+inputs*3+6+Number(result.defeatPenalty?.seconds||0),hpAfter=persistentHp(r);
  row.battles.push({index:index+1,hpBefore,hpAfter,rngBefore,rngAfter:r.s.global.PRNG_STATE,enemies,result:copy(result),materials,mora:r.s.global.MORA-walletBefore,seconds,presentationMs,inputs});row.wins+=result.victory?1:0;row.losses+=result.victory?0:1;row.materials+=materials;row.experiencePerParticipant+=Number(result.xp||0);row.seconds+=seconds;row.finalHp=hpAfter;
  trimDiagnosticHistory(r);onProgress(row);
  if(!result.victory){row.stop='FIRST_LOSS';break;}
  if(target>0&&row.materials>=target){row.stop='TARGET_REACHED';break;}
 }
 if(settleFinalRecovery&&recovery&&!row.stop&&needRest(r)){const trip=nativeRest();row.recoveries.push(trip);row.seconds+=trip.seconds;if(trip.failed){row.stop='RECOVERY_FAILED';row.reason=trip.reason;}}
 row.stop??='VICTORY_LIMIT';row.materialsPerMinute=row.materials*60/row.seconds;row.meanSeconds=row.seconds/row.battles.length;row.meanBattleSeconds=row.battles.reduce((n,x)=>n+x.seconds,0)/row.battles.length;row.meanRounds=row.battles.reduce((n,x)=>n+x.result.rounds,0)/row.battles.length;row.recoveryExcluded=!recovery;row.netMora=r.s.global.MORA-startingMora;row.finalMora=r.s.global.MORA;row.finalHp=persistentHp(r);row.lodgingMora=row.recoveries.reduce((n,x)=>n+x.lodgingCost,0);row.lodgingCount=row.recoveries.filter(x=>x.receipt).length;row.travelEncounterCount=row.recoveries.reduce((n,x)=>n+x.encounters.length,0);return row;
}
function compact(row){const {battles,recoveries,...rest}=row;return {...rest,battleCount:battles.length,minimumHpRatio:Math.min(...battles.flatMap(b=>b.hpAfter.map(h=>h.hp/h.maxHp))),recoveries:recoveries.map(q=>({failed:q.failed||false,reason:q.reason||null,seconds:q.seconds,lodgingCost:q.lodgingCost,quote:q.quote,encounterCount:q.encounters.length})),openingEnemies:battles[0]?.enemies};}
function baselineCases({limit=12,routes=['ROUTE_TRAVELER','ROUTE_ISEKAI'],seeds=[717]}={}){const cases=[];for(const route of routes)for(const seed of seeds){for(const stage of STAGES)for(const element of ELEMENTS)cases.push({kind:'ASCENSION',level:55,stage,element,route,seed,limit,recovery:true,settleFinalRecovery:true,mode:'NATIVE_BASELINE_SCREENING'});for(const level of [20,55])for(const stage of STAGES.filter(x=>x<=level+5))cases.push({kind:'TALENT',level,stage,route,seed,limit,recovery:true,settleFinalRecovery:true,mode:'NATIVE_BASELINE_SCREENING'});}return cases;}
function saveAudit(out,data,full=true){fs.mkdirSync(path.dirname(out),{recursive:true});const summary={...data,rows:data.rows.map(compact)};fs.writeFileSync(out,JSON.stringify(summary,null,2)+'\n');if(full)fs.writeFileSync(out+'.gz',zlib.gzipSync(JSON.stringify(data)+'\n',{level:9}));}
function runCases(cases,{out=DEFAULT_OUT,rewardTables=null,label='NATIVE_BASELINE'}={}){
 const data={version:require('../package.json').version,tool:'tools/audit_material_rewards_v01616.cjs',sourceSnapshot:copy(SOURCE_SNAPSHOT),label,rewardTables,timing:{displaySpeed:2,internalSpeed:1,presentationDivisor:1000,inputSeconds:3,reentrySeconds:6,silentFramesExcluded:true,travelSecondsPerMove:4,facilityEntrySeconds:4,lodgingSeconds:6},assumptions:{party:PARTY,oneInitialFullHp:true,noBetweenBattleArtificialHeal:true,prngSeedOncePerCampaign:true,deterministicSaveIdPerRouteLevelSeed:true,auditClockMs:AUDIT_CLOCK_MS,recoveryAt:'Before the next fight if any active target is dead or below 50% HP',actualNativeTravelAndInnBuy:true,baselineSettlesLastFightRequiredRest:true,finalTargetDoesNotRequireArtificialExtraRest:true,noEnemyOrDamageOverrides:true,synthetic:['Ownership and story unlocks','Legal stated equipment and mid talents','Starting 200000 Mora wallet, excluded from earned income'],excluded:['Human and network latency','Obtaining starting gear and money','Obtaining food and market items'],diagnosticHistory:'Retain last 30 native log/receipt records to bound audit VM cloning; action sequence, actual inventory/XP/HP/PRNG remain native.'},rows:[]};
 saveAudit(out,data);for(let index=0;index<cases.length;index++){const options=cases[index],row=campaign({...options,rewardTables:options.rewardTables??rewardTables});row.mode=options.mode||label;data.rows.push(row);saveAudit(out,data,index%8===7||index===cases.length-1);console.log(JSON.stringify({index:index+1,total:cases.length,kind:row.kind,level:row.level,stage:row.stage,route:row.route,element:row.element,materials:row.materials,wins:row.wins,losses:row.losses,seconds:row.seconds,meanSeconds:row.meanSeconds,inns:row.lodgingCount,lodgingMora:row.lodgingMora,netMora:row.netMora,stop:row.stop,reason:row.reason}));}
 data.finishedSourceFingerprint=fingerprint();data.sourceStayedUnchanged=data.finishedSourceFingerprint===data.sourceSnapshot.sourceFingerprint;data.counts={conditions:data.rows.length,nativeDomainBattles:data.rows.reduce((n,r)=>n+r.battles.length,0),wins:data.rows.reduce((n,r)=>n+r.wins,0),losses:data.rows.reduce((n,r)=>n+r.losses,0),lodgingReceipts:data.rows.reduce((n,r)=>n+r.lodgingCount,0),travelEncounters:data.rows.reduce((n,r)=>n+r.travelEncounterCount,0)};saveAudit(out,data);return data;
}
if(require.main===module){const option=name=>{const i=process.argv.indexOf(name);return i<0?undefined:process.argv[i+1];},out=option('--out')||DEFAULT_OUT,casesFile=option('--cases'),tablesFile=option('--tables'),limit=Number(option('--limit')||12);runCases(casesFile?JSON.parse(fs.readFileSync(casesFile)):baselineCases({limit,routes:(option('--routes')||'ROUTE_TRAVELER,ROUTE_ISEKAI').split(','),seeds:(option('--seeds')||'717').split(',').map(Number)}),{out,rewardTables:tablesFile?JSON.parse(fs.readFileSync(tablesFile)):null,label:tablesFile?'MATERIAL_QUANTITY_CANDIDATE':'NATIVE_BASELINE'});}
module.exports={campaign,baselineCases,runCases,compact,persistentHp,itemCount,tablePayout,SOURCE_SNAPSHOT,STAGES,ELEMENTS,PARTY,DEFAULT_OUT};
