'use strict';
// Read-only reproduction of the historical growth fixture and its exact all-AI policy.
// Counterfactual replacements affect an isolated VM only, never product source files.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),zlib=require('node:zlib');
const arg=k=>{const i=process.argv.indexOf(k);return i<0?null:process.argv[i+1];},root=arg('--root')||path.resolve(__dirname,'..'),baseline=arg('--baseline')||'/tmp/crpg_v01619_baseline',out=arg('--out')||path.join(root,'docs/data/qa_v01619/growth_regression_validation'),cp=x=>JSON.parse(JSON.stringify(x)),team=['MOND_AMBER','MOND_KAEYA','MOND_NOELLE'];
const clock=Date.now(),cases=[['MAP_MOND_WOLVENDOM','EG_MOND_HILI_ELITE',[17,30,45]],['MAP_LIYUE_PLAINS','EG_LIYUE_HILI_ROCK',[32,45,60]]].flatMap(([map,group,levels])=>levels.flatMap(level=>[11,22,33].map(seed=>({map,group,level,seed}))));
function load(dir,mode='NATIVE'){
 const c=vm.createContext({console,Date:class extends Date{static now(){return clock;}},setTimeout,clearTimeout}),index=fs.readFileSync(path.join(dir,'source/index.html'),'utf8'),hash=crypto.createHash('sha256'),sources=[],substitutions=[];
 const legacyRules=['OLD_REACTION_SELECTION','OLD_ALL_THREE'].includes(mode)?fs.readFileSync(path.join(baseline,'source/runtime_rules.js'),'utf8'):'';
 for(const[,name]of index.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)){
  let source=fs.readFileSync(path.join(dir,'source',name),'utf8');hash.update(name);hash.update(source);sources.push({path:'source/'+name,sha256:crypto.createHash('sha256').update(source).digest('hex')});
  const replace=(from,to)=>{if(source.split(from).length!==2)throw Error('Counterfactual expected one match: '+from);source=source.replace(from,to);substitutions.push({name,from,to});};
  if(name==='runtime_combat.js'&&['OLD_SEQUENTIAL_SHIELDS','OLD_ALL_THREE'].includes(mode))replace("else if(t.side==='ALLY'){","else if(false&&t.side==='ALLY'){");
  if(name==='runtime_rules.js'&&['OLD_MELT_FREEZE','OLD_ALL_THREE'].includes(mode))replace("case'RX_MELT_PYRO':t.statuses=t.statuses.filter(s=>s.id!=='STATUS_FREEZE');break;","case'RX_MELT_PYRO':break;");
  if(name==='runtime_rules.js'&&['OLD_REACTION_SELECTION','OLD_ALL_THREE'].includes(mode)){
   const start=source.indexOf('P.reactionFor=function(t,element,o={})'),end=source.indexOf('P.reactionSupportReason=function',start),oldStart=legacyRules.indexOf('P.reactionFor=function(t,element,o={})'),oldEnd=legacyRules.indexOf('P.reactionSupportReason=function',oldStart);
   if([start,end,oldStart,oldEnd].some(n=>n<0))throw Error('Reaction function boundaries missing');const from=source.slice(start,end),to=legacyRules.slice(oldStart,oldEnd);replace(from,to);
  }
  vm.runInContext(source,c,{filename:name});
 }
 const raw=fs.readFileSync(path.join(dir,'content/db.json'));hash.update(raw);const db=JSON.parse(raw),R=c.CRPGRuntime.Runtime;let freshId=0;
 function fresh(map='MAP_MOND_CITY',route='ROUTE_TRAVELER'){
  const r=new R(db);r.newGame({name:'클라나드',route,seed:71247,saveId:'V011-'+(++freshId)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,STORY_MENU_POLICY:'',WORLD_TIME:'12:00',MORA:3000});delete r.s.storyJourney;delete r.s.storyBreak;r.prepareStory();return r;
 }
 const helperSource=fs.readFileSync(path.join(root,'tests/helpers_balance_v0141.cjs'),'utf8'),helperModule={exports:{}},hc=vm.createContext({console,module:helperModule,require:filename=>{if(filename==='./helpers_v011.cjs')return{fresh,c,db,R};throw Error('Unexpected helper dependency '+filename);}});vm.runInContext(helperSource,hc,{filename:'helpers_balance_v0141.cjs'});
 return{R,db,c,...helperModule.exports,mode,fingerprint:hash.digest('hex'),sources,substitutions,root:dir,helperSha256:crypto.createHash('sha256').update(helperSource).digest('hex')};
}
function observe(env,spec){
 const r=env.fixture(Array(4).fill(spec.level),team,3),trace={heals:[],shieldCasts:[],damagePackets:[],attempts:[]};Object.assign(r.s.global,{CURRENT_MAP_ID:spec.map,SAVE_ID:'GROWTH-FEEL-'+spec.seed,LAST_COMMITTED_ACTION_SEQ:0});
 const fixture={talents:cp(r.s.talents||{}),ascensions:cp(r.s.ascensions),equipment:cp(r.s.inventory.filter(x=>x.equipped)),party:cp(r.s.party)},nativeHeal=r.heal,nativeShield=r.shield,nativeApply=r.applyDamage,nativeDamage=r.damage,nativeFinish=r.finishBattle,nativeStart=r.startBattle;let firstActors,finished;
 r.heal=function(a,n,...args){const before=a.hp,applied=nativeHeal.call(this,a,n,...args);trace.heals.push({actor:a.source,targetId:a.id,round:this.s.runtime?.round,requested:n,applied,before,after:a.hp,source:args[0]});return applied;};
 r.shield=function(a,value,source,...args){const before=cp(a.shields||[]),result=nativeShield.call(this,a,value,source,...args);trace.shieldCasts.push({actor:a.source,targetId:a.id,round:this.s.runtime?.round,value,source,before,after:cp(a.shields||[])});return result;};
 r.applyDamage=function(a,t,n,d={}){const before={hp:t.hp,shields:cp(t.shields||[])},round=this.s.runtime?.round,result=nativeApply.call(this,a,t,n,d);trace.damagePackets.push({actor:a.source,target:t.source,actorId:a.id,targetId:t.id,actorSide:a.side,targetSide:t.side,round,requested:n,details:cp(d),result,before,after:{hp:t.hp,shields:cp(t.shields||[])}});return result;};
 r.damage=function(a,t,k,e,o={}){const round=this.s.runtime?.round,result=nativeDamage.call(this,a,t,k,e,o);trace.attempts.push({actor:a.source,target:t?.source,actorId:a.id,targetId:t?.id,actorSide:a.side,targetSide:t?.side,round,coefficient:k,element:e,options:cp(o),landed:result});return result;};
 r.startBattle=function(...args){const result=nativeStart.apply(this,args);firstActors=cp(this.s.runtime?.actors||[]);return result;};
 r.finishBattle=function(win){if(this.s.runtime)finished={victory:win,round:this.s.runtime.round,actors:cp(this.s.runtime.actors),fields:cp(this.s.runtime.fields),log:cp(this.s.runtime.log)};return nativeFinish.call(this,win);};
 const result=env.run(r,spec.group,spec.seed),log=finished?.log||r.s.runtime?.log||[],count=arr=>Object.fromEntries([...new Set(arr)].map(x=>[x,arr.filter(y=>y===x).length])),packets=trace.damagePackets,allyPackets=packets.filter(p=>p.targetSide==='ALLY'),enemyPackets=packets.filter(p=>p.targetSide==='ENEMY');
 return{...spec,mode:env.mode,fingerprint:env.fingerprint,fixture,initialActors:firstActors,stats:result.stats,result:result.result,finished:finished||null,stalledBattle:r.s.runtime?cp(r.s.runtime):null,storedState:{mode:r.s.global.MODE,screen:r.s.global.SCREEN_MODE,map:r.s.global.CURRENT_MAP_ID,playerHp:r.s.global.PLAYER_HP_CURRENT,chars:team.map(id=>({id,level:r.s.chars[id].level,hp:r.s.chars[id].hp})),result:cp(r.s.global.LAST_BATTLE_RESULT_JSON||'')},trace,metrics:{healing:trace.heals.reduce((s,h)=>s+h.applied,0),healEvents:trace.heals.length,healingSources:count(trace.heals.map(h=>h.source||h.actor)),shieldSources:count(trace.shieldCasts.map(h=>h.source)),allyHpLost:allyPackets.reduce((s,p)=>s+Math.max(0,p.before.hp-p.after.hp),0),enemyHpLost:enemyPackets.reduce((s,p)=>s+Math.max(0,p.before.hp-p.after.hp),0),shieldStrengthConsumed:allyPackets.reduce((s,p)=>s+Math.max(0,p.before.shields.reduce((n,h)=>n+h.value,0)-p.after.shields.reduce((n,h)=>n+h.value,0)),0),multiAllyShieldPackets:allyPackets.filter(p=>p.before.shields.filter(s=>s.value>0).length>=2).length,misses:log.filter(x=>x.miss).length,allyMisses:log.filter(x=>x.miss&&firstActors.some(a=>a.side==='ALLY'&&(a.id===x.actorId||a.name===x.actor))).length,enemyMisses:log.filter(x=>x.miss&&firstActors.some(a=>a.side==='ENEMY'&&(a.id===x.actorId||a.name===x.actor))).length,reactions:count(log.filter(x=>x.text?.endsWith(' 반응')).map(x=>x.reaction)),cards:count(log.filter(x=>x.cardName).map(x=>x.card||x.cardName))}};
}
function main(){fs.mkdirSync(out,{recursive:true});const data={schemaVersion:1,baselinePublishedCommit:'1e1b2442b53d42873d29556898f5f612d52d0c7a',clock,assumptions:{fixture:'Unmodified tests/helpers_balance_v0141.cjs fixture; Isekai + Amber/Kaeya/Noelle; enhancement3; default talent1; starting full HP.',policy:'Unmodified helper run; COMBAT_BEGIN, optional wind route, then all allies AI and autoUntilPlayer up to200 cycles.',enemy:'Explicit group; no enemy parameter modifications.',counterfactuals:'Isolated VM substitutions on final source only. Enemy and player fixtures/policy remain identical.',interpretation:'Equal initial seed does not force equal later draws when combat behavior changes.'},environments:[],rows:[],isolations:[],errors:[]};
for(const [name,dir]of [['baseline',baseline],['final',root]]){const env=load(dir);data.environments.push({name,...env,R:undefined,db:undefined,c:undefined,fixture:undefined,run:undefined});for(const spec of cases){try{const row=observe(env,spec);row.engine=name;data.rows.push(row);console.log(JSON.stringify({engine:name,...spec,result:row.result.victory,rounds:row.result.rounds,healing:row.metrics.healing,multiShield:row.metrics.multiAllyShieldPackets}));}catch(e){data.errors.push({engine:name,spec,error:e.stack});}}}
const failureCase=cases.find(x=>x.map==='MAP_MOND_WOLVENDOM'&&x.level===17&&x.seed===22);
for(const mode of ['OLD_SEQUENTIAL_SHIELDS','OLD_MELT_FREEZE','OLD_REACTION_SELECTION','OLD_ALL_THREE']){const env=load(root,mode);data.environments.push({name:mode,...env,R:undefined,db:undefined,c:undefined,fixture:undefined,run:undefined});try{const row=observe(env,failureCase);data.isolations.push(row);console.log(JSON.stringify({mode,result:row.result.victory,rounds:row.result.rounds,healing:row.metrics.healing,multiShield:row.metrics.multiAllyShieldPackets}));}catch(e){data.errors.push({mode,error:e.stack});}}
fs.writeFileSync(path.join(out,'native.json.gz'),zlib.gzipSync(JSON.stringify(data),{level:9}));const summaries={schemaVersion:1,environments:data.environments,errors:data.errors,rows:data.rows.map(({trace,finished,stalledBattle,...row})=>({...row,finalActors:finished?.actors,finalRound:finished?.round})),isolations:data.isolations.map(({trace,finished,stalledBattle,...row})=>({...row,finalActors:finished?.actors,finalRound:finished?.round})),nativeSha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(out,'native.json.gz'))).digest('hex')};fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(summaries,null,2)+'\n');console.log(JSON.stringify({done:true,rows:data.rows.length,isolations:data.isolations.length,errors:data.errors.length}));if(data.errors.length)process.exitCode=1;return data;}
if(require.main===module)main();module.exports={load,observe,cases,clock,main};
