'use strict';
// Diagnostic: native continuous EXP fights, HP/PRNG settlement, level-up healing,
// paid ascensions and actual MOVE -> lodging -> MOVE. Modelled 2x presentation
// is not wall-clock human/network time. Fixtures and analytic costs are explicit.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {setup,observe,heal,G,api,PLAYER}=require('./audit_balance_v01522.cjs');
const {policy,REFERENCE_TEAM}=require('./audit_balance_v0161.cjs');
const {payAscension}=require('./audit_growth_pacing_v0166.cjs');
const {c,root}=require('../tests/helpers_v011.cjs');
const PARTY=[PLAYER,...REFERENCE_TEAM],BOUNDARIES=[10,20,30,40,50,55,60],TARGET_MINUTES=[10,30,60,210,240,150,150];
const DEFAULT_OUT=path.join(root,'docs/data/growth_bands_v01615.json');
const cp=x=>JSON.parse(JSON.stringify(x));
function fingerprint(){const h=crypto.createHash('sha256');for(const f of fs.readdirSync(path.join(root,'source')).filter(x=>x.endsWith('.js')).sort()){h.update(f);h.update(fs.readFileSync(path.join(root,'source',f)));}return h.digest('hex');}
const hp=r=>PARTY.map(owner=>({owner,level:r.growth(owner).level,phase:r.growthPhase(owner),hp:owner===PLAYER?r.s.global.PLAYER_HP_CURRENT:r.s.chars[owner].hp,maxHp:owner===PLAYER?r.s.global.PLAYER_HP_MAX:r.character(owner).maxHp}));
const needRest=r=>hp(r).some(a=>a.hp<=0||a.hp/a.maxHp<.5);
function profile(level){return {gear:level<5?'starter':'craft',enhance:level<10?0:level<30?3:6,talent:'mid'};}
function attachTiming(r){const base=r.action;r._auditMeter={presentationMs:0,inputs:0};r.action=function(type,args){const before=c.CRPGPresentation.snapshot(this.s),out=base.call(this,type,args);for(const f of c.CRPGPresentation.actionFrames(c.CRPGPresentation.delta(before,this.s))){if(f.kind==='state'&&f.silent)continue;this._auditMeter.presentationMs+=f.kind==='action'?460+(f.attemptCount>1?520:650):1400;}if(type==='COMBAT')this._auditMeter.inputs++;return out;};return r;}
function fight(r,domain){const before=hp(r),levelBefore=r.growth(PLAYER).level,wallet=r.s.global.MORA;const m=r._auditMeter;m.presentationMs=0;m.inputs=0;r.action('DOMAIN_START',{domain});const result=policy(r),after=hp(r);return {domain,levelBefore,levelAfter:r.growth(PLAYER).level,phase:r.growthPhase(),victory:!!result.victory,rounds:result.rounds,experience:result.xp||0,mora:r.s.global.MORA-wallet,before,after,presentationMs:m.presentationMs,playerInputs:m.inputs,seconds:m.presentationMs/1000+3*m.inputs+6+Number(result.defeatPenalty?.seconds||0),defeatPenalty:cp(result.defeatPenalty||null)};}
function edgesFrom(r,map){return r.rows('47_MAP_EDGE_DB').filter(e=>e[1]===map&&e[8]==='Y'&&e[11]==='ACTIVE'&&(!e[6]||(e[6]==='FLAG_TRUE'&&[true,'TRUE'].includes(r.s.flags[e[7]]))));}
function shortest(r,from,to){const queue=[{map:from,edges:[]}],seen=new Set([from]);while(queue.length){const a=queue.shift();if(a.map===to)return a.edges;for(const e of edgesFrom(r,a.map)){if(seen.has(e[2]))continue;seen.add(e[2]);queue.push({map:e[2],edges:[...a.edges,e[0]]});}}return null;}
function innOptions(r){return r.placeCatalog().filter(p=>p.kind==='FACILITY').flatMap(p=>r.rows('19_SHOP_STOCK_DB').filter(s=>s[1]===p.merchant&&s[3]==='SERVICE_INN_REST_8H').flatMap(s=>p.maps.map(map=>({map,place:p.id,stock:s[0],stockRow:s}))));}
function nearestInn(r,from){return innOptions(r).map(i=>({...i,out:shortest(r,from,i.map),back:shortest(r,i.map,from)})).filter(i=>i.out&&i.back).sort((a,b)=>(a.out.length+a.back.length)-(b.out.length+b.back.length)||r.stockPrice(a.stockRow)-r.stockPrice(b.stockRow))[0];}
function travel(r,edges){const events=[];let seconds=0;for(const edge of edges){const from=r.s.global.CURRENT_MAP_ID;r.action('MOVE',{edge});seconds+=4;events.push({type:'MOVE',edge,from,to:r.s.global.CURRENT_MAP_ID});if(r.s.runtime){const m=r._auditMeter;m.presentationMs=0;m.inputs=0;const result=policy(r),battleSeconds=m.presentationMs/1000+3*m.inputs+6+Number(result.defeatPenalty?.seconds||0);seconds+=battleSeconds;events.push({type:'ENCOUNTER',victory:!!result.victory,xp:result.xp||0,mora:result.mora||0,seconds:battleSeconds});if(!result.victory)return {failed:true,seconds,events};}}return {failed:false,seconds,events};}
function recover(r){const start=r.s.global.CURRENT_MAP_ID,inn=nearestInn(r,start),before=hp(r),wallet=r.s.global.MORA;if(!inn)return {failed:true,reason:'NO_LEGAL_ROUNDTRIP_INN',before,seconds:0};const out=travel(r,inn.out);if(out.failed)return {...out,reason:'OUTWARD_ENCOUNTER_DEFEAT',before,after:hp(r)};r.action('PLACE_ENTER',{place:inn.place,mode:'SHOP'});const quote=r.innRecoveryQuote?r.innRecoveryQuote(inn.stockRow):{cost:Number(inn.stockRow[5])};const receipt=r.action('BUY',{stock:inn.stock,quantity:1});const recovered=hp(r);if(!recovered.every(a=>a.hp===a.maxHp))throw Error('Native lodging did not heal/revive every active target');const back=travel(r,inn.back);return {failed:back.failed,reason:back.failed?'RETURN_ENCOUNTER_DEFEAT':null,before,afterLodging:recovered,after:hp(r),inn:inn.map,stock:inn.stock,quote:cp(quote),lodgingCost:receipt.result.cost,legacyFixedLodgingCost:Number(inn.stockRow[5]),mora:r.s.global.MORA-wallet,seconds:out.seconds+10+back.seconds,movementFacilityInputs:inn.out.length+inn.back.length+2,events:[...out.events,{type:'PLACE_ENTER',place:inn.place},{type:'BUY',stock:inn.stock,cost:receipt.result.cost},...back.events]};}
function candidates(r){return Object.values(G.domains).filter(d=>d.kind==='EXP').flatMap(d=>r.growthDomainEntries(d.map).filter(x=>!x.reason));}
function sampleCandidates(r,{probeRuns=3,owner=PLAYER}={}){const save=cp(r.s),attempts=[];for(const domain of candidates(r)){r.s=cp(save);r.s.global.CURRENT_MAP_ID=domain.map;const runs=[],rests=[];let seconds=0,wins=0,xp=0,failed=false;for(let n=0;n<probeRuns;n++){if(needRest(r)){const rest=recover(r);rests.push(rest);seconds+=rest.seconds;if(rest.failed){failed=true;break;}}const row=fight(r,domain.id);runs.push(row);seconds+=row.seconds;if(!row.victory){failed=true;break;}wins++;xp+=row.experience;if(r.growth(owner).max)break;}attempts.push({domain:domain.id,map:domain.map,stage:domain.level,runs,wins,losses:runs.filter(x=>!x.victory).length,recoveries:rests,seconds,experience:xp,xpPerMinute:xp/(seconds/60),completed:!failed,finalLevel:r.growth().level,finalHp:hp(r)});}
 r.s=save;const ranked=attempts.filter(x=>x.completed&&x.wins>0).sort((a,b)=>b.xpPerMinute-a.xpPerMinute||b.stage-a.stage);return {level:r.growth(owner).level,protagonistLevel:r.growth(PLAYER).level,phase:r.growthPhase(owner),hpAtSelection:hp(r),probeRuns,attempts,best:ranked[0]?{domain:ranked[0].domain,map:ranked[0].map,stage:ranked[0].stage,xpPerMinute:ranked[0].xpPerMinute}:null};}
function legalTalents(r){for(const owner of PARTY){const cap=r.growth(owner).talentCap,t=Math.max(1,Math.floor(cap*.65));r.s.talents[owner]={na:t,e:t,q:t};}}
function milestoneGear(r,level){const p=profile(level);if(level===5){for(const inv of r.s.inventory.filter(x=>x.equipped))inv.equipped=false;}if(level===5||level===10){const template=setup({level,route:r.s.global.STORY_ROUTE_ID,team:REFERENCE_TEAM,...p});for(const inv of template.s.inventory.filter(x=>x.equipped)){if(r.s.inventory.some(x=>x.equipped&&x.owner===inv.owner&&x.equip===inv.equip))continue;const slot=r.giveEquipment(inv.equip);r.action('EQUIP',{slot,owner:inv.owner});}}for(const inv of r.s.inventory.filter(x=>x.equipped))inv.enhance=p.enhance;r.recalculate();return {level,...p,inventory:r.s.inventory.filter(x=>x.equipped).map(x=>({owner:x.owner,equip:x.equip,enhance:x.enhance}))};}
function trimDiagnosticHistory(r){if(r.s.log.length>30)r.s.log=r.s.log.slice(-30);const receipts=Object.entries(r.s.combatReceipts||{});if(receipts.length>30)r.s.combatReceipts=Object.fromEntries(receipts.slice(-30));}
function cultivation({route='ROUTE_TRAVELER',seed=717,from=1,to=60,probeRuns=3,owner=PLAYER,supportEnhance=6,cachedSelections=[],onProgress=()=>{},runLimit=5000}={}){
 const r=attachTiming(setup({level:owner===PLAYER?from:[60,from,60,60],route,team:REFERENCE_TEAM,...profile(from),saveId:'GROWTH-V01615-'+route+'-'+seed+'-'+from}));observe(r);Object.assign(r.tutorialState().done,{combatAttack:true,combatGuard:true,combatSkill:true,combatBurst:true});r.s.global.PRNG_STATE=seed;r.s.global.MORA=100000000;r.s.domainDaily={day:G.dayOf(r.leyLineNow()),wins:3};
 if(owner!==PLAYER||from>=50&&supportEnhance>6){for(const inv of r.s.inventory.filter(x=>x.equipped&&(owner===PLAYER||x.owner!==owner)))inv.enhance=supportEnhance;r.recalculate();heal(r);}
 const row={route,seed,from,to,owner,supportEnhance,profile:profile(from),sourceFingerprint:fingerprint(),initialHp:hp(r),mode:'native-continuous-campaign',startingMora:r.s.global.MORA,syntheticFunding:true,battles:[],recoveries:[],ascensions:[],gearMilestones:[],selections:[],bands:[],seconds:0,wins:0,losses:0,lodgingMora:0,phaseMora:0,probeBattleCount:0,diagnosticHistoryPruning:true};let selectedLevel=-1,choice=null,bandFrom=from,lastSeconds=0,lastWins=0,lastRest=0,lastPhaseMora=0,lastLodging=0;const pending=BOUNDARIES.filter(l=>l>from&&l<=to);
 for(let n=0;n<runLimit&&r.growth(owner).level<to;n++){
  const g=r.growth(owner);if(g.max&&!g.final){for(const target of owner===PLAYER?PARTY:[owner]){const x=r.growth(target);if(x.max&&!x.final){const paid=payAscension(r,target);row.ascensions.push(paid);row.phaseMora+=paid.paid.mora;}}legalTalents(r);selectedLevel=-1;}
  const level=r.growth(owner).level;if(owner===PLAYER&&[5,10,30,50].includes(level)&&!row.gearMilestones.some(x=>x.level===level)){const milestone=milestoneGear(r,level);if(level>=50&&supportEnhance>6){for(const inv of r.s.inventory.filter(x=>x.equipped))inv.enhance=supportEnhance;r.recalculate();milestone.enhance=supportEnhance;}row.gearMilestones.push(milestone);}
  if(selectedLevel!==level){const prior=cachedSelections.find(s=>s.level===level);const sample=prior?{level,phase:r.growthPhase(owner),hpAtSelection:hp(r),probeRuns:prior.probeRuns,selectionReuse:true,best:cp(prior.best),attempts:prior.attempts.map(a=>({domain:a.domain,map:a.map,stage:a.stage,wins:a.wins,losses:a.losses,seconds:a.seconds,experience:a.experience,xpPerMinute:a.xpPerMinute,completed:a.completed,recoveries:a.recoveries.map(q=>({failed:q.failed,seconds:q.seconds,lodgingCost:q.lodgingCost})),runs:[],finalLevel:a.finalLevel}))}:sampleCandidates(r,{probeRuns,owner});row.selections.push(sample);row.probeBattleCount+=sample.attempts.reduce((n,x)=>n+x.runs.length,0);choice=sample.best;selectedLevel=level;if(!choice){row.stopReason='NO_SUSTAINABLE_STAGE';break;}}
  if(r.s.global.CURRENT_MAP_ID!==choice.map){const edges=shortest(r,r.s.global.CURRENT_MAP_ID,choice.map);if(!edges){row.stopReason='NO_STAGE_ROUTE';break;}const t=travel(r,edges);row.seconds+=t.seconds;row.stageTransfers??=[];row.stageTransfers.push(t);if(t.failed){row.stopReason='STAGE_TRANSFER_DEFEAT';row.losses++;break;}}
  if(needRest(r)){const recovery=recover(r);row.recoveries.push(recovery);row.seconds+=recovery.seconds;row.lodgingMora+=recovery.lodgingCost||0;if(recovery.failed){row.stopReason=recovery.reason;row.losses++;break;}}
  const battle=fight(r,choice.domain);row.battles.push(battle);row.seconds+=battle.seconds;row.wins+=battle.victory?1:0;row.losses+=battle.victory?0:1;
  if(!battle.victory){row.stopReason='COMBAT_DEFEAT';break;}
  while(pending.length&&r.growth(owner).level>=pending[0]){const bandTo=pending.shift();row.bands.push({from:bandFrom,to:bandTo,wins:row.wins-lastWins,seconds:row.seconds-lastSeconds,lodgingCount:row.recoveries.length-lastRest,lodgingMora:row.lodgingMora-lastLodging,ascensionMora:row.phaseMora-lastPhaseMora});bandFrom=bandTo;lastWins=row.wins;lastSeconds=row.seconds;lastRest=row.recoveries.length;lastPhaseMora=row.phaseMora;lastLodging=row.lodgingMora;}
  row.finalHp=hp(r);row.finalMora=r.s.global.MORA;trimDiagnosticHistory(r);onProgress(row);
 }
 row.stopReason??=r.growth(owner).level>=to?'TARGET_REACHED':'RUN_LIMIT';row.finalHp=hp(r);row.finalMora=r.s.global.MORA;row.actualTargetCompleted=row.stopReason==='TARGET_REACHED';return row;
}
function analyticCosts(){const r=setup({level:60}),cfg=api.enhancementConfig;function expected(target){const delta=[0];let cost=0;for(let l=0;l<target;l++){const t=l+1,p=cfg.success[t]/10000,d=cfg.down[t]/10000;delta[t]=(cfg.mora[t]+d*delta[l])/p;cost+=delta[t];}return cost;}const levels=[1,10,20,30,40,50,55,60],rows=[];for(const id of [PLAYER,'MOND_AMBER','LIYUE_XIANGLING','MOND_DILUC'])for(let i=0;i<levels.length-1;i++){const from=levels[i],to=levels[i+1],phase=G.phaseFor(from);r.s.ascensions[id]=phase;if(id===PLAYER)r.s.global.PLAYER_LEVEL_STATE=from;else r.s.chars[id].level=from;const asc=r.ascensionInfo(id);let xp=0;for(let l=from;l<to;l++)xp+=G.xpNext(l);const talentFrom=Math.max(1,Math.floor(G.talentCaps[phase]*.65)),nextPhase=from===1?phase:phase+1,talentTo=Math.max(1,Math.floor(G.talentCaps[nextPhase]*.65));let talentMora=0,talentItems={};for(let t=talentFrom;t<talentTo;t++){r.s.talents[id]={na:t,e:t,q:t};r.s.ascensions[id]=nextPhase;for(const kind of ['na','e','q']){const q=r.talentUpgradeInfo(id,kind).cost;talentMora+=q.mora;for(const [item,n]of Object.entries(q.items))talentItems[item]=(talentItems[item]||0)+n;}}const previousEnhance=from<=10?0:from<=30?3:6,nextEnhance=from<10?0:from<30?3:6;rows.push({owner:id,rarity:id===PLAYER?0:r.rarityOf(id),from,to,requiredXp:xp,heroBooks:Math.ceil(xp/1000),ascensionMora:from===1?0:asc.cost.mora,ascensionMaterials:from===1?{}:asc.cost.items,talentFrom,talentTo,talentMora,talentItems,gear3ExpectedMoraIncrement:3*Math.max(0,expected(nextEnhance)-expected(previousEnhance))});}
 const leyTiers=api.leyLines.tiers.map(t=>({...t,bookXp:Object.entries(t.books).reduce((n,[id,q])=>n+q*api.leyLines.bookXp[id],0)}));return {rows,gear3ExpectedMoraByEnhance:Object.fromEntries([0,3,6,10,12].map(l=>[l,3*expected(l)])),leyTiers,leyLimit:'One claimed reward per kind per real-time hour shared across regions; party recipients spend books separately; never compare 4-member direct XP to one-owner books without multiplying demand.',levelTargets:levels.slice(0,-1).map((from,i)=>({from,to:levels[i+1],targetMinutes:TARGET_MINUTES[i]}))};}
function main(){const opt=n=>{const i=process.argv.indexOf(n);return i<0?undefined:process.argv[i+1];},out=opt('--out')||DEFAULT_OUT;const routes=(opt('--routes')||'ROUTE_TRAVELER,ROUTE_ISEKAI').split(','),seeds=(opt('--seeds')||'717').split(',').map(Number),from=Number(opt('--from')||1),to=Number(opt('--to')||60),probeRuns=Number(opt('--probe-runs')||3),owner=opt('--owner')||PLAYER,supportEnhance=Number(opt('--support-enhance')||6),priorFile=opt('--verify-replay'),priorData=priorFile?JSON.parse(fs.readFileSync(priorFile)):null;const data={version:require('../package.json').version,sourceFingerprint:fingerprint(),timing:{displaySpeed:2,internalSpeed:1,presentationDivisor:1000,inputSeconds:3,reentrySeconds:6,silentFramesExcluded:true,travelSecondsPerMove:4,facilityEntrySeconds:4,lodgingSeconds:6},assumptions:{party:PARTY,oneInitialFullHp:true,noBetweenBattleArtificialHeal:true,prngSeedOncePerCampaign:true,nativeLevelUpHeal:true,nativePhaseHeal:true,recoveryAt:'Any dead target or HP under 50%',selection:'All unlocked stages probed from the same saved HP/PRNG, continuous native short campaigns; failures retained; actual campaign chooses fastest successful probe and carries native HP/PRNG.',probeRuns,gearMilestones:'Starter +0 through Lv.4; crafted +0 at Lv.5; +3 at Lv.10; +6 at Lv.30 and afterward.',synthetic:['Ownership and story gates','Initial money budget for recording native costs, not an earned-income claim','Legal equipment/talents at stated milestones','Exact materials and money for native paid ascensions; not material-farming time'],excluded:['Human and network latency','Story time','Craft/ore/ascension/talent material farming','Cost of raw crafting ingredients, market prices','Quest Mora income'],diagnosticHistory:'Keeps the most recent 30 logs and battle receipts in VM to bound diagnostic clone cost; action sequence and actual growth/inventory/HP/PRNG preserved.'},costs:analyticCosts(),campaigns:[]};if(opt('--append')&&fs.existsSync(out)){const old=JSON.parse(fs.readFileSync(out));data.campaigns=old.campaigns||[];}
 fs.mkdirSync(path.dirname(out),{recursive:true});const save=()=>fs.writeFileSync(out,JSON.stringify(data,null,2)+'\n');save();if(!process.argv.includes('--costs-only'))for(const route of routes)for(const seed of seeds){data.campaigns=data.campaigns.filter(x=>!(x.route===route&&x.seed===seed&&x.from===from&&x.to===to&&(x.owner||PLAYER)===owner&&x.supportEnhance===supportEnhance));let current;const row=cultivation({route,seed,from,to,probeRuns,owner,supportEnhance,cachedSelections:priorData?.campaigns.find(x=>x.route===route&&x.seed===seed&&x.from===from&&x.to===to)?.selections||[],onProgress:r=>{if(!current){current=r;data.campaigns.push(current);}if(r.battles.length%100===0){save();console.log(JSON.stringify({route,seed,level:r.finalHp.find(a=>a.owner===owner).level,wins:r.wins,seconds:r.seconds,rests:r.recoveries.length}));}}});if(!current)data.campaigns.push(row);if(priorData){const prior=priorData.campaigns.find(x=>x.route===route&&x.seed===seed&&x.from===from&&x.to===to);if(!prior)throw Error('Missing prior campaign');const allowQuoteAdjustment=process.argv.includes('--allow-quote-adjustment'),exact=['wins','losses','seconds','phaseMora','stopReason','finalHp',...(allowQuoteAdjustment?[]:['lodgingMora'])];for(const key of exact)if(JSON.stringify(row[key])!==JSON.stringify(prior[key]))throw Error('Final source native replay differs: '+route+' '+key);row.finalSourceVerification={comparedToSourceFingerprint:prior.sourceFingerprint,exact,priorVersion:priorData.version,currentVersion:data.version,fullNativeReplay:true,selectionProbesReused:true,...(allowQuoteAdjustment?{lodgingQuoteCorrection:{prior:prior.lodgingMora,current:row.lodgingMora,delta:row.lodgingMora-prior.lodgingMora,reason:'Native inn quote now rounds the integer lost-HP numerator; other campaign outcomes must match exactly.'}}:{})};}save();console.log(JSON.stringify({route,seed,from,to,stop:row.stopReason,bands:row.bands,wins:row.wins,seconds:row.seconds,rests:row.recoveries.length}));}data.version=require('../package.json').version;data.finishedSourceFingerprint=fingerprint();data.sourceStayedUnchanged=data.finishedSourceFingerprint===data.sourceFingerprint;save();}
if(require.main===module)main();
function compactCampaign(row){
 const owner=row.owner||PLAYER,byLevel=new Map();
 for(const battle of row.battles){const before=battle.before.find(a=>a.owner===owner),after=battle.after.find(a=>a.owner===owner),level=before.level;
  if(!byLevel.has(level))byLevel.set(level,{level,wins:0,losses:0,seconds:0,awardedXpPerParticipant:0,domains:{},nativeLevelUps:0,minimumTargetHpRatio:1});
  const out=byLevel.get(level);out.wins+=battle.victory?1:0;out.losses+=battle.victory?0:1;out.seconds+=battle.seconds;out.awardedXpPerParticipant+=battle.experience;out.domains[battle.domain]=(out.domains[battle.domain]||0)+1;out.nativeLevelUps+=Math.max(0,after.level-before.level);out.minimumTargetHpRatio=Math.min(out.minimumTargetHpRatio,after.hp/after.maxHp);
 }
 const {battles,recoveries,selections,stageTransfers,...base}=row;
 const samples=[...new Set([0,recoveries.length-1,recoveries.reduce((best,q,i)=>q.lodgingCost>(recoveries[best]?.lodgingCost??-1)?i:best,0)])].filter(i=>recoveries[i]);
 return {...base,battleCount:battles.length,battlesByLevel:[...byLevel.values()],recoveries:recoveries.map(q=>({failed:q.failed,stock:q.stock,lodgingCost:q.lodgingCost,seconds:q.seconds})),nativeInnQuoteSamples:samples.map(i=>({recoveryIndex:i,inn:recoveries[i].inn,stock:recoveries[i].stock,lodgingCost:recoveries[i].lodgingCost,seconds:recoveries[i].seconds,quote:recoveries[i].quote,travelEncounters:recoveries[i].events?.filter(e=>e.type==='ENCOUNTER')||[]})),selections:selections.map(s=>({level:s.level,phase:s.phase,probeRuns:s.probeRuns,selectionReuse:!!s.selectionReuse,best:s.best,candidateCount:s.attempts.length,candidateDetail:'Selected and unsuccessful probes in summary; complete candidate metrics in the compressed native trace.',attempts:s.attempts.filter(a=>a.domain===s.best?.domain||!a.completed).map(a=>({domain:a.domain,map:a.map,stage:a.stage,wins:a.wins,losses:a.losses,seconds:a.seconds,experience:a.experience,xpPerMinute:a.xpPerMinute,completed:a.completed,probeBattleCount:a.runs?.length||0,recoveryCount:a.recoveries?.length||0,recoveries:[],runs:[]}))})),stageTransferCount:stageTransfers?.length||0};
}
function compactData(data){
 const out={...data,campaigns:data.campaigns.map(compactCampaign)};
 if(data.catchup)out.catchup={...data.catchup,campaigns:data.catchup.campaigns.map(compactCampaign)};
 if(data.supplementalLate10)out.supplementalLate10={...data.supplementalLate10,campaigns:data.supplementalLate10.campaigns.map(compactCampaign)};
 return out;
}
module.exports={cultivation,analyticCosts,sampleCandidates,recover,travel,shortest,hp,profile,compactCampaign,compactData,DEFAULT_OUT};
