'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=(process.env.CRPG_AUDIT_ROOT || require('node:path').resolve(__dirname,'..'));
const H=require('./audit_healing_helpers_v01619.cjs');
const cp=x=>JSON.parse(JSON.stringify(x)),env=H.load(root,JSON.parse(process.env.CRPG_HEALER_CANDIDATE||'null')),seeds=[717,925],levels=[10,30,50,60],runs=8;
const recoveryPolicies=process.argv.includes('--quick')?['REST_BELOW_HALF']:['NO_INTERMEDIATE_RECOVERY','REST_BELOW_HALF'];
const supports={Barbara:'MOND_BARBARA',Jean:'MOND_JEAN',Sucrose:'MOND_SUCROSE'};
const domainKeys={10:{TALENT:'FORSAKEN_RIFT',ASCENSION:'VALLEY_OF_REMEMBRANCE',EXP:'MIDSUMMER_COURTYARD'},30:{TALENT:'TAISHAN_MANSION',ASCENSION:'LIANSHAN_FORMULA',EXP:'RIDGE_WATCH'},50:{TALENT:'TAISHAN_MANSION',ASCENSION:'LIANSHAN_FORMULA',EXP:'DOMAIN_OF_GUYUN'},60:{TALENT:'TAISHAN_MANSION',ASCENSION:'LIANSHAN_FORMULA',EXP:'LOST_VALLEY'}};
const opt=k=>{const i=process.argv.indexOf(k);return i<0?null:process.argv[i+1];};
const outfile=opt('--out')||'/tmp/crpg_reaction_plan/healer_v01619/results.json';
const data={variant:process.env.CRPG_AUDIT_LABEL||env.candidate?.name||'CURRENT_NATIVE',auditInstrumentation:'Base heal VM-only callback observes amount after native talent/rhythm/formation/gear before bond and missing HP cap; no numeric formula mutation.',fingerprint:env.fingerprint,candidate:env.candidate,substitutions:env.substitutions,root,assumptions:{fixture:'Traveler + Xiangling + Fischl + Barbara/Jean/Sucrose, all initially same declared level; legal current ascension phase, talents at floor(65% of legal cap), forge weapon/reinforced leather/healer brooch enhancement from the authoritative case rows (+3 at Lv10/15/20/25 and +6 at Lv30/40/50/60 in the final 144 cases). No constellations/artifacts. Ownership/progression/starter funds diagnostic only.',native:'Native public DOMAIN_START, COMBAT, MOVE, PLACE_ENTER, BUY. Auditor does not change product enemy/damage/healing/RNG/cooldown/talent/recovery formulas; candidate substitutions only when explicitly supplied. Persistent HP, XP, PRNG; one full-HP initialization only.',recovery:'Two explicit policies: NO_INTERMEDIATE_RECOVERY runs until eight fights or wipe with no inn between fights; REST_BELOW_HALF uses native roundtrip inn if any active member is dead/below 50%, including travel encounters. Only end-of-campaign missing HP triggers travel to nearest legal inn and BUY, stopping there. Defeat action lock can block this final recovery and is recorded as a separate failure.',time:'Native presentation frames counted with displayed 2x internal rate 1: ms/1000 + 3sec/player COMBAT + 6sec receipt/reentry; native MOVE 4sec, inn 10sec. Human/network acquisition time excluded.',healing:'Effective healing measured by authoritative Runtime.heal return; source requests before receiver/formation/skill/talent multipliers logged separately. Zero effective calls are counted, but raw request totals are not asserted as final overheal.',limits:'Casefile defines exact levels, legal domain keys, talents, enhancement and seeds; the final fixture has eight levels, three domain kinds, two seeds and eight planned wins/campaign; fixture is representative, not all possible gear/compositions. Own skills chosen Q then hold E then basic, allies native balanced AI.'},rows:[],errors:[]};
function measure(r){const m=H.observe(env,r),events=[];let nominal=null;r._auditHealNominal=function(a,n,source){nominal={target:a.source,source,amount:Number(n),roundedBeforeBondAndMissingHp:Math.max(0,Math.round(n))};};const heal=r.heal;r.heal=function(a,n,source,...rest){const before=a.hp;nominal=null;const out=heal.call(this,a,n,source,...rest);events.push({source,target:a.source,round:this.s.runtime?.round,targetSide:a.side,requestedBeforeModifiers:Number(n),requestedAfterNativeModifiers:nominal?.amount??null,nominalRoundedBeforeBondAndMissingHp:nominal?.roundedBeforeBondAndMissingHp??null,before,after:a.hp,maxHp:a.maxHp,effective:Number(out)||0});return out;};let loss=0,ko=0;const damage=r.applyDamage;r.applyDamage=function(a,t,n,o){const before=t.hp,out=damage.call(this,a,t,n,o);if(t.side==='ALLY'){loss+=Math.max(0,before-t.hp);if(before>0&&t.hp<=0)ko++;}return out;};return{m,events,loss:()=>loss,ko:()=>ko};}
function totalHp(list){return list.reduce((s,a)=>s+a.hp,0)/list.reduce((s,a)=>s+a.maxHp,0);}
function run(spec){const domain=spec.key+':'+spec.level,r=H.setup(env,{level:spec.level,team:['LIYUE_XIANGLING','MOND_FISCHL',supports[spec.support]],route:'ROUTE_TRAVELER',seed:spec.seed,enhance:spec.enhance,talent:spec.talent,map:env.api.growthV01522.domains[spec.key].map}),meter=measure(r);
 const out={...spec,candidate:process.env.CRPG_AUDIT_LABEL||env.candidate?.name||'CURRENT_NATIVE',domain,element:'NEUTRAL',initialHp:H.hp(r),talents:cp(r.s.talents),equipment:cp(r.s.inventory.filter(i=>i.equipped).map(i=>({owner:i.owner,equip:i.equip,enhance:i.enhance}))),battles:[],recoveries:[],wins:0,losses:0,mainSeconds:0,recoverySeconds:0,lodgingMora:0};
 for(let i=0;i<runs;i++){if(spec.recoveryPolicy==='REST_BELOW_HALF'&&H.hp(r).some(a=>a.hp<=0||a.hp/a.maxHp<.5)){const rec=H.recover(env,r);out.recoveries.push({...rec,afterMainFights:i,final:false});out.recoverySeconds+=rec.seconds||0;out.lodgingMora+=rec.lodgingMora||0;if(rec.failed){out.stopReason=rec.reason;break;}}
  const before=H.hp(r),prior={...meter.m},priorHeal=meter.events.length,priorLoss=meter.loss(),priorKo=meter.ko();r.action('DOMAIN_START',{domain,element:'NEUTRAL'});
  const initial=cp(r.s.runtime.actors.map(a=>({source:a.source,side:a.side,level:a.level,hp:a.hp,maxHp:a.maxHp,atk:a.atk,def:a.def,cooldowns:cp(a.cooldowns||{}),statuses:cp(a.statuses||[])}))),entryFields=cp(r.s.runtime.fields),reward=H.play(r),last=r._auditLast;
  const seconds=(meter.m.ms-prior.ms)/1000+3*(meter.m.inputs-prior.inputs)+6+Number(reward.defeatPenalty?.seconds||0),heals=meter.events.slice(priorHeal).filter(e=>e.targetSide==='ALLY');
  const row={number:i+1,before,after:H.hp(r),initial,entryFields,win:!!reward.victory,rounds:reward.rounds,seconds,playerActions:meter.m.inputs-prior.inputs,ownDamage:meter.m.ownDamage-prior.ownDamage,allyDamage:meter.m.allyDamage-prior.allyDamage,effectiveHealing:heals.reduce((s,e)=>s+e.effective,0),zeroEffectiveHealCalls:heals.filter(e=>!e.effective).length,healCalls:heals.length,heals,allyHpDamage:meter.loss()-priorLoss,koEvents:meter.ko()-priorKo,beforeReward:last?.actors.filter(a=>a.side==='ALLY').map(a=>({owner:a.source,level:a.level,hp:a.hp,maxHp:a.maxHp,cooldowns:cp(a.cooldowns||{}),statuses:cp(a.statuses||[])})),healingBeforeReward:(last?.log||[]).filter(e=>Object.hasOwn(e,'heal')&&last.actors.some(a=>a.side==='ALLY'&&a.name===e.target)).reduce((s,e)=>s+e.heal,0),cards:last?.log.filter(e=>e.card&&e.actor).map(e=>({actor:e.actor,card:e.card,round:e.round})),defeatPenalty:reward.defeatPenalty||null};
  row.rewardHpDelta=row.after.map(a=>{const b=row.beforeReward?.find(v=>v.owner===a.owner);return{owner:a.owner,levelBefore:b?.level,levelAfter:a.level,hpBefore:b?.hp,hpAfter:a.hp,delta:b?a.hp-b.hp:null,maxHpBefore:b?.maxHp,maxHpAfter:a.maxHp};});out.battles.push(row);out.mainSeconds+=seconds;out.wins+=row.win?1:0;out.losses+=row.win?0:1;if(!row.win){out.stopReason='DEFEAT';break;}if(r.s.log.length>30)r.s.log=r.s.log.slice(-30);
 }
 out.afterMainHp=H.hp(r);out.afterMainHpRatio=totalHp(out.afterMainHp);out.mainRounds=out.battles.reduce((s,b)=>s+b.rounds,0);out.mainActions=out.battles.reduce((s,b)=>s+b.playerActions,0);out.mainEffectiveHealing=out.battles.reduce((s,b)=>s+b.effectiveHealing,0);out.mainAllyHpDamage=out.battles.reduce((s,b)=>s+b.allyHpDamage,0);out.mainKoEvents=out.battles.reduce((s,b)=>s+b.koEvents,0);out.mainZeroHealCalls=out.battles.reduce((s,b)=>s+b.zeroEffectiveHealCalls,0);out.intermediateInnCount=out.recoveries.filter(x=>!x.final).length;out.firstInnAfterFights=out.recoveries.find(x=>!x.final)?.afterMainFights??null;
 if(out.afterMainHp.some(a=>a.hp<a.maxHp)){try{const rec=H.recover(env,r,{finishAtInn:true});out.recoveries.push({...rec,afterMainFights:out.battles.length,final:true});out.recoverySeconds+=rec.seconds||0;out.lodgingMora+=rec.lodgingMora||0;out.endpoint=rec.endpoint;if(rec.failed)out.finalRecoveryFailure=rec.reason;}catch(e){out.finalRecoveryFailure={code:e.code||e.name,message:e.message};out.endpoint={map:r.s.global.CURRENT_MAP_ID,allFullHp:false,blocked:true};}}else out.endpoint={map:r.s.global.CURRENT_MAP_ID,allFullHp:true,finalInnNeeded:false};
 out.finalHp=H.hp(r);out.totalSeconds=out.mainSeconds+out.recoverySeconds;out.stopReason??='RUNS_COMPLETED';return out;}
let cases=[];for(const level of levels)for(const [kind,key]of Object.entries(domainKeys[level]))for(const support of Object.keys(supports))for(const seed of seeds)for(const recoveryPolicy of recoveryPolicies)cases.push({level,kind,key,support,seed,recoveryPolicy});
if(opt('--casesfile'))cases=JSON.parse(fs.readFileSync(opt('--casesfile')));
if(process.argv.includes('--quick'))cases=cases.filter(x=>x.level===30&&x.kind==='TALENT'&&x.seed===717);
if(process.argv.includes('--repair-errors')){const prior=JSON.parse(fs.readFileSync('/tmp/crpg_healer_audit/repeat/results.json'));cases=prior.errors.map(({error,...spec})=>spec);data.rows=prior.rows;data.repairedOriginalErrors=prior.errors;}
for(const spec of cases){try{const row=run(spec);data.rows.push(row);console.log(JSON.stringify({level:spec.level,kind:spec.kind,support:spec.support,seed:spec.seed,recoveryPolicy:spec.recoveryPolicy,wins:row.wins,losses:row.losses,rounds:row.mainRounds,seconds:+row.mainSeconds.toFixed(1),endHp:+row.afterMainHpRatio.toFixed(4),intermediateInn:row.intermediateInnCount,mora:row.lodgingMora,heals:row.mainEffectiveHealing,damage:row.mainAllyHpDamage,ko:row.mainKoEvents}));}catch(e){data.errors.push({...spec,error:e.stack});console.log(JSON.stringify({...spec,error:e.message}));}fs.writeFileSync(outfile,JSON.stringify(data,null,2)+'\n');}
