'use strict';
// Legal public blossom entries and native combat, one declared seeded matchup
// per tier/region/kind/team. Initial ownership and full HP are explicit fixtures.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),zlib=require('node:zlib');
const H=require('./audit_healing_helpers_v01619.cjs'),ROOT=path.resolve(__dirname,'..'),args=process.argv.slice(2),arg=k=>args.includes(k)?args[args.indexOf(k)+1]:null,env=H.load(arg('--source-root')||ROOT),out=path.resolve(arg('--out')||path.join(ROOT,'docs/data/full_balance_v01621/economy/leyline_native.json'));
const rows=[],errors=[],teams={story4:['MOND_AMBER','MOND_KAEYA','MOND_LISA'],healer4:['MOND_KAEYA','LIYUE_XINGQIU','MOND_BARBARA']};
function save(){fs.mkdirSync(path.dirname(out),{recursive:true});const result={schema:1,sourceRoot:env.root,sourceFingerprint:env.fingerprint,assumptions:{party:'Four declared owned members; C0, native legal per-level equipment/phase/mid talents; one initial funded wallet and full HP per condition.',actions:'Native PLACE_ENTER/BOSS_ROUTE/COMBAT. No enemy stat, damage, heal, RNG or reward override. Native loss is a loss, not an audit failure.',timing:'Actual displayed2x schedule: presentationMs/1000 +3seconds per player combat input +6seconds settlement/reentry. Already-at-blossom fixture excludes acquisition/travel and final recovery. It is not a continuous hourly farming campaign.',clock:'Real action-start hour; each kind has one cross-region payout per hour, not two regional quotas.',limits:'One seed717 and two4starC0 compositions per matchup; no actual user-save or complete roster claim.'},rows,errors,counts:{conditions:rows.length,wins:rows.filter(x=>x.result.victory).length,losses:rows.filter(x=>!x.result.victory).length,errors:errors.length}};const raw=Buffer.from(JSON.stringify(result,null,2)+'\n');fs.writeFileSync(out,raw);fs.writeFileSync(out+'.gz',zlib.gzipSync(raw,{level:9}));}
for(const tier of env.api.leyLines.tiers)for(const region of ['몬드','리월'])for(const kind of ['WEALTH','REVELATION'])for(const[team,members]of Object.entries(teams)){
 try{const r=H.setup(env,{level:tier.level,team:members,route:'ROUTE_TRAVELER',seed:717});const blossom=r.leyLineStatus().blossoms.find(x=>x.region===region&&x.kind===kind);assert(blossom);r.s.global.CURRENT_MAP_ID=blossom.map;r.s.placeVisit=null;r.action('PLACE_ENTER',{place:'BOSS:'+blossom.route,mode:'BOSS'});const money=r.s.global.MORA,books=r.itemCount('MAT_CHAR_EXP_HERO'),meter=H.observe(env,r);r.action('BOSS_ROUTE',{route:blossom.route,entry:'DIRECT',tier:tier.tier});const enemies=JSON.parse(JSON.stringify(r.s.runtime.actors.filter(x=>x.side==='ENEMY'))),result=H.play(r);assert(!result.stalled,'native combat must settle');const mora=r.s.global.MORA-money,heroBooks=r.itemCount('MAT_CHAR_EXP_HERO')-books;if(result.victory){assert.equal(mora,kind==='WEALTH'?tier.mora:0);assert.equal(heroBooks,kind==='REVELATION'?tier.books.MAT_CHAR_EXP_HERO:0);assert.equal(result.xp,tier.directXp);assert(r.leyLineClaimed(kind));}const seconds=meter.ms/1000+meter.inputs*3+6;rows.push({tier:tier.tier,level:tier.level,region,kind,team,enemies,result,seconds,mora,heroBooks,bookXp:heroBooks*1000,directXpEach:result.xp||0,hpAfter:H.hp(r),nominalFullPartyHeal:meter.heal,oncePerHourReason:r.actionReason('BOSS_ROUTE',{route:blossom.route,entry:'DIRECT',tier:tier.tier})});console.log(JSON.stringify({tier:tier.tier,region,kind,team,victory:result.victory,seconds,mora,heroBooks}));}
 catch(e){errors.push({tier:tier.tier,region,kind,team,code:e.code||e.name,message:e.message});console.error(JSON.stringify(errors.at(-1)));}save();
}
assert.equal(errors.length,0,'inspect recorded native audit errors');
