"use strict";
// Native public pricing/receipts and independent absorbing-state cost calculation.
// Diagnostic previous +10 ownership/funding is explicit. No RNG/payment/action override.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),zlib=require('node:zlib');
const H=require('./audit_protagonist_v01618.cjs');
const args=process.argv.slice(2),arg=k=>args.includes(k)?args[args.indexOf(k)+1]:undefined;
const root=path.resolve(arg('--root')||path.resolve(__dirname,'..')),beforeRoot=arg('--before-root')?path.resolve(arg('--before-root')):null,out=path.resolve(arg('--out-dir')||path.join(root,'docs/data/balance_v01627/enhancement_price_revision'));
const cp=x=>JSON.parse(JSON.stringify(x)),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const before=beforeRoot?H.load(beforeRoot):require('../tests/test_enemy_balance_v01627.cjs').loadBefore(root),current=H.load(root);assert.equal(before.fingerprint,'b69a8b91e0d0df86e2e9adc4edf1ab0493e0ff26354c7a3e026b1884ae7b9159','exact genuine published 0.16.26 runtime');assert.equal(sha(fs.readFileSync(path.join(root,'content/db.json'))),'dcc2800000f20684e2c57420404aa3a3a7fe68b9042c608306ba2ec62bd178da','authored DB unchanged');const NativeDate=Date,NOW=1791615600000,FixedDate=class extends NativeDate{constructor(...args){super(...(args.length?args:[NOW]));}static now(){return NOW;}};
for(const e of [before,current]){e.c.Date=FixedDate;const rel=e.c.CRPGRelationships;if(!e.R.prototype.__relationshipsInstalled)rel.install(e.api,{events:rel.catalogFromDB(e.db),activities:rel.activitiesFromDB(e.db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});}
const OLD={mora:[22400,40000],ores:[{ORE_WHITE_IRON:64,ORE_CRYSTAL:40},{ORE_WHITE_IRON:100,ORE_CRYSTAL:80}]},NEW={mora:[14000,18000],ores:[{ORE_WHITE_IRON:40,ORE_CRYSTAL:28},{ORE_WHITE_IRON:48,ORE_CRYSTAL:36}]};
const data={schema:1,root,beforeRoot,currentFingerprint:current.fingerprint,beforeFingerprint:before.fingerprint,dbSha256:sha(fs.readFileSync(path.join(root,'content/db.json'))),sourceSha256:sha(fs.readFileSync(path.join(root,'source/runtime_enhancement.js'))),beforeSourceSha256:sha(fs.readFileSync(beforeRoot?path.join(beforeRoot,'source/runtime_enhancement.js'):path.join(root,'docs/data/balance_v01627/before/source/runtime_enhancement.js'))),assumptions:{preparation:'Owned previous+10 Rancour, Lv60 legal Traveler, diagnostic funding of20millionMora and100000 units each ore/boss item. Public EQUIP, PLACE_ENTER, EQUIP_ASCEND, ENHANCE; initial PRNGseed explicit; no roll, dice, probability, payment, stat, action validation override. Immutable genuine0.16.26 source loaded separately.',scope:'Only target11/12 Mora/whiteiron/crystal prices change. No stat gain, success/hold/down, cap, ascension, equipment gain eligibility, recipes, boss loot or admission changes. Actual attempts compare same seeded actions; expected resources from full Markov model, not samplemean.',time:'Game minutes per action preserved; no natural acquisition/fullcharacter progression or player-market price forecast claimed.'},configuration:{before:cp(before.api.enhancementConfig),current:cp(current.api.enhancementConfig)},checks:[],equipmentComparisons:[],costPaths:[],nativeSamples:[],boundarySamples:[],marketComparisons:[]};
function check(name,fn){const evidence=fn();data.checks.push({name,ok:true,evidence});console.log('PASS '+name);}
function save(){fs.mkdirSync(out,{recursive:true});const raw=Buffer.from(JSON.stringify(data,null,2)+'\n'),gz=zlib.gzipSync(raw,{level:9});fs.writeFileSync(path.join(out,'native.json.gz'),gz);fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({schema:1,currentFingerprint:data.currentFingerprint,beforeFingerprint:data.beforeFingerprint,dbSha256:data.dbSha256,sourceSha256:data.sourceSha256,beforeSourceSha256:data.beforeSourceSha256,toolSha256:sha(fs.readFileSync(__filename)),raw:'native.json.gz',uncompressedSha256:sha(raw),gzipSha256:sha(gz),checks:data.checks.length,nativeSamples:data.nativeSamples.length},null,2)+'\n');}
function stats(r){const p=r.player();return {hp:p.hp,maxHp:p.maxHp,atk:p.atk,def:p.def,crit:p.crit,critDmg:p.critDmg,spd:p.spd,hit:p.hit,eva:p.eva,equipment:cp(r.equipmentStats('PLAYER_CUSTOM')),traits:cp(r.actorTraits('PLAYER_CUSTOM'))};}
function funds(r){return {mora:r.s.global.MORA,items:Object.fromEntries(['ORE_IRON','ORE_WHITE_IRON','ORE_CRYSTAL','TRPG_BOSS_ESSENCE','TRPG_BOSS_CORE'].map(id=>[id,r.itemCount(id)]))};}
function intent(r,type,params){return {id:r.s.global.SAVE_ID+':'+(r.s.global.LAST_COMMITTED_ACTION_SEQ+1),revision:r.s.global.SAVE_REVISION,type,...params};}
function argsFrom(r,slot,kind){const q=r.enhancementQuote(slot,kind);return {slot,expectedLevel:q.level,expectedCap:q.cap,instanceRevision:q.instanceRevision};}
function payExact(r,a,q){const initial=funds(r),result=cp(r.transact(a)),final=funds(r);assert.equal(initial.mora-final.mora,q.cost.mora);for(const id of Object.keys(initial.items))assert.equal(initial.items[id]-final.items[id],q.cost.items[id]||0);assert.deepEqual(result.result.cost,cp(q.cost));return {action:cp(a),quote:cp(q),receipt:result,initial,final,prng:r.s.global.PRNG_STATE,world:{day:r.s.global.WORLD_DAY,time:r.s.global.WORLD_TIME},stats:stats(r),inventoryEquipment:cp(r.s.inventory.filter(i=>i.equip))};}
function solve(A,b){A=A.map((row,i)=>[...row,b[i]]);for(let col=0;col<A.length;col++){let pivot=col;for(let j=col+1;j<A.length;j++)if(Math.abs(A[j][col])>Math.abs(A[pivot][col]))pivot=j;[A[col],A[pivot]]=[A[pivot],A[col]];const z=A[col][col];assert(Math.abs(z)>1e-12);for(let k=col;k<=A.length;k++)A[col][k]/=z;for(let j=0;j<A.length;j++)if(j!==col){const x=A[j][col];for(let k=col;k<=A.length;k++)A[j][k]-=x*A[col][k];}}return A.map(x=>x.at(-1));}
function expected(c,from,to){const columns=['attempts','mora','ORE_IRON','ORE_WHITE_IRON','ORE_CRYSTAL'],result={from,to,expected:{},matrix:{},error:{}};for(const key of columns){const F=[0],get=j=>key==='attempts'?1:key==='mora'?c.mora[j]:c.ores[j][key]||0;for(let j=1;j<=to;j++)F[j]=(get(j)+c.down[j]/10000*F[j-1])/(c.success[j]/10000);let sum=F.slice(from+1).reduce((a,b)=>a+b,0);const matrix=Array.from({length:to},()=>Array(to).fill(0)),cost=[];for(let i=0;i<to;i++){const j=i+1,p=c.success[j]/10000,d=c.down[j]/10000,h=1-p-d;matrix[i][i]=1-h;if(i+1<to)matrix[i][i+1]=-p;if(i>0)matrix[i][i-1]=-d;cost[i]=get(j);}const solved=solve(matrix,cost)[from];assert(Math.abs(sum-solved)<1e-7,'independent Markov matrix cost '+key);const ascend=from<=10&&to>10?(key==='mora'?c.ascensionCost.mora:key==='attempts'?0:c.ascensionCost.items[key]||0):0;result.expected[key]=sum+ascend;result.matrix[key]=solved+ascend;result.error[key]=sum-solved;}if(from<=10&&to>10)result.ascension={mora:c.ascensionCost.mora,items:cp(c.ascensionCost.items),actions:1};return result;}
check('only target11/12 price/material columns changed; all mechanism fields identical',()=>{const old=cp(before.api.enhancementConfig),fresh=cp(current.api.enhancementConfig);for(const[j,n]of [[11,0],[12,1]]){assert.equal(old.mora[j],OLD.mora[n]);assert.deepEqual(old.ores[j],OLD.ores[n]);assert.equal(fresh.mora[j],NEW.mora[n]);assert.deepEqual(fresh.ores[j],NEW.ores[n]);fresh.mora[j]=old.mora[j];fresh.ores[j]=old.ores[j];}assert.deepEqual(fresh,old);for(let j=2;j<=12;j++){assert(current.api.enhancementConfig.mora[j]>=current.api.enhancementConfig.mora[j-1]);for(const id of ['ORE_WHITE_IRON','ORE_CRYSTAL'])assert((current.api.enhancementConfig.ores[j][id]||0)>=(current.api.enhancementConfig.ores[j-1][id]||0));}return{priceTargets:[11,12],allOtherConfigExactlyEqual:true,monotoneMoraWhiteironCrystal:true};});
check('actual equipment profiles retain all milestones/traits and low prices across every supported equipment row',()=>{const a=H.setup(before,{level:60,gear:'none',route:'ROUTE_TRAVELER'}),b=new current.R(current.db,cp(a.s));let count=0;for(const row of a.rows('16_EQUIP_DB')){if(!a.isMondEnhanceable(row[0]))continue;const slot=a.giveEquipment(row[0]);b.s.inventory=cp(a.s.inventory);const invA=a.s.inventory.find(i=>i.slot===slot),invB=b.s.inventory.find(i=>i.slot===slot),pA=JSON.parse(a.row('16_EQUIP_DB',row[0])[32]),pB=JSON.parse(b.row('16_EQUIP_DB',row[0])[32]);for(const j of [11,12])pB.costs[j]=cp(pA.costs[j]);assert.deepEqual(pB,pA,'all nonprice native profile fields '+row[0]);assert.deepEqual(cp(b.gearTraitsFor(row[0])),cp(a.gearTraitsFor(row[0])));for(let level=0;level<=12;level++)assert.deepEqual(cp(b.enhancementStatsAt(invB,level)),cp(a.enhancementStatsAt(invA,level)));for(let level=0;level<10;level++){invA.enhance=invB.enhance=level;invA.enhancementCap=invB.enhancementCap=10;assert.deepEqual(cp(b.enhancementQuote(slot)),cp(a.enhancementQuote(slot)));}data.equipmentComparisons.push({id:row[0],name:row[1],all13StatsIdentical:true,allNonpriceProfileFieldsIdentical:true,target1to10QuotesIdentical:true});count++;}return{rows:count,statsPerRow:13,priceTargetsUntouched:10};});
check('independent full absorbing Markov matrix agrees for six paths and five reward columns',()=>{for(const[from,to]of [[0,6],[0,10],[0,12],[6,10],[10,12],[6,12]]){const x={before:expected(before.api.enhancementConfig,from,to),current:expected(current.api.enhancementConfig,from,to)};for(const key of Object.keys(x.before.expected))if(to<=10)assert.equal(x.current.expected[key],x.before.expected[key]);data.costPaths.push(x);}return{paths:6,columns:5,linearSystems:12*5,maxAbsoluteError:Math.max(...data.costPaths.flatMap(p=>[p.before,p.current].flatMap(x=>Object.values(x.error).map(Math.abs))))};});
for(const seed of [717,4242,9031])check('public native seeded progression, exact payments and old paid receipt/load preservation:'+seed,()=>{const a=H.setup(before,{level:60,route:'ROUTE_TRAVELER',seed,gear:'none',talent:10});const slot=a.giveEquipment('EQ_SWORD_RANCOUR');a.action('EQUIP',{slot,owner:'PLAYER_CUSTOM'});const inv=a.s.inventory.find(i=>i.slot===slot);inv.enhance=10;inv.enhancementCap=10;a.recalculate();a.s.global.MORA=20000000;for(const id of ['ORE_IRON','ORE_WHITE_IRON','ORE_CRYSTAL','TRPG_BOSS_ESSENCE','TRPG_BOSS_CORE'])a.giveItem(id,100000);a.action('PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP',mode:'CRAFT'});a.s.global.PRNG_STATE=seed;const initial=JSON.parse(a.serialize()),b=new current.R(current.db,cp(initial));assert.deepEqual(JSON.parse(b.serialize()),initial,'actual previous+10 save loads exactly');const sample={seed,slot,initialSave:initial,attempts:[],ascensions:[]};for(const r of [a,b]){const q=r.enhancementQuote(slot,'ASCEND');assert.equal(q.reason,'');const action=intent(r,'EQUIP_ASCEND',argsFrom(r,slot,'ASCEND'));sample.ascensions.push(payExact(r,action,q));}assert.deepEqual(sample.ascensions[1],sample.ascensions[0]);let observed=new Set;for(let n=0;a.s.inventory.find(i=>i.slot===slot).enhance<12&&n<250;n++){for(const r of [a,b]){if(!r.currentPlace()?.valid){for(let w=0;r.placeEntryReason('EVT_SCHEDULE_MRC_MOND_EQUIP','CRAFT');w++){assert(w<48);r.action('WAIT',{minutes:30});assert(!r.s.runtime);}r.action('PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP',mode:'CRAFT'});}}const qa=a.enhancementQuote(slot),qb=b.enhancementQuote(slot);assert.equal(qa.reason,'');assert.equal(qb.reason,'');const actionA=intent(a,'ENHANCE',argsFrom(a,slot)),actionB=intent(b,'ENHANCE',argsFrom(b,slot)),ra=payExact(a,actionA,qa),rb=payExact(b,actionB,qb);const xa=cp(ra.receipt.result),xb=cp(rb.receipt.result);delete xa.cost;delete xb.cost;assert.deepEqual(xb,xa,'outcome/probabilities/levels/stat growth exactly same');assert.equal(rb.prng,ra.prng);assert.deepEqual(rb.world,ra.world);assert.deepEqual(rb.stats,ra.stats);assert.deepEqual(rb.inventoryEquipment,ra.inventoryEquipment);observed.add(ra.receipt.result.outcome);const oldSave=JSON.parse(a.serialize()),loaded=new current.R(current.db,cp(oldSave));assert.deepEqual(JSON.parse(loaded.serialize()),oldSave,'complete paid old receipt save remains exact');const beforeReplay=loaded.serialize();assert.deepEqual(cp(loaded.transact(actionA)),ra.receipt,'old action retry returns old price receipt');assert.equal(loaded.serialize(),beforeReplay,'old retry neither pays nor rerolls');const stale=b.serialize();assert.throws(()=>b.action('ENHANCE',{slot:actionB.slot,expectedLevel:actionB.expectedLevel,expectedCap:actionB.expectedCap,instanceRevision:actionB.instanceRevision}));assert.equal(b.serialize(),stale);sample.attempts.push({target:qa.target,before:ra,current:rb,oldSaveSha256:sha(JSON.stringify(oldSave)),oldPaidReceiptRetryExact:true});}
assert.equal(a.s.inventory.find(i=>i.slot===slot).enhance,12);assert.equal(b.s.inventory.find(i=>i.slot===slot).enhance,12);const finalOld=JSON.parse(a.serialize()),loadedFinal=new current.R(current.db,cp(finalOld));assert.deepEqual(JSON.parse(loadedFinal.serialize()),finalOld,'entire actual old+12 finished save stays equal');assert.deepEqual(stats(loadedFinal),stats(a));assert.deepEqual(stats(b),stats(a));sample.finalOldSave=finalOld;sample.finalNewSave=JSON.parse(b.serialize());sample.totals={before:{mora:sample.ascensions[0].quote.cost.mora+sample.attempts.reduce((s,x)=>s+x.before.quote.cost.mora,0)},current:{mora:sample.ascensions[1].quote.cost.mora+sample.attempts.reduce((s,x)=>s+x.current.quote.cost.mora,0)},attempts:sample.attempts.length,outcomes:[...observed]};for(const side of ['before','current'])sample.totals[side].items=sample.attempts.reduce((s,x)=>{for(const[id,n]of Object.entries(x[side].quote.cost.items))s[id]=(s[id]||0)+n;return s;},cp(sample.ascensions[side==='before'?0:1].quote.cost.items));data.nativeSamples.push(sample);save();return{attempts:sample.attempts.length,outcomes:[...observed],costs:sample.totals,oldSavedReceiptsAndPlus12FullSavesUnchanged:true,allNativeOutcomeStatsAndPrngSame:true};});

function nextRoll(seed){let x=seed>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;return {state:x>>>0,roll:1+Math.floor((x>>>0)/4294967296*10000)};}
for(const target of [11,12])for(const outcome of ['SUCCESS','HOLD','DOWN'])check('native seed-selected outcome pays one current/old cost; paid receipt never changes:'+target+':'+outcome,()=>{
 const cfg=current.api.enhancementConfig,success=cfg.success[target],down=cfg.down[target];let seed=1;for(;seed<1000000;seed++){const q=nextRoll(seed);if((q.roll<=success?'SUCCESS':q.roll>10000-down?'DOWN':'HOLD')===outcome)break;}assert(seed<1000000);
 const a=H.setup(before,{level:60,route:'ROUTE_TRAVELER',seed:717,gear:'none',talent:10}),slot=a.giveEquipment('EQ_SWORD_RANCOUR');a.action('EQUIP',{slot,owner:'PLAYER_CUSTOM'});const inv=a.s.inventory.find(i=>i.slot===slot);inv.enhance=target-1;inv.enhancementCap=12;a.recalculate();a.s.global.MORA=1000000;for(const id of ['ORE_WHITE_IRON','ORE_CRYSTAL'])a.giveItem(id,1000);a.action('PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP',mode:'CRAFT'});a.s.global.PRNG_STATE=seed;const initial=JSON.parse(a.serialize()),b=new current.R(current.db,cp(initial));assert.deepEqual(JSON.parse(b.serialize()),initial);
 const qa=a.enhancementQuote(slot),qb=b.enhancementQuote(slot),actionA=intent(a,'ENHANCE',argsFrom(a,slot)),actionB=intent(b,'ENHANCE',argsFrom(b,slot)),oldReceipt=payExact(a,actionA,qa),newReceipt=payExact(b,actionB,qb);assert.equal(oldReceipt.receipt.result.outcome,outcome);assert.equal(newReceipt.receipt.result.outcome,outcome);assert.equal(newReceipt.prng,nextRoll(seed).state);assert.equal(oldReceipt.prng,newReceipt.prng);assert.deepEqual(newReceipt.inventoryEquipment,oldReceipt.inventoryEquipment);assert.deepEqual(newReceipt.stats,oldReceipt.stats);const oldPaid=JSON.parse(a.serialize()),loaded=new current.R(current.db,cp(oldPaid));assert.deepEqual(JSON.parse(loaded.serialize()),oldPaid);const beforeRetry=loaded.serialize();assert.deepEqual(cp(loaded.transact(actionA)),oldReceipt.receipt);assert.equal(loaded.serialize(),beforeRetry);
 const row={target,outcome,seed,independentFirstNativeRoll:nextRoll(seed),fixture:'previous owned cap12 equipment at target-1; seed selected observationally using independent unchanged xorshift, no die/RNG function override; three complete progression seeds kept separately',initialSave:initial,before:oldReceipt,current:newReceipt,oldPaidSaveSha256:sha(JSON.stringify(oldPaid)),oldReceiptRetryExact:true};data.boundarySamples.push(row);return{target,outcome,seed,roll:nextRoll(seed).roll,oldCost:qa.cost,currentCost:qb.cost,resourcesPaidOnce:true};
});
check('all ascended equipment remains untradeable and fixed NPC resale never grows with cheaper enhancement',()=>{
 const a=H.setup(before,{level:60,gear:'none',route:'ROUTE_TRAVELER'}),b=new current.R(current.db,cp(a.s));for(const row of a.rows('16_EQUIP_DB')){if(!a.isMondEnhanceable(row[0]))continue;const slot=a.giveEquipment(row[0]);b.s.inventory=cp(a.s.inventory);const ia=a.s.inventory.find(i=>i.slot===slot),ib=b.s.inventory.find(i=>i.slot===slot);ia.enhance=ib.enhance=12;ia.enhancementCap=ib.enhancementCap=12;const oldRule=cp(a.tradeRule(ia)),freshRule=cp(b.tradeRule(ib));assert.deepEqual(freshRule,oldRule);assert.equal(freshRule.ok,false);assert.match(freshRule.reason,/돌파한 장비/);assert.equal(b.saleUnitPrice(ib),a.saleUnitPrice(ia));data.marketComparisons.push({id:row[0],rule:freshRule,npcSaleMora:b.saleUnitPrice(ib),unchangedResale:true});}return{rows:data.marketComparisons.length,ascendedMarketBlocked:true,npcResaleUnchanged:true};
});
data.summary={checks:data.checks.length,passed:data.checks.filter(x=>x.ok).length,equipmentRows:data.equipmentComparisons.length,nativeSamples:data.nativeSamples.length,nativePairedAttempts:data.nativeSamples.reduce((s,x)=>s+x.attempts.length,0),seedSelectedBoundaryCases:data.boundarySamples.length,marketRows:data.marketComparisons.length,observedOutcomes:[...new Set(data.nativeSamples.flatMap(x=>x.totals.outcomes))],marginal:data.costPaths.find(x=>x.current.from===10&&x.current.to===12)};save();fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(data.summary,null,2)+'\n');console.log(JSON.stringify(data.summary));
