'use strict';
// Actual native before/current scope and early-story combat comparisons.
// Granted legal preparation and scene/event access, never damage/RNG/outcome.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),zlib=require('node:zlib');
const H=require('./audit_protagonist_v01618.cjs'),N=require('../tests/test_enemy_balance_v01627.cjs'),ROOT=path.resolve(__dirname,'..'),OUT=path.resolve(process.argv[2]||path.join(ROOT,'reports/abyss_difficulty_v01627/final_scope'));
const current=N.productionBootstrap(H.load(ROOT)),before=N.productionBootstrap(N.loadBefore(ROOT)),cp=x=>JSON.parse(JSON.stringify(x)),team=['MOND_AMBER','MOND_KAEYA','MOND_LISA'];
const stats=b=>cp(b.actors.map(a=>({id:a.id,source:a.source,side:a.side,level:a.level,hp:a.hp,maxHp:a.maxHp,atk:a.atk,def:a.def,spd:a.spd,shields:cp(a.shields)})));
const setup=(e,o)=>H.setup(e,{team,route:'ROUTE_TRAVELER',seed:717,gear:'craft',enhance:3,talent:10,...o});
const report={beforeFingerprint:before.fingerprint,currentFingerprint:current.fingerprint,checks:[],story:[]};
function check(id,fn){try{report.checks.push({id,passed:true,evidence:fn()});}catch(e){report.checks.push({id,passed:false,error:e.stack});}console.log(JSON.stringify(report.checks.at(-1)));}
for(const f of [1,6,9])check('native_abyss_actors_remain_identical_floor_'+f,()=>{const runs=[before,current].map(e=>{const r=setup(e,{level:f===1?15:f===6?40:55,map:'MAP_V141_MUSK_REEF'}),ab=r.ensureAbyss();for(let n=1;n<f;n++)ab.clears[n]={rounds:1,chambers:[1,1,1],party:[],run:ab.run};r.action('ABYSS_ENTER',{floor:f});assert.equal(r.s.runtime.enemyBalanceRevision,undefined);return r;});assert.deepEqual(stats(runs[1].s.runtime),stats(runs[0].s.runtime));assert.deepEqual(cp(runs[1].s.runtime.order),cp(runs[0].s.runtime.order));assert.equal(runs[1].s.global.PRNG_STATE,runs[0].s.global.PRNG_STATE);return{floor:f,actors:stats(runs[1].s.runtime),markerAbsent:true};});
for(const boss of current.api.raidV0152.bosses)check('native_public_raid_event_remains_identical_'+boss.id,()=>{const runs=[before,current].map(e=>{const r=setup(e,{level:60,map:'MAP_MOND_PLAINS'});r.raidServerEvent={id:'RAID_627',boss:boss.id,startsAt:0,endsAt:4102444800000,target:4000};r.action('RAID_ENTER');assert(r.s.runtime.raid);assert.equal(r.s.runtime.enemyBalanceRevision,undefined);return r;});assert.deepEqual(stats(runs[1].s.runtime),stats(runs[0].s.runtime));assert.deepEqual(cp(runs[1].s.runtime.order),cp(runs[0].s.runtime.order));assert.equal(runs[1].s.global.PRNG_STATE,runs[0].s.global.PRNG_STATE);return{boss:boss.id,origin:runs[1].s.runtime.origin,actors:stats(runs[1].s.runtime),markerAbsent:true};});
for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI'])check('native_protect_formation_remains_identical_'+route,()=>{const node=route==='ROUTE_TRAVELER'?'TRV_LY4_OSIAL_COMBAT':'ISK_L04_K1_040',group=route==='ROUTE_TRAVELER'?'EG_BOSS_OSIAL':'EG_ISK_L04_OSIAL',runs=[before,current].map(e=>{const r=setup(e,{level:60,map:'MAP_OSIAL_BATTLE',route});r.s.flags.FLAG_ISK_L01_LEAF='K1';r.storySetCursor(node);r.startBattle(group,'STORY:'+node,{confirmed:true,companions:team});assert.equal(r.s.runtime.storyConfig.objective.kind,'PROTECT_FORMATION');assert.equal(r.s.runtime.enemyBalanceRevision,undefined);return r;});assert.deepEqual(stats(runs[1].s.runtime),stats(runs[0].s.runtime));assert.deepEqual(cp(runs[1].s.runtime.liyueObjective),cp(runs[0].s.runtime.liyueObjective));assert.deepEqual(cp(runs[1].s.runtime.order),cp(runs[0].s.runtime.order));assert.equal(runs[1].s.global.PRNG_STATE,runs[0].s.global.PRNG_STATE);return{route,actors:stats(runs[1].s.runtime),objective:cp(runs[1].s.runtime.liyueObjective),markerAbsent:true};});
for(const origin of ['EXPLICIT','STORY:DIFFICULTY_SCOPE_NUMERIC'])check('fresh_ordinary_and_story_independent_def_basis_'+origin,()=>{const rows=[];for(const level of [3,10,12,30,50,60]){const runs=[before,current].map(e=>{const r=setup(e,{level:30,map:'MAP_MOND_FOREST'}),a={id:'QA_DEF_'+level,source:'MON_HILI_FIGHTER',side:'ENEMY',grade:'일반',hp:105,maxHp:105,atk:24,def:20,spd:10,statuses:[],shields:[]},b={id:'NEW_NUMERIC_'+level,origin,actors:[a],enemyBalanceRevision:1};r.tuneGrowthEnemy(a,b,level);return a;});const old=runs[0],a=runs[1],w=level<=20?0:level===30?.25:level===50?.8:1,expected={hp:Math.round(old.maxHp*(1+.4*w)),atk:Math.round(old.atk*(1+.6*w)),def:Math.round(Math.round(old.def*(1+.5*w))*(100+5*Math.max(0,level-35))/100)};assert.deepEqual([a.maxHp,a.atk,a.def],[expected.hp,expected.atk,expected.def]);rows.push({level,before:[old.maxHp,old.atk,old.def],after:[a.maxHp,a.atk,a.def],expected});}return{origin,rows,probe:'independent current-policy arithmetic, not a completed combat'};});
const SCENES=[{node:'TRV_M02_N139',group:'EG_TRV_WOLF_WAVE',map:'MAP_MOND_TEMPLE_WOLF',enemyLevel:10},{node:'TRV_M02_N157',group:'EG_TRV_LION_WAVE',map:'MAP_MOND_TEMPLE_LION',enemyLevel:12}];
for(const scene of SCENES)for(const level of [3,10])for(const seed of [717,4242,9031])for(const[e,label]of[[before,'before'],[current,'current']]){const row={scene:scene.node,group:scene.group,enemyLevel:scene.enemyLevel,playerLevel:level,seed,engine:label};let r;try{r=setup(e,{level,seed,map:scene.map,gear:level===3?'starter':'craft',enhance:level===3?0:3,talent:10});row.gear=cp(r.s.inventory.filter(v=>v.equipped));row.talents=Object.fromEntries(r.s.party.filter(v=>v.active).map(v=>[v.source,r.talentLevels(v.source)]));row.before=H.hp(r);r.storySetCursor(scene.node);const meter=H.observe(e,r);r.startBattle(scene.group,'STORY:'+scene.node,{confirmed:true,companions:team});row.initial=stats(r.s.runtime);row.policyMarker=r.s.runtime.enemyBalanceRevision??null;row.result=H.play(r);row.inputs=meter.inputs;row.presentationMs=meter.ms;row.native=r._auditLast;row.after=H.hp(r);row.ko=row.native?.actors.filter(a=>a.side==='ALLY'&&a.hp<=0).map(a=>a.source)||[];row.finalHp=row.native?.actors.filter(a=>a.side==='ALLY').reduce((n,a)=>n+a.hp,0)/row.native?.actors.filter(a=>a.side==='ALLY').reduce((n,a)=>n+a.maxHp,0);row.state=row.result.victory?'WIN':row.result.stalled?'INPUT_LIMIT':'LOSS';}catch(e){row.state='ERROR';row.error=e.stack;}report.story.push(row);console.log(JSON.stringify({scene:row.scene,playerLevel:level,enemyLevel:row.enemyLevel,engine:label,seed,state:row.state,rounds:row.result?.rounds,ko:row.ko,finalHp:row.finalHp,marker:row.policyMarker,error:row.error}));}
fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(OUT+'/raw.json.gz',zlib.gzipSync(JSON.stringify(report)));report.story=report.story.map(r=>({scene:r.scene,group:r.group,enemyLevel:r.enemyLevel,playerLevel:r.playerLevel,seed:r.seed,engine:r.engine,state:r.state,rounds:r.result?.rounds,ko:r.ko,finalHp:r.finalHp,policyMarker:r.policyMarker,error:r.error}));report.total=report.checks.length;report.failed=report.checks.filter(x=>!x.passed).length;fs.writeFileSync(OUT+'/summary.json',JSON.stringify(report,null,2)+'\n');fs.copyFileSync(__filename,OUT+'/runner.cjs');if(report.failed||report.story.some(x=>x.state==='ERROR'))process.exitCode=1;
