'use strict';
// Isolated candidate VM only; product source and authored DB are never modified.
const fs=require('node:fs'),path=require('node:path'),H=require('./audit_protagonist_v01618.cjs');
const args=process.argv.slice(2),arg=k=>args.includes(k)?args[args.indexOf(k)+1]:null,root=path.resolve(arg('--root')||path.resolve(__dirname,'..')),out=arg('--out')||'/tmp/crpg_v01627_ordinary/candidates.json';
const candidates=arg('--profiles')?JSON.parse(fs.readFileSync(arg('--profiles'))):[{name:'BASELINE',hp:1,atk:1,def:1},{name:'A',hp:1.3,atk:1.4,def:1.5},{name:'B',hp:1.5,atk:1.6,def:1.75},{name:'C',hp:1.6,atk:1.8,def:2}],teams={story4:H.TEAMS.story4,heal5:['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN']},rows=[],errors=[];fs.mkdirSync(path.dirname(out),{recursive:true});
const data={schema:1,sourceRoot:root,assumptions:'Native public fixed-four-party combat and companion AI; Isekai C0, crafted +6, no artifacts/exclusive/boss equipment. Prepared legal max base talents or floor(legal cap*.65) compared. Candidate enemy HP/ATK/DEF multipliers are VM-only after the unchanged native curve, ramping from Lv15 to60; no forced damage, hits, heal or wins. Two-X timing uses native presentation/1000 +3seconds/player input +6seconds re-entry.',rows,errors};const save=()=>fs.writeFileSync(out,JSON.stringify(data,null,2)+'\n');
for(const candidate of candidates){const env=H.load(root);data.fingerprint=env.fingerprint;const P=env.R.prototype,old=P.tuneGrowthEnemy;P.tuneGrowthEnemy=function(a,b,l){const scaled=a.growthScaled;old.call(this,a,b,l);if(scaled||a.grade==='보스'||a.fieldStructure)return;const profile=candidate[this._growthDomain?.kind]||candidate,t=Math.max(0,Math.min(1,(l-15)/45)),m=k=>1+(profile[k]-1)*t;const prior=a.maxHp;a.hp=a.maxHp=Math.round(a.maxHp*m('hp'));a.atk=Math.round(a.atk*m('atk'));a.def=Math.round(a.def*m('def'));for(const s of a.shields||[]){s.value=Math.round(s.value*a.maxHp/prior);if(s.initialValue)s.initialValue=Math.round(s.initialValue*a.maxHp/prior);}};
for(const kind of ['TALENT','ASCENSION','EXP'])for(const[name,team]of Object.entries(teams))for(const talent of [6,10])try{const domain={TALENT:'TAISHAN_MANSION:60',ASCENSION:'LIANSHAN_FORMULA:60',EXP:'LOST_VALLEY:60'}[kind],row=H.campaign(env,{name:candidate.name+':'+kind+':'+name+':T'+talent,team,level:60,talent,route:'ROUTE_ISEKAI',seed:717,domain,element:'NEUTRAL'},{runs:1}),f=row.battles[0],pre=f.hpBeforeReward;row.candidate=candidate;row.firstPreRewardHpRatio=pre.reduce((n,a)=>n+Math.max(0,a.hp),0)/pre.reduce((n,a)=>n+a.maxHp,0);rows.push(row);console.log(JSON.stringify({name:row.name,wins:row.wins,rounds:row.rounds,secs:row.seconds,hp:row.firstPreRewardHpRatio,ownDamage:row.ownDamage,allyDamage:row.allyDamage,heal:row.healing}));save();}catch(e){errors.push({candidate:candidate.name,kind,team:name,talent,error:e.message,code:e.code||e.name});save();}}
data.counts={conditions:rows.length,wins:rows.reduce((n,r)=>n+r.wins,0),losses:rows.reduce((n,r)=>n+r.losses,0),errors:errors.length};save();
