'use strict';
// Isolated sequential workers bound memory while executing the exact same
// source/browser/server contract bodies and genuine previous-engine loader.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{createRequire}=require('node:module'),{pathToFileURL}=require('node:url'),{spawnSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'),BROWSER=path.resolve(process.argv[2]||path.join(ROOT,'dist')),OUT=path.resolve(process.argv[3]||path.join(ROOT,'reports/balance-v01625-engines')),SERVER=path.join(ROOT,'server/generated/engine.mjs'),ENGINE=process.argv[4];
const H=require('./audit_protagonist_v01618.cjs'),sha=raw=>crypto.createHash('sha256').update(raw).digest('hex'),NOW=1791615600000,OriginalDate=Date,FixedDate=class extends OriginalDate{constructor(...args){super(...(args.length?args:[NOW]));}static now(){return NOW;}};
function productionBootstrap(env){if(!env.R.prototype.__relationshipsInstalled){const rel=env.c?.CRPGRelationships;assert(rel,'same production relationship module');rel.install(env.api,{events:rel.catalogFromDB(env.db),activities:rel.activitiesFromDB(env.db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});}assert.equal(env.R.prototype.__relationshipsInstalled,true);return env;}
function browser(){const c=vm.createContext({console,Date:FixedDate,setTimeout,clearTimeout});c.window=c;vm.runInContext(fs.readFileSync(path.join(BROWSER,'data.js'),'utf8'),c);let modules=0;for(const[,file]of fs.readFileSync(path.join(BROWSER,'index.html'),'utf8').matchAll(/<script src="([^"?]+)(?:\?[^" ]*)?"/g))if(file==='world_content.js'||file==='presentation.js'||file.startsWith('runtime')){const raw=fs.readFileSync(path.join(BROWSER,file));assert.equal(sha(raw),sha(fs.readFileSync(path.join(ROOT,'source',file))),file);modules++;vm.runInContext(raw.toString(),c,{filename:'built/'+file});}assert.equal(modules,120);return{c,db:c.CRPG_DATA,R:c.CRPGRuntime.Runtime,api:c.CRPGRuntime,root:ROOT,fingerprint:JSON.parse(fs.readFileSync(path.join(BROWSER,'release.json'))).engineVersion};}
async function worker(){globalThis.Date=FixedDate;const rawDB=fs.readFileSync(path.join(ROOT,'content/db.json')),rawHash=sha(rawDB);let env;
 if(ENGINE==='source')env=H.load(ROOT);else if(ENGINE==='browser')env=browser();else{const server=await import(pathToFileURL(SERVER).href);env={R:server.R,db:server.DB,api:globalThis.CRPGRuntime,root:ROOT,fingerprint:server.ENGINE_FINGERPRINT};}
 productionBootstrap(env);env.rawDbSHA256=rawHash;if(env.c)env.c.Date=FixedDate;const rows=[];
 for(const test of ['test_character_balance_v01625.cjs','test_skill_rhythm_ownership_v01625.cjs','test_daily_pressure_v01624.cjs','test_basic_air_range_v01624.cjs']){const file=path.join(ROOT,'tests',test),code=fs.readFileSync(file,'utf8'),output=path.join(OUT,ENGINE+'-'+test+'.json'),nativeRequire=createRequire(file),before=sha(JSON.stringify(env.db)),facade={argv:[process.execPath,file,...(test==='test_character_balance_v01625.cjs'?['--out',output,'--require-recorded-qa']:[output])],exitCode:0};const adaptedRequire=id=>id==='../tools/audit_protagonist_v01618.cjs'?{...H,load:()=>env}:nativeRequire(id);
 vm.runInNewContext(code,{console,require:adaptedRequire,process:facade,__dirname:path.dirname(file),__filename:file,Buffer,setTimeout,clearTimeout,TextEncoder,TextDecoder},{filename:file,timeout:180000});
 const result=JSON.parse(fs.readFileSync(output));if(result.total===undefined&&Array.isArray(result.checks)){result.total=result.checks.length;result.passed=result.checks.filter(c=>c.passed===true||c.ok===true).length;result.failed=result.total-result.passed;}assert.equal(result.failed,0);assert.equal(result.passed,result.total);assert.equal(facade.exitCode,0);assert.equal(before,sha(JSON.stringify(env.db)));rows.push({test,engine:ENGINE,engineFingerprint:env.fingerprint,toolSHA256:sha(code),output:path.basename(output),outputSHA256:sha(fs.readFileSync(output)),checks:result.total,passed:result.passed,rawDbObjectUnchanged:true});if(global.gc)global.gc();}
 assert.equal(rawHash,sha(fs.readFileSync(path.join(ROOT,'content/db.json'))));fs.writeFileSync(path.join(OUT,ENGINE+'-summary.json'),JSON.stringify({engine:ENGINE,fingerprint:env.fingerprint,rawDbSHA256:rawHash,rows},null,2)+'\n');}
(async()=>{fs.mkdirSync(OUT,{recursive:true});if(ENGINE)return worker();assert(!fs.existsSync(path.join(OUT,'summary.json')),'Use a fresh output folder');const rows=[];for(const engine of ['source','browser','server']){const result=spawnSync(process.execPath,['--max-old-space-size=640','--expose-gc',__filename,BROWSER,OUT,engine],{cwd:ROOT,encoding:'utf8',maxBuffer:8*1024*1024,timeout:600000});fs.writeFileSync(path.join(OUT,engine+'.stdout.log'),result.stdout||'');fs.writeFileSync(path.join(OUT,engine+'.stderr.log'),result.stderr||'');assert.equal(result.status,0,engine+' worker failed: '+result.stderr);const summary=JSON.parse(fs.readFileSync(path.join(OUT,engine+'-summary.json')));rows.push(...summary.rows);console.log(engine+' '+summary.rows.reduce((n,r)=>n+r.passed,0)+' passed');}const build=JSON.parse(fs.readFileSync(path.join(BROWSER,'release.json')));assert.equal(JSON.parse(fs.readFileSync(path.join(OUT,'server-summary.json'))).fingerprint,build.engineVersion);const summary={scope:'Exact new character/ownership, prior daily-pressure and bow-range contracts on actual source/browser/server engines. Each current engine runs in a separate process, with the genuine seven-module previous engine loaded for compatibility comparisons.',rawDbSHA256:sha(fs.readFileSync(path.join(ROOT,'content/db.json'))),engineFingerprint:build.engineVersion,serverEngineSHA256:sha(fs.readFileSync(SERVER)),rows,total:rows.reduce((n,r)=>n+r.checks,0),passed:rows.reduce((n,r)=>n+r.passed,0),failed:0};fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify({total:summary.total,passed:summary.passed,failed:0}));})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
