'use strict';
// Observational native comparisons. Fixtures grant declared ownership/gear/levels only;
// enemy rules, HP, rolls, actions, recovery payment and carry-over remain native.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const DEFAULT_ROOT=path.resolve(__dirname,'..'),PLAYER='PLAYER_CUSTOM',IE='PLAYER_ISEKAI_E',IQ='PLAYER_ISEKAI_Q';
const cp=x=>JSON.parse(JSON.stringify(x));
function load(root=DEFAULT_ROOT,candidate=null){const c=vm.createContext({console,Date,setTimeout,clearTimeout}),h=crypto.createHash('sha256'),index=fs.readFileSync(path.join(root,'source/index.html'),'utf8'),substitutions=[];
 const replacement=(txt,from,to,f)=>{const n=txt.split(from).length-1;if(n!==1)throw new Error('Expected one exact healing formula in '+f+': '+from+'; found '+n);substitutions.push({file:f,from,to});return txt.replace(from,to);};
 for(const [,f]of index.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)){let text=fs.readFileSync(path.join(root,'source',f),'utf8');h.update(f);h.update(text);
 if(candidate?.currentRevision){
  if(f==='runtime_combat.js'&&text.includes('jeanQFlat:450,'))text=replacement(text,'jeanQFlat:450,','jeanQFlat:'+candidate.jeanQFlat+',',f);
  else if(f==='runtime_combat.js')text=replacement(text,"healAll('atk',.05,450);","healAll('atk',.05,"+candidate.jeanQFlat+");",f);
  if(f==='runtime_rules.js'&&text.includes("this.combatStat(a,'atk')*.05+450,a.name);"))text=replacement(text,"this.combatStat(a,'atk')*.05+450,a.name);","this.combatStat(a,'atk')*.05+"+candidate.jeanQFlat+",a.name);",f);
 }else if(candidate&&candidate.name!=='BASELINE'){
  if(f==='runtime_rules.js')text=replacement(text,"case'MOND_JEAN_Q':for(const t of allies)this.heal(t,this.combatStat(a,'atk')*1.2,a.name);","case'MOND_JEAN_Q':for(const t of allies)this.heal(t,this.combatStat(a,'atk')*"+candidate.jeanQ+"+"+(candidate.jeanQFlat||0)+",a.name);",f);
  if(f==='runtime_combat.js'){
   text=replacement(text,"case'MOND_JEAN_Q':healAll('atk',1.2);","case'MOND_JEAN_Q':for(const t of allies)this.heal(t,this.combatStat(a,'atk')*"+candidate.jeanQ+"+"+(candidate.jeanQFlat||0)+",a.name);",f);
   text=replacement(text,"if(f.kind==='DANDELION')allies.forEach(t=>this.heal(t,this.combatStat(a,'atk')*.35,a.name));",candidate.focusedJeanFields?"if(f.kind==='DANDELION'&&f.healRound!==b.round&&(f.healTicks||0)<2){f.healRound=b.round;f.healTicks=(f.healTicks||0)+1;const target=allies.slice().sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp||b.actors.indexOf(x)-b.actors.indexOf(y))[0];if(target)this.heal(target,this.combatStat(a,'atk')*"+candidate.jeanField+"+"+(candidate.jeanFieldFlat||0)+",a.name);}":"if(f.kind==='DANDELION')allies.forEach(t=>this.heal(t,this.combatStat(a,'atk')*"+candidate.jeanField+",a.name));",f);
   text=replacement(text,"case'MOND_BARBARA_Q':healAll('maxHp',.25);","case'MOND_BARBARA_Q':for(const t of allies)this.heal(t,this.combatStat(a,'maxHp')*"+candidate.barbaraQ+"+"+(candidate.barbaraQFlat||0)+",a.name);",f);
   text=replacement(text,"if(status(a,'STATUS_BARBARA_MELODY_LOOP'))for(const ally of this.s.runtime.actors.filter(x=>x.side===a.side))this.heal(ally,a.maxHp*.06,a.name);","if(status(a,'STATUS_BARBARA_MELODY_LOOP'))for(const ally of this.s.runtime.actors.filter(x=>x.side===a.side))this.heal(ally,a.maxHp*"+candidate.barbaraE+"+"+(candidate.barbaraEFlat||0)+",a.name);",f);
  }
 }
 if(f==='runtime_combat.js'){const prefix="P.heal=function(a,amount,source=''){if(a.hp<=0)return 0;";if(text.split(prefix).length!==2)throw new Error('Base heal audit hook must match once');text=text.replace(prefix,prefix+"this._auditHealNominal?.(a,amount,source);");}
 vm.runInContext(text,c,{filename:f});}
 vm.runInContext(fs.readFileSync(path.join(root,'source/presentation.js'),'utf8'),c);const raw=fs.readFileSync(path.join(root,'content/db.json'));h.update(raw);return{c,db:JSON.parse(raw),R:c.CRPGRuntime.Runtime,api:c.CRPGRuntime,root,fingerprint:h.digest('hex'),candidate,substitutions};}
function setup(env,{level=30,team=[],route='ROUTE_ISEKAI',seed=717,map='MAP_MOND_CITY',gear,enhance,talent}={}){const{R,db,api}=env,r=new R(db);r.newGame({name:'동일 조건 비교',route,seed,saveId:'PROTAGONIST-V01618-'+route+'-'+level+'-'+seed});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,STORY_MENU_POLICY:'',WORLD_TIME:'12:00',MORA:1000000});delete r.s.storyJourney;delete r.s.storyBreak;r.prepareStory();
 for(const f of ['FLAG_TRV_ANEMO_UNLOCKED','FLAG_TRV_MON_CH1_CLEAR','FLAG_TRV_MON_CH2_CLEAR','FLAG_ISK_M03_CLEAR','FLAG_ISK_M05_CLEAR','FLAG_ACCESS_REGION_LIYUE'])r.s.flags[f]=true;
 for(const rt of ['TRV','ISK'])for(const region of ['MOND','LIYUE'])for(let n=1;n<=4;n++){const id=`Q_${rt}_${region}_0${n}`;if(r.tables['22_QUEST_DB'].has(id))r.questState(id).claimed=true;}
 r.s.inventory=[];const owned={};r.s.party=r.s.party.map((p,i)=>i?{slot:'PARTY_'+(i+1),active:false}:p);const starter={'한손검':'EQ_SWORD_COOL_STEEL','양손검':'EQ_CLAYMORE_DEBATE','장병기':'EQ_POLEARM_BLACK_TASSEL','활':'EQ_BOW_SLINGSHOT','법구':'EQ_CATALYST_MAGIC_GUIDE'},craft={'한손검':'EQ_SWORD_RANCOUR','양손검':'EQ_CLAYMORE_WHITEBLIND','장병기':'EQ_POLEARM_CRESCENT','활':'EQ_BOW_CRESCENT','법구':'EQ_CATALYST_MAPPA'};
 gear??=level<5?'starter':'craft';enhance??=level<10?0:level<30?3:6;
 for(const[i,id]of[PLAYER,...team].entries()){if(id===PLAYER){r.s.global.PLAYER_LEVEL_STATE=level;r.s.global.PLAYER_XP_STATE=0;}else{r.s.chars[id].level=level;r.s.chars[id].xp=0;owned[id]={state:'JOINED'};r.s.party[i]={slot:'PARTY_'+(i+1),type:'CHAR',source:id,control:'AI',active:true,tactic:'균형'};}r.s.ascensions[id]=api.growthV01522.phaseFor(level);}
 r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(owned);for(const id of[PLAYER,...team]){const cap=r.growth(id).talentCap,t=talent??Math.max(1,Math.floor(cap*.65));(r.s.talents??={})[id]={na:Math.min(cap,t),e:Math.min(cap,t),q:Math.min(cap,t)};if(gear==='none')continue;const weapon=(gear==='starter'?starter:craft)[r.equipmentProficiencies(id)[0]],equips=[weapon,gear==='starter'?'EQ_ARMOR_TRAVEL_COAT':'EQ_ARMOR_REINFORCED_LEATHER',...(gear==='starter'?[]:['EQ_ACC_HEALER_BROOCH'])];for(const eq of equips){if(Number(r.row('16_EQUIP_DB',eq)[19]||1)>level)continue;const slot=r.giveEquipment(eq);r.action('EQUIP',{slot,owner:id});const inv=r.s.inventory.find(x=>x.slot===slot);inv.enhance=enhance;if(enhance>10)inv.enhancementCap=12;}}
 r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;for(const id of team)r.s.chars[id].hp=r.character(id).maxHp;Object.assign(r.tutorialState().done,{combatAttack:true,combatGuard:true,combatSkill:true,combatBurst:true});r.s.global.PRNG_STATE=seed;r.s.domainDaily={day:api.growthV01522.dayOf(r.leyLineNow()),wins:3};return r;}
function hp(r){return r.s.party.filter(p=>p.active).map(p=>{const a=p.source===PLAYER?r.player():r.character(p.source);return{owner:p.source,level:a.level,hp:a.hp,maxHp:a.maxHp};});}
function play(r,{policy='E_FIRST'}={}){if(r.combatOpening?.())r.action('COMBAT_BEGIN');for(let n=0;r.s.runtime&&n<400;n++){const b=r.s.runtime;if(b.liyueInterlude){r.action('LIYUE_INTERLUDE_ACK');continue;}if(b.interlude){r.action('STORY_NEXT',{node:r.storyActiveNodeId()});continue;}const cards=r.combatCards().filter(x=>!x.reason),foes=b.actors.filter(a=>a.side==='ENEMY'&&a.hp>0);let card=cards.find(x=>x.id==='SYS_MOND_WIND_ROUTE'),target;if(!card&&b.subduedPending)card=cards.find(x=>x.id===b.storyConfig?.orb_action?.id);if(!card&&policy==='E_FIRST'){const e=cards.find(x=>x.id===IE);if(e){const ids=new Set(e.targets.map(x=>x.id)),unmarked=foes.filter(x=>ids.has(x.id)&&!(x.statuses||[]).some(s=>s.id==='STATUS_ISEKAI_EXPOSED'&&(s.rounds==null||s.rounds>0)));if(unmarked.length){card=e;target=unmarked.sort((a,b)=>b.hp-a.hp)[0];}}}card??=cards.find(x=>/PLAYER_(?:TRAVELER_ANEMO|ISEKAI)_Q$/.test(x.id));card??=cards.find(x=>x.id==='PLAYER_TRAVELER_ANEMO_E');card??=cards.find(x=>x.id===IE);card??=cards.find(x=>x.id==='PLAYER_BASIC_ATTACK')||cards.find(x=>x.id==='PLAYER_BASIC_GUARD');if(!card){r.autoUntilPlayer();continue;}target??=card.targets.map(t=>foes.find(a=>a.id===t.id)||t).sort((a,b)=>(a.hp??Infinity)-(b.hp??Infinity))[0];r.action('COMBAT',{card:card.id,...(target?{target:target.id}:{}),...(card.id==='PLAYER_TRAVELER_ANEMO_E'?{branch:'HOLD'}:{})});}return r.s.runtime?{victory:false,stalled:true,rounds:r.s.runtime.round}:JSON.parse(r.s.global.LAST_BATTLE_RESULT_JSON||'{}');}
function observe(env,r){const meter={ms:0,inputs:0,ownDamage:0,allyDamage:0,jointDamage:0,exposureDamage:0,heal:0,actions:0};r._protagonistMeter=meter;const action=r.action;r.action=function(type,args){const before=env.c.CRPGPresentation.snapshot(this.s),out=action.call(this,type,args);for(const f of env.c.CRPGPresentation.actionFrames(env.c.CRPGPresentation.delta(before,this.s))){if(f.kind==='state'&&f.silent)continue;meter.ms+=f.kind==='action'?460+(f.attemptCount>1?520:650):1400;}if(type==='COMBAT')meter.inputs++;return out;};const damage=r.applyDamage;r.applyDamage=function(a,t,n,o){const hp=t.hp,shield=(t.shields||[]).reduce((s,x)=>s+x.value,0),out=damage.call(this,a,t,n,o),delta=Math.max(0,hp-t.hp)+Math.max(0,shield-(t.shields||[]).reduce((s,x)=>s+x.value,0));if(a.side==='ALLY'&&t.side==='ENEMY'){meter[a.source===PLAYER?'ownDamage':'allyDamage']+=delta;if(o?.card===IQ)meter.jointDamage+=delta;}return out;};const heal=r.heal;r.heal=function(...args){const amount=heal.apply(this,args);meter.heal+=amount;return amount;};const finish=r.finishBattle;r.finishBattle=function(win){const b=this.s.runtime;if(b){r._auditLast={actors:cp(b.actors),rounds:b.round,win,log:cp(b.log)};}return finish.call(this,win);};return meter;}
function shortest(r,from,to){const q=[{map:from,edges:[]}],seen=new Set([from]);while(q.length){const a=q.shift();if(a.map===to)return a.edges;for(const e of r.rows('47_MAP_EDGE_DB').filter(e=>e[1]===a.map&&e[8]==='Y'&&e[11]==='ACTIVE'&&(!e[6]||e[6]==='FLAG_TRUE'&&[true,'TRUE'].includes(r.s.flags[e[7]])))){if(!seen.has(e[2])){seen.add(e[2]);q.push({map:e[2],edges:[...a.edges,e[0]]});}}}return null;}
function recover(env,r,{finishAtInn=false}={}){
 const start=r.s.global.CURRENT_MAP_ID,options=r.placeCatalog().filter(p=>p.kind==='FACILITY').flatMap(p=>r.rows('19_SHOP_STOCK_DB').filter(s=>s[1]===p.merchant&&s[3]==='SERVICE_INN_REST_8H').flatMap(s=>p.maps.map(map=>({map,place:p.id,stock:s[0],row:s,out:shortest(r,start,map),back:shortest(r,map,start)})))).filter(x=>x.out&&x.back).sort((a,b)=>a.out.length+a.back.length-b.out.length-b.back.length||r.stockPrice(a.row)-r.stockPrice(b.row)),inn=options[0];
 if(!inn)return{failed:true,reason:'NO_INN',before:hp(r)};
 const before=hp(r),events=[];let seconds=finishAtInn?0:10;
 for(const dir of ['out','back']){
  if(dir==='back'){
   r.action('PLACE_ENTER',{place:inn.place,mode:'SHOP'});
   const quote=r.innRecoveryQuote(inn.row),needed=hp(r).some(a=>a.hp<a.maxHp);
   if(!finishAtInn||needed){const receipt=r.action('BUY',{stock:inn.stock,quantity:1});events.push({type:'INN',quote:cp(quote),cost:receipt.result.cost});if(finishAtInn)seconds+=10;}
   else events.push({type:'INN_NOT_NEEDED',quote:cp(quote),cost:0});
   if(finishAtInn)return{failed:false,before,after:hp(r),stock:inn.stock,lodgingMora:events.find(x=>/^INN/.test(x.type)).cost,events,seconds,endpoint:{map:r.s.global.CURRENT_MAP_ID,place:inn.place,stock:inn.stock,allFullHp:hp(r).every(a=>a.hp===a.maxHp),prng:r.s.global.PRNG_STATE,worldDay:r.s.global.WORLD_DAY,worldTime:r.s.global.WORLD_TIME},outEdges:inn.out};
  }
  for(const edge of inn[dir]){r.action('MOVE',{edge});seconds+=4;if(r.s.runtime){const prior={...r._protagonistMeter},result=play(r),battleSeconds=(r._protagonistMeter.ms-prior.ms)/1000+3*(r._protagonistMeter.inputs-prior.inputs)+6+Number(result.defeatPenalty?.seconds||0);seconds+=battleSeconds;events.push({type:'TRAVEL_COMBAT',victory:!!result.victory,seconds:battleSeconds});if(!result.victory)return{failed:true,reason:'TRAVEL_DEFEAT',before,after:hp(r),events,seconds};}}
 }
 return{failed:false,before,after:hp(r),stock:inn.stock,lodgingMora:events.find(x=>x.type==='INN').cost,events,seconds};
}
function campaign(env,spec,{runs=1,policy='E_FIRST',finalRecovery=false,finishAtInn=false}={}){const domain=spec.domain&&env.api.growthV01522.domains[spec.domain.split(':')[0]],r=setup(env,{...spec,map:spec.map||domain?.map}),meter=observe(env,r),result={...spec,policy,fixtureHp:hp(r),equipment:cp(r.s.inventory.filter(x=>x.equipped).map(x=>({owner:x.owner,equip:x.equip,enhance:x.enhance}))),talents:cp(r.s.talents),battles:[],recoveries:[],wins:0,losses:0,seconds:0,lodgingMora:0};
 for(let i=0;i<runs;i++){if(hp(r).some(a=>a.hp<=0||a.hp/a.maxHp<.5)){const rest=recover(env,r);result.recoveries.push(rest);result.seconds+=rest.seconds||0;result.lodgingMora+=rest.lodgingMora||0;if(rest.failed){result.stopReason=rest.reason;break;}}const before=hp(r),prior={...meter};if(spec.domain)r.action('DOMAIN_START',{domain:spec.domain,element:spec.element||'NEUTRAL'});else r.startBattle(spec.group,spec.origin||'RANDOM');const initial=cp(r.s.runtime.actors.map(a=>({source:a.source,side:a.side,level:a.level,hp:a.hp,maxHp:a.maxHp,atk:a.atk,def:a.def})));const reward=play(r,{policy}),last=r._auditLast,seconds=(meter.ms-prior.ms)/1000+3*(meter.inputs-prior.inputs)+6+Number(reward.defeatPenalty?.seconds||0);const row={before,after:hp(r),initial,victory:!!reward.victory,rounds:reward.rounds,seconds,ownDamage:meter.ownDamage-prior.ownDamage,allyDamage:meter.allyDamage-prior.allyDamage,jointDamage:meter.jointDamage-prior.jointDamage,healing:meter.heal-prior.heal,playerInputs:meter.inputs-prior.inputs,hpBeforeReward:last?.actors.filter(a=>a.side==='ALLY').map(a=>({owner:a.source,hp:a.hp,maxHp:a.maxHp})),jointParticipants:last?.log.filter(x=>x.participants).map(x=>x.participants),casts:last?.log.filter(x=>x.protagonistSkill||x.participants).map(x=>({card:x.card,round:x.round,bonus:x.jointBonusPct,exposed:x.exposedPct})),failure:reward.defeatPenalty||null};result.battles.push(row);result.seconds+=seconds;result.wins+=row.victory?1:0;result.losses+=row.victory?0:1;if(!row.victory){result.stopReason='DEFEAT';break;}if(r.s.log.length>30)r.s.log=r.s.log.slice(-30);}
 if(finishAtInn){const rest=recover(env,r,{finishAtInn:true});result.recoveries.push(rest);result.seconds+=rest.seconds||0;result.lodgingMora+=rest.lodgingMora||0;result.endpoint=rest.endpoint;if(rest.failed)result.stopReason=rest.reason;else if(!rest.endpoint.allFullHp)result.stopReason='INN_NOT_FULL';}
 else if(finalRecovery&&hp(r).some(a=>a.hp<a.maxHp)){const rest=recover(env,r);result.recoveries.push(rest);result.seconds+=rest.seconds||0;result.lodgingMora+=rest.lodgingMora||0;if(rest.failed)result.stopReason=rest.reason;}result.finalHp=hp(r);result.finalHpRatio=result.finalHp.reduce((s,a)=>s+a.hp,0)/result.finalHp.reduce((s,a)=>s+a.maxHp,0);result.rounds=result.battles.reduce((s,a)=>s+a.rounds,0);result.ownDamage=result.battles.reduce((s,a)=>s+a.ownDamage,0);result.allyDamage=result.battles.reduce((s,a)=>s+a.allyDamage,0);result.jointDamage=result.battles.reduce((s,a)=>s+a.jointDamage,0);result.healing=result.battles.reduce((s,a)=>s+a.healing,0);result.stopReason??='RUNS_COMPLETED';return result;}
const TEAMS={solo:[],amber:['MOND_AMBER'],opening3:['MOND_AMBER','MOND_KAEYA'],story4:['MOND_AMBER','MOND_KAEYA','MOND_LISA'],support4:['MOND_FISCHL','LIYUE_XIANGLING','MOND_BARBARA'],vape4:['LIYUE_XIANGLING','LIYUE_XINGQIU','MOND_BENNETT'],freeze4:['MOND_KAEYA','LIYUE_XINGQIU','MOND_DIONA'],standard5:['MOND_DILUC','LIYUE_XINGQIU','MOND_JEAN'],limited5:['LIYUE_HUTAO','LIYUE_YELAN','LIYUE_ZHONGLI']};
function main(){const arg=k=>{const i=process.argv.indexOf(k);return i<0?undefined:process.argv[i+1];},env=load(arg('--root')||DEFAULT_ROOT,arg('--candidate')?JSON.parse(arg('--candidate')):null),out=arg('--out')||'/tmp/crpg_v01618/protagonist_summary.json',cases=arg('--cases')?JSON.parse(fs.readFileSync(arg('--cases'))):[...['story4','support4','vape4','freeze4','standard5','limited5'].flatMap(name=>[30,60].map(level=>({name,team:TEAMS[name],level,domain:level===30?'TAISHAN_MANSION:30':'TAISHAN_MANSION:60'}))),...['solo','amber','opening3','story4'].map(name=>({name,team:TEAMS[name],level:3,group:'EG_MOND_HILI_PATROL',map:'MAP_MOND_PLAINS',gear:'starter',enhance:0,talent:1}))],seeds=(arg('--seeds')||'717,4242,9031').split(',').map(Number),routes=(arg('--routes')||'ROUTE_TRAVELER,ROUTE_ISEKAI').split(','),data={runtimeRoot:env.root,fingerprint:env.fingerprint,candidate:env.candidate,assumptions:{enemy:'Native fixed four-person rule; no enemy stat/action edits.',fixtures:'Owned allies, equal levels/legal phase and talents, equal weapon/armor/accessory enhancement; no constellations or artifacts. One initial full HP only.',actions:'Native public COMBAT actions. Traveler Q then hold E; Isekai E marks a fresh highest-HP target then Q; alternate Q-first can be requested.',recovery:'Native MOVE with incidental battles and BUY lodging at HP below 50% or death; HP/PRNG carried between all fights.',time:'Displayed 2x uses internal rate 1 and presentationMs / 1000; 3 seconds per combat input, 6 seconds receipt/reentry, 4 seconds per move, 10 seconds lodging input/processing.',limits:'Human/network latency and acquisition grind excluded. Starting money is diagnostic funding, not income. Exact matchup outcomes are sampled, not a promise every composition wins.'},rows:[],errors:[]};if(process.argv.includes('--finish-at-inn'))data.assumptions.endpoint='After the six native main fights, MOVE to the same selected legal inn and BUY only if HP is missing; stop there with actual full HP, without return travel. Intermediate recovery and input/time policy are unchanged.';fs.mkdirSync(path.dirname(out),{recursive:true});for(const spec of cases)for(const route of routes)for(const seed of seeds){try{const row=campaign(env,{...spec,route,seed},{runs:Number(arg('--runs')||1),policy:arg('--policy')||'E_FIRST',finalRecovery:process.argv.includes('--final-recovery'),finishAtInn:process.argv.includes('--finish-at-inn')});data.rows.push(row);console.log(JSON.stringify({name:spec.name,level:spec.level,route,seed,wins:row.wins,rounds:row.rounds,seconds:Math.round(row.seconds),hp:+row.finalHpRatio.toFixed(3),mora:row.lodgingMora}));}catch(e){data.errors.push({spec,route,seed,code:e.code||e.name,message:e.message});console.log(JSON.stringify(data.errors.at(-1)));}fs.writeFileSync(out,JSON.stringify(data,null,2)+'\n');}return data;}
if(require.main===module)main();module.exports={load,setup,observe,play,hp,recover,campaign,TEAMS};
