'use strict';
// --native checks current product without patches; detached candidates require frozen 0.16.24 signatures. Neither edits product source.
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto'),assert=require('assert/strict');
const arg=k=>{const i=process.argv.indexOf(k);return i<0?undefined:process.argv[i+1];},ROOT=path.resolve(arg('--root')||path.join(__dirname,'..')),OUT=path.resolve(arg('--out')||path.join(ROOT,'docs/data/balance_v01625/healing/ordinary_candidates')),H=require(path.join(ROOT,'tools/audit_protagonist_v01618.cjs')),cp=x=>JSON.parse(JSON.stringify(x));fs.mkdirSync(OUT,{recursive:true});
const selected=process.argv.includes('--native'),variants=selected?[{id:'CURRENT_PRODUCT'}]:[{id:'BASELINE_V01624'},{id:'HP15_JADE40_JEAN75_EARLY',qHp:.15,jade:.40,jean:.75,early:true},{id:'HP12_JADE40_JEAN75_EARLY',qHp:.12,jade:.40,jean:.75,early:true},{id:'HP10_JADE325_JEAN60_EARLY',qHp:.10,jade:.325,jean:.60,early:true}];
const index=fs.readFileSync(ROOT+'/source/index.html','utf8'),files=[...index.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)].map(m=>'source/'+m[1]);files.push('source/index.html','source/presentation.js','content/db.json','tools/audit_protagonist_v01618.cjs');const hash=()=>Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(ROOT+'/'+f)).digest('hex')])),before=hash();
function replaceOne(s,from,to,file){assert.equal(s.split(from).length-1,1,file+': candidate requires exact 0.16.24 signature');return s.replace(from,to);}
function load(v){if(!v.qHp)return H.load(ROOT);const c=vm.createContext({console,Date,setTimeout,clearTimeout}),h=crypto.createHash('sha256'),patches=[];for(const[,file]of index.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)){let s=fs.readFileSync(ROOT+'/source/'+file,'utf8');if(file==='runtime_combat.js'){s=replaceOne(s,"source==='LIYUE_ZHONGLI_E'?.65:1","source==='LIYUE_ZHONGLI_E'?"+v.jade+':1',file);patches.push({file,kind:'Jade core absorption factor',from:.65,to:v.jade});}if(file==='runtime_liyue_cards.js'){s=replaceOne(s,"case'ZHONGLI_Q':for(const t of many(.8,'GEO',4,{rawAdd:hp*.25}))","case'ZHONGLI_Q':for(const t of many(.8,'GEO',4,{rawAdd:hp*"+v.qHp+'}))',file);patches.push({file,kind:'Zhongli Q HP raw addition only; ATK .8 stays',from:.25,to:v.qHp});if(v.early){s=replaceOne(s,'n*=[0,0,.5,.7,.9][Math.min(5,b.round)]??1;','n*=[1,.5,.7,.85,.95][Math.min(5,b.round)]??1;',file);patches.push({file,kind:'Zhongli external incoming factor R1/R2/R3/R4/R5+',from:[0,.5,.7,.9,1],to:[.5,.7,.85,.95,1]});}}h.update(file);h.update(s);vm.runInContext(s,c,{filename:file});}vm.runInContext(fs.readFileSync(ROOT+'/source/presentation.js','utf8'),c);const raw=fs.readFileSync(ROOT+'/content/db.json');h.update(raw);return{c,db:JSON.parse(raw),R:c.CRPGRuntime.Runtime,api:c.CRPGRuntime,root:ROOT,fingerprint:h.digest('hex'),patches};}
const environments=Object.fromEntries(variants.map(v=>[v.id,load(v)]));
const report={scope:'Public ordinary EXP/TALENT starts with native player/companion combat and two-fight HP carryover. Detached VM exact candidate factors only; product files untouched. No boss tuning, healing rhythm fix, new gimmick or economy changes injected.',assumptions:{team:['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN'],investment:'TravelerC0 and 5starC0, same level/legal phase/max base talents, craft+10/cap10; no artifacts/exclusive/boss equipment.',carryover:'One initial full HP after declared fixture; no food/inn/free recovery between two native fights. A fight2 KO is a carryover-recovery signal, not automatically a candidate rejection. First-fight defeat is separately reported.',actions:'H.play native public Q/E hold/basic, companion existing AI; seed717. Input/presentation time is measured policy time, not human/network time.',numbers:'Q HP term only is patched, ATK .8 retained. Jade core factor is patched (.65 baseline). Jean immediate and stored field coefficients use official card healingMultiplier. Early immunity factors are patched. Text in detached VM is not a shipped description; product descriptions must be reconciled in final source.'},variants:variants.map(v=>({...v,fingerprint:environments[v.id].fingerprint,patches:environments[v.id].patches||[]})),rows:[],errors:[]};
if(selected){report.scope='Current product native EXP/TALENT starts, two-fight HP carryover; no source/profile candidate edits. Wound quotes use unchanged existing inn formula.';report.assumptions.numbers='Current source character budget, ownership fixes and native AI; no injected multipliers.';}
const team=report.assumptions.team;
for(const level of[20,40,60])for(const kind of['EXP','TALENT'])for(const v of variants){const env=environments[v.id],A=env.api.adminBalance,sites=env.api.growthV01522.domains,key=Object.keys(sites).find(k=>sites[k].kind===kind&&sites[k].levels.includes(level));try{const seed=H.setup(env,{level,team,route:'ROUTE_TRAVELER',seed:717,map:sites[key].map,enhance:10,talent:10});for(const i of seed.s.inventory.filter(i=>i.equip)){i.enhancementCap=10;if(!seed.enhancementHasGain(i))i.enhance=0;}seed.recalculate();seed.s.global.PLAYER_HP_CURRENT=seed.s.global.PLAYER_HP_MAX;for(const id of team)seed.s.chars[id].hp=seed.character(id).maxHp;const profile={revision:v.jean?1:0,config:A.emptyConfig()};if(v.jean)profile.config.cards.MOND_JEAN_Q={healingMultiplier:v.jean};const r=A.createRuntime(env.db,seed.s,profile),meter=H.observe(env,r),row={level,kind,key,variant:v.id,initial:cp(H.hp(r)),battles:[]};for(let n=0;n<2;n++){const beforeHp=H.hp(r),prior={...meter};r.action('DOMAIN_START',{domain:key+':'+level});const enemyStart=cp(r.s.runtime.actors.filter(a=>a.side==='ENEMY').map(a=>({source:a.source,level:a.level,hp:a.hp,atk:a.atk,def:a.def}))),result=H.play(r),last=r._auditLast;row.battles.push({n:n+1,victory:!!result.victory,rounds:result.rounds,stalled:!!result.stalled,ko:last?.actors.filter(a=>a.side==='ALLY'&&a.hp<=0).map(a=>a.source)||[],beforeHp,afterHp:H.hp(r),enemyStart,healing:meter.heal-prior.heal,seconds:(meter.ms-prior.ms)/1000+3*(meter.inputs-prior.inputs)+6});if(!result.victory)break;}row.finalHp=H.hp(r);row.hpRatio=row.finalHp.reduce((n,a)=>n+a.hp,0)/row.finalHp.reduce((n,a)=>n+a.maxHp,0);const stock=r.rows('19_SHOP_STOCK_DB').find(s=>s[3]==='SERVICE_INN_REST_8H');row.innQuote=cp(r.innRecoveryQuote(stock));row.healing=meter.heal;report.rows.push(row);console.log(JSON.stringify({level,kind,variant:v.id,battles:row.battles.map(b=>({victory:b.victory,rounds:b.rounds,ko:b.ko})),hp:row.hpRatio,inn:row.innQuote.cost}));}catch(e){report.errors.push({level,kind,variant:v.id,error:e.stack});console.log(report.errors.at(-1));}fs.writeFileSync(OUT+'/native.json',JSON.stringify(report,null,2)+'\n');}
report.inputSHA256=before;const after=hash();report.inputDrift=Object.keys(before).filter(f=>before[f]!==after[f]);report.summary={conditions:report.rows.length,fights:report.rows.reduce((n,r)=>n+r.battles.length,0),firstFightDefeats:report.rows.filter(r=>!r.battles[0]?.victory).length,carryoverDefeats:report.rows.filter(r=>r.battles[1]&&!r.battles[1].victory).length,koEvents:report.rows.reduce((n,r)=>n+r.battles.reduce((n,b)=>n+b.ko.length,0),0),errors:report.errors.length,drift:report.inputDrift};fs.writeFileSync(OUT+'/native.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.summary));if(report.errors.length||report.inputDrift.length)process.exitCode=1;
