'use strict';
// Native repeated material domains, with carried HP and public inn recovery.
const fs=require('node:fs'),path=require('node:path'),H=require('./audit_protagonist_v01618.cjs');
const args=process.argv.slice(2),arg=k=>args.includes(k)?args[args.indexOf(k)+1]:null;
const root=path.resolve(arg('--root')||path.resolve(__dirname,'..')),env=H.load(root),out=arg('--out')||'/tmp/crpg_v01627_ordinary/final_material_campaigns.json',rows=[],errors=[];
const data={schema:1,root,fingerprint:env.fingerprint,assumptions:'Native public DOMAIN_START/COMBAT/MOVE/BUY six-run campaigns. Four declared owned C0 actors at Lv60 with ordinary crafted +6, legal talents6, no artifacts/exclusive/boss equipment. Initial full HP and funded wallet only. No materials/food or healing granted between fights. Native inn round-trip occurs if any member is below50% HP or KO. Stage55/60 ASCENSION neutral and TALENT. Inn travel retains strengthened actual map enemies and movement encounters. Time is displayed2x native frames plus3s/player input,6s/receipt,4s/move,10s/inn. Initial destination travel, material income acquisition and human/network latency excluded. This reports representative three-seed outcomes, not all elemental counter-compositions.',rows,errors};
const save=()=>{fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(data,null,2)+'\n');};
for(const kind of ['TALENT','ASCENSION'])for(const stage of [55,60])for(const[name,team]of Object.entries({story4:H.TEAMS.story4,heal5:['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN']}))for(const seed of [717,4242,9031]){try{const domain=(kind==='TALENT'?'TAISHAN_MANSION':'LIANSHAN_FORMULA')+':'+stage,row=H.campaign(env,{name,level:60,team,talent:6,route:'ROUTE_ISEKAI',seed,domain,element:'NEUTRAL'},{runs:6,finishAtInn:args.includes('--finish-at-inn')}),q=H.setup(env,{level:60,team,talent:6,route:'ROUTE_ISEKAI',seed,map:env.api.growthV01522.domains[domain.split(':')[0]].map});q.action('DOMAIN_START',{domain,element:'NEUTRAL'});const reward=q.growthDomainRewards(q.s.runtime.growthDomain,'NEUTRAL');row.kind=kind;row.stage=stage;row.materialEach=Object.values(reward.items).reduce((n,x)=>n+x,0);row.materialPerMinute=row.materialEach*row.wins/row.seconds*60;rows.push(row);console.log(JSON.stringify({kind,stage,name,seed,w:row.wins,l:row.losses,s:row.seconds,mora:row.lodgingMora,rest:row.recoveries.length,each:row.materialEach,perMinute:row.materialPerMinute}));}catch(e){errors.push({kind,stage,name,seed,code:e.code||e.name,message:e.message});}save();}
data.counts={conditions:rows.length,battles:rows.reduce((n,r)=>n+r.battles.length,0),wins:rows.reduce((n,r)=>n+r.wins,0),losses:rows.reduce((n,r)=>n+r.losses,0),errors:errors.length};save();
