'use strict';
// Native fixed-four-party boss comparisons. Diagnostic ownership/gear only; no battle HP reset.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),H=require('./audit_protagonist_v01618.cjs'),cp=x=>x===undefined?null:JSON.parse(JSON.stringify(x));
const opt=k=>{const i=process.argv.indexOf(k);return i<0?null:process.argv[i+1];};
const mode=opt('--mode')||'current',baseline=opt('--baseline')||'/tmp/crpg_v01619_baseline',out=opt('--out')||path.join(ROOT,'docs/data/boss_balance_v01619/current.json');
function load(){const c=vm.createContext({console,Date,setTimeout,clearTimeout}),h=crypto.createHash('sha256'),sourceHashes={};const src=mode==='baseline'||mode==='floor-candidate'?baseline:ROOT;
 const index=fs.readFileSync(src+'/source/index.html','utf8');for(const [,f]of index.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)){let text=fs.readFileSync(src+'/source/'+f,'utf8');
  if(mode==='floor-candidate'&&f==='runtime_growth_v01522.js')text=text.replace('a.hp=a.maxHp=Math.round(hp);a.atk=',"const authoredBossAtk=['FB_ANEMO_HYPOSTASIS','FB_ELECTRO_HYPOSTASIS','FB_CRYO_REGISVINE'].includes(a.source)?a.atk:0;a.hp=a.maxHp=Math.round(hp);a.atk=").replace('a.def=Math.round([20,28,35,42][i]*adCurve(level));','a.atk=Math.max(a.atk,authoredBossAtk);a.def=Math.round([20,28,35,42][i]*adCurve(level));');
  sourceHashes['source/'+f]=crypto.createHash('sha256').update(text).digest('hex');h.update(f);h.update(text);vm.runInContext(text,c,{filename:f});}
 const presentation=fs.readFileSync(src+'/source/presentation.js','utf8');sourceHashes['source/presentation.js']=crypto.createHash('sha256').update(presentation).digest('hex');vm.runInContext(presentation,c);const raw=fs.readFileSync(baseline+'/content/db.json');sourceHashes['content/db.json']=crypto.createHash('sha256').update(raw).digest('hex');h.update(raw);return{c,db:JSON.parse(raw),R:c.CRPGRuntime.Runtime,api:c.CRPGRuntime,root:src,fingerprint:h.digest('hex'),sourceHashes};}
const env=load(),FB=env.api.fieldBosses;
const teams={FOUR_ATTACK:['LIYUE_XIANGLING','MOND_KAEYA','MOND_FISCHL'],FOUR_HEAL:['LIYUE_XIANGLING','MOND_KAEYA','MOND_BARBARA'],FOUR_C6_HEAL:['LIYUE_XIANGLING','MOND_KAEYA','MOND_BARBARA'],FIVE_DEFENSIVE:['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN']};
const prepared={FB_ANEMO_HYPOSTASIS:['LIYUE_XIANGLING','MOND_FISCHL','MOND_BARBARA'],FB_ELECTRO_HYPOSTASIS:['LIYUE_XIANGLING','MOND_KAEYA','MOND_BARBARA'],FB_CRYO_REGISVINE:['LIYUE_XIANGLING','MOND_AMBER','MOND_BARBARA'],FB_CRYO_HYPOSTASIS:['LIYUE_XIANGLING','LIYUE_XINGQIU','MOND_BARBARA'],FB_GEO_HYPOSTASIS:['MOND_NOELLE','LIYUE_NINGGUANG','MOND_BARBARA'],FB_PYRO_REGISVINE:['LIYUE_XINGQIU','MOND_KAEYA','MOND_BARBARA'],FB_OCEANID:['MOND_FISCHL','MOND_KAEYA','MOND_BARBARA'],FB_PRIMO_GEOVISHAP:['MOND_NOELLE','LIYUE_XINGQIU','MOND_FISCHL'],FB_RUIN_SERPENT:['MOND_NOELLE','LIYUE_XIANGLING','MOND_FISCHL']};
let cases;if(opt('--cases'))cases=JSON.parse(fs.readFileSync(opt('--cases')));else{cases=[];for(const boss of ['FB_ANEMO_HYPOSTASIS','FB_ELECTRO_HYPOSTASIS','FB_CRYO_REGISVINE'])for(const team of Object.keys(teams))for(const delta of [0,-5])for(const seed of [717,925,4242])cases.push({boss,team,level:FB.bosses[boss].level+delta,seed});}
const data={version:'0.16.19',mode,fingerprint:env.fingerprint,sourceHashes:env.sourceHashes,assumptions:{party:'Fixed four-person; protagonist plus three companions, equal initial levels/legal ascensions, native craft weapon/leather armor/healer brooch. Early +3; Lv30+ +6. Base talents65%cap, optional legal cap. FOUR_C6_HEAL only companions C6; protagonist C0.',combat:'Public PLACE_ENTER/BOSS_ROUTE and native COMBAT actions, native enemy states, HP/XP/RNG persist across requested runs; one initial full-HP only. No food/inn midrun. Final HP report separates win/loss.',limits:'Representative declared ownership fixtures, not natural acquisition or every composition; quantities are per condition.'},rows:[],errors:[]};
for(const spec of cases){try{const team=spec.ids||teams[spec.team]||prepared[spec.boss],level=spec.level??FB.bosses[spec.boss].level,enhance=spec.enhance??(level>=30?6:3),r=H.setup(env,{level,team,route:'ROUTE_TRAVELER',seed:spec.seed,map:FB.bosses[spec.boss].map,enhance,talent:spec.talent});if(spec.team==='FOUR_C6_HEAL'||spec.constellation===6)for(const id of team){r.giveItem('STELLA_'+id,6);for(let n=0;n<6;n++)r.action('CONSTELLATION_UNLOCK',{char:id});}
 const meter=H.observe(env,r),row={...spec,ids:team,level,enhance,initialHp:H.hp(r),talents:cp(r.s.talents),effectiveTalents:Object.fromEntries(['PLAYER_CUSTOM',...team].map(id=>[id,cp(r.talentLevels(id))])),constellations:cp(r.s.constellations),battles:[],wins:0,losses:0};
 for(let n=0;n<(spec.runs||1);n++){const route=FB.route(spec.boss);r.action('PLACE_ENTER',{place:'BOSS:'+route,mode:'BOSS'});r.action('BOSS_ROUTE',{route,entry:'DIRECT'});const native=r.s.runtime,boss=native.actors.find(x=>x.source===spec.boss);const initial={hp:boss.hp,maxHp:boss.maxHp,atk:boss.atk,def:boss.def,level:boss.level,fb:cp(boss.fb),fieldBoss:cp(native.fieldBoss)};const receipt=H.play(r),last=r._auditLast;row.battles.push({number:n+1,victory:!!receipt.victory,rounds:receipt.rounds,initial,coreHits:last?.log.filter(x=>x.text?.startsWith('냉기 핵에 금이 갔다')).length||0,coreBreaks:last?.log.filter(x=>x.card==='FB_CORE_BROKEN').length||0,revives:last?.log.filter(x=>x.card==='FB_REVIVED').length||0,actualKo:last?.actors.filter(x=>x.side==='ALLY'&&x.hp<=0).map(x=>x.source)||[],beforeRewardHp:last?.actors.filter(x=>x.side==='ALLY').map(x=>({source:x.source,level:x.level,hp:x.hp,maxHp:x.maxHp}))||[],after:H.hp(r),receipt});if(receipt.victory)row.wins++;else{row.losses++;break;}}
 row.finalHp=H.hp(r);row.finalHpRatio=row.finalHp.reduce((s,x)=>s+x.hp,0)/row.finalHp.reduce((s,x)=>s+x.maxHp,0);row.meter=meter;data.rows.push(row);console.log(JSON.stringify({boss:spec.boss,team:spec.team,level,seed:spec.seed,wins:row.wins,losses:row.losses,rounds:row.battles.map(x=>x.rounds),hp:+row.finalHpRatio.toFixed(4),ko:row.battles.map(x=>x.actualKo.length)}));
 }catch(e){data.errors.push({...spec,error:e.stack,code:e.code||e.name});console.log(JSON.stringify(data.errors.at(-1)));}}
data.summary={conditions:data.rows.length,firstWins:data.rows.filter(x=>x.battles[0]?.victory).length,complete:data.rows.filter(x=>x.wins===(x.runs||1)).length,fights:data.rows.reduce((s,x)=>s+x.battles.length,0),wins:data.rows.reduce((s,x)=>s+x.wins,0),losses:data.rows.reduce((s,x)=>s+x.losses,0),errors:data.errors.length};fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(data,null,2)+'\n');console.log(JSON.stringify({out,...data.summary}));if(data.errors.length)process.exitCode=1;
