'use strict';
// Native combat and incoming-HP accounting; candidate multipliers, if supplied,
// live only in this VM. Product source, enemy cards and authored DB are untouched.
const fs=require('node:fs'),path=require('node:path'),H=require('./audit_protagonist_v01618.cjs');
const args=process.argv.slice(2),arg=k=>args.includes(k)?args[args.indexOf(k)+1]:null,root=path.resolve(arg('--root')||path.resolve(__dirname,'..')),out=arg('--out')||'/tmp/crpg_v01627_ordinary/native.json',env=H.load(root),profile=arg('--profile')?JSON.parse(fs.readFileSync(arg('--profile'))):null;
const P=env.R.prototype,metrics=new WeakMap(),cp=x=>JSON.parse(JSON.stringify(x));
function metric(r,b){if(!b)return null;if(!metrics.has(r))metrics.set(r,{hpDamage:0,shieldDamage:0,incomingPackets:0,minPartyHpRatio:1,minMemberHpRatio:1,members:{},minKo:0,firstHp:[]});const m=metrics.get(r),ids=new Set(r.s.party.filter(x=>x.active).map(x=>x.source)),allies=b.actors.filter(x=>x.side==='ALLY'&&ids.has(x.source));if(!m.firstHp.length)m.firstHp=allies.map(a=>({owner:a.source,hp:a.hp,maxHp:a.maxHp}));const total=allies.reduce((n,a)=>n+Math.max(0,a.hp),0),max=allies.reduce((n,a)=>n+a.maxHp,0);if(max)m.minPartyHpRatio=Math.min(m.minPartyHpRatio,total/max);for(const a of allies){m.minMemberHpRatio=Math.min(m.minMemberHpRatio,a.hp/a.maxHp);m.members[a.source]=Math.min(m.members[a.source]??1,a.hp/a.maxHp);}m.minKo=Math.max(m.minKo,allies.filter(a=>a.hp<=0).length);return m;}
const oldDamage=P.applyDamage;P.applyDamage=function(a,t,n,o){const b=this.s.runtime,m=metric(this,b),hp=t.hp,sh=(t.shields||[]).reduce((n,s)=>n+s.value,0),out=oldDamage.call(this,a,t,n,o);if(m&&t.side==='ALLY'&&this.s.party.some(p=>p.active&&p.source===t.source)){const lost=Math.max(0,hp-t.hp),shield=Math.max(0,sh-(t.shields||[]).reduce((n,s)=>n+s.value,0));m.hpDamage+=lost;m.shieldDamage+=shield;m.incomingPackets++;metric(this,b);}return out;};
const oldHeal=P.heal;P.heal=function(...args){metric(this,this.s.runtime);const out=oldHeal.apply(this,args);metric(this,this.s.runtime);return out;};
if(profile){const old=P.tuneGrowthEnemy;P.tuneGrowthEnemy=function(a,b,l){const scaled=a.growthScaled;old.call(this,a,b,l);if(scaled||a.grade==='보스'||a.fieldStructure)return;const p=profile[this._growthDomain?.kind]||profile.FIELD||profile,t=(()=>{const pts=[[20,0],[30,.25],[40,.55],[50,.8],[60,1]];if(l<=20)return 0;for(let i=1;i<pts.length;i++)if(l<=pts[i][0])return pts[i-1][1]+(pts[i][1]-pts[i-1][1])*(l-pts[i-1][0])/(pts[i][0]-pts[i-1][0]);return 1;})(),m=k=>1+(p[k]-1)*t,prior=a.maxHp;a.hp=a.maxHp=Math.round(a.maxHp*m('hp'));a.atk=Math.round(a.atk*m('atk'));a.def=Math.round(a.def*m('def'));for(const s of a.shields||[]){s.value=Math.round(s.value*a.maxHp/prior);if(s.initialValue)s.initialValue=Math.round(s.initialValue*a.maxHp/prior);}};}
const teams={story4:H.TEAMS.story4,heal4:H.TEAMS.support4,heal5:['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN']},levels=(arg('--levels')||'30,35,40,50,60').split(',').map(Number),elements=(arg('--elements')||'NEUTRAL').split(','),teamNames=(arg('--teams')||'story4,heal4,heal5').split(','),seeds=(arg('--seeds')||'717,4242,9031').split(',').map(Number),kinds=(arg('--kinds')||'ASCENSION,TALENT,EXP').split(','),rows=[],errors=[],data={schema:1,sourceRoot:root,fingerprint:env.fingerprint,profile,assumptions:'Four owned C0 members; ordinary crafted +6 Lv30+, +3 below30, no artifacts/exclusive/boss equipment, native legal phase and base talents. Mid=max(1,floor(cap*.65)); cap=max legal. Only initial full HP supplied. Actual native COMBAT and companion AI, rolls/heal/HP/KO unchanged. Displayed2x presentation/1000 +3s/player input +6s receipt/re-entry. No travel/acquisition/natural ownership in one-fight sample. Pre-reward and in-fight HP/KO reported separately from native 10% exit recovery.',rows,errors};fs.mkdirSync(path.dirname(out),{recursive:true});const save=()=>fs.writeFileSync(out,JSON.stringify(data,null,2)+'\n');
for(const level of levels)for(const[key,d]of Object.entries(env.api.growthV01522.domains))if(d.levels?.includes(level)&&kinds.includes(d.kind))for(const teamName of teamNames)for(const seed of seeds)for(const element of d.kind==='ASCENSION'?elements:['NEUTRAL'])try{const r=H.setup(env,{level:Number(arg('--actor-level')||level),team:teams[teamName],route:'ROUTE_ISEKAI',seed,map:d.map,...(arg('--talents')==='cap'?{talent:10}:{})}),meter=H.observe(env,r);r.action('DOMAIN_START',{domain:key+':'+level,element});const initial=cp(r.s.runtime.actors),expected=cp(r.growthDomainRewards(r.s.runtime.growthDomain,element)),result=H.play(r),last=r._auditLast,pre=last.actors.filter(a=>a.side==='ALLY'&&r.s.party.some(p=>p.active&&p.source===a.source)),row={domain:key+':'+level,kind:d.kind,level,team:teamName,seed,element,preparation:{gear:cp(r.s.inventory.filter(x=>x.equipped).map(x=>({owner:x.owner,equip:x.equip,enhance:x.enhance}))),talents:cp(r.s.talents),phases:cp(r.s.ascensions)},initial:initial.map(a=>({source:a.source,side:a.side,level:a.level,hp:a.hp,maxHp:a.maxHp,atk:a.atk,def:a.def})),result:cp(result),rounds:last.rounds,seconds:meter.ms/1000+meter.inputs*3+6,playerInputs:meter.inputs,ownDamage:meter.ownDamage,allyDamage:meter.allyDamage,healing:meter.heal,incoming:cp(metrics.get(r)||{}),preRewardHp:pre.map(a=>({owner:a.source,hp:a.hp,maxHp:a.maxHp})),preRewardHpRatio:pre.reduce((n,a)=>n+Math.max(0,a.hp),0)/pre.reduce((n,a)=>n+a.maxHp,0),preRewardKO:pre.filter(a=>a.hp<=0).map(a=>a.source),after:H.hp(r),innQuote:cp(r.innRecoveryQuote(r.row('19_SHOP_STOCK_DB','STK_INN_MOND'))),expectedRewards:expected};rows.push(row);console.log(JSON.stringify({domain:row.domain,team:teamName,seed,element,W:!!result.victory,R:row.rounds,sec:row.seconds,hp:row.preRewardHpRatio,incoming:row.incoming.hpDamage,minMemberHp:row.incoming.minMemberHpRatio,minPartyHp:row.incoming.minPartyHpRatio,ko:row.preRewardKO,lodge:row.innQuote.cost}));save();}catch(e){errors.push({level,key,teamName,seed,element,error:e.message,code:e.code||e.name,stack:e.stack});console.error(JSON.stringify(errors.at(-1)));save();}
data.counts={conditions:rows.length,wins:rows.filter(r=>r.result.victory).length,losses:rows.filter(r=>!r.result.victory).length,errors:errors.length};save();
