'use strict';
// Native repeated-domain observations. Candidate replacements exist only in the
// isolated VM and never write product sources, saves or enemy formulas.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),zlib=require('node:zlib'),crypto=require('node:crypto');
const H=require('./audit_protagonist_v01618.cjs'),arg=k=>{const i=process.argv.indexOf(k);return i<0?null:process.argv[i+1];},copy=x=>JSON.parse(JSON.stringify(x));
const root=arg('--root')||path.resolve(__dirname,'..'),out=arg('--out')||'/tmp/crpg_v01619_other_healers',cloudStrong=process.argv.includes('--cloud-strong'),cloudFocused=process.argv.includes('--cloud-focused'),dionaFocused=process.argv.includes('--diona-focused'),dionaHybrid=process.argv.includes('--diona-hybrid')||dionaFocused,candidate=process.argv.includes('--candidate-hybrid')||cloudStrong||cloudFocused||dionaHybrid,legacyYaoyao=process.argv.includes('--legacy-yaoyao-healing');
if(candidate&&legacyYaoyao)throw new Error('Legacy Yaoyao isolation and archived hybrid candidates are separate modes.');
const REPLACE=[
 ["case'XIANYUN_Q':allies.forEach(t=>heal(t,stat('atk')*.8));add('BAMBOO_STAR');", "case'XIANYUN_Q':allies.forEach(t=>heal(t,stat('atk')*"+(cloudFocused?'.03+1250':cloudStrong?'.04+905':'.15+775')+"));add('BAMBOO_STAR');"],
 ["active(b,a.side).forEach(v=>this.heal(v,this.combatStat(source,'atk')*.25,source.name));", cloudFocused?"const healTarget=lowest(active(b,a.side));if(healTarget)this.heal(healTarget,this.combatStat(source,'atk')*.08+600,source.name);":"active(b,a.side).forEach(v=>this.heal(v,this.combatStat(source,'atk')*"+(cloudStrong?'.015+280':'.04+250')+",source.name));"],
 ["if(low)heal(low,atk*.55*(a.liyueDirectRound===b.round?1.25:1));", "if(low)heal(low,(atk*.13+350)*(a.liyueDirectRound===b.round?1.25:1));"],
 ["if(source)this.heal(a,this.combatStat(source,'atk')*.45,source.name);", "if(source)this.heal(a,this.combatStat(source,'atk')*.1+295,source.name);"],
 ["allies.forEach(t=>heal(t,hp*.1));const f=field(b,'YUEGUI_THROWING'", "allies.forEach(t=>heal(t,hp*.025+380));const f=field(b,'YUEGUI_THROWING'"],
 ["if(low)heal(low,a.maxHp*.05);hit(.35,'DENDRO'", "if(low)heal(low,a.maxHp*.015+180);hit(.35,'DENDRO'"]
];
function load(){if(!candidate&&!legacyYaoyao)return H.load(root);const c=vm.createContext({console,Date,setTimeout,clearTimeout}),hash=crypto.createHash('sha256'),substitutions=[];
 const index=fs.readFileSync(path.join(root,'source/index.html'),'utf8');
 for(const[,name]of index.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)){let source=fs.readFileSync(path.join(root,'source',name),'utf8');hash.update(name);hash.update(source);
  if(name==='runtime_liyue_cards.js'&&candidate)for(const[from,to]of REPLACE){const n=source.split(from).length-1;if(n!==1)throw new Error('Expected one candidate formula: '+from+'; found '+n);source=source.replace(from,to);substitutions.push({name,from,to});}
  if(name==='runtime_liyue_cards.js'&&legacyYaoyao){const from='yaoyaoQRatio:.025,yaoyaoQFlat:380,yaoyaoFieldRatio:.015,yaoyaoFieldFlat:180',to='yaoyaoQRatio:.1,yaoyaoQFlat:0,yaoyaoFieldRatio:.05,yaoyaoFieldFlat:0';if(source.split(from).length!==2)throw new Error('Expected one current Yaoyao healing budget');source=source.replace(from,to);substitutions.push({name,from,to});}
  if(name==='runtime_combat.js'&&dionaHybrid){const from="if(f.kind==='FROST_MIST'){hit(.45,'CRYO',3,'중거리');allies.forEach(t=>this.heal(t,a.maxHp*.08,a.name));}",to=dionaFocused?"if(f.kind==='FROST_MIST'){hit(.45,'CRYO',3,'중거리');const target=allies.slice().sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp||b.actors.indexOf(x)-b.actors.indexOf(y))[0];if(target)this.heal(target,a.maxHp*.02+1200,a.name);}":"if(f.kind==='FROST_MIST'){hit(.45,'CRYO',3,'중거리');allies.forEach(t=>this.heal(t,a.maxHp*.02+300,a.name));}";if(source.split(from).length!==2)throw new Error('Expected one Diona field formula');source=source.replace(from,to);substitutions.push({name,from,to});}
  vm.runInContext(source,c,{filename:name});
 }vm.runInContext(fs.readFileSync(path.join(root,'source/presentation.js'),'utf8'),c);const raw=fs.readFileSync(path.join(root,'content/db.json'));hash.update(raw);
 return{c,db:JSON.parse(raw),R:c.CRPGRuntime.Runtime,api:c.CRPGRuntime,root,fingerprint:hash.digest('hex'),candidate:legacyYaoyao?'LEGACY_YAOYAO_ON_CURRENT':'HYBRID',substitutions};
}
const env=load(),supports=(arg('--supports')||'LIYUE_XIANYUN,LIYUE_QIQI,LIYUE_YAOYAO,LIYUE_BAIZHU,MOND_DIONA,MOND_MIKA').split(','),levels=(arg('--levels')||'25,50,60').split(',').map(Number),seeds=(arg('--seeds')||'717,925').split(',').map(Number),runs=Number(arg('--runs')||3),domainKind=arg('--domain-kind')||'TALENT';
if(!['TALENT','EXP'].includes(domainKind))throw new Error('Supported audit domain kinds: TALENT, EXP');
const data={fingerprint:env.fingerprint,runtimeRoot:root,candidate:legacyYaoyao?'LEGACY_YAOYAO_ON_CURRENT':candidate?'HYBRID'+(cloudStrong?'_CLOUD_STRONG':'')+(cloudFocused?'_CLOUD_FOCUSED':'')+(dionaFocused?'_DIONA_FOCUSED':dionaHybrid?'_DIONA':''):'NATIVE',substitutions:env.substitutions||[],assumptions:{party:'Traveler/Xiangling/Fischl/support; four active C0; native balanced AI.',gear:'Craft weapon/reinforced leather/healer brooch all enhancement6; no artifacts/exclusive weapons.',levels:'25/50/60 by default; native legal ascension phase, talent4/5/6 respectively; no level or HP reset after entry.',enemy:'Actual DOMAIN_START at authored same-level talent or EXP domain; enemy rules and groups remain native.',recovery:'One initial full HP, no inn/food/refill between native fights; stop on defeat. Final native innRecoveryQuote is hypothetical and not paid.',time:'Native 2x presentationMs/1000 +3sec/manual COMBAT input +6sec receipt/reentry; excludes network/human/acquisition time.',limits:'Two seeds and representative party only; wins, KO, fullHP and heal amounts are separate; victory10% protagonist revival and combat-only HP cap clipping remain native.'},rows:[],errors:[]};
fs.mkdirSync(out,{recursive:true});
for(const support of supports)for(const level of levels)for(const seed of seeds){const domainId=domainKind==='TALENT'?(level<=25?'FORSAKEN_RIFT':'TAISHAN_MANSION'):(level<=25?'PEAK_OF_VINDAGNYR':level<=40?'ZHOU_FORMULA':level<=50?'DOMAIN_OF_GUYUN':'LOST_VALLEY');const spec={support,level,seed,domainKind,team:['LIYUE_XIANGLING','MOND_FISCHL',support],route:'ROUTE_TRAVELER',gear:'craft',enhance:6,talent:level<=25?4:level<=50?5:6,domain:domainId+':'+level};
 try{const r=H.setup(env,{...spec,map:env.api.growthV01522.domains[spec.domain.split(':')[0]].map});r.s.constellations??={};for(const id of['PLAYER_CUSTOM',...spec.team])r.s.constellations[id]=0;
  const meter=H.observe(env,r),heals=[],nativeHeal=r.heal;r.heal=function(a,n,source,...rest){const before={hp:a.hp,maxHp:a.maxHp},applied=nativeHeal.call(this,a,n,source,...rest);heals.push({target:a.source,id:a.id,source,round:this.s.runtime?.round,requested:n,applied,before,after:{hp:a.hp,maxHp:a.maxHp}});return applied;};
  const row={...spec,fixtureHp:H.hp(r),talents:copy(r.s.talents),equipment:copy(r.s.inventory.filter(i=>i.equipped)),battles:[],wins:0,losses:0,seconds:0};
  for(let i=0;i<runs;i++){const before=H.hp(r),healIndex=heals.length,prior={...meter};r.action('DOMAIN_START',{domain:spec.domain,element:'NEUTRAL'});
   const initial=copy(r.s.runtime.actors.map(a=>({source:a.source,id:a.id,side:a.side,level:a.level,hp:a.hp,maxHp:a.maxHp,atk:a.atk,def:a.def}))),result=H.play(r),last=r._auditLast;if(result.stalled)throw new Error('Native combat stalled');
   const seconds=(meter.ms-prior.ms)/1000+3*(meter.inputs-prior.inputs)+6+Number(result.defeatPenalty?.seconds||0);
   row.battles.push({index:i+1,before,initial,result:copy(result),victory:!!result.victory,rounds:last?.rounds,seconds,after:H.hp(r),hpBeforeReward:copy(last?.actors.filter(a=>a.side==='ALLY').map(a=>({source:a.source,id:a.id,hp:a.hp,maxHp:a.maxHp}))),heals:copy(heals.slice(healIndex)),log:copy(last?.log)});row.seconds+=seconds;
   if(result.victory)row.wins++;else{row.losses++;break;}
  }
  row.finalHp=H.hp(r);row.finalHpRatio=row.finalHp.reduce((s,a)=>s+a.hp,0)/row.finalHp.reduce((s,a)=>s+a.maxHp,0);row.allAlive=row.finalHp.every(a=>a.hp>0);row.allFull=row.finalHp.every(a=>a.hp===a.maxHp);row.koBattles=row.battles.filter(b=>b.hpBeforeReward.some(a=>a.hp<=0)).length;
  const stock=r.rows('19_SHOP_STOCK_DB').find(a=>a[3]==='SERVICE_INN_REST_8H');row.nativeInnQuote=copy(r.innRecoveryQuote(stock));row.comparableFinalQuote=row.wins===runs&&!row.losses?row.nativeInnQuote:null;row.totalHeal=row.battles.reduce((s,b)=>s+b.heals.reduce((a,h)=>a+h.applied,0),0);row.finalLevels=row.finalHp.map(a=>({owner:a.owner,level:a.level}));data.rows.push(row);
  console.log(JSON.stringify({support,level,seed,wins:row.wins,losses:row.losses,hp:+row.finalHpRatio.toFixed(4),ko:row.koBattles,heal:row.totalHeal,seconds:+row.seconds.toFixed(1)}));
 }catch(e){data.errors.push({spec,message:e.message,code:e.code||e.name});console.log(JSON.stringify(data.errors.at(-1)));}
 fs.writeFileSync(path.join(out,'native.json.gz'),zlib.gzipSync(JSON.stringify(data),{level:9}));
}
const summary={fingerprint:data.fingerprint,candidate:data.candidate,conditions:data.rows.length,errors:data.errors,battles:data.rows.reduce((s,r)=>s+r.battles.length,0),wins:data.rows.reduce((s,r)=>s+r.wins,0),losses:data.rows.reduce((s,r)=>s+r.losses,0),groups:supports.flatMap(support=>levels.map(level=>{const rows=data.rows.filter(r=>r.support===support&&r.level===level);return{support,level,conditions:rows.length,wins:rows.reduce((s,r)=>s+r.wins,0),losses:rows.reduce((s,r)=>s+r.losses,0),completeAllAlive:rows.filter(r=>r.wins===runs&&r.allAlive&&!r.koBattles).length,completeAllFull:rows.filter(r=>r.wins===runs&&r.allFull).length,hp:rows.map(r=>r.finalHpRatio),ko:rows.reduce((s,r)=>s+r.koBattles,0),heal:rows.map(r=>r.totalHeal),quotes:rows.map(r=>r.comparableFinalQuote),seconds:rows.map(r=>r.seconds)};})),nativeSha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(out,'native.json.gz'))).digest('hex')};
fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify({done:true,conditions:summary.conditions,battles:summary.battles,wins:summary.wins,losses:summary.losses,errors:summary.errors.length}));
