'use strict';
// QA only: exact menu search and actual CRAFT/MEAL_BATCH/BUY receipts.
// Ingredient ownership and learned recipes are declared synthetic setup. This
// audit does not grant player items, change combat, or invent gathering time.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),copy=x=>JSON.parse(JSON.stringify(x)),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const PARTY=['PLAYER_CUSTOM','MOND_AMBER','MOND_KAEYA','MOND_LISA'],LEVELS=[1,10,20,30,40,50,55,60],ROUTES=['ROUTE_TRAVELER','ROUTE_ISEKAI'];
const MENUS={EASY:['FOOD_TEA_BREAK_PANCAKE','FOOD_CHICKEN_SKEWER','FOOD_RADISH_SOUP','FOOD_MINT_JELLY','FOOD_STEAK','FOOD_MORA_MEAT'],MEDIUM:['FOOD_SWEET_MADAME','FOOD_HASH_BROWN','FOOD_MATSUTAKE_ROLL','FOOD_UNIVERSAL_PEACE','FOOD_PIZZA','FOOD_BOLOGNESE'],HARD:['FOOD_VEGETARIAN_ABALONE','FOOD_PERCH_STEW','FOOD_BAMBOO_SOUP','FOOD_CRAB_HAM_BAKE','FOOD_FISH_NOODLES','FOOD_LUCKY_SNOW_DELIGHT']};
const SOURCES={MOND:{city:'MAP_MOND_CITY',merchant:'MRC_MOND_GENERAL',cookMap:'MAP_MOND_CITY',cook:'EVT_SCHEDULE_SERVICE_MOND_COOK',inn:'EVT_SCHEDULE_MRC_MOND_INN',stock:'STK_INN_MOND'},LIYUE:{city:'MAP_LIYUE_HARBOR',merchant:'MRC_LIYUE_GENERAL',cookMap:'MAP_LY_DETAIL_CHIHU',cook:'EVT_SCHEDULE_SERVICE_LIYUE_COOK',inn:'EVT_SCHEDULE_MRC_LIYUE_INN',stock:'STK_INN_LIYUE'}};
const CLOCK=Date.parse('2026-10-09T07:00:00Z');
function loadEnvironment(sourceRoot=ROOT){
 let clock=CLOCK;const c=vm.createContext({console,Date:class extends Date{static now(){return clock;}},setTimeout,clearTimeout}),loaded=[];
 const html=fs.readFileSync(path.join(sourceRoot,'source/index.html'),'utf8');
 for(const [,file]of html.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)){const code=fs.readFileSync(path.join(sourceRoot,'source',file),'utf8');loaded.push({file,sha256:sha(code)});vm.runInContext(code,c,{filename:file});}
 const rawDb=fs.readFileSync(path.join(sourceRoot,'content/db.json'),'utf8'),db=JSON.parse(rawDb),R=c.CRPGRuntime.Runtime,G=c.CRPGRuntime.growthV01522;
 return {c,db,R,G,advance:ms=>clock+=ms,provenance:{sourceRoot,packageVersion:JSON.parse(fs.readFileSync(path.join(sourceRoot,'package.json'))).version,dbSha256:sha(rawDb),loadedSource:loaded,loadedSourceDigest:sha(JSON.stringify(loaded)),toolSha256:sha(fs.readFileSync(__filename)),auditClockMs:CLOCK}};
}
function setup(env,{levels=55,route='ROUTE_TRAVELER',region='MOND'}={}){
 const r=new env.R(env.db);r.newGame({name:'음식 숙박 감사',route,seed:717,saveId:'FOOD-LODGING-V01617-'+route+'-'+JSON.stringify(levels)+'-'+region});
 Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:SOURCES[region].city,STORY_MENU_POLICY:'',WORLD_TIME:'12:00',MORA:1000000});delete r.s.storyJourney;delete r.s.storyBreak;r.prepareStory();
 for(const id of ['FLAG_TRV_ANEMO_UNLOCKED','FLAG_TRV_MON_CH1_CLEAR','FLAG_TRV_MON_CH2_CLEAR','FLAG_ISK_M03_CLEAR','FLAG_ISK_M05_CLEAR','FLAG_ACCESS_REGION_LIYUE'])r.s.flags[id]=true;
 r.s.inventory=[];r.s.talents??={};r.s.party=[r.s.party[0],...PARTY.slice(1).map((source,i)=>({slot:'PARTY_'+(i+2),type:'CHAR',source,control:'AI',active:true,tactic:'균형'}))];r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(Object.fromEntries(PARTY.slice(1).map(id=>[id,{state:'JOINED'}])));
 const weapons={'한손검':'EQ_SWORD_RANCOUR','양손검':'EQ_CLAYMORE_WHITEBLIND','활':'EQ_BOW_CRESCENT','법구':'EQ_CATALYST_MAPPA','장병기':'EQ_POLEARM_CRESCENT'};
 for(const [i,id]of PARTY.entries()){const level=Array.isArray(levels)?levels[i]:levels;if(id==='PLAYER_CUSTOM')r.s.global.PLAYER_LEVEL_STATE=level;else r.s.chars[id].level=level;r.s.ascensions[id]=env.G.phaseFor(level);const cap=r.growth(id).talentCap,t=Math.max(1,Math.floor(cap*.65));r.s.talents[id]={na:t,e:t,q:t};for(const equip of [weapons[r.equipmentProficiencies(id)[0]],'EQ_ARMOR_REINFORCED_LEATHER','EQ_ACC_HEALER_BROOCH']){if(!equip||Number(r.row('16_EQUIP_DB',equip)[19])>level)continue;const slot=r.giveEquipment(equip);r.action('EQUIP',{slot,owner:id});r.s.inventory.find(x=>x.slot===slot).enhance=level<30?3:6;}}
 r.recalculate();for(const id of PARTY){const a=id==='PLAYER_CUSTOM'?r.player():r.character(id);if(id==='PLAYER_CUSTOM')r.s.global.PLAYER_HP_CURRENT=a.maxHp;else r.s.chars[id].hp=a.maxHp;}
 Object.assign(r.tutorialState().done,{combatAttack:true,combatGuard:true,combatSkill:true,combatBurst:true});r.s.global.PRNG_STATE=717;return r;
}
function cloneRuntime(r){const out=Object.create(Object.getPrototypeOf(r));Object.assign(out,r);out.s=copy(r.s);return out;}
const hp=r=>PARTY.map(owner=>{const a=owner==='PLAYER_CUSTOM'?r.player():r.character(owner);return{owner,level:a.level,hp:a.hp,maxHp:a.maxHp,lastMeal:r.economyOwner(owner).lastMeal};});
function injure(r,loss,owners=PARTY){for(const owner of owners){const a=owner==='PLAYER_CUSTOM'?r.player():r.character(owner),value=Math.max(1,a.maxHp-Math.ceil(a.maxHp*loss));if(owner==='PLAYER_CUSTOM')r.s.global.PLAYER_HP_CURRENT=value;else r.s.chars[owner].hp=value;}return hp(r);}
function learnRecipes(r){const usage=JSON.parse(r.s.global.SHOP_STOCK_USAGE_STATE||'{}'),licenses=[];for(const raw of r.rows('17_RECIPE_DB')){const q=r.recipeDefinition(raw[0]),m=/^(STK_\w+(?: 또는 STK_\w+)*) 구매완료$/.exec(String(q[18]||''));if(m){const stock=m[1].split(' 또는 ')[0];usage[stock+'|AUDIT-SYNTHETIC-LEARNED']=1;licenses.push({recipe:q[0],stock,synthetic:true});}}r.s.global.SHOP_STOCK_USAGE_STATE=JSON.stringify(usage);return licenses;}
function purchaseLowerBounds(r,region){
 const merchant=SOURCES[region].merchant,prices={};for(const s of r.rows('19_SHOP_STOCK_DB'))if(s[1]===merchant&&s[2]==='ITEM'&&Number(s[5])>0&&!/SYSTEM_DISABLED|레거시|사용 금지/.test(s[8]||'')){const value=Number(s[5]);if(!prices[s[3]]||value<prices[s[3]].unitMora)prices[s[3]]={unitMora:value,route:'NPC_BUY',stock:s[0],stockQuantity:Number(s[6]),condition:s[8]};}
 for(let i=0;i<r.rows('17_RECIPE_DB').length;i++){let changed=false;for(const raw of r.rows('17_RECIPE_DB')){const q=r.recipeDefinition(raw[0]);if(q[2]!=='ITEM')continue;const cost=r.recipeCost(q),entries=Object.entries(cost.items);if(entries.some(([id])=>!prices[id]))continue;const unit=(cost.mora+entries.reduce((n,[id,k])=>n+k*prices[id].unitMora,0))/Number(q[4]);if(!prices[q[3]]||unit<prices[q[3]].unitMora){prices[q[3]]={unitMora:unit,route:'CRAFT_LOWER_BOUND',recipe:q[0]};changed=true;}}if(!changed)break;}return prices;
}
function foodCatalog(r,region){
 const lower=purchaseLowerBounds(r,region),out=[];for(const raw of r.rows('17_RECIPE_DB')){const f=r.tables['14_ITEM_DB'].get(raw[3]);if(f?.[2]!=='음식'||!(Number(f[8])>0))continue;const q=r.recipeDefinition(raw[0]),cost=r.recipeCost(q);let spec;try{spec=r.foodSpec(f[0]);}catch(e){out.push({food:f[0],recipe:q[0],unsupported:e.code});continue;}if(spec.status)continue;
 const readyFoodStocks=r.rows('19_SHOP_STOCK_DB').filter(s=>s[2]==='ITEM'&&s[3]===f[0]&&!/SYSTEM_DISABLED|레거시|사용 금지/.test(s[8]||'')&&r.tables['18_MERCHANT_DB'].get(s[1])?.[2]===(region==='MOND'?'몬드':'리월')).map(s=>({stock:s[0],merchant:s[1],unitMora:Number(s[5]),stockQuantity:Number(s[6]),period:s[7],condition:s[8]}));const readyFoodMoraLowerBound=readyFoodStocks.length?Math.min(...readyFoodStocks.map(s=>s.unitMora)):null;const missing=Object.keys(cost.items).filter(id=>!lower[id]),opportunity=Object.entries(cost.items).reduce((n,[id,k])=>n+k*r.saleUnitPrice({item:id}),0),npc=missing.length?null:Object.entries(cost.items).reduce((n,[id,k])=>n+k*lower[id].unitMora,0);
 out.push({food:f[0],name:f[1],recipe:q[0],baseHealing:spec.heal,output:Number(q[4]),cost:copy(cost),minutes:Number(String(q[19]).match(/\d+/)?.[0]||0)*(String(q[19]).includes('시간')?60:1),unlock:q[18],recipeReason:r.craftReason(q),ingredientNpcOpportunityMora:opportunity,purchasedIngredientMoraLowerBound:npc,allNpcMoraLowerBound:npc===null?null:npc+cost.mora,readyFoodStocks,readyFoodMoraLowerBound,minimumNpcMoraLowerBound:npc===null?readyFoodMoraLowerBound:readyFoodMoraLowerBound===null?npc+cost.mora:Math.min(npc+cost.mora,readyFoodMoraLowerBound),missingPurchasable:missing,resaleMora:r.saleUnitPrice({item:f[0]})});}return out;
}
class Heap{constructor(compare){this.q=[];this.compare=compare;}push(x){const q=this.q;q.push(x);let i=q.length-1;while(i){const p=(i-1)>>1;if(this.compare(q[p],x)<=0)break;q[i]=q[p];i=p;}q[i]=x;}pop(){const q=this.q,first=q[0],last=q.pop();if(q.length){let i=0;while(i*2+1<q.length){let j=i*2+1;if(j+1<q.length&&this.compare(q[j+1],q[j])<0)j++;if(this.compare(last,q[j])<=0)break;q[i]=q[j];i=j;}q[i]=last;}return first;}get size(){return this.q.length;}}
const cmp=(a,b)=>a[0]-b[0]||a[1]-b[1]||a[2]-b[2];
function optimalMenu(r,owner,foods,priority='craftCash'){
 const a=r.economyOwner(owner),missing=a.maxHp-a.hp;if(missing<=0)return{owner,path:[],missingHp:0,healed:0,objectiveCost:0,states:0};if(a.hp<=0)return{owner,blocked:'TARGET_DOWN',missingHp:missing};
 const choices=foods.filter(f=>!f.unsupported&&!f.recipeReason&&f.output===1&&(priority!=='allNpc'||f.minimumNpcMoraLowerBound!==null)).map(f=>({...f,healing:r.foodHealingAmount(f.baseHealing,owner),weight:priority==='allNpc'?f.minimumNpcMoraLowerBound:priority==='opportunity'?f.cost.mora+f.ingredientNpcOpportunityMora:f.cost.mora}));
 if(choices.length<2)return{owner,blocked:'FEWER_THAN_TWO_ELIGIBLE_FOODS',missingHp:missing,eligible:choices.map(f=>f.food)};
 const queue=new Heap((a,b)=>cmp(a.score,b.score)),labels=new Map(),first={healed:0,last:a.lastMeal||'NONE',score:[0,0,0],path:[]};queue.push(first);let states=0;
 function retain(node){let group=labels.get(node.last);if(!group){group=[];labels.set(node.last,group);}if(group.some(x=>!x.dead&&x.healed>=node.healed&&cmp(x.score,node.score)<=0))return false;for(const x of group)if(!x.dead&&x.healed<=node.healed&&cmp(x.score,node.score)>=0)x.dead=true;group.push(node);return true;}retain(first);
 while(queue.size){const node=queue.pop();if(node.dead)continue;if(++states>2000000)throw Error('Menu search limit; refuse unproved result');if(node.healed>=missing)return{owner,path:node.path,missingHp:missing,requestedHealing:node.path.reduce((n,id)=>n+choices.find(f=>f.food===id).healing,0),healed:missing,objectiveCost:node.score[0]/1e6,states};
  for(const f of choices){if(f.food===node.last)continue;const next={healed:Math.min(missing,node.healed+f.healing),last:f.food,score:[node.score[0]+Math.round(f.weight*1e6),node.score[1]+1,node.score[2]+Math.round(f.ingredientNpcOpportunityMora*1e6)],path:[...node.path,f.food]};if(retain(next))queue.push(next);}}
 return{owner,blocked:'NO_ALTERNATING_MENU',missingHp:missing,states};
}
function executeMenu(template,plans,foods,{inputSeconds=3}={}){
 if(plans.some(p=>p.blocked))return{blocked:plans.filter(p=>p.blocked)};const r=cloneRuntime(template),before=hp(r),byFood=new Map(foods.map(f=>[f.food,f])),counts={};for(const p of plans)for(const id of p.path)counts[id]=(counts[id]||0)+1;
 const ingredients={},crafts=[],meals=[],wallet=r.s.global.MORA;let expectedFee=0,ingredientOpportunity=0,ingredientPurchase=0,allPurchaseKnown=true,minimumNpc=0,minimumNpcKnown=true;
 for(const [id,n]of Object.entries(counts)){const f=byFood.get(id);expectedFee+=f.cost.mora*n;ingredientOpportunity+=f.ingredientNpcOpportunityMora*n;if(f.minimumNpcMoraLowerBound===null)minimumNpcKnown=false;else minimumNpc+=f.minimumNpcMoraLowerBound*n;if(f.purchasedIngredientMoraLowerBound===null)allPurchaseKnown=false;else ingredientPurchase+=f.purchasedIngredientMoraLowerBound*n;for(const [item,k]of Object.entries(f.cost.items))ingredients[item]=(ingredients[item]||0)+k*n;}
 for(const [id,n]of Object.entries(ingredients))r.giveItem(id,n);const cook=SOURCES[template._auditRegion],placeStart=r.action('PLACE_ENTER',{place:cook.cook,mode:'CRAFT'}).result;
 for(const [id,n]of Object.entries(counts)){const f=byFood.get(id);let left=n;while(left){const quantity=Math.min(left,5,Math.floor(1440/f.minutes));assert(quantity>0);const out=r.action('CRAFT',{recipe:f.recipe,quantity}).result;assert.equal(out.quantity,quantity);crafts.push(copy(out));left-=quantity;}}
 const fee=wallet-r.s.global.MORA;assert.equal(fee,expectedFee,'quoted fee must equal actual native debits');r.action('PLACE_LEAVE');
 const batches=Math.max(0,...plans.map(p=>p.path.length));for(let index=0;index<batches;index++){const entries=plans.filter(p=>p.path[index]).map(p=>({owner:p.owner,item:p.path[index],variant:'NORMAL'})),out=r.action('MEAL_BATCH',{meals:entries}).result;assert.equal(out.minutes,10);meals.push(copy(out));}
 const after=hp(r);assert(after.every(a=>a.hp===a.maxHp),'all selected loss must be restored by actual meal receipts');for(const id of Object.keys(counts))assert.equal(r.itemCount(id),0,'all made servings are consumed');
 const crafted=crafts.reduce((n,x)=>n+x.quantity,0),actualHealed=meals.flatMap(x=>x.meals).reduce((n,x)=>n+x.healed,0),requestedHealing=meals.flatMap(x=>x.meals).reduce((n,x)=>n+x.requestedHealing,0),gameMinutes=crafts.reduce((n,x)=>n+x.minutes,0)+10*meals.length;
 return{before,after,foodCounts:counts,ingredients,craftedServings:crafted,craftActions:crafts.length,mealBatchActions:meals.length,facilityActions:2,actionInputCount:crafts.length+meals.length+2,inputBudgetSeconds:(crafts.length+meals.length+2)*inputSeconds,acquisitionAndTravelSeconds:null,gameMinutes,craftMora:fee,ingredientNpcOpportunityMora:ingredientOpportunity,ownedIngredientTotalMora:fee+ingredientOpportunity,purchasedIngredientMoraLowerBound:allPurchaseKnown?ingredientPurchase:null,allNpcMoraLowerBound:allPurchaseKnown?fee+ingredientPurchase:null,minimumNpcMoraLowerBound:minimumNpcKnown?minimumNpc:null,readyFoodAlternative:'Each food may use ready-food NPC lower bound when cheaper. No ready-food BUY is executed here; stock quantities and restock wait are retained in catalog and excluded from lower bound.',requestedHealing,actualHealed,overheal:requestedHealing-actualHealed,crafts,meals,placeStart};
}
function innComparison(template){const out={};for(const [region,site]of Object.entries(SOURCES)){const r=cloneRuntime(template);r.s.global.CURRENT_MAP_ID=site.city;r.s.placeVisit=null;r.s.global.SCREEN_MODE='LOCATION';const quote=copy(r.innRecoveryQuote(r.row('19_SHOP_STOCK_DB',site.stock)));r.action('PLACE_ENTER',{place:site.inn,mode:'SHOP'});const wallet=r.s.global.MORA,receipt=r.action('BUY',{stock:site.stock,quantity:1}).result;assert.equal(wallet-r.s.global.MORA,quote.cost);assert.equal(receipt.cost,quote.cost);assert(hp(r).every(x=>x.hp===x.maxHp));out[region]={quote,receipt:copy(receipt),fullRecovery:true,location:'Synthetic independent start at the stated city; no travel shortcut in gameplay',inputActions:2,gameMinutes:receipt.minutes};}return out;}
function travelToKitchen(r,region){const site=SOURCES[region],route=r.navigationRoute(site.cookMap);if(!route)return{blocked:'NO_KITCHEN_ROUTE'};const edges=[];for(const edge of route.edges){const receipt=r.action('MOVE',{edge:edge[0]}).result;edges.push({edge:edge[0],receipt});if(r.s.runtime)return{blocked:'KITCHEN_TRAVEL_COMBAT',edges};}return{startingCity:site.city,kitchenMap:site.cookMap,kitchenPlace:site.cook,edges,gameMinutes:route.minutes,realTravelSeconds:null};}
function audit({out=null,sourceRoot=ROOT,levels=LEVELS,routes=ROUTES,losses=[.25,.5,.75],priorities=['craftCash','allNpc','opportunity'],regions=['MOND','LIYUE'],menus=Object.keys(MENUS),extras=true,onProgress=()=>{}}={}){
 const env=loadEnvironment(sourceRoot),data={schema:1,tool:'tools/audit_food_lodging_v01617.cjs',provenance:env.provenance,menus:copy(MENUS),priorities,assumptions:{synthetic:['Four-member ownership and declared per-target level/phase/talents/legal equipment.','One initial 1000000 Mora wallet, excluded from income.','Exact chosen menu raw ingredients start owned; separately value NPC purchase lower bounds and lost resale opportunity.','Bought recipe flags are explicit synthetic learned licenses; their one-time purchase and travel are excluded from recurring menu costs.','Independent initial city and imposed HP loss; this table is not a combat campaign.'],native:['CRAFT fees and quantities, MEAL_BATCH recipient healing/caps/repeat restrictions, and BUY lodging receipts are executed.','Same food may not repeat for one recipient; no satiety gauge exists in the current runtime.','No KO healing/revival is invented; lodging retains full-party recovery.','Gear HP and per-target level scaling remain native; no combat or healing override.'],timing:{inputSeconds:3,craftBulkLimit:5,nativeGameMinutesDistinctFromRealTime:true,acquisitionAndTravelTimesNotInvented:true,realElapsed:null},prices:'Current regional general-store ingredient catalog plus processing/craft lower bounds. Stock depletion, recipe unlock acquisition, processing actions and travel are excluded from NPC lower bounds; unknown goods remain null.',supplyAudit:'tools/audit_food_supply_v01617.cjs provides actual zero-stock LIFE/processing/CRAFT/MEAL/travel campaigns separately.'},catalog:[],rows:[],exceptions:[]};
 function save(){if(out){fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(data,null,2)+'\n');}}
 function collect(levels,route,region,loss,owners,mode){const template=setup(env,{levels,route,region});template._auditRegion=region;const licenses=learnRecipes(template),initialHp=injure(template,loss,owners),inn=innComparison(template),kitchen=travelToKitchen(template,region);if(kitchen.blocked){data.exceptions.push({levels,route,region,loss,mode,kitchen});return;}const place=template.action('PLACE_ENTER',{place:SOURCES[region].cook,mode:'CRAFT'});const foods=foodCatalog(template,region);template.action('PLACE_LEAVE');if(data.catalog.every(x=>x.region!==region))data.catalog.push({region,foods,syntheticLearnedRecipes:licenses,kitchen});
  for(const menu of menus)for(const priority of priorities){const selected=foods.filter(f=>MENUS[menu].includes(f.food)),plans=PARTY.map(owner=>optimalMenu(template,owner,selected,priority)),actual=executeMenu(template,plans,selected);const row={mode,levels,route,region,hpLoss:loss,injuredOwners:owners,initialHp,inn,kitchen,menu,priority,plans,actual};data.rows.push(row);onProgress(row);}
 }
 save();let completed=0;const total=levels.length*routes.length*regions.length*losses.length;
 for(const level of levels)for(const route of routes)for(const region of regions)for(const loss of losses){collect(level,route,region,loss,PARTY,'SAME_LEVEL_FOUR');if(++completed%4===0){save();console.log(JSON.stringify({audit:'food-lodging',completed,total,rows:data.rows.length,exceptions:data.exceptions.length}));}}
 if(extras)for(const route of routes)for(const region of regions){collect([60,10,20,40],route,region,.5,PARTY,'MIXED_TARGET_LEVELS');for(const level of [10,30,60])for(const loss of [.01,.05])collect(level,route,region,loss,['MOND_AMBER'],'ONE_TARGET_SMALL_LOSS');}
 const dead=setup(env,{levels:60});dead.s.chars.MOND_AMBER.hp=0;dead.giveItem('FOOD_SWEET_MADAME',1);const before=dead.serialize();let blocked=null;try{dead.action('USE_ITEM',{item:'FOOD_SWEET_MADAME',owner:'MOND_AMBER'});}catch(e){blocked=e.code;}assert.equal(blocked,'TARGET_DOWN');assert.equal(dead.serialize(),before);data.koBoundary={foodBlocked:blocked,failedFoodAtomic:true,inn:innComparison(dead)};
 data.counts={conditions:completed,rows:data.rows.length,menuExecutions:data.rows.filter(r=>!r.actual.blocked).length,blockedMenus:data.rows.filter(r=>r.actual.blocked).length,exceptions:data.exceptions.length,foodRecipes:data.catalog[0]?.foods.length||0,nativeCraftActions:data.rows.reduce((n,r)=>n+(r.actual.craftActions||0),0),nativeMealBatchActions:data.rows.reduce((n,r)=>n+(r.actual.mealBatchActions||0),0)};save();return data;
}
if(require.main===module){const args=process.argv.slice(2),option=name=>args.includes(name)?args[args.indexOf(name)+1]:undefined,out=option('--out')||path.join(ROOT,'docs/data/food_lodging_v01617_baseline.json');const data=audit({out,sourceRoot:option('--source-root')||ROOT,levels:option('--levels')?.split(',').map(Number)||LEVELS,routes:option('--routes')?.split(',')||ROUTES,regions:option('--regions')?.split(',')||['MOND','LIYUE'],extras:!args.includes('--no-extras')});console.log(JSON.stringify({out,...data.counts}));}
module.exports={audit,loadEnvironment,setup,cloneRuntime,hp,injure,learnRecipes,purchaseLowerBounds,foodCatalog,optimalMenu,executeMenu,innComparison,travelToKitchen,MENUS,SOURCES,PARTY,LEVELS,ROUTES};
