'use strict';
// Observational native campaigns. This audit never edits enemy stats, damage,
// healing amounts, meal locks, WORLD_DAY, HP or RNG between actions.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const option=name=>{const i=process.argv.indexOf(name);return i<0?undefined:process.argv[i+1];};
const SOURCE_ROOT=path.resolve(option('--source-root')||path.join(__dirname,'..'));
const {setup,observe,G,PLAYER}=require(path.join(SOURCE_ROOT,'tools/audit_balance_v01522.cjs'));
const {policy,REFERENCE_TEAM}=require(path.join(SOURCE_ROOT,'tools/audit_balance_v0161.cjs'));
const {c,advance}=require(path.join(SOURCE_ROOT,'tests/helpers_v011.cjs'));
const CLOCK_MS=Date.parse('2026-10-09T05:00:00Z'),PARTY=[PLAYER,...REFERENCE_TEAM];
const REQUIRED_GROWTH_SHA='f62c64529a8244e23f4ffce75f3bf6bc08027172da1b775c1aa1168210501247';
const DEFAULT_RECIPES=['REC_FOOD_SWEET_MADAME','REC_FOOD_CHICKEN_SKEWER'];
const DEFAULT_OUT=path.join(__dirname,'../docs/data/food_campaign_v01617_final.json');
const copy=x=>JSON.parse(JSON.stringify(x)),digest=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const count=(r,id)=>r.itemCount(id);
function hp(r){return PARTY.map(owner=>({owner,level:r.growth(owner).level,phase:r.growthPhase(owner),hp:owner===PLAYER?r.s.global.PLAYER_HP_CURRENT:r.s.chars[owner].hp,maxHp:owner===PLAYER?r.s.global.PLAYER_HP_MAX:r.character(owner).maxHp}));}
const restNeeded=r=>hp(r).some(x=>x.hp<=0||x.hp/x.maxHp<.5);
const world=r=>({day:r.s.global.WORLD_DAY,time:r.s.global.WORLD_TIME,clockMs:c.Date.now(),map:r.s.global.CURRENT_MAP_ID,rng:r.s.global.PRNG_STATE});
function trim(r){if(r.s.log.length>30)r.s.log=r.s.log.slice(-30);const receipts=Object.entries(r.s.combatReceipts||{});if(receipts.length>30)r.s.combatReceipts=Object.fromEntries(receipts.slice(-30));}
function sourceSnapshot(){const loaded=[...fs.readFileSync(path.join(SOURCE_ROOT,'source/index.html'),'utf8').matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)].map(x=>x[1]).concat('presentation.js'),hash=crypto.createHash('sha256');for(const file of loaded)hash.update(file+'\0').update(fs.readFileSync(path.join(SOURCE_ROOT,'source',file))).update('\0');return {sourceRoot:SOURCE_ROOT,growthSha256:digest(path.join(SOURCE_ROOT,'source/runtime_growth_v01522.js')),economySha256:digest(path.join(SOURCE_ROOT,'source/runtime_economy.js')),innSha256:digest(path.join(SOURCE_ROOT,'source/runtime.js')),dbSha256:digest(path.join(SOURCE_ROOT,'content/db.json')),loadedNativeFiles:loaded.length,loadedNativeFilesSha256:hash.digest('hex'),toolSha256:digest(__filename),packageVersion:JSON.parse(fs.readFileSync(path.join(SOURCE_ROOT,'package.json'))).version};}
function ingredientValue(r,id,n){const stocks=r.rows('19_SHOP_STOCK_DB').filter(x=>x[2]==='ITEM'&&x[3]===id&&Number(x[5])>0&&!/SYSTEM_DISABLED|레거시|사용 금지/.test(x[8]||''));const local=stocks.filter(x=>r.merchantOpen(x[1]));const lowest=rows=>rows.length?Math.min(...rows.map(x=>Number(x[5]))):null;return {id,name:r.row('14_ITEM_DB',id)[1],quantity:n,npcSaleUnit:r.saleUnitPrice({item:id}),npcSaleValue:r.saleUnitPrice({item:id})*n,lowestGlobalShopUnit:lowest(stocks),lowestCurrentlyOpenShopUnit:lowest(local),shopStocks:stocks.map(x=>({stock:x[0],merchant:x[1],price:x[5],condition:x[8],stockLimit:x[6]})),valuationOnly:true};}
function campaign({level=55,stage=60,route='ROUTE_TRAVELER',element='HYDRO',strategy='INN_ONLY',seed=717,limit=6,packQuantity,recipes=DEFAULT_RECIPES,startingMora=200000}={}){
 advance(CLOCK_MS-c.Date.now());
 const [key,site]=Object.entries(G.domains).find(([,d])=>d.kind==='ASCENSION'&&d.levels.includes(stage))||[];if(!site)throw Error('Missing ascension domain');
 const region=site.region,kitchen=region==='몬드'?{place:'EVT_SCHEDULE_SERVICE_MOND_COOK',map:'MAP_MOND_CITY'}:{place:'EVT_SCHEDULE_SERVICE_LIYUE_COOK',map:'MAP_LY_DETAIL_CHIHU'};
 const r=setup({level,route,team:REFERENCE_TEAM,map:kitchen.map,gear:'craft',enhance:level<30?3:6,talent:'mid',saveId:'FOOD-V01617-'+route+'-'+level+'-'+element+'-'+seed});
 Object.assign(r.tutorialState().done,{combatAttack:true,combatGuard:true,combatSkill:true,combatBurst:true});r.s.global.PRNG_STATE=seed;r.s.global.MORA=startingMora;r.s.domainDaily={day:G.dayOf(r.leyLineNow()),wins:3};observe(r);
 const row={level,stage,route,element,strategy,seed,domain:key+':'+stage,region,party:PARTY,enhance:level<30?3:6,talent:'mid',limit,startingMora,initialHp:hp(r),initialWorld:world(r),syntheticStartingMora:true,syntheticInitialIngredients:strategy==='PREPARED_MEAL_AND_INN',prep:{actions:[],encounters:[],seconds:0,craftingMora:0,craftingWorldMinutes:0,ingredients:[],craftReceipts:[]},battles:[],recoveries:[],mealReceipts:[],lodgingReceipts:[],wins:0,losses:0,seconds:0};
 const nativeAction=r.action;let presentationMs=0,inputs=0;
 r.action=function(type,args){const before=c.CRPGPresentation.snapshot(this.s),out=nativeAction.call(this,type,args);let ms=0;for(const frame of c.CRPGPresentation.actionFrames(c.CRPGPresentation.delta(before,this.s))){if(frame.kind==='state'&&frame.silent)continue;ms+=frame.kind==='action'?460+(frame.attemptCount>1?520:650):1400;}presentationMs+=ms;if(type==='COMBAT')inputs++;if(type==='COMBAT'||type==='COMBAT_BEGIN'||ms>0)advance(ms+(type==='COMBAT'?3000:0));return out;};
 function action(bucket,type,args={},visualSeconds=0){const before=world(r),wallet=r.s.global.MORA,p0=presentationMs,i0=inputs,out=r.action(type,args);const seconds=3+visualSeconds;advance(seconds*1000);bucket.seconds+=seconds;bucket.actions.push({type,args:copy(args),before,after:world(r),mora:r.s.global.MORA-wallet,receipt:copy(out)});if(r.s.runtime){const result=policy(r),duration=(presentationMs-p0)/1000+(inputs-i0)*3+6+Number(result.defeatPenalty?.seconds||0);advance((6+Number(result.defeatPenalty?.seconds||0))*1000);bucket.seconds+=duration;bucket.encounters.push({result:copy(result),seconds:duration,hpAfter:hp(r),worldAfter:world(r)});if(!result.victory)throw Error('TRAVEL_DEFEAT');trim(r);}return out.result??out;}
 function travel(bucket,map){const nav=r.navigationRoute(map);if(!nav)throw Error('NO_ROUTE:'+map);for(const edge of nav.edges)action(bucket,'MOVE',{edge:edge[0]},(c.CRPGRuntime.directRegionTransitIds||[]).includes(edge[0])?30:1);}
 const unitCosts={};
 try{
  if(strategy==='PREPARED_MEAL_AND_INN'){
   action(row.prep,'PLACE_ENTER',{place:kitchen.place,mode:'CRAFT'},1);
   const quantity=packQuantity??(level<20?8:level<50?16:24),ingredients={};
   for(const id of recipes){const rec=r.recipeDefinition(id),reason=r.craftReason(rec);if(reason)throw Error('RECIPE_LOCKED:'+id+':'+reason);const cost=r.recipeCost(rec,quantity);for(const [item,n]of Object.entries(cost.items))ingredients[item]=(ingredients[item]||0)+n;unitCosts[rec[3]]={recipe:id,quantityPerCraft:Number(rec[4]),moraPerFood:cost.mora/(quantity*Number(rec[4])),itemsPerFood:Object.fromEntries(Object.entries(cost.items).map(([item,n])=>[item,n/(quantity*Number(rec[4]))]))};}
   for(const [id,n]of Object.entries(ingredients)){r.giveItem(id,n);row.prep.ingredients.push(ingredientValue(r,id,n));}
   row.initialFoodStock={};
   for(const id of recipes){const rec=r.recipeDefinition(id);for(let remaining=quantity;remaining>0;){const batch=Math.min(5,remaining),wallet=r.s.global.MORA,before=count(r,rec[3]),out=action(row.prep,'CRAFT',{recipe:id,quantity:batch},1.4);if(r.s.global.MORA!==wallet-out.cost.mora)throw Error('CRAFT_RECEIPT_MISMATCH');row.prep.craftReceipts.push(copy(out));row.prep.craftingMora+=out.cost.mora;row.prep.craftingWorldMinutes+=out.minutes;if(count(r,rec[3])-before!==out.quantity)throw Error('CRAFT_INVENTORY_MISMATCH');remaining-=batch;}row.initialFoodStock[rec[3]]=count(r,rec[3]);}
   action(row.prep,'PLACE_LEAVE',{},1);
  }
  travel(row.prep,site.map);
 }catch(error){row.stop='PREPARATION_FAILED';row.reason=error.code||error.message;}
 row.seconds+=row.prep.seconds;row.combatStartingHp=hp(r);row.combatStartingWorld=world(r);
 function nativeInn(cause,{returnToDomain=true,appendToCampaign=true}={}){const bucket={kind:'INN',cause,before:hp(r),worldBefore:world(r),walletBefore:r.s.global.MORA,actions:[],encounters:[],seconds:0,lodgingCost:0,returnToDomain};
  try{travel(bucket,region==='몬드'?'MAP_MOND_CITY':'MAP_LIYUE_HARBOR');action(bucket,'PLACE_ENTER',{place:region==='몬드'?'EVT_SCHEDULE_MRC_MOND_INN':'EVT_SCHEDULE_MRC_LIYUE_INN',mode:'SHOP'},1);const stock=region==='몬드'?'STK_INN_MOND':'STK_INN_LIYUE',quote=copy(r.innRecoveryQuote(r.row('19_SHOP_STOCK_DB',stock))),wallet=r.s.global.MORA,receipt=action(bucket,'BUY',{stock,quantity:1},3);bucket.quote=quote;bucket.receipt=copy(receipt);bucket.lodgingCost=wallet-r.s.global.MORA;bucket.afterLodging=hp(r);if(bucket.lodgingCost!==quote.cost||bucket.afterLodging.some(x=>x.hp!==x.maxHp))throw Error('INN_SETTLEMENT_MISMATCH');if(appendToCampaign)row.lodgingReceipts.push({cause,quote,receipt:copy(receipt),paid:bucket.lodgingCost,world:world(r)});if(returnToDomain)travel(bucket,site.map);
  }catch(error){bucket.failed=true;bucket.reason=error.code||error.message;}
  bucket.after=hp(r);bucket.worldAfter=world(r);bucket.walletAfter=r.s.global.MORA;bucket.mora=r.s.global.MORA-bucket.walletBefore;if(appendToCampaign){row.recoveries.push(bucket);row.seconds+=bucket.seconds;}return bucket;
 }
 function nativeMeals(){const bucket={kind:'MEALS',before:hp(r),worldBefore:world(r),actions:[],encounters:[],seconds:0,foodCount:0};let fallback=null;
  for(let pass=0;pass<20;pass++){
   const injured=hp(r).filter(x=>x.hp>0&&x.hp<x.maxHp);if(!injured.length)break;const stock=Object.fromEntries(Object.keys(unitCosts).map(id=>[id,count(r,id)])),meals=[];
   for(const target of injured){const last=r.economyOwner(target.owner).lastMeal,candidates=Object.keys(unitCosts).filter(id=>stock[id]>0&&id!==last).map(id=>({id,heal:r.foodHealingAmount(Number(r.row('14_ITEM_DB',id)[8]),target.owner)})).sort((a,b)=>Math.abs(a.heal-(target.maxHp-target.hp))-Math.abs(b.heal-(target.maxHp-target.hp))||b.heal-a.heal);if(!candidates.length){fallback='FOOD_STOCK_OR_REPEAT_LOCK';continue;}const food=candidates[0].id;stock[food]--;meals.push({owner:target.owner,item:food,variant:'NORMAL'});}
   if(!meals.length){fallback='FOOD_STOCK_OR_REPEAT_LOCK';break;}
   const before=hp(r);try{const out=action(bucket,'MEAL_BATCH',{meals},0);bucket.foodCount+=out.meals.length;row.mealReceipts.push({before,after:hp(r),world:world(r),receipt:copy(out)});}catch(error){fallback=error.code||error.message;break;}
  }
  if(hp(r).some(x=>x.hp>0&&x.hp<x.maxHp))fallback??='FOOD_RECOVERY_INCOMPLETE';bucket.after=hp(r);bucket.worldAfter=world(r);bucket.fallback=fallback;row.recoveries.push(bucket);row.seconds+=bucket.seconds;return fallback;
 }
 for(let i=0;i<limit&&!row.stop;i++){
  if(restNeeded(r)){
   let trip;if(strategy==='INN_ONLY')trip=nativeInn('INN_ONLY');else if(hp(r).some(x=>x.hp<=0))trip=nativeInn('KO_REQUIRES_NATIVE_INN');else{const reason=nativeMeals();if(reason)trip=nativeInn(reason);}
   if(trip?.failed){row.stop='RECOVERY_FAILED';row.reason=trip.reason;break;}
  }
  const reason=r.actionReason('DOMAIN_START',{domain:row.domain,element});if(reason){row.stop='ENTRY_BLOCKED';row.reason=reason;break;}
  const before=hp(r),beforeWorld=world(r),wallet=r.s.global.MORA,materials=count(r,'GROWTH_GEM_'+element);presentationMs=0;inputs=0;r.action('DOMAIN_START',{domain:row.domain,element});
  if(r.s.runtime.materialBudget||r.s.runtime.growthDomain?.materialBudgetVersion!==undefined)throw Error('WEAKENED_COMBAT_PRESENT');
  const enemies=[...r.s.runtime.actors,...(r.s.runtime.enemyReserve||[])].filter(x=>x.side==='ENEMY').map(x=>({source:x.source,hp:x.maxHp,atk:x.atk,def:x.def,spd:x.spd,shield:(x.shields||[]).reduce((n,s)=>n+s.value,0)})),result=policy(r),seconds=presentationMs/1000+inputs*3+6+Number(result.defeatPenalty?.seconds||0);advance((6+Number(result.defeatPenalty?.seconds||0))*1000);
  row.battles.push({index:i+1,before,after:hp(r),beforeWorld,afterWorld:world(r),enemies,result:copy(result),seconds,presentationMs,inputs,materials:count(r,'GROWTH_GEM_'+element)-materials,mora:r.s.global.MORA-wallet});row.seconds+=seconds;row.wins+=result.victory?1:0;row.losses+=result.victory?0:1;trim(r);if(!result.victory)row.stop='FIRST_LOSS';
 }
 row.stop??='VICTORY_LIMIT';row.finalHp=hp(r);row.finalWorld=world(r);row.finalMora=r.s.global.MORA;row.netMora=row.finalMora-startingMora;row.lodgingCount=row.lodgingReceipts.length;row.lodgingMora=row.lodgingReceipts.reduce((n,x)=>n+x.paid,0);row.foodCount=row.mealReceipts.reduce((n,x)=>n+x.receipt.meals.length,0);row.mealActionCount=row.mealReceipts.length;row.foodUsed={};for(const q of row.mealReceipts)for(const m of q.receipt.meals)row.foodUsed[m.item]=(row.foodUsed[m.item]||0)+1;
 row.foodConsumptionCost={craftingMora:0,ingredients:{},npcSaleOpportunityMora:0,globalShopReplacementMora:0,unpricedShopIngredients:[]};for(const [id,n]of Object.entries(row.foodUsed)){const unit=unitCosts[id];row.foodConsumptionCost.craftingMora+=unit.moraPerFood*n;for(const [item,amount]of Object.entries(unit.itemsPerFood))row.foodConsumptionCost.ingredients[item]=(row.foodConsumptionCost.ingredients[item]||0)+amount*n;}
 for(const [id,n]of Object.entries(row.foodConsumptionCost.ingredients)){const value=ingredientValue(r,id,n);row.foodConsumptionCost.npcSaleOpportunityMora+=value.npcSaleValue;if(value.lowestGlobalShopUnit===null)row.foodConsumptionCost.unpricedShopIngredients.push(id);else row.foodConsumptionCost.globalShopReplacementMora+=value.lowestGlobalShopUnit*n;}
 row.finalFoodStock=Object.fromEntries(Object.keys(unitCosts).map(id=>[id,count(r,id)]));row.finalFoodStockValue=Object.entries(row.finalFoodStock).map(([id,n])=>({item:id,name:r.row('14_ITEM_DB',id)[1],quantity:n,paidCookingFeeInStock:unitCosts[id].moraPerFood*n,npcSaleUnit:r.saleUnitPrice({item:id}),npcSaleValue:r.saleUnitPrice({item:id})*n,actualSaleNotExecuted:true}));row.leftoverFoodNpcSaleValue=row.finalFoodStockValue.reduce((n,x)=>n+x.npcSaleValue,0);row.leftoverCookingFeePaid=row.finalFoodStockValue.reduce((n,x)=>n+x.paidCookingFeeInStock,0);row.finalIngredientStock=Object.fromEntries(row.prep.ingredients.map(x=>[x.id,count(r,x.id)]));row.foodLedgerBalanced=Object.keys(unitCosts).every(id=>(row.initialFoodStock[id]||0)===(row.foodUsed[id]||0)+row.finalFoodStock[id]);if(!row.foodLedgerBalanced)throw Error('FOOD_LEDGER_MISMATCH');row.foodRequestedHealing=row.mealReceipts.reduce((n,x)=>n+x.receipt.meals.reduce((m,a)=>m+a.requestedHealing,0),0);row.foodActualHealing=row.mealReceipts.reduce((n,x)=>n+x.receipt.meals.reduce((m,a)=>m+a.healed,0),0);row.foodBondAbsorption=row.mealReceipts.reduce((n,x)=>n+x.receipt.meals.reduce((m,a)=>m+a.absorbed,0),0);row.foodOverhealing=row.foodRequestedHealing-row.foodActualHealing-row.foodBondAbsorption;row.upfrontRecoveryMora=row.prep.craftingMora+row.lodgingMora;row.consumedRecoveryMora=row.foodConsumptionCost.craftingMora+row.lodgingMora;row.recoveryAndPrepSeconds=row.prep.seconds+row.recoveries.reduce((n,x)=>n+x.seconds,0);row.travelEncounterCount=row.prep.encounters.length+row.recoveries.reduce((n,x)=>n+x.encounters.length,0);
 const terminal=nativeInn('ENDPOINT_FULL_HP_CITY',{returnToDomain:false,appendToCampaign:false});row.terminalNormalization={...terminal,rawEndpoint:{hp:row.finalHp,world:row.finalWorld,mora:row.finalMora},endingFullHpCity:!terminal.failed&&terminal.after.every(x=>x.hp===x.maxHp)&&terminal.worldAfter.map===(region==='몬드'?'MAP_MOND_CITY':'MAP_LIYUE_HARBOR'),normalizedSeconds:row.seconds+terminal.seconds,normalizedUpfrontRecoveryMora:row.upfrontRecoveryMora+terminal.lodgingCost,normalizedConsumedRecoveryMora:row.consumedRecoveryMora+terminal.lodgingCost,normalizedFinalMora:r.s.global.MORA};return row;
}
function cases({limit=6}={}){const out=[];for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI'])for(const [level,stage]of [[10,10],[30,30],[55,60]])for(const element of ['PYRO','HYDRO'])for(const strategy of ['INN_ONLY','PREPARED_MEAL_AND_INN'])out.push({level,stage,element,route,strategy,limit});return out;}
function run(campaignCases,{out=DEFAULT_OUT}={}){const snapshot=sourceSnapshot();if(snapshot.growthSha256!==REQUIRED_GROWTH_SHA)throw Error('Native combat/growth source changed; refusing to call this an unchanged-combat comparison.');const data={version:snapshot.packageVersion,tool:'tools/audit_food_campaign_v01617.cjs',sourceSnapshot:snapshot,clockMs:CLOCK_MS,timing:{displaySpeed:2,internalSpeed:1,presentationDivisor:1000,inputSeconds:3,receiptReentrySeconds:6,ordinaryMoveVisualSeconds:1,directRegionMoveVisualSeconds:30,placeEnterLeaveVisualSeconds:1,craftVisualSeconds:1.4,mealFixedVisualSeconds:0,innVisualSeconds:3,networkSecondsExcluded:true},assumptions:{party:PARTY,startingMap:'Regional cooking facility map, both strategies',oneInitialFullHp:true,noBetweenActionArtificialHealing:true,seedSetOncePerCampaign:true,noBetweenActionRngReset:true,realClockAdvancedByModeledDuration:true,worldTimeAndDayCarry:true,recoveryAt:'Before the next domain if any active target is dead or below 50% HP',meals:'At recovery, fill living party members with native MEAL_BATCH and alternate legally. Inn is used for KO, shortage, or an unavailable legal meal.',noArtificialLastRest:true,synthetic:['Ownership and story unlocks','Stated crafted +3/+6 equipment and mid talents','Starting 200000 Mora, excluded from earnings','A single declared batch of initial raw ingredients, excluded from native acquired resources'],ingredientsNotFree:'Actual gather/hunt/fish/processing time is not included; initial inventory is declared synthetic and remaining/consumed quantities plus NPC opportunity and shop replacement valuations are recorded.',inventoryNotRefilled:true,recipeLocksNotBypassed:true,allPreparedFoodsActuallyCrafted:true,preparedFoodCost:'Upfront complete batch payment and amortized consumed-food fee are both shown; leftovers keep their actual inventory value.',excluded:['Getting initial characters, gear and wallet','Raw ingredient acquisition or player-market purchase','Human/menu/network latency beyond a declared 3 seconds per action']},rows:[]};
 data.assumptions.craftingBatchMaximum=5;data.assumptions.endpoint='Raw six-fight fields remain intact. A separate native terminalNormalization moves to the regional city and buys inn recovery to finish at the same full-HP city endpoint, without returning to the domain.';const save=()=>{fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(data,null,2)+'\n');};save();for(const options of campaignCases){const row=campaign(options);data.rows.push(row);save();console.log(JSON.stringify({case:data.rows.length,total:campaignCases.length,level:row.level,stage:row.stage,route:row.route,element:row.element,strategy:row.strategy,wins:row.wins,losses:row.losses,seconds:row.seconds,inns:row.lodgingCount,innMora:row.lodgingMora,foods:row.foodCount,mealActions:row.mealActionCount,upfrontMora:row.upfrontRecoveryMora,consumedMora:row.consumedRecoveryMora,normalizedSeconds:row.terminalNormalization.normalizedSeconds,normalizedConsumedMora:row.terminalNormalization.normalizedConsumedRecoveryMora,normalizedFullHp:row.terminalNormalization.endingFullHpCity,stop:row.stop,reason:row.reason}));}
 data.finishedSourceSnapshot=sourceSnapshot();data.sourcesUnchanged=['growthSha256','economySha256','innSha256','dbSha256','loadedNativeFilesSha256','toolSha256'].every(k=>data.sourceSnapshot[k]===data.finishedSourceSnapshot[k]);data.counts={conditions:data.rows.length,domainBattles:data.rows.reduce((n,x)=>n+x.battles.length,0),domainWins:data.rows.reduce((n,x)=>n+x.wins,0),domainLosses:data.rows.reduce((n,x)=>n+x.losses,0),mealActions:data.rows.reduce((n,x)=>n+x.mealActionCount,0),foodsConsumed:data.rows.reduce((n,x)=>n+x.foodCount,0),lodgingReceipts:data.rows.reduce((n,x)=>n+x.lodgingCount,0),travelEncounters:data.rows.reduce((n,x)=>n+x.travelEncounterCount,0),terminalLodgingReceipts:data.rows.filter(x=>x.terminalNormalization.receipt).length,terminalTravelEncounters:data.rows.reduce((n,x)=>n+x.terminalNormalization.encounters.length,0),terminalFullHpCityEndpoints:data.rows.filter(x=>x.terminalNormalization.endingFullHpCity).length};data.comparisons=[];
 for(const inn of data.rows.filter(x=>x.strategy==='INN_ONLY')){const food=data.rows.find(x=>x.strategy==='PREPARED_MEAL_AND_INN'&&x.level===inn.level&&x.stage===inn.stage&&x.element===inn.element&&x.route===inn.route&&x.seed===inn.seed);if(!food)continue;const ni=inn.terminalNormalization,nf=food.terminalNormalization;data.comparisons.push({level:inn.level,stage:inn.stage,element:inn.element,route:inn.route,domainWins:{inn:inn.wins,food:food.wins},seconds:{inn:inn.seconds,food:food.seconds,saved:inn.seconds-food.seconds},lodgingCount:{inn:inn.lodgingCount,food:food.lodgingCount},mora:{innRecovery:inn.upfrontRecoveryMora,foodUpfrontRecovery:food.upfrontRecoveryMora,foodConsumedRecovery:food.consumedRecoveryMora,foodConsumedWithNpcIngredientOpportunity:food.consumedRecoveryMora+food.foodConsumptionCost.npcSaleOpportunityMora,foodConsumedWithGlobalShopIngredientReplacement:food.consumedRecoveryMora+food.foodConsumptionCost.globalShopReplacementMora,unpricedShopIngredients:food.foodConsumptionCost.unpricedShopIngredients},sameFullHpCityEndpoint:{bothFinishedFullHpCity:ni.endingFullHpCity&&nf.endingFullHpCity,seconds:{inn:ni.normalizedSeconds,food:nf.normalizedSeconds,saved:ni.normalizedSeconds-nf.normalizedSeconds},mora:{innRecovery:ni.normalizedUpfrontRecoveryMora,foodUpfrontRecovery:nf.normalizedUpfrontRecoveryMora,foodConsumedRecovery:nf.normalizedConsumedRecoveryMora,foodConsumedWithNpcIngredientOpportunity:nf.normalizedConsumedRecoveryMora+food.foodConsumptionCost.npcSaleOpportunityMora,foodConsumedWithGlobalShopIngredientReplacement:nf.normalizedConsumedRecoveryMora+food.foodConsumptionCost.globalShopReplacementMora}},foods:food.foodCount,mealActions:food.mealActionCount,foodLeftover:food.finalFoodStock,leftoverFoodNpcSaleValue:food.leftoverFoodNpcSaleValue,leftoverCookingFeePaid:food.leftoverCookingFeePaid,openingEnemiesIdentical:JSON.stringify(inn.battles[0]?.enemies)===JSON.stringify(food.battles[0]?.enemies),openingHpIdentical:JSON.stringify(inn.combatStartingHp)===JSON.stringify(food.combatStartingHp),rngAfterPreparationMatches:inn.combatStartingWorld.rng===food.combatStartingWorld.rng,bothFinished:inn.wins===inn.limit&&food.wins===food.limit});}save();return data;
}
if(require.main===module){const file=option('--cases'),campaignCases=file?JSON.parse(fs.readFileSync(file)):cases({limit:Number(option('--limit')||6)});run(campaignCases,{out:option('--out')||DEFAULT_OUT});}
module.exports={campaign,cases,run,sourceSnapshot,PARTY,DEFAULT_RECIPES,CLOCK_MS};
