/* Build first. Real paused playback must fit the reserved command area at every size. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'evidence/v01522/ui'),checks=[];
const server=cp.spawn(process.env.PYTHON||'python',['-m','http.server','19123','--bind','127.0.0.1','--directory',path.join(root,'dist')],{stdio:'ignore'});let browser;
async function run(){
 await new Promise(r=>setTimeout(r,400));browser=await chromium.launch({...(process.env.CRPG_BROWSER_EXECUTABLE?{executablePath:process.env.CRPG_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--single-process']});
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning'&&m.text().startsWith('battle fx'))errors.push(m.text());});
 await page.goto('http://127.0.0.1:19123/?frame=0');await page.waitForFunction(()=>!!window.CRPGRuntime&&!!saveStore);
 await page.evaluate(()=>{game=new CRPGRuntime.Runtime(CRPG_DATA);game.newGame({name:'재생 검증',route:'ROUTE_ISEKAI',seed:27});Object.assign(game.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',CURRENT_MAP_ID:'MAP_MOND_PLAINS',SCREEN_MODE:'LOCATION'});for(const k of ['storyJourney','storyBreak','storyArrival','storyContext'])delete game.s[k];game.prepareStory();itemPresenter=CRPGInventoryPresenter.create(game.db,MANIFEST);activeSaveSlot=null;saveFailed=false;busy=false;game.startBattle('EG_MOND_HILI_PATROL','RANDOM');const target=game.s.runtime.actors.find(a=>a.side==='ENEMY');target.hp=target.maxHp=1000;game.action('COMBAT_BEGIN');render();});
 await page.locator('[data-card-id="PLAYER_BASIC_GUARD"]').click();await page.locator('.battle-execute>button').click();await page.waitForFunction(()=>GameEffects.dock?.querySelector('.playback-outcomes')?.textContent.includes('→'));await page.getByRole('button',{name:'일시정지',exact:true}).click();
 for(const [width,height] of [[390,844],[360,640],[844,390],[1440,900],[1024,600]]){
  await page.setViewportSize({width,height});await page.waitForTimeout(150);const result=await page.evaluate(()=>{const dock=document.querySelector('.combat-playback'),d=dock.getBoundingClientRect(),c=document.querySelector('.battle-command').getBoundingClientRect(),b=document.querySelector('.combat-panel').getBoundingClientRect(),controls=[...dock.querySelectorAll('button,input')].filter(x=>getComputedStyle(x).display!=='none');return {fits:Math.abs(d.top-c.top)<2&&Math.abs(d.left-c.left)<2&&d.bottom<=c.bottom+2&&d.right<=c.right+2,board:b.bottom<=innerHeight,controls:controls.every(x=>{const r=x.getBoundingClientRect();return r.top>=d.top-1&&r.left>=d.left-1&&r.right<=d.right+1&&r.bottom<=d.bottom+1;}),scroll:document.body.scrollHeight<=innerHeight+1};});assert(Object.values(result).every(Boolean),JSON.stringify({width,height,...result}));checks.push({width,height,...result});await page.screenshot({path:path.join(out,'playback-'+width+'x'+height+'.png')});
 }
 await page.getByRole('button',{name:'계속 재생',exact:true}).click();await page.waitForFunction(()=>!busy,null,{timeout:120000});await page.evaluate(()=>{window.liveStatusChecks=[];const previous=GameEffects.showAction;GameEffects.showAction=function(frame){const result=previous.call(this,frame);for(const t of frame.targets||[])for(const e of t.events||[])if(e.statusApplied)liveStatusChecks.push({id:e.statusApplied.id,actor:frame.actorId,visible:!!this.actorNode(t.targetId)?.querySelector('.st-chip[data-id="'+e.statusApplied.id+'"]')});return result;};});await page.locator('[data-card-id="PLAYER_ISEKAI_E"]').click();const target=await page.evaluate(()=>game.combatCards().find(c=>c.id==='PLAYER_ISEKAI_E').targets.find(t=>game.s.runtime.actors.find(a=>a.id===t.id)?.side==='ENEMY').id);await page.locator('.combatant-row[data-actor-id="'+target+'"]').click();await page.locator('.battle-execute>button').click();await page.waitForFunction(()=>!busy,null,{timeout:120000});const statuses=await page.evaluate(()=>liveStatusChecks);assert(statuses.some(x=>x.id==='STATUS_ISEKAI_EXPOSED'&&x.actor==='PLAYER_CUSTOM'&&x.visible),'actual E debuff appears in its playback frame: '+JSON.stringify({statuses,errors,result:await page.evaluate(()=>lastResult)}));checks.push({liveStatus:statuses});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'playback-results.json'),JSON.stringify({checks,errors},null,2));console.log('PASS playback bounds and real pause/resume at five viewport sizes');
}
run().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{server.kill();await browser?.close();});
