'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright')));}
const root=path.resolve(__dirname,'..'),out=path.join(root,'evidence/v01523/tutorial');fs.mkdirSync(out,{recursive:true});
(async()=>{const server=cp.spawn('python',['-m','http.server','19123','--bind','127.0.0.1','--directory',path.join(root,'dist')],{stdio:'ignore'});let browser;const findings=[];
 try{browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:fs.existsSync('/tmp/chromium')?{executablePath:'/tmp/chromium'}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--use-gl=angle','--use-angle=swiftshader','--single-process']});
 const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});if(process.env.TUTORIAL_DEBUG)page.on('console',m=>console.log('BROWSER',m.text()));
 for(const [width,height]of [[1280,800],[844,390],[390,844]]){
 await page.setViewportSize({width,height});errors.length=0;await page.goto('http://127.0.0.1:19123/?frame=0');await page.waitForFunction(()=>!!window.CRPGRuntime&&!!saveStore);
  await page.evaluate(()=>{game=new CRPGRuntime.Runtime(CRPG_DATA);game.newGame({route:'ROUTE_TRAVELER',name:'첫걸음',seed:27});for(let i=0;i<100&&!game.s.storyJourney;i++){const n=game.storyNode(),cs=game.storyChoices();game.action(cs.length?'STORY_CHOICE':n[5]==='INPUT_TEXT'?'STORY_NAME':'STORY_NEXT',cs.length?{node:cs[0][4]}:n[5]==='INPUT_TEXT'?{name:'첫걸음'}:{node:n[4]});}game.s.global.ENCOUNTER_COOLDOWN=100;itemPresenter=CRPGInventoryPresenter.create(game.db,MANIFEST);activeSaveSlot=null;saveFailed=false;lastSaveError='';busy=false;render();});
  async function state(){await page.waitForTimeout(100);return page.evaluate(()=>({step:game.tutorialDirective()?.id,screen:game.s.global.SCREEN_MODE,target:tutorialTarget?.outerHTML.slice(0,450),text:document.querySelector('#tutorial-tour')?.innerText,done:game.tutorialState().done,phase:game.playPhase(),busy,error:lastSaveError}));}
  async function click(){try{await page.waitForFunction(()=>!!tutorialTarget?.isConnected&&!busy,null,{timeout:10000});}catch(e){console.log('MISSING',await state(),await page.locator('#modal').innerText());await page.screenshot({path:path.join(out,width+'-missing.png')});throw e;}const before=await state();console.log(width,JSON.stringify(before));const target=page.locator('.tutorial-target');assert.equal(await target.count(),1);await target.click();await page.waitForFunction(()=>!busy,null,{timeout:120000});return before;}
  // The actual map pin, then the actual move button. Nothing else may consume an action.
  assert.equal((await state()).step,'move');const revision=await page.evaluate(()=>game.s.global.SAVE_REVISION);await page.evaluate(()=>document.querySelector('[data-screen="PARTY"]')?.click());await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>game.s.global.SAVE_REVISION),revision);
  await page.screenshot({path:path.join(out,width+'-move.png')});await click();await click();assert.equal((await state()).step,'arrival');await click();
  // Dialogue remains the game's authored dialogue. Advance it natively to the real combat gate.
  await page.evaluate(()=>{for(let i=0;i<150&&!game.s.battlePreparation;i++){const n=game.storyNode(),cs=game.storyChoices();if(game.s.storyJourney)throw Error('unexpected second journey');game.action(cs.length?'STORY_CHOICE':'STORY_NEXT',cs.length?{node:cs[0][4]}:{node:n[4]});}render();});
  if(process.env.TUTORIAL_DEBUG)await page.evaluate(()=>{const x=game.equipmentPreview;game.equipmentPreview=function(...a){console.log('preview-start',...a);const r=x.apply(this,a);console.log('preview-end');return r;};const y=showModal;showModal=function(...a){console.log('modal-start',a[0]);const r=y.apply(this,a);console.log('modal-end');return r;};});assert.equal((await state()).step,'party');let clicks=0;while((await state()).step!=='combatStart'&&clicks++<14){await click();}assert.equal((await state()).step,'combatStart','preparation spotlight must lead into the real fight');assert(await page.evaluate(()=>game.s.runtime.actors.some(a=>a.source==='MOND_AMBER')));
  await page.screenshot({path:path.join(out,width+'-start.png')});await click();assert.equal((await state()).step,'combatAttack');await click();assert((await state()).target.includes('combatant-row'));
  // Information buttons inside an enemy card are not an alternate route out of the forced target step.
  await page.evaluate(()=>tutorialTarget.querySelector('.enemy-info-button')?.click());assert.equal(await page.locator('#modal[open]').count(),0);if(width===390){console.log('KEYBOARD',await page.evaluate(()=>({focus:document.activeElement?.outerHTML.slice(0,120),target:tutorialTarget?.tagName})));await page.keyboard.press('Enter');await page.waitForTimeout(100);}else await click();assert((await state()).target.includes('data-action="COMBAT"'));await page.screenshot({path:path.join(out,width+'-attack.png')});await click();assert(await page.evaluate(()=>game.tutorialState().done.combatAttack));
  assert(!await page.locator('.scenario-guide').count());assert.equal(errors.length,0,errors.join('\n'));findings.push({width,height,passed:true,final:await state()});
 }
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(findings,null,2)+'\n');console.log('PASS all three viewport flows, outside input blocking and actual first-fight commands');
 }finally{server.kill();await browser?.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
