// Generate the Liyue colour layer for source/shell.css. Run `node tools/gen_liyue_theme.cjs` after editing colours
// in shell.css. Every rule whose declarations use the night-blue surface or slate ink colours gets a
// body.teyvat[data-region=liyue] twin with the same lightness in warm brown, and the gold trim leans orange. Images
// are untouched. The block between the markers is replaced and moved to the end of the file, so it can be re-run.
const fs=require('fs');
const file=require('path').join(__dirname,'..','source','shell.css');
const START='/* ---------- 리월 색 (generated by tools/gen_liyue_theme.cjs) ---------- */',END='/* ---------- /리월 색 ---------- */';
let css=fs.readFileSync(file,'utf8');
const cut=css.indexOf(START);if(cut>=0){const end=css.indexOf(END,cut);css=(css.slice(0,cut).replace(/\s+$/,'\n')+(end>=0?css.slice(end+END.length):'')).replace(/\s+$/,'\n');}
function rgb2hsl(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),l=(mx+mn)/2;let h=0,s=0;if(mx!==mn){const d=mx-mn;s=l>.5?d/(2-mx-mn):d/(mx+mn);h=mx===r?(g-b)/d+(g<b?6:0):mx===g?(b-r)/d+2:(r-g)/d+4;h*=60;}return [h,s,l];}
function hsl2rgb(h,s,l){h/=360;const f=t=>{t=(t+1)%1;return t<1/6?p+(q-p)*6*t:t<1/2?q:t<2/3?p+(q-p)*(2/3-t)*6:p;};const q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;return s===0?[l,l,l].map(v=>Math.round(v*255)):[f(h+1/3),f(h),f(h-1/3)].map(v=>Math.round(v*255));}
// Night blue / slate (dark, blue hue) -> warm brown of the same lightness; gold trim -> a little more orange.
function warm(r,g,b){const [h,s,l]=rgb2hsl(r,g,b);
 if(h>=185&&h<=270&&l<.48&&s>=.04)return hsl2rgb(28,Math.min(.62,s*1.18+.03),l*1.02);
 if(h>=34&&h<=52&&s>=.25&&l>=.5&&l<=.85)return hsl2rgb(31,Math.min(.85,s*1.2),l);
 return null;}
function mapColors(value){let changed=false;
 const out=value.replace(/rgba?\((\d+),\s*(\d+),\s*(\d+)(,\s*[\d.]+)?\)|#([0-9a-fA-F]{6})\b|#([0-9a-fA-F]{3})\b/g,(m,r,g,b,a,h6,h3)=>{let R,G,B;if(h6){R=parseInt(h6.slice(0,2),16);G=parseInt(h6.slice(2,4),16);B=parseInt(h6.slice(4,6),16);}else if(h3){R=parseInt(h3[0]+h3[0],16);G=parseInt(h3[1]+h3[1],16);B=parseInt(h3[2]+h3[2],16);}else{R=+r;G=+g;B=+b;}
  const w=warm(R,G,B);if(!w)return m;changed=true;return a?`rgba(${w[0]},${w[1]},${w[2]}${a.replace(/\s/g,'')})`:'#'+w.map(v=>v.toString(16).padStart(2,'0')).join('');});
 return changed?out:null;}
// Minimal CSS walk: top-level rules and rules inside @media/@supports; @keyframes and @font-face are skipped.
function walk(text){const blocks=[];let i=0;
 while(i<text.length){const open=text.indexOf('{',i);if(open<0)break;const head=text.slice(i,open).replace(/\/\*[\s\S]*?\*\//g,'').trim();let depth=1,j=open+1;while(j<text.length&&depth){if(text[j]==='{')depth++;else if(text[j]==='}')depth--;j++;}
  const body=text.slice(open+1,j-1);
  if(/^@(media|supports)/.test(head))blocks.push({at:head,rules:walk(body).map(r=>r)});
  else if(!head.startsWith('@'))blocks.push({sel:head,body});
  i=j;}
 return blocks;}
function splitSelectors(sel){const out=[];let depth=0,cur='';for(const ch of sel){if(ch==='(')depth++;if(ch===')')depth--;if(ch===','&&depth===0){out.push(cur.trim());cur='';}else cur+=ch;}if(cur.trim())out.push(cur.trim());return out;}
// Colours that mean something stay the same in both regions: item rarity (the 3★ blue and 4★ purple cards turned brown at
// the top in Liyue — user: 「아이템들 색깔이 이상해 리월에서 뒤 UI 색에 영향받나본데」) and element colours. Their rules get a
// Liyue twin with the colours unchanged, so the warm twin of a plain rule (the same specificity, later) cannot cover them.
const MEANING=/\.tier-\d|rarity|data-aura|data-element|\.el-/,MEANING_PROP=/^--(rar-|aura)/,COLORISH=/#[0-9a-fA-F]{3,8}\b|rgba?\(|gradient\(|var\(--rar/;
const twin=s=>s.replace(/^body\.teyvat/,'body.teyvat[data-region=liyue]');
function emit(rules){let out='';for(const r of rules){
 if(r.at){const inner=emit(r.rules);if(inner)out+=r.at+'{\n'+inner+'}\n';continue;}
 const parts=splitSelectors(r.sel).filter(s=>s.startsWith('body.teyvat')&&!s.includes('data-region'));if(!parts.length)continue;
 const plain=parts.filter(s=>!MEANING.test(s)),meant=parts.filter(s=>MEANING.test(s));
 const decls=r.body.replace(/\/\*[\s\S]*?\*\//g,'').split(';').map(d=>d.trim()).filter(Boolean),warmed=[],kept=[];
 for(const d of decls){const k=d.indexOf(':');if(k<0)continue;const prop=d.slice(0,k).trim(),val=d.slice(k+1).trim(),m=mapColors(val);
  if(COLORISH.test(val))kept.push(prop+':'+val);if(m&&!MEANING_PROP.test(prop))warmed.push(prop+':'+m);}
 if(plain.length&&warmed.length)out+=plain.map(twin).join(',')+'{'+warmed.join(';')+'}\n';
 if(meant.length&&kept.length)out+=meant.map(twin).join(',')+'{'+kept.join(';')+'}\n';}
 return out;}
const generated=emit(walk(css));
const accent='body.teyvat[data-region=liyue]{--acc:#f0a04b;--acc-2:#ffd3a1;--acc-rgb:240,160,75;--acc-deep:#5c3613}\n';
css=css.replace(/\s+$/,'\n')+'\n'+START+'\n/* 리월(몬드와 같은 구성, 남색 바탕 → 같은 밝기의 갈색, 금색 테두리 → 주황빛 금색, 강조색 → 주황). */\n'+accent+generated+END+'\n';
fs.writeFileSync(file,css);
console.log('rules',generated.split('\n').filter(Boolean).length,'bytes',generated.length);
