/* Disposable preview fixtures; generated pages never enter the deployment pack. */
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),src=path.join(root,'source'),db=JSON.parse(fs.readFileSync(path.join(root,'content/db.json'))),ctx=vm.createContext({console});
const scripts=[...fs.readFileSync(path.join(src,'index.html'),'utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(f=>f.startsWith('runtime')||f==='save_adapter.js');
for(const f of scripts)vm.runInContext(fs.readFileSync(path.join(src,f),'utf8'),ctx,{filename:f});
ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db)});
function fresh(name,level=1){const r=new ctx.CRPGRuntime.Runtime(db);r.newGame({name,route:'ROUTE_ISEKAI',seed:82194257,saveId:'V09-QA-'+name});for(let i=0;i<300&&r.playPhase()!=='FREE';i++){const choices=r.storyChoices();if(choices.length)r.action('STORY_CHOICE',{node:choices[0][4]});else if(r.storyNode()[5]==='INPUT_TEXT')r.action('STORY_NAME',{name});else r.action('STORY_NEXT',{node:r.storyActiveNodeId()});}r.s.global.PLAYER_LEVEL_STATE=level;r.s.global.PLAYER_XP_STATE=0;r.s.global.MORA=5000;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;return r;}
const fixtures={};
const shop=fresh('상점 검증',7);shop.action('PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP',mode:'SHOP'});fixtures.shop=JSON.parse(shop.serialize());
const guild=fresh('길드 검증');guild.action('PLACE_ENTER',{place:'EVT_SCHEDULE_NPC_MOND_KATHERYNE'});fixtures.guild=JSON.parse(guild.serialize());
const field=fresh('탐험 검증',3);field.s.global.CURRENT_MAP_ID='MAP_MOND_WINDRISE';field.action('MENU',{screen:'LOCATION'});fixtures.field=JSON.parse(field.serialize());
const battle=fresh('전투 검증');battle.action('PARTY',{char:'MOND_AMBER',slot:2});battle.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';battle.s.global.PRNG_STATE=82194257;battle.startBattle('EG_MOND_HILI_PATROL','RANDOM');fixtures.battle=JSON.parse(battle.serialize());
const party=fresh('편성 검증');party.action('PARTY',{char:'MOND_AMBER',slot:2});party.action('MENU',{screen:'PARTY'});fixtures.party=JSON.parse(party.serialize());
let page=fs.readFileSync(path.join(root,'dist/index.html'),'utf8');fs.writeFileSync(path.join(root,'dist/qa-v09.html'),page);
fs.writeFileSync(path.join(root,'dist/qa-v09-mobile.html'),'<!doctype html><meta charset="utf-8"><title>모바일 화면 검사</title><iframe title="게임" src="qa-v09.html" style="width:390px;height:844px;border:0"></iframe>');
const html=`<!doctype html><meta charset="utf-8"><title>0.9 화면 검증</title><link rel="stylesheet" href="style.css"><main style="display:block"><h1>0.9 격리된 검증 저장</h1><p>합성 저장을 새 슬롯에 추가합니다.</p>${Object.keys(fixtures).map(k=>'<button data-fixture="'+k+'">'+k+' 검증 저장 추가</button>').join('')}<p id="status" role="status"></p><a href="qa-v09.html">검증 게임 열기</a></main><script src="data.js"></script><script src="assets.js"></script>${scripts.map(f=>'<script src="'+f+'"></script>').join('')}<script>const fixtures=${JSON.stringify(fixtures).replace(/</g,'\\u003c')};CRPGRelationships.install(CRPGRuntime,{events:CRPGRelationships.catalogFromDB(CRPG_DATA),activities:CRPGRelationships.activitiesFromDB(CRPG_DATA)});for(const button of document.querySelectorAll('[data-fixture]'))button.onclick=async()=>{try{const store=new CRPGSave.SaveAdapter({contentVersion:CRPG_MANIFEST.saveCompatibilityVersion,validate:s=>new CRPGRuntime.Runtime(CRPG_DATA,s).s});await store.open();await store.save('qa-v09-'+button.dataset.fixture+'-'+Date.now(),fixtures[button.dataset.fixture],{expectedSlotRevision:0});store.close?.();document.getElementById('status').textContent='저장 완료 · '+button.dataset.fixture;}catch(e){document.getElementById('status').textContent=e.message;}};</script>`;
fs.writeFileSync(path.join(root,'dist/qa-v09-fixtures.html'),html);console.log('Prepared disposable v0.9 preview pages');
