/* Disposable preview fixtures; generated pages never enter the deployment pack. */
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),src=path.join(root,'source'),db=JSON.parse(fs.readFileSync(path.join(root,'content/db.json'))),ctx=vm.createContext({console});
const scripts=[...fs.readFileSync(path.join(src,'index.html'),'utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(f=>f.startsWith('runtime')||f==='save_adapter.js');
for(const f of scripts)vm.runInContext(fs.readFileSync(path.join(src,f),'utf8'),ctx,{filename:f});
ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db)});
function fresh(name,level=1){const r=new ctx.CRPGRuntime.Runtime(db);r.newGame({name,route:'ROUTE_ISEKAI',seed:82194257,saveId:'V010-QA-'+name});for(let i=0;i<300&&r.playPhase()!=='FREE';i++){const choices=r.storyChoices();if(choices.length)r.action('STORY_CHOICE',{node:choices[0][4]});else if(r.storyNode()[5]==='INPUT_TEXT')r.action('STORY_NAME',{name});else r.action('STORY_NEXT',{node:r.storyActiveNodeId()});}r.s.global.PLAYER_LEVEL_STATE=level;r.s.global.PLAYER_XP_STATE=0;r.s.global.MORA=5000;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;return r;}
const fixtures={};
const fishing=fresh('낚시 검증');fishing.s.global.CURRENT_MAP_ID='MAP_CRPG_CIDER_BANK';fishing.giveItem('TRPG_FISHING_ROD',1);fishing.giveItem('CRPG_FRUIT_BAIT',6);fishing.action('MENU',{screen:'LOCATION'});fixtures.fishing=JSON.parse(fishing.serialize());
const mining=fresh('광산 검증');mining.s.global.CURRENT_MAP_ID='MAP_CRPG_MOND_QUARRY';mining.action('MENU',{screen:'LOCATION'});fixtures.mining=JSON.parse(mining.serialize());
const cooking=fresh('재료 검증');cooking.giveItem('ING_BIRD_EGG',6);cooking.giveItem('ING_SWEET_FLOWER',5);cooking.giveItem('ING_FOWL',5);cooking.giveItem('ING_FLOUR',3);cooking.action('MENU',{screen:'INVENTORY'});fixtures.cooking=JSON.parse(cooking.serialize());
const level=fresh('성장 검증');level.s.global.PLAYER_HP_CURRENT=1;level.s.global.PLAYER_XP_STATE=299;level.giveItem('MAT_CHAR_EXP_WANDERER',1);level.action('MENU',{screen:'INVENTORY'});fixtures.level=JSON.parse(level.serialize());
const wait=fresh('대기 검증');wait.action('MENU',{screen:'LOCATION'});fixtures.wait=JSON.parse(wait.serialize());
for(const [key,name,place]of [['sara','식당 이야기 검증','EVT_SCHEDULE_NPC_MOND_SARA'],['tavern','주점 이야기 검증','EVT_CRPG_ANGELS_SHARE']]){const r=new ctx.CRPGRuntime.Runtime(db);r.newGame({name,route:'ROUTE_TRAVELER',seed:82194257,saveId:'V010-QA-'+key});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:'MAP_MOND_CITY',STORY_MENU_POLICY:'',WORLD_TIME:'12:00',MORA:5000});r.prepareStory();r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;r.action('PLACE_ENTER',{place});fixtures[key]=JSON.parse(r.serialize());}
let page=fs.readFileSync(path.join(root,'dist/index.html'),'utf8');fs.writeFileSync(path.join(root,'dist/qa-v010.html'),page);
fs.writeFileSync(path.join(root,'dist/qa-v010-mobile.html'),'<!doctype html><meta charset="utf-8"><title>모바일 화면 검사</title><iframe title="게임" src="qa-v010.html" style="width:390px;height:844px;border:0"></iframe>');
const html=`<!doctype html><meta charset="utf-8"><title>0.10 화면 검증</title><link rel="stylesheet" href="style.css"><main style="display:block"><h1>0.10 격리된 검증 저장</h1><p>합성 저장을 새 슬롯에 추가합니다.</p>${Object.keys(fixtures).map(k=>'<button data-fixture="'+k+'">'+k+' 검증 저장 추가</button>').join('')}<p id="status" role="status"></p><a href="qa-v010.html">검증 게임 열기</a></main><script src="data.js"></script><script src="assets.js"></script>${scripts.map(f=>'<script src="'+f+'"></script>').join('')}<script>const fixtures=${JSON.stringify(fixtures).replace(/</g,'\\u003c')};CRPGRelationships.install(CRPGRuntime,{events:CRPGRelationships.catalogFromDB(CRPG_DATA),activities:CRPGRelationships.activitiesFromDB(CRPG_DATA)});for(const button of document.querySelectorAll('[data-fixture]'))button.onclick=async()=>{try{const store=new CRPGSave.SaveAdapter({contentVersion:CRPG_MANIFEST.saveCompatibilityVersion,validate:s=>new CRPGRuntime.Runtime(CRPG_DATA,s).s});await store.open();await store.save('qa-v010-'+button.dataset.fixture+'-'+Date.now(),fixtures[button.dataset.fixture],{expectedSlotRevision:0});store.close?.();document.getElementById('status').textContent='저장 완료 · '+button.dataset.fixture;}catch(e){document.getElementById('status').textContent=e.message;}};</script>`;
fs.writeFileSync(path.join(root,'dist/qa-v010-fixtures.html'),html);console.log('Prepared disposable v0.10 preview pages');
