'use strict';
// Rebuild the paired observational summary from native audit JSON. No game calls.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const arg=k=>{const i=process.argv.indexOf(k);return i<0?undefined:process.argv[i+1];};
const read=p=>JSON.parse(fs.readFileSync(p));
const before=read(arg('--before')),parts=(arg('--after')||'').split(',').filter(Boolean).map(read),cases=read(arg('--cases'));
const after={...parts[0],rows:parts.flatMap(p=>p.rows),errors:parts.flatMap(p=>p.errors||[])};
const key=r=>[r.level,r.kind,r.key,r.support,r.seed,r.recoveryPolicy,r.enhance,r.talent??'MODERATE'].join('|');
const map=rows=>{const m=new Map(rows.map(r=>[key(r),r]));assert.equal(m.size,rows.length,'unique condition keys');return m;};
const bm=map(before.rows),am=map(after.rows),cm=map(cases);assert.deepEqual([...bm.keys()].sort(),[...cm.keys()].sort());assert.deepEqual([...am.keys()].sort(),[...cm.keys()].sort());assert.equal(before.errors?.length||0,0);assert.equal(after.errors.length,0);
const sum=(a,fn)=>a.reduce((s,x)=>s+fn(x),0),median=a=>{a=a.filter(x=>Number.isFinite(x)).sort((x,y)=>x-y);return a.length?(a[Math.floor((a.length-1)/2)]+a[Math.ceil((a.length-1)/2)])/2:null;};
const hp=a=>sum(a,x=>x.hp)/sum(a,x=>x.maxHp);
function packetCheck(data){let battles=0;for(const r of data.rows)for(const b of r.battles){battles++;assert.equal(sum(b.heals,x=>x.effective),b.effectiveHealing);assert.equal(b.effectiveHealing,b.healingBeforeReward,'native log agrees with effective Runtime.heal returns');for(const h of b.heals)assert.equal(h.after-h.before,h.effective);}return battles;}
function metrics(rows){const battles=rows.flatMap(r=>r.battles),first=rows.map(r=>r.battles[0]),clear=rows.filter(r=>r.wins===8&&!r.finalRecoveryFailure);
 return{conditions:rows.length,actualBattles:battles.length,wins:sum(rows,r=>r.wins),losses:sum(rows,r=>r.losses),firstWins:sum(first,b=>Number(b.win)),eightWins:clear.length,koEvents:sum(rows,r=>r.mainKoEvents),effectiveHealing:sum(rows,r=>r.mainEffectiveHealing),hpDamage:sum(rows,r=>r.mainAllyHpDamage),firstEffectiveHealing:sum(first,b=>b.effectiveHealing),firstHpDamage:sum(first,b=>b.allyHpDamage),firstKo:sum(first,b=>b.koEvents),firstMedianHpBeforeReward:median(first.map(b=>hp(b.beforeReward))),firstMedianHpAfterReward:median(first.map(b=>hp(b.after))),rewardHpDeltaNet:sum(battles,b=>sum(b.rewardHpDelta,x=>x.delta||0)),levelupPositiveHp:sum(battles,b=>sum(b.rewardHpDelta,x=>x.levelAfter>x.levelBefore?Math.max(0,x.delta||0):0)),nonLevelupPositiveHp:sum(battles,b=>sum(b.rewardHpDelta,x=>x.levelAfter===x.levelBefore?Math.max(0,x.delta||0):0)),rewardHpNegativeClip:sum(battles,b=>sum(b.rewardHpDelta,x=>Math.min(0,x.delta||0))),levelupRewardEvents:sum(battles,b=>b.rewardHpDelta.filter(x=>x.levelAfter>x.levelBefore).length),finalRecoveryFailures:rows.filter(r=>r.finalRecoveryFailure).length,clearMedianHp:median(clear.map(r=>r.afterMainHpRatio)),clearMedianActualInnMora:median(clear.map(r=>r.lodgingMora)),clearZeroActualInn:clear.filter(r=>r.lodgingMora===0).length};}
const group=[];for(const level of [...new Set(cases.map(r=>r.level))])for(const support of ['Barbara','Jean','Sucrose']){
 const b=before.rows.filter(r=>r.level===level&&r.support===support),a=after.rows.filter(r=>r.level===level&&r.support===support),matched=a.filter(r=>r.wins===8&&!r.finalRecoveryFailure&&bm.get(key(r)).wins===8&&!bm.get(key(r)).finalRecoveryFailure);
 group.push({level,support,before:metrics(b),after:metrics(a),bothEightWins:matched.length,matchedEightMedianInnBefore:median(matched.map(r=>bm.get(key(r)).lodgingMora)),matchedEightMedianInnAfter:median(matched.map(r=>r.lodgingMora))});
}
const summary={schema:'healing-v01619-paired-native-1',beforeFingerprint:before.fingerprint,afterFingerprints:[...new Set(parts.map(p=>p.fingerprint))],cases:cases.length,checks:{conditionKeysExact:true,errorsZero:true,beforeNativeHealBattles:packetCheck(before),afterNativeHealBattles:packetCheck(after)},definitions:{first:'Exactly the first full-HP native fight for each case; comparable denominator.',carry:'Up to eight native wins with no intermediate recovery, then actual MOVE/BUY at a legal inn. A wipe is a failure, not zero-cost recovery.',healing:'Effective Runtime.heal returns are checked against native pre-reward heal log and target HP delta. Post talent/rhythm/trait nominal is separately available in after event rows.',hp:'Before-reward and after-reward HP separated. Level-up/reward HP delta is not counted as skill healing.',cost:'Actual legal inn receipt, including incidental outbound fights; only both-eight-win/valid-endpoint cases compared for same success target.',limitations:'Native fixed 4-person representative composition, two seeds, legal tiers and moderate talents; eight unrecovered repetitions intentionally test persistence rather than mandatory first-clear balance. Total healing/incoming across all campaigns have unequal fight counts.'},overall:{before:metrics(before.rows),after:metrics(after.rows)},supports:['Barbara','Jean','Sucrose'].map(s=>({support:s,before:metrics(before.rows.filter(r=>r.support===s)),after:metrics(after.rows.filter(r=>r.support===s))})),byLevelSupport:group};
const out=arg('--out');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(summary,null,2)+'\n');
const fields=['condition','level','kind','support','seed','enhance','beforeFirstWin','afterFirstWin','beforeWins','afterWins','beforeKO','afterKO','beforeHealing','afterHealing','beforeDamage','afterDamage','beforeEndHp','afterEndHp','beforeActualInn','afterActualInn','beforeRecoveryFailure','afterRecoveryFailure'];
const quote=x=>'"'+String(x??'').replaceAll('"','""')+'"',lines=[fields.map(quote).join(',')];
for(const spec of cases){const k=key(spec),b=bm.get(k),a=am.get(k),valid=r=>r.finalRecoveryFailure?'':r.lodgingMora;lines.push([k,a.level,a.kind,a.support,a.seed,a.enhance,b.battles[0].win,a.battles[0].win,b.wins,a.wins,b.mainKoEvents,a.mainKoEvents,b.mainEffectiveHealing,a.mainEffectiveHealing,b.mainAllyHpDamage,a.mainAllyHpDamage,b.afterMainHpRatio,a.afterMainHpRatio,valid(b),valid(a),JSON.stringify(b.finalRecoveryFailure||null),JSON.stringify(a.finalRecoveryFailure||null)].map(quote).join(','));}
fs.writeFileSync(out.replace(/\.json$/,'.csv'),lines.join('\n')+'\n');console.log(JSON.stringify({cases:summary.cases,before:summary.overall.before,after:summary.overall.after},null,2));
