import gzip,hashlib,json,re,shutil
from pathlib import Path
root=Path(__file__).resolve().parents[1];folder=root/'docs/data/balance_v01627/ordinary';tmp=folder/'raw'
def load(name):return json.loads(gzip.decompress((tmp/(name+'.json.gz')).read_bytes()))
def cash(r):return sum(r.get(k,0) for k in ['purchasedMora','processCraftMora','foodCraftMora'])
manifest=json.loads((folder/'manifest.json').read_text())
for name in ['final_food_actor55_all','final_food_bundles_actor55','final_talent90_settlement']:
 raw=gzip.decompress((tmp/(name+'.json.gz')).read_bytes());d=json.loads(raw);manifest['rawFiles']=[x for x in manifest['rawFiles'] if x['file']!='raw/'+name+'.json.gz'];p=folder/'raw'/(name+'.json.gz');p.write_bytes(gzip.compress(raw,mtime=0));manifest['rawFiles'].append({'file':'raw/'+p.name,'uncompressedSha256':hashlib.sha256(raw).hexdigest(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'counts':d.get('counts'),'sourceFingerprint':d.get('fingerprint'),'status':'native diagnostic, exact assumptions in raw evidence'})
(folder/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
M=load('final_material_campaigns')['rows'];wealth=load('final_material_mora')['rows'];max_mora_s=max(r['marginalSecondsPerMora'] for r in wealth)
material=[]
for kind in ['TALENT','ASCENSION']:
 for name in ['story4','heal5']:
  for seed in [717,4242,9031]:
   rows={r['stage']:r for r in M if r['kind']==kind and r['name']==name and r['seed']==seed};a,b=rows[55],rows[60];q55=a['materialEach'];q60=90 if kind=='TALENT' else b['materialEach'];low_s=a['seconds']+a['lodgingMora']*max_mora_s;high_s=b['seconds']+b['lodgingMora']*max_mora_s
   material.append({'kind':kind,'team':name,'seed':seed,'runs':6,'stage55Seconds':a['seconds'],'stage60Seconds':b['seconds'],'stage55Mora':a['lodgingMora'],'stage60Mora':b['lodgingMora'],'each55':q55,'measuredEach60':b['materialEach'],'finalEach60':q60,'timeBenefit':q60/q55*a['seconds']/b['seconds']-1,'cashInclusiveBenefit':q60/q55*low_s/high_s-1,'moraReinvestmentSecondsPerMora':max_mora_s,'rewardReprojection':'Exact final90 quantity projection over preserved native80 combat/inn outcomes; separate public settlement proves90. No combat body changed.' if kind=='TALENT' else 'Native unchanged5400 payout.'})
D=load('final_food_plus6_all')['rows'];P=load('final_food_bundles_retail')['rows'];R=load('product2_food_bundles')['rows'];experience=[]
for seed in [717,4242,9031]:
 d={x['stage']:x for x in D if x['route']=='ROUTE_TRAVELER' and x['name']=='heal5' and x['seed']==seed};p={x['stage']:x for x in P if x['seed']==seed};r={x['stage']:x for x in R if x['seed']==seed}
 for mode,sup in [('retailMixed',p),('directGather',r)]:
  low_s=d[55]['seconds']+sup[55]['seconds'];high_s=d[60]['seconds']+sup[60]['seconds'];experience.append({'seed':seed,'procurement':mode,'runs':6,'lowSeconds':low_s,'highSeconds':high_s,'lowXp':48000,'highXp':144000,'breakevenXp60':8000*high_s/low_s,'finalBenefit':3*low_s/high_s-1,'lowSupplyCash':cash(sup[55]),'highSupplyCash':cash(sup[60]),'durationSensitivityHigh':d[60]['seconds']+sup[60]['upperBoundSeconds']})
D50=load('final_food_actor50_all')['rows'];D55=load('final_food_actor55_all')['rows'];D60=D
body=[]
for route in ['ROUTE_ISEKAI','ROUTE_TRAVELER']:
 for name in ['story4','heal5']:
  vals=[]
  for seed in [717,4242,9031]:
   rate=[]
   for rows in [D50,D55,D60]:rate.append(max(x['xpPerMinute'] for x in rows if x['route']==route and x['name']==name and x['seed']==seed and x['wins']==6))
   vals.append(954460/rate[0]+978090*.5*(1/rate[1]+1/rate[2]))
  body.append({'route':route,'team':name,'minutesBySeed':vals,'meanMinutes':sum(vals)/3,'minMinutes':min(vals),'maxMinutes':max(vals)})
B50=load('final_food_bundles_actor50')['rows'];B55=load('final_food_bundles_actor55')['rows'];B60=P;budget=[]
for seed in [717,4242,9031]:
 def row(d,stage):return next(x for x in d if x.get('route')=='ROUTE_TRAVELER' and x.get('name')=='heal5' and x['seed']==seed and x['stage']==stage)
 def supply(d,stage):return next(x for x in d if x['seed']==seed and x['stage']==stage)
 a=row(D50,55);b=row(D55,60);c=row(D60,60);p=supply(B50,55);q=supply(B55,60);r=supply(B60,60)
 sec50=954460/48000*(a['seconds']+p['seconds']);sec55=978090/144000*.5*(b['seconds']+q['seconds']+c['seconds']+r['seconds']);cash50=954460/48000*cash(p);cash55=978090/144000*.5*(cash(q)+cash(r));budget.append({'seed':seed,'level50to55Minutes':sec50/60,'level55to60Minutes':sec55/60,'hours':(sec50+sec55)/3600,'supplyCashMora':cash50+cash55})
summary={'schema':1,'exp60Final':24000,'talent60Final':90,'dbSha256':manifest['dbSha256'],'materialCampaigns':load('final_material_campaigns')['counts'],'moraAcquisition':load('final_material_mora')['counts'],'finalExpCampaigns':load('final_food_plus6_all')['counts'],'level50Campaigns':load('final_food_actor50_all')['counts'],'level55Campaigns':load('final_food_actor55_all')['counts'],'materialEfficiency':material,'xpEfficiencyIncludingProcurement':experience,'level50to60':{'xp50to55':954460,'xp55to60':978090,'totalXp':1932550,'bodyBudget':body,'travelerHealing5AcquisitionBudget':budget,'budgetMethod':'50→55 conservatively holds the measured actual Lv50 post-ascension phase5 six-run time and food consumption at legal stage55.55→60 linearly averages Lv55 post-ascension phase6 andLv60 perXP cycle costs at stage60 when native campaigns win. Both boundary food bundles are acquired from zero inventory; declared Lv60 four-star acquisition party retained. No fully continuous1→60 natural-ownership/gear/ascension-material campaign is claimed. Failed higher-tier compositions fall back to a proven tier. Gear/talent/ascension preparation, recipe unlock outside exact receipts and story progress are not included.'}}
(folder/'summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
lines=['# 일반 적·비경·회복·재화 연계 검증 — 0.16.27','', '결론: 경험치 비경 최상위 보상을 **24,000 경험치**, 특성 비경 최상위 보상을 **90권**으로 조정한다. 돌파 비경 최상위 5,400개는 유지한다. 전투 부담을 줄여 효율을 맞추지 않는다. 기존 전투의 지급 약속은 새 보상 버전과 분리한다.','', '## 검증 조건','', '- 실제 원본 `content/db.json`을 사용했다. SHA-256은 `'+manifest['dbSha256']+'`이다. 합성 QA DB, 적 스펙·피해·회복·주사위·보상 오버라이드는 최종 근거에서 제외했다.','- 캐릭터 보유, 합법적 레벨·돌파 단계·특성, 장비, 시작 HP 및 시험 비용을 위한 지갑은 명시된 준비 조건이다. 재료·장비를 처음부터 자연 수급한 계정으로 전체 이야기를 주행한 검증은 아니다.','- 4인 명함 편성. 일반 제작 무기·방어구·장신구 +6, 중간 특성, 전용·보스 장비·성유물 없음. 일부 +10 준비 비교를 별도로 보존한다.','- 시간은 실제 표시 2배속 전투 프레임, 수동 입력 3초, 결과·재입장 6초, 이동 4초, 숙박 입력 10초를 합쳤다. 네트워크 지연과 사용자 판단 시간은 포함하지 않는다. 생활 미니게임은 실제 유효 입력·랜덤 수급·입력 간격·조기 종료와 최대 시간 민감도를 모두 기록했다.','- 같은 시드/편성을 여러 목적에 다시 측정했다. 아래 표의 건수를 합쳐 독립 시뮬레이션 총건수라고 표현하면 안 된다.','', '## 최종 경험치 효율 — 음식이 공짜라는 가정 제거','', '여행자·종려·다이루크·진, Lv60/특성6/+6, 각 단계 6연전이다. 전투 사이 HP와 RNG를 그대로 이어간다. 먼저 실제 식사로 소모 메뉴를 측정하고, 그 메뉴만 재료·음식이 하나도 없는 상태에서 공개 `MOVE/LIFE_START/LIFE_FINISH/BUY/CRAFT`로 다시 조달했다. 완제품 혼용은 실제 재고와 일별 재고 대기까지 포함한다. 채집 경로에서는 다른 재료가 함께 나온 것도 실제 인벤토리에 남긴다.','', '| 수급 방법 | 시드 | Lv55 6회 전체 시간 | Lv60 6회 전체 시간 | 최종 상위 효율 |','|---|---:|---:|---:|---:|']
for x in experience:lines.append(f"| {'완제품·직접 수급 혼용' if x['procurement']=='retailMixed' else '직접 수급'} | {x['seed']} | {x['lowSeconds']:.2f}초 | {x['highSeconds']:.2f}초 | +{x['finalBenefit']*100:.1f}% |")
lines += ['', '구보상 10,000은 높은 단계 전투·보급 부담을 보상하지 못했다. 중간 후보 13,000도 음식 보유분만 넣으면 좋아 보였으나 직접 채집 시간을 합치면 실패했다. 직접 수급 최악의 손익분기는 22,266 경험치, 완제품 혼용 최악은 19,437이다. 최종 24,000은 측정한 직접 수급에서도 최소 약7.8% 우위를 남긴다. 완제품 혼용은 최소 약23.5% 우위다.','', '음식은 구매·재료·가공·조리 비용이 실제로 차감된다. 가장 빠른 완제품 경로를 무료 음식으로 설명하지 않는다. 최대 미니게임 시간을 끝까지 기다리는 민감도에서는 시드4242 혼용 경로가 약7.6% 불리할 수 있다. 실제 UI는 모든 대상을 수집하면 조기 종료되지만, 느린 조작·이동 경로까지 모든 사용자의 상위 효율을 보장한 것은 아니다.','', '최종 24캠페인/144전은 24,000이 지급되는 소스에서 실제 재실행했으며 144승/오류0이었다. Lv55 명함의 무회복 편성은 높은 단계에서 일부 패배한다. 높은 단계에 이길 수 없는 상태까지 강제로 높은 단계가 유리하다고 계산하지 않는다.','', '## 특성·돌파 — 숙박·강화된 이동전투·모라 보충까지','', 'Lv55/60 각각 6연전, 두 편성×세 시드×두 종류, 총24캠페인/144전에서 144승/오류0. HP가 50% 미만이거나 전투불능이면 실제 숙박 왕복을 진행했다. 이동 중 강화된 필드 적과의 전투, 숙박비, 귀환 HP를 유지했다.','', '| 비경 | 편성 | 시드 | Lv55 6회 시간 / 숙박비 | Lv60 6회 시간 / 숙박비 | 최종 보상 비율 | 모라 보충 포함 상위 효율 |','|---|---|---:|---:|---:|---:|---:|']
for x in material:lines.append(f"| {'특성' if x['kind']=='TALENT' else '돌파'} | {'엠버·케이아·리사' if x['team']=='story4' else '종려·다이루크·진'} | {x['seed']} | {x['stage55Seconds']:.2f}초 / {x['stage55Mora']:,}모라 | {x['stage60Seconds']:.2f}초 / {x['stage60Mora']:,}모라 | {x['each55']:,} → {x['finalEach60']:,} | +{x['cashInclusiveBenefit']*100:.1f}% |")
lines += ['', '특성 구보상80권은 가장 유리한 낮은 단계와 비교해 상위 효율이 +1.25%밖에 남지 않았다. 유지비532모라의 실제 부의 꽃 보충 시간까지 넣으면 약+1%라 수동 입력이 조금만 길어져도 뒤집힐 수 있었다. 그래서 최상위만 90권으로 올렸다. 위 시간·숙박비는 실제80권을 받은 원자료를 그대로 보존하고, 보상량만90으로 정확히 재계산했다. 별도 최종 공개 전투1회가 실제90권 지급·정산을 검증한다. 전투와 회복 규칙은 이 마지막 보상 조정에서 바뀌지 않았다. 최종 최소 효율 여유는 모라 보충까지 약13.5%다.','', '부의 꽃은 같은 종려·다이루크·진 편성으로 태산부에서 실제 이동해 토벌하고 귀환·숙박까지 수행했다. 시작 지갑0모라, 세 시드 왕복110.76~147.84초, 순수입39,946~40,019모라. 가장 느린 실제 초/모라를 위 표 모든 숙박비에 적용했다. 이는 보유 잔액을 유지하는 장기 한계비용이며 532모라만 분할 지급받는다는 뜻이 아니다. 첫 부의 꽃 왕복의 선행 시간과 남는 잔액은 원자료에 따로 있다. 시간당 한 번의40,000모라 보상 제한도 유지되고, 해당 최악 특성 사례의 숙박 소모 약3,139모라/시간은 이 한도 아래다.','', '돌파 8원소×3단계×2편성×3시드의 단판144조건도 보존했다. 127승/17패이며, 준비 없이 특정 원소 적을 상대하는 잘못된 편성의 패배를 삭제하지 않았다. 위 돌파 연속 효율 표는 중립 재료를 실제로 수급한 조건이다. 높은 단계에 맞는 원소 공략이 필요한 경우까지 전체 승리로 표현하지 않는다.','', '90권 변경은 리월 캐릭터1→10의3특성 재료5,040권 기준 최상위 일반 보상63회 →56회에 해당한다. 전체 육성의 레벨 경험치·돌파·장비 비용은 유지하며, 마지막 특성 재료 반복이 7회 줄어드는 영향이다. 일일 보너스·반복 중 손실·다른 재료 수급은 이 단순 나눗셈에 포함하지 않았다.','', '## Lv50→60 시간 견적','', '필요 경험치는50→55 954,460,55→60 978,090, 합계1,932,550이다. Lv50 실제 공개 돌파 후 단계55를 선택하고,55에서 다시 공개 돌파한 뒤 실제로 성공한 단계60을 선택한다. 첫 구간은 성장 도중 더 강해지는 이익을 미리 빌리지 않도록 Lv50에서 측정한 시간/경험치를 유지한다. 둘째 구간은 실제Lv55·Lv60의 시간/경험치 경계값을 평균한다. 전투·식사뿐 아니라 두 경계의 실제 메뉴 수급 시간을 넣었다.','', '| 여행자·종려·다이루크·진 / 일반 제작+6 | 50→55 | 55→60 | 합계 | 음식 수급 현금 |','|---|---:|---:|---:|---:|']
for x in budget:lines.append(f"| 시드{x['seed']} | {x['level50to55Minutes']:.1f}분 | {x['level55to60Minutes']:.1f}분 | {x['hours']:.2f}시간 | {x['supplyCashMora']:,.0f}모라 |")
lines += ['', f"세 시드 평균은{sum(x['hours'] for x in budget)/3:.2f}시간, 범위{min(x['hours'] for x in budget):.2f}~{max(x['hours'] for x in budget):.2f}시간이다. 지정한50→60 약5시간 목표를 크게 벗어나 빠르게 끝나는 징후가 없어 경험치 요구량은 추가 변경하지 않았다.", '', '이는 **경계값을 이용한 구간 예산**이며 처음부터 끝까지 한 계정으로50→60을 연속 플레이한 실측 시간이 아니다. 수급 자체는 영수증이 있는 실제 행동이지만 수급 전투 편성은 별도 Lv60 4성 명함 준비 조건이다. 장비·특성 준비, 돌파재료·모라 선행 수급, 이야기 진행, 사람의 판단·지연은 제외되어 실제 새 캐릭터 완성 시간과 다르다. 반대로 매6회 메뉴를 재료0부터 새로 준비하는 견적은 이후 남는 재료를 재사용하는 숙련 플레이보다 오래 걸릴 수 있다. '+ '모라 수급 현금의 별도 부의 꽃 한계시간은 약1분 이내이며 원석·시장 거래를 통한 외부 수급은 계산하지 않았다.','', '나머지 편성의 음식 보유 상태 전투·식사 예산은 아래와 같다. 필요한 음식 자연 수급 시간을 포함한 전체 시간이 아니므로 앞의 약5시간 표와 같은 범주로 섞지 않는다.','', '| 주인공 | 동료 | 50→60 전투·식사 예산 평균 / 범위 |','|---|---|---:|']
for x in body:lines.append(f"| {'이세계인' if x['route']=='ROUTE_ISEKAI' else '여행자'} | {'엠버·케이아·리사' if x['team']=='story4' else '종려·다이루크·진'} | {x['meanMinutes']:.1f}분 / {x['minMinutes']:.1f}~{x['maxMinutes']:.1f}분 |")
lines += ['', '이세계인4성 무회복 편성은Lv55의 단계60에서 세 시드 모두 일부 전투가 패배해, 성공한 단계55로 계산했다. +10만으로도 이 문제를 전부 무시할 수는 없었다. 조합과 회복 준비가 부족한 편성의 도전 실패를 무료 승리로 대체하지 않는다.','', '## 회복·경제 교차 확인','', '- 기존 음식·숙박 산식은 유지했다. Lv20/40/60의25%·50% 손실,6개 메뉴,36조건에서 공개 조리76회·식사66회가 정상 차감·회복됐다. 전투불능은 일반 식사로 되살아나지 않는다.','- Lv60 25% 손실 기준 숙박264모라, 쉬운/중간/어려운 메뉴 현금28/8/8모라, 재료 NPC 판매 기회비용 포함80/104/168모라였다.50% 손실은 숙박503모라, 현금44/10/8모라, 기회비용145/154/200모라. 재료 시간·전투·재고를 붙이면 어려운 음식의 낮은 현금과 높은 수급 부담이 분리된다.','- 어려운 음식4인분의 실제 직접 조달: 몬드 해시브라운241~262초·14~16회 채집, 리월 채식전복392~474초·26~31회 채집. 쉬운 달걀4인분48~63초, 민트젤리4인분154~247초. 단독 조달 경로는 최단 경로 증명이 아니고 잉여 재료도 남는다.','- 지맥40조건은 원소·지역·난이도·편성별 실제 공개 도전으로40승/오류0. 경험치책은 계시의 꽃에 남고, 경험치 비경은 직접 경험치를 지급한다. 책 보상·시간당 지급 제한을 지우지 않았다.','- 실시간 시장 가격·거래량·유저 보유 재고는 접근하지 않았다. NPC 매입가와 실제 지출을 기록한 경제 비교를 시장 물가 안정의 증명으로 표현하지 않는다.','', '## 원자료·재현','', '`summary.json`에 계산식과 표 숫자가 있다. `manifest.json`은 압축 원자료의 원문·압축 SHA와 각 소스 지문을 기록한다. `raw/`에는 정확한 준비, HP, 랜덤, 행동, 수급·정산 영수증과 실패를 보존한다. 초기 후보/중단 파일을 성공한 최종 조건으로 합산하지 않는다.','', '```bash','python tools/replay_ordinary_v01627.py --snapshot product_snapshot_2 --dest /tmp/crpg-ordinary-01627-snapshot','node tools/audit_ordinary_native_v01627.cjs --root /tmp/crpg-ordinary-01627-snapshot --levels 50,55,60 --kinds ASCENSION --teams story4,heal5 --elements NEUTRAL,PYRO,HYDRO,CRYO,ELECTRO,ANEMO,GEO,DENDRO --out /tmp/ascension-replay.json','node tools/audit_material_campaign_v01627.cjs --root . --out /tmp/material-final.json','python tools/summarize_ordinary_v01627.py','node tools/audit_material_mora_v01627.cjs --root . --out /tmp/material-mora-final.json','node tools/audit_food_campaign_v01627.cjs --root . --routes ROUTE_ISEKAI,ROUTE_TRAVELER --actor-level 60 --talent 6 --enhance 6 --threshold 0.7 --food-policy gathering --out /tmp/food-final.json','gzip -dc docs/data/balance_v01627/ordinary/raw/product2_food_supply.json.gz > /tmp/food-supply-catalog.json','node tools/audit_food_bundle_v01627.cjs --runtime-root . --input /tmp/food-final.json --supply-input /tmp/food-supply-catalog.json --retail-food --consolidate-gather --out /tmp/food-native-supply.json','```','', '재현 도구는 고정 시드·원본 DB·소스121개를 SHA로 확인한 입력을 복원한다. 현재 소스가90권이라 최종 재료 캠페인 재현에서는90권이 바로 지급된다. 보존한80권 캠페인을 정확히 다시 돌리려면 `--snapshot before_talent90`으로 복원한 루트를 사용한다.','']
(folder/'README_KO.md').write_text('\n'.join(lines))
print('saved',folder/'README_KO.md')
print('final min material benefit', min(x['cashInclusiveBenefit'] for x in material))
print('mean acquisition inclusive growth hours',sum(x['hours'] for x in budget)/3)
