'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),H=require('./audit_protagonist_v01618.cjs');
const ROOT=path.resolve(__dirname,'..'),env=H.load(ROOT),{R,db}=env,FB=env.api.fieldBosses,cp=x=>x===undefined?null:JSON.parse(JSON.stringify(x));
const output=process.argv[2]||ROOT+'/docs/data/boss_balance_v01619/boundaries.json',report={version:'0.16.19',fingerprint:env.fingerprint,scope:'New-battle boss ATK floors and Serpent/Cryo scheduling, explicit preservation of legacy saved fights',checks:[]};
function check(id,fn){try{report.checks.push({id,passed:true,evidence:fn()});console.log('PASS '+id);}catch(e){report.checks.push({id,passed:false,error:e.stack});console.error('FAIL '+id+' '+e.message);}}
function start(id='FB_CRYO_HYPOSTASIS',team=['MOND_AMBER','LIYUE_XIANGLING','MOND_BARBARA']){const r=H.setup(env,{level:25,route:'ROUTE_TRAVELER',team,seed:717,map:FB.bosses[id].map,enhance:6,talent:4});r.startBattle(FB.group(id),'BOSS:'+FB.route(id));r.action('COMBAT_BEGIN');const b=r.s.runtime,boss=b.actors.find(x=>x.source===id);r.die=()=>50;r.random=()=>.5;return{r,b,boss,allies:b.actors.filter(x=>x.side==='ALLY'),me:b.actors.find(x=>x.source==='PLAYER_CUSTOM')};}
const actor=(f,id)=>f.b.actors.find(x=>x.source===id);
function core(f){f.r.applyDamage(f.me,f.boss,f.boss.hp+999999,{element:'물리'});assert.equal(f.boss.hp,1);assert.equal(f.boss.fb.revival.hits,0);}
function hit(f,n=1){for(let i=0;i<n;i++)f.r.applyDamage(actor(f,'MOND_AMBER'),f.boss,100,{element:'불',sourceKind:'FIELD'});}
function nativeE(f,id){const a=actor(f,id),c=f.r.actorCards(a).find(x=>x.id===id+'_E');assert.equal(f.r.cardReason(a,c),'');f.r.executeCard(a,c,f.boss.id);return c.id;}
const expected={FB_ANEMO_HYPOSTASIS:[18,13182,1281,164],FB_ELECTRO_HYPOSTASIS:[20,14588,1053,183],FB_CRYO_REGISVINE:[22,18264,1689,203],FB_CRYO_HYPOSTASIS:[30,25550,1509,294],FB_GEO_HYPOSTASIS:[45,52113,4117,508],FB_PYRO_REGISVINE:[38,37953,2644,401],FB_OCEANID:[40,40457,2919,430],FB_PRIMO_GEOVISHAP:[48,56718,4694,557],FB_RUIN_SERPENT:[56,83496,7840,700]};
for(const [id,stats]of Object.entries(expected))check('final_stats:'+id,()=>{const f=start(id),a=f.boss,got=[a.level,a.maxHp,a.atk,a.def];assert.deepEqual(got,stats);assert.equal(f.b.fieldBoss.behaviorRevision,2);const shields=cp(a.shields);const loaded=new R(db,JSON.parse(f.r.serialize())),la=loaded.s.runtime.actors.find(x=>x.source===id);assert.deepEqual([la.level,la.maxHp,la.atk,la.def],stats);assert.deepEqual(cp(la.shields),shields);return{stats,saveReload:true};});
check('saved_early_boss_is_not_retuned',()=>{const f=start('FB_ANEMO_HYPOSTASIS');delete f.b.fieldBoss.behaviorRevision;f.boss.atk=574;f.boss.hp=f.boss.maxHp-321;const before={hp:f.boss.hp,maxHp:f.boss.maxHp,atk:f.boss.atk,def:f.boss.def};const loaded=new R(db,JSON.parse(f.r.serialize())),a=loaded.s.runtime.actors.find(x=>x.source===f.boss.source);loaded.tuneGrowthEnemy(a,loaded.s.runtime,18);assert.deepEqual({hp:a.hp,maxHp:a.maxHp,atk:a.atk,def:a.def},before);return before;});
check('serpent_burrow_holds_all_remaining_actions_until_next_own_turn',()=>{const f=start('FB_RUIN_SERPENT'),{r,b,boss}=f;boss.turns=1;const at=b.log.length;for(let i=0;i<r.combatActionsPerTurn(boss);i++)r.aiTurn(boss,f.allies);assert.equal(boss.fb.burrowed,true);assert.deepEqual(cp(b.log.slice(at).filter(x=>x.fieldBoss).map(x=>x.card)),['FB_BURROW']);const hp=boss.hp;r.damage(f.me,boss,1,'물리',{sureHit:true});assert.equal(boss.hp,hp);const loaded=new R(db,JSON.parse(r.serialize())),lb=loaded.s.runtime,a=lb.actors.find(x=>x.source===boss.source);a.turns++;const from=lb.log.length;loaded.aiTurn(a,lb.actors.filter(x=>x.side==='ALLY'));assert.equal(a.fb.burrowed,false);assert.deepEqual(cp(lb.log.slice(from).filter(x=>x.fieldBoss).map(x=>x.card)),['FB_EMERGE']);return{firstOwnTurn:['FB_BURROW'],nextOwnTurn:['FB_EMERGE'],saveReload:true,burrowDamageBlocked:true};});
check('legacy_serpent_turn_schedule_remains',()=>{const f=start('FB_RUIN_SERPENT');delete f.b.fieldBoss.behaviorRevision;f.boss.turns=1;const at=f.b.log.length;for(let i=0;i<f.r.combatActionsPerTurn(f.boss);i++)f.r.aiTurn(f.boss,f.allies);assert.equal(f.boss.fb.burrowed,false);const moves=f.b.log.slice(at).filter(x=>x.fieldBoss).map(x=>x.card);assert.deepEqual(cp(moves),['FB_BURROW','FB_EMERGE']);return{moves};});
check('serpent_opened_armor_burrow_blocks_native_fields_and_final_typed_damage',()=>{const f=start('FB_RUIN_SERPENT'),{r,b,boss}=f;boss.fb.armorOpened=true;nativeE(f,'LIYUE_XIANGLING');boss.turns=1;for(let i=0;i<r.combatActionsPerTurn(boss);i++)r.aiTurn(boss,f.allies);assert.equal(boss.fb.burrowed,true);const before={hp:boss.hp,shields:cp(boss.shields)},at=b.log.length;r.damage(actor(f,'MOND_AMBER'),boss,.1,'불',{range:'원거리',sureHit:true});r.tickFields('END');const kinds=['FIELD','OBJECT','REACTION','REACTION_DOT'];for(const sourceKind of kinds)r.applyDamage(actor(f,'MOND_AMBER'),boss,100,{element:'불',sourceKind});assert.deepEqual({hp:boss.hp,shields:cp(boss.shields)},before);const loaded=new R(db,JSON.parse(r.serialize())),la=loaded.s.runtime.actors.find(x=>x.source===boss.source),lm=loaded.s.runtime.actors.find(x=>x.source==='MOND_AMBER');loaded.applyDamage(lm,la,100,{element:'불',sourceKind:'REACTION_DOT'});assert.equal(la.hp,before.hp);la.turns++;loaded.aiTurn(la,loaded.s.runtime.actors.filter(x=>x.side==='ALLY'));assert.equal(la.fb.burrowed,false);loaded.applyDamage(lm,la,100,{element:'불',sourceKind:'REACTION_DOT'});assert.equal(la.hp,before.hp-100);return{armorOpened:true,burrowedHpUnchanged:before.hp,finalTypedKinds:kinds,nativeGuobaFieldBlocked:true,saveReload:true,nextOwnTurnDamageRestored:true,blockedPackets:b.log.slice(at).filter(x=>x.damage===0&&x.immune).length};});
check('cryo_creation_end_is_free_and_next_two_full_rounds_count',()=>{const f=start();core(f);const timeline=[];for(let n=0;n<3;n++){const ending=f.b.round;f.r.roundEnd();timeline.push({endingRound:ending,hp:f.boss.hp,revival:cp(f.boss.fb.revival),nextRound:f.b.round});}assert.equal(timeline[0].revival.rounds,2);assert.equal(timeline[1].revival.rounds,1);assert.equal(timeline[2].revival,null);assert.equal(f.boss.hp,Math.round(f.boss.maxHp*.5));assert.equal(f.b.log.filter(x=>x.card==='FB_REVIVED').length,1);f.r.applyDamage(f.me,f.boss,f.boss.hp+1,{element:'물리'});assert.equal(f.boss.hp,0);return{timeline,oneRevivalOnly:true};});
check('cryo_creation_end_native_guoba_keeps_full_two_round_window',()=>{const f=start();nativeE(f,'LIYUE_XIANGLING');core(f);f.r.roundEnd();assert.equal(f.boss.fb.revival.hits,1);assert.equal(f.boss.fb.revival.rounds,2);f.r.roundEnd();assert.equal(f.boss.fb.revival.hits,2);assert.equal(f.boss.fb.revival.rounds,1);assert.equal(f.boss.hp,1);return{nativeGuobaTicks:2,hits:2,remaining:1,bodyStillAlive:1};});
check('cryo_last_end_native_field_fourth_hit_breaks_before_timeout',()=>{const f=start();core(f);hit(f,3);f.r.roundEnd();f.r.roundEnd();assert.equal(f.boss.fb.revival.rounds,1);nativeE(f,'LIYUE_XIANGLING');f.r.roundEnd();assert.equal(f.boss.hp,0);assert.equal(f.boss.fb.revival,null);assert.equal(f.b.log.filter(x=>x.card==='FB_CORE_BROKEN').length,1);assert.equal(f.b.log.filter(x=>x.card==='FB_REVIVED').length,0);return{initialHits:3,lastEndNativeCard:'LIYUE_XIANGLING_E',breaks:1,revives:0};});
check('cryo_last_end_reaction_dot_fourth_hit_breaks_before_timeout',()=>{const f=start();core(f);hit(f,3);f.r.roundEnd();f.r.roundEnd();f.boss.statuses.push({id:'FIXTURE_POSITIVE_PYRO_DOT',rounds:1,createdRound:f.b.round,actor:actor(f,'MOND_AMBER').id,tickDamage:100,element:'PYRO'});f.r.roundEnd();assert.equal(f.boss.hp,0);assert.equal(f.boss.fb.revival,null);assert.equal(f.b.log.filter(x=>x.card==='FB_REVIVED').length,0);return{lastEndPositiveTypedDot:true,hp:0};});
check('cryo_timeout_precedes_next_start_bunny_explosion',()=>{const f=start();core(f);hit(f,3);f.r.roundEnd();f.r.roundEnd();assert.equal(f.b.round,3);nativeE(f,'MOND_AMBER');const before=f.b.log.filter(x=>x.text?.startsWith('냉기 핵에 금이 갔다')).length;f.r.roundEnd();assert.equal(f.boss.fb.revival,null);assert(f.boss.hp>0&&f.boss.hp<Math.round(f.boss.maxHp*.5));assert.equal(f.b.log.filter(x=>x.card==='FB_CORE_BROKEN').length,0);assert.equal(f.b.log.filter(x=>x.text?.startsWith('냉기 핵에 금이 갔다')).length,before);const timeline=f.b.log.filter(x=>x.card==='FB_REVIVED'||x.sourceKind==='OBJECT').map(x=>({card:x.card,sourceKind:x.sourceKind,round:x.round,damage:x.damage}));assert(timeline.findIndex(x=>x.card==='FB_REVIVED')<timeline.findIndex(x=>x.sourceKind==='OBJECT'));return{timeline,coreFourthHitAtNextStart:false,hp:f.boss.hp};});
check('cryo_new_core_save_reload_preserves_created_and_counted_round',()=>{const f=start();core(f);f.r.roundEnd();f.r.roundEnd();hit(f,2);const before=cp(f.boss.fb.revival),loaded=new R(db,JSON.parse(f.r.serialize())),b=loaded.s.runtime,boss=b.actors.find(x=>x.source===f.boss.source);assert.deepEqual(cp(boss.fb.revival),before);loaded.fieldBossRoundEndAfterDamage(b);assert.equal(boss.fb.revival,null);return{before,after:cp(boss.fb.revival),hp:boss.hp};});
check('cryo_same_end_boundary_is_not_counted_twice',()=>{const f=start();core(f);f.b.round++;f.r.fieldBossRoundEndAfterDamage(f.b);assert.equal(f.boss.fb.revival.rounds,1);f.r.fieldBossRoundEndAfterDamage(f.b);assert.equal(f.boss.fb.revival.rounds,1);return cp(f.boss.fb.revival);});
check('legacy_cryo_save_keeps_two_old_ends_and_first_timeout_order',()=>{const f=start();delete f.b.fieldBoss.behaviorRevision;core(f);nativeE(f,'LIYUE_XIANGLING');const old=cp(f.boss.fb.revival),loaded=new R(db,JSON.parse(f.r.serialize())),b=loaded.s.runtime,boss=b.actors.find(x=>x.source===f.boss.source);loaded.roundEnd();assert.equal(boss.fb.revival.rounds,1);assert.equal(boss.fb.revival.hits,1);loaded.roundEnd();assert.equal(boss.fb.revival,null);assert(boss.hp<Math.round(boss.maxHp*.5));return{old,legacyRevivedBeforeSecondField:true,afterHp:boss.hp};});
check('new_core_invalid_countdown_save_is_rejected',()=>{const f=start();core(f);const s=JSON.parse(f.r.serialize());s.runtime.actors.find(x=>x.source===f.boss.source).fb.revival.startedRound=s.runtime.round+1;assert.throws(()=>new R(db,s),/냉기 핵/);return{futureCreatedRoundRejected:true};});
report.total=report.checks.length;report.passed=report.checks.filter(x=>x.passed).length;report.failed=report.total-report.passed;fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({output,total:report.total,passed:report.passed,failed:report.failed}));if(report.failed)process.exitCode=1;
