'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const h=require('../tests/helpers_v011.cjs'),{R,db}=h;let seq=0,results=[];
function test(name,fn){try{results.push({name,ok:true,evidence:fn()||null});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function free(map='MAP_MOND_CITY'){const r=new R(db);r.newGame({name:'hotfix',route:'ROUTE_TRAVELER',seed:1326+seq,saveId:'HOTFIX-'+(++seq)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,WORLD_TIME:'12:00',STORY_MENU_POLICY:'',SCREEN_MODE:'LOCATION',MORA:999999});delete r.s.storyJourney;delete r.s.storyBreak;try{r.prepareStory();}catch{}return r;}
test('enemy skill install no longer blocks smith purchase',()=>{const r=free(),e=r.placeEntries().find(x=>x.merchant==='MRC_MOND_EQUIP');assert(e);r.action('PLACE_ENTER',{place:e.id,mode:'SHOP'});const stocks=r.placeStocks(),t=stocks.find(x=>x.row[0]==='STK_CRPG_MOND_WORN_SWORD');assert(t);const before=r.s.global.MORA;r.action('BUY',{stock:t.row[0],quantity:1});assert(r.s.inventory.some(i=>i.equip==='EQ_CRPG_WORN_SWORD'));return{stocks:stocks.length,cost:before-r.s.global.MORA};});
test('Mond smith exposes exact nonempty equipment categories',()=>{const r=free(),e=r.placeEntries().find(x=>x.merchant==='MRC_MOND_EQUIP');r.action('PLACE_ENTER',{place:e.id,mode:'SHOP'});const groups={};for(const s of r.placeStocks().filter(x=>x.row[2]==='EQUIP')){const q=r.row('16_EQUIP_DB',s.row[3]),g=q[2];groups[g]=(groups[g]||0)+1;}for(const g of ['한손검','양손검','장병기','활','법구','방어구','장신구','특수'])assert(groups[g]>0,g);return groups;});
test('Liyue smith uses new regional enhancement',()=>{const r=free('MAP_LIYUE_HARBOR'),e=r.placeEntries().find(x=>x.merchant==='MRC_LIYUE_EQUIP');assert(e&&e.modes.includes('CRAFT'));r.action('PLACE_ENTER',{place:e.id,mode:'CRAFT'});const slot=r.giveEquipment('EQ_SWORD_HARBINGER'),q=r.enhancementQuote(slot);assert(q.supported);r.s.global.MORA=999999;for(const[id,n]of Object.entries(q.cost.items||{}))r.giveItem(id,n);const q2=r.enhancementQuote(slot),args={slot,expectedLevel:q2.level,expectedCap:q2.cap,instanceRevision:q2.instanceRevision};assert.equal(r.enhancementFacilityReason(),'');assert.equal(r.actionReason('ENHANCE',args),'');return{basis:JSON.parse(r.row('16_EQUIP_DB','EQ_SWORD_HARBINGER')[32]).basis,target:q2.target};});
test('Liyue smith completes +10 ascend +11 +12 and survives travel/save',()=>{
 const r=free('MAP_LIYUE_HARBOR'),e=r.placeEntries().find(x=>x.merchant==='MRC_LIYUE_EQUIP');r.s.global.WORLD_TIME='08:00';r.s.flags.FLAG_ACCESS_REGION_LIYUE=true;r.action('PLACE_ENTER',{place:e.id,mode:'CRAFT'});
 const slot=r.giveEquipment('EQ_SWORD_HARBINGER');r.s.global.MORA=999999;r.die=()=>1;
 const pay=q=>{for(const[id,n]of Object.entries(q.cost?.items||{})){const have=r.itemCount(id);if(have<n)r.giveItem(id,n-have);}};
 for(let target=1;target<=10;target++){const q=r.enhancementQuote(slot);assert.equal(q.target,target);pay(q);r.action('ENHANCE',{slot,expectedLevel:q.level,expectedCap:q.cap,instanceRevision:q.instanceRevision});assert.equal(r.s.inventory.find(i=>i.slot===slot).enhance,target);}
 const aq=r.enhancementQuote(slot,'ASCEND');pay(aq);r.action('EQUIP_ASCEND',{slot,expectedLevel:aq.level,expectedCap:aq.cap,instanceRevision:aq.instanceRevision});let inv=r.s.inventory.find(i=>i.slot===slot);assert.equal(inv.enhance,10);assert.equal(inv.enhancementCap,12);
 for(let target=11;target<=12;target++){const q=r.enhancementQuote(slot);assert.equal(q.target,target);pay(q);r.action('ENHANCE',{slot,expectedLevel:q.level,expectedCap:q.cap,instanceRevision:q.instanceRevision});}
 inv=r.s.inventory.find(i=>i.slot===slot);assert.equal(inv.enhance,12);assert.equal(inv.enhancementCap,12);r.action('PLACE_LEAVE');r.s.global.ENCOUNTER_COOLDOWN=1;r.die=()=>100;r.action('MOVE',{edge:'EDGE_CRPG_LIYUE_HARBOR_TO_MOND_CITY'});assert.equal(r.s.global.CURRENT_MAP_ID,'MAP_MOND_CITY');
 const restored=new R(db,JSON.parse(r.serialize())),saved=restored.s.inventory.find(i=>i.slot===slot);assert.equal(saved.enhance,12);assert.equal(saved.enhancementCap,12);return{level:saved.enhance,cap:saved.enhancementCap,map:restored.s.global.CURRENT_MAP_ID};
});
test('Azhdaha authored repeat Y stays enterable after clear flag',()=>{
 const r=free('MAP_AZHDAHA_DOMAIN'),row=r.row('35_BOSS_ROUTE_DB','BRT_AZHDAHA');assert.equal(row[14],'Y');r.s.flags[row[13]]=true;const e=r.placeBossEntries().find(x=>x.route==='BRT_AZHDAHA');assert(e);assert.equal(e.reason,'');assert.equal(e.entries.find(x=>x.entry==='DIRECT').reason,'');r.action('PLACE_ENTER',{place:e.id,mode:'BOSS'});r.action('BOSS_ROUTE',{route:'BRT_AZHDAHA',entry:'DIRECT'});assert.equal(r.s.runtime.group,'EG_BOSS_AZHDAHA');return{repeat:row[14],group:r.s.runtime.group};
});
test('Azhdaha phases immunity converter and save state execute at runtime',()=>{
 const r=free('MAP_AZHDAHA_DOMAIN'),e=r.placeBossEntries().find(x=>x.route==='BRT_AZHDAHA');r.action('PLACE_ENTER',{place:e.id,mode:'BOSS'});r.action('BOSS_ROUTE',{route:'BRT_AZHDAHA',entry:'DIRECT'});const b=r.s.runtime,boss=b.actors.find(a=>a.source==='BOSS_AZHDAHA'),player=b.actors.find(a=>a.id==='PLAYER_CUSTOM');assert(boss?.azhdaha);assert.notEqual(boss.azhdaha.element1,boss.azhdaha.element2);assert.equal(boss.azhdaha.current,'GEO');if(b.opening)b.opening.state='STARTED';
 boss.hp=Math.floor(boss.maxHp*.69);r.resolveEnemyPhases();assert.equal(boss.azhdaha.phase,2);assert.equal(boss.azhdaha.current,boss.azhdaha.element1);const shiftEvents=()=>b.log.filter(x=>x.card==='ECARD_AZHDAHA_PHASE_SHIFT'&&x.phase).length,firstShifts=shiftEvents();r.resolveEnemyPhases();assert.equal(shiftEvents(),firstShifts);
 boss.hp=Math.floor(boss.maxHp*.39);r.resolveEnemyPhases();assert.equal(boss.azhdaha.phase,3);assert.equal(boss.azhdaha.current,boss.azhdaha.element2);assert.equal(shiftEvents(),2);
 const restored=new R(db,JSON.parse(r.serialize())),rb=restored.s.runtime.actors.find(a=>a.source==='BOSS_AZHDAHA');assert.deepEqual(rb.azhdaha,boss.azhdaha);
 boss.hp=boss.maxHp;player.atk=1000;boss.def=0;boss.azhdaha.current=boss.azhdaha.element1;boss.azhdaha.neutralUsedRound=0;r.s.preparedTools=['TRPG_TACTICAL_ELEMENT_CONVERTER'];const current=boss.azhdaha.current,before=boss.hp;r.damage(player,boss,.2,current,{range:'원거리',sureHit:true,noCrit:true});assert(boss.hp<before);const afterFirst=boss.hp;r.damage(player,boss,.2,current,{range:'원거리',sureHit:true,noCrit:true});assert.equal(boss.hp,afterFirst);boss.azhdaha.neutralUsedRound=0;r.damage(player,boss,.2,current,{range:'원거리',sureHit:true,noCrit:true,sourceKind:'DOT'});assert.equal(boss.hp,afterFirst);const other=['PYRO','HYDRO','CRYO','ELECTRO'].find(x=>x!==current);r.damage(player,boss,.2,other,{range:'원거리',sureHit:true,noCrit:true});assert(boss.hp<afterFirst);return{elements:[boss.azhdaha.element1,boss.azhdaha.element2],phase:boss.azhdaha.phase,neutralOnce:true};
});
test('Azhdaha Zhongli contract keeps debuff after Zhongli KO while releasing center lock',()=>{
 const r=free('MAP_AZHDAHA_DOMAIN');r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify({LIYUE_ZHONGLI:{state:'JOINED'}});r.s.party[1]={slot:'PARTY_2',type:'CHAR',source:'LIYUE_ZHONGLI',control:'AI',active:true,tactic:'균형'};const e=r.placeBossEntries().find(x=>x.route==='BRT_AZHDAHA');r.action('PLACE_ENTER',{place:e.id,mode:'BOSS'});r.action('BOSS_ROUTE',{route:'BRT_AZHDAHA',entry:'DIRECT'});const boss=r.s.runtime.actors.find(a=>a.source==='BOSS_AZHDAHA'),z=r.s.runtime.actors.find(a=>a.source==='LIYUE_ZHONGLI');assert(boss.azhdaha.zhongliBound);assert(z);assert.equal(r.combatStat(boss,'atk'),boss.atk*.85);assert.equal(r.combatStat(boss,'def'),boss.def*.85);assert.equal(r.azhdahaCenter(boss).source,'LIYUE_ZHONGLI');z.hp=0;assert.notEqual(r.azhdahaCenter(boss)?.source,'LIYUE_ZHONGLI');assert.equal(r.combatStat(boss,'atk'),boss.atk*.85);assert.equal(r.combatStat(boss,'def'),boss.def*.85);return{atk:r.combatStat(boss,'atk'),def:r.combatStat(boss,'def'),released:true};
});
test('Azhdaha v0.13.25 remains executable',()=>{const r=free('MAP_AZHDAHA_DOMAIN'),e=r.placeBossEntries().find(x=>x.route==='BRT_AZHDAHA');assert(e);assert.equal(e.entries.find(x=>x.entry==='DIRECT').reason,'');r.action('PLACE_ENTER',{place:e.id,mode:'BOSS'});r.action('BOSS_ROUTE',{route:'BRT_AZHDAHA',entry:'DIRECT'});assert(r.s.runtime.actors.some(a=>a.source==='BOSS_AZHDAHA'));return r.s.runtime.group;});
test('combat UI source has only per-enemy info buttons',()=>{const read=f=>fs.readFileSync(path.join(h.root,'source',f),'utf8'),intel=read('app_enemy_intel.js'),pro=read('app_protagonist.js'),css=read('style.css');assert(intel.includes("button('정보',()=>EnemyIntel.open(a.id))"));assert(!intel.includes("button('적 기술 정보'"));assert(!intel.includes('최근 적 기술 다시 보기'));assert(!intel.includes('enemy-inspect-name'));assert(!pro.includes("controls?.append(el('p','skill-preview'"));assert(css.includes('grid-template-columns:32px minmax(0,1fr)'));return true;});
test('market filter source supports broad and exact equipment views',()=>{const exp=fs.readFileSync(path.join(h.root,'source/app_experience.js'),'utf8'),market=fs.readFileSync(path.join(h.root,'source/app_market.js'),'utf8');for(const g of ['기본 무기','한손검','양손검','장병기','활','법구','방어구','장신구','특수']){assert(exp.includes("'"+g+"'"),g);assert(market.includes("'"+g+"'"),g);}assert(market.includes('entryGroups(e).includes(marketCategory)'));return true;});
test('craft results use item icons',()=>{const exp=fs.readFileSync(path.join(h.root,'source/app_experience.js'),'utf8');assert(exp.includes("output.append(itemGlyph(d)"));return true;});
const report={version:'0.13.26',total:results.length,passed:results.filter(x=>x.ok).length,results};console.log(JSON.stringify({total:report.total,passed:report.passed}));if(report.total!==report.passed)process.exitCode=1;
