'use strict';
const assert=require('node:assert/strict'),{db,R}=require('../tests/helpers_v011.cjs');
let seq=0,results=[];function test(n,f){try{results.push({name:n,ok:true,evidence:f()||null});}catch(e){results.push({name:n,ok:false,error:e.stack});}}
function fresh(route='ROUTE_TRAVELER',map='MAP_MOND_CITY',level=12){const r=new R(db);r.newGame({name:'step5',route,seed:900+seq,saveId:'STEP5-'+(++seq)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'HUB',STORY_CURSOR_NODE_ID:'HUB',ACTIVE_STORY_QUEST:'',SCREEN_MODE:'LOCATION',STORY_MENU_POLICY:'FULL',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',STORY_WAITING:false,CURRENT_MAP_ID:map,WORLD_TIME:'12:00',MORA:100000,PLAYER_LEVEL_STATE:level,PLAYER_XP_STATE:0});for(const k of ['storyJourney','storyBreak','storyArrival','storyMenuFrame','storyContext'])delete r.s[k];r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;return r;}
const cases=[['MAP_LIYUE_PLAINS','EG_TREASURE_PATROL'],['MAP_LIYUE_MOUNTAINS','EG_LIYUE_HILI_ROCK'],['MAP_LIYUE_JUEYUN','EG_LIYUE_VISHAP'],['MAP_CHASM_SURFACE','EG_LIYUE_RUIN'],['MAP_CHASM_DEEP','EG_CHASM_SERPENT']];
test('recommended levels',()=>{const ev=[];for(const[map,group]of cases)for(const level of[1,20]){const r=fresh('ROUTE_TRAVELER',map,level),m=r.row('32_MAP_DB',map);r.die=()=>level===1?1:3;r.startBattle(group,'RANDOM');const lv=r.s.runtime.actors.filter(a=>a.side==='ENEMY').map(a=>a.level);assert(lv.every(x=>x>=+m[6]&&x<=+m[7]));ev.push({map,level,spawn:[...new Set(lv)]});}return ev;});
test('Katheryne no legends, local Liyue contact works',()=>{const r=fresh('ROUTE_TRAVELER','MAP_MOND_CITY',20);r.s.flags.FLAG_TRV_MON_PROLOGUE_CLEAR=true;r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;const k=r.placeEntries().find(e=>e.entity==='NPC_MOND_KATHERYNE');r.action('PLACE_ENTER',{place:k.id,mode:'TALK'});assert.equal(r.legendContactEntries().length,0);assert(r.commissionEntries().length>0);r.action('PLACE_LEAVE');Object.assign(r.questState('Q_TRV_LIYUE_01'),{state:'완료',claimed:true});r.s.global.CURRENT_MAP_ID='MAP_LIYUE_HARBOR';const d=r.storyDefinition('LEG_LIYUE_XIANGLING'),p=r.legendIntroductionPlaces(d);assert.equal(p.length,1);assert.equal(p[0].id,'EVT_CRPG_LIYUE_WANMIN');return{katheryneLegends:0,place:p[0].name};});
test('22 Liyue costs',()=>{const r=fresh(),defs=[...r.storyIndex().legends.values()].filter(d=>d.ROUTE_SCOPE==='ROUTE_TRAVELER'&&d.REGION==='리월'&&d.CHAR_ID!=='LIYUE_ZHONGLI');assert.equal(defs.length,22);assert(defs.every(d=>+d.COST_MORA>=300&&Object.keys(JSON.parse(d.COST_ITEMS_JSON||'{}')).length));return{count:22,min:Math.min(...defs.map(d=>+d.COST_MORA))};});
test('Diluc normal and story-free paths',()=>{const r=fresh('ROUTE_ISEKAI');r.s.flags.FLAG_ISK_M05_CLEAR=true;const d=r.storyDefinition('LEG_ISK_MOND_DILUC');assert.equal(+d.COST_MORA,650);assert(!/FLAG_ISK_MOND_BRANCH|FLAG_ISK_EXPEDITION_FORK/.test(d.START_CONDITION));const ui=r.recruitmentEntries().find(e=>e.character==='MOND_DILUC');assert(!/AB|AB1|AB2/.test(JSON.stringify({method:ui.method,requirements:ui.requirements})));r.s.flags.FLAG_ISK_MOND_BRANCH='EXPEDITION';r.s.flags.FLAG_ISK_EXPEDITION_FORK='RETURN';assert.equal(r.legendEffectiveCost(d).mora,0);return{normal:650,storyWaiver:0};});
const report={total:results.length,passed:results.filter(x=>x.ok).length,results};require('fs').mkdirSync(require('path').join(__dirname,'../reports/gameplay_step5'),{recursive:true});require('fs').writeFileSync(require('path').join(__dirname,'../reports/gameplay_step5/runtime-tests-live.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({total:report.total,passed:report.passed}));if(report.passed!==report.total)process.exitCode=1;
