'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const h=require('../tests/helpers_v011.cjs'),{R,db}=h;let seq=0,results=[];
function test(name,fn){try{results.push({name,ok:true,evidence:fn()||null});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function free(map='MAP_MOND_CITY'){const r=new R(db);r.newGame({name:'hotfix',route:'ROUTE_TRAVELER',seed:1326+seq,saveId:'HOTFIX-'+(++seq)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,WORLD_TIME:'12:00',STORY_MENU_POLICY:'',SCREEN_MODE:'LOCATION',MORA:999999});delete r.s.storyJourney;delete r.s.storyBreak;try{r.prepareStory();}catch{}return r;}
test('enemy skill install no longer blocks smith purchase',()=>{const r=free(),e=r.placeEntries().find(x=>x.merchant==='MRC_MOND_EQUIP');assert(e);r.action('PLACE_ENTER',{place:e.id,mode:'SHOP'});const stocks=r.placeStocks(),t=stocks.find(x=>x.row[0]==='STK_CRPG_MOND_WORN_SWORD');assert(t);const before=r.s.global.MORA;r.action('BUY',{stock:t.row[0],quantity:1});assert(r.s.inventory.some(i=>i.equip==='EQ_CRPG_WORN_SWORD'));return{stocks:stocks.length,cost:before-r.s.global.MORA};});
test('Mond smith exposes nonempty equipment groups',()=>{const r=free(),e=r.placeEntries().find(x=>x.merchant==='MRC_MOND_EQUIP');r.action('PLACE_ENTER',{place:e.id,mode:'SHOP'});const groups={};for(const s of r.placeStocks().filter(x=>x.row[2]==='EQUIP')){const q=r.row('16_EQUIP_DB',s.row[3]),g=['법구','장신구'].includes(q[2])?'법구·장신구':q[2]==='방어구'?'방어구':q[14]==='Y'?'단조 무기':'기본 무기';groups[g]=(groups[g]||0)+1;}assert(groups['기본 무기']>0);assert(groups['법구·장신구']>0);assert(groups['방어구']>0);return groups;});
test('Liyue smith uses new regional enhancement',()=>{const r=free('MAP_LIYUE_HARBOR'),e=r.placeEntries().find(x=>x.merchant==='MRC_LIYUE_EQUIP');assert(e&&e.modes.includes('CRAFT'));r.action('PLACE_ENTER',{place:e.id,mode:'CRAFT'});const slot=r.giveEquipment('EQ_SWORD_HARBINGER'),q=r.enhancementQuote(slot);assert(q.supported);r.s.global.MORA=999999;for(const[id,n]of Object.entries(q.cost.items||{}))r.giveItem(id,n);const q2=r.enhancementQuote(slot),args={slot,expectedLevel:q2.level,expectedCap:q2.cap,instanceRevision:q2.instanceRevision};assert.equal(r.enhancementFacilityReason(),'');assert.equal(r.actionReason('ENHANCE',args),'');return{basis:JSON.parse(r.row('16_EQUIP_DB','EQ_SWORD_HARBINGER')[32]).basis,target:q2.target};});
test('Azhdaha v0.13.25 remains executable',()=>{const r=free('MAP_AZHDAHA_DOMAIN'),e=r.placeBossEntries().find(x=>x.route==='BRT_AZHDAHA');assert(e);assert.equal(e.entries.find(x=>x.entry==='DIRECT').reason,'');r.action('PLACE_ENTER',{place:e.id,mode:'BOSS'});r.action('BOSS_ROUTE',{route:'BRT_AZHDAHA',entry:'DIRECT'});assert(r.s.runtime.actors.some(a=>a.source==='BOSS_AZHDAHA'));return r.s.runtime.group;});
test('combat UI source has only per-enemy info buttons',()=>{const read=f=>fs.readFileSync(path.join(h.root,'source',f),'utf8'),intel=read('app_enemy_intel.js'),pro=read('app_protagonist.js'),css=read('style.css');assert(intel.includes("button('정보',()=>EnemyIntel.open(a.id))"));assert(!intel.includes("button('적 기술 정보'"));assert(!intel.includes('최근 적 기술 다시 보기'));assert(!intel.includes('enemy-inspect-name'));assert(!pro.includes("controls?.append(el('p','skill-preview'"));assert(css.includes('grid-template-columns:32px minmax(0,1fr)'));return true;});
test('craft results use item icons',()=>{const exp=fs.readFileSync(path.join(h.root,'source/app_experience.js'),'utf8');assert(exp.includes("output.append(itemGlyph(d)"));return true;});
const report={version:'0.13.26',total:results.length,passed:results.filter(x=>x.ok).length,results};console.log(JSON.stringify({total:report.total,passed:report.passed}));if(report.total!==report.passed)process.exitCode=1;
