'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const h=require('../tests/helpers_v011.cjs'),{R,db}=h;let seq=0,results=[];
function test(name,fn){try{results.push({name,ok:true,evidence:fn()||null});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function free(map='MAP_LIYUE_HARBOR',route='ROUTE_TRAVELER'){const r=new R(db);r.newGame({name:'artifact',route,seed:1328+seq,saveId:'ART-'+(++seq)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,WORLD_TIME:'12:00',STORY_MENU_POLICY:'',SCREEN_MODE:'LOCATION',MORA:999999});delete r.s.storyJourney;delete r.s.storyBreak;try{r.prepareStory();}catch{}return r;}
function unlockTartaglia(r){r.s.quests.Q_TRV_LIYUE_03={state:'완료',node:'COMPLETE',claimed:true};}
function unlockAzhdaha(r){r.s.combatReceipts??={};r.s.combatReceipts.TEST_AZH={victory:true,group:'EG_BOSS_AZHDAHA'};}
test('step10 module installs artifact equipment and material definitions',()=>{const r=free();for(const id of ['EQ_ARTIFACT_EDGE','EQ_ARTIFACT_TIDE','EQ_ARTIFACT_GUARD','EQ_ARTIFACT_VITAL','EQ_ARTIFACT_SWIFT','EQ_ARTIFACT_BALANCE']){const row=r.row('16_EQUIP_DB',id);assert.equal(row[2],'특수');}assert(r.row('14_ITEM_DB','MAT_AZHDAHA_ARTIFACT_CRYSTAL'));return{module:r.liyueArtifactModuleVersion,kinds:Object.keys(h.c.CRPGRuntime.liyueArtifactConfig.archetypes).length};});
test('Tartaglia farm is gated, starts the real boss, drops one artifact, and records 48h admission',()=>{const r=free('MAP_LIYUE_GOLDEN_HOUSE');assert.match(r.liyueArtifactFarmReason('TARTAGLIA'),/전투 기록|제3막/);unlockTartaglia(r);assert.equal(r.liyueArtifactFarmReason('TARTAGLIA'),'');r.action('LIYUE_ARTIFACT_CHALLENGE',{kind:'TARTAGLIA'});assert.equal(r.s.runtime.group,'EG_BOSS_TARTAGLIA');assert.equal(r.s.runtime.origin,'MATERIAL_CHALLENGE:LIYUE_TARTAGLIA_FARM');const until=r.s.liyueArtifactFarm.cooldowns.TARTAGLIA;r.finishBattle(true);const arts=r.s.inventory.filter(i=>i.artifact);assert.equal(arts.length,1);assert.equal(arts[0].enhance,0);assert(arts[0].artifact.quality>=1&&arts[0].artifact.quality<=1000);assert.match(r.liyueArtifactFarmReason('TARTAGLIA'),/48시간/);r.advanceTime(1440);assert.match(r.liyueArtifactFarmReason('TARTAGLIA'),/남은 시간/);r.advanceTime(1440);assert.equal(r.liyueArtifactFarmReason('TARTAGLIA'),'');return{until,artifact:arts[0].artifact};});
test('Tartaglia artifacts have multiple archetypes and deliberately wide roll variance',()=>{const r=free(),rolls=[];for(let i=0;i<900;i++)rolls.push(r.rollArtifact());const kinds=new Set(rolls.map(x=>r.artifactInstance(x.slot).artifact.kind)),qualities=rolls.map(x=>x.quality);assert.equal(kinds.size,6);assert(Math.min(...qualities)<80);assert(Math.max(...qualities)>950);const edge=rolls.map(x=>r.artifactInstance(x.slot)).filter(x=>x.artifact.kind==='EDGE').sort((a,b)=>a.artifact.quality-b.artifact.quality);assert(edge.length>20);const low=edge[0],high=edge.at(-1);assert(high.artifact.stats.ATK/low.artifact.stats.ATK>5);return{kinds:[...kinds],minQuality:Math.min(...qualities),maxQuality:Math.max(...qualities),edgeAtkRatio:high.artifact.stats.ATK/low.artifact.stats.ATK};});
test('artifact occupies SPECIAL slot and contributes its rolled stats',()=>{const r=free(),prior=r.giveEquipment('EQ_SPECIAL_FIELD_PACK');r.equip(prior,'PLAYER_CUSTOM');const drop=r.rollArtifact(),inv=r.artifactInstance(drop.slot),rolled=r.artifactStats(inv);r.equip(inv.slot,'PLAYER_CUSTOM');assert.equal(inv.category,'SPECIAL');assert(inv.equipped);assert.equal(r.s.inventory.find(i=>i.slot===prior).equipped,false);const total=r.equipmentStats('PLAYER_CUSTOM');for(const [k,v]of Object.entries(rolled))assert(total[k]>=v);return{slot:inv.slot,grade:inv.artifact.grade,stats:rolled};});
test('Azhdaha farm uses an independent 48h clock and drops 2-4 enhancement crystals',()=>{const r=free('MAP_AZHDAHA_DOMAIN');unlockAzhdaha(r);assert.equal(r.liyueArtifactFarmReason('AZHDAHA'),'');r.action('LIYUE_ARTIFACT_CHALLENGE',{kind:'AZHDAHA'});assert.equal(r.s.runtime.group,'EG_BOSS_AZHDAHA');assert.equal(r.s.runtime.origin,'MATERIAL_CHALLENGE:LIYUE_AZHDAHA_FARM');r.finishBattle(true);const n=r.itemCount('MAT_AZHDAHA_ARTIFACT_CRYSTAL');assert(n>=2&&n<=4);assert.match(r.liyueArtifactFarmReason('AZHDAHA'),/48시간/);assert.equal(r.s.liyueArtifactFarm.cooldowns.TARTAGLIA,undefined);return{crystals:n,cooldown:r.s.liyueArtifactFarm.cooldowns.AZHDAHA};});
test('artifact enhancement is separate from +12 gear, probabilistic, and capped at +5',()=>{const r=free('MAP_LIYUE_HARBOR'),smith=r.placeEntries().find(x=>x.merchant==='MRC_LIYUE_EQUIP'&&x.modes.includes('CRAFT'));assert(smith);r.action('PLACE_ENTER',{place:smith.id,mode:'CRAFT'});const drop=r.rollArtifact(),slot=drop.slot;r.giveItem('MAT_AZHDAHA_ARTIFACT_CRYSTAL',30);r.random=()=>0;for(let target=1;target<=5;target++){const q=r.artifactEnhancementQuote(slot);assert.equal(q.target,target);const rec=r.action('ARTIFACT_ENHANCE',{slot,expectedLevel:q.level,instanceRevision:q.instanceRevision});assert(rec.result.success);assert.equal(r.artifactInstance(slot).artifact.level,target);assert.equal(r.artifactInstance(slot).enhance,0);}const max=r.artifactEnhancementQuote(slot);assert(max.maxed);assert.equal(r.artifactEnhancementReason({slot}), '이미 +5 최대 강화입니다.');return{level:r.artifactInstance(slot).artifact.level,ordinaryEnhance:r.artifactInstance(slot).enhance};});
test('artifact enhancement failure consumes cost but never destroys or downgrades the artifact',()=>{const r=free('MAP_LIYUE_HARBOR'),smith=r.placeEntries().find(x=>x.merchant==='MRC_LIYUE_EQUIP'&&x.modes.includes('CRAFT'));r.action('PLACE_ENTER',{place:smith.id,mode:'CRAFT'});const slot=r.rollArtifact().slot;r.giveItem('MAT_AZHDAHA_ARTIFACT_CRYSTAL',5);const before=r.itemCount('MAT_AZHDAHA_ARTIFACT_CRYSTAL'),q=r.artifactEnhancementQuote(slot);r.random=()=>.99999;const rec=r.action('ARTIFACT_ENHANCE',{slot,expectedLevel:q.level,instanceRevision:q.instanceRevision});assert.equal(rec.result.success,false);assert.equal(r.artifactInstance(slot).artifact.level,0);assert.equal(r.itemCount('MAT_AZHDAHA_ARTIFACT_CRYSTAL'),before-q.cost.items.MAT_AZHDAHA_ARTIFACT_CRYSTAL);assert(r.artifactInstance(slot));return{roll:rec.result.roll,remaining:r.itemCount('MAT_AZHDAHA_ARTIFACT_CRYSTAL')};});
test('artifact instance data and farm cooldown survive serialize/reload',()=>{const r=free('MAP_LIYUE_GOLDEN_HOUSE');unlockTartaglia(r);r.action('LIYUE_ARTIFACT_CHALLENGE',{kind:'TARTAGLIA'});r.finishBattle(true);const inv=r.s.inventory.find(i=>i.artifact),snapshot=JSON.parse(JSON.stringify(inv.artifact)),until=r.s.liyueArtifactFarm.cooldowns.TARTAGLIA,save=JSON.parse(r.serialize()),loaded=new R(db,save),after=loaded.s.inventory.find(i=>i.slot===inv.slot);assert.equal(JSON.stringify(after.artifact),JSON.stringify(snapshot));assert.equal(loaded.s.liyueArtifactFarm.cooldowns.TARTAGLIA,until);assert.doesNotThrow(()=>loaded.serialize());return{slot:inv.slot,quality:after.artifact.quality,cooldown:until};});
test('Osial is not added to the repeat farming system',()=>{const r=free('MAP_OSIAL_BATTLE');assert(!Object.keys(h.c.CRPGRuntime.liyueArtifactConfig.farm).some(k=>/OSIAL/i.test(k)));assert.match(r.liyueArtifactFarmReason('OSIAL'),/지원하지 않는/);return true;});
test('v0.13.28 sources wire runtime, UI, build and release metadata',()=>{const index=fs.readFileSync(path.join(h.root,'source/index.html'),'utf8'),build=fs.readFileSync(path.join(h.root,'tools/build.py'),'utf8'),ui=fs.readFileSync(path.join(h.root,'source/app_liyue_artifacts.js'),'utf8'),pkg=require(path.join(h.root,'package.json'));assert(index.includes('runtime_liyue_artifacts.js'));assert(index.includes('app_liyue_artifacts.js'));assert(build.includes('runtime_liyue_artifacts.js'));assert(build.includes('app_liyue_artifacts.js'));assert(ui.includes("MAP_LIYUE_GOLDEN_HOUSE"));assert(ui.includes("MAP_AZHDAHA_DOMAIN"));assert(!ui.includes('MAP_OSIAL_BATTLE'));assert.equal(pkg.version,'0.13.28');return true;});
const report={version:'0.13.28',total:results.length,passed:results.filter(x=>x.ok).length,results};console.log(JSON.stringify({total:report.total,passed:report.passed}));if(report.total!==report.passed)process.exitCode=1;
