'use strict';
// v0.13.41 steps 12-6-6~12-6-8: companion exclusive weapons from boss materials, and boss-material gear.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),runtimeDir=process.env.CRPG_RUNTIME_DIR||'source',dir=path.join(root,runtimeDir),DB=JSON.parse(fs.readFileSync(root+'/content/db.json','utf8'));
let clock=1790355600000;
const ctx=vm.createContext({console,Date:class extends Date{static now(){return clock;}},setTimeout,clearTimeout,TextEncoder,TextDecoder});
for(const[,f]of fs.readFileSync(dir+'/index.html','utf8').matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ?]*)\.js)(?:\?[^" ]*)?"/g))vm.runInContext(fs.readFileSync(dir+'/'+f,'utf8'),ctx,{filename:f});
const api=ctx.CRPGRuntime,R=api.Runtime,L=x=>JSON.parse(JSON.stringify(x)),X=api.exclusiveWeapons;
const report={version:'0.13.41',runtimeDir,scope:'companion exclusive weapons, signature traits, boss-material gear',checks:[]};
function test(n,f){try{report.checks.push({name:n,passed:true,evidence:f()||null});console.log('PASS '+n);}catch(e){report.checks.push({name:n,passed:false,error:e.stack});console.error('FAIL '+n+'\n'+e.stack);}}
let seq=0;
function fresh(route='ROUTE_TRAVELER',map='MAP_LIYUE_HARBOR'){const r=new R(DB);r.newGame({name:'점검',route,seed:4300+seq,saveId:'EX-'+(++seq)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,WORLD_TIME:'12:00',STORY_MENU_POLICY:'',SCREEN_MODE:'LOCATION',MORA:99999,PLAYER_LEVEL_STATE:9});delete r.s.storyJourney;delete r.s.storyBreak;delete r.s.liyueField;try{r.prepareStory();}catch{}r.recalculate();return r;}
function join(r,ids,level=9){const own=JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON||'{}');ids.forEach((id,i)=>{own[id]={state:'JOINED'};r.s.chars[id].level=level;r.s.party[i+1]={slot:'PARTY_'+(i+2),type:'CHAR',source:id,control:'AI',active:true,tactic:'균형'};});r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(own);for(const id of ids)r.s.chars[id].hp=r.character(id).maxHp;}
const forge=r=>{const e=r.placeCatalog().find(x=>x.merchant==='MRC_LIYUE_EQUIP');r.action('PLACE_ENTER',{place:e.id,mode:'CRAFT'});};
// Official ascension boss materials (genshin-db). Everyone else uses a marked substitute.
const OFFICIAL={MOND_ALBEDO:'MAT_FB_BASALT_PILLAR',MOND_BARBARA:'MAT_FB_CLEANSING_HEART',MOND_BENNETT:'MAT_FB_EVERFLAME_SEED',MOND_VENTI:'MAT_FB_HURRICANE_SEED',MOND_DIONA:'MAT_FB_HOARFROST_CORE',MOND_DILUC:'MAT_FB_EVERFLAME_SEED',MOND_AMBER:'MAT_FB_EVERFLAME_SEED',MOND_JEAN:'MAT_FB_HURRICANE_SEED',MOND_KAEYA:'MAT_FB_HOARFROST_CORE',MOND_KLEE:'MAT_FB_EVERFLAME_SEED',MOND_MONA:'MAT_FB_CLEANSING_HEART',MOND_NOELLE:'MAT_FB_BASALT_PILLAR',MOND_FISCHL:'MAT_FB_LIGHTNING_PRISM',MOND_LISA:'MAT_FB_LIGHTNING_PRISM',MOND_RAZOR:'MAT_FB_LIGHTNING_PRISM',MOND_ROSARIA:'MAT_FB_HOARFROST_CORE',MOND_SUCROSE:'MAT_FB_HURRICANE_SEED',MOND_EULA:'MAT_FB_CRYSTALLINE_BLOOM',
 LIYUE_BEIDOU:'MAT_FB_LIGHTNING_PRISM',LIYUE_QIQI:'MAT_FB_HOARFROST_CORE',LIYUE_NINGGUANG:'MAT_FB_BASALT_PILLAR',LIYUE_KEQING:'MAT_FB_LIGHTNING_PRISM',LIYUE_GANYU:'MAT_FB_HOARFROST_CORE',LIYUE_XINGQIU:'MAT_FB_CLEANSING_HEART',LIYUE_HUTAO:'MAT_FB_JUVENILE_JADE',LIYUE_XIANGLING:'MAT_FB_EVERFLAME_SEED',LIYUE_XIAO:'MAT_FB_JUVENILE_JADE',LIYUE_XINYAN:'MAT_FB_EVERFLAME_SEED',LIYUE_TARTAGLIA:'MAT_FB_CLEANSING_HEART',LIYUE_YANFEI:'MAT_FB_JUVENILE_JADE',LIYUE_YELAN:'MAT_FB_RUNIC_FANG',LIYUE_ZHONGLI:'MAT_FB_BASALT_PILLAR',LIYUE_CHONGYUN:'MAT_FB_HOARFROST_CORE'};

test('every playable companion owns exactly one exclusive weapon of their own class; protagonists own none',()=>{const r=fresh(),playable=r.rows('07_CHAR_DB').filter(c=>/^(MOND|LIYUE)_/.test(c[0])&&(r.equipmentProficiencies(c[0])||[]).length).map(c=>c[0]);
 assert.equal(playable.length,43);assert.deepEqual(L(X.weapons.map(w=>w.owner)).sort(),playable.slice().sort());
 for(const w of X.weapons){const row=r.row('16_EQUIP_DB',w.id);assert.equal(row[30],w.owner);assert.deepEqual(L(r.equipmentProficiencies(w.owner)),[row[2]],w.id);assert(Number(row[4])<=74,'not above the best generic forge weapon: '+w.id);}
 assert(!X.weapons.some(w=>w.owner==='PLAYER_CUSTOM'));return {weapons:X.weapons.length};});
test('each weapon uses the original ascension boss material, substitutes are marked',()=>{const subs=[];for(const w of X.weapons){if(OFFICIAL[w.owner]){assert.equal(w.material,OFFICIAL[w.owner],w.owner);assert.equal(w.official,true,w.owner);}else{assert.equal(w.official,false,w.owner);subs.push(w.owner);}}
 assert.deepEqual(subs.sort(),['LIYUE_BAIZHU','LIYUE_GAMING','LIYUE_LANYAN','LIYUE_SHENHE','LIYUE_XIANYUN','LIYUE_YAOYAO','LIYUE_YUNJIN','LIYUE_ZIBAI','MOND_DAHLIA','MOND_MIKA']);
 const r=fresh();for(const w of X.weapons){const rec=r.row('17_RECIPE_DB',X.recipeId(w));assert.match(String(rec[21]),w.official?/원작 돌파 재료/:/대체 재료/);}return {substitutes:subs.length};});
test('a companion weapon is crafted only after the companion joins, and only they can wield it',()=>{const r=fresh();forge(r);const lisa=X.weapons.find(w=>w.owner==='MOND_LISA');
 assert(!r.placeRecipes().some(x=>x.row[0]===X.recipeId(lisa)),'hidden before joining');join(r,['MOND_LISA','MOND_BARBARA']);assert(r.placeRecipes().some(x=>x.row[0]===X.recipeId(lisa)));
 for(const [id,n]of Object.entries({MAT_FB_LIGHTNING_PRISM:4,MAT_LIYUE_COR_LAPIS:6,ORE_CRYSTAL:3}))r.giveItem(id,n);const out=r.action('CRAFT',{recipe:X.recipeId(lisa)}).result;assert.equal(out.result,lisa.id);assert.equal(r.itemCount('MAT_FB_LIGHTNING_PRISM'),0);
 const slot=r.s.inventory.find(i=>i.equip===lisa.id).slot;assert.match(r.actionReason('EQUIP',{slot,owner:'MOND_BARBARA'}),/전용/);assert.throws(()=>r.action('EQUIP',{slot,owner:'MOND_BARBARA'}),/전용/);r.action('EQUIP',{slot,owner:'MOND_LISA'});assert(r.s.inventory.find(i=>i.slot===slot).equipped);
 const q=L(r.enhancementQuote(slot));assert(q.supported&&q.statsAfter.ATK>q.statsBefore.ATK);return {crafted:out.result};});
test('전용 공명 boosts the owner own skills only; 치유 공명 and 수호 공명 boost the owner heals and shields',()=>{const r=fresh('ROUTE_TRAVELER','MAP_MOND_PLAINS');join(r,['MOND_LISA','MOND_BARBARA','MOND_NOELLE']);r.startBattle('EG_MOND_HILI_ELITE','RANDOM');const b=r.s.runtime,foe=b.actors.find(a=>a.side==='ENEMY'),ally=src=>b.actors.find(a=>a.source===src);
 const lisa=ally('MOND_LISA');lisa.traits={SIGNATURE:20};const own=r.combatDamageMultiplier(lisa,foe,'번개',{card:'MOND_LISA_Q'}),basic=r.combatDamageMultiplier(lisa,foe,'번개',{}),other=r.combatDamageMultiplier(lisa,foe,'번개',{card:'MOND_BARBARA_E'});
 assert(Math.abs(own/basic-1.2)<1e-9);assert.equal(other,basic);
 const barbara=ally('MOND_BARBARA'),noelle=ally('MOND_NOELLE');noelle.hp=1;barbara.traits={HEAL_OUT:25};const healed=r.heal(noelle,100,barbara.name);assert.equal(healed,125);
 noelle.traits={SHIELD_OUT:25};r.shield(noelle,200,'MOND_NOELLE_E',2);assert.equal(noelle.shields.find(s=>s.source==='MOND_NOELLE_E').value,250);r.shield(lisa,200,'MOND_LISA_E',2);assert.equal(lisa.shields.find(s=>s.source==='MOND_LISA_E').value,200);return {own,basic};});
test('nine boss-material gear pieces: one per boss material, counter traits, forged at the Liyue equipment shop',()=>{const r=fresh();forge(r);const mats=new Set();
 for(const g of X.bossGear){const rec=r.row('17_RECIPE_DB',X.recipeId(g));assert.equal(rec[17],'MRC_LIYUE_EQUIP');const ing=r.rows('48_RECIPE_INGREDIENT_DB').filter(i=>i[1]===rec[0]);assert(ing.some(i=>i[3]===g.material&&Number(i[4])===3));mats.add(g.material);assert(L(r.gearTraitLines(g.id)).filter(l=>!l.innate).length>=2,g.id);}
 assert.equal(mats.size,9);for(const [id,n]of Object.entries({MAT_FB_EVERFLAME_SEED:3,MAT_LIYUE_COR_LAPIS:3}))r.giveItem(id,n);const out=r.action('CRAFT',{recipe:X.recipeId(X.bossGear.find(g=>g.id==='EQ_FB_SPECIAL_EMBER_WARD'))}).result;assert.equal(out.result,'EQ_FB_SPECIAL_EMBER_WARD');return {gear:X.bossGear.length};});
test('the forge shows an exclusive weapon tab and the note about original or substitute materials',()=>{const craft=fs.readFileSync(dir+'/app_experience.js','utf8'),html=fs.readFileSync(dir+'/index.html','utf8'),build=fs.readFileSync(root+'/tools/build.py','utf8');
 assert(craft.includes("['EXCLUSIVE','전용 무기']")&&craft.includes('exclusiveOwner'));assert(html.indexOf('runtime_exclusive_weapons.js')>html.indexOf('runtime_liyue_forge.js')&&html.indexOf('runtime_exclusive_weapons.js')<html.indexOf('runtime_enhancement.js'));assert(build.includes("'runtime_exclusive_weapons.js'"));
 const icons=JSON.parse(fs.readFileSync(root+'/content/item-icons.json','utf8')).icons;for(const g of [...X.weapons,...X.bossGear])assert(icons[g.id]&&fs.existsSync(root+'/'+icons[g.id].path),g.id);return {};});
fs.mkdirSync(root+'/reports/exclusive_weapons',{recursive:true});fs.writeFileSync(root+'/reports/exclusive_weapons/runtime-tests.json',JSON.stringify(report,null,2)+'\n');
const failed=report.checks.filter(c=>!c.passed).length;console.log(JSON.stringify({total:report.checks.length,passed:report.checks.length-failed,failed}));if(failed)process.exitCode=1;
