'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const h=require('../tests/helpers_v011.cjs'),{R,db,c}=h;let passed=0;
function test(name,fn){try{const e=fn()||{};passed++;console.log('PASS '+name+' '+JSON.stringify(e));}catch(err){console.error('FAIL '+name+'\n'+err.stack);process.exitCode=1;}}
function fresh(route='ROUTE_TRAVELER'){const r=new R(db);r.newGame({name:route==='ROUTE_TRAVELER'?'여행자검증':'이세계인검증',route,seed:1223,saveId:'STEP12BC-'+route});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',SCREEN_MODE:'LOCATION',STORY_MENU_POLICY:'',WORLD_TIME:'12:00',PLAYER_BASE_HP:100000});delete r.s.storyContext;try{r.prepareStory();}catch{}r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;return r;}
test('Hydro Slime keeps native Hydro aura after Pyro reaction',()=>{const r=fresh(),cfg=c.CRPGRuntime.mondEncounterConfig;let found=null;for(const map of Object.keys(cfg.maps)){const threat=r.mondAreaThreat(map);const entry=threat.entries.find(e=>e.monsters.some(m=>m.id==='MON_SLIME_HYDRO'));if(entry){found={map,group:entry.group};break;}}assert(found);r.s.global.CURRENT_MAP_ID=found.map;r.startBattle(found.group,'RANDOM');const slime=r.s.runtime.actors.find(a=>a.source==='MON_SLIME_HYDRO'),player=r.s.runtime.actors.find(a=>a.source==='PLAYER_CUSTOM');assert(slime);assert.equal(slime.nativeAura,'물');assert.equal(slime.aura,'물');r.damage(player,slime,.1,'PYRO',{sureHit:true});assert.equal(slime.nativeAura,'물');assert.equal(slime.aura,'물');return{map:found.map,aura:slime.aura};});
test('shield absorbs damage independently from HP and records absorption',()=>{const r=fresh();r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';const group=r.mondAreaThreat().entries[0].group;r.startBattle(group,'RANDOM');const player=r.s.runtime.actors.find(a=>a.source==='PLAYER_CUSTOM'),enemy=r.s.runtime.actors.find(a=>a.side==='ENEMY');const hp=player.hp;r.shield(player,100,'TEST_SHIELD',3);assert.equal(player.shields[0].initialValue,100);r.applyDamage(enemy,player,60,{element:'물리'});assert.equal(player.hp,hp);assert.equal(player.shields[0].value,40);const log=r.s.runtime.log.at(-1);assert.equal(log.absorbed,60);assert.equal(log.damage,0);return{shield:player.shields[0].value,absorbed:log.absorbed};});
test('combat UI exposes separate shield gauge, shield status and shield damage wording',()=>{const src=fs.readFileSync(path.join(h.root,'source/app_experience.js'),'utf8');for(const marker of ["shield-meter","meter(shieldBox,'보호막'","'보호막 '+Math.round(shieldValue)","'보호막 피해 '+e.absorbed"])assert(src.includes(marker),marker);return{};});
test('Traveler remains sword-only',()=>{const r=fresh('ROUTE_TRAVELER');assert.deepEqual(Array.from(r.equipmentProficiencies('PLAYER_CUSTOM')),['한손검']);const sword=r.giveEquipment('EQ_CRPG_WORN_SWORD');assert.doesNotThrow(()=>r.equip(sword,'PLAYER_CUSTOM'));const bow=r.giveEquipment('EQ_CRPG_TRAINING_BOW');assert.throws(()=>r.equip(bow,'PLAYER_CUSTOM'),e=>e.code==='PROFICIENCY');return{proficiencies:Array.from(r.equipmentProficiencies('PLAYER_CUSTOM'))};});
test('Isekai protagonist equips all five weapon classes',()=>{const r=fresh('ROUTE_ISEKAI'),ids={한손검:'EQ_CRPG_WORN_SWORD',양손검:'EQ_CRPG_TRAINING_CLAYMORE',장병기:'EQ_CRPG_TRAINING_POLEARM',활:'EQ_CRPG_TRAINING_BOW',법구:'EQ_CRPG_TRAINING_CATALYST'},got=Array.from(r.equipmentProficiencies('PLAYER_CUSTOM'));assert.deepEqual(got,['한손검','양손검','장병기','활','법구']);for(const [type,id] of Object.entries(ids)){const slot=r.giveEquipment(id);assert.doesNotThrow(()=>r.equip(slot,'PLAYER_CUSTOM'),type+' '+id);assert.equal(r.s.inventory.find(x=>x.slot===slot).equipped,true);}return{proficiencies:got};});
console.log(JSON.stringify({total:5,passed}));if(passed!==5)process.exitCode=1;
