'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),DB=JSON.parse(fs.readFileSync(root+'/content/db.json')),runtimeDir=process.env.CRPG_RUNTIME_DIR||'source';
function stack(dir){const c=vm.createContext({console,Date:class extends Date{static now(){return 1790355600000;}},setTimeout,clearTimeout,TextEncoder,TextDecoder});const html=fs.readFileSync(dir+'/index.html','utf8');for(const[,f]of html.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ?]*)\.js)(?:\?[^" ]*)?"/g))vm.runInContext(fs.readFileSync(dir+'/'+f,'utf8'),c,{filename:f});vm.runInContext(fs.readFileSync(dir+'/journal_presenter.js','utf8'),c,{filename:'journal_presenter.js'});return c;}
const ctx=stack(root+'/'+runtimeDir),R=ctx.CRPGRuntime.Runtime,J=ctx.CRPGJournalPresenter,report={version:'0.13.27',runtimeDir,scope:'mission journal, collapsible affinity missions, official item icons',checks:[]};
function test(n,f){try{report.checks.push({name:n,passed:true,evidence:f()||null});console.log('PASS '+n);}catch(e){report.checks.push({name:n,passed:false,error:e.stack});console.error('FAIL '+n+'\n'+e.stack);}}
let seq=0;const L=x=>JSON.parse(JSON.stringify(x));// values from the VM realm compare by content
function fresh(route='ROUTE_TRAVELER'){const r=new R(DB);r.newGame({name:'임무정리',route,seed:1327,saveId:'JOURNAL-'+(++seq)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:'MAP_MOND_CITY',WORLD_TIME:'12:00',STORY_MENU_POLICY:'',SCREEN_MODE:'LOCATION',MORA:999999});delete r.s.storyJourney;delete r.s.storyBreak;try{r.prepareStory();}catch{}r.s.flags.FLAG_TRV_MON_PROLOGUE_CLEAR=true;r.s.flags.FLAG_ISK_MON_PROLOGUE_CLEAR=true;return r;}
const legends=r=>[...r.storyIndex().legends.values()].filter(d=>d.ROUTE_SCOPE===r.s.global.STORY_ROUTE_ID);
function finishLegend(r,d){r.s.storyEventReceipts??={};r.s.storyEventReceipts[d.id]=true;for(const a of r.storyIndex().affections.values())if(a.ROUTE_SCOPE===d.ROUTE_SCOPE&&a.PROFILE_ID===d.PROFILE_ID)for(const f of JSON.parse(a.REQUIRED_FLAGS||'[]'))r.s.flags[f]=true;}
function meet(r,pid,score){const x=r.relation?r.relation(pid):r.markContact(pid);x.firstContact=x.firstContact??1;x.BOND_SCORE=score;return x;}
// A Mond city personal mission whose first affinity scene is also in Mond city.
function cityPair(r){for(const d of legends(r)){if(d.MAP_ID!=='MAP_MOND_CITY')continue;const h=[...r.storyIndex().affections.values()].find(a=>a.ROUTE_SCOPE===d.ROUTE_SCOPE&&a.PROFILE_ID===d.PROFILE_ID&&/_H01$/.test(a.id)&&a.MAP_ID==='MAP_MOND_CITY');if(h)return{d,pid:d.PROFILE_ID};}throw Error('no city pair');}
test('in progress lists only introduced, unfinished companion missions',()=>{const r=fresh(),ds=legends(r).slice(0,5);assert.deepEqual(L(J.inProgress(r).legends),[]);r.s.guildLegends={};for(const d of ds.slice(0,3))r.s.guildLegends[d.id]={day:1};finishLegend(r,ds[2]);const ids=L(J.inProgress(r).legends.map(m=>m.id)).sort();assert.deepEqual(ids,[ds[0].id,ds[1].id].sort());for(const d of ds.slice(3))assert(!ids.includes(d.id));return{introduced:3,finished:1,listed:ids.length};});
test('companion missions carry place-aware status and unmet requirements',()=>{const r=fresh(),{d}=cityPair(r);r.s.guildLegends={[d.id]:{day:1}};let m=J.inProgress(r).legends[0];assert.equal(m.id,d.id);assert.notEqual(m.status,'travel');r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';m=J.inProgress(r).legends[0];assert(['travel','locked'].includes(m.status));if(m.status==='travel')assert.equal(m.map,'MAP_MOND_CITY');assert(m.requirements.every(q=>q.kind!=='introduction'));return{here:J.inProgress(fresh()).legends.length,away:m.status};});
test('affinity track is ordered and explains the real blocker',()=>{const r=fresh(),{d,pid}=cityPair(r);meet(r,pid,25);let t=J.affectionTrack(r,pid);assert(t.length>=5);assert.deepEqual(L(t.slice(0,5).map(x=>x.stage)),[1,2,3,4,5]);assert(t.slice(5).every(x=>x.stage===0&&/^유대 이야기/.test(x.label)));assert.equal(t[0].status,'locked');assert.match(t[0].reason,/개인 임무/);finishLegend(r,d);t=J.affectionTrack(r,pid);assert.equal(t[0].status,'ready');assert.equal(t[1].status,'locked');assert.match(t[1].reason,/앞선 관계 이야기/);r.s.storyEventReceipts[t[0].id]=true;t=J.affectionTrack(r,pid);assert.equal(t[0].status,'done');assert.equal(t[1].status,'locked');assert.equal(t[1].reason,'호감도 40점 필요 · 현재 25점');r.s.relations[pid].BOND_SCORE=45;t=J.affectionTrack(r,pid);assert(['ready','travel'].includes(t[1].status));assert.equal(t[1].need,40);return t.slice(0,3).map(x=>x.short+':'+x.status);});
test('only the place is missing -> travel, not locked',()=>{const r=fresh(),{d,pid}=cityPair(r);meet(r,pid,25);finishLegend(r,d);r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';const h1=J.affectionTrack(r,pid)[0];assert.equal(h1.status,'travel');assert.equal(h1.map,'MAP_MOND_CITY');return h1;});
test('affinity missions in progress show the next playable stage per person',()=>{const r=fresh(),{d,pid}=cityPair(r),other=legends(r).find(x=>x.PROFILE_ID!==pid);meet(r,other.PROFILE_ID,100);meet(r,pid,25);finishLegend(r,d);const j=J.inProgress(r);assert.deepEqual(L(j.affections.map(a=>a.profile)),[pid]);assert.equal(j.affections[0].next.stage,1);assert.equal(j.waiting,1);return j.affections[0].next;});
test('relations put people with something to play first and keep insertion order otherwise',()=>{const r=fresh(),{d,pid}=cityPair(r),other=legends(r).find(x=>x.PROFILE_ID!==pid);meet(r,other.PROFILE_ID,100);meet(r,pid,25);finishLegend(r,d);const people=J.relations(r);assert.equal(people[0].profile,pid);assert.equal(people[1].profile,other.PROFILE_ID);assert.equal(people[0].hearts,1);assert.equal(people[1].hearts,5);assert.equal(people[0].next.status,'ready');return people.map(p=>p.name+':'+(p.next?.status||'none'));});
test('presenter never changes the save',()=>{const r=fresh(),{d,pid}=cityPair(r);meet(r,pid,25);r.s.guildLegends={[d.id]:{day:1}};r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';const before=r.serialize();J.inProgress(r);J.relations(r);J.affectionTrack(r,pid);assert.equal(r.serialize(),before);});
test('both routes build a journal without errors',()=>{const out={};for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI']){const r=fresh(route);r.s.guildLegends={};for(const d of legends(r).slice(0,6))r.s.guildLegends[d.id]={day:1};const j=J.inProgress(r);assert.equal(j.legends.length,6);out[route]=j.legends.map(m=>m.status);}return out;});
test('mission and affinity screens use the journal (source)',()=>{const read=f=>fs.readFileSync(path.join(root,runtimeDir,f),'utf8'),adv=read('app_adventure.js'),exp=read('app_experience.js'),life=read('app_life.js'),html=read('index.html'),css=read('style.css'),sw=read('sw.js');for(const f of ['app_adventure.js','app_experience.js','app_life.js','journal_presenter.js'])new vm.Script(read(f),{filename:f});
 assert(adv.includes("for(const label of ['진행 중','동료 획득','완료'])"));assert(!adv.includes("'진행 중','동료 획득','개인 임무','완료'"));assert(adv.includes('CRPGJournalPresenter.inProgress(game)'));for(const t of ["journalSection(p,'의뢰'","journalSection(p,'동료 획득 임무'","journalSection(p,'호감도 임무'"])assert(adv.includes(t));
 assert(exp.includes("el('details','relationship-missions')")&&exp.includes('openRelationMissions')&&exp.includes("'모두 펼치기'")&&exp.includes("'모두 접기'"));assert(exp.includes('CRPGJournalPresenter.relations(game)'));assert(!life.includes("missionTab='개인 임무'"));
 assert(html.indexOf('journal_presenter.js')>html.indexOf('inventory_presenter.js')&&html.indexOf('journal_presenter.js')<html.indexOf('app_experience.js'));assert(sw.includes("'journal_presenter.js'"));assert(css.includes('.relationship-missions>summary')&&css.includes('.journal-section'));
 if(runtimeDir==='source')assert(fs.readFileSync(path.join(root,'tools/build.py'),'utf8').includes("'journal_presenter.js'"));});
test('item icons: every recorded texture ships and matches its hash',()=>{const icons=JSON.parse(fs.readFileSync(path.join(root,'content/item-icons.json'),'utf8')),kinds={};assert.equal(icons.unavailable.length,0);for(const[id,x]of Object.entries(icons.icons)){const file=path.join(root,x.path);assert(fs.existsSync(file),id+' '+x.path);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),x.sha256,id);kinds[x.matchType]=(kinds[x.matchType]||0)+1;if(x.matchType==='official_base_visual')assert(x.sourceName&&x.note,id);}assert(Object.keys(icons.icons).length>=265);return kinds;});
test('item icons: former fallbacks now resolve to their own texture',()=>{const icons=JSON.parse(fs.readFileSync(path.join(root,'content/item-icons.json'),'utf8')).icons,want={TRPG_TACTICAL_ELEMENT_CONVERTER:'UI_ItemIcon_220021',TRPG_REPAIR_KIT:'UI_ItemIcon_220028',TRPG_MEDKIT:'UI_ItemIcon_220008',EQ_SWORD_FINALE:'UI_EquipIcon_Sword_Vorpal',EQ_ARMOR_IRON_GUARD:'UI_RelicIcon_15017_3',MAT_TRANSOCEANIC_PEARL:'UI_ItemIcon_112080',MAT_XENOCHROMATIC_CRYSTAL:'UI_ItemIcon_112082',FOOD_SNEZ_BORSCHT:'UI_ItemIcon_108889',MAT_LIYUE_QINGXIN:'UI_ItemIcon_100031'};for(const[id,tex]of Object.entries(want))assert.equal(icons[id].path,'assets/icons/'+tex+'.webp',id);
 const P=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(root,'source/inventory_presenter.js'),'utf8'),P);const presenter=P.CRPGInventoryPresenter.create(DB,{itemIcons:JSON.parse(fs.readFileSync(path.join(root,'content/item-icons.json'),'utf8'))});for(const id of ['TRPG_BANDAGE','TRPG_FISHING_ROD'])assert.equal(presenter.itemDetail({item:id,quantity:1}).icon.matchType,'official_base_visual');assert.equal(presenter.itemDetail({equip:'EQ_ACC_HEALER_BROOCH',quantity:1,enhance:0}).icon.url,'assets/icons/UI_RelicIcon_10007_4.webp');});
report.total=report.checks.length;report.passed=report.checks.filter(x=>x.passed).length;fs.mkdirSync(root+'/reports/journal_step10',{recursive:true});fs.writeFileSync(root+'/reports/journal_step10/runtime-tests.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({total:report.total,passed:report.passed}));if(report.total!==report.passed)process.exitCode=1;
