'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const h=require('../tests/helpers_v011.cjs'),{R,db,c}=h;
let passed=0;function test(name,fn){try{const e=fn()||{};passed++;console.log('PASS '+name+' '+JSON.stringify(e));}catch(err){console.error('FAIL '+name+'\n'+err.stack);process.exitCode=1;}}
function fresh(){const r=new R(db);r.newGame({name:'12-2A 검증',route:'ROUTE_TRAVELER',seed:1231,saveId:'STEP12-2A'});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',SCREEN_MODE:'LOCATION',STORY_MENU_POLICY:'',CURRENT_MAP_ID:'MAP_MOND_PLAINS',WORLD_TIME:'12:00',PLAYER_BASE_HP:100000});delete r.s.storyContext;try{r.prepareStory();}catch{}r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;return r;}
test('Mond random pools contain no Treasure Hoarder species',()=>{const r=fresh(),cfg=c.CRPGRuntime.mondEncounterConfig;let groups=0;for(const map of Object.keys(cfg.maps)){const entries=r.rows('34_MAP_ENCOUNTER_POOL').filter(x=>x[1]===map);assert.equal(entries.length,4,map);for(const e of entries){groups++;const members=r.rows('49_ENCOUNTER_MEMBER_DB').filter(x=>x[1]===e[5]).map(x=>x[3]);assert(members.length, e[5]);assert(members.every(id=>!id.startsWith('MON_TH_')),map+' '+e[5]+' '+members.join(','));}}assert.equal(groups,Object.keys(cfg.maps).length*4);assert(!JSON.stringify(cfg).includes('MON_TH_'));return{maps:Object.keys(cfg.maps).length,groups};});
test('Liyue Treasure Hoarder group remains available',()=>{const r=fresh(),members=r.rows('49_ENCOUNTER_MEMBER_DB').filter(x=>x[1]==='EG_TREASURE_PATROL').map(x=>x[3]);assert(members.some(id=>id.startsWith('MON_TH_')));r.s.global.CURRENT_MAP_ID='MAP_LIYUE_PLAINS';assert.doesNotThrow(()=>r.startBattle('EG_TREASURE_PATROL','EXPLICIT'));return{members};});
test('Dvalin story portrait has a shipped enemy-art fallback',()=>{const r=fresh(),m=r.row('09_MONSTER_DB','BOSS_DVALIN'),key='enemy_'+m[15]+'.png',manifest=JSON.parse(fs.readFileSync(path.join(h.root,'content/asset-manifest.json'),'utf8')),app=fs.readFileSync(path.join(h.root,'source/app.js'),'utf8');assert(m[15]);const blob=JSON.stringify(manifest);assert(blob.includes(key)||blob.includes('enemy_'+m[15]),key);assert(app.includes("game.tables['09_MONSTER_DB'].get(n[6])"));assert(app.includes("assetPath('enemy_'+monster[15]+'.png')"));return{name:m[1],asset:key};});
test('Dvalin terrain collapse records one explicit defeat reason',()=>{const r=fresh();r.s.global.CURRENT_MAP_ID='MAP_STORMTERROR_LAIR';r.startBattle('EG_BOSS_DVALIN','EXPLICIT');const b=r.s.runtime;b.terrain=1;b.round=2;r.roundEnd();assert.equal(r.s.runtime,null);const result=JSON.parse(r.s.global.LAST_BATTLE_RESULT_JSON);assert.equal(result.victory,false);assert.equal(result.defeatReason,'TERRAIN_COLLAPSE');assert.equal(result.defeatMessage,'지형이 모두 무너져 전멸했습니다.');return{reason:result.defeatReason,message:result.defeatMessage};});
test('result UI names the player for gained XP and shows defeat cause once',()=>{const src=fs.readFileSync(path.join(h.root,'source/app_legacy.js'),'utf8');assert(src.includes("game.s.global.PLAYER_NAME+' 경험치 획득 +'"));assert(src.includes("if(!b.victory&&b.defeatMessage)p.append"));return{};});
console.log(JSON.stringify({total:5,passed}));if(passed!==5)process.exitCode=1;
