'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),DB=JSON.parse(fs.readFileSync(root+'/content/db.json')),runtimeDir=process.env.CRPG_RUNTIME_DIR||'source';
function stack(dir){const c=vm.createContext({console,Date:class extends Date{static now(){return 1790355600000;}},setTimeout,clearTimeout,TextEncoder,TextDecoder});const html=fs.readFileSync(dir+'/index.html','utf8');for(const[,f]of html.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ?]*)\.js)(?:\?[^" ]*)?"/g))vm.runInContext(fs.readFileSync(dir+'/'+f,'utf8'),c,{filename:f});vm.runInContext(fs.readFileSync(dir+'/save_adapter.js','utf8'),c,{filename:'save_adapter.js'});return c;}
const ctx=stack(root+'/'+runtimeDir),R=ctx.CRPGRuntime.Runtime,report={version:'0.13.21',runtimeDir,scope:'priority 4 staged Liyue recruitment',checks:[],stages:{}};
function test(n,f){try{report.checks.push({name:n,passed:true,evidence:f()||null});console.log('PASS '+n);}catch(e){report.checks.push({name:n,passed:false,error:e.stack});console.error('FAIL '+n+'\n'+e.stack);}}
function fresh(route='ROUTE_ISEKAI'){const r=new R(DB);r.newGame({name:'리월영입검증',route,seed:421,saveId:'LY-REC-'+route});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'HUB',STORY_CURSOR_NODE_ID:'HUB',ACTIVE_STORY_QUEST:'',SCREEN_MODE:'LOCATION',STORY_MENU_POLICY:'FULL',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',WORLD_TIME:'12:00',MORA:100000});for(const k of ['storyJourney','storyBreak','storyArrival','storyMenuFrame','storyContext','battlePreparation','storyRecovery'])delete r.s[k];return r;}
function finish(r,n){const q=(r.s.global.STORY_ROUTE_ID==='ROUTE_ISEKAI'?'Q_ISK_LIYUE_0':'Q_TRV_LIYUE_0')+n;Object.assign(r.questState(q),{state:'완료',claimed:true,completedTurn:0,acceptedTurn:0});return q;}
function def(r,ch){return[...r.storyIndex().legends.values()].find(d=>d.ROUTE_SCOPE===r.s.global.STORY_ROUTE_ID&&d.CHAR_ID===ch);}
function reg(r,d){r.s.global.CURRENT_MAP_ID=d.MAP_ID;r.s.guildLegends??={};r.s.guildLegends[d.id]={day:r.s.global.WORLD_DAY};}
const stages={1:['LIYUE_XIANGLING','LIYUE_XINGQIU','LIYUE_CHONGYUN','LIYUE_YAOYAO','LIYUE_GAMING','LIYUE_XINYAN','LIYUE_YANFEI','LIYUE_YUNJIN','LIYUE_LANYAN','LIYUE_XIAO','LIYUE_BEIDOU','LIYUE_HUTAO'],2:['LIYUE_KEQING','LIYUE_QIQI','LIYUE_YELAN','LIYUE_GANYU'],3:['LIYUE_TARTAGLIA'],4:['LIYUE_NINGGUANG','LIYUE_BAIZHU','LIYUE_SHENHE','LIYUE_XIANYUN','LIYUE_ZIBAI']};
test('both routes patch all 22 non-Archon Liyue legends into staged chapter gates',()=>{for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI']){const r=fresh(route),ds=[...r.storyIndex().legends.values()].filter(d=>d.ROUTE_SCOPE===route&&d.REGION==='리월'&&d.CHAR_ID!=='LIYUE_ZHONGLI'),c={};assert.equal(ds.length,22);for(const d of ds){c[d.LIYUE_RECRUIT_STAGE]=(c[d.LIYUE_RECRUIT_STAGE]||0)+1;assert.match(d.START_CONDITION,/DONE\(Q_(?:TRV|ISK)_LIYUE_0[1-4]\)=TRUE/);assert(!/LIYUE_PERSONAL_READY|FLAG_TRV_LIYUE_CLEAR|FLAG_ISK_L04_REGION_CLEAR/.test(d.START_CONDITION));assert.equal(r.storyIndex().nodes.get(route+':'+d.ENTRY_NODE_ID)[11],d.START_CONDITION);}assert.deepEqual(c,{1:12,2:4,3:1,4:5});report.stages[route]=c;}return report.stages;});
test('stage membership exact and Zhongli special unchanged',()=>{const r=fresh('ROUTE_TRAVELER');for(const[s,cs]of Object.entries(stages))for(const ch of cs)assert.equal(def(r,ch).LIYUE_RECRUIT_STAGE,+s);const z=def(r,'LIYUE_ZHONGLI');assert.equal(z.LIYUE_RECRUIT_STAGE,undefined);assert(/FLAG_TRV_LIYUE_CLEAR|LIYUE_PERSONAL_READY/.test(z.START_CONDITION));assert.match(r.recruitmentEntries().find(e=>e.character==='LIYUE_ZHONGLI').method,/눈동자 전량 수집/);});
test('stage 1 opens after chapter 1 without region completion',()=>{for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI']){const r=fresh(route),d=def(r,'LIYUE_XIANGLING');reg(r,d);assert.notEqual(r.storyEntryReason(d),'');finish(r,1);assert.equal(r.storyEntryReason(d),'');r.action('LEGEND_ENTER',{quest:d.id});assert.equal(r.s.storyContext.entry,d.id);const n=r.storyNode();assert(n&&n[1]===d.QUEST_ID&&n[2]===d.id);}return{routes:2};});
test('higher stages stay locked until exact chapter',()=>{const r=fresh();for(const[ch,s]of [['LIYUE_KEQING',2],['LIYUE_TARTAGLIA',3],['LIYUE_NINGGUANG',4]]){const d=def(r,ch);reg(r,d);for(let n=1;n<s;n++)finish(r,n);assert.notEqual(r.storyEntryReason(d),'');finish(r,s);assert.equal(r.storyEntryReason(d),'');}return{Keqing:2,Tartaglia:3,Ningguang:4};});
test('Zibai keeps return flag',()=>{const r=fresh(),d=def(r,'LIYUE_ZIBAI');reg(r,d);for(let n=1;n<=4;n++)finish(r,n);assert.notEqual(r.storyEntryReason(d),'');r.s.flags.FLAG_WORLD_ZIBAI_RETURNED=true;assert.equal(r.storyEntryReason(d),'');});
test('requirements show exact chapter',()=>{const r=fresh();finish(r,1);for(const[ch,s]of [['LIYUE_HUTAO',1],['LIYUE_GANYU',2],['LIYUE_TARTAGLIA',3],['LIYUE_NINGGUANG',4]]){const q=r.legendRequirements(def(r,ch),{cost:false,location:false,introduction:false}).find(x=>x.kind==='story'&&/리월 본편/.test(x.label));assert.equal(q.label,'리월 본편 '+s+'장 완료');assert.equal(q.met,s===1);}});
test('free rejoin no longer demands finale',()=>{const r=fresh(),d=def(r,'LIYUE_XIANGLING');finish(r,1);Object.assign(r.questState(d.QUEST_ID),{state:'완료',claimed:true});r.s.flags[d.COMPLETE_FLAG_ID]=true;r.s.global.COMPANION_ELIGIBILITY_JSON='{}';const row=r.storyIndex().nodes.get(r.s.global.STORY_ROUTE_ID+':'+d.id+'_REJOIN_START');r.s.global.CURRENT_MAP_ID=row[8];assert.equal(r.recruitmentRejoinEntry(d).reason,'');});
test('Isekai Liyue progress no longer blocks Mond registration',()=>{const r=fresh(),d=r.storyDefinition('LEG_ISK_MOND_AMBER');r.s.flags.FLAG_ISK_MAIN_UNLOCKED=true;r.s.flags.FLAG_ISK_MON_PROLOGUE_CLEAR=true;r.ensureLiyue();r.s.liyue.activeQuest='Q_ISK_LIYUE_02';r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';r.action('PLACE_ENTER',{place:'EVT_SCHEDULE_NPC_MOND_SARA',mode:'SHOP'});assert.equal(r.actionReason('LEGEND_REGISTER',{quest:d.id}),'');});
test('Liyue guild opens between chapters but stays blocked inside next chapter',()=>{const r=fresh();r.ensureLiyue();r.s.global.CURRENT_MAP_ID='MAP_LIYUE_HARBOR';r.s.liyue.activeQuest='Q_ISK_LIYUE_01';finish(r,1);r.s.liyue.activeQuest='';assert.equal(r.actionReason('PLACE_ENTER',{place:'EVT_CRPG_LIYUE_GUILD',mode:'TALK'}),'');r.s.liyue.activeQuest='Q_ISK_LIYUE_02';assert.match(r.actionReason('PLACE_ENTER',{place:'EVT_CRPG_LIYUE_GUILD',mode:'TALK'}),/허가된 본편 구역/);});
test('save reload preserves staged availability',()=>{const r=fresh('ROUTE_TRAVELER');finish(r,2);const d=def(r,'LIYUE_GANYU');reg(r,d);assert.equal(r.storyEntryReason(d),'');const rr=new R(DB,JSON.parse(r.serialize())),a=def(rr,'LIYUE_GANYU');assert.equal(a.LIYUE_RECRUIT_STAGE,2);assert.equal(rr.storyEntryReason(a),'');assert.equal(rr.serialize(),r.serialize());});
report.total=report.checks.length;report.passed=report.checks.filter(x=>x.passed).length;fs.mkdirSync(root+'/reports/liyue_recruitment_step4',{recursive:true});fs.writeFileSync(root+'/reports/liyue_recruitment_step4/runtime-tests.json',JSON.stringify(report,null,2));console.log(JSON.stringify({total:report.total,passed:report.passed,stages:report.stages},null,2));if(report.total!==report.passed)process.exitCode=1;
