'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const h=require('../tests/helpers_v011.cjs'),{R,db,c}=h;let seq=0,results=[];
function test(name,fn){try{results.push({name,ok:true,evidence:fn()||null});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function fresh(map='MAP_LIYUE_PLAINS',level=12,count=1){
 const r=new R(db);r.newGame({name:'step11',route:'ROUTE_TRAVELER',seed:1329+seq,saveId:'STEP11-'+(++seq)});
 Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,WORLD_TIME:'12:00',STORY_MENU_POLICY:'',SCREEN_MODE:'LOCATION',MORA:999999,PLAYER_LEVEL_STATE:level,PLAYER_BASE_HP:100000});
 delete r.s.storyJourney;delete r.s.storyBreak;try{r.prepareStory();}catch{}r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;
 for(const [i,id]of ['MOND_AMBER','MOND_KAEYA','MOND_LISA'].slice(0,Math.max(0,count-1)).entries()){r.unlockCharacter(id);r.action('PARTY',{char:id,slot:i+2});}
 return r;
}
function resetBattle(r){r.s.runtime=null;delete r.s.battlePreparation;Object.assign(r.s.global,{MODE:'NORMAL',ACTIVE_BATTLE_ID:'',COMBAT_ACTION_PHASE:'NONE',SCREEN_MODE:'LOCATION'});}
const cfg=c.CRPGRuntime.liyueEncounterConfig,allowed=new Set(cfg.allowedMonsterIds);
test('covers exactly all 23 current Liyue random maps',()=>{const r=fresh(),runtime=r.rows('32_MAP_DB').filter(x=>x[1]==='리월'&&x[8]==='Y'&&x[12]!=='Y').map(x=>x[0]).sort(),configured=Object.keys(cfg.maps).sort();assert.equal(runtime.length,23);assert.deepEqual(runtime,configured);return{maps:runtime.length};});
test('every map has four contiguous d100 entries and 92 unique local groups',()=>{const r=fresh(),groups=new Set();for(const map of Object.keys(cfg.maps)){const rows=r.rows('34_MAP_ENCOUNTER_POOL').filter(x=>x[1]===map);assert.equal(rows.length,4,map);rows.sort((a,b)=>Number(a[3])-Number(b[3]));let face=1;for(const row of rows){assert.equal(row[2],'d100');assert.equal(Number(row[3]),face);assert(row[5].startsWith('EG_LIYUE_LOCAL_'));assert(!String(row[10]).includes('상위 지역 편성 계승'));groups.add(row[5]);face=Number(row[4])+1;}assert.equal(face,101);}assert.equal(groups.size,92);return{maps:23,poolEntries:92,groups:groups.size};});
test('all 23 maps have distinct encounter signatures',()=>{const sig=Object.values(cfg.maps).map(a=>a.enc.map(x=>x.join(':')).join('|'));assert.equal(new Set(sig).size,23);return{signatures:23};});
test('new groups use only the eleven already-supported Liyue species and old six groups stay intact',()=>{const r=fresh(),expected={EG_TREASURE_PATROL:['MON_TH_SCOUT','MON_TH_MARKSMAN','MON_TH_POTION_PYRO'],EG_LIYUE_HILI_ROCK:['MON_MITACHURL_ROCK','MON_HILI_FIGHTER','MON_HILI_SHOOTER'],EG_LIYUE_VISHAP:['MON_GEOVISHAP_HATCHLING'],EG_LIYUE_RUIN:['MON_RUIN_GUARD_VARIANT'],EG_CHASM_HUSK:['MON_HUSK_STANDARD','MON_HUSK_BOW'],EG_CHASM_SERPENT:['MON_BLACK_SERPENT_SWORD','MON_HUSK_BOW']};for(const [id,want]of Object.entries(expected)){const got=r.rows('49_ENCOUNTER_MEMBER_DB').filter(x=>x[1]===id).map(x=>x[3]);assert.deepEqual(got,want,id);}for(const id of Object.keys(cfg.maps).flatMap(map=>r.rows('34_MAP_ENCOUNTER_POOL').filter(x=>x[1]===map).map(x=>x[5])))for(const m of r.rows('49_ENCOUNTER_MEMBER_DB').filter(x=>x[1]===id)){assert(allowed.has(m[3]),m[3]);assert.notEqual(r.row('09_MONSTER_DB',m[3])[3],'보스');}return{allowed:[...allowed]};});
test('all 92 local groups start successfully and use each map recommended level range',()=>{let started=0;for(const map of Object.keys(cfg.maps)){const r=fresh(map,12,1),m=r.row('32_MAP_DB',map),groups=r.rows('34_MAP_ENCOUNTER_POOL').filter(x=>x[1]===map).map(x=>x[5]);for(const group of groups){assert.doesNotThrow(()=>r.startBattle(group,'RANDOM'),map+' / '+group);const b=r.s.runtime,enemies=b.actors.filter(a=>a.side==='ENEMY');assert(enemies.length>=1&&enemies.length<=1);assert(enemies.every(a=>a.level>=Number(m[6])&&a.level<=Number(m[7])),map+' levels');assert.equal(b.group,group);started++;resetBattle(r);}}assert.equal(started,92);return{started};});
test('party-size limiter remains active on new groups',()=>{const map='MAP_LIYUE_PLAINS',group='EG_LIYUE_LOCAL_LIYUE_PLAINS_2',solo=fresh(map,12,1),full=fresh(map,12,4);solo.random=()=>.999999;full.random=()=>.999999;solo.startBattle(group,'RANDOM');full.startBattle(group,'RANDOM');const a=solo.s.runtime.actors.filter(x=>x.side==='ENEMY').length,b=full.s.runtime.actors.filter(x=>x.side==='ENEMY').length;assert.equal(a,1);assert(b>1&&b<=4);return{solo:a,party4:b};});
test('encounter opening exposes biome and composition role',()=>{const r=fresh('MAP_LY_DETAIL_YAOGUANG');r.startBattle('EG_LIYUE_LOCAL_LY_DETAIL_YAOGUANG_1','RANDOM');const e=r.s.runtime.encounter;assert(e);assert.match(e.label,/해안·모래톱/);assert.match(e.text,/원거리 매복조/);return{label:e.label,text:e.text};});
test('representative new groups keep LIYUE_FIELD_MORA_V2 settlement',()=>{const cases=[['MAP_LIYUE_PLAINS','EG_LIYUE_LOCAL_LIYUE_PLAINS_1'],['MAP_LY_DETAIL_GUILI','EG_LIYUE_LOCAL_LY_DETAIL_GUILI_1'],['MAP_LY_DETAIL_HULAO','EG_LIYUE_LOCAL_LY_DETAIL_HULAO_1'],['MAP_LY_DETAIL_GUYUN','EG_LIYUE_LOCAL_LY_DETAIL_GUYUN_1'],['MAP_CHASM_DEEP','EG_LIYUE_LOCAL_CHASM_DEEP_3']],out=[];for(const[map,group]of cases){const r=fresh(map,12,4);r.startBattle(group,'RANDOM');r.action('COMBAT_BEGIN',{battle:r.s.runtime.id});for(const a of r.s.runtime.actors.filter(x=>x.side==='ENEMY'))a.hp=0;r.die=()=>100;const before=r.s.global.MORA,res=r.finishBattle(true),delta=r.s.global.MORA-before;assert.equal(res.rewardPolicy,'LIYUE_FIELD_MORA_V2');assert.equal(res.mora,delta);assert(delta>=10&&delta<=180);out.push({map,group,mora:delta});}return out;});
test('step10 artifact loop remains installed and separate',()=>{const r=fresh('MAP_LIYUE_GOLDEN_HOUSE');assert.equal(r.liyueArtifactModuleVersion,1);assert.deepEqual(Object.keys(c.CRPGRuntime.liyueArtifactConfig.farm).sort(),['AZHDAHA','TARTAGLIA']);return{artifactVersion:r.liyueArtifactModuleVersion};});
test('v0.13.29 source, build and release metadata are wired',()=>{const root=h.root,index=fs.readFileSync(path.join(root,'source/index.html'),'utf8'),build=fs.readFileSync(path.join(root,'tools/build.py'),'utf8'),pkg=require(path.join(root,'package.json')),notes=JSON.parse(fs.readFileSync(path.join(root,'content/release-notes.json'),'utf8'));assert(index.includes('runtime_liyue_encounters.js'));assert(build.includes('runtime_liyue_encounters.js'));assert.equal(pkg.version,'0.13.29');assert.equal(notes.version,'0.13.29');return{version:pkg.version};});
const report={version:'0.13.29',total:results.length,passed:results.filter(x=>x.ok).length,results};console.log(JSON.stringify({total:report.total,passed:report.passed,failed:report.total-report.passed}));if(report.total!==report.passed)process.exitCode=1;
