'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const h=require('../tests/helpers_v011.cjs'),{R,db,c}=h;let seq=0,results=[];
function test(n,f){try{results.push({name:n,ok:true,evidence:f()||null});console.log('PASS '+n);}catch(e){results.push({name:n,ok:false,error:e.stack});console.error('FAIL '+n+'\n'+e.stack);}}
function fresh(map='MAP_LIYUE_HARBOR',level=13){const r=new R(db);r.newGame({name:'v01323',route:'ROUTE_TRAVELER',seed:1323+seq,saveId:'V01323-'+(++seq)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'HUB',STORY_CURSOR_NODE_ID:'HUB',ACTIVE_STORY_QUEST:'',SCREEN_MODE:'LOCATION',STORY_MENU_POLICY:'FULL',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',STORY_WAITING:false,CURRENT_MAP_ID:map,WORLD_TIME:'12:00',MORA:100000,PLAYER_LEVEL_STATE:level,PLAYER_XP_STATE:0,PLAYER_BASE_HP:100000});for(const k of ['storyJourney','storyBreak','storyArrival','storyMenuFrame','storyContext'])delete r.s[k];r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;r.s.flags.FLAG_ACCESS_REGION_LIYUE=true;r.ensureExplorationState?.();if(r.s.exploration)r.s.exploration.visitedMaps[map]=true;return r;}
test('hatchling inherits common vishap skills',()=>{const r=fresh('MAP_LIYUE_JUEYUN',7);r.startBattle('EG_LIYUE_VISHAP','RANDOM');const a=r.s.runtime.actors.find(x=>x.source==='MON_GEOVISHAP_HATCHLING'),cards=r.actorCards(a);assert.deepEqual(Array.from(cards,x=>x.id).sort(),['ECARD_VISHAP_CHARGE','ECARD_VISHAP_TAIL']);assert(cards.every(x=>x.level===1&&!r.cardReason(a,x)));return{cards:Array.from(cards,x=>x.name)};});
test('ruin variant spin is available in Liyue field',()=>{const r=fresh('MAP_CHASM_SURFACE',8);r.startBattle('EG_LIYUE_RUIN','RANDOM');const a=r.s.runtime.actors.find(x=>x.source==='MON_RUIN_GUARD_VARIANT'),spin=r.actorCards(a).find(x=>x.id==='ECARD_RUIN_VARIANT_SPIN');assert(spin);assert.equal(spin.level,1);assert.equal(r.cardReason(a,spin),'');return{level:a.level};});
test('Mond monster resale is bounded',()=>{const r=fresh('MAP_MOND_CITY'),want={MAT_SLIME_CONDENSATE:6,MAT_SLIME_SECRETIONS:18,MAT_SLIME_CONCENTRATE:54,MAT_DAMAGED_MASK:6,MAT_STAINED_MASK:18,MAT_OMINOUS_MASK:54,MAT_WHOPPER_NECTAR:7,MAT_SHIMMERING_NECTAR:21,MAT_ENERGY_NECTAR:63,MAT_RECRUIT_INSIGNIA:8,MAT_SERGEANT_INSIGNIA:24,MAT_LIEUTENANT_INSIGNIA:72,MAT_CHAOS_DEVICE:12,MAT_CHAOS_CIRCUIT:36,MAT_CHAOS_CORE:108},got={};for(const[id,n]of Object.entries(want)){r.giveItem(id,1);got[id]=r.saleUnitPrice(r.s.inventory.find(x=>x.item===id));assert.equal(got[id],n);}return got;});
test('Liyue gains ten local commissions through Lv13',()=>{const q=c.CRPGRuntime.explorationCatalog.liyueQuests;assert.equal(q.length,10);assert.equal(Math.min(...q.map(x=>x.level)),4);assert.equal(Math.max(...q.map(x=>x.level)),13);const total=fresh().rows('22_QUEST_DB').filter(r=>r[2]==='리월'&&fresh().isCommission(r[0])).length;assert.equal(total,15);return{added:10,total};});
test('delivery commission consumes materials once',()=>{const r=fresh(),g=r.placeEntries().find(e=>e.entity==='NPC_LIYUE_KATHERYNE'),id='Q_CRPG_LIYUE_EXP_TREASURE_PROOF';r.action('PLACE_ENTER',{place:g.id,mode:'TALK'});r.action('COMMISSION_ACCEPT',{quest:id});r.giveItem('MAT_TREASURE_INSIGNIA',5);r.action('PLACE_LEAVE');r.action('QUEST_CHOICE',{quest:id,choice:'careful'});assert.equal(r.itemCount('MAT_TREASURE_INSIGNIA'),0);assert.equal(r.s.quests[id].node,'READY_TO_CLAIM');return{spent:5};});
test('three patrol requirement counts post-accept Liyue wins',()=>{const r=fresh(),g=r.placeEntries().find(e=>e.entity==='NPC_LIYUE_KATHERYNE'),id='Q_CRPG_LIYUE_EXP_THREE_PATROLS';r.action('PLACE_ENTER',{place:g.id,mode:'TALK'});r.action('COMMISSION_ACCEPT',{quest:id});r.action('PLACE_LEAVE');for(let i=0;i<3;i++){r.s.global.CURRENT_MAP_ID='MAP_LIYUE_PLAINS';r.s.global.LAST_COMMITTED_ACTION_SEQ++;r.startBattle('EG_TREASURE_PATROL','RANDOM');for(const a of r.s.runtime.actors.filter(x=>x.side==='ENEMY'))a.hp=0;r.finishBattle(true);}r.s.global.CURRENT_MAP_ID='MAP_LIYUE_HARBOR';assert.equal(r.questConditions(id),'');return{wins:JSON.parse(r.s.global.WORLD_VISIT_COUNTS_JSON).LIYUE_ENCOUNTERS};});
test('facility UI uses bundled icon set and removes duplicate edge list',()=>{const app=fs.readFileSync(path.join(h.root,'source/app_adventure.js'),'utf8');for(const n of ['UI_Icon_Intee_Blacksmith.png','UI_Icon_Intee_Restaurant.png','UI_Icon_Intee_Cooking.png','UI_Icon_Intee_GeneralCargo.png','UI_Icon_Intee_Combine.png','UI_Icon_Intee_DailyEvent_0.png','UI_Icon_Intee_Comfort.png','UI_Icon_Intee_Shop.png','UI_Icon_Intee_Talk.png'])assert(app.includes('assets/icons/facility/'+n));assert(!app.includes('다른 구역으로 이동'));return{icons:6};});
test('destination cards travel immediately, pins remain preview',()=>{const app=fs.readFileSync(path.join(h.root,'source/app_navigation.js'),'utf8');assert(app.includes("actionButton('','MOVE',{edge:n.row[0]},true)"));assert(app.includes('목적지 카드를 누르면 바로 이동합니다.'));assert(app.includes('this.choose(n.id)'));return{cards:'direct',pins:'preview'};});
const report={version:'0.13.23',total:results.length,passed:results.filter(x=>x.ok).length,results};console.log(JSON.stringify({total:report.total,passed:report.passed}));if(report.total!==report.passed)process.exitCode=1;
