'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const h=require('../tests/helpers_v011.cjs'),{R,db,c}=h;let passed=0;
function test(name,fn){try{const e=fn()||{};passed++;console.log('PASS '+name+' '+JSON.stringify(e));}catch(err){console.error('FAIL '+name+'\n'+err.stack);process.exitCode=1;}}
function fresh(route='ROUTE_ISEKAI'){const r=new R(db);r.newGame({name:'12-2DEF',route,seed:1231,saveId:'STEP12DEF-'+route});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',SCREEN_MODE:'LOCATION',STORY_MENU_POLICY:'',WORLD_TIME:'12:00',MORA:999999,PLAYER_BASE_HP:100000});delete r.s.storyContext;try{r.prepareStory();}catch{}r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;return r;}
test('inn rest heals fully, advances eight hours, and returns to town screen',()=>{const r=fresh(),stock=r.rows('19_SHOP_STOCK_DB').find(x=>x[2]==='SERVICE'&&x[3]==='SERVICE_INN_REST_8H');assert(stock,'inn stock');const merchant=stock[1],schedule=r.rows('51_EVENT_DB').map(x=>{try{return JSON.parse(x[13]||'{}')}catch{return null}}).find(x=>x?.merchant_id===merchant);assert(schedule?.map_ids?.length,'inn schedule');r.s.global.CURRENT_MAP_ID=schedule.map_ids[0];const mins=schedule.from_minute??0;r.s.global.WORLD_TIME=String(Math.floor(mins/60)%24).padStart(2,'0')+':'+String(mins%60).padStart(2,'0');r.s.global.PLAYER_HP_CURRENT=1;const entry=r.placeCatalog().find(e=>e.merchant===merchant&&e.maps.includes(r.s.global.CURRENT_MAP_ID));assert(entry,'inn place');r.action('PLACE_ENTER',{place:entry.id,mode:'SHOP'});const before=(r.s.global.WORLD_DAY-1)*1440+Number(r.s.global.WORLD_TIME.slice(0,2))*60+Number(r.s.global.WORLD_TIME.slice(3));const out=r.action('BUY',{stock:stock[0],quantity:1}).result,after=(r.s.global.WORLD_DAY-1)*1440+Number(r.s.global.WORLD_TIME.slice(0,2))*60+Number(r.s.global.WORLD_TIME.slice(3));assert.equal(out.service,'INN_REST');assert.equal(out.recovered,true);assert.equal(after-before,480);assert.equal(r.s.global.PLAYER_HP_CURRENT,r.s.global.PLAYER_HP_MAX);assert.equal(r.s.placeVisit,null);assert.equal(r.s.global.SCREEN_MODE,'LOCATION');return{merchant,minutes:out.minutes};});
test('UI has progress overlays for rest crafting and all enhancement actions',()=>{const src=fs.readFileSync(path.join(h.root,'source/app_adventure.js'),'utf8'),av=fs.readFileSync(path.join(h.root,'source/app_av.js'),'utf8');for(const x of ["task-progress-overlay","type==='CRAFT'","'ENHANCE','EQUIP_ASCEND','ARTIFACT_ENHANCE'","result.service==='INN_REST'","파티 HP가 모두 회복되었습니다.", "game.s.global.PLAYER_NAME+' 경험치 획득 +'"])assert(src.includes(x),x);assert(av.includes('playTravel(adventureBefore,type,params)'));return{};});
test('Mond combat XP uses the authored 45 percent pass while quest/book economy is untouched',()=>{const r=fresh();r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';const group=r.mondAreaThreat().entries[0].group;r.startBattle(group,'RANDOM');const parts=r.s.runtime.mondBalance.rewards.parts,raw=r.s.runtime.mondBalance.rewards.xp;for(const part of parts){const mult={일반:1,정예:2,강적:4}[part.grade]||1;assert.equal(part.xp,Math.round((30+15*part.level)*mult*.45));}for(const a of r.s.runtime.actors.filter(x=>x.side==='ENEMY'))a.hp=0;const out=r.finishBattle(true);assert.equal(out.xp,raw);assert(raw>0);const book=r.row('14_ITEM_DB','MAT_CHAR_EXP_WANDERER');assert.match(String(book[7])+' '+String(book[8]),/XP \+50/);const qrow=r.row('22_QUEST_DB','Q_MOND_XP_SUPPLY'),qdef=JSON.parse(qrow[10]),q=JSON.parse(qrow[11]);assert.equal(qdef.conditions.min_level,1);assert.equal(q.items.MAT_CHAR_EXP_ADVENTURER,1);assert.equal(q.items.MAT_CHAR_EXP_WANDERER,2);return{raw,combatXp:out.xp,starterSupplyLevel:qdef.conditions.min_level};});
test('generic Liyue combat XP is also reduced to 40 percent',()=>{const r=fresh();r.s.global.CURRENT_MAP_ID='MAP_LIYUE_PLAINS';const group=r.rows('34_MAP_ENCOUNTER_POOL').find(x=>x[1]==='MAP_LIYUE_PLAINS')[5];r.startBattle(group,'RANDOM');const raw=r.s.runtime.actors.filter(x=>x.side==='ENEMY').reduce((n,a)=>{const m=r.row('09_MONSTER_DB',a.source),mult={일반:1,정예:3,강적:6,보스:12}[m[3]]||1;return n+Math.round((30+15*a.level)*mult);},0);for(const a of r.s.runtime.actors.filter(x=>x.side==='ENEMY'))a.hp=0;const out=r.finishBattle(true);assert.equal(out.xp,Math.max(1,Math.round(raw*.4)));return{raw,combatXp:out.xp};});
test('Liyue shop exposes five weapon classes plus five armor and five accessory choices',()=>{const r=fresh(),stocks=r.rows('19_SHOP_STOCK_DB').filter(x=>x[1]==='MRC_LIYUE_EQUIP'&&x[2]==='EQUIP'),rows=stocks.map(x=>r.row('16_EQUIP_DB',x[3])),types=Object.fromEntries(['한손검','양손검','장병기','활','법구','방어구','장신구'].map(t=>[t,rows.filter(e=>e[2]===t).length]));for(const t of ['한손검','양손검','장병기','활','법구'])assert(types[t]>=1,t);assert.equal(types['방어구'],5);assert.equal(types['장신구'],5);assert.equal(stocks.length,15);return{stocks:stocks.length,types};});
test('new Liyue armor/accessories have distinct roles, icons, and shared enhancement',()=>{const r=fresh(),cfg=c.CRPGRuntime.liyueEntryEquipment;assert.equal(cfg.gear.length,8);const roles=new Set(cfg.gear.map(x=>x.role));assert(roles.size>=7);const app=fs.readFileSync(path.join(h.root,'source/app_liyue_equipment.js'),'utf8'),paths=[...app.matchAll(/assets\/icons\/([^']+\.webp)/g)].map(x=>x[1]);assert.equal(paths.length,8);assert.equal(new Set(paths).size,8);for(const p of paths)assert(fs.existsSync(path.join(h.root,'assets/icons',p)),p);for(const g of cfg.gear){const row=r.row('16_EQUIP_DB',g.id);assert.equal(row[33],'Y',g.id);const slot=r.giveEquipment(g.id),q=r.enhancementQuote(slot);assert.equal(q.supported,true,g.id);assert.equal(q.target,1,g.id);}return{gear:cfg.gear.length,roles:[...roles],uniqueIcons:new Set(paths).size};});
test('new modules are wired before enhancement and before item presenter creation',()=>{const html=fs.readFileSync(path.join(h.root,'source/index.html'),'utf8'),build=fs.readFileSync(path.join(h.root,'tools/build.py'),'utf8');assert(html.indexOf('runtime_liyue_equipment.js')>html.indexOf('runtime_equipment.js'));assert(html.indexOf('runtime_liyue_equipment.js')<html.indexOf('runtime_enhancement.js'));assert(html.indexOf('app_liyue_equipment.js')>html.indexOf('inventory_presenter.js'));assert(html.indexOf('app_liyue_equipment.js')<html.indexOf('app_experience.js'));assert(build.includes("'runtime_liyue_equipment.js'")&&build.includes("'app_liyue_equipment.js'"));return{};});
console.log(JSON.stringify({total:7,passed}));if(passed!==7)process.exitCode=1;
