'use strict';
// Native engine regression tests for operator profiles, not a combat difficulty simulation.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),h=require('./audit_protagonist_v01618.cjs'),copy=x=>JSON.parse(JSON.stringify(x));let checks=0;
function load(include){const FixedDate=class extends Date{constructor(...a){super(...(a.length?a:[1791615600000]));}static now(){return 1791615600000;}};const c=vm.createContext({console,Date:FixedDate,setTimeout,clearTimeout}),html=fs.readFileSync(path.join(ROOT,'source/index.html'),'utf8');for(const[,f]of html.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)){if(!include&&f==='runtime_balance_admin_v01623.js')continue;vm.runInContext(fs.readFileSync(path.join(ROOT,'source',f),'utf8'),c,{filename:f});}vm.runInContext(fs.readFileSync(path.join(ROOT,'source/presentation.js'),'utf8'),c);return{c,db:JSON.parse(fs.readFileSync(path.join(ROOT,'content/db.json'))),R:c.CRPGRuntime.Runtime,api:c.CRPGRuntime,root:ROOT};}
function same(a,b,label){assert.deepEqual(copy(a),copy(b),label);checks++;}function ok(v,label){assert.ok(v,label);checks++;}
const base=load(false),env=load(true),A=env.api.adminBalance,catalog=A.catalog(new env.R({...env.db})),initialHash=crypto.createHash('sha256').update(JSON.stringify(env.db)).digest('hex');
// A configurable packet must retain its originating card; untagged follow-ups are excluded from the API too.
for(const id of ['LIYUE_BEIDOU_Q','LIYUE_XINGQIU_Q','LIYUE_XIANYUN_E','LIYUE_XIANYUN_Q','LIYUE_YELAN_Q','LIYUE_YUNJIN_Q','ECARD_CICIN_ELECTRO_SUMMON']){
 ok(!catalog.cards.find(c=>c.id===id)?.fields.some(f=>f.key==='damageMultiplier'),'untagged damage control omitted: '+id);
 assert.throws(()=>A.validateConfig({cards:{[id]:{damageMultiplier:2}}},catalog));checks++;
}
same(A.validateConfig({cards:{LIYUE_XIANYUN_Q:{healingMultiplier:2}}},catalog).cards.LIYUE_XIANYUN_Q,{healingMultiplier:2},'Xianyun Q implemented healing stays editable');
for(const id of ['LIYUE_XIANGLING_E','LIYUE_QIQI_E','MOND_MONA_Q','LIYUE_HUTAO_E'])same(A.validateConfig({cards:{[id]:{damageMultiplier:2}}},catalog).cards[id],{damageMultiplier:2},'tagged field or delayed damage remains editable: '+id);
const options={name:'동일 기본값',route:'ROUTE_TRAVELER',seed:717,saveId:'ADMIN-BALANCE-IDENTITY'};
const plain=new base.R({...base.db}),identity=A.createRuntime(env.db,null,{revision:0,config:A.emptyConfig()});same(plain.newGame(options),identity.newGame(options),'empty profile new game identity');
const spec={level:20,team:['LIYUE_XIANGLING','MOND_KAEYA','MOND_BARBARA'],route:'ROUTE_TRAVELER',seed:717,gear:'craft',enhance:3};
const old=h.setup(base,spec),current=h.setup(env,spec);same(old.s,current.s,'fixture identity');
old.startBattle('EG_MOND_SLIME_SMALL','RANDOM');current.startBattle('EG_MOND_SLIME_SMALL','RANDOM');const annotated=copy(current.s);delete annotated.runtime.adminBalanceRevision;same(old.s,annotated,'empty profile battle order RNG HP identity');same(h.play(old),h.play(current),'empty profile battle result');
const seed=h.setup(env,spec),save=copy(seed.s),conf=A.emptyConfig();conf.enemies.MON_SLIME_PYRO={level:20,hp:12345,atk:222,def:111,spd:90,hit:95,eva:9,resist:17};conf.characters.MOND_BARBARA={hpMultiplier:2,atkMultiplier:1.5,defMultiplier:.5};conf.tables=[{table:'14_ITEM_DB',id:'FOOD_SWEET_MADAME',column:8,value:555},{table:'16_EQUIP_DB',id:'EQ_SWORD_COOL_STEEL',column:4,value:333},{table:'17_RECIPE_DB',id:'REC_FOOD_SWEET_MADAME',column:15,value:99}];
// Recipes differ across authored/local catalogs; select an actual current recipe for the tested food.
const recipe=seed.rows('17_RECIPE_DB').find(x=>x[3]==='FOOD_SWEET_MADAME'&&!/레거시/.test(x[18]||''));conf.tables[2].id=recipe[0];conf.economy={innMultiplier:2,craftMoraMultiplier:2,ascensionMoraMultiplier:2,talentMoraMultiplier:2,rewardXpMultiplier:2,rewardMoraMultiplier:3};conf.encounters.EG_MOND_SLIME_SMALL=[{monster:'MON_SLIME_PYRO',min:2,max:2}];
const tuned=A.createRuntime(env.db,save,{revision:3,config:conf}),unchanged=A.createRuntime(env.db,save,{revision:0,config:A.emptyConfig()});same(tuned.s.chars.MOND_BARBARA.hp,save.chars.MOND_BARBARA.hp,'larger maximum does not heal');same(tuned.character('MOND_BARBARA').maxHp,Math.round(seed.character('MOND_BARBARA').maxHp*2),'character HP multiplier');same(tuned.character('MOND_BARBARA').atk,Math.round(seed.character('MOND_BARBARA').atk*1.5),'character ATK multiplier');same(tuned.row('14_ITEM_DB','FOOD_SWEET_MADAME')[8],555,'installed food override');same(tuned.row('16_EQUIP_DB','EQ_SWORD_COOL_STEEL')[4],333,'equipment override');same(tuned.recipeDefinition(recipe[0])[15],198,'hardcoded cooking cost override and shared multiplier');same(unchanged.row('14_ITEM_DB','FOOD_SWEET_MADAME')[8],seed.row('14_ITEM_DB','FOOD_SWEET_MADAME')[8],'profile isolation');
tuned.startBattle('EG_MOND_SLIME_SMALL','RANDOM');same(tuned.s.runtime.adminBalanceRevision,3,'battle profile binding');same(tuned.s.runtime.actors.filter(x=>x.side==='ENEMY').length,2,'encounter replacement');for(const enemy of tuned.s.runtime.actors.filter(x=>x.side==='ENEMY'))same([enemy.level,enemy.maxHp,enemy.atk,enemy.def,enemy.spd,enemy.hit,enemy.eva,enemy.resist],[20,12345,222,111,90,95,9,17],'final enemy overrides');
const reloaded=A.createRuntime(env.db,tuned.s,{revision:3,config:conf});same(reloaded.s.runtime,tuned.s.runtime,'active battle reload preserves existing effects and order');assert.throws(()=>A.createRuntime(env.db,tuned.s,{revision:0,config:A.emptyConfig()}),/버전/);checks++;
const inn=seed.rows('19_SHOP_STOCK_DB').find(x=>x[3]==='SERVICE_INN_REST_8H');const quote0=seed.innRecoveryQuote(inn),quote3=reloaded.innRecoveryQuote(reloaded.row('19_SHOP_STOCK_DB',inn[0]));same(quote3.cost,Math.ceil(Math.ceil(20*quote3.regionalRate)*2)+quote3.targets.reduce((n,x)=>n+Math.ceil(Math.ceil(4*x.level*(x.maxHp-Math.max(0,x.hp))/x.maxHp*quote3.regionalRate)*2),0),'inn quote scales per target');
// Effects use a real battle actor and real effect executors; action eligibility is not asserted here.
const effects=A.emptyConfig();effects.cards={MOND_BARBARA_E:{healingMultiplier:2},MOND_BARBARA_Q:{healingMultiplier:2},MOND_JEAN_Q:{healingMultiplier:2},LIYUE_QIQI_Q:{healingMultiplier:2},LIYUE_ZHONGLI_E:{shieldMultiplier:2},LIYUE_XIANGLING_E:{damageMultiplier:2}};
const fieldBaseline=h.setup(env,spec);for(const id of ['FB_ANEMO_HYPOSTASIS','FB_ELECTRO_HYPOSTASIS','FB_CRYO_REGISVINE']){fieldBaseline.startBattle(env.api.fieldBosses.group(id),'BOSS:'+env.api.fieldBosses.route(id));const a=fieldBaseline.s.runtime.actors.find(x=>x.source===id),entry=catalog.enemies.find(x=>x.id===id),values=Object.fromEntries(entry.fields.map(x=>[x.key,x.base]));same([values.level,values.hp,values.atk,values.def],[a.level,a.maxHp,a.atk,a.def],'field boss catalog equals actual repeat-challenge native stat including authored floor');fieldBaseline.s.runtime=null;fieldBaseline.s.global.MODE='NORMAL';fieldBaseline.s.global.ACTIVE_BATTLE_ID='';}
const e=A.createRuntime(env.db,save,{revision:4,config:effects});e.startBattle('EG_MOND_SLIME_SMALL','RANDOM');const b=e.s.runtime,bar=b.actors.find(x=>x.source==='MOND_BARBARA');e.executeCard(bar,e.cardDefinition(e.row('08_SKILL_CARD_DB','MOND_BARBARA_E')),bar.id);const melody=bar.statuses.find(x=>x.id==='STATUS_BARBARA_MELODY_LOOP'),budget=e.combatHealingBudget();same(melody.healRatio,budget.barbaraERatio*2,'Barbara persistent heal ratio');same(melody.healFlat,budget.barbaraEFlat*2,'Barbara persistent flat heal');
const jean=e.character('MOND_JEAN');jean.id='MOND_JEAN';jean.statuses=[];jean.shields=[];b.actors.push(jean);const field=e.addField('DANDELION',jean,2,{sourceCardId:'MOND_JEAN_Q',healTargetCount:1});same(field.healRatio,budget.jeanFieldRatio*2,'Jean field heal ratio');same(field.healFlat,budget.jeanFieldFlat*2,'Jean field flat heal');e.addField('DANDELION',jean,2,{sourceCardId:'MOND_JEAN_Q',healTargetCount:1});const refreshed=b.fields.find(x=>x.kind==='DANDELION');same(refreshed.healRatio,budget.jeanFieldRatio*2,'refreshed live field applies multiplier once');same(refreshed.healFlat,budget.jeanFieldFlat*2,'refreshed live field preserves scaled flat');
e._adminBalanceCard={actor:'LIYUE_QIQI',card:'LIYUE_QIQI_Q'};const talisman=e.addCombatStatus(b.actors.find(x=>x.side==='ENEMY'),'FORTUNE_TALISMAN',2,{healRatio:.1,healFlat:295,actor:'LIYUE_QIQI'});delete e._adminBalanceCard;same(talisman.healRatio,.2,'Qiqi derivative heal ratio');same(talisman.healFlat,590,'Qiqi derivative flat heal');
const pulseTarget=b.actors.find(x=>x.side==='ALLY');pulseTarget.hp=1;const pulseBefore=pulseTarget.hp;e.tickFields('END');const pulseHeals=b.log.filter(x=>x.target===pulseTarget.name&&x.heal>0);ok(pulseTarget.hp>pulseBefore&&pulseHeals.length>0,'real field pulse applies recovery');
bar.shields=[];e.shield(bar,100,'LIYUE_ZHONGLI_E',2,{initialValue:100});const jade=bar.shields.find(x=>x.source==='LIYUE_ZHONGLI_E');same(jade.value,143,'shield multiplier reaches final formation and gear absorption');same(jade.initialValue,200,'shield initialValue scales with same profile');
const zeroEffects=A.createRuntime(env.db,save,{revision:0,config:A.emptyConfig()});zeroEffects.startBattle('EG_MOND_SLIME_SMALL','RANDOM');function hitOnce(r){const a=r.s.runtime.actors.find(x=>x.source==='LIYUE_XIANGLING'),t=r.s.runtime.actors.find(x=>x.side==='ENEMY');a.crit=0;a.hit=100;t.hp=t.maxHp=1000000;t.eva=0;t.aura=null;t.auras=[];r.s.global.PRNG_STATE=717;const before=t.hp;r.damage(a,t,.5,'PHYSICAL',{card:'LIYUE_XIANGLING_E',sureHit:true,noAura:true});return before-t.hp;}const d0=hitOnce(zeroEffects),d2=hitOnce(e);ok(Math.abs(d2-2*d0)<=2,'damage multiplier reaches final native damage once');
const s0=copy(save),smaller=A.emptyConfig();smaller.characters.MOND_BARBARA={hpMultiplier:.1};const small=A.createRuntime(env.db,s0,{revision:5,config:smaller});ok(small.s.chars.MOND_BARBARA.hp<=small.character('MOND_BARBARA').maxHp,'lower maximum clamps HP');
const gc=A.emptyConfig();gc.growth={domains:{'TAISHAN_MANSION:30':{materialQuantity:11,xp:999},'MIDSUMMER_COURTYARD:10':{xp:123}},ascension:{'1':42},talents:{MOND:{'1':7},LIYUE:{'1':9}}};gc.economy.rewardXpMultiplier=2;
const gr=A.createRuntime(env.db,save,{revision:6,config:gc}),site=env.api.growthV01522.domains.TAISHAN_MANSION,entry=gr.growthDomainEntries(site.map).find(x=>x.id==='TAISHAN_MANSION:30'),day=env.api.growthV01522.dayOf(gr.leyLineNow());gr.s.domainDaily={day,wins:0};let reward=gr.growthDomainRewards(entry,'NEUTRAL');same(reward.items.GROWTH_TALENT_LIYUE,22,'current entrance reward uses first-three double');same(reward.xp,1998,'current entrance XP includes stage and global factor once');gr.s.domainDaily.wins=3;reward=gr.growthDomainRewards(entry,'NEUTRAL');same(reward.items.GROWTH_TALENT_LIYUE,11,'current entrance after daily bonus');const legacy=gr.growthDomainRewards({...entry,version:3},'NEUTRAL');ok(legacy.items.GROWTH_TALENT_LIYUE!==11,'explicit legacy stage bypasses new overrides');const expEntry=gr.growthDomainEntries(env.api.growthV01522.domains.MIDSUMMER_COURTYARD.map).find(x=>x.id==='MIDSUMMER_COURTYARD:10'),expReward=gr.growthDomainRewards(expEntry);same(expReward.items,{},'EXP stage never adds books');same(expReward.xp,246,'EXP stage configurable XP matches global factor');
const asc=gr.ascensionInfo('PLAYER_CUSTOM'),gem=Object.keys(asc.cost.items).find(x=>x.startsWith('GROWTH_GEM_'));same(asc.cost.items[gem],42,'common ascension requirement');for(const[id,n]of Object.entries(asc.cost.items))gr.giveItem(id,id===gem?n-1:n);same(gr.ascensionInfo('PLAYER_CUSTOM').reason,'돌파 재료가 부족합니다.','new required gem shortage reported');gr.giveItem(gem,1);same(gr.ascensionInfo('PLAYER_CUSTOM').reason,'','material shortage clears after actual inventory reaches new cost');gr.s.chars.MOND_JEAN.level=20;gr.s.ascensions.MOND_JEAN=1;const five=gr.ascensionInfo('MOND_JEAN');same(Object.entries(five.cost.items).find(([id])=>id.startsWith('GROWTH_GEM_'))[1],84,'five-star gem requirement retains twice common cost');ok(!!five.reason,'unowned character ownership restriction remains');
same(gr.talentUpgradeInfo('MOND_BARBARA','na').cost.items.GROWTH_TALENT_MOND,7,'MOND talent book requirement');same(gr.talentUpgradeInfo('LIYUE_XIANGLING','e').cost.items.GROWTH_TALENT_LIYUE,9,'LIYUE talent book requirement');
const strong=h.setup(env,{level:30,team:['LIYUE_XIANGLING','LIYUE_XINGQIU','MOND_BENNETT'],route:'ROUTE_TRAVELER',seed:717,enhance:10}),native=A.createRuntime(env.db,strong.s,{revision:6,config:gc});native.s.global.CURRENT_MAP_ID=site.map;const bookBefore=native.itemCount('GROWTH_TALENT_LIYUE');native.action('DOMAIN_START',{domain:'TAISHAN_MANSION:30'});const plan=native.mondRewardPlan(native.s.runtime);same(plan.xp,1998,'actual domain reward plan stage XP and global factor');same(plan.parts.reduce((n,x)=>n+x.xp,0),1998,'actual domain reward parts agree with total');const result=h.play(native);ok(result.victory,'native public domain completion');same(result.xp,1998,'native settlement XP equals preview');same(native.itemCount('GROWTH_TALENT_LIYUE')-bookBefore,11,'native settlement material quantity equals preview after bonus');
const missingGrowth=copy(A.emptyConfig());delete missingGrowth.growth;const oldShape=A.createRuntime(env.db,save,{revision:0,config:missingGrowth});same(A.profileOf(oldShape).revision,0,'old identity profile without growth uses same canonical cache key');
const invalid=[{cards:{MOND_BARBARA_E:{script:'BAD'}}},{enemies:{MON_SLIME_PYRO:{hp:0}}},{tables:[{table:'08_SKILL_CARD_DB',id:'MOND_BARBARA_E',column:32,value:'BAD'}]},{encounters:{EG_MOND_SLIME_SMALL:[{monster:'MON_SLIME_PYRO',min:1,max:8},{monster:'MON_SLIME_ANEMO',min:1,max:1}]}},{encounters:{FAKE:[{monster:'MON_SLIME_PYRO',min:1,max:1}]}},{economy:{rewardMoraMultiplier:Infinity}},{growth:{domains:{'MIDSUMMER_COURTYARD:10':{materialQuantity:999}}}},{growth:{ascension:{'6':1}}}];for(const bad of invalid){assert.throws(()=>A.validateConfig(bad,catalog));checks++;}
same(crypto.createHash('sha256').update(JSON.stringify(env.db)).digest('hex'),initialHash,'authored shared DB untouched');console.log(JSON.stringify({ok:true,checks,catalog:{enemies:catalog.enemies.length,characters:catalog.characters.length,cards:catalog.cards.length},limits:'Operator application tests only; not an exhaustive combat balance claim.'}));
