'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'), db=JSON.parse(fs.readFileSync(root+'/content/db.json'));
for(const f of ['runtime.js','runtime_extensions.js','runtime_story.js','runtime_nodes.js','runtime_events.js','runtime_relationships.js','runtime_combat.js','runtime_mond_cards.js','runtime_economy.js','runtime_passives.js','save_adapter.js']) require(root+'/source/'+f);
const Runtime=CRPGRuntime.Runtime, report={checks:[],traces:{}};
function check(name,fn){fn();report.checks.push({name,passed:true});}
function create(route='ROUTE_ISEKAI',knowledge='KNOWN') { const r=new Runtime(db);r.newGame({name:'개정 검증',route,seed:812,saveId:'rev01-test'});r.s.flags.FLAG_ISK_META_KNOWLEDGE=knowledge;r.s.global.ACTIVE_STORY_QUEST='Q_ISK_MOND_02';return r; }
function jump(r,id,map='MAP_MOND_TEMPLE_FALCON'){r.s.global.PENDING_CHOICE_GROUP_ID='';r.s.global.CURRENT_MAP_ID=map;r.storySetCursor(id);r.prepareStory();}
function run(r,stop,pick,limit=80) {let seen=[];for(let n=0;n<limit;n++){let id=r.storyActiveNodeId();if(id===stop)return seen; const choices=r.storyChoices();if(choices.length){let chosen=pick?.(choices)||choices[0];assert(chosen);seen.push(chosen[4]);r.action('STORY_CHOICE',{node:chosen[4]});}else{const row=r.storyNode();assert(row,'missing '+id);seen.push(row[4]);r.action('STORY_NEXT',{node:row[4]});}}throw Error('Traversal exceeded limit at '+r.storyActiveNodeId());}
const flag='FLAG_ISK_K_TEMPLE_EXIT';
for(const [num,value,callback] of [[1,'COUNTERWEIGHT','OBSERVE'],[2,'SIGNAL','SIGNAL'],[3,'FORCE_RESCUED','FORCE']]){
 check('temple branch '+value+' reaches original merge and persists exactly its choice',()=>{let r=create();jump(r,'ISK_M02_K_SEARCH_01');const before={hp:r.s.global.PLAYER_HP_CURRENT,mora:r.s.global.MORA,party:JSON.stringify(r.s.party)};let trace=run(r,'ISK_M02_K_SEARCH_02',cs=>cs.find(c=>c[4]==='REV01_ISK_K_GATE_C'+num));assert.equal(r.s.flags[flag],value);assert.equal(r.s.global.PLAYER_HP_CURRENT,before.hp);assert.equal(r.s.global.MORA,before.mora);assert.equal(JSON.stringify(r.s.party),before.party);assert.equal(trace.filter(x=>/^REV01_ISK_K_GATE_C\d$/.test(x)).length,1);assert(trace.includes('REV01_ISK_K_GATE_MERGE'));r=new Runtime(db,JSON.parse(r.serialize()));jump(r,'ISK_M02_K_CITY_END_02','MAP_MOND_CITY');let recalled=run(r,'ISK_M02_K_CITY_END_03');assert.deepEqual(recalled.filter(x=>x.startsWith('REV01_ISK_K_CALLBACK_')),['REV01_ISK_K_CALLBACK_'+callback]);report.traces[value]={temple:trace,return:recalled};});
}
for(const id of ['ISK_M02_K_IDENTITY_C1','ISK_M02_K_IDENTITY_C2'])for(const alternate of [false,true]){
 check('identity '+id+' '+(alternate?'new reply':'existing reply'),()=>{let r=create();jump(r,'CHOICE_GROUP:ISK_M02_G_K_IDENTITY','MAP_MOND_CITY');let trace=run(r,'ISK_M02_K_SECRET_01',cs=>cs.find(c=>c[4]===id)||cs.find(c=>alternate?c[4].endsWith('_ALT'):c[4].endsWith('_SAY')));assert.equal(r.s.flags.FLAG_ISK_VENTI_TOLD_JEAN,true);assert.equal(trace.filter(x=>/_SECRET_(PLAIN|CAREFUL)$/.test(x)).length,1);assert(!JSON.stringify(trace).includes('AMBER'));report.traces[id+'-'+alternate]=trace;});
}
for(const value of [undefined,'UNSET'])check('old save with '+String(value)+' skips all new flashbacks',()=>{let r=create();if(value===undefined)delete r.s.flags[flag];else r.s.flags[flag]=value;jump(r,'ISK_M02_K_CITY_END_02','MAP_MOND_CITY');assert.deepEqual(run(r,'ISK_M02_K_CITY_END_03'),['ISK_M02_K_CITY_END_02']);});
for(const [route,knowledge] of [['ROUTE_ISEKAI','UNKNOWN'],['ROUTE_TRAVELER','KNOWN']])check('new choices hidden for '+route+'/'+knowledge,()=>{let r=create(route,knowledge);jump(r,'CHOICE_GROUP:REV01_ISK_K_GATE_CHOICE');assert.equal(r.storyChoices().length,0);});
check('save at pending new choice roundtrips and resolves without duplicating selection',()=>{let r=create();jump(r,'CHOICE_GROUP:REV01_ISK_K_GATE_CHOICE');const state=JSON.parse(r.serialize());r=new Runtime(db,state);r.prepareStory();assert.equal(r.storyChoices().length,3);r.action('STORY_CHOICE',{node:'REV01_ISK_K_GATE_C1'});assert.equal(r.s.flags[flag],'COUNTERWEIGHT');assert.throws(()=>r.action('STORY_CHOICE',{node:'REV01_ISK_K_GATE_C2'}));assert.equal(r.s.flags[flag],'COUNTERWEIGHT');});
check('every new next reference exists in same route and maximum three new choices',()=>{const rows=db['55_MAIN_STORY_DB'].slice(1),keys=new Set(rows.map(r=>r[0]+':'+r[4]));for(const r of rows.filter(r=>String(r[4]).startsWith('REV01_'))){const next=r[13];if(next.startsWith('CHOICE_GROUP:')){const group=rows.filter(x=>x[0]===r[0]&&x[5]==='CHOICE'&&x[14]===next.slice(13));assert(group.length>=2&&group.length<=3);}else assert(keys.has(r[0]+':'+next),next);assert(r[11].includes('FLAG_ISK_META_KNOWLEDGE=KNOWN'));}});
const previous=JSON.parse(fs.readFileSync(root+'/content/story-revisions/rev01-base-save-compatibility.json'));
const current=JSON.parse(fs.readFileSync(root+'/dist/asset-manifest.json'));
check('old v0.13.15 save-version and its supported ancestors retained',()=>{for(const v of [previous.saveCompatibilityVersion,...previous.compatibleSaveVersions])assert(current.compatibleSaveVersions.includes(v));});
check('v0.13.15-format save imports through actual SaveAdapter and retains story cursor',()=>{const r=create();jump(r,'ISK_M02_K_CITY_END_02','MAP_MOND_CITY');delete r.s.flags[flag];const raw={envelopeSchema:1,runtimeSchema:2,contentVersion:previous.saveCompatibilityVersion,state:JSON.parse(r.serialize())};const adapter=new CRPGSave.SaveAdapter({contentVersion:current.saveCompatibilityVersion,compatibleContentVersions:current.compatibleSaveVersions});try{const out=adapter.parseImport(JSON.stringify(raw));assert.equal(out.state.global.STORY_CURSOR_NODE_ID,raw.state.global.STORY_CURSOR_NODE_ID);const loaded=new Runtime(db,out.state);loaded.prepareStory();assert.deepEqual(run(loaded,'ISK_M02_K_CITY_END_03'),['ISK_M02_K_CITY_END_02']);}finally{adapter.close();}});
report.total=report.checks.length;report.passed=report.checks.filter(x=>x.passed).length;fs.mkdirSync(root+'/reports/story_rev01',{recursive:true});fs.writeFileSync(root+'/reports/story_rev01/runtime-tests.json',JSON.stringify(report,null,2));console.log(JSON.stringify({checks:report.total,passed:report.passed}));
