'use strict';
// Native ownership contracts; controlled wounds/rolls isolate support arithmetic, not boss difficulty.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),H=require('../tools/audit_protagonist_v01618.cjs'),env=H.load(ROOT),cp=x=>JSON.parse(JSON.stringify(x));
const watched=[...fs.readFileSync(ROOT+'/source/index.html','utf8').matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)].map(m=>'source/'+m[1]);watched.push('source/index.html','content/db.json');
const hashes=()=>Object.fromEntries(watched.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(ROOT+'/'+f)).digest('hex')])),before=hashes();
const output=process.argv[2]||ROOT+'/reports/skill_rhythm_ownership_v01625/runtime-tests.json',report={scope:'Actual native card/field/talisman effects and deterministic ownership arithmetic. Wound/roll fixtures do not prove battle difficulty. New characterBalanceRevision=1; unmarked saves retain original support scope.',fingerprint:env.fingerprint,checks:[]};
function test(name,fn){try{report.checks.push({name,passed:true,evidence:fn()??null});console.log('PASS '+name);}catch(e){report.checks.push({name,passed:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function fixture(team=['LIYUE_XIANYUN','LIYUE_BAIZHU','MOND_AMBER'],modern=true,profile=null,cons=0){let r=H.setup(env,{level:25,team,route:'ROUTE_TRAVELER',gear:'none',talent:10});if(cons){r.giveItem('STELLA_LIYUE_ZHONGLI',cons);for(let n=0;n<cons;n++)r.action('CONSTELLATION_UNLOCK',{char:'LIYUE_ZHONGLI'});}if(profile)r=env.api.adminBalance.createRuntime(env.db,r.s,profile);r.startBattle('EG_MOND_HILI_PATROL','RANDOM');const b=r.s.runtime;if(!modern)delete b.characterBalanceRevision;assert.equal(b.characterBalanceRevision,modern?1:undefined);b.fields=[];b.log=[];b.round=1;b.terrain=null;b.actionSequence=1;for(const a of b.actors){a.statuses=[];a.shields=[];a.cooldowns={};a.traits={};a.traitState={};a.hp=a.side==='ALLY'?1:10000000;a.auras=[];a.aura=null;a.nativeAura=null;if(a.side==='ENEMY'){a.maxHp=10000000;a.eva=0;}else{a.hit=100;a.crit=0;}}r.die=()=>50;r.random=()=>.5;const heals=[],old=r.heal;r.heal=function(t,n,source,...rest){const out=old.call(this,t,n,source,...rest);heals.push({actor:t.source,source,sourceActorId:rest[0],meta:cp(rest[1]||null),requested:n,applied:out,rhythm:cp(this._rhythm||null),consCast:this._consCast?.card});return out;};return{r,b,heals,enemy:b.actors.find(a=>a.side==='ENEMY'),actor:id=>b.actors.find(a=>a.source===id)};}
function cast(f,owner,id){const a=f.actor(owner),c=f.r.actorCards(a).find(c=>c.id===id);assert(c,id);assert.equal(f.r.cardSupport(c),'');f.r.executeCard(a,c,f.enemy.id);return c;}
function resetWounds(f){for(const a of f.b.actors.filter(a=>a.side==='ALLY'))a.hp=1;f.heals.length=0;f.b.round++;f.b.actionSequence++;}
function persistent(f,kind){return f.heals.filter(h=>h.meta?.sourceKind===kind);}
for(const modern of [true,false])test((modern?'new':'unmarked')+' cross-caster Xianyun field during Baizhu E uses correct rhythm',()=>{const f=fixture(undefined,modern);cast(f,'LIYUE_XIANYUN','LIYUE_XIANYUN_Q');resetWounds(f);cast(f,'LIYUE_BAIZHU','LIYUE_BAIZHU_E');const h=f.heals.find(h=>h.source===f.actor('LIYUE_XIANYUN').name);assert(h);assert.equal(h.applied,Math.round(h.requested*(modern?1:1.3)));if(modern){assert.equal(h.sourceActorId,f.actor('LIYUE_XIANYUN').id);assert.equal(h.meta.sourceCardId,'LIYUE_XIANYUN_Q');}else{assert.equal(h.sourceActorId,undefined);assert.equal(h.meta,null);}return h;});
for(const modern of [true,false])test((modern?'new':'unmarked')+' own Baizhu E keeps revision HP ratio and talent/slow-skill support once',()=>{const f=fixture(undefined,modern),a=f.actor('LIYUE_BAIZHU'),budget=env.api.characterBalanceV01625,ratio=f.r.combatBaizhuHealingRatio();assert.equal(ratio,modern?.03:.08);assert.equal(ratio,modern?budget.baizhuERatio:budget.legacyBaizhuERatio);cast(f,'LIYUE_BAIZHU','LIYUE_BAIZHU_E');const h=f.heals.filter(h=>h.source===a.name);assert.equal(h.length,4);const factor=f.r.premiumTalentMultiplier(a,'e')*1.3;for(const row of h){assert.equal(row.requested,a.maxHp*ratio);assert.equal(row.applied,Math.round(row.requested*factor));}return{maxHp:a.maxHp,ratio,factor,heals:h};});
for(const modern of [true,false])test((modern?'new':'unmarked')+' Xianyun own normal attack triggers persistent field with declared attribution',()=>{const f=fixture(undefined,modern);cast(f,'LIYUE_XIANYUN','LIYUE_XIANYUN_Q');resetWounds(f);f.r.basicHit(f.actor('LIYUE_XIANYUN'),f.enemy);const h=f.heals.find(h=>h.source===f.actor('LIYUE_XIANYUN').name);assert(h);assert.equal(h.applied,Math.round(h.requested));assert.equal(h.meta?.sourceKind,modern?'FIELD':undefined);return h;});
for(const modern of [true,false])test((modern?'new':'unmarked')+' own Qiqi pre-existing talisman during Q does not inherit cast talent/rhythm',()=>{const f=fixture(['LIYUE_QIQI','MOND_DILUC','MOND_AMBER'],modern);cast(f,'LIYUE_QIQI','LIYUE_QIQI_Q');resetWounds(f);cast(f,'LIYUE_QIQI','LIYUE_QIQI_Q');const h=f.heals.find(h=>h.source===f.actor('LIYUE_QIQI').name);assert(h);const factor=modern?1:1.5*f.r.premiumTalentMultiplier(f.actor('LIYUE_QIQI'),'q');assert.equal(h.applied,Math.round(h.requested*factor));assert.equal(h.meta?.sourceKind,modern?'FOLLOWUP':undefined);return{factor,...h};});
test('admin Xianyun stored Q healing scales once when its normal attack triggers field',()=>{const profile={revision:162501,config:{cards:{LIYUE_XIANYUN_Q:{healingMultiplier:.5}}}},f=fixture(undefined,true,profile);cast(f,'LIYUE_XIANYUN','LIYUE_XIANYUN_Q');const field=f.b.fields.find(f=>f.kind==='BAMBOO_STAR'),a=f.actor('LIYUE_XIANYUN'),expected=f.r.combatStat(a,'atk')*field.healRatio+field.healFlat;resetWounds(f);f.r.basicHit(a,f.enemy);const h=persistent(f,'FIELD')[0];assert(h);assert.equal(h.requested,expected);assert.equal(h.applied,Math.round(expected));return{field:cp(field),heal:h};});
test('admin Qiqi stored Q healing is not scaled a second time during own Q',()=>{const f=fixture(['LIYUE_QIQI','MOND_DILUC','MOND_AMBER'],true,{revision:162502,config:{cards:{LIYUE_QIQI_Q:{healingMultiplier:.5}}}});cast(f,'LIYUE_QIQI','LIYUE_QIQI_Q');const s=f.enemy.statuses.find(s=>s.id==='FORTUNE_TALISMAN'),a=f.actor('LIYUE_QIQI'),expected=f.r.combatStat(a,'atk')*s.healRatio+s.healFlat;resetWounds(f);cast(f,'LIYUE_QIQI','LIYUE_QIQI_Q');const h=persistent(f,'FOLLOWUP')[0];assert(h);assert.equal(h.requested,expected);assert.equal(h.applied,Math.round(expected));return{status:cp(s),heal:h};});
test('explicit actor ID disambiguates same-name healer through exclusive and role wrappers',()=>{const f=fixture(),owner=f.actor('LIYUE_XIANYUN'),other=f.actor('LIYUE_BAIZHU'),target=f.actor('PLAYER_CUSTOM');other.name=owner.name;owner.traits.HEAL_OUT=10;other.traits.HEAL_OUT=40;owner.statuses=[{id:'ROLE',supportOut:1.1}];other.statuses=[{id:'ROLE',supportOut:1.2}];f.r._rhythm={actor:owner.id,dmg:1,support:1.3};const out=f.r.heal(target,100,other.name,other.id);assert.equal(out,168);f.r._rhythm=null;return{applied:out,sourceActorId:other.id,exclusiveBonus:40,roleBonus:20,rhythmBorrowed:false};});
test('direct own heal keeps rhythm while explicit other caster is excluded',()=>{const f=fixture(),owner=f.actor('LIYUE_XIANYUN'),other=f.actor('LIYUE_BAIZHU'),target=f.actor('PLAYER_CUSTOM');f.r._rhythm={actor:owner.id,dmg:1,support:1.3};assert.equal(f.r.heal(target,100,owner.name,owner.id),130);assert.equal(f.r.heal(target,100,other.name,other.id),100);for(const sourceKind of ['FIELD','FOLLOWUP'])assert.equal(f.r.heal(target,100,owner.name,owner.id,{sourceKind}),100);f.r._rhythm=null;return{own:130,other:100,persistent:100};});
test('shields resolve declared source owner instead of unrelated active caster',()=>{const f=fixture(['LIYUE_ZHONGLI','LIYUE_BAIZHU','MOND_AMBER']),owner=f.actor('LIYUE_BAIZHU'),other=f.actor('LIYUE_ZHONGLI'),target=f.actor('PLAYER_CUSTOM');f.r._rhythm={actor:owner.id,dmg:1,support:1.3};f.r._consCast={a:owner,kind:'e',card:'LIYUE_BAIZHU_E'};const value=200,factor=f.r.premiumTalentMultiplier(other,'e');f.r.shield(target,value,'LIYUE_ZHONGLI_E',2,{actor:other.id});const shield=target.shields.find(s=>s.source==='LIYUE_ZHONGLI_E');assert(shield);assert.equal(shield.value,Math.round(value*f.r.combatCharacterBudget().zhongliShieldMultiplier));return{shield:cp(shield),unrelatedCastTalentExcluded:true,sourceTalentFactor:factor,currentCaster:owner.source};});
test('direct own source E shield retains active caster talent and rhythm',()=>{const f=fixture(['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN']),z=f.actor('LIYUE_ZHONGLI');f.r._rhythm={actor:z.id,dmg:1,support:1.3};f.r._consCast={a:z,kind:'q',card:'LIYUE_ZHONGLI_Q'};f.r.shield(z,200,'LIYUE_ZHONGLI_E',2,{actor:z.id});const shield=z.shields.find(s=>s.source==='LIYUE_ZHONGLI_E'),factor=f.r.premiumTalentMultiplier(z,'e');assert.equal(shield.value,Math.round(200*f.r.combatCharacterBudget().zhongliShieldMultiplier*factor*1.3));return{shield:cp(shield),factor,rhythm:1.3};});
test('native public Zhongli C2 unlock and Q place configured E-source shields on every ally',()=>{const f=fixture(['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN'],true,null,2),z=f.actor('LIYUE_ZHONGLI');cast(f,'LIYUE_ZHONGLI','LIYUE_ZHONGLI_Q');const values=f.b.actors.filter(a=>a.side==='ALLY').map(a=>({owner:a.source,shield:a.shields.find(s=>s.source==='LIYUE_ZHONGLI_E')}));const expected=Math.round(z.maxHp*.2*f.r.combatCharacterBudget().zhongliShieldMultiplier);for(const row of values){assert(row.shield);assert.equal(row.shield.value,expected);}return{maxHp:z.maxHp,expected,shields:cp(values)};});
for(const modern of [true,false])test((modern?'new':'unmarked')+' native Noelle E crystallize keeps reaction pool separate from skill support',()=>{const f=fixture(['MOND_NOELLE','MOND_DILUC','MOND_AMBER'],modern),a=f.actor('MOND_NOELLE');for(const enemy of f.b.actors.filter(a=>a.side==='ENEMY')){enemy.aura='불';enemy.auras=[{element:'불',rounds:2}];}cast(f,'MOND_NOELLE','MOND_NOELLE_E');const reaction=a.shields.find(s=>s.source==='RX_CRYSTALLIZE'),own=a.shields.find(s=>s.source==='MOND_NOELLE_E');assert(reaction);assert(own);const base=f.r.reactionBase(a),skill=f.r.combatStat(a,'def')*1.6*f.r.premiumTalentMultiplier(a,'e')*1.6;assert.equal(reaction.value,Math.round(base*(modern?1:1.6)));assert.equal(own.value,Math.round(skill));return{reaction:cp(reaction),reactionBase:base,oldErroneousRhythm:1.6,ownSkillShield:cp(own),skillFormula:skill};});
const after=hashes();report.inputSHA256=before;report.inputDrift=Object.keys(before).filter(f=>before[f]!==after[f]);test('runtime inputs remain unchanged while testing',()=>{assert.deepEqual(report.inputDrift,[]);return{inputs:watched.length,drift:0};});fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');const failed=report.checks.filter(c=>!c.passed);console.log(JSON.stringify({checks:report.checks.length,passed:report.checks.length-failed.length,failed:failed.length,fingerprint:report.fingerprint,output}));if(failed.length)process.exitCode=1;
