/* Standalone: node v09-research/quests/test_exploration.cjs [game-root] */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(process.argv[2]||path.resolve(__dirname,'..')),ctx=vm.createContext({console}),db=JSON.parse(fs.readFileSync(path.join(root,'content/db.json'))),original=JSON.stringify(db);
const scripts=[...fs.readFileSync(path.join(root,'source/index.html'),'utf8').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1].split('?')[0]).filter(f=>(f.startsWith('runtime')||f==='save_adapter.js')&&f!=='runtime_exploration.js');
for(const f of scripts)vm.runInContext(fs.readFileSync(path.join(root,'source',f),'utf8'),ctx,{filename:f});
vm.runInContext(fs.readFileSync(path.join(root,'source/runtime_exploration.js'),'utf8'),ctx,{filename:'runtime_exploration.js'});
ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db)});
const Runtime=ctx.CRPGRuntime.Runtime,catalog=ctx.CRPGRuntime.explorationCatalog,copy=x=>JSON.parse(JSON.stringify(x));let checks=0;
function check(name,fn){fn();checks++;console.log('PASS '+name);}
function fresh(route='ROUTE_TRAVELER'){const r=new Runtime(db);r.newGame({name:'탐험 검증',route,seed:74219,saveId:'QA-EXPLORATION-'+route});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'TRV_M02_MENU_003',STORY_CURSOR_NODE_ID:'TRV_M02_MENU_003',CURRENT_MAP_ID:'MAP_MOND_CITY',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',STORY_WAITING:false,STORY_MENU_POLICY:'',SCREEN_MODE:'LOCATION'});if(route==='ROUTE_ISEKAI'){r.s.global.CURRENT_STORY_NODE_ID='PAUSE';r.s.global.STORY_CURSOR_NODE_ID='PAUSE';r.s.global.STORY_WAITING=true;}return r;}
function level(r,n){r.s.global.PLAYER_LEVEL_STATE=n;r.s.global.PLAYER_XP_STATE=0;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;}
function map(r,id){r.s.global.CURRENT_MAP_ID=id;r.s.placeVisit=null;}
function guild(r){map(r,'MAP_MOND_CITY');r.s.global.WORLD_TIME='12:00';const e=r.placeEntries().find(e=>e.entity==='NPC_MOND_KATHERYNE');assert.ok(e);r.action('PLACE_ENTER',{place:e.id,mode:'TALK'});}
function throwsUnchanged(r,fn){const before=r.serialize();assert.throws(fn);assert.equal(r.serialize(),before);}
check('local overlay does not mutate source DB and is present before save validation',()=>{const r=fresh();assert.equal(JSON.stringify(db),original);assert.equal(r.tables['14_ITEM_DB'].has(catalog.item),true);assert.equal(catalog.quests.length,10);const reload=new Runtime(db,copy(r.s));assert.equal(reload.tables['22_QUEST_DB'].has(catalog.quests[0].id),true);});
check('existing Favonius level 3 gate applies to acceptance and execution',()=>{const r=fresh();guild(r);assert.equal(r.commissionEntries().some(q=>q.row[0]==='Q_MOND_FAVONIUS_SUPPLY'),false);throwsUnchanged(r,()=>r.action('COMMISSION_ACCEPT',{quest:'Q_MOND_FAVONIUS_SUPPLY'}));level(r,3);assert.equal(r.commissionEntries().some(q=>q.row[0]==='Q_MOND_FAVONIUS_SUPPLY'),true);r.action('COMMISSION_ACCEPT',{quest:'Q_MOND_FAVONIUS_SUPPLY'});assert.equal(r.s.quests.Q_MOND_FAVONIUS_SUPPLY.guildAccepted,true);assert.ok(r.questConditions('Q_MOND_FAVONIUS_SUPPLY'));});
check('unvisited Liyue hidden even with access flag or old accepted quest; forged claim/choice blocked',()=>{const r=fresh();level(r,20);guild(r);r.s.flags.FLAG_ACCESS_REGION_LIYUE=true;r.s.quests.Q_LIYUE_XP_SUPPLY={guildAccepted:true,state:'진행중',node:'INVESTIGATE',attempts:0,claimed:false};assert.equal(r.regionVisited('리월'),false);assert.equal(r.commissionEntries().some(q=>q.row[2]==='리월'),false);assert.equal(r.view().quests.some(q=>q.row[2]==='리월'),false);throwsUnchanged(r,()=>r.action('COMMISSION_ACCEPT',{quest:'Q_LIYUE_EXP_PLAINS_CARAVAN'}));throwsUnchanged(r,()=>r.action('QUEST_CHOICE',{quest:'Q_LIYUE_EXP_PLAINS_CARAVAN',choice:'careful'}));throwsUnchanged(r,()=>r.action('CLAIM_QUEST',{quest:'Q_LIYUE_EXP_PLAINS_CARAVAN'}));});
check('real successful move visits Liyue, persists after return and save load',()=>{const r=fresh();level(r,20);r.s.flags.FLAG_ACCESS_REGION_LIYUE=true;r.action('MOVE',{edge:'EDGE_CRPG_MOND_CITY_TO_LIYUE_HARBOR'});assert.equal(r.regionVisited('리월'),true);assert.equal(r.s.exploration.visitedMaps.MAP_LIYUE_HARBOR,true);r.action('MOVE',{edge:'EDGE_CRPG_LIYUE_HARBOR_TO_MOND_CITY'});const restored=new Runtime(db,copy(r.s));assert.equal(restored.regionVisited('리월'),true);assert.ok(restored.commissionEntries().some(q=>q.row[2]==='리월'));});
check('old saves recover only actual current/map-count/completion evidence',()=>{for(const evidence of ['current','count','completed']){const r=fresh();delete r.s.exploration;if(evidence==='current')map(r,'MAP_LIYUE_HARBOR');if(evidence==='count')r.s.global.WORLD_VISIT_COUNTS_JSON=JSON.stringify({MAP_LIYUE_PLAINS:1});if(evidence==='completed')r.s.quests.Q_LIYUE_EXP_PLAINS_CARAVAN={claimed:true,state:'완료'};const restored=new Runtime(db,copy(r.s));assert.equal(restored.regionVisited('리월'),true);assert.ok(Object.keys(restored.s.exploration.visitedMaps).some(id=>restored.tables['32_MAP_DB'].get(id)[1]==='리월'));}});
check('old scripted-travel receipt with same save and route restores actual visited map',()=>{const r=fresh('ROUTE_ISEKAI');delete r.s.exploration;const e=r.storyEventDefinitions().find(e=>{const p=JSON.parse(e.EXEC_PAYLOAD_JSON||'{}');return p.handler==='isk_story_travel'&&p.to_map&&p.to_map!=='MAP_MOND_CITY';});assert.ok(e);const p=JSON.parse(e.EXEC_PAYLOAD_JSON);r.s.global.EVENT_PROGRESS_JSON=JSON.stringify({[e.EVENT_ID]:{event:e.EVENT_ID,saveId:r.s.global.SAVE_ID,route:r.s.global.STORY_ROUTE_ID,resolvedNode:e.SOURCE_ID_OR_FILTER}});const restored=new Runtime(db,copy(r.s));assert.equal(restored.s.exploration.visitedMaps[p.to_map],true);});
check('all 10 new quests have valid maps, items and groups; every noncombat quest grants once',()=>{for(const spec of catalog.quests){const r=fresh();level(r,20);guild(r);r.action('COMMISSION_ACCEPT',{quest:spec.id});map(r,spec.map);const row=r.row('22_QUEST_DB',spec.id),d=JSON.parse(row[10]),reward=JSON.parse(row[11]);for(const id of Object.keys(reward.items))assert.ok(r.tables['14_ITEM_DB'].has(id));if(d.choices[0].combat_group){assert.ok(r.tables['33_ENCOUNTER_GROUP_DB'].has(d.choices[0].combat_group));continue;}if(d.conditions.activity_requirement)r.s.quests.Q_MOND_EXP_PLAINS_CART={claimed:true,state:'완료'};r.action('QUEST_CHOICE',{quest:spec.id,choice:'careful'});const mora=r.s.global.MORA;r.action('CLAIM_QUEST',{quest:spec.id});assert.equal(r.s.global.MORA,mora+reward.mora);throwsUnchanged(r,()=>r.action('CLAIM_QUEST',{quest:spec.id}));}});
check('new quest XP actually raises player XP exactly once',()=>{const r=fresh();guild(r);const id='Q_CRPG_MOND_EXP_BRIDGE_PARCEL';r.action('COMMISSION_ACCEPT',{quest:id});r.action('QUEST_CHOICE',{quest:id,choice:'careful'});r.action('CLAIM_QUEST',{quest:id});assert.equal(r.s.global.PLAYER_XP_STATE,50);throwsUnchanged(r,()=>r.action('CLAIM_QUEST',{quest:id}));});
check('combat commission enters the registered encounter and claim waits for victory',()=>{const r=fresh();level(r,3);guild(r);const id='Q_CRPG_MOND_EXP_DAWN_VINEYARD';r.action('COMMISSION_ACCEPT',{quest:id});map(r,'MAP_MOND_DAWN_WINERY');r.action('QUEST_CHOICE',{quest:id,choice:'careful'});assert.equal(r.s.runtime.origin,'QUEST:'+id);assert.equal(r.s.runtime.group,'EG_MOND_SLIME_SMALL');assert.equal(r.s.quests[id].node,'AWAIT_VICTORY');throwsUnchanged(r,()=>r.action('CLAIM_QUEST',{quest:id}));r.finishBattle(true);assert.equal(r.s.quests[id].node,'READY_TO_CLAIM');r.action('CLAIM_QUEST',{quest:id});assert.equal(r.s.quests[id].claimed,true);});
check('points enforce map and level, hide on completion, never respawn after day/save',()=>{const r=fresh(),p=catalog.points.find(p=>p.level===1&&p.map==='MAP_MOND_PLAINS');throwsUnchanged(r,()=>r.action('OCULUS_COLLECT',{point:p.id}));map(r,p.map);const high=catalog.points.find(p=>p.map===r.s.global.CURRENT_MAP_ID&&p.level>1);assert.ok(!r.oculusEntries().some(p=>p.id===high.id));throwsUnchanged(r,()=>r.action('OCULUS_COLLECT',{point:high.id}));r.action('OCULUS_COLLECT',{point:p.id});assert.equal(r.itemCount(catalog.item),1);assert.ok(!r.oculusEntries().some(e=>e.id===p.id));r.advanceTime(1440);const restored=new Runtime(db,copy(r.s));throwsUnchanged(restored,()=>restored.action('OCULUS_COLLECT',{point:p.id}));assert.equal(restored.itemCount(catalog.item),1);});
check('collection locked by story, combat and active work',()=>{const p=catalog.points[0];for(const lock of ['story','combat','work']){const r=fresh();map(r,p.map);if(lock==='story'){r.s.global.CURRENT_STORY_NODE_ID='TRV_M01_START';r.s.global.STORY_CURSOR_NODE_ID='TRV_M01_START';r.s.global.STORY_MENU_POLICY='SAVE_LOAD_ONLY';}else if(lock==='combat')r.startBattle('EG_CRPG_MOND_FIRST_FIELD','RANDOM');else r.action('LIFE_START',{kind:'GATHER'});throwsUnchanged(r,()=>r.action('OCULUS_COLLECT',{point:p.id}));assert.equal(r.itemCount(catalog.item),0);}});
check('ritual hidden before threshold; final requires story and contact in both routes; grants no party slot',()=>{for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI']){const r=fresh(route);level(r,6);map(r,'MAP_MOND_WINDRISE');assert.equal(r.oculusExchangeEntry(),null);for(const p of catalog.points){map(r,p.map);r.action('OCULUS_COLLECT',{point:p.id});}assert.equal(r.itemCount(catalog.item),12);map(r,'MAP_MOND_WINDRISE');assert.equal(r.oculusExchangeEntry().id,'TIER_1');throwsUnchanged(r,()=>r.action('OCULUS_OFFER',{tier:'TIER_FINAL'}));r.action('OCULUS_OFFER',{tier:'TIER_1'});r.action('OCULUS_OFFER',{tier:'TIER_2'});assert.equal(r.oculusExchangeEntry(),null);throwsUnchanged(r,()=>r.action('OCULUS_OFFER',{tier:'TIER_FINAL'}));const q=route==='ROUTE_TRAVELER'?'Q_TRV_MOND_02':'Q_ISK_MOND_03',flag=route==='ROUTE_TRAVELER'?'FLAG_TRV_MON_CH2_CLEAR':'FLAG_ISK_M05_CLEAR';r.s.quests[q]={claimed:true,state:'완료'};r.s.flags[flag]=true;assert.equal(r.oculusExchangeEntry(),null);r.markContact('PROFILE_MOND_VENTI');assert.equal(r.oculusExchangeEntry().id,'TIER_FINAL');const party=JSON.stringify(r.s.party),growth=JSON.stringify(r.s.chars.MOND_VENTI);r.action('OCULUS_OFFER',{tier:'TIER_FINAL'});assert.equal(r.itemCount(catalog.item),0);assert.equal(JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON).MOND_VENTI.state,'JOINED');assert.equal(JSON.stringify(r.s.party),party);assert.equal(JSON.stringify(r.s.chars.MOND_VENTI),growth);const restored=new Runtime(db,copy(r.s));assert.equal(restored.s.exploration.tiers.length,3);throwsUnchanged(restored,()=>restored.action('OCULUS_OFFER',{tier:'TIER_FINAL'}));}});
check('oculus receipt replay is idempotent; malformed ledger rejected',()=>{const r=fresh(),p=catalog.points[0];map(r,p.map);const a={type:'OCULUS_COLLECT',point:p.id,id:r.s.global.SAVE_ID+':1',revision:0};r.transact(a);const before=r.serialize();r.transact(a);assert.equal(r.serialize(),before);const bad=copy(r.s);bad.inventory.find(x=>x.item===catalog.item).quantity++;assert.throws(()=>new Runtime(db,bad));});
console.log(JSON.stringify({checks,passed:checks,sourceUnchanged:JSON.stringify(db)===original}));
