'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto');
const gameRoot=process.env.CRPG_GAME||(fs.existsSync(path.join(__dirname,'../source/runtime.js'))?path.resolve(__dirname,'..'):path.resolve(__dirname,'../../game'));
const source=process.env.CRPG_SOURCE||path.join(gameRoot,'source'),db=JSON.parse(fs.readFileSync(process.env.CRPG_DB||path.join(gameRoot,'content/db.json'))),results=[];
const modules=[...fs.readFileSync(path.join(source,'index.html'),'utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(x=>(x.startsWith('runtime')||x==='save_adapter.js'||x==='presentation.js')&&fs.existsSync(path.join(source,x)));
const candidatePath=process.env.CRPG_OPENING||(fs.existsSync(path.join(__dirname,'runtime_opening.js'))?path.join(__dirname,'runtime_opening.js'):path.join(source,'runtime_opening.js'));
const sourceCode=modules.map(name=>[name,fs.readFileSync(path.join(source,name),'utf8')]),candidate=fs.readFileSync(candidatePath,'utf8');
let skew=0;// lets a test skip the 60 second defeat lock without waiting
function context(opening=true){const c=vm.createContext({console,Date:class extends Date{static now(){return super.now()+skew;}}});for(const[name,code]of sourceCode){if(name==='runtime_opening.js'){if(opening)vm.runInContext(candidate,c,{filename:'candidate/runtime_opening.js'});}else vm.runInContext(code,c,{filename:name});}return c;}
const ctx=context(),legacy=context(false),R=ctx.CRPGRuntime.Runtime,copy=x=>JSON.parse(JSON.stringify(x));
function fresh(c=ctx,id='OPENING-TEST',route='ROUTE_TRAVELER'){const r=new c.CRPGRuntime.Runtime(db);r.newGame({name:'시작 순서 검증',route,seed:21574,saveId:id});return r;}
function hub(c=ctx,id='OPENING-TEST'){const r=fresh(c,id);Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'HUB',STORY_CURSOR_NODE_ID:'HUB',SCREEN_MODE:'LOCATION',STORY_MENU_POLICY:'FULL',PENDING_CHOICE_GROUP_ID:'',CURRENT_MAP_ID:'MAP_WOLF_ARENA',PLAYER_BASE_HP:100000});r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;r.action('PLACE_ENTER',{place:'BOSS:BRT_ANDRIUS'});return r;}
function story(c=ctx,id='OPENING-STORY'){const r=fresh(c,id,'ROUTE_ISEKAI'),cfg=r.combatStoryConfig('EG_ISK_M04_AB_DVALIN');Object.assign(r.s.flags,{FLAG_ISK_META_KNOWLEDGE:'UNKNOWN',FLAG_ISK_MOND_BRANCH:'EXPEDITION',FLAG_ISK_EXPEDITION_FORK:'RETURN',FLAG_ISK_ORB_OWNED:true});r.s.quests.Q_ISK_MOND_02={state:'진행중',node:'ACTIVE',claimed:false};r.giveItem('KEY_ISK_MYSTERY_ORB',1);Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:cfg.node_id,STORY_CURSOR_NODE_ID:cfg.node_id,PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',SCREEN_MODE:'STORY',CURRENT_MAP_ID:cfg.map_id});r.prepareStory();r.action('STORY_NEXT',{node:cfg.node_id});assert.equal(r.playPhase(),'PREPARATION');return r;}
function block(r,type,params={}){const before=r.serialize();assert.throws(()=>r.action(type,params));assert.equal(r.serialize(),before);}
function combatOnly(r){const b=copy(r.s.runtime);delete b.opening;return JSON.stringify({battle:b,prng:r.s.global.PRNG_STATE});}
function test(name,fn){try{const evidence=fn();results.push({name,ok:true,evidence:evidence||null});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
test('public story preparation commits actual order without any automatic turn or HP loss',()=>{const r=story();const hp=r.s.global.PLAYER_HP_CURRENT,result=r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});const b=r.s.runtime;assert.equal(r.playPhase(),'COMBAT_OPENING');assert.equal(b.round,1);assert.equal(b.cursor,0);assert.equal(b.actionSequence,0);assert.equal(b.turnStarted,null);assert(b.actors.every(a=>a.turns===0));assert.equal(r.combatActor().hp,hp);assert(!b.log.some(e=>Object.hasOwn(e,'damage')||Object.hasOwn(e,'heal')||e.guard||e.miss));assert.equal(result.result.opening,true);assert.equal(JSON.stringify(b.order),JSON.stringify(b.opening.initialOrder));assert.equal(r.combatOpening().firstActorId,b.order[0].id);return{battle:b.id,hp,order:r.combatOrderView(),logs:b.log};});
test('opening previews, menus and internal auto/newRound calls never advance or reroll',()=>{const r=hub();r.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});const b=copy(r.s.runtime),rng=r.s.global.PRNG_STATE;for(let i=0;i<4;i++){r.combatOpening();r.combatOrderView();r.view();r.autoUntilPlayer();r.newRound();r.resolveEnemyPhases();}assert.equal(JSON.stringify(r.s.runtime),JSON.stringify(b));assert.equal(r.s.global.PRNG_STATE,rng);r.action('MENU',{screen:'SYSTEM'});assert.equal(r.playPhase(),'COMBAT_OPENING');r.action('MENU',{screen:'COMBAT'});assert.equal(JSON.stringify(r.s.runtime),JSON.stringify(b));assert.equal(r.s.global.PRNG_STATE,rng);for(const[type,params]of [['COMBAT',{card:'PLAYER_BASIC_ATTACK'}],['COMBAT_PREPARE',{group:b.group}],['PARTY',{char:'MOND_AMBER',slot:2}],['STORY_NEXT',{node:'HUB'}],['MOVE',{edge:'INVALID'}],['TOOL_PREPARE',{items:[]}],['COMBAT_BEGIN',{battle:'WRONG'}]])block(r,type,params);assert(r.combatCards().every(c=>c.reason));return{prng:rng,round:b.round,logCount:b.log.length};});
test('SaveAdapter and Runtime round-trip opening without auto execution',()=>{const r=hub();r.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});const serialized=r.serialize(),adapter=new ctx.CRPGSave.SaveAdapter({validate:s=>new R(db,s).s}),prepared=adapter.prepare(JSON.parse(serialized)),saved=new R(db,prepared);assert.equal(saved.serialize(),serialized);assert.equal(saved.playPhase(),'COMBAT_OPENING');assert.equal(JSON.stringify(saved.combatOpening()),JSON.stringify(r.combatOpening()));const request={battle:r.s.runtime.id};assert.equal(JSON.stringify(r.action('COMBAT_BEGIN',request)),JSON.stringify(saved.action('COMBAT_BEGIN',request)));assert.equal(saved.serialize(),r.serialize());return{round:r.s.runtime.round,phase:r.playPhase(),prng:r.s.global.PRNG_STATE};});
test('begin consumes already-rolled initiative and equals legacy combat outcome / PRNG',()=>{for(const entry of ['DIRECT','GAUNTLET']){const a=hub(legacy,'OPENING-PARITY-'+entry),b=hub(ctx,'OPENING-PARITY-'+entry);a.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry});b.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry});const initial=copy(b.s.runtime.order);const result=b.action('COMBAT_BEGIN',{battle:b.s.runtime.id});assert.equal(JSON.stringify(result.result.initialOrder),JSON.stringify(initial));assert.deepEqual(JSON.parse(combatOnly(b)),JSON.parse(combatOnly(a)));}return{entries:['DIRECT','GAUNTLET'],comparison:'all runtime battle state except opening metadata + exact PRNG state'};});
test('duplicate explicit COMBAT_BEGIN returns receipt; new duplicate action rejects atomically',()=>{const r=hub();r.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});const g=r.s.global,a={id:g.SAVE_ID+':'+(g.LAST_COMMITTED_ACTION_SEQ+1),revision:g.SAVE_REVISION,type:'COMBAT_BEGIN',battle:r.s.runtime.id};const receipt=r.transact(a),state=r.serialize();assert.equal(JSON.stringify(r.transact(a)),JSON.stringify(receipt));assert.equal(r.serialize(),state);block(r,'COMBAT_BEGIN',{battle:r.s.runtime.id});return{action:a.id,events:receipt.result.events.length};});
test('after beginning, normal combat reaches next rounds and stays deterministic after save',()=>{const r=hub();r.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});r.action('COMBAT_BEGIN',{battle:r.s.runtime.id});const restored=new R(db,JSON.parse(r.serialize()));for(let i=0;i<4;i++){assert.equal(JSON.stringify(r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'})),JSON.stringify(restored.action('COMBAT',{card:'PLAYER_BASIC_GUARD'})));assert.equal(r.serialize(),restored.serialize());}assert(r.s.runtime.round>1);return{round:r.s.runtime.round,prng:r.s.global.PRNG_STATE};});
test('story defeat and public retry recreate opening with same order and no automatic damage',()=>{const r=story();r.s.global.PLAYER_HP_CURRENT=1;r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});const first=r.s.runtime.id,order=JSON.stringify(r.s.runtime.order),rng=r.s.global.PRNG_STATE;assert.equal(r.combatActor().hp,1);const result=r.action('COMBAT_BEGIN',{battle:first});assert.equal(result.result.finished,true);assert.equal(r.playPhase(),'RECOVERY');assert.throws(()=>r.action('STORY_RETRY'),/정신을 차리는 중/);skew+=60000;r.action('STORY_RETRY');assert.equal(r.playPhase(),'PREPARATION');r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});assert.equal(r.playPhase(),'COMBAT_OPENING');assert.notEqual(r.s.runtime.id,first);assert.equal(JSON.stringify(r.s.runtime.order),order);assert.equal(r.s.global.PRNG_STATE,rng);assert.equal(r.combatActor().hp,1);assert.equal(r.s.runtime.round,1);return{firstBattle:first,retryBattle:r.s.runtime.id,order:r.combatOrderView()};});
test('Dvalin cutins and subdued final action retain existing continuation and save behavior',()=>{const r=story();Object.assign(r.s.global,{PLAYER_BASE_HP:100000,PLAYER_BASE_ATK:100000});r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});r.action('COMBAT_BEGIN',{battle:r.s.runtime.id});r.action('COMBAT',{card:'ACT_ISK_M04_AERIAL_STEP'});for(let attempts=0;attempts<4&&r.playPhase()==='COMBAT';attempts++){const card=r.combatCards().find(c=>c.id==='PLAYER_BASIC_ATTACK'&&!c.reason);assert(card);r.action('COMBAT',{card:card.id,target:card.targets[0].id});}assert.equal(r.playPhase(),'CUTIN',JSON.stringify(r.s.runtime?.log));assert.equal(r.combatOpening(),null);block(r,'COMBAT_BEGIN',{battle:r.s.runtime.id});const saved=new R(db,JSON.parse(r.serialize()));assert.equal(saved.serialize(),r.serialize());let lines=0;while(r.playPhase()==='CUTIN'&&lines++<30){const choices=r.storyChoices(),type=choices.length?'STORY_CHOICE':'STORY_NEXT',params={node:(choices[0]||r.storyNode())[4]};assert.equal(JSON.stringify(r.action(type,params)),JSON.stringify(saved.action(type,params)));assert.equal(saved.serialize(),r.serialize());}assert.equal(r.playPhase(),'COMBAT');assert(r.s.runtime.subduedPending);const orb=r.combatCards().find(c=>c.id===r.s.runtime.storyConfig.orb_action.id);const result=r.action('COMBAT',{card:orb.id,target:orb.targets[0].id});assert.equal(result.result.finished,true);assert.equal(JSON.parse(r.s.global.LAST_BATTLE_RESULT_JSON).result,'ALIVE_PURIFIED');return{lines,result:JSON.parse(r.s.global.LAST_BATTLE_RESULT_JSON).result};});
test('legacy active battle without opening metadata remains playable',()=>{const old=hub(legacy);old.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});const r=new R(db,JSON.parse(old.serialize()));assert.equal(r.combatOpening(),null);assert.equal(r.playPhase(),'COMBAT');r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});return{phase:r.playPhase(),round:r.s.runtime.round};});
test('corrupt pending initiative or turn state rejects at load',()=>{const r=hub();r.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});for(const mutate of [s=>s.runtime.order[0].score++,s=>s.runtime.cursor++,s=>s.runtime.actors[0].turns++,s=>s.global.COMBAT_ACTION_PHASE='WAIT_PLAYER']){const bad=JSON.parse(r.serialize());mutate(bad);assert.throws(()=>new R(db,bad),e=>e.code==='OPENING_SAVE');}return{mutations:4};});
test('duplicate addon installation does not wrap or reroll a second time',()=>{const method=R.prototype.newRound;vm.runInContext(candidate,ctx);assert.equal(R.prototype.newRound,method);const r=hub();r.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});assert(r.s.runtime.order.length>0);r.serialize();return{orderCount:r.s.runtime.order.length};});
const report={generatedAt:new Date().toISOString(),productEdited:false,modules,candidateSHA256:crypto.createHash('sha256').update(candidate).digest('hex'),results};fs.writeFileSync(path.join(__dirname,'../reports/opening-tests.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:results.filter(x=>x.ok).length,total:results.length}));if(results.some(x=>!x.ok))process.exitCode=1;
