import assert from 'node:assert/strict';
import {onlineFixture,R,DB} from './helpers_online.mjs';
const f=onlineFixture();await f.start();
const r=new R(DB,JSON.parse(f.read().state));
// Both backends must use the same fixed PRNG state for this damage assertion.
r.s.global.PRNG_STATE=7317;
Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:'MAP_MOND_PLAINS',STORY_MENU_POLICY:'',WORLD_TIME:'12:00'});
delete r.s.storyJourney;delete r.s.storyBreak;r.prepareStory();
r.startBattle('EG_MOND_HILI_PATROL','RANDOM');f.seed(r.s);
const opened=await f.action('COMBAT_BEGIN',{battle:r.s.runtime.id});assert.equal(opened.status,200);
assert.equal(opened.state.runtime.actors.find(a=>a.id===opened.state.runtime.order[opened.state.runtime.cursor].id).control,'PLAYER');
const round=await f.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});assert.equal(round.status,200);
const logs=round.state.runtime?.log||round.state.lastCombatLog;
const damage=logs.filter(e=>Object.hasOwn(e,'damage'));
assert(damage.length,'fixture must produce real damage');
for(const event of damage){
 assert(event.targetId,'server damage must identify its exact target');
 assert(event.actorId,'server damage must identify its actor');
 assert(Number.isFinite(event.hpBefore)&&Number.isFinite(event.hpAfter),'server damage must include HP transitions');
 assert(Number.isInteger(event.actionSequence)&&Number.isInteger(event.round),'server events must group one action across all targets');
}
console.log('PASS authoritative combat starts at player input and returns identified HP/action events');
const navigation=new R(DB);navigation.newGame({name:'화면 문맥 검증',route:'ROUTE_ISEKAI',seed:7317,saveId:'NAV-CONTEXT'});
navigation.serverAdmin=true;navigation.action('OPERATOR_DEBUG',{op:'travel',map:'MAP_MOND_CITY'});
Object.assign(navigation.s.flags,{FLAG_ISK_MON_PROLOGUE_CLEAR:true,FLAG_ISK_MAIN_UNLOCKED:true});
const shop=navigation.placeEntries().find(x=>x.modes.includes('SHOP')&&!navigation.actionReason('PLACE_ENTER',{place:x.id,mode:'SHOP'}));
assert(shop,'fixture must enter an actually accessible shop');
navigation.action('PLACE_ENTER',{place:shop.id,mode:'SHOP'});assert(navigation.s.placeVisit);f.seed(navigation.s);
const departed=await f.action('WAIT',{minutes:10},{uiActions:['LOCATION','SYSTEM'],uiScreen:'SYSTEM'});
assert.equal(departed.status,200,departed.error);assert.equal(departed.state.placeVisit,null,'intermediate departure must not disappear when final screen is SYSTEM');
f.seed(navigation.s);const beforeInvalid=f.read();
const invalid=await f.action('WAIT',{minutes:10},{uiActions:['LOCATION','SHOP'],uiScreen:'SHOP'});
assert.equal(invalid.status,409);assert.equal(f.read().state,beforeInvalid.state);assert.equal(f.read().revision,beforeInvalid.revision,'invalid navigation cannot partially commit');
const malformed=await f.action('WAIT',{minutes:10},{uiActions:['OPERATOR_DEBUG']});assert.equal(malformed.status,400);assert.equal(f.read().state,beforeInvalid.state);
console.log('PASS ordered local menu context, inaccessible service rejection and atomic rollback');
navigation.action('PLACE_LEAVE');navigation.unlockCharacter('MOND_KAEYA');
const weapon=navigation.giveEquipment('EQ_SWORD_HARBINGER');f.seed(navigation.s);
const party=await f.action('PARTY',{char:'MOND_KAEYA',slot:2},{uiActions:['PARTY'],uiScreen:'PARTY'});
assert.equal(party.status,200,party.error);assert(JSON.parse(f.read().state).party.some(p=>p.source==='MOND_KAEYA'&&p.active));
const equip=await f.action('EQUIP',{slot:weapon,owner:'MOND_KAEYA'},{uiActions:['INVENTORY'],uiScreen:'INVENTORY'});
assert.equal(equip.status,200,equip.error);assert(JSON.parse(f.read().state).inventory.find(i=>i.slot===weapon).equipped);
const restored=await f.call('/me');assert.deepEqual(restored.state.party,equip.state.party);assert.deepEqual(restored.state.inventory,equip.state.inventory);
console.log('PASS party and equipment changes immediately persist through server reload');
