/* Runtime and UI-adapter regressions. All mutations are isolated test saves.
 * Usage: node revision-research/flow-regressions.cjs
 * Optional: CRPG_SOURCE=/path/source CRPG_DB=/path/content.json node ...
 */
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const source=process.env.CRPG_SOURCE||path.resolve(__dirname,'../source');
const dataPath=process.env.CRPG_DB||path.resolve(__dirname,'../content/db.json');
const index=fs.readFileSync(path.join(source,'index.html'),'utf8');
const files=[...index.matchAll(/<script\s+src="([^"]+)"/g)].map(x=>x[1]).filter(x=>/^runtime[^/]*\.js$/.test(x));
const ctx=vm.createContext({console}),hashes={},loaded=[];
for(const file of files){const p=path.join(source,file);if(file==='runtime_rules.js'&&!fs.existsSync(p))continue;const text=fs.readFileSync(p,'utf8');hashes[file]=crypto.createHash('sha256').update(text).digest('hex');vm.runInContext(text,ctx,{filename:file});loaded.push(file);}
const db=JSON.parse(fs.readFileSync(dataPath,'utf8'));
ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});
const {Runtime}=ctx.CRPGRuntime,results=[];
const copy=x=>JSON.parse(JSON.stringify(x));
let saveSeq=0;
function fresh(route='ROUTE_TRAVELER'){const r=new Runtime(db);r.newGame({name:'고정된이름',route,seed:74219,saveId:'FLOW-REGRESSION-'+(++saveSeq)});return r;}
function goto(r,node){Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:node,STORY_CURSOR_NODE_ID:node,PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',SCREEN_MODE:'STORY'});r.prepareStory();return r;}
function overview(r){return{phase:r.playPhase(),screen:r.s.global.SCREEN_MODE,node:r.storyActiveNodeId(),main:r.s.global.STORY_CURSOR_NODE_ID,map:r.s.global.CURRENT_MAP_ID,waiting:r.s.global.STORY_WAITING,policy:r.s.global.STORY_MENU_POLICY,context:r.s.storyContext?.kind||null,menuFrame:r.s.storyMenuFrame?.main||null,stack:r.s.storyReturnStack?.length||0};}
function blocked(r,type,params={},code='ACTION_LOCK'){const before=r.serialize();let caught;try{r.action(type,params);}catch(e){caught=e;}assert.ok(caught,`expected ${type} to be rejected: ${JSON.stringify(overview(r))}`);if(code)assert.equal(caught.code,code,`${type}: ${caught.message}`);assert.equal(r.serialize(),before,`${type} rejection changed save`);return caught.message;}
function freeHub(){const r=fresh();goto(r,'TRV_M02_MENU_003');return r;}
// Cursor/prerequisites are isolated fixtures; waiting state and event receipts below
// are produced only by the real public STORY_NEXT action, never forged.
function knownPause(node='ISK_M02_K_GATE'){const r=fresh('ROUTE_ISEKAI');Object.assign(r.s.flags,{FLAG_ISK_MAIN_UNLOCKED:true,FLAG_ISK_MON_PROLOGUE_CLEAR:true,FLAG_ISK_META_KNOWLEDGE:'KNOWN',FLAG_ISK_LEG_AMBER_CLEAR:false,FLAG_ISK_LYRE_STATUS:'TRAIL_LOST',FLAG_ISK_VENTI_TOLD_JEAN:true,FLAG_ISK_FATUI_TEMPLE_DEAD:true,FLAG_ISK_TEAR_RECOVERED:true,FLAG_ISK_TEAR_PURIFICATION:'FAILED',FLAG_ISK_TEAR_FAILURE_TONE:'SILENT'});r.s.quests.Q_ISK_MOND_02={state:'진행중',node:'ACTIVE',claimed:false};goto(r,node);r.s.global.CURRENT_MAP_ID=r.storyNode()[8];r.action('STORY_NEXT',{node});assert.equal(r.isStoryWaiting(),true);return r;}
function registerAtGuild(r,kind,quest){const map=r.s.global.CURRENT_MAP_ID;r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';r.action('PLACE_ENTER',{place:'EVT_SCHEDULE_NPC_MOND_KATHERYNE',mode:'TALK'});r.action(kind,{quest});r.action('PLACE_LEAVE');r.s.global.CURRENT_MAP_ID=map;}
function prep(){const r=fresh('ROUTE_ISEKAI'),cfg=r.combatStoryConfig('EG_ISK_M04_AB_DVALIN');Object.assign(r.s.flags,{FLAG_ISK_META_KNOWLEDGE:'UNKNOWN',FLAG_ISK_MOND_BRANCH:'EXPEDITION',FLAG_ISK_EXPEDITION_FORK:'RETURN',FLAG_ISK_ORB_OWNED:true});r.s.quests.Q_ISK_MOND_02={state:'진행중',node:'ACTIVE',claimed:false};r.giveItem('KEY_ISK_MYSTERY_ORB',1);goto(r,cfg.node_id);r.action('STORY_NEXT',{node:cfg.node_id});assert.equal(r.playPhase(),'PREPARATION');return r;}
function cutin(){const r=prep(),cfg=r.combatStoryConfig(r.s.battlePreparation.group);Object.assign(r.s.global,{PLAYER_BASE_HP:100000,PLAYER_BASE_ATK:100000});r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;r.action('COMBAT_PREPARE',{group:cfg.group_id,companions:[]});r.action('COMBAT_BEGIN',{battle:r.s.runtime.id});r.action('COMBAT',{card:'ACT_ISK_M04_AERIAL_STEP'});const card=r.combatCards().find(x=>x.id==='PLAYER_BASIC_ATTACK'&&!x.reason);r.action('COMBAT',{card:card.id,target:card.targets[0].id});assert.equal(r.playPhase(),'CUTIN');return r;}
async function test(name,fn){try{const evidence=await fn();results.push({name,ok:true,evidence:evidence||null});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:{message:e.message,code:e.code,stack:e.stack}});console.error('FAIL '+name+'\n'+e.stack);}}

// Small DOM harness invokes the real app_revision.js functions without starting
// browser storage or network boot. Browser visual QA is deliberately separate.
class Element {
 constructor(tag='div',className='',text=''){this.tagName=tag.toUpperCase();this.className=className||'';this._text=String(text??'');this.children=[];this.attributes={};this.style={};this.isConnected=true;this.disabled=false;}
 append(...items){this.children.push(...items.filter(x=>x!==undefined&&x!==null));}
 prepend(...items){this.children.unshift(...items);}
 replaceChildren(...items){this.children=[];this.append(...items);}
 setAttribute(k,v){this.attributes[k]=String(v);}
 get textContent(){return this._text+this.children.map(c=>typeof c==='string'?c:c.textContent).join('');}
 set textContent(v){this._text=String(v);this.children=[];}
 querySelectorAll(selector){const choices=selector.split(',').map(x=>x.trim()),found=[];const match=e=>choices.some(s=>s.startsWith('.')?e.className.split(' ').includes(s.slice(1)):e.tagName===s.toUpperCase());const walk=e=>{for(const c of e.children){if(c instanceof Element){if(match(c))found.push(c);walk(c);}}};walk(this);return found;}
 querySelector(s){return this.querySelectorAll(s)[0]||null;}
}
function uiHarness(r){
 const wordmark=new Element('a'),spy={messages:[],actions:[],saves:0,renders:0,begins:0};
 const u=vm.createContext({console,Promise,Map,Set,JSON,Date,Number,String,Array,Math,URL,Blob,Element,game:r,busy:false,Runtime,DB:db,CRPGRuntime:ctx.CRPGRuntime,CRPGRelationships:ctx.CRPGRelationships,MANIFEST:{},window:{},settings:{},selectedNPC:null,selectedCard:null,selectedTarget:null,activeSaveSlot:'test-slot',slotRevisions:new Map(),sceneHistory:[],saveFailed:false,lastSaveError:'',root:new Element('div'),document:{querySelector:()=>wordmark},
  el:(...args)=>new Element(...args),button:(text,fn,disabled=false)=>{const e=new Element('button','',text);e.onclick=fn;e.disabled=disabled;return e;},act:(type,params)=>{spy.actions.push({type,params});return r.action(type,params);},say:text=>spy.messages.push(text),parseUI:(s,f={})=>{try{return JSON.parse(s)}catch{return f}},displayText:x=>x,routeName:x=>x,meter:()=>{},panel:()=>new Element('section'),updateQuick:()=>{},enforceExposure:()=>{},applySettings:()=>{},showModal:()=>{},
  battlePrepare:()=>{},chapterActions:()=>{},safeName:(table,id,col=1)=>r.tables[table]?.get(id)?.[col]||id,combat:()=>{},story:()=>{},begin:async()=>{spy.begins++;},loadSlot:async()=>{},manualSave:async()=>{},slotsUI:async()=>{},system:()=>{},inventory:p=>p.append(new Element('button','','장착')),quests:p=>p.append(new Element('button','','의뢰 수행')),reward:()=>{},render:()=>{spy.renders++;},saveStore:{save:async()=>{spy.saves++;return{slotRevision:spy.saves};}}
 });
 let text=fs.readFileSync(path.join(source,'app_revision.js'),'utf8');hashes['app_revision.js']=crypto.createHash('sha256').update(text).digest('hex');
 text=text.replace(/^boot\(\);\s*$/m,'\n/* boot suppressed only in this isolated test harness */\n');
 vm.runInContext(text,u,{filename:'app_revision.js'});return{u,spy,wordmark};
}

(async()=>{
await test('story: world menus, direct move, wait and treasure actions reject atomically',()=>{const r=fresh();for(const screen of ['LOCATION','SHOP','CRAFT','BOSS_INTRO'])blocked(r,'MENU',{screen});blocked(r,'MOVE',{edge:'EDGE_MOND_FOREST_TO_CITY'});blocked(r,'WAIT',{minutes:60});blocked(r,'QUEST_CHOICE',{quest:'Q_MOND_EXP_PLAINS_CART',choice:'careful'});blocked(r,'CLAIM_QUEST',{quest:'Q_MOND_EXP_PLAINS_CART'});return overview(r);});
await test('story: read-only inventory opens but mutation and hidden story advance do not',()=>{const r=fresh(),node=r.storyNode()[4];r.action('MENU',{screen:'INVENTORY'});blocked(r,'EQUIP',{slot:'not-relevant'});blocked(r,'STORY_NEXT',{node});r.action('MENU',{screen:'STORY'});assert.equal(r.storyActiveNodeId(),node);r.action('STORY_NEXT',{node});assert.notEqual(r.storyActiveNodeId(),node);assert.equal(r.s.storyMenuFrame,null);});
await test('story: save menu roundtrip preserves cursor, pending choice and physical map',()=>{const r=fresh(),choice=r.storyIndex().byTable['55_MAIN_STORY_DB'].find(x=>x[0]==='ROUTE_TRAVELER'&&x[5]==='CHOICE');goto(r,'CHOICE_GROUP:'+choice[14]);const before=overview(r),pending=r.s.global.PENDING_INPUT_JSON;r.action('MENU',{screen:'SYSTEM'});blocked(r,'STORY_CHOICE',{node:r.storyChoices()[0][4]});r.action('MENU',{screen:'STORY'});assert.equal(r.storyActiveNodeId(),before.node);assert.equal(r.s.global.PENDING_INPUT_JSON,pending);assert.equal(r.s.global.CURRENT_MAP_ID,before.map);});
await test('locked: outer economy/passive/relationship wrappers cannot bypass the transaction gate',()=>{const r=fresh();r.s.global.STORY_MENU_POLICY='SAVE_LOAD_ONLY';r.s.global.PLAYER_HP_CURRENT-=20;r.giveItem('FOOD_HASH_BROWN',2);for(const [type,params]of [['USE_ITEM',{item:'FOOD_HASH_BROWN'}],['MEAL_BATCH',{meals:[{item:'FOOD_HASH_BROWN',owner:'PLAYER_CUSTOM'}]}],['TOOL_PREPARE',{items:[]}],['CRAFT',{recipe:'irrelevant'}],['PARTY_REMOVE',{slot:2}],['PARTY_REPLACE',{slot:2,char:'MOND_AMBER'}],['PARTY_TACTIC',{slot:2,tactic:'균형'}],['RELATION_ACTIVITY',{activityId:'irrelevant'}],['WAIT',{minutes:60}]])blocked(r,type,params);r.action('MENU',{screen:'SYSTEM'});r.action('MENU',{screen:'STORY'});return overview(r);});
await test('locked: authored next-chapter explicit resume remains allowed',()=>{const r=knownPause('ISK_M03_K_060');assert.equal(r.playPhase(),'STORY_LOCKED');blocked(r,'WAIT',{minutes:60});assert.equal(r.actionReason('STORY_RESUME'),'',`authored resume was blocked at ${JSON.stringify(overview(r))}`);r.action('STORY_RESUME');assert.notEqual(r.storyActiveNodeId(),'ISK_M03_K_060');assert.equal(r.s.global.STORY_MENU_POLICY,'');assert.equal(r.s.storyResumeReceipts.ISK_M04_K_001.from,'ISK_M03_K_060');return overview(r);});
await test('waiting: stray wait flag never unlocks an unresolved narrative or pause',()=>{const r=fresh();r.s.global.STORY_WAITING=true;assert.equal(r.playPhase(),'STORY');blocked(r,'WAIT',{minutes:60});const pause=goto(fresh('ROUTE_ISEKAI'),'ISK_M02_K_GATE');pause.s.global.STORY_WAITING=true;pause.s.global.STORY_NEXT_PREPARED=pause.storyNode()[13];assert.equal(pause.playPhase(),'STORY');blocked(pause,'STORY_RESUME');});
await test('menus: save/load/settings aliases normalize and do not change story context',()=>{const r=fresh(),initial=overview(r);r.s.global.STORY_MENU_POLICY='SAVE_LOAD_ONLY';for(const screen of ['SAVE','LOAD','SETTINGS']){r.action('MENU',{screen});assert.equal(r.s.global.SCREEN_MODE,'SYSTEM');r.action('MENU',{screen:'STORY'});assert.equal(r.storyActiveNodeId(),initial.node);assert.equal(r.s.global.CURRENT_MAP_ID,initial.map);}blocked(r,'MENU',{screen:'HUB'});blocked(r,'MENU',{screen:'MAIN_MENU'});});
await test('transaction: duplicate receipt remains stable after context changes; stale revision rejects',()=>{const r=fresh(),node=r.storyNode()[4],g=r.s.global,a={id:g.SAVE_ID+':1',revision:g.SAVE_REVISION,type:'STORY_NEXT',node};const receipt=r.transact(a);r.s.global.STORY_MENU_POLICY='SAVE_LOAD_ONLY';const before=r.serialize();assert.equal(JSON.stringify(r.transact(a)),JSON.stringify(receipt));assert.equal(r.serialize(),before);const stale={...a,id:g.SAVE_ID+':2',revision:0,node:r.storyNode()[4]};assert.throws(()=>r.transact(stale),{code:'STALE_ACTION'});assert.equal(r.serialize(),before);});
await test('input: changing the startup name rejects without consuming anything',()=>{const r=goto(fresh('ROUTE_ISEKAI'),'ISK_M01_NAME_INPUT');blocked(r,'STORY_NAME',{name:'다른이름'},'NAME_FIXED');r.action('STORY_NAME',{name:r.s.global.PLAYER_NAME});assert.equal(r.s.flags.FLAG_ISK_NAME_SET,true);assert.equal(r.s.global.PLAYER_NAME,'고정된이름');});
await test('input: generic STORY_NEXT cannot replace explicit fixed-name confirmation',()=>{const r=goto(fresh('ROUTE_ISEKAI'),'ISK_M01_NAME_INPUT');blocked(r,'STORY_NEXT',{node:'ISK_M01_NAME_INPUT'},null);});
await test('prep: world movement, exploration and other story entry reject; inventory tools remain usable',()=>{const r=prep();blocked(r,'MENU',{screen:'LOCATION'});blocked(r,'MOVE',{edge:'EDGE_MOND_PLAINS_TO_CITY'});blocked(r,'QUEST_CHOICE',{quest:'Q_MOND_EXP_PLAINS_CART',choice:'careful'});blocked(r,'CLAIM_QUEST',{quest:'Q_MOND_EXP_PLAINS_CART'});blocked(r,'LEGEND_ENTER',{quest:'LEG_ISK_MOND_AMBER'});r.action('MENU',{screen:'INVENTORY'});r.action('TOOL_PREPARE',{items:[]});r.action('MENU',{screen:'STORY'});assert.equal(r.s.global.SCREEN_MODE,'COMBAT_PREP');assert.ok(r.s.battlePreparation);return overview(r);});
await test('prep: serialize/load keeps preparation and correct return from SYSTEM',()=>{const r=prep();r.action('MENU',{screen:'SYSTEM'});const resumed=new Runtime(db,JSON.parse(r.serialize()));assert.equal(resumed.playPhase(),'PREPARATION');resumed.action('MENU',{screen:'STORY'});assert.equal(resumed.s.global.SCREEN_MODE,'COMBAT_PREP');assert.equal(resumed.s.battlePreparation.group,r.s.battlePreparation.group);});
await test('general story battle: preparation exposes owned selection and rejects world-action bypass',()=>{const r=goto(fresh(),'TRV_M02_N123');r.action('STORY_NEXT',{node:'TRV_M02_N123'});assert.equal(r.playPhase(),'PREPARATION');assert.equal(r.battlePreparation(r.s.battlePreparation.group).guests.length,0);blocked(r,'WAIT',{minutes:60});blocked(r,'MOVE',{edge:'EDGE_MOND_CITY_TO_PLAINS'});r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});assert.equal(r.playPhase(),'COMBAT_OPENING');r.action('COMBAT_BEGIN',{battle:r.s.runtime.id});assert.equal(r.playPhase(),'COMBAT');assert.ok(r.s.storyBattleCheckpoint);});
await test('defeat: checkpoint retry restores complete gameplay state while action revisions stay monotonic',()=>{let r=goto(fresh(),'TRV_M02_N123');r.action('STORY_NEXT',{node:'TRV_M02_N123'});r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});r.action('COMBAT_BEGIN',{battle:r.s.runtime.id});const checkpoint=copy(r.s.storyBattleCheckpoint);let turns=0;while(r.s.runtime){r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});assert.ok(++turns<100);}assert.equal(r.playPhase(),'RECOVERY');assert.equal(r.s.global.PLAYER_HP_CURRENT,0);for(const [type,params]of [['WAIT',{minutes:60}],['MENU',{screen:'LOCATION'}],['PARTY',{char:'MOND_AMBER',slot:2}],['STORY_NEXT',{node:'TRV_M02_N123'}]])blocked(r,type,params);assert.ok(r.actionReason('TITLE'));r.action('MENU',{screen:'SYSTEM'});r=new Runtime(db,JSON.parse(r.serialize()));const before=copy(r.s.global),action={id:before.SAVE_ID+':'+(before.LAST_COMMITTED_ACTION_SEQ+1),revision:before.SAVE_REVISION,type:'STORY_RETRY'},receipt=r.transact(action);assert.equal(r.playPhase(),'PREPARATION');assert.equal(r.s.global.SAVE_REVISION,before.SAVE_REVISION+1);assert.equal(r.s.global.LAST_COMMITTED_ACTION_SEQ,before.LAST_COMMITTED_ACTION_SEQ+1);assert.equal(r.s.global.TURN,before.TURN+1);const actual=copy(r.s);for(const key of ['SAVE_REVISION','LAST_COMMITTED_ACTION_SEQ','LAST_COMMITTED_ACTION_ID','LAST_ACTION_RECEIPT_JSON','TURN']){delete checkpoint.global[key];delete actual.global[key];}assert.deepEqual(actual,checkpoint);const stable=r.serialize();assert.deepEqual(copy(r.transact(action)),copy(receipt));assert.equal(r.serialize(),stable);r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});assert.equal(r.playPhase(),'COMBAT_OPENING');r.action('COMBAT_BEGIN',{battle:r.s.runtime.id});assert.equal(r.playPhase(),'COMBAT');return{actualDefeatTurns:turns,retryRevision:r.s.global.SAVE_REVISION};});
await test('cutin: direct public return and combat commands cannot skip unresolved authored text',()=>{const r=cutin(),before=copy(r.s.runtime.interludeSeen);blocked(r,'STORY_RETURN');blocked(r,'COMBAT',{card:'PLAYER_BASIC_GUARD'});blocked(r,'WAIT',{minutes:60});assert.deepEqual(copy(r.s.runtime.interludeSeen),before);return overview(r);});
await test('cutin: save/load and all actual authored choices still return normally to the battle',()=>{let r=cutin();const scenes=new Set();let turns=0;while(r.s.runtime?.interlude){scenes.add(r.s.runtime.interlude.scene_id);r.action('MENU',{screen:'SYSTEM'});const loaded=new Runtime(db,JSON.parse(r.serialize()));assert.equal(loaded.storyActiveNodeId(),r.storyActiveNodeId());r=loaded;r.action('MENU',{screen:'STORY'});const choices=r.storyChoices();if(choices.length)r.action('STORY_CHOICE',{node:choices[0][4]});else r.action('STORY_NEXT',{node:r.storyNode()[4]});if(++turns>30)throw Error('cutin did not end');}assert.equal(scenes.size,2);assert.equal(r.playPhase(),'COMBAT');assert.ok(r.s.runtime.subduedPending);return{authoredSteps:turns,scenes:[...scenes]};});
await test('free: authored menu gate permits exploration while return does not teleport',()=>{const r=freeHub();assert.equal(r.playPhase(),'FREE');registerAtGuild(r,'COMMISSION_ACCEPT','Q_MOND_EXP_PLAINS_CART');r.action('MENU',{screen:'LOCATION'});r.action('MOVE',{edge:'EDGE_MOND_CITY_TO_PLAINS'});const moved=r.s.global.CURRENT_MAP_ID;r.action('MENU',{screen:'STORY'});assert.equal(r.s.global.CURRENT_MAP_ID,moved);assert.equal(r.playPhase(),'FREE');r.action('QUEST_CHOICE',{quest:'Q_MOND_EXP_PLAINS_CART',choice:'careful'});r.action('CLAIM_QUEST',{quest:'Q_MOND_EXP_PLAINS_CART'});assert.equal(r.s.quests.Q_MOND_EXP_PLAINS_CART.claimed,true);return overview(r);});
await test('personal: entering from free quest menu does not inherit a stale main menu frame',()=>{const r=freeHub();r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;registerAtGuild(r,'LEGEND_REGISTER','LEG_MOND_ALBEDO');r.action('MENU',{screen:'QUEST'});r.action('LEGEND_ENTER',{quest:'LEG_MOND_ALBEDO'});const node=r.storyActiveNodeId(),main=r.s.global.STORY_CURSOR_NODE_ID;r.action('MENU',{screen:'INVENTORY'});blocked(r,'WAIT',{minutes:60});r.action('MENU',{screen:'STORY'});assert.equal(r.storyActiveNodeId(),node);assert.equal(r.s.global.STORY_CURSOR_NODE_ID,main);assert.equal(r.s.storyContext.kind,'LEGEND');assert.equal(r.s.storyReturnStack.length,1);return overview(r);});
await test('free pause: personal return preserves the previous free wait phase and prepared continuation',()=>{const r=knownPause();const main=r.storyActiveNodeId(),next=r.s.global.STORY_NEXT_PREPARED;assert.equal(r.playPhase(),'FREE');registerAtGuild(r,'LEGEND_REGISTER','LEG_ISK_MOND_AMBER');r.action('LEGEND_ENTER',{quest:'LEG_ISK_MOND_AMBER'});let steps=0;while(r.s.storyContext&&steps++<50){const choices=r.storyChoices();if(choices.length){const leave=choices.find(x=>String(x[12]).includes('NO_COST_NO_PROGRESS'))||choices[0];r.action('STORY_CHOICE',{node:leave[4]});}else r.action('STORY_NEXT',{node:r.storyNode()[4]});}assert.equal(r.s.storyContext,null);assert.equal(r.storyActiveNodeId(),main);assert.equal(r.s.global.STORY_NEXT_PREPARED,next);assert.equal(r.playPhase(),'FREE',`normal pause lost free permission: ${JSON.stringify(overview(r))}`);return{steps,...overview(r)};});
await test('UI: title button policy prevents abandoning story and allows a free checkpoint',async()=>{const locked=uiHarness(fresh());await locked.u.fresh();assert.ok(locked.u.game);assert.equal(locked.spy.saves,0);assert.ok(locked.spy.messages.length);await locked.u.begin('다른이름','ROUTE_TRAVELER');assert.equal(locked.spy.begins,0);const free=uiHarness(freeHub());await free.u.fresh();assert.equal(free.u.game,null);assert.equal(free.spy.saves,1);return{storyReason:locked.spy.messages[0],freeSaved:free.spy.saves};});
await test('UI: fixed-name node has no editable field and confirms the original startup name',()=>{const r=goto(fresh('ROUTE_ISEKAI'),'ISK_M01_NAME_INPUT'),{u,spy}=uiHarness(r),p=new Element('section');u.story(p,{node:r.storyNode()});assert.equal(p.querySelectorAll('input').length,0);const confirm=p.querySelectorAll('button')[0];assert.ok(confirm);assert.equal(confirm.disabled,false);confirm.onclick();assert.equal(spy.actions[0].type,'STORY_NAME');assert.equal(spy.actions[0].params.name,'고정된이름');assert.equal(r.s.flags.FLAG_ISK_NAME_SET,true);});
await test('UI: inspect-only inventory and quests disable all mutation buttons during story',()=>{const {u}=uiHarness(fresh()),inv=new Element('section'),quests=new Element('section');u.inventory(inv);u.quests(quests,{});assert.ok(inv.querySelectorAll('button').every(b=>b.disabled));assert.ok(quests.querySelectorAll('button').every(b=>b.disabled));});
await test('UI: XP meter shows numerical progress and handles maximum level',()=>{const r=fresh(),{u}=uiHarness(r),p=new Element('section');u.xpMeter(p);const bar=p.querySelector('progress');assert.ok(bar);assert.equal(bar.value,0);assert.equal(bar.max,Number(r.row('26_LEVEL_RULES',1)[2]));r.s.global.PLAYER_LEVEL_STATE=20;r.s.global.PLAYER_XP_STATE=0;const max=new Element('section');u.xpMeter(max);assert.equal(max.querySelectorAll('progress').length,0);assert.match(max.textContent,/최대 레벨/);});
const summary={source,dataPath,loaded,sourceHashes:hashes,total:results.length,passed:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length,results};
console.log(JSON.stringify(summary,null,2));if(summary.failed)process.exitCode=1;
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
