'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),db=JSON.parse(fs.readFileSync(path.join(root,'content/db.json'),'utf8')),files=[...fs.readFileSync(path.join(root,'source/index.html'),'utf8').matchAll(/<script src="((?:world_content|runtime[^" ]*)\.js)"/g)].map(x=>x[1]);
let clock=Date.now();function load(omit){const c=vm.createContext({console,Date:class extends Date{static now(){return clock;}},setTimeout,clearTimeout});for(const f of files)if(!omit||f!=='runtime_encounter.js')vm.runInContext(fs.readFileSync(path.join(root,'source',f),'utf8'),c,{filename:f});return c.CRPGRuntime.Runtime;}
const Base=load(true),Candidate=load(false),copy=x=>JSON.parse(JSON.stringify(x)),results=[];
function fresh(R,map='MAP_MOND_PLAINS'){const r=new R(db);r.newGame({name:'검증',route:'ROUTE_TRAVELER',seed:71247,saveId:'ENCOUNTER-AUDIT'});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,STORY_MENU_POLICY:'',WORLD_TIME:'12:00',MORA:3000,ENCOUNTER_COOLDOWN:0});delete r.s.storyJourney;delete r.s.storyBreak;r.prepareStory();return r;}
function check(name,setup,expectedKind,expectedLabel){try{const a=fresh(Base),b=fresh(Candidate);setup(a);setup(b);assert(a.s.runtime&&b.s.runtime);assert.equal(b.s.runtime.opening.state,'PENDING');const raw=copy(b.s),other=copy(a.s);delete raw.runtime.encounter;assert.deepEqual(raw,other,'encounter module must change descriptive metadata only');assert.equal(b.s.runtime.encounter.kind,expectedKind);if(expectedLabel)assert.equal(b.s.runtime.encounter.label,expectedLabel);const before=b.serialize();b.random=()=>{throw Error('description consumed RNG');};b.die=()=>{throw Error('description rolled dice');};for(let i=0;i<3;i++){const opening=b.combatOpening();assert(opening.pending);assert(opening.encounter.text);b.describeEncounter(b.s.runtime);}assert.equal(b.serialize(),before,'opening view mutates state');const restored=new Candidate(db,JSON.parse(before));assert.equal(restored.s.runtime.opening.state,'PENDING');results.push({name,ok:true,context:b.s.runtime.encounter});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
check('explicit field opening has zero extra RNG, HP or turn effects',r=>r.startBattle('EG_MOND_SLIME_SMALL','RANDOM'),'FIELD');
check('waiting encounter carries context without extra RNG, HP or turn effects',r=>{r.die=()=>1;r.action('WAIT',{minutes:60});},'FIELD','주변의 적과 조우');
check('movement encounter describes arrival without extra RNG, HP or turn effects',r=>{r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';const edge=r.view().edges.find(e=>e.row[2]==='MAP_MOND_PLAINS'&&!e.reason);assert(edge);r.die=()=>1;r.action('MOVE',{edge:edge.row[0]});},'FIELD','이동 중 조우');
check('hunting encounter preserves earned materials and pre-start HP',r=>{r.s.global.CURRENT_MAP_ID='MAP_CRPG_WHISPER_HUNT';r.action('LIFE_START',{kind:'HUNT'});r.s.lifeJob.startedAt=clock-10000;r.die=()=>1;r.action('LIFE_FINISH',{job:r.s.lifeJob.id});},'FIELD','탐색 중 조우');
check('story temple explanation preserves original opening state',r=>{r.s.global.CURRENT_MAP_ID='MAP_MOND_FOREST';const row=r.storyIndex().byTable['55_MAIN_STORY_DB'].find(x=>x[0]==='ROUTE_TRAVELER'&&x[5]==='COMBAT_GATE'&&String(x[12]).includes('EG_TRV_FALCON_WAVE'));assert(row);Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:row[4],STORY_CURSOR_NODE_ID:row[4],CURRENT_MAP_ID:row[8],SCREEN_MODE:'STORY',STORY_WAITING:false});r.prepareStory();r.action('STORY_NEXT',{node:row[4]});r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});},'STORY','이야기 속 전투');
const report={total:results.length,passed:results.filter(r=>r.ok).length,comparison:'current full runtime with and without runtime_encounter.js; saved states equal except runtime.encounter',results};fs.writeFileSync(path.join(__dirname,'../reports/encounter-context-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({total:report.total,passed:report.passed}));if(report.passed!==report.total)process.exitCode=1;
