'use strict';
// 0.16.16: the 0.16.15 material-combat budget is retired. This historical test
// filename stays in the existing release manifest; native baseline and already
// started 0.16.15 battles are checked rather than re-creating the rejected tuning.
const assert=require('node:assert/strict'),crypto=require('node:crypto');
const {R,db,c}=require('./helpers_v011.cjs');
const {setup,G,PLAYER}=require('../tools/audit_balance_v01522.cjs');
const {REFERENCE_TEAM}=require('../tools/audit_balance_v0161.cjs');
const fixture=require('./fixtures/material_native_v01614.json');
const copy=x=>JSON.parse(JSON.stringify(x));let checks=0;
function check(name,run){run();checks++;console.log('PASS '+name);}
function prepare(domain='LIANSHAN_FORMULA:60',element='HYDRO',options={}){const spec=G.domains[domain.split(':')[0]],r=setup({level:55,route:'ROUTE_TRAVELER',team:REFERENCE_TEAM,map:spec.map,gear:'craft',enhance:6,talent:'mid',...options});r.s.domainDaily={day:G.dayOf(r.leyLineNow()),wins:3};r.s.global.PRNG_STATE=717;return {r,domain,element};}
function start(domain,element,options){const x=prepare(domain,element,options);x.r.action('DOMAIN_START',{domain:x.domain,element:x.element});return x.r;}
const enemyStats=r=>copy([...r.s.runtime.actors,...(r.s.runtime.enemyReserve||[])].filter(a=>a.side==='ENEMY').map(a=>({source:a.source,hp:a.hp,maxHp:a.maxHp,atk:a.atk,def:a.def,spd:a.spd,hit:a.hit,grade:a.grade,level:a.level,shields:a.shields,enemySkills:a.enemySkills})));
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
function legacyBattle(){const r=start(),s=copy(r.s);s.runtime=copy(fixture.legacyRuntime);s.global.ACTIVE_BATTLE_ID=s.runtime.id;return new R(db,s);}
check('new material fights use native fixed-four scaling without a material override',()=>{const r=start(),b=r.s.runtime;assert.equal(b.materialBudget,undefined);assert.equal(b.growthDomain.materialBudgetVersion,undefined);assert.equal(r.tuneMaterialDomain,undefined);assert.equal(c.CRPGRuntime.growthV01522.materialBudgetVersion,undefined);assert.equal(b.actors.filter(a=>a.side==='ENEMY').reduce((n,a)=>n+a.maxHp,0),182413);assert(b.actors.find(a=>a.source==='MON_ABYSS_MAGE_HYDRO').enemySkillsInitialized);});
check('all material stages/elements and one/four-person routes match the pinned 0.16.14 native enemies',()=>{assert.equal(fixture.nativeRelease,'443d4a2e8b8959ce15a13e7cca4a5e87863e26f8');assert.equal(fixture.probes.length,216);const templates=new Map();for(const p of fixture.probes){const key=p.domain.split(':')[0]+':'+p.scenario;if(!templates.has(key))templates.set(key,prepare(p.domain,p.element,p.scenario==='one-isekai'?{route:'ROUTE_ISEKAI',team:[]}:{}).r);const template=templates.get(key),r=Object.create(template);r.s=copy(template.s);r.action('DOMAIN_START',{domain:p.domain,element:p.element});assert.equal(hash(enemyStats(r)),p.hash,p.domain+' '+p.element+' '+p.scenario);assert.equal(r.s.runtime.materialBudget,undefined);assert.equal(r.s.runtime.growthDomain.materialBudgetVersion,undefined);}});
check('fresh native material fights reload without HP, shield, order or reward changes',()=>{const r=start(),a=r.s.runtime.actors.find(a=>a.side==='ENEMY');a.hp=Math.floor(a.hp*.7);for(const shield of a.shields||[])shield.value=Math.floor(shield.value*.6);const before=copy(r.s.runtime),loaded=new R(db,copy(r.s));assert.deepEqual(copy(loaded.s.runtime),before);assert.deepEqual(copy(new R(db,copy(loaded.s)).s.runtime),before);});
check('the actual saved 0.16.15 fight retains its tuned HP/ATK, damage, shields and turn state',()=>{assert.equal(fixture.legacyRelease,'4e56987f9c357d8a7471e61adf4153d3da72ca6e');assert.equal(fixture.legacyGrowthSourceSha256,'7aec037900c70d89382d1474d340a80a14c02986c6336e8a542cd7a62caffd1c');const r=legacyBattle();assert.deepEqual(copy(r.s.runtime),fixture.legacyRuntime);assert.equal(r.s.runtime.growthDomain.materialBudgetVersion,1);assert.deepEqual(copy(r.s.runtime.materialBudget),{version:1,durability:48000,pressure:6920});assert.deepEqual(copy(new R(db,copy(r.s)).s.runtime),fixture.legacyRuntime);});
check('a saved 0.16.15 fight pays its original 32 gems once; its next new fight uses native difficulty',()=>{const r=legacyBattle();assert.equal(r.growthDomainRewards(r.s.runtime.growthDomain,'HYDRO').items.GROWTH_GEM_HYDRO,32);for(const a of r.s.runtime.actors.filter(a=>a.side==='ENEMY'))a.hp=0;const out=r.finishBattle(true);assert.equal(out.domain.items.GROWTH_GEM_HYDRO,32);const saved=r.serialize();r.finishBattle(true);assert.equal(r.serialize(),saved);r.action('DOMAIN_START',{domain:'LIANSHAN_FORMULA:60',element:'HYDRO'});assert.equal(r.s.runtime.materialBudget,undefined);assert.equal(r.s.runtime.growthDomain.materialBudgetVersion,undefined);assert.equal(r.s.runtime.actors.filter(a=>a.side==='ENEMY').reduce((n,a)=>n+a.maxHp,0),182413);});
check('old native version-4 stats and 12-gem promises stay untouched',()=>{const r=start();r.s.runtime.growthDomain.ascensionRewardVersion=0;const before=copy(r.s.runtime),loaded=new R(db,copy(r.s));assert.deepEqual(copy(loaded.s.runtime),before);assert.equal(loaded.growthDomainRewards(loaded.s.runtime.growthDomain,'HYDRO').items.GROWTH_GEM_HYDRO,12);});
check('legacy versions 1, 2 and 3 keep native enemies and never acquire retired budgets',()=>{const plans=[{id:'TALENT:10',kind:'TALENT',level:10,region:'몬드',map:'MAP_MOND_CITY',element:'NEUTRAL',day:0},{version:2,id:'FORSAKEN_RIFT:2',key:'FORSAKEN_RIFT',stage:2,kind:'TALENT',level:10,region:'몬드',map:'MAP_MOND_SPRINGVALE',element:'NEUTRAL',day:0},{version:3,id:'FORSAKEN_RIFT:TALENT',key:'FORSAKEN_RIFT',name:'잊혀진 협곡',kind:'TALENT',level:5,region:'몬드',map:'MAP_MOND_SPRINGVALE',element:'NEUTRAL',day:0}];for(const d of plans){const {r}=prepare('FORSAKEN_RIFT:10');r._growthDomain=d;r.startBattle(r.growthDomainGroup(d,'NEUTRAL'),'DOMAIN:'+d.id);delete r._growthDomain;const before=copy(r.s.runtime);assert.equal(before.materialBudget,undefined);assert.deepEqual(copy(new R(db,copy(r.s)).s.runtime),before);}});
check('EXP and ordinary field enemies stay outside material-budget history',()=>{const exp=start('MIDSUMMER_COURTYARD:10');assert.equal(exp.s.runtime.materialBudget,undefined);assert.equal(exp.s.runtime.growthDomain.materialBudgetVersion,undefined);assert.equal(exp.s.runtime.actors.filter(a=>a.side==='ENEMY').reduce((n,a)=>n+a.maxHp,0),11200);const r=setup({level:55,team:REFERENCE_TEAM,map:'MAP_LIYUE_PLAINS'});r.startBattle('EG_LIYUE_HILI_ROCK','RANDOM');assert.equal(r.s.runtime.materialBudget,undefined);assert.equal(r.s.runtime.growthDomain,undefined);});
check('forged, missing and misplaced legacy budget markers are still rejected',()=>{const r=legacyBattle();for(const mutate of [s=>s.runtime.growthDomain.materialBudgetVersion=2,s=>delete s.runtime.materialBudget,s=>s.runtime.materialBudget.pressure=1,s=>delete s.runtime.growthDomain.materialBudgetVersion,s=>s.runtime.materialBudget.version=2]){const saved=copy(r.s);mutate(saved);assert.throws(()=>new R(db,saved),/재료 비경/);}const exp=start('MIDSUMMER_COURTYARD:10'),saved=copy(exp.s);saved.runtime.growthDomain.materialBudgetVersion=1;saved.runtime.materialBudget={version:1,durability:5800,pressure:730};assert.throws(()=>new R(db,saved),/재료 비경/);const field=setup({level:55,team:REFERENCE_TEAM,map:'MAP_LIYUE_PLAINS'});field.startBattle('EG_LIYUE_HILI_ROCK','RANDOM');const wrong=copy(field.s);wrong.runtime.materialBudget={version:1,durability:46000,pressure:6630};assert.throws(()=>new R(db,wrong),/재료 비경/);});
console.log(JSON.stringify({checks,nativeStartProbes:fixture.probes.length,ok:true}));
