// Native account-server integration, including identity, CAS, battle pinning,
// receipt replay, a second independent server and an actual SQLite restart.
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {startLiveRegionStaging} from '../server/fixed-region-live.mjs';
import {consoleSecret} from '../server/admin-console-setup.mjs';
import {R,DB,ENGINE_FINGERPRINT} from '../server/generated/engine.mjs';
import {splitState,joinState} from '../server/state-parts.mjs';

const pepper='admin-balance-integration-pepper-'.padEnd(64,'p'),password='balance-game-password',consolePassword='balance-console-password';
const secret=await consoleSecret(consolePassword,pepper),dir=await mkdtemp(join(tmpdir(),'crpg-balance-')),dbPath=join(dir,'balance.sqlite3');
let checks=0;const check=(value,message)=>{assert(value,message);checks++;};
const clone=x=>structuredClone(x),empty=()=>globalThis.CRPGRuntime.adminBalance.emptyConfig();
let app,second;
async function open(path=dbPath){
 const s=await startLiveRegionStaging({dbPath:path,pepper,host:'127.0.0.1',port:0,features:['chat','trade','coop'],adminConsoleId:'BALANCE',adminConsoleHash:secret});
 const base='http://127.0.0.1:'+s.address.port;
 async function api(path,{body,token,admin}={}){const headers={};if(token)headers.authorization='Bearer '+token;if(admin)headers.authorization='Admin '+admin;if(body!==undefined)headers['content-type']='application/json';const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});return{status:response.status,json:await response.json()};}
 return{...s,base,api};
}
function writeState(store,id,state){const parts=splitState(state);store.db.prepare('DELETE FROM parts WHERE account_id=?').run(id);const stmt=store.db.prepare('INSERT INTO parts VALUES(?,?,?)');for(const[path,value]of parts)stmt.run(id,path,value);store.invalidate(id);}
function free(r){Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:'MAP_MOND_CITY',STORY_MENU_POLICY:'',SCREEN_MODE:'LOCATION'});delete r.s.storyJourney;delete r.s.storyBreak;r.s.storyContext=null;r.prepareStory?.();return r;}
try{
 check(!!globalThis.CRPGRuntime.adminBalance,'fresh generated engine includes the shared balance implementation');
 app=await open();
 check((await app.api('/admin/balance')).status===401,'balance catalog requires the separate operator login');
 check((await app.api('/admin/balance/apply',{body:{expectedRevision:0,config:empty()}})).status===401,'no anonymous edits');
 check((await app.api('/balance')).status===401,'the game profile endpoint requires a game login');
 const login=await app.api('/admin/login',{body:{id:'BALANCE',password:consolePassword}});check(login.status===200,'operator login');const admin=login.json.token;
 const reg=await app.api('/register',{body:{username:'balance_player',password}});check(reg.status===200,'game login');const token=reg.json.token,id=reg.json.account.id;
 check((await app.api('/admin/balance',{token})).status===401,'a game session cannot edit server balance');
 check((await app.api('/balance',{admin})).status===401,'an operator session cannot impersonate a game account');
 const created=await app.api('/game/new',{token,body:{name:'수치 검사',route:'ROUTE_TRAVELER'}});check(created.status===200,'legacy new-game payload remains valid at identity revision');check(created.json.balance.revision===0,'new game returns its exact balance revision');
 const baseline=new R(DB);baseline.newGame({name:'동일 규칙',route:'ROUTE_TRAVELER',saveId:'BALANCE-IDENTITY',seed:717});const identity=globalThis.CRPGRuntime.adminBalance.createRuntime(DB,null,{revision:0,config:empty()});identity.newGame({name:'동일 규칙',route:'ROUTE_TRAVELER',saveId:'BALANCE-IDENTITY',seed:717});check(JSON.stringify(identity.s)===JSON.stringify(baseline.s),'empty profile retains native game state exactly');
 const sourceBefore=JSON.stringify(DB),savedBefore=JSON.stringify(joinState(app.store.loadParts(id))),auditBefore=app.store.db.prepare('SELECT COUNT(*) AS n FROM admin_audit').get().n;
 const current=await app.api('/admin/balance',{admin});check(current.status===200&&current.json.revision===0,'initial profile and catalog');const catalog=current.json.catalog;check(catalog.enemies.length>0&&catalog.characters.length>0&&catalog.cards.length>0&&catalog.tables.length>0&&catalog.encounters.length>0,'all supported balance categories are populated');
 const r=free(app.store.runtimeOf(id));r.adminApply({op:'level',target:'PLAYER_CUSTOM',value:10});const service=r.rows('19_SHOP_STOCK_DB').find(row=>row[2]==='SERVICE'&&r.innRecoveryQuote(row));check(!!service,'actual lodging service exists');r.s.global.PLAYER_HP_CURRENT=Math.max(1,Math.floor(r.s.global.PLAYER_HP_MAX/2));writeState(app.store,id,r.s);const baseQuote=app.store.runtimeOf(id).innRecoveryQuote(service);
 const ordinary=catalog.enemies.find(e=>e.id==='MON_SLIME_HYDRO')||catalog.enemies.find(e=>e.id.startsWith('MON_SLIME_'));check(!!ordinary,'ordinary monster catalog');
 const group=catalog.encounters.find(e=>e.members.length&&e.members.every(m=>r.tables['09_MONSTER_DB'].get(m.monster)?.[3]!=='보스'));check(!!group,'ordinary existing encounter');
 const stock=catalog.tables.find(row=>row.table==='19_SHOP_STOCK_DB'&&row.fields.some(f=>f.key===5)&&r.tables['19_SHOP_STOCK_DB'].get(row.id)?.[2]==='ITEM');check(!!stock,'actual editable item stock');
 const config=empty();config.economy.innMultiplier=2;config.enemies[ordinary.id]={level:10,hp:54321,atk:789,def:456};config.encounters[group.id]=[{monster:ordinary.id,min:2,max:2}];config.tables.push({table:stock.table,id:stock.id,column:5,value:1234});
 const stateBeforePreview=JSON.stringify(joinState(app.store.loadParts(id))),preview=await app.api('/admin/balance/preview',{admin,body:{expectedRevision:0,config}});check(preview.status===200&&preview.json.changes.length>=7,'preview lists concrete numeric changes');check(app.store.balance.currentRevision()===0&&app.store.db.prepare('SELECT COUNT(*) AS n FROM balance_profiles').get().n===1,'preview creates no profile');check(JSON.stringify(joinState(app.store.loadParts(id)))===stateBeforePreview&&app.store.db.prepare('SELECT COUNT(*) AS n FROM admin_audit').get().n===auditBefore,'preview modifies neither player save nor audit state');
 const invalids=[{...empty(),enemies:{NO_SUCH_ENEMY:{hp:1}}},{...empty(),economy:{innMultiplier:0}},{...empty(),enemies:{[ordinary.id]:{hp:1.5}}},{...empty(),characters:{PLAYER_CUSTOM:{hpMultiplier:'2'}}},{...empty(),tables:[{table:'accounts',id:'balance_player',column:1,value:2}]},{...empty(),tables:[{table:stock.table,id:stock.id,column:5,value:-1}]},{...empty(),encounters:{[group.id]:[{monster:ordinary.id,min:1,max:9}]}},{...empty(),scripts:'alert(1)'},JSON.parse('{"economy":{"__proto__":2}}')];
 for(const bad of invalids)check((await app.api('/admin/balance/apply',{admin,body:{expectedRevision:0,config:bad}})).status===400,'invalid field, identifier, type or limit is refused');check(app.store.balance.currentRevision()===0&&app.store.db.prepare('SELECT COUNT(*) AS n FROM balance_profiles').get().n===1,'invalid requests retain the current revision');
 // Keep one replayable action before the numeric revision moves.
 let me=(await app.api('/me',{token})).json;const action={engineVersion:ENGINE_FINGERPRINT,type:'MENU',params:{screen:'SYSTEM'},revision:me.revision,requestId:'balance-before-edit-0001',responseMode:'state-parts-v1'};const receipt=await app.api('/game/action',{token,body:action});check(receipt.status===200,'identity game action commits');
 const applied=await app.api('/admin/balance/apply',{admin,body:{expectedRevision:0,config,note:'테스트용 보스·비용·편성'}});check(applied.status===200&&applied.json.revision===1,'applying appends revision 1');check(app.store.db.prepare("SELECT COUNT(*) AS n FROM admin_audit WHERE op='balance-apply'").get().n===1,'balance apply is audited');check(JSON.stringify(DB)===sourceBefore,'authored global DB is unchanged');
 const quoted=app.store.runtimeOf(id).innRecoveryQuote(service);check(quoted.cost===Math.ceil(baseQuote.roomCost*2)+baseQuote.targets.reduce((n,t)=>n+Math.ceil(t.recoveryCost*2),0),'native server lodging quote applies the saved multiplier');check(app.store.runtimeOf(id).row('19_SHOP_STOCK_DB',stock.id)[5]===1234,'native server item price applies the saved table override');
 check((await app.api('/admin/balance/apply',{admin,body:{expectedRevision:0,config:empty()}})).status===409,'stale operator write is rejected');check((await app.api('/admin/balance/preview',{admin,body:{expectedRevision:0,config:empty()}})).status===409,'stale operator preview is rejected');
 const replay=await app.api('/game/action',{token,body:action});check(replay.status===200&&replay.json.replayed&&replay.json.balance.revision===1,'receipt replay precedes new-profile CAS and returns the current view');
 me=(await app.api('/me',{token})).json;check(me.balance.revision===1,'me exposes current profile outside battle');const next={...action,revision:me.revision,requestId:'balance-current-act-0001'};const rejected=await app.api('/game/action',{token,body:next});check(rejected.status===409&&rejected.json.code==='BALANCE_REVISION_CONFLICT','missing profile revision cannot commit after an edit');check((await app.api('/game/action',{token,body:{...next,expectedBalanceRevision:0}})).status===409,'a stale displayed profile cannot commit');const accepted=await app.api('/game/action',{token,body:{...next,expectedBalanceRevision:1}});check(accepted.status===200&&accepted.json.balance.revision===1,'matching profile commits and returns the profile with the state patch');
 // A fresh native fight contains the configured monsters and exact final specs.
 const guestReg=await app.api('/register',{body:{username:'balance_guest',password}}),guestToken=guestReg.json.token,guestId=guestReg.json.account.id;const newAccountView=(await app.api('/me',{token:guestToken})).json;check(newAccountView.state===null&&newAccountView.balance.revision===1,'new account without a save receives the current profile before starting');check((await app.api('/game/new',{token:guestToken,body:{name:'같은 전투',route:'ROUTE_TRAVELER'}})).status===409,'a new journey with a missing current profile is refused without creating a save');check((await app.api('/game/new',{token:guestToken,body:{name:'같은 전투',route:'ROUTE_TRAVELER',expectedBalanceRevision:1}})).status===200,'new game after an edit requires the current balance revision');const guestRuntime=free(app.store.runtimeOf(guestId));guestRuntime.adminApply({op:'level',target:'PLAYER_CUSTOM',value:10});writeState(app.store,guestId,guestRuntime.s);const hostFree=free(app.store.runtimeOf(id));writeState(app.store,id,hostFree.s);const roomOpen=await app.api('/coop/open',{token,body:{visibility:'PUBLIC'}});check(roomOpen.status===200,'actual co-op room opens');const roomId=roomOpen.json.room.id;check((await app.api('/coop/join',{token:guestToken,body:{room:roomId,char:'PLAYER_CUSTOM'}})).status===200,'actual guest joins with a server-produced profile-1 snapshot');
 const battleRuntime=free(app.store.runtimeOf(id));battleRuntime.s.global.PLAYER_HP_CURRENT=battleRuntime.s.global.PLAYER_HP_MAX;battleRuntime.startBattle(group.id,'BALANCE_NATIVE');check(battleRuntime.s.runtime.adminBalanceRevision===1,'new native battle records revision');const foes=battleRuntime.s.runtime.actors.filter(a=>a.side==='ENEMY');check(foes.length===2&&foes.every(a=>a.source===ordinary.id&&a.maxHp===54321&&a.atk===789&&a.def===456&&a.level===10),'actual encounter creation applies lineup and specs after native growth hooks');writeState(app.store,id,battleRuntime.s);
 const pinnedSave=clone(battleRuntime.s),secondConfig=empty();secondConfig.enemies[ordinary.id]={hp:11111};secondConfig.economy.innMultiplier=3;secondConfig.characters.PLAYER_CUSTOM={atkMultiplier:2};
 const changed=await app.api('/admin/balance/apply',{admin,body:{expectedRevision:1,config:secondConfig,note:'진행 중 전투 고정 검사'}});check(changed.status===200&&changed.json.revision===2,'second configuration appends revision 2');const pinned=app.store.runtimeOf(id);check(app.store.balance.runtimeRevision(pinned)===1&&pinned.s.runtime.actors.filter(a=>a.side==='ENEMY').every(a=>a.maxHp===54321),'a saved battle retains revision 1 after current revision changes');check((await app.api('/me',{token})).json.balance.revision===1,'the active fight client receives its pinned profile');const room=app.store.coopRooms().get(roomId),guestNew=app.store.runtimeOf(guestId).coopSnapshot('PLAYER_CUSTOM');check(guestNew.actor.atk===2*room.members[0].snap.actor.atk,'current guest stats reflect the new character multiplier');room.members[0].snap={...guestNew,adminBalanceRevision:2};const frozenContext=app.store.coopContextFor(id);check(frozenContext.members[0].snap.adminBalanceRevision===1&&frozenContext.members[0].snap.actor.atk===guestNew.actor.atk/2,'newly admitted guest is rebuilt under the fight profile rather than current profile');
 const legacy=clone(pinnedSave);delete legacy.runtime.adminBalanceRevision;writeState(app.store,id,legacy);check(app.store.balance.runtimeRevision(app.store.runtimeOf(id))===0&&(await app.api('/me',{token})).json.balance.revision===0,'unmarked pre-tool battle uses identity rather than the newest profile');
 // End a pinned native fight with the public forfeit transaction. Its response and
 // the next warm runtime must use the newest profile, rather than retaining 1.
 writeState(app.store,id,pinnedSave);me=(await app.api('/me',{token})).json;const forfeit={engineVersion:ENGINE_FINGERPRINT,type:'COMBAT_FORFEIT',params:{},revision:me.revision,requestId:'balance-pinned-forfeit-01',expectedBalanceRevision:1,responseMode:'state-parts-v1'};const ended=await app.api('/game/action',{token,body:forfeit});check(ended.status===200,JSON.stringify(ended.json));check(ended.json.balance.revision===2,'finished battle response switches to current revision');app.store.me(app.store.account('balance_player'));check(app.store.balance.runtimeRevision(app.store.runtimeOf(id))===2,'next runtime after a finished battle uses latest profile');const latestContext=app.store.coopContextFor(id);check(latestContext.members[0].snap.adminBalanceRevision===2&&latestContext.members[0].snap.actor.atk===guestNew.actor.atk,'the next co-op fight uses current character rules');
 const rollbackPreview=await app.api('/admin/balance?revision=0',{admin});check(rollbackPreview.status===200&&rollbackPreview.json.revision===2&&rollbackPreview.json.restoreProfile.revision===0&&rollbackPreview.json.changes.length>0,'rollback has a concrete current-to-target preview');const rolled=await app.api('/admin/balance/rollback',{admin,body:{expectedRevision:2,targetRevision:0,note:'기본값 복원'}});check(rolled.status===200&&rolled.json.revision===3,'rollback appends revision 3 instead of deleting history');check(app.store.db.prepare('SELECT COUNT(*) AS n FROM balance_profiles').get().n===4&&app.store.balance.profile(1).config.enemies[ordinary.id].hp===54321,'historical configurations remain immutable');check(app.store.db.prepare("SELECT COUNT(*) AS n FROM admin_audit WHERE op='balance-rollback'").get().n===1,'rollback is audited');check(app.store.balance.runtimeRevision(app.store.runtimeOf(id))===3,'rolled-back identity has its own new revision');
 // A second store may have the same integer revision with different numbers.
 second=await open(':memory:');const secondLogin=await second.api('/admin/login',{body:{id:'BALANCE',password:consolePassword}}),reg2=await second.api('/register',{body:{username:'balance_second',password}}),token2=reg2.json.token,id2=reg2.json.account.id;check((await second.api('/game/new',{token:token2,body:{name:'다른 서버',route:'ROUTE_TRAVELER'}})).status===200,'second store starts on identity');const c2=empty();c2.economy.innMultiplier=4;check((await second.api('/admin/balance/apply',{admin:secondLogin.json.token,body:{expectedRevision:0,config:c2}})).status===200,'independent store revision 1 accepts distinct numbers');check(second.store.balance.runtimeRevision(second.store.runtimeOf(id2))===1&&app.store.balance.profile(1).config.economy.innMultiplier===2,'store revisions and prepared runtimes are isolated');check(app.store.balance.currentRevision()===3,'second server cannot change the first server');await second.close();second=null;
 const historic=await app.api('/balance?revision=1',{token});check(historic.status===200&&historic.json.config.enemies[ordinary.id].hp===54321,'authenticated browser can obtain immutable battle profile');check((await app.api('/balance?revision=-1',{token})).status===400&&(await app.api('/balance?revision=999999',{token})).status===404,'invalid or nonexistent profile references are refused');
 const beforeRestart=app.store.balance.view(),firstRevisionConfig=app.store.balance.profile(1).config,stateAfter=JSON.stringify(joinState(app.store.loadParts(id)));await app.close();app=null;
 app=await open();check(app.store.balance.currentRevision()===3&&JSON.stringify(app.store.balance.profile(1).config)===JSON.stringify(firstRevisionConfig),'SQLite restart preserves immutable old and current profiles');const relog=await app.api('/login',{body:{username:'balance_player',password}});check(relog.status===200,'game login after restart');const restored=(await app.api('/me',{token:relog.json.token})).json;check(restored.balance.revision===3&&JSON.stringify(joinState(app.store.loadParts(id)))===stateAfter,'restart loads the selected profile without rewriting the player save');check((await app.api('/game/action',{token:relog.json.token,body:forfeit})).json.replayed===true,'battle-ending receipt remains replayable after restart and rollback');check(app.store.db.prepare('SELECT COUNT(*) AS n FROM balance_profiles').get().n===4,'restart does not add another default revision');
 console.log(JSON.stringify({ok:true,checks,categories:['separate operator authentication','identity state equality','validated catalog','preview without state changes','negative validation','transactional apply and CAS','actual item and inn costs','actual enemy specs and encounter','immutable pinned battle','unmarked legacy battle','finished fight switches profile','receipt replay','rollback and audit','independent server isolation','co-op snapshot profile parity','SQLite restart persistence'],initialSaveBytes:savedBefore.length}));
}finally{if(second)await second.close();if(app)await app.close();await rm(dir,{recursive:true,force:true});}
