'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=process.env.CRPG_ROOT||path.resolve(__dirname,'..'),out=path.join(root,'reports'),candidateDir=process.env.CRPG_CANDIDATE_SOURCE||path.join(root,'source'),db=JSON.parse(fs.readFileSync(path.join(root,'content/db.json'))),cp=x=>JSON.parse(JSON.stringify(x));
const files=[...fs.readFileSync(path.join(root,'source/index.html'),'utf8').matchAll(/<script src="(runtime[^\"]*\.js)"/g)].map(x=>x[1]);
function load(candidate=true){const context=vm.createContext({console});for(const f of files){const proposed=path.join(candidateDir,f),baseline=path.join(out,'baseline',f),source=candidate&&fs.existsSync(proposed)?proposed:!candidate&&fs.existsSync(baseline)?baseline:path.join(root,'source',f);vm.runInContext(fs.readFileSync(source,'utf8'),context,{filename:f});}context.CRPGRelationships.install(context.CRPGRuntime,{events:context.CRPGRelationships.catalogFromDB(db),activities:context.CRPGRelationships.activitiesFromDB(db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});return context.CRPGRuntime.Runtime;}
const Candidate=load(),results=[],fixtures=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/story-v081.json')));
function test(name,fn){const start=Date.now();try{const evidence=fn();results.push({name,passed:true,ms:Date.now()-start,evidence});console.log('PASS',name);}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error.stack);process.exitCode=1;}}
function action(r,type,params={}){return r.action(type,params);}
function step(r,prefer){if(!['STORY','STORY_WAIT'].includes(r.s.global.SCREEN_MODE))action(r,'MENU',{screen:'STORY'});const choices=r.storyChoices();if(choices.length){const selected=prefer?.(choices)||choices.find(c=>String(c[12]).includes('LEGEND_ACCEPT_AND_PAY'))||choices.find(c=>String(c[12]).includes('JOIN_ACCEPTED:'))||choices[0];return action(r,'STORY_CHOICE',{node:selected[4]});}const row=r.storyNode();assert(row);return action(r,row[5]==='INPUT_TEXT'?'STORY_NAME':'STORY_NEXT',row[5]==='INPUT_TEXT'?{name:r.s.global.PLAYER_NAME}:{node:row[4]});}
function opening(Runtime,unknown=false,observe=()=>{}){const r=new Runtime(db);r.newGame({name:'검증',route:'ROUTE_ISEKAI',seed:74219,saveId:'V09-STORY-'+(unknown?'U':'K')});for(let i=0;i<320;i++){if(r.playPhase()==='FREE')return r;observe(r);step(r,choices=>choices.find(c=>String(c[12]).includes('FLAG_ISK_META_KNOWLEDGE='+(unknown?'UNKNOWN':'KNOWN'))));}throw Error('Opening bound');}
const LEG='LEG_ISK_MOND_AMBER',QUEST='Q_LEG_ISK_MOND_AMBER',PID='PROFILE_MOND_AMBER';
let free,completed,baselineComplete=fixtures.baselineComplete,legacyBlank=fixtures.legacyBlank;
function enterAmber(r){const d=r.storyDefinition(LEG),place=r.legendIntroductionPlaces(d)[0];assert(place,'missing Amber introduction contact');const map=r.s.global.CURRENT_MAP_ID;r.s.global.CURRENT_MAP_ID=place.maps[0];action(r,'PLACE_ENTER',{place:place.id});action(r,'LEGEND_REGISTER',{quest:LEG});action(r,'PLACE_LEAVE');r.s.global.CURRENT_MAP_ID=map;r.giveItem('TRPG_STURDY_CLOTH',1);action(r,'LEGEND_ENTER',{quest:LEG});}
function completeAmber(r){enterAmber(r);for(let i=0;i<220&&r.s.storyContext;i++)step(r);assert(!r.s.storyContext);return r;}
function rejects(r,type,params){const before=r.serialize();assert.throws(()=>action(r,type,params));assert.equal(r.serialize(),before);}

test('candidate public openings preserve content choices with no blank automatic nodes',()=>{for(const unknown of [false,true]){const r=opening(Candidate,unknown,r=>{const row=r.storyNode();if(!r.storyChoices().length)assert(String(row[9]||'').trim(),row[4]);});assert(r.s.flags.FLAG_ISK_RECRUIT_AMBER);assert.equal(r.s.quests.Q_ISK_MOND_01.claimed,true);if(unknown)assert(r.s.flags.FLAG_ISK_STARTER_KIT_BOUGHT);else free=cp(r.s);}return {paths:2};});
test('legacy blank-event reload advances with exactly one effect application and receipt',()=>{for(const [id,state]of Object.entries(legacyBlank)){const snapshot=cp(state),r=new Candidate(db,state);assert.notEqual(r.storyActiveNodeId(),id);assert.equal(JSON.stringify(state),JSON.stringify(snapshot));assert(JSON.parse(r.s.global.STORY_NODE_EFFECTS_JSON)['ROUTE_ISEKAI:'+id]);const encoded=r.serialize(),again=new Candidate(db,JSON.parse(encoded));assert.equal(again.serialize(),encoded);if(id==='ISK_M01_UT_AID')assert.equal(r.s.global.MORA,state.global.MORA+1000);if(id==='ISK_M01_UT_KIT')assert(r.s.flags.FLAG_ISK_STARTER_KIT_BOUGHT);}return {count:Object.keys(legacyBlank).length};});
test('automatic event failure rolls back predecessor action and all earlier effects',()=>{const r=new Candidate(db,cp(free)),row=r.storyIndex().nodes.get('ROUTE_ISEKAI:ISK_M01_UT_AID');r.s.global.STORY_CURSOR_NODE_ID=r.s.global.CURRENT_STORY_NODE_ID='ISK_M01_UT030';const beforeRow=r.storyNode();assert(beforeRow);const prior=cp(beforeRow);beforeRow[11]='';beforeRow[12]='FLAG:FLAG_ISK_AID_RECEIVED=FALSE';beforeRow[13]=row[4];row[12]='EVENT:EVT_ISK_AID;UNKNOWN_COMMAND';r.s.global.STORY_WAITING=false;r.s.global.SCREEN_MODE='STORY';r.s.global.STORY_NODE_EFFECTS_JSON='{}';const before=cp(r.s);assert.throws(()=>action(r,'STORY_NEXT',{node:beforeRow[4]}));assert.deepEqual(cp(r.s),before);return {predecessor:prior[4]};});
test('legend completion grants exactly ten via public authored flow and both canonical ids are done',()=>{const r=completeAmber(new Candidate(db,cp(free)));assert.equal(r.storyBond(PID),10);assert(r.storyDone(LEG));assert(r.storyDone(QUEST));assert.equal(r.s.storyEventReceipts[LEG].bond.change,10);completed=cp(r.s);rejects(r,'LEGEND_ENTER',{quest:LEG});rejects(r,'LEGEND_ENTER',{quest:QUEST});return {bond:r.storyBond(PID)};});
test('each old completion evidence independently blocks repeat without clawback or regrant',()=>{const end=[...new Candidate(db,cp(baselineComplete)).storyIndex().nodes.values()].find(row=>row[1]===QUEST&&String(row[12]).includes('COMPLETE_LEGEND'));for(const kind of ['quest','questReceipt','legendReceipt','flag','nodeReceipt']){const s=cp(baselineComplete);delete s.quests[QUEST];s.storyEventReceipts={};s.flags.FLAG_ISK_LEG_AMBER_CLEAR=false;s.global.STORY_NODE_EFFECTS_JSON='{}';if(kind==='quest')s.quests[QUEST]={state:'완료',claimed:true};if(kind==='questReceipt')s.storyEventReceipts[QUEST]={turn:1,day:1};if(kind==='legendReceipt')s.storyEventReceipts[LEG]={turn:1,day:1};if(kind==='flag')s.flags.FLAG_ISK_LEG_AMBER_CLEAR=true;if(kind==='nodeReceipt')s.global.STORY_NODE_EFFECTS_JSON=JSON.stringify({[end[4]]:true});const r=new Candidate(db,s);assert.equal(r.storyBond(PID),20,kind);assert(r.storyDone(LEG),kind);assert(r.s.quests[QUEST].claimed);assert(r.s.flags.FLAG_ISK_LEG_AMBER_CLEAR);rejects(r,'LEGEND_ENTER',{quest:LEG});assert.equal(new Candidate(db,JSON.parse(r.serialize())).storyBond(PID),20);}return {forms:5};});
test('old save already inside repeated completed legend returns to original main frame',()=>{const old=fixtures.legacyRepeated,main=old.storyReturnStack.at(-1).main,r=new Candidate(db,cp(old));assert(!r.s.storyContext);assert.equal(r.storyActiveNodeId(),main);assert.equal(r.storyBond(PID),20);return {main};});
test('daily narrative runs at score 10 and arbitrary later scores with no general gain',()=>{const r=new Candidate(db,cp(completed)),a=r.relationshipActivityEntries().find(a=>a.profileId===PID);assert(a);assert.equal(a.reason,'');const prior=r.storyBond(PID),day=r.s.global.WORLD_DAY,receipt=action(r,'RELATION_ACTIVITY',{activityId:a.id});assert.equal(r.storyBond(PID),prior);assert(receipt.result.dialogue);assert.equal(r.lastRelationshipActivity(PID).day,day);rejects(r,'RELATION_ACTIVITY',{activityId:a.id});r.advanceTime(1440);r.changeBond(PID,51);assert.equal(r.relationshipActivityReason(a),'');action(r,'RELATION_ACTIVITY',{activityId:a.id});assert.equal(r.storyBond(PID),61);return {scores:[10,61],dialogue:receipt.result.title};});
test('affection H01 authored completion grants no score and daily requirement remains usable',()=>{const r=new Candidate(db,cp(completed));r.changeBond(PID,10);action(r,'AFFECTION_ENTER',{event:'AFF_ISK_MOND_AMBER_H01'});for(let i=0;i<160&&r.s.storyContext;i++)step(r);assert(r.storyDone('AFF_ISK_MOND_AMBER_H01'));assert.equal(r.storyBond(PID),20);const a=r.relationshipActivityEntries().find(a=>a.profileId===PID);action(r,'RELATION_ACTIVITY',{activityId:a.id});assert(r.storyAfterDaily('AFF_ISK_MOND_AMBER_H01'));assert.equal(r.storyBond(PID),20);return {score:20};});

function prepareFight(){const r=new Candidate(db,cp(completed));r.storySetCompanion('MOND_KAEYA','JOINED');r.storySetCompanion('MOND_LISA','JOINED');action(r,'PARTY',{char:'MOND_AMBER',slot:2});action(r,'PARTY',{char:'MOND_KAEYA',slot:3});action(r,'PARTY',{char:'MOND_LISA',slot:4});for(const id of ['PROFILE_MOND_KAEYA','PROFILE_MOND_LISA'])r.markContact(id);return r;}
const GROUP=db['33_ENCOUNTER_GROUP_DB'].slice(1).find(r=>r[6]==='PARTY_BANDED'&&String(r[0]).includes('MOND'))?.[0];
function finishByPublicAction(r,victory=true){r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';r.s.global.ENCOUNTER_COOLDOWN=0;const die=r.die;r.die=()=>1;action(r,'WAIT',{minutes:60});r.die=die;const b=r.s.runtime;assert(b);if(victory){for(const a of b.actors.filter(a=>a.side==='ENEMY'))a.hp=0;}else for(const a of b.actors.filter(a=>a.side==='ALLY'))a.hp=0;const a={type:'COMBAT_BEGIN',battle:b.id,id:r.s.global.SAVE_ID+':'+(r.s.global.LAST_COMMITTED_ACTION_SEQ+1),revision:r.s.global.SAVE_REVISION};const receipt=r.transact(a);assert(!r.s.runtime);return {a,receipt};}

test('one victorious battle gives only active slot 2 exactly one point and duplicate receipt is harmless',()=>{const r=prepareFight();const last=finishByPublicAction(r);assert.equal(r.storyBond(PID),11);assert.equal(r.storyBond('PROFILE_MOND_KAEYA'),0);assert.equal(r.storyBond('PROFILE_MOND_LISA'),0);assert.equal(Object.values(r.s.relationshipBattleReceipts).length,1);const saved=r.serialize();assert.deepEqual(cp(r.transact(last.a)),cp(last.receipt));assert.equal(r.serialize(),saved);assert.equal(new Candidate(db,JSON.parse(saved)).storyBond(PID),11);return {group:GROUP,score:11};});
test('defeat gives no point and empty slot 2 or incomplete legend gives none',()=>{const r=prepareFight();finishByPublicAction(r,false);assert.equal(r.storyBond(PID),10);const a=prepareFight();action(a,'PARTY_REMOVE',{slot:2});finishByPublicAction(a);assert.equal(a.storyBond(PID),10);const b=prepareFight();action(b,'PARTY_SWAP',{from:2,to:3});finishByPublicAction(b);assert.equal(b.storyBond(PID),10);assert.equal(b.storyBond('PROFILE_MOND_KAEYA'),0);return {};});
test('battle actor source and slot outrank actor id and stale persistent party, including story guest',()=>{const r=prepareFight();const b={id:'GUEST-TEST',actors:[{id:'GUEST_INSTANCE_42',source:'MOND_AMBER',side:'ALLY',slot:2,guest:true},{id:'MOND_KAEYA',source:'MOND_KAEYA',side:'ALLY',slot:3}]};r.s.party[1].source='MOND_KAEYA';const target=r.relationshipBattleTarget(b);assert.equal(target.profileId,PID);b.relationshipTarget=target;assert.equal(r.awardBattleBond(b).change,1);assert.equal(r.awardBattleBond(b).change,1);assert.equal(r.storyBond(PID),11);b.id='NO-TARGET';b.relationshipTarget=null;assert.equal(r.awardBattleBond(b),null);assert.equal(r.storyBond(PID),11);return {char:target.charId,guest:true};});
test('formation UI labels slot two and explains exact gain rules',()=>{const code=fs.readFileSync(path.join(candidateDir,'app_party.js'),'utf8');assert(code.includes('치명타 확률 +5% · 호감도 동행'));assert(code.includes('전투 승리마다 1점'));assert(code.includes('10점으로 한 번'));return {};});
test('all 24 authored legends complete for exactly ten with immutable duplicate completion action',()=>{const probe=new Candidate(db,cp(free));let count=0;for(const def of probe.storyIndex().legends.values()){if(def.REGION!=='몬드'||def.ROUTE_SCOPE!=='ROUTE_TRAVELER'&&!['LEG_ISK_MOND_AMBER','LEG_ISK_MOND_DILUC','LEG_ISK_MOND_JEAN','LEG_ISK_MOND_EULA'].includes(def.id))continue;const r=new Candidate(db);r.newGame({name:'전설검증',route:def.ROUTE_SCOPE,seed:74219,saveId:'LEGEND-'+def.id});Object.assign(r.s.global,{STORY_CURSOR_NODE_ID:'END',CURRENT_STORY_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',STORY_MENU_POLICY:'',CURRENT_MAP_ID:def.MAP_ID,MORA:100000});r.prepareStory();for(const m of String(def.START_CONDITION).matchAll(/(FLAG_[A-Z0-9_]+)=(TRUE|FALSE)/g))r.s.flags[m[1]]=m[2]==='TRUE';r.s.flags.FLAG_ISK_META_KNOWLEDGE='KNOWN';r.s.quests.Q_ISK_MOND_03={state:'완료',claimed:true};r.s.guildLegends={[def.id]:{day:r.s.global.WORLD_DAY}};for(const [item,n]of Object.entries(JSON.parse(def.COST_ITEMS_JSON||'{}')))r.giveItem(item,n);action(r,'LEGEND_ENTER',{quest:def.id});let clicks=0;while(r.s.storyContext&&clicks++<250)step(r);assert(!r.s.storyContext,def.id);assert.equal(r.storyBond(def.PROFILE_ID),10,def.id);assert(r.storyDone(def.id));const encoded=r.serialize(),last=JSON.parse(r.s.global.LAST_ACTION_RECEIPT_JSON);assert.deepEqual(cp(r.transact({id:r.s.global.LAST_COMMITTED_ACTION_ID,revision:r.s.global.SAVE_REVISION-1,type:last.type,node:last.result.resolved})),last);assert.equal(r.serialize(),encoded);count++;}assert.equal(count,24);return {count};});
test('old ongoing battle without new target metadata settles slot 2 once after reload',()=>{let r=prepareFight();r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';r.s.global.ENCOUNTER_COOLDOWN=0;r.die=()=>1;action(r,'WAIT',{minutes:60});delete r.s.runtime.relationshipTarget;r=new Candidate(db,JSON.parse(r.serialize()));for(const a of r.s.runtime.actors.filter(a=>a.side==='ENEMY'))a.hp=0;action(r,'COMBAT_BEGIN');assert.equal(r.storyBond(PID),11);return {};});
fs.writeFileSync(path.join(out,'story-v09-results.json'),JSON.stringify({tests:results,passed:results.filter(x=>x.passed).length,total:results.length},null,2));
