'use strict';const assert=require('node:assert/strict'),{fresh,R,db,fs,root}=require('./helpers_v011.cjs'),{fixture,run}=require('./helpers_abyss.cjs'),{equip,artifacts}=require('./helpers_abyss_artifacts.cjs');const report=[];
const teams={4:['MOND_AMBER','MOND_KAEYA','LIYUE_YAOYAO'],5:['MOND_LISA','LIYUE_TARTAGLIA','LIYUE_LANYAN'],6:['LIYUE_GANYU','LIYUE_SHENHE','LIYUE_XIANYUN'],7:['LIYUE_YELAN','LIYUE_HUTAO','LIYUE_BAIZHU'],8:['MOND_RAZOR','MOND_BARBARA','MOND_FISCHL'],9:['MOND_NOELLE','MOND_DIONA','LIYUE_NINGGUANG'],10:['LIYUE_XINGQIU','LIYUE_KEQING','MOND_SUCROSE'],11:['MOND_BENNETT','LIYUE_QIQI','MOND_ALBEDO'],12:['MOND_DILUC','MOND_JEAN','LIYUE_ZHONGLI']};
assert.equal(new Set(Object.values(teams).flat()).size,27,'nine independent companion teams');
assert.throws(()=>fixture(6).action('ABYSS_ENTER',{floor:1}),/Lv. 10/);assert.throws(()=>fresh().action('ABYSS_ENTER',{floor:1}));
for(const f of [1,2,3,4,5,6,7,8,9,10,11,12]){const r=fixture(f<=3?[10,12,15][f-1]:20,teams[f],f<=3?7:12),ids=r.abyssParty();if(f>=4)artifacts(r,ids);if(f===12){equip(r,'PLAYER_CUSTOM','EQ_CLAYMORE_ARCHAIC');for(const id of ids.slice(1))equip(r,id,'EQ_EX_'+id);}for(const id of ids){if(f===8)equip(r,id,'EQ_LY_SPECIAL_LEYLINE_STAKE');if(f===9)equip(r,id,'EQ_ACC_STEADFAST');if(f===10)equip(r,id,'EQ_LY_ACC_STARGAZER');if(f===11)equip(r,id,'EQ_LY_ACC_QINGXIN_SACHET');}r.action('OPERATOR_DEBUG',{op:'heal'});const out=run(r,f);report.push({floor:f,level:out.level,win:out.result.victory,rounds:out.result.rounds,stats:out.stats,gear:out.gear});assert(out.result.victory,'solvable floor '+f);assert.equal(out.result.xp,0);const before=r.s.inventory.length;r.action('MENU',{screen:'LOCATION'});r.action('ABYSS_REWARD',{floor:f,equipment:'EQ_SWORD_AMENOMA'});assert.equal(r.s.inventory.length,before+1);assert.throws(()=>r.action('ABYSS_REWARD',{floor:f,equipment:'EQ_SWORD_AMENOMA'}));r.action('ABYSS_RESET',{confirm:true});assert.throws(()=>r.action('ABYSS_REWARD',{floor:f,equipment:'EQ_SWORD_AMENOMA'}));if(f===12){const inv=r.s.inventory.at(-1);assert(inv.artifact.quality>=900);assert.equal(inv.equip,'EQ_ABYSS_INAZUMA_ARTIFACT');}}
// Tags are committed at entry, survive failed battles and serialization, allow only the same floor.
let r=fixture(20);r.action('OPERATOR_DEBUG',{op:'abyss_unlock',value:4});r.action('ABYSS_ENTER',{floor:4});assert.equal(Object.keys(r.s.abyss.tags).length,3);assert(!r.s.abyss.tags.PLAYER_CUSTOM);r=new R(db,JSON.parse(r.serialize()));r.finishBattle(false);r.s.global.CURRENT_STORY_NODE_ID=r.s.global.STORY_CURSOR_NODE_ID='END';r.s.global.SCREEN_MODE='LOCATION';r.s.postDefeat=null;r.s.storyRecovery=null;r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;for(const id of r.abyssParty().slice(1))r.s.chars[id].hp=r.character(id).maxHp;r.s.abyss.clears[4]={rounds:1,attempt:1,party:r.abyssParty(),run:1};assert.match(r.abyssFloorReason(5),/딱지/);assert.equal(r.s.abyss.tags.MOND_DILUC,4);assert.equal(r.s.abyss.claimed[4],undefined);
// Ordinary damage cannot bypass floor 8, including enormous attacks; enhanced fixed mechanism works.
r=fixture(20);r.action('OPERATOR_DEBUG',{op:'abyss_unlock',value:8});r.action('ABYSS_ENTER',{floor:8});let b=r.s.runtime,a=b.actors[0],t=b.actors.find(x=>x.side==='ENEMY');const hp=t.hp;r.applyDamage(a,t,1000000,{sourceKind:'REACTION'});assert.equal(t.hp,hp);assert.equal(r.enemyIntel(t.id).cards[0].description,'무적입니다.');r.applyDamage(a,t,100,{sourceKind:'ABYSS_FIXED'});assert.equal(t.hp,hp-100);
// The floor 12 requirement uses natural artifact stats and every member's gear, not one character.
r=fixture(20,teams[12],12);artifacts(r,r.abyssParty());r.action('OPERATOR_DEBUG',{op:'abyss_unlock',value:12});r.action('ABYSS_ENTER',{floor:12});assert(r.abyssMasteryReady());const ar=r.s.inventory.find(x=>x.artifact&&x.equipped);ar.artifact.quality=899;assert(!r.abyssMasteryReady());ar.artifact.quality=999;const w=r.s.inventory.find(x=>x.equipped&&x.category==='WEAPON');w.enhance=11;assert(!r.abyssMasteryReady());
fs.mkdirSync(root+'/reports/abyss',{recursive:true});fs.writeFileSync(root+'/reports/abyss/balance-v01341.json',JSON.stringify({provenance:'Synthetic level/gear setup. Native stat formulas, natural artifact rolls selected from 1500 drops per actor and enhanced to legal level5; no inflated base HP/ATK. COMBAT_BEGIN and all COMBAT actions run normally. Floors tested independently; tag persistence tested separately. This proves solvability, not an estimated player clear rate.',runs:report},null,2));console.log('PASS all 12 floors through native combat, no-hint immunity, entry tags, first-clear rewards, reset, quality/full-enhancement gates');
