'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {fresh}=require('./helpers_v011.cjs');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const checks=[];function test(name,fn){try{const evidence=fn()||null;checks.push({name,ok:true,evidence});console.log('PASS '+name);}catch(e){checks.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);process.exitCode=1;}}
for(const file of ['source/runtime_combat.js','source/runtime_liyue_cards.js','source/presentation.js','source/app_experience.js','source/app_av.js','source/app_combat_fx.js'])test('syntax '+file,()=>{new Function(read(file));});
function actor(id,side,extra={}){return {id,source:id,name:id,side,control:side==='ALLY'?'PLAYER':'AI',grade:side==='ENEMY'?'일반':'캐릭터',hp:1000,maxHp:1000,atk:100,def:100,spd:60,crit:0,critDmg:50,hit:100,eva:0,resist:0,level:10,range:'근접',statuses:[],shields:[],cooldowns:{},turns:0,...extra};}
function arena(){const r=fresh('MAP_MOND_PLAINS'),a=actor('ALLY_OWNER','ALLY'),p=actor('ALLY_TARGET','ALLY'),e=actor('ENEMY_TEST','ENEMY');r.s.runtime={id:'V142',combatVersion:1,round:1,actors:[a,p,e],order:[],cursor:0,phase:'WAIT_PLAYER',ticks:{},log:[],fields:[],terrain:null,storyConfig:null,interludeSeen:{},pendingInterludes:[],toolCharges:{},actionSequence:1};return{r,a,p,e,b:r.s.runtime};}
test('shield packets carry immediate before/after values',()=>{const {r,p,e,b}=arena();r.shield(p,100,'TEST',2);const hp=p.hp;r.applyDamage(e,p,40,{element:'물리'});const x=b.log.at(-1);assert.equal(p.hp,hp);assert.equal(p.shields[0].value,60);assert.deepEqual({absorbed:x.absorbed,before:x.shieldBefore,after:x.shieldAfter,damage:x.damage},{absorbed:40,before:100,after:60,damage:0});return x;});
test('Baron Bunny redirects only a rolled single-target packet and keeps own HP',()=>{const {r,a,p,e,b}=arena();b.fields.push({kind:'BUNNY',actor:a.id,side:'ALLY',hp:500,maxHp:500,def:100,tauntChance:30,done:false,rounds:1,createdRound:1,explodeAt:2});r.die=()=>1;const hp=p.hp;r.damage(e,p,.5,'PHYSICAL',{sureHit:true,noCrit:true});assert.equal(p.hp,hp);assert(b.fields[0].hp<500);assert(b.log.some(x=>x.taunted&&x.targetId==='SUMMON:BUNNY:'+a.id));const bunny=b.fields[0],after=bunny.hp;r.die=()=>100;r.damage(e,p,.5,'PHYSICAL',{sureHit:true,noCrit:true});assert(p.hp<hp);assert.equal(bunny.hp,after);const hp2=p.hp,after2=bunny.hp;r.die=()=>1;r.damage(e,p,.5,'PHYSICAL',{sureHit:true,noCrit:true,aoe:true});assert(p.hp<hp2);assert.equal(bunny.hp,after2);return{redirected:true,remaining:bunny.hp};});
test('Oz attacks from summon identity for exactly two END ticks even if Fischl is down',()=>{const {r,a,e,b}=arena();a.hp=0;b.fields.push({kind:'OZ',actor:a.id,side:'ALLY',rounds:99,createdRound:1,sourceCardId:'MOND_FISCHL_E',name:'오즈',asset:'summon_oz.webp',summonTurns:2,summonTicks:0});r.tickFields('END');assert(b.fields.some(f=>f.kind==='OZ'&&f.summonTicks===1));assert(b.log.some(x=>x.presentationActorId==='SUMMON:OZ:'+a.id));r.tickFields('END');assert(!b.fields.some(f=>f.kind==='OZ'));return{targetHp:e.hp};});
test('Guoba and Yuegui attack from their own summon positions and expire after two ticks',()=>{for(const spec of [{kind:'GOU_BA',card:'LIYUE_XIANGLING_E',name:'누룽지',asset:'summon_guoba.webp'},{kind:'YUEGUI_THROWING',card:'LIYUE_YAOYAO_E',name:'월계',asset:'summon_yuegui.webp'}]){const {r,a,b}=arena();a.hp=0;b.fields.push({kind:spec.kind,actor:a.id,side:'ALLY',rounds:99,createdRound:1,sourceCardId:spec.card,liyue:true,name:spec.name,asset:spec.asset,summonTurns:2,summonTicks:0});r.tickFields('END');assert(b.fields.some(f=>f.kind===spec.kind&&f.summonTicks===1),spec.kind);assert(b.log.some(x=>x.presentationActorId==='SUMMON:'+spec.kind+':'+a.id),spec.kind);r.tickFields('END');assert(!b.fields.some(f=>f.kind===spec.kind),spec.kind);}});
test('combat UI ships summon lanes, source-origin FX, live shields and battle-music hold',()=>{const exp=read('source/app_experience.js'),av=read('source/app_av.js'),fx=read('source/app_combat_fx.js'),pres=read('source/presentation.js'),build=read('tools/build.py');for(const token of ['battleSummons(stage,b)','summon_baron_bunny.webp','summon_oz.webp','summon_guoba.webp','summon_yuegui.webp','data-summon-id'])assert(exp.includes(token)||exp.includes(token.replace('data-summon-id','dataset.summonId')),token);assert(av.includes('combatHold'));assert(av.includes("'.battle-summon[data-summon-id]'")||av.includes('.battle-summon[data-summon-id]'));assert(av.includes('shield(event.shieldAfter)'));assert(av.includes("보호막 -"));assert(fx.includes('summonSource'));assert(pres.includes('presentationActorId'));assert(build.includes("assets/summons"));for(const f of ['summon_baron_bunny.webp','summon_oz.webp','summon_guoba.webp','summon_yuegui.webp'])assert(fs.existsSync(path.join(root,'assets/summons',f)),f);});
const report={version:'0.14.2',total:checks.length,passed:checks.filter(x=>x.ok).length,checks};fs.mkdirSync(path.join(root,'reports/local-v0142'),{recursive:true});fs.writeFileSync(path.join(root,'reports/local-v0142/combat-summons.json'),JSON.stringify(report,null,2)+'\n');if(report.total!==report.passed)process.exitCode=1;
