'use strict';
// Executes the actual combatSpeedControl/GameEffects source unchanged in a minimal DOM and virtual clock.
// No product files, runtime state, saves, or real timers are used.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const parent=path.resolve(__dirname,'..'),root=process.env.CRPG_ROOT||(fs.existsSync(path.join(parent,'source/app_av.js'))?parent:'/workspace/scratch/adc1ed75baeb/game');
const file=path.join(root,'source/app_av.js'),source=fs.readFileSync(file,'utf8'),start=source.indexOf('function combatSpeedControl(){'),end=source.indexOf('let renderedSaveId=null;');
assert(start>=0&&end>start,'actual playback source boundaries');
const extracted=source.slice(start,end),visibility=source.match(/document\.addEventListener\('visibilitychange',[^\n]+/)[0],pagehide=source.match(/window\.addEventListener\('pagehide',[^\n]+/)[0];
const report={source:file,sha256:crypto.createHash('sha256').update(source).digest('hex'),tests:[]};
function harness({speed=1,reducedMotion=false}={}){
 let now=0,nextId=0,forbidden=0,persisted=0,stops=0,syncs=0;const timers=new Map(),shown=[],animations=[],sounds=[],docListeners={},windowListeners={};
 class Node {
  constructor(tag,cls='',text=''){this.tag=tag;this.textContent=text;this.className=cls;this.children=[];this.parentNode=null;this.dataset={};this.style={};this.attrs={};this.inert=false;const set=new Set(cls.split(/\s+/).filter(Boolean));this.classList={add:(...names)=>names.forEach(x=>set.add(x)),remove:(...names)=>names.forEach(x=>set.delete(x)),contains:x=>set.has(x),toggle:(x,force)=>{const on=force===undefined?!set.has(x):!!force;if(on)set.add(x);else set.delete(x);return on;}};}
  setAttribute(k,v){this.attrs[k]=String(v);}
  append(...nodes){for(const node of nodes){node.parentNode=this;this.children.push(node);if(this.classList.contains('combat-effects')&&node.classList.contains('impact'))shown.push({label:node.children.find(x=>x.classList.contains('impact-label'))?.textContent,time:now});}}
  remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this);this.parentNode=null;}
  replaceChildren(...nodes){for(const child of this.children)child.parentNode=null;this.children=[];this.append(...nodes);}
  matches(selector){if(selector==='[data-actor-id]')return !!this.dataset.actorId;const compound=selector.match(/^\.([\w-]+)\[data-actor-id\]$/);if(compound)return this.classList.contains(compound[1])&&!!this.dataset.actorId;if(selector.startsWith('.'))return this.classList.contains(selector.slice(1));return this.tag===selector;}
  querySelectorAll(selector){if(selector.includes(' ')){const [first,...rest]=selector.split(' ');return this.querySelectorAll(first).flatMap(n=>n.querySelectorAll(rest.join(' ')));}const out=[];for(const n of this.children){if(n.matches(selector))out.push(n);out.push(...n.querySelectorAll(selector));}return out;}
  querySelector(s){return this.querySelectorAll(s)[0]||null;}
  getBoundingClientRect(){return {top:160,bottom:360,left:100,width:120,height:200};}
  animate(frames,options){const record={actor:this.dataset.actorId,time:now,options,paused:false,cancelled:false};animations.push(record);return {finished:new Promise(()=>{}),cancel(){record.cancelled=true;},pause(){record.paused=true;},play(){record.paused=false;}};}
 }
 const el=(...args)=>new Node(...args),body=el('body'),docEl=el('html'),rootNode=el('main'),settings={combatSpeed:speed,reducedMotion,damageFlash:true};body.append(rootNode);
 for(const id of ['PLAYER_CUSTOM','ENEMY']){const actor=el('section','combatant-row');actor.dataset.actorId=id;actor.dataset.maxHp='100';actor.append(el('div','stat','HP  100 / 100'));const meter=el('div','meter');meter.append(el('i'));actor.append(meter);rootNode.append(actor);}
 const document={body,documentElement:docEl,hidden:false,querySelectorAll:s=>body.querySelectorAll(s),addEventListener:(name,fn)=>docListeners[name]=fn};
 const sandbox={document,window:{addEventListener:(name,fn)=>windowListeners[name]=fn},root:rootNode,busy:true,settings,innerHeight:900,innerWidth:1200,performance:{now:()=>now},el,button:(label,fn)=>{const n=el('button','',label);n.onclick=fn;return n;},persistSettings:()=>{persisted++;},GameAudio:{play:cue=>sounds.push({cue,time:now}),stop:()=>{stops++;},sync:()=>{syncs++;}},setTimeout:(fn,delay)=>{const id=++nextId;timers.set(id,{fn,at:now+delay,delay});return id;},clearTimeout:id=>timers.delete(id)};
 for(const name of ['game','Runtime','CRPGRuntime','storeSave','storeStoryCheckpoint','saveAdapter'])Object.defineProperty(sandbox,name,{get(){forbidden++;throw Error('Playback accessed forbidden game/save global: '+name);}});
 const ctx=vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'source/app_combat_fx.js'),'utf8'),ctx);vm.runInContext(extracted+'\n'+visibility+'\n'+pagehide+'\n;globalThis.playback=GameEffects;globalThis.makeSpeed= combatSpeedControl;',ctx,{filename:'actual-app_av-playback.js'});
 const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
 async function tick(ms){const until=now+ms;let guard=0;while(true){const due=[...timers.entries()].filter(([,v])=>v.at<=until).sort((a,b)=>a[1].at-b[1].at||a[0]-b[0])[0];if(!due)break;assert(++guard<1000,'virtual timer loop');now=due[1].at;timers.delete(due[0]);due[1].fn();await flush();}now=until;await flush();}
 const click=label=>{const b=body.querySelectorAll('button').find(b=>b.textContent===label);assert(b,'button '+label);b.onclick();return flush();};
 const speedTo=n=>{const input=body.querySelector('.combat-speed').querySelector('input');input.value=String(n);input.oninput();return input;};
 return {fx:ctx.playback,makeSpeed:ctx.makeSpeed,root:rootNode,body,document,settings,shown,animations,sounds,timers,flush,tick,click,speedTo,hidden:async()=>{document.hidden=true;docListeners.visibilitychange();await flush();},visible:()=>{document.hidden=false;docListeners.visibilitychange();},pagehide:async()=>{windowListeners.pagehide();await flush();},stats:()=>({forbidden,persisted,stops,syncs,now})};
}
const event=(key,n=0)=>({key,kind:'damage',element:'PHYSICAL',label:'피해 '+key,amount:10,targetId:'PLAYER_CUSTOM',target:'주인공',actorId:'ENEMY',actor:'적',cardName:'일반공격',hpBefore:100-n*10,hpAfter:90-n*10,maxHp:100,side:'ENEMY',round:1,cue:'hit'});
async function test(name,fn){try{const evidence=await fn();report.tests.push({name,ok:true,evidence});console.log('PASS '+name);}catch(e){report.tests.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
(async()=>{
 await test('shows exactly one event immediately and advances at 1400ms boundaries',async()=>{const h=harness(),job=h.fx.play([event('a'),event('b',1),event('c',2)]);assert.deepEqual(h.shown.map(x=>x.label),['피해 a']);await h.tick(1399);assert.equal(h.shown.length,1);await h.tick(1);assert.equal(h.shown.length,2);await h.tick(1400);assert.equal(h.shown.length,3);await h.tick(1400);await job;assert(!h.fx.active);assert.equal(h.body.querySelector('.combat-playback'),null);assert.deepEqual(h.shown.map(x=>x.time),[0,1400,2800]);assert.equal(h.stats().forbidden,0);return {times:h.shown.map(x=>x.time)};});
 await test('pause freezes automatically advancing; next displays one and stays paused; resume continues',async()=>{const h=harness(),job=h.fx.play([event('p1'),event('p2',1),event('p3',2)]);await h.tick(300);await h.click('일시정지');assert(h.fx.paused);await h.tick(10000);assert.equal(h.shown.length,1);await h.click('다음 표시');assert.equal(h.shown.length,2);assert(h.fx.paused);await h.tick(10000);assert.equal(h.shown.length,2);await h.click('계속 재생');assert(!h.fx.paused);await h.tick(1399);assert.equal(h.shown.length,2);await h.tick(1);assert.equal(h.shown.length,3);h.fx.cancel();await job;assert.equal(h.stats().forbidden,0);return {};});
 await test('0.5x and 2x use actual slider and reschedule to 2800ms and 700ms',async()=>{const checks=[];for(const [speed,delay]of [[.5,2800],[2,700]]){const h=harness(),other=h.makeSpeed();h.body.append(other);const job=h.fx.play([event('s1'),event('s2',1)]);const input=h.speedTo(speed);input.onchange();for(const row of h.document.querySelectorAll('.combat-speed')){assert.equal(Number(row.querySelector('input').value),speed);assert.match(row.querySelector('output').textContent,new RegExp(String(speed)));}await h.tick(delay-1);assert.equal(h.shown.length,1);await h.tick(1);assert.equal(h.shown.length,2);h.fx.cancel();await job;assert.equal(h.stats().persisted,1);assert.equal(h.stats().forbidden,0);checks.push({speed,delay});}return checks;});
 await test('result button cancels timer and pending sequence without a later event',async()=>{const h=harness(),job=h.fx.play([event('c1'),event('c2',1),event('c3',2)]);await h.click('결과 바로 보기');await job;assert.equal(h.shown.length,1);assert(!h.fx.active);assert.equal(h.fx.dock,null);assert.equal(h.root.inert,true);await h.tick(100000);assert.equal(h.shown.length,1);assert.equal(h.stats().forbidden,0);return {rootInertWhileActionBusy:h.root.inert};});
 await test('repeated keys across completed play calls are not replayed',async()=>{const h=harness();let job=h.fx.play([event('same')]);await h.tick(1400);await job;job=h.fx.play([event('same')]);await job;assert.equal(h.shown.length,1);assert(!h.fx.active);assert.equal(h.stats().forbidden,0);return {};});
 await test('duplicate keys within the same event batch are shown once',async()=>{const h=harness(),job=h.fx.play([event('dup'),event('dup'),event('other',1)]);await h.tick(10000);await job;assert.deepEqual(h.shown.map(x=>x.label),['피해 dup','피해 other']);assert.equal(h.stats().forbidden,0);return {};});
 await test('hidden and pagehide use actual listeners to stop pending display; showing tab does not replay',async()=>{for(const via of ['hidden','pagehide']){const h=harness(),job=h.fx.play([event('h1'),event('h2',1)]);await h.tick(100);await h[via]();await job;await h.tick(10000);assert.equal(h.shown.length,1);assert(!h.fx.active);assert.equal(h.stats().stops,1);if(via==='hidden'){h.visible();assert.equal(h.stats().syncs,1);await h.fx.play([event('h1'),event('h2',1)]);assert.equal(h.shown.length,1);}assert.equal(h.stats().forbidden,0);}const hidden=harness();hidden.document.hidden=true;await hidden.fx.play([event('before-hidden')]);assert.equal(hidden.shown.length,0);return {};});
 await test('reduced motion preserves exact reading durations and HP updates while disabling actor animation',async()=>{const sequences=[];for(const reducedMotion of [false,true]){const h=harness({reducedMotion}),job=h.fx.play([event('r1'),event('r2',1)]);await h.tick(2800);await job;assert.equal(h.root.querySelector('[data-actor-id]').querySelector('.stat').textContent,'HP  80 / 100');assert.equal(h.root.querySelector('[data-actor-id]').querySelector('.meter i').style.width,'80%');assert.equal(h.stats().forbidden,0);sequences.push({reducedMotion,times:h.shown.map(x=>x.time),animations:h.animations.length});}assert.deepEqual(sequences[0].times,sequences[1].times);assert(sequences[0].animations>0);assert.equal(sequences[1].animations,0);return sequences;});
 await test('grouped actions preserve critical totals and suppress extra attack motions for reactions',async()=>{const h=harness(),p=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(root,'source/presentation.js'),'utf8'),p);const direct={...event('grouped'),critical:true,action:1,sourceKind:null,side:'ALLY'},reaction={...event('reaction'),sourceKind:'REACTION',critical:false,action:1,hpBefore:90,hpAfter:80},announcement={...event('announce'),kind:'reaction',label:'과부하',sourceKind:null,action:1,hpBefore:undefined,hpAfter:undefined};const frames=p.CRPGPresentation.actionFrames([direct,reaction,announcement]);const job=h.fx.play(frames);assert.equal(h.root.querySelector('[data-actor-id]').querySelector('.stat').textContent,'HP  100 / 100');await h.tick(269);assert.equal(h.shown.length,0);await h.tick(1);assert.match(h.fx.dock.querySelector('.playback-message').textContent,/1회 행동/);assert.match(h.fx.dock.querySelector('.playback-outcomes').children[0].textContent,/피해 20.*치명타 포함.*HP 100 → 80/);assert(h.fx.layer.querySelector('.critical'));assert.equal(h.animations.filter(x=>x.actor==='ENEMY').length,1);h.fx.cancel();await job;for(const sourceKind of ['REACTION','BUBBLE','ASSIST','FOLLOWUP','SUMMON']){const frame=p.CRPGPresentation.actionFrames([{...reaction,key:sourceKind,sourceKind},announcement])[0];h.fx.showAction(frame);}h.fx.showAction(p.CRPGPresentation.actionFrames([{...announcement,key:'standalone'}])[0]);assert.equal(h.animations.filter(x=>x.actor==='ENEMY').length,1,'effect frames never animate another actor attack');return {directActions:1,effectFrames:6};});
 report.total=report.tests.length;report.passed=report.tests.filter(x=>x.ok).length;report.failed=report.total-report.passed;const output=process.env.CRPG_REPORT_DIR||path.join(root,'reports');fs.writeFileSync(path.join(output,'playback-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({total:report.total,passed:report.passed,failed:report.failed}));process.exitCode=report.failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
