const assert=require('node:assert/strict'),fs=require('fs'),base=require('path').resolve(__dirname,'..');require(base+'/source/runtime_story.js');const {Runtime}=require('../source/runtime_combat.js');const db=JSON.parse(fs.readFileSync(base+'/content/db.json')),results=[];
function test(name,f){try{f();results.push({name,ok:true})}catch(e){results.push({name,ok:false,error:e.stack})}}
function fixture(chars){const r=new Runtime(db);r.newGame({name:'추가기술검증',seed:1245,saveId:'EXTRA-CARDS'});r.s.global.CURRENT_STORY_NODE_ID='HUB';r.s.global.STORY_CURSOR_NODE_ID='HUB';r.s.global.CURRENT_MAP_ID='MAP_STORMTERROR_LAIR';r.s.global.PLAYER_BASE_HP=100000;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(Object.fromEntries(chars.map(c=>[c,{state:'JOINED'}])));for(let i=0;i<chars.length;i++)r.action('PARTY',{char:chars[i],slot:i+2});return r;}
test('Bennett Q buffs only pyro allies and suppresses enemy light tags',()=>{const r=fixture(['MOND_BENNETT','MOND_DILUC']);r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});const bennett=r.combatActor('MOND_BENNETT'),diluc=r.combatActor('MOND_DILUC'),boss=r.s.runtime.actors.find(a=>a.side==='ENEMY');assert.equal(r.combatStat(bennett,'atk'),bennett.atk*1.2);assert.equal(r.combatStat(diluc,'atk'),diluc.atk*1.2);assert(!r.combatTags(boss).includes('[광계]'));assert.equal(r.combatStat(r.combatActor(),'atk'),r.combatActor().atk);});
test('Dahlia shared two hymn regenerations preserve original shield magnitude',()=>{const r=fixture(['MOND_DAHLIA']);r.s.chars.MOND_DAHLIA.level=20;r.s.chars.MOND_DAHLIA.hp=r.character('MOND_DAHLIA').maxHp;r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});while(r.s.runtime&&!r.combatActor('MOND_DAHLIA').shields.length)r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});const b=r.s.runtime,a=r.combatActor(),boss=b.actors.find(a=>a.side==='ENEMY'),shield=a.shields.find(s=>s.source==='MOND_DAHLIA_Q');assert(shield);const initial=shield.initialValue;const before=b.hymn.ALLY;r.applyDamage(boss,a,shield.value,{element:'바람'});assert.equal(b.hymn.ALLY,before-1);assert.equal(a.shields.find(s=>s.source==='MOND_DAHLIA_Q').value,Math.round(initial*.5));});
test('Klee Q distributes exactly four attacks at round end and preserves aura limit',()=>{const r=fixture(['MOND_KLEE']);r.giveItem('TRPG_TACTICAL_LEVITATOR',1);r.s.preparedTools=['TRPG_TACTICAL_LEVITATOR'];r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});r.action('COMBAT',{card:'TOOL:TRPG_TACTICAL_LEVITATOR'});const b=r.s.runtime;assert(b.fields.some(f=>f.kind==='BOMBARD'));const start=b.log.length;r.tickFields('END');const events=b.log.slice(start).filter(x=>x.actor===r.combatActor('MOND_KLEE').name&&(x.damage!==undefined||x.miss));assert.equal(events.length,4);});
test('Jean source skills are available against movement-immune boss and heal field executes',()=>{const r=fixture(['MOND_JEAN']);r.s.chars.MOND_JEAN.hp=500;r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});if(!r.combatActor('MOND_JEAN').cooldowns.MOND_JEAN_Q)r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});assert(r.combatActor('MOND_JEAN').cooldowns.MOND_JEAN_Q>0);assert(r.s.runtime.fields.some(f=>f.kind==='DANDELION'));assert(r.s.runtime.log.some(e=>e.actor==='진'&&e.heal>0));});
test('party slot gap preserves slot3 maxHP bonus rather than compressing to slot2 crit',()=>{const r=fixture([]);r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify({MOND_AMBER:{state:'JOINED'}});r.action('PARTY',{char:'MOND_AMBER',slot:3});const baseChar=r.character('MOND_AMBER');r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});const actor=r.combatActor('MOND_AMBER');assert.equal(actor.slot,3);assert.equal(actor.maxHp,Math.round(baseChar.maxHp*1.05));assert.equal(actor.crit,baseChar.crit);});
test('Mona bubble and omen run against boss; unknown weak-target classification disables other cases',()=>{const r=fixture(['MOND_MONA']);r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});const boss=r.s.runtime.actors.find(a=>a.side==='ENEMY'),mona=r.combatActor('MOND_MONA');assert(boss.statuses.some(s=>s.id==='ILLUSORY_BUBBLE'));const before=boss.hp;r.damage(mona,boss,.1,'PHYSICAL',{range:'원거리',sureHit:true,noCrit:true});assert(boss.hp<before);assert(!boss.statuses.some(s=>s.id==='ILLUSORY_BUBBLE'));assert(boss.statuses.some(s=>s.id==='OMEN'));});
console.log(JSON.stringify(results,null,2));fs.writeFileSync(__dirname+'/extra-card-test-results.json',JSON.stringify(results,null,2));if(results.some(r=>!r.ok))process.exitCode=1;
