'use strict';
// Native construction, save and numeric contracts. These are not clear-rate,
// natural acquisition, graphical browser or battle-difficulty simulations.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const H=require('../tools/audit_protagonist_v01618.cjs'),ROOT=path.resolve(__dirname,'..');
const copy=x=>JSON.parse(JSON.stringify(x)),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const NativeDate=Date,NOW=1791615600000,FixedDate=class extends NativeDate{constructor(...args){super(...(args.length?args:[NOW]));}static now(){return NOW;}};
const AUTHORED_DB_SHA256='dcc2800000f20684e2c57420404aa3a3a7fe68b9042c608306ba2ec62bd178da';
const BEFORE_FINGERPRINT='b69a8b91e0d0df86e2e9adc4edf1ab0493e0ff26354c7a3e026b1884ae7b9159';
const CURRENT_EXP60_XP=24000;
const PRIOR_TALENT_BOOKS={MOND:{5:1,10:2,15:10,20:20,25:32},LIYUE:{30:3,35:4,40:7,45:9,50:19,55:28,60:80}};
// Independent, published 0.16.26 native repeat-challenge anchors. Do not derive
// expected numbers from the current profile API or substitute a historical QA DB.
const BEFORE_ANCHORS={
 FB_ANEMO_HYPOSTASIS:[18,18000,1600,180],FB_ELECTRO_HYPOSTASIS:[20,16000,1700,210],
 FB_CRYO_REGISVINE:[22,26000,1950,220],FB_CRYO_HYPOSTASIS:[30,30000,1850,294],
 FB_PYRO_REGISVINE:[38,60000,4000,460],FB_OCEANID:[40,40457,4000,430],
 FB_GEO_HYPOSTASIS:[45,52113,4117,508],FB_PRIMO_GEOVISHAP:[48,64000,5500,570],
 FB_RUIN_SERPENT:[56,83496,8500,700],BOSS_ANDRIUS:[25,20094,2055,236],
 BOSS_DVALIN:[28,42540,3744,270],BOSS_TARTAGLIA:[50,125761,9703,591],
 BOSS_AZHDAHA:[60,137874,13189,778]
};
// Independently reviewed final target profiles, with their existing phase/profile
// rounding followed by K(level)/100 DEF rounding. These are not copied from API output.
const FINAL_ANCHORS={
 FB_ANEMO_HYPOSTASIS:[18,19800,1760,198],FB_ELECTRO_HYPOSTASIS:[20,16800,1785,210],
 FB_CRYO_REGISVINE:[22,28600,2048,231],FB_CRYO_HYPOSTASIS:[30,33000,2128,323],
 FB_PYRO_REGISVINE:[38,63000,4200,555],FB_OCEANID:[40,48548,4800,591],
 FB_GEO_HYPOSTASIS:[45,57324,4940,801],FB_PRIMO_GEOVISHAP:[48,70400,6050,987],
 FB_RUIN_SERPENT:[56,91846,9350,1507],BOSS_ANDRIUS:[25,20094,2466,248],
 BOSS_DVALIN:[28,42540,4492,270],BOSS_TARTAGLIA:[50,144625,16010,1241],
 BOSS_AZHDAHA:[60,151661,18465,1926]
};
const FIELD_SHIELD_PRESSURE={FB_ANEMO_HYPOSTASIS:2,FB_ELECTRO_HYPOSTASIS:2,FB_CRYO_REGISVINE:2,FB_CRYO_HYPOSTASIS:2,FB_PYRO_REGISVINE:2,FB_OCEANID:2,FB_GEO_HYPOSTASIS:3,FB_PRIMO_GEOVISHAP:1.5,FB_RUIN_SERPENT:4};
// Reviewed common budgets, independent of the exported runtime configuration.
const COMMON_POLICY={ordinary:{hp:1.4,atk:3.2,def:1.5},TALENT:{hp:1.5,atk:2.2,def:1.75},ASCENSION:{hp:1.5,atk:1.3,def:1.4},EXP:{hp:1.05,atk:1.08,def:1.1}};
const LEVEL_WEIGHTS={5:0,20:0,25:.125,27:.175,30:.25,35:.4,40:.55,50:.8,60:1};
const ORDINARY_ATTACK_MULTIPLIERS={5:1,20:1,25:1.075,27:1.105,30:1.15,35:1.68,40:2.21,50:2.76,60:3.2};
function productionBootstrap(env){if(!env.R.prototype.__relationshipsInstalled){const rel=env.c?.CRPGRelationships;assert(rel,'native production relationship bootstrap is available');rel.install(env.api,{events:rel.catalogFromDB(env.db),activities:rel.activitiesFromDB(env.db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});}return env;}
function specifications(api){const field=Object.keys(api.fieldBosses.bosses).map(source=>({source,kind:'FIELD',level:BEFORE_ANCHORS[source][0],map:api.fieldBosses.bosses[source].map,group:api.fieldBosses.group(source),origin:'BOSS:'+api.fieldBosses.route(source)}));return [...field,...['BOSS_ANDRIUS','BOSS_DVALIN'].map(source=>({...api.enhancementConfig.bosses[source],source,kind:'MOND',level:BEFORE_ANCHORS[source][0],origin:'MATERIAL_CHALLENGE:'+source})),...Object.entries(api.liyueArtifactConfig.farm).map(([kind,f])=>({source:kind==='TARTAGLIA'?'BOSS_TARTAGLIA':'BOSS_AZHDAHA',kind:'LIYUE',farmKind:kind,level:BEFORE_ANCHORS[kind==='TARTAGLIA'?'BOSS_TARTAGLIA':'BOSS_AZHDAHA'][0],map:f.map,group:f.group,origin:'MATERIAL_CHALLENGE:'+f.key}))];}
function stats(a){return[a.level,a.maxHp,a.atk,a.def];}
function loadBefore(root=ROOT,before=path.join(root,'docs/data/balance_v01627/before')){
 const manifest=JSON.parse(fs.readFileSync(path.join(before,'source_manifest.json'),'utf8'));
 assert.equal(manifest.version,'0.16.26');assert.equal(manifest.commit,'7f33d2b34c48834c67c9134e2548d48932782e5c');assert.equal(manifest.rawDbSHA256,AUTHORED_DB_SHA256);
 const oldFile=relative=>{const overlay=path.join(before,relative);return fs.existsSync(overlay)?overlay:path.join(root,relative);};
 const entries=manifest.entries;assert(Array.isArray(entries)&&entries.length>100,'full native source load closure proof is required');
 const expected=new Map(entries.map(e=>[e.path,e.sha256]));assert.equal(expected.size,entries.length,'unique historical source identities');
 for(const e of entries)assert.equal(sha(fs.readFileSync(oldFile(e.path))),e.sha256,'immutable 0.16.26 native source: '+e.path);
 const index=fs.readFileSync(oldFile('source/index.html'),'utf8'),scripts=[...index.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)].map(x=>x[1]);
 for(const relative of ['source/index.html','source/presentation.js',...scripts.map(f=>'source/'+f)])assert(expected.has(relative),'manifest proves every actual historical loaded module: '+relative);
 const c=vm.createContext({console,Date:FixedDate,setTimeout,clearTimeout}),fingerprint=crypto.createHash('sha256');
 for(const file of scripts){const raw=fs.readFileSync(oldFile('source/'+file),'utf8');fingerprint.update(file);fingerprint.update(raw);vm.runInContext(raw,c,{filename:'0.16.26/'+file});}
 vm.runInContext(fs.readFileSync(oldFile('source/presentation.js'),'utf8'),c,{filename:'0.16.26/presentation.js'});
 const raw=fs.readFileSync(path.join(root,'content/db.json'));assert.equal(sha(raw),manifest.rawDbSHA256,'actual authored DB, never a historical QA replacement');fingerprint.update(raw);
 const id=fingerprint.digest('hex');assert.equal(id,BEFORE_FINGERPRINT,'complete genuine native 0.16.26 closure identity');return{c,api:c.CRPGRuntime,R:c.CRPGRuntime.Runtime,db:JSON.parse(raw),root,fingerprint:id,rawDbSHA256:sha(raw),baselineProof:{version:manifest.version,commit:manifest.commit,files:entries.length,manifestSHA256:sha(fs.readFileSync(path.join(before,'source_manifest.json')))}};
}
function run({env,beforeEnv,finalAnchors=FINAL_ANCHORS,expectedRevision=1,onCheck}={}){
 assert(env&&beforeEnv,'both actual current and genuine 0.16.26 native engines are required');
 for(const e of [env,beforeEnv])if(e.c)e.c.Date=FixedDate;
 productionBootstrap(env);productionBootstrap(beforeEnv);
 const hashes={current:sha(JSON.stringify(env.db)),before:sha(JSON.stringify(beforeEnv.db))},checks=[],specs=specifications(env.api),cache=new WeakMap(),curveRuntimes=new WeakMap();
 const check=(id,fn)=>{try{checks.push({id,passed:true,evidence:fn()});}catch(e){checks.push({id,passed:false,error:e.stack});}if(onCheck)onCheck(checks.at(-1),checks.length);if(global.gc)global.gc();};
 const curveRuntime=e=>{if(!curveRuntimes.has(e)){const r=new e.R(e.db);r.installGrowthContent();curveRuntimes.set(e,r);}return curveRuntimes.get(e);};
 const prepared=(e,spec,{level=spec.level,team=['MOND_AMBER','MOND_KAEYA','MOND_NOELLE'],gear='craft',enhance=level<30?3:6}={})=>{
  let entries=cache.get(e);if(!entries){entries=new Map();cache.set(e,entries);}const key=[spec.source,level,team.join(','),gear,enhance].join(':');
  if(entries.has(key))return new e.R(e.db,copy(entries.get(key)));
  const r=H.setup(e,{level,team,route:'ROUTE_TRAVELER',seed:717,map:spec.map,gear,enhance,talent:10});
  for(const i of r.s.inventory.filter(i=>i.equip)){i.enhancementCap=10;if(!r.enhancementHasGain(i))i.enhance=0;assert(!/^EQ_EX_|^EQ_ARTIFACT_|^EQ_FB_/.test(i.equip));}
  if(spec.kind==='MOND'){const flag=r.row('35_BOSS_ROUTE_DB',spec.route)[13];assert(flag);r.s.flags[flag]=true;}
  if(spec.kind==='LIYUE'&&spec.farmKind==='AZHDAHA')r.s.flags[r.row('35_BOSS_ROUTE_DB','BRT_AZHDAHA')[13]]=true;
  r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;for(const id of team)r.s.chars[id].hp=r.character(id).maxHp;
  entries.set(key,copy(r.s));return r;
 };
 const enter=(r,spec)=>{if(spec.kind==='FIELD'){const route=r.fieldBossCatalog().find(x=>x.id===spec.source).route;r.action('PLACE_ENTER',{place:'BOSS:'+route,mode:'BOSS'});r.action('BOSS_ROUTE',{route,entry:'DIRECT'});}else if(spec.kind==='MOND')r.action('MOND_MATERIAL_CHALLENGE',{boss:spec.source});else r.action('LIYUE_ARTIFACT_CHALLENGE',{kind:spec.farmKind});assert.equal(r.s.runtime?.origin,spec.origin);assert.equal(r.s.runtime.opening.state,'PENDING');assert(r.s.runtime.actors.every(a=>a.turns===0));return r;};
 const start=(e,spec,opts)=>enter(prepared(e,spec,opts),spec);
 const boss=(r,spec)=>{const a=r.s.runtime?.actors.find(a=>a.side==='ENEMY'&&a.source===spec.source);assert(a,'actual native boss '+spec.source);return a;};
 check('same_actual_authored_database_and_all_thirteen_species',()=>{assert.equal(hashes.current,hashes.before);assert.equal(env.rawDbSHA256||sha(fs.readFileSync(path.join(env.root||ROOT,'content/db.json'))),AUTHORED_DB_SHA256);assert.equal(specs.length,13);assert.deepEqual(specs.map(s=>s.source).sort(),Object.keys(BEFORE_ANCHORS).sort());assert.deepEqual(copy(finalAnchors),FINAL_ANCHORS,'external final evidence agrees with independently reviewed target table');return{rawDbSHA256:AUTHORED_DB_SHA256,species:13};});
 check('public_equipment_fixture_is_twelve_equipped_legal_ordinary_items',()=>{const r=prepared(env,specs.find(s=>s.source==='FB_CRYO_HYPOSTASIS')),items=r.s.inventory.filter(i=>i.equip&&i.equipped);assert.equal(items.length,12);const owners=['PLAYER_CUSTOM','MOND_AMBER','MOND_KAEYA','MOND_NOELLE'];for(const id of owners){const worn=items.filter(i=>i.owner===id);assert.equal(worn.length,3);assert.deepEqual(copy(worn.map(i=>i.category).sort()),['ACCESSORY','ARMOR','WEAPON']);assert(worn.every(i=>i.enhance===6));const t=r.talentLevels(id);assert.deepEqual(copy(t.base),{na:4,e:4,q:4});assert.equal(r.growth(id).talentCap,4);}return{items:items.map(i=>({owner:i.owner,id:i.equip,enhance:i.enhance,category:i.category})),baseTalentCap:4,preparation:'H.setup invokes public EQUIP; grants ownership, phase and initial resources only'};});
 check('actual_public_constellation_unlock_changes_legal_native_talents_and_effects',()=>{const r=prepared(env,specs.find(s=>s.source==='FB_CRYO_HYPOSTASIS')),id='MOND_NOELLE';r.giveItem('STELLA_'+id,6);for(let n=1;n<=6;n++){r.action('CONSTELLATION_UNLOCK',{char:id});assert.equal(r.constellationLevel(id),n);}assert.equal(r.itemCount('STELLA_'+id),0);const t=r.talentLevels(id);assert.deepEqual(copy(t.base),{na:4,e:4,q:4});assert.deepEqual([t.na,t.e,t.q],[4,7,7]);enter(r,specs.find(s=>s.source==='FB_CRYO_HYPOSTASIS'));const a=r.s.runtime.actors.find(a=>a.source===id);assert(r.consFx(a).some(f=>f.n===6));assert(r.premiumTalentMultiplier(a,'e')>r.premiumTalentMultiplier(a,'na'));return{constellation:6,base:copy(t.base),effective:[t.na,t.e,t.q],nativeFx:r.consFx(a).length};});
 check('future_enhancement_prices11_12_are_literal_with_all_other_published_configuration_unchanged',()=>{
  const prior=copy(beforeEnv.api.enhancementConfig),current=copy(env.api.enhancementConfig),expected=copy(prior);
  expected.mora[11]=14000;expected.mora[12]=18000;expected.ores[11]={ORE_WHITE_IRON:40,ORE_CRYSTAL:28};expected.ores[12]={ORE_WHITE_IRON:48,ORE_CRYSTAL:36};assert.deepEqual(current,expected,'only two future Mora/ore targets change; probabilities, downgrade, stats, caps and ascension stay published');
  assert.deepEqual(prior.mora,[0,80,120,180,390,760,1375,2400,4400,7500,12000,22400,40000]);assert.deepEqual(prior.success,[0,10000,9500,9000,8500,8000,7000,6000,5000,4000,3000,2500,2000]);assert.deepEqual(prior.down,[0,0,0,0,0,0,0,0,0,50,100,200,300]);assert.deepEqual(prior.primaryGrowth,[0,.05,.10,.15,.20,.25,.30,.35,.40,.45,.50,.65,.80]);
  const r=prepared(env,specs.find(s=>s.source==='FB_CRYO_HYPOSTASIS')),slot=r.giveEquipment('EQ_SWORD_RANCOUR'),inv=r.s.inventory.find(i=>i.slot===slot),rows=[];
  for(const[target,mora,white,crystal]of[[11,14000,40,28],[12,18000,48,36]]){inv.enhance=target-1;inv.enhancementCap=12;const q=r.enhancementQuote(slot);assert.equal(q.target,target);assert.deepEqual(copy(q.cost),{mora,items:{ORE_WHITE_IRON:white,ORE_CRYSTAL:crystal}});assert.equal(q.success,target===11?2500:2000);assert.equal(q.down,target===11?200:300);assert.equal(q.hold,10000-q.success-q.down);rows.push({target,cost:copy(q.cost),success:q.success,hold:q.hold,down:q.down});}
  return{rows,unchangedTargets0Through10:true,unchangedProbabilitiesDowngradeStatsCapsAndAscension:true,proof:'literal quotes/configuration only; native payment receipts are a separate audit'};
 });
 check('genuine_v01626_owned_plus11_plus12_inventory_and_stats_restore_without_repricing_or_charge',()=>{
  const rows=[];for(const level of[11,12]){const spec=specs.find(s=>s.source==='FB_CRYO_HYPOSTASIS'),old=prepared(beforeEnv,spec),slot=old.giveEquipment('EQ_SWORD_RANCOUR');old.action('EQUIP',{slot,owner:'PLAYER_CUSTOM'});const inv=old.s.inventory.find(i=>i.slot===slot);inv.enhance=level;inv.enhancementCap=12;old.recalculate();const oldStats=copy(old.equipmentStats('PLAYER_CUSTOM')),oldPlayer=copy(old.player()),save=JSON.parse(old.serialize()),loaded=new env.R(env.db,copy(save));
   assert.deepEqual(JSON.parse(loaded.serialize()),save,'previously owned legal enhancement levels, resources and all save fields are unchanged');assert.deepEqual(copy(loaded.equipmentStats('PLAYER_CUSTOM')),oldStats);assert.deepEqual(copy(loaded.player()),oldPlayer);assert.equal(loaded.s.global.MORA,save.global.MORA);assert.deepEqual(copy(loaded.s.inventory),copy(save.inventory));
   const state=loaded.serialize();loaded.view();assert.equal(loaded.serialize(),state,'preview never charges a previous enhancement');rows.push({level,slot,stats:oldStats,saveSHA256:sha(JSON.stringify(save)),exactPreviouslyOwnedState:true});}
  return{rows,ownershipFixture:'genuine native old runtime with declared previously owned +11/+12 equipment; actual paid receipt proof is separate',beforeFingerprint:beforeEnv.fingerprint};
 });
 check('unchanged_four_person_ally_growth_equipment_and_effective_defense_projection',()=>{
  const anchors={PLAYER_CUSTOM:[5607,1023.6,510],MOND_AMBER:[6034,957.6,607.6],MOND_KAEYA:[6782,1078,695.8],MOND_NOELLE:[7482,989.8,1012.2]},rows=[];
  for(const[e,label]of[[beforeEnv,'0.16.26'],[env,'current']]){const spec=specs.find(s=>s.source==='FB_CRYO_HYPOSTASIS'),r=prepared(e,spec);r.s.global.CURRENT_MAP_ID='MAP_MOND_FOREST';r.startBattle('EG_MOND_HILI_PATROL','EXPLICIT');const allies=r.s.runtime.actors.filter(a=>a.side==='ALLY');assert.equal(allies.length,4);for(const a of allies){const expected=anchors[a.source];assert(expected);for(const[i,n]of[a.maxHp,a.atk,a.def].entries())assert(Math.abs(n-expected[i])<1e-9,'independent native ally raw projection '+a.source);const def=expected[2]/Math.sqrt(1+.12*29+.003*29*29);assert(Math.abs(r.combatStat(a,'def')-def)<1e-9,'ally DEF-based skills retain the previous curve');rows.push({engine:label,source:a.source,maxHp:a.maxHp,atk:a.atk,def:a.def,effectiveDefense:def,talents:copy(r.talentLevels(a.source))});}}
  return{rows,preparation:'Traveler + Amber/Kaeya/Noelle, Lv30/phase2/base talents4, twelve crafted +6 items, default native formation; maximum HP projection only'};
 });
 for(const [scope,policy]of Object.entries(COMMON_POLICY))for(const grade of ['일반','정예','강적','보스'])check('common_grade_curve_native_projection:'+scope+':'+grade,()=>{
  const old=curveRuntime(beforeEnv),current=curveRuntime(env),source=old.rows('09_MONSTER_DB').find(row=>row[3]===grade);assert(source,'actual authored monster grade '+grade);const rows=[];
  const construct=row=>({id:'CURVE_'+row[0],source:row[0],side:'ENEMY',grade:row[3],hp:Number(row[6]),maxHp:Number(row[6]),atk:Number(row[7]),def:Number(row[8]),spd:Number(row[19]),hit:Number(row[20]),eva:Number(row[21]),resist:Number(row[22]),statuses:[],shields:[],cooldowns:{}});
  for(const[levelString,w]of Object.entries(LEVEL_WEIGHTS)){const level=Number(levelString),a=construct(source),b=construct(current.row('09_MONSTER_DB',source[0])),domain=scope==='ordinary'?undefined:{version:4,kind:scope,level},oldBattle={id:'GENUINE_OLD_CURVE',origin:'EXPLICIT',actors:[a],growthDomain:domain},newBattle={id:'NEW_CURVE',origin:'EXPLICIT',actors:[b],growthDomain:domain,enemyBalanceRevision:1};old.tuneGrowthEnemy(a,oldBattle,level);current.tuneGrowthEnemy(b,newBattle,level);const expected=[level,a.maxHp,a.atk,a.def];if(grade!=='보스'){expected[1]=Math.round(expected[1]*(1+(policy.hp-1)*w));expected[2]=Math.round(expected[2]*(scope==='ordinary'?ORDINARY_ATTACK_MULTIPLIERS[level]:(1+(policy.atk-1)*w)));expected[3]=Math.round(expected[3]*(1+(policy.def-1)*w));}expected[3]=Math.round(expected[3]*(100+5*Math.max(0,level-35))/100);assert.deepEqual(stats(b),expected,'selected common budget and independent level-defense scaling');rows.push({level,weight:w,before:stats(a),after:stats(b),expected});}
  return{source:source[0],grade,scope,policy,rows,probe:'native tune of grade actors constructed from actual DB rows; no authored encounter, party or victory claim'};
 });
 check('unmarked_old_future_wave_retains_prior_common_curve',()=>{
  const old=curveRuntime(beforeEnv),current=curveRuntime(env),row=old.rows('09_MONSTER_DB').find(row=>row[3]==='정예'),rows=[];
  for(const level of [30,50,60]){const make=()=>({id:'OLD_WAVE_'+row[0],source:row[0],side:'ENEMY',grade:row[3],hp:Number(row[6]),maxHp:Number(row[6]),atk:Number(row[7]),def:Number(row[8]),spd:Number(row[19]),hit:Number(row[20]),eva:Number(row[21]),resist:Number(row[22]),statuses:[],shields:[]}),a=make(),b=make();old.tuneGrowthEnemy(a,{id:'OLD_WAVE_BATTLE',origin:'EXPLICIT',actors:[a]},level);current.tuneGrowthEnemy(b,{id:'OLD_WAVE_BATTLE',origin:'EXPLICIT',actors:[b]},level);assert.deepEqual(stats(b),stats(a));rows.push({level,stats:stats(b)});}return{source:row[0],rows,probe:'unmarked future wave policy guard; genuine public saved battles are tested separately'};
 });
 if(expectedRevision!==undefined)for(const attackerLevel of [25,35,45,50,55,60])for(const side of ['ALLY','ENEMY'])check('independent_native_damage_packet_K_'+side+'_'+attackerLevel,()=>{
  const r=start(env,specs[0]),b=r.s.runtime;assert.equal(b.enemyBalanceRevision,1);assert.equal(b.defenseRevision,1);
  const targetLevel=50,K=100+5*Math.max(0,attackerLevel-35),targetK=175;
  // Fixed arithmetic inputs isolate the policy from character skills and random
  // outcomes. A native pre-absorption packet is captured, never a forced victory.
  const a={id:'FORMULA_ATTACKER',source:'FORMULA_SOURCE',side,level:attackerLevel,hp:10000,maxHp:10000,atk:1000,def:200,crit:0,critDmg:50,hit:100,eva:0,resist:0,range:'전장',grade:'일반',traits:{},statuses:[],shields:[],cooldowns:{},element:'물리'};
  const t={...copy(a),id:'FORMULA_TARGET',source:'FORMULA_TARGET',side:side==='ALLY'?'ENEMY':'ALLY',level:targetLevel,def:side==='ALLY'?350:200,atk:0,aura:null,nativeAura:null,guard:false,slotDamageMultiplier:1};
  b.actors=[a,t];b.fields=[];const ad=1+.12*49+.003*49*49,effectiveDefense=t.def/Math.sqrt(ad),expected=1000*.65*K/(K+effectiveDefense);
  assert.equal(r.combatDefenseBase(a,t),K);assert(Math.abs(r.combatStat(t,'def')-effectiveDefense)<1e-10);
  let actual;const apply=r.applyDamage,random=r.random;r.applyDamage=(_a,_t,n)=>{actual=n;return true;};r.random=()=>.5;
  try{r.damage(a,t,.65,'물리',{sureHit:true,noCrit:true,noAura:true,ignoreTaunt:true,covered:true,range:'전장',sourceKind:'NUMERIC_CONTRACT'});}finally{r.applyDamage=apply;r.random=random;}
  assert(Number.isFinite(actual));assert(Math.abs(actual-expected)<1e-8,'independent K, DEF normalization and native packet');
  if(side==='ALLY'&&attackerLevel===50){const beforeDefense=200/Math.sqrt(ad),sameLevelBefore=100/(100+beforeDefense),sameLevelAfter=K/(K+effectiveDefense);assert(Math.abs(sameLevelAfter-sameLevelBefore)<1e-12,'equal-level passing is algebraically preserved');}
  return{attackerLevel,targetLevel,side,K,targetK:side==='ALLY'?targetK:100,rawDefense:t.def,effectiveDefense,expected,actual,error:actual-expected,probe:'sure-hit, no-crit, mean variance, no buffs or reactions; direct packet only'};
 });
 for(const [ordinal,spec]of specs.entries()){
  check('genuine_v01626_literal_native_projection:'+spec.source,()=>{const r=start(beforeEnv,spec),a=boss(r,spec);assert.deepEqual(stats(a),BEFORE_ANCHORS[spec.source]);assert(a.growthScaled);return{origin:spec.origin,stats:stats(a),effectiveDefense:r.combatStat(a,'def')};});
  if(finalAnchors)check('final_literal_native_projection:'+spec.source,()=>{assert(finalAnchors[spec.source],'independently reviewed final anchor '+spec.source);const r=start(env,spec),a=boss(r,spec);assert.deepEqual(stats(a),finalAnchors[spec.source]);if(expectedRevision!==undefined)assert.equal(r.s.runtime.enemyBalanceRevision,expectedRevision);return{origin:spec.origin,stats:stats(a),effectiveDefense:r.combatStat(a,'def')};});
  check('admin_exact_final_override_and_opening_roll:'+spec.source,()=>{const seed=prepared(env,spec),config=env.api.adminBalance.emptyConfig(),values={hp:654321+ordinal,atk:3210+ordinal,def:456+ordinal,spd:90+ordinal};config.enemies[spec.source]=values;const r=env.api.adminBalance.createRuntime(env.db,copy(seed.s),{revision:100+ordinal,config});enter(r,spec);const a=boss(r,spec),b=r.s.runtime;assert.deepEqual([a.maxHp,a.hp,a.atk,a.def,a.spd],[values.hp,values.hp,values.atk,values.def,values.spd]);assert.equal(b.adminBalanceRevision,100+ordinal);assert.equal(b.order[0].id,'PLAYER_CUSTOM');assert.deepEqual(copy(b.order),copy(b.opening.initialOrder));for(const enemy of b.actors.filter(a=>a.side==='ENEMY'&&!a.fbSummon)){const q=b.order.find(q=>q.id===enemy.id),roll=q.score-r.combatStat(enemy,'spd');assert(roll>=0&&roll<=9,'one native die plus final effective speed');}const saved=JSON.parse(r.serialize()),loaded=env.api.adminBalance.createRuntime(env.db,copy(saved),{revision:100+ordinal,config});assert.deepEqual(copy(loaded.s.runtime),copy(saved.runtime));const order=copy(b.order),rng=r.s.global.PRNG_STATE;r.view();r.combatOpening();assert.deepEqual(copy(b.order),order);assert.equal(r.s.global.PRNG_STATE,rng);const receipt=r.action('COMBAT_BEGIN');assert.deepEqual(copy(receipt.result.initialOrder),order);assert.equal(r.s.runtime.turnStarted,'1:PLAYER_CUSTOM');assert.equal(r.s.global.PRNG_STATE,rng);return{values,initialOrder:order,loadAndPreviewDoNotReroll:true};});
  for(const boundary of ['PENDING','WAIT_PLAYER'])check('genuine_v01626_saved_rules_and_native_resume:'+spec.source+':'+boundary,()=>{
   const old=start(beforeEnv,spec);
   if(boundary==='WAIT_PLAYER'){old.action('COMBAT_BEGIN');if(spec.source!=='BOSS_DVALIN'){const wind=old.combatCards().find(c=>c.id==='SYS_MOND_WIND_ROUTE'&&!c.reason);if(wind)old.action('COMBAT',{card:wind.id,target:wind.targets[0].id});const card=old.combatCards().find(c=>c.id==='PLAYER_TRAVELER_ANEMO_E'&&!c.reason);assert(card,'native player skill remains legal');const enemies=old.s.runtime.actors.filter(a=>a.side==='ENEMY'&&a.hp>0),target=card.targets.find(t=>enemies.some(a=>a.id===t.id));assert(target);old.action('COMBAT',{card:card.id,target:target.id,branch:'HOLD'});assert(old.s.runtime,'genuine native old fight remains ongoing');assert.equal(old.s.runtime.phase,'WAIT_PLAYER');assert.equal(old.s.runtime.opening.state,'STARTED');assert(old.s.runtime.actors.some(a=>Object.values(a.cooldowns||{}).some(n=>n>0)));}else{assert.equal(old.s.runtime.opening.state,'STARTED');assert.equal(old.s.runtime.phase,'WAIT_PLAYER');}}
   const saved=JSON.parse(old.serialize()),loaded=new env.R(env.db,copy(saved)),legacy=new beforeEnv.R(beforeEnv.db,copy(saved));assert.equal(saved.runtime.enemyBalanceRevision,undefined,'genuine 0.16.26 battle is unmarked');assert.deepEqual(copy(loaded.s.runtime),copy(saved.runtime));assert.equal(loaded.s.global.PRNG_STATE,saved.global.PRNG_STATE);assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(legacy.serialize()));
   if(boundary==='PENDING'){legacy.action('COMBAT_BEGIN');loaded.action('COMBAT_BEGIN');}else{legacy.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});loaded.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});}
   assert.deepEqual(copy(loaded.s.runtime),copy(legacy.s.runtime),'one actual resumed action retains old damage, fields, shields, statuses, cooldowns and initiative');assert.equal(loaded.s.global.PRNG_STATE,legacy.s.global.PRNG_STATE);assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(legacy.serialize()),'full native resumed save including settlement');return{boundary,preparation:spec.source==='BOSS_DVALIN'&&boundary==='WAIT_PLAYER'?'native BEGIN then first WAIT; other fights use an actual player skill and nonzero cooldown':'native public entry/action',oldEngineFingerprint:beforeEnv.fingerprint,savedRuntimeSHA256:sha(JSON.stringify(saved.runtime)),nativeResume:true};
  });
 }
 // These authored three-round evacuation objectives already have an explicit
 // integrity/action budget. Their genuine native policy is excluded before
 // startBattle's first projection as well as after fieldObjective is attached.
 const protectedFields=[{mission:'reed',stage:1,kind:'ESCORT',map:'MAP_LY_DETAIL_DIHUA'},{mission:'guyun',stage:1,kind:'DEFEND',map:'MAP_LY_DETAIL_GUYUN'}];
 const startProtectedField=(e,spec)=>{
  const r=H.setup(e,{level:48,team:['MOND_AMBER','MOND_KAEYA','MOND_BARBARA'],route:'ROUTE_ISEKAI',seed:12,map:spec.map,gear:'craft',enhance:6,talent:6});
  const placement=e.c.CRPGLiyueRework.placements.find(p=>p.mission===spec.mission);assert(placement);r.storySetCursor('R39_FIELD_'+placement.anchor);r.prepareStory();
  const f=r.s.liyueField;assert(f);f.mission=spec.mission;f.stage=spec.stage;f.steps=Array.from({length:spec.stage},(_,stage)=>({stage}));r.s.global.CURRENT_MAP_ID=r.liyueFieldView().target;
  assert.equal(r.liyueFieldView().step.kind,spec.kind);r.s.global.PRNG_STATE=12;r.action('LIYUE_FIELD_BATTLE');assert.equal(r.s.runtime.fieldObjective.kind,spec.kind);return r;
 };
 for(const spec of protectedFields){
  check('new_native_protected_field_excludes_policy_before_projection_and_initiative:'+spec.kind,()=>{
   const old=startProtectedField(beforeEnv,spec),current=startProtectedField(env,spec),a=old.s.runtime,b=current.s.runtime;
   assert.equal(a.enemyBalanceRevision,undefined);assert.equal(b.enemyBalanceRevision,undefined);assert.equal(b.opening.state,'PENDING');
   assert.deepEqual(copy(b.actors),copy(a.actors),'all native actor projections, equipment, shields and starting statuses retain the existing objective budget');
   assert.deepEqual(copy(b.order),copy(a.order),'first effective speed and native initial rolls stay within the same old objective policy');assert.deepEqual(copy(b.fieldObjective),copy(a.fieldObjective));assert.equal(current.s.global.PRNG_STATE,old.s.global.PRNG_STATE);
   assert.deepEqual(JSON.parse(current.serialize()),JSON.parse(old.serialize()),'complete new native protected encounter agrees with the genuine source engine');
   return{kind:spec.kind,mission:spec.mission,marker:null,actors:b.actors.map(a=>({source:a.source,side:a.side,stats:stats(a)})),exactNativeBeforeProjectionAndInitiative:true};
  });
  check('new_native_protected_field_save_restores_exactly_and_rejects_unpublished_marker:'+spec.kind,()=>{
   const r=startProtectedField(env,spec),save=JSON.parse(r.serialize()),loaded=new env.R(env.db,copy(save));assert.deepEqual(JSON.parse(loaded.serialize()),copy(save));assert.equal(loaded.s.runtime.enemyBalanceRevision,undefined);
   const invalid=copy(save);invalid.runtime.enemyBalanceRevision=1;assert.throws(()=>new env.R(env.db,invalid),e=>e.code==='ENEMY_BALANCE_SAVE','unpublished accidentally marked candidate is not a genuine historical policy');
   r.action('COMBAT_BEGIN');loaded.action('COMBAT_BEGIN');assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(r.serialize()));
   return{kind:spec.kind,exactNativeRestoreAndBegin:true,unsupportedScopeRejected:true};
  });
  for(const boundary of ['PENDING','WAIT_PLAYER'])check('genuine_v01626_protected_field_save_and_native_resume:'+spec.kind+':'+boundary,()=>{
   const old=startProtectedField(beforeEnv,spec);if(boundary==='WAIT_PLAYER'){old.action('COMBAT_BEGIN');old.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});assert(old.s.runtime);assert.equal(old.s.runtime.phase,'WAIT_PLAYER');}
   const save=JSON.parse(old.serialize()),loaded=new env.R(env.db,copy(save));assert.equal(save.runtime.enemyBalanceRevision,undefined);assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(old.serialize()));
   const action=boundary==='PENDING'?'COMBAT_BEGIN':'COMBAT';old.action(action,action==='COMBAT'?{card:'PLAYER_BASIC_GUARD'}:{});loaded.action(action,action==='COMBAT'?{card:'PLAYER_BASIC_GUARD'}:{});
   assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(old.serialize()),'native continued actors, initiative, integrity, damage, result and PRNG match genuine 0.16.26');
   return{kind:spec.kind,boundary,oldEngineFingerprint:beforeEnv.fingerprint,savedRuntimeSHA256:sha(JSON.stringify(save.runtime)),fullNativeResumeAndPRNG:true};
  });
 }
 const dvalinSpec=specs.find(s=>s.source==='BOSS_DVALIN'),WIND='SYS_MOND_WIND_ROUTE',ACCESS='EXPLICIT_ACCESS_TO_BOSS_DVALIN';
 check('new_Dvalin_rematch_has_no_wind_card_or_direct_execution_after_start_and_restore',()=>{
  const rows=[];for(const boundary of ['PENDING','STARTED']){const r=start(env,dvalinSpec);if(boundary==='STARTED')r.action('COMBAT_BEGIN');assert.equal(r.s.runtime.mondBossBalance.rematchNoWindRevision,1);assert.equal(r.s.runtime.mondBossBalance.windRoute,false);assert(!r.combatCards().some(c=>c.id===WIND));const save=JSON.parse(r.serialize()),loaded=new env.R(env.db,copy(save));assert.deepEqual(copy(loaded.s.runtime),copy(save.runtime));assert(!loaded.combatCards().some(c=>c.id===WIND));const state=loaded.serialize();assert.throws(()=>loaded.executeCombatSystem(loaded.combatActor(),WIND,'PLAYER_CUSTOM'),e=>e.code==='BOSS_WIND_ROUTE');assert.equal(loaded.serialize(),state);assert.throws(()=>loaded.action('COMBAT',{card:WIND,target:'PLAYER_CUSTOM'}),e=>e.code===(boundary==='PENDING'?'ACTION_LOCK':'CARD'));assert.equal(loaded.serialize(),state,'rejected public wind is atomic');assert(loaded.s.runtime.actors.filter(a=>a.side==='ALLY').every(a=>!a.statuses.some(s=>s.id===ACCESS)));rows.push({boundary,marker:1,cardHidden:true,directAndPublicExecutionRejected:true,exactRestoreAndAtomicity:true});}return{rows};
 });
 check('genuine_old_Dvalin_rematch_keeps_public_wind_action_and_exact_native_resume',()=>{
  const old=start(beforeEnv,dvalinSpec,{enhance:6}),save=JSON.parse(old.serialize()),loaded=new env.R(env.db,copy(save));assert.equal(save.runtime.mondBossBalance.rematchNoWindRevision,undefined);for(const r of [old,loaded]){r.action('COMBAT_BEGIN');const card=r.combatCards().find(c=>c.id===WIND);assert(card&&!card.reason);r.action('COMBAT',{card:WIND,target:card.targets[0].id});assert(r.s.runtime,'native old wind fixture remains ongoing');assert.equal(r.s.runtime.mondBossBalance.windRoute,true);assert(r.s.runtime.actors.filter(a=>a.side==='ALLY').every(a=>a.statuses.some(s=>s.id===ACCESS)));}assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(old.serialize()));return{genuineOldFlag:null,nativeWindCast:true,accessStatus:ACCESS,fullStateAndPRNGExactlyPreserved:true};
 });
 check('authored_Traveler_Dvalin_story_gate_preserves_its_public_wind_route',()=>{
  const r=prepared(env,dvalinSpec,{enhance:6}),node='TRV_M02_N371',row=r.rows('55_MAIN_STORY_DB').find(row=>row[4]===node);assert.equal(row[5],'COMBAT_GATE');assert.match(row[12],/START_FIXED_COMBAT:EG_BOSS_DVALIN/);r.storySetCursor(node);r.prepareStory();r.action('STORY_NEXT',{node});r.action('PREP_SELECT',{group:'EG_BOSS_DVALIN',companions:['MOND_AMBER','MOND_KAEYA','MOND_NOELLE']});r.action('COMBAT_PREPARE',{group:'EG_BOSS_DVALIN'});assert.equal(r.s.runtime.origin,'STORY:'+node);assert.equal(r.s.runtime.mondBossBalance.rematchNoWindRevision,undefined);r.action('COMBAT_BEGIN');const wind=r.combatCards().find(c=>c.id===WIND);assert(wind&&!wind.reason);r.action('COMBAT',{card:WIND,target:wind.targets[0].id});assert(r.s.runtime);assert.equal(r.s.runtime.mondBossBalance.windRoute,true);assert(r.s.runtime.actors.some(a=>a.side==='ALLY'&&a.statuses.some(s=>s.id===ACCESS)));return{node,actualAuthoredGate:true,publicPreparationAndWindCast:true,fixtures:'granted levels, gear, owned party and story cursor; not a complete campaign or story difficulty proof'};
 });
 check('new_Dvalin_rematch_retains_ranged_access_public_tactical_float_and_15pct_close_penalty',()=>{
  const r=prepared(env,dvalinSpec,{enhance:6});r.giveItem('TRPG_TACTICAL_LEVITATOR',1);r.action('TOOL_PREPARE',{items:['TRPG_TACTICAL_LEVITATOR']});enter(r,dvalinSpec);r.action('COMBAT_BEGIN');const a=r.combatActor(),t=boss(r,dvalinSpec),basic=r.combatCards().find(c=>c.id==='PLAYER_BASIC_ATTACK');assert(t.airborne);assert.match(basic.reason,/원거리.*대공.*부유/);assert.doesNotMatch(basic.reason,/상승 기류|바람길/);assert.equal(basic.targets.length,0);for(const range of ['근접','중거리'])assert.equal(r.hasAirAccess(a,t,range),false);for(const range of ['원거리','전장','대공','부유'])assert.equal(r.hasAirAccess(a,t,range),true);
  r.action('COMBAT',{card:'TOOL:TRPG_TACTICAL_LEVITATOR',target:a.id});assert(r.s.runtime,'actual public float fixture remains ongoing');const live=r.combatActor(),target=boss(r,dvalinSpec);assert(live.statuses.some(s=>s.id==='STATUS_TACTICAL_LEVITATION'));assert.equal(r.s.runtime.toolCharges.TRPG_TACTICAL_LEVITATOR,2);assert.equal(r.s.runtime.mondBossBalance.windRoute,false);assert.equal(r.combatCards().find(c=>c.id==='PLAYER_BASIC_ATTACK').reason,'');assert(r.combatCards().find(c=>c.id==='PLAYER_BASIC_ATTACK').targets.some(t=>t.id===target.id));for(const range of ['근접','중거리'])assert.equal(r.hasAirAccess(live,target,range),true);
  const damage=r.applyDamage,random=r.random,packets={};r.applyDamage=(_a,_t,n)=>{packets.active=n;return true;};r.random=()=>.5;try{for(const range of ['원거리','근접']){packets.active=undefined;assert.equal(r.damage(live,target,.65,'물리',{range,sureHit:true,noCrit:true,noAura:true,ignoreTaunt:true,covered:true,sourceKind:'NUMERIC_CONTRACT'}),true);packets[range]=packets.active;assert(Number.isFinite(packets[range]));}}finally{r.applyDamage=damage;r.random=random;}assert(Math.abs(packets.근접-packets.원거리*.85)<1e-8);return{normalRangedAccess:true,publicToolPreparedAndConsumed:true,remainingCharges:2,tacticalClosePacket:packets.근접,rangedPacket:packets.원거리,closeMultiplier:.85,probe:'native access and deterministic pre-absorption packet after one real public float action; no win claim'};
 });
 check('Dvalin_rematch_wind_flag_rejects_invalid_values_scopes_or_wind_state',()=>{
  const save=JSON.parse(start(env,dvalinSpec).serialize()),rejected=[];for(const value of [0,2,-1,'1',null]){const bad=copy(save);bad.runtime.mondBossBalance.rematchNoWindRevision=value;assert.throws(()=>new env.R(env.db,bad),e=>e.code==='BOSS_BALANCE_SAVE');rejected.push({value});}const wind=copy(save);wind.runtime.mondBossBalance.windRoute=true;assert.throws(()=>new env.R(env.db,wind),e=>e.code==='BOSS_BALANCE_SAVE');const story=copy(save);story.runtime.origin='STORY:TRV_M02_N371';delete story.runtime.dailyPressureRevision;assert.throws(()=>new env.R(env.db,story),e=>e.code==='BOSS_BALANCE_SAVE');const andrius=JSON.parse(start(env,specs.find(s=>s.source==='BOSS_ANDRIUS')).serialize());andrius.runtime.mondBossBalance.rematchNoWindRevision=1;assert.throws(()=>new env.R(env.db,andrius),e=>e.code==='BOSS_BALANCE_SAVE');return{invalidValues:rejected,windAlreadyTrueRejected:true,storyAndOtherBossRejected:true};
 });
 const absorption=(r,a,{shielded=false,card='FB_NUMERIC_CONTRACT',sourceKind}={})=>{const t=r.s.runtime.actors.find(a=>a.source==='PLAYER_CUSTOM');assert(t);t.hp=t.maxHp;t.guard=false;t.shields=[];if(shielded)r.shield(t,10000,'NUMERIC_PRESSURE_SHIELD',2);const hp=t.hp,value=t.shields.reduce((n,s)=>n+s.value,0),details={element:'물리',range:'전장',covered:true,card,...(sourceKind?{sourceKind}:{})};r.applyDamage(a,t,1000,details);return{hpDamage:hp-t.hp,shieldDamage:value-t.shields.reduce((n,s)=>n+s.value,0)};};
 for(const spec of specs.filter(s=>s.kind==='FIELD'))check('field_pressure_direct_shield_only_and_packet_scope:'+spec.source,()=>{
  const old=start(beforeEnv,spec),current=start(env,spec),oa=boss(old,spec),ca=boss(current,spec),factor=FIELD_SHIELD_PRESSURE[spec.source],rows=[];
  assert.equal(old.s.runtime.fieldBoss.pressureRevision,undefined);assert.equal(current.s.runtime.fieldBoss.pressureRevision,1);assert.equal(current.s.runtime.fieldBoss.behaviorRevision,5);
  for(const options of [{shielded:false},{shielded:true},{shielded:true,sourceKind:'REACTION'},{shielded:true,sourceKind:'FIELD'},{shielded:true,sourceKind:'OBJECT'},{shielded:true,card:'UNRELATED_NUMERIC_CONTRACT'}]){const before=absorption(old,oa,options),after=absorption(current,ca,options);assert.equal(after.hpDamage,before.hpDamage,'shield policy does not multiply bare HP packets');const expected=options.shielded&&!options.sourceKind&&!options.card?before.shieldDamage*factor:before.shieldDamage;assert(Math.abs(after.shieldDamage-expected)<=1,'only direct same-boss FB packets drain the declared shield budget');rows.push({options,before,after,expectedShieldDamage:expected});}
  const save=JSON.parse(current.serialize());for(const value of [0,2,-1,'1',null]){const bad=copy(save);bad.runtime.fieldBoss.pressureRevision=value;assert.throws(()=>new env.R(env.db,bad),e=>e.code==='FIELD_BOSS_SAVE');}
  return{factor,rows,unsupportedMarkerValues:[0,2,-1,'1',null],probe:'native applyDamage with fixed 1000 input, normal armor and shields; no victory or full-move damage claim'};
 });
 check('field_move_pressure_coefficients_and_excluded_source_kinds',()=>{const evidence=[];for(const[source,moves]of Object.entries({FB_GEO_HYPOSTASIS:{ROCKFALL:1.5,UPHEAVAL:1.5},FB_PRIMO_GEOVISHAP:{BEAM:1.15}})){const spec=specs.find(s=>s.source===source);for(const[e,label]of[[beforeEnv,'0.16.26'],[env,'current']]){const r=start(e,spec),a=boss(r,spec),t=r.s.runtime.actors.find(a=>a.source==='PLAYER_CUSTOM'),native=r.damage,records=[];r.damage=(_a,_t,k,_el,o)=>{records.push({k,card:o.card,sourceKind:o.sourceKind??null});return true;};try{for(const[move,factor]of Object.entries(moves))for(const sourceKind of [undefined,'REACTION','FIELD']){r.fbHit(a,t,.65,'물리',{move,...(sourceKind?{sourceKind}:{})});const q=records.at(-1),expected=.65*(label==='current'&&!sourceKind?factor:1);assert(Math.abs(q.k-expected)<1e-12);evidence.push({engine:label,source,move,sourceKind:sourceKind??null,k:q.k,expected});}}finally{r.damage=native;}}}return{evidence,probe:'native fbHit coefficient captured at its existing damage call; packet formula is independently tested elsewhere'};});
 check('oceanid_owned_summon_pressure_and_initial_body_scaling',()=>{
  const spec=specs.find(s=>s.source==='FB_OCEANID'),old=start(beforeEnv,spec),current=start(env,spec),boar=current.s.runtime.actors.find(a=>a.source==='FB_MIMIC_BOAR'),oldBoar=old.s.runtime.actors.find(a=>a.source==='FB_MIMIC_BOAR');assert(boar&&oldBoar);assert.equal(boar.fbSummon.owner,boss(current,spec).id);assert.equal(boar.level,40);assert.equal(boar.maxHp,Math.round(1218/5*(1+.13*39+.002*39*39)*1.48));assert.equal(boar.atk,4320);assert.equal(boar.def,768);const before=absorption(old,oldBoar,{shielded:true}),after=absorption(current,boar,{shielded:true});assert.equal(after.hpDamage,before.hpDamage);assert(Math.abs(after.shieldDamage-before.shieldDamage*2)<=1);return{beforeBody:stats(oldBoar),afterBody:stats(boar),before,after,shieldFactor:2,bodyBudget:1218};
 });
 check('fresh_crab_shell_initial_maximum_scales_with_value_and_old_future_spawn_stays_exact',()=>{
  const spec=specs.find(s=>s.source==='FB_OCEANID'),current=start(env,spec),crab=current.fbSummon(current.s.runtime,boss(current,spec),'FB_MIMIC_CRAB'),shell=crab.shields.find(s=>s.source==='FB_CRAB_SHELL');
  assert.equal(crab.maxHp,Math.round(1050/5*(1+.13*39+.002*39*39)*1.48));assert.equal(crab.maxHp,2832);assert(shell);assert.equal(shell.value,708);assert.equal(shell.initialValue,708,'fresh shell starts at its full displayed maximum');assert.deepEqual(copy(shell.damageMultipliers),{번개:2,얼음:1.5});
  const freshSave=JSON.parse(current.serialize()),freshLoad=new env.R(env.db,copy(freshSave));assert.deepEqual(copy(freshLoad.s.runtime),copy(freshSave.runtime));
  const old=start(beforeEnv,spec),oldSave=JSON.parse(old.serialize()),loaded=new env.R(env.db,copy(oldSave));assert.equal(oldSave.runtime.enemyBalanceRevision,undefined);assert.equal(oldSave.runtime.fieldBoss.pressureRevision,undefined);
  const oldCrab=old.fbSummon(old.s.runtime,boss(old,spec),'FB_MIMIC_CRAB'),loadedCrab=loaded.fbSummon(loaded.s.runtime,boss(loaded,spec),'FB_MIMIC_CRAB'),oldShell=oldCrab.shields.find(s=>s.source==='FB_CRAB_SHELL');
  assert.equal(oldCrab.maxHp,2360);assert.equal(oldShell.value,590);assert.equal(oldShell.initialValue,818,'existing unmarked battle preserves its genuine old future-summon policy');assert.deepEqual(copy(loadedCrab),copy(oldCrab));assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(old.serialize()));
  return{fresh:{maxHp:crab.maxHp,shield:copy(shell)},genuineOldFuture:{maxHp:oldCrab.maxHp,shield:copy(oldShell)},nativeSavedPolicyPreserved:true,probe:'actual native crab spawn after public entry; spawn only, no victory or encounter outcome claim'};
 });
 check('genuine_old_geo_future_summons_and_shield_pressure_stay_unchanged',()=>{
  const spec=specs.find(s=>s.source==='FB_GEO_HYPOSTASIS'),old=start(beforeEnv,spec),saved=JSON.parse(old.serialize()),loaded=new env.R(env.db,copy(saved));assert.equal(saved.runtime.enemyBalanceRevision,undefined);assert.equal(saved.runtime.fieldBoss.pressureRevision,undefined);const oa=boss(old,spec),ca=boss(loaded,spec);old.fbSummon(old.s.runtime,oa,'FB_SUMMON_PILLAR');loaded.fbSummon(loaded.s.runtime,ca,'FB_SUMMON_PILLAR');assert.deepEqual(copy(loaded.s.runtime),copy(old.s.runtime),'new future summons in a genuine old field fight keep old level DEF and HP');const before=absorption(old,oa,{shielded:true}),after=absorption(loaded,ca,{shielded:true});assert.deepEqual(after,before);assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(old.serialize()));return{oldBehavior:5,pressureMarker:null,summons:copy(loaded.s.runtime.actors.filter(a=>a.fbSummon).map(a=>({id:a.id,stats:stats(a)}))),before,after};
 });
 const expSpec={source:'EXP60_CONTRACT',kind:'DOMAIN',level:56,map:'MAP_CHASM_DEEP'};
 const expStart=e=>{const r=prepared(e,expSpec),entry=r.growthDomainEntries().find(d=>d.id==='LOST_VALLEY:60');assert(entry&&!entry.reason);const preview=r.growthDomainRewards(entry,'NEUTRAL');r.action('DOMAIN_START',{domain:entry.id});assert.equal(r.s.runtime.growthDomain.kind,'EXP');assert.equal(r.s.runtime.growthDomain.version,4);return{r,entry,preview};};
 const settleExp=(r,xp)=>{const daily=copy(r.s.domainDaily),books=r.itemCount('MAT_CHAR_EXP_HERO'),ids=['PLAYER_CUSTOM','MOND_AMBER','MOND_KAEYA','MOND_NOELLE'];assert.equal(r.mondRewardPlan(r.s.runtime).xp,xp);for(const a of r.s.runtime.actors.filter(a=>a.side==='ENEMY'))a.hp=0;const result=r.finishBattle(true);assert.equal(result.xp,xp);assert.deepEqual(copy(result.domain.items),{});assert.equal(r.itemCount('MAT_CHAR_EXP_HERO'),books);for(const id of ids){assert.equal(r.growth(id).xp,xp);assert.equal(r.s.lastGrowth[id].gained,xp);}assert.deepEqual(copy(r.s.domainDaily),daily,'EXP does not consume material-domain daily doubles');const state=r.serialize();r.finishBattle(true);assert.equal(r.serialize(),state,'the same receipt cannot award XP twice');return{xp,result:copy(result),activePartyXp:Object.fromEntries(ids.map(id=>[id,r.growth(id).xp])),booksAdded:0,materialDoubleCounterUnchanged:true,controlledSettlement:'enemy HP set to zero solely to verify the native reward ledger; not a player win or difficulty measurement'};};
 for(const boundary of ['PENDING','STARTED'])check('new_EXP60_preview_save_and_actual_xp_settlement:'+boundary,()=>{const {r,entry,preview}=expStart(env);assert.equal(entry.expRewardVersion,1);assert.equal(preview.xp,CURRENT_EXP60_XP);assert.deepEqual(copy(preview.items),{});assert.equal(preview.doubles,false);assert.equal(r.s.runtime.enemyBalanceRevision,1);assert.equal(r.s.runtime.growthDomain.expRewardVersion,1);if(boundary==='STARTED')r.action('COMBAT_BEGIN');const saved=JSON.parse(r.serialize()),loaded=new env.R(env.db,copy(saved));assert.deepEqual(copy(loaded.s.runtime),copy(saved.runtime));assert.equal(loaded.s.global.PRNG_STATE,saved.global.PRNG_STATE);const settlement=settleExp(loaded,CURRENT_EXP60_XP);return{boundary,entry:copy(entry),preview:copy(preview),settlement};});
 check('genuine_v01626_EXP60_retains_10000_preview_projection_and_settlement',()=>{const {r:old,entry,preview}=expStart(beforeEnv);assert.equal(entry.expRewardVersion,undefined);assert.equal(preview.xp,10000);assert.equal(old.s.runtime.growthDomain.expRewardVersion,undefined);assert.equal(old.s.runtime.enemyBalanceRevision,undefined);const saved=JSON.parse(old.serialize()),loaded=new env.R(env.db,copy(saved));assert.deepEqual(copy(loaded.s.runtime),copy(saved.runtime));assert.deepEqual(copy(loaded.growthDomainRewards(loaded.s.runtime.growthDomain,'NEUTRAL')),copy(old.growthDomainRewards(old.s.runtime.growthDomain,'NEUTRAL')));assert.equal(loaded.mondRewardPlan(loaded.s.runtime).xp,10000);const before=settleExp(old,10000),after=settleExp(loaded,10000);assert.deepEqual(after,before);assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(old.serialize()));return{entry:copy(entry),preview:copy(preview),before,after,oldEngineFingerprint:beforeEnv.fingerprint};});
 check('admin_catalog_EXP60_default_matches_native_entry_preview_and_old_baseline',()=>{
  const rows=[];for(const[e,label,xp]of[[beforeEnv,'0.16.26',10000],[env,'current',CURRENT_EXP60_XP]]){const r=prepared(e,expSpec),catalog=e.api.adminBalance.catalog(r),definition=catalog.growth.find(g=>g.id==='DOMAIN:LOST_VALLEY:60');assert(definition);const value=definition.fields.find(f=>f.key==='xp');assert(value);assert.equal(value.base,xp);const entry=r.growthDomainEntries().find(d=>d.id==='LOST_VALLEY:60');assert.equal(r.growthDomainRewards(entry,'NEUTRAL').xp,xp);rows.push({engine:label,catalogBaseXp:value.base,previewXp:xp,entryRewardRevision:entry.expRewardVersion??null});}return{rows};
 });
 check('operator_EXP60_xp_override_economy_multiplier_and_saved_profile_keep_precedence',()=>{
  const config=env.api.adminBalance.emptyConfig();config.growth.domains['LOST_VALLEY:60']={xp:8001};config.economy.rewardXpMultiplier=1.25;const evidence=[];
  for(const[e,label,revision]of[[beforeEnv,'genuine0.16.26',926260],[env,'current',926270]]){const r=e.api.adminBalance.createRuntime(e.db,copy(prepared(e,expSpec).s),{revision,config}),entry=r.growthDomainEntries().find(d=>d.id==='LOST_VALLEY:60');assert(entry&&!entry.reason);assert.equal(r.growthDomainRewards(entry,'NEUTRAL').xp,10001,'round(8001 operator XP × 1.25 economy multiplier)');r.action('DOMAIN_START',{domain:entry.id});assert.equal(r.s.runtime.adminBalanceRevision,revision);assert.equal(r.mondRewardPlan(r.s.runtime).xp,10001);const saved=JSON.parse(r.serialize()),loaded=env.api.adminBalance.createRuntime(env.db,copy(saved),{revision,config});assert.deepEqual(copy(loaded.s.runtime),copy(saved.runtime));assert.deepEqual(copy(env.api.adminBalance.profileOf(loaded).config),copy(config));assert.throws(()=>new env.R(env.db,copy(saved)),e=>e.code==='BALANCE_CONFIG','saved operator revision requires its real stored profile');assert.throws(()=>env.api.adminBalance.createRuntime(env.db,copy(saved),{revision:revision+1,config}),e=>e.code==='BALANCE_CONFIG','a different stored revision cannot load this battle');const before=settleExp(r,10001),after=settleExp(loaded,10001);assert.deepEqual(after,before);assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(r.serialize()));evidence.push({engine:label,revision,operatorXp:8001,economyMultiplier:1.25,actualPreviewAndSettlementXp:10001,enemyRevision:saved.runtime.enemyBalanceRevision??null,expRevision:saved.runtime.growthDomain.expRewardVersion??null,exactNativeSettlementAndStoredProfile:true});}
  return{evidence,ledgerProbe:'controlled settlement only; no combat victory or difficulty claim'};
 });
 check('EXP_reward_revision_rejects_invalid_value_or_scope',()=>{const {r}=expStart(env),save=JSON.parse(r.serialize());for(const value of [0,2,-1,'1',null]){const bad=copy(save);bad.runtime.growthDomain.expRewardVersion=value;assert.throws(()=>new env.R(env.db,bad),e=>e.code==='GROWTH_SAVE');}const unmarked=copy(save);delete unmarked.runtime.enemyBalanceRevision;assert.throws(()=>new env.R(env.db,unmarked),e=>e.code==='GROWTH_SAVE');const material=prepared(env,{source:'TALENT60_CONTRACT',kind:'DOMAIN',level:56,map:'MAP_D163_TAISHAN_MANSION'});material.action('DOMAIN_START',{domain:'TAISHAN_MANSION:60'});const invalid=JSON.parse(material.serialize());invalid.runtime.growthDomain.expRewardVersion=1;assert.throws(()=>new env.R(env.db,invalid),e=>e.code==='GROWTH_SAVE');return{invalidValues:[0,2,-1,'1',null],missingEnemyRevisionRejected:true,materialKindRejected:true};});
 const talentSpec={source:'TALENT60_CONTRACT',kind:'DOMAIN',level:56,map:'MAP_D163_TAISHAN_MANSION'},BOOK='GROWTH_TALENT_LIYUE';
 const talentStart=e=>{const r=prepared(e,talentSpec),entry=r.growthDomainEntries().find(d=>d.id==='TAISHAN_MANSION:60');assert(entry&&!entry.reason);const preview=r.growthDomainRewards(entry,'NEUTRAL');r.action('DOMAIN_START',{domain:entry.id});return{r,entry,preview};};
 const settleTalent=(r,quantity)=>{const items=r.itemCount(BOOK),daily=copy(r.s.domainDaily),plan=copy(r.mondRewardPlan(r.s.runtime));for(const a of r.s.runtime.actors.filter(a=>a.side==='ENEMY'))a.hp=0;const result=r.finishBattle(true);assert.equal(result.domain.items[BOOK],quantity);assert.equal(r.itemCount(BOOK)-items,quantity);assert.equal(r.s.domainDaily.wins,daily.wins+1);const state=r.serialize();r.finishBattle(true);assert.equal(r.serialize(),state,'material receipt is idempotent');return{quantity,plan,result:copy(result),itemsAdded:quantity,dailyBefore:daily,dailyAfter:copy(r.s.domainDaily),controlledSettlement:'enemy HP set to zero only to verify the native material ledger; no victory or difficulty claim'};};
 check('talent_native_preview_twelve_stages_only_Liyue60_changes_and_requirements_stay_exact',()=>{
  const rows=[];for(const[region,key]of[['MOND','FORSAKEN_RIFT'],['LIYUE','TAISHAN_MANSION']]){const site=env.api.growthV01522.domains[key],make=e=>prepared(e,{source:key+'_TALENT_CONTRACT',kind:'DOMAIN',level:56,map:site.map}),old=make(beforeEnv),current=make(env),oe=old.growthDomainEntries(),ce=current.growthDomainEntries();for(const[levelString,previous]of Object.entries(PRIOR_TALENT_BOOKS[region])){const level=Number(levelString),id=key+':'+level,a=oe.find(d=>d.id===id),b=ce.find(d=>d.id===id);assert(a&&b);assert.equal(a.talentRewardVersion,3);assert.equal(b.talentRewardVersion,4);const before=copy(old.growthDomainRewards(a,'NEUTRAL')),after=copy(current.growthDomainRewards(b,'NEUTRAL')),quantity=region==='LIYUE'&&level===60?90:previous;assert.equal(before.items['GROWTH_TALENT_'+region],previous);assert.equal(after.items['GROWTH_TALENT_'+region],quantity);const expected=copy(before);expected.items['GROWTH_TALENT_'+region]=quantity;assert.deepEqual(after,expected);rows.push({id,previous,quantity,beforeRevision:3,afterRevision:4});}}assert.equal(rows.length,12);assert.deepEqual(copy(env.api.growthV01522.previousDomainTalentBooks),PRIOR_TALENT_BOOKS);assert.deepEqual(copy(env.api.growthV01522.legacyDomainTalentBooks[3]),PRIOR_TALENT_BOOKS);assert.deepEqual(copy(env.api.growthV01522.talentBookCosts),copy(beforeEnv.api.growthV01522.talentBookCosts),'all actual talent upgrade material requirements remain unchanged');return{rows,requirementsUnchanged:true};
 });
 check('new_talent60_revision4_pinned_preview_saved_rules_and_actual90_receipt',()=>{
  const rows=[];for(const boundary of ['PENDING','STARTED']){const{r,entry,preview}=talentStart(env);assert.equal(entry.talentRewardVersion,4);assert.equal(preview.items[BOOK],90);assert.equal(preview.bonus,false);assert.equal(r.s.runtime.enemyBalanceRevision,1);assert.equal(r.s.runtime.growthDomain.talentRewardVersion,4);if(boundary==='STARTED')r.action('COMBAT_BEGIN');const save=JSON.parse(r.serialize()),loaded=new env.R(env.db,copy(save));assert.deepEqual(copy(loaded.s.runtime),copy(save.runtime));assert.equal(loaded.s.global.PRNG_STATE,save.global.PRNG_STATE);rows.push({boundary,preview:copy(preview),settlement:settleTalent(loaded,90)});}return{rows};
 });
 check('genuine_v01626_talent60_revision3_native_preview_save_and80_receipt_stay_exact',()=>{
  const rows=[];for(const boundary of ['PENDING','STARTED']){const{r:old,entry,preview}=talentStart(beforeEnv);assert.equal(entry.talentRewardVersion,3);assert.equal(preview.items[BOOK],80);if(boundary==='STARTED')old.action('COMBAT_BEGIN');const save=JSON.parse(old.serialize()),loaded=new env.R(env.db,copy(save));assert.equal(save.runtime.enemyBalanceRevision,undefined);assert.equal(save.runtime.growthDomain.talentRewardVersion,3);assert.deepEqual(copy(loaded.s.runtime),copy(save.runtime));assert.deepEqual(copy(loaded.growthDomainRewards(loaded.s.runtime.growthDomain,'NEUTRAL')),copy(old.growthDomainRewards(old.s.runtime.growthDomain,'NEUTRAL')));const before=settleTalent(old,80),after=settleTalent(loaded,80);assert.deepEqual(after,before);assert.deepEqual(JSON.parse(loaded.serialize()),JSON.parse(old.serialize()));rows.push({boundary,preview:copy(preview),before,after});}return{rows,oldEngineFingerprint:beforeEnv.fingerprint};
 });
 check('talent_reward_revision4_rejects_invalid_values_unmarked_policy_and_other_kind',()=>{
  const{r}=talentStart(env),save=JSON.parse(r.serialize());for(const value of [5,-1,'4',null]){const bad=copy(save);bad.runtime.growthDomain.talentRewardVersion=value;assert.throws(()=>new env.R(env.db,bad),e=>e.code==='GROWTH_SAVE');}const unmarked=copy(save);delete unmarked.runtime.enemyBalanceRevision;assert.throws(()=>new env.R(env.db,unmarked),e=>e.code==='GROWTH_SAVE');const exp=JSON.parse(expStart(env).r.serialize());exp.runtime.growthDomain.talentRewardVersion=4;assert.throws(()=>new env.R(env.db,exp),e=>e.code==='GROWTH_SAVE');return{invalidValues:[5,-1,'4',null],unmarkedBattleAndExperienceKindRejected:true,legacyVersions:'0/1/2/3 remain valid historical policies'};
 });
 check('admin_talent60_catalog90_prior80_and_operator_material_override_keep_native_precedence',()=>{
  const rows=[];for(const[e,label,quantity]of[[beforeEnv,'0.16.26',80],[env,'current',90]]){const r=prepared(e,talentSpec),definition=e.api.adminBalance.catalog(r).growth.find(g=>g.id==='DOMAIN:TAISHAN_MANSION:60');assert.equal(definition.fields.find(f=>f.key==='materialQuantity').base,quantity);rows.push({engine:label,baseMaterialQuantity:quantity});}const config=env.api.adminBalance.emptyConfig();config.growth.domains['TAISHAN_MANSION:60']={materialQuantity:37,xp:8001};const revision=946270,r=env.api.adminBalance.createRuntime(env.db,copy(prepared(env,talentSpec).s),{revision,config}),entry=r.growthDomainEntries().find(d=>d.id==='TAISHAN_MANSION:60');assert.equal(r.growthDomainRewards(entry,'NEUTRAL').items[BOOK],37);assert.equal(r.growthDomainRewards(entry,'NEUTRAL').xp,8001);r.action('DOMAIN_START',{domain:entry.id});const save=JSON.parse(r.serialize()),loaded=env.api.adminBalance.createRuntime(env.db,copy(save),{revision,config});assert.deepEqual(copy(loaded.s.runtime),copy(save.runtime));assert.equal(loaded.mondRewardPlan(loaded.s.runtime).xp,8001);const receipt=settleTalent(loaded,37);assert.equal(receipt.result.xp,8001);return{rows,operatorMaterialQuantity:37,operatorXp:8001,exactStoredProfileAndNativeReceipt:true,receipt};
 });
 check('fresh_save_and_unsupported_revision_policy',()=>{const r=start(env,specs[0]),saved=JSON.parse(r.serialize()),loaded=new env.R(env.db,copy(saved));assert.deepEqual(copy(loaded.s.runtime),copy(saved.runtime));assert.equal(loaded.s.global.PRNG_STATE,saved.global.PRNG_STATE);if(expectedRevision!==undefined){assert.equal(saved.runtime.enemyBalanceRevision,expectedRevision);for(const value of [0,expectedRevision+1,-1,'1',null]){const bad=copy(saved);bad.runtime.enemyBalanceRevision=value;assert.throws(()=>new env.R(env.db,bad),e=>e.code==='ENEMY_BALANCE_SAVE');}}return{marker:saved.runtime.enemyBalanceRevision??null,savedProjectionAndOrderPreserved:true,unsupportedRevisionChecked:expectedRevision!==undefined};});
 check('fixed_eight_enemy_reserves_keep_tuned_projection_on_reentry_and_load',()=>{const spec=specs.find(s=>s.source==='FB_CRYO_HYPOSTASIS'),r=prepared(env,spec);r.s.global.CURRENT_MAP_ID='MAP_MOND_FOREST';r.startBattle('EG_MOND_HILI_PATROL','EXPLICIT');const b=r.s.runtime,base=b.actors.find(a=>a.side==='ENEMY');for(let n=0;n<10;n++)b.actors.push({...copy(base),id:'NUMERIC_RESERVE_'+n});r.limitBattleEnemies();assert.equal(b.actors.filter(a=>a.side==='ENEMY'&&!a.fbSummon&&a.hp>0).length,8);assert(b.enemyReserve.length>0);for(const a of [...b.actors,...b.enemyReserve].filter(a=>a.side==='ENEMY'))assert.deepEqual(stats(a),stats(base));const saved=JSON.parse(r.serialize()),loaded=new env.R(env.db,copy(saved));assert.deepEqual(copy(loaded.s.runtime),copy(saved.runtime));const reserve=copy(loaded.s.runtime.enemyReserve[0]);loaded.s.runtime.actors.find(a=>a.side==='ENEMY').hp=0;loaded.limitBattleEnemies();const arrived=loaded.s.runtime.actors.find(a=>a.id===reserve.id);assert(arrived);assert.deepEqual(copy(arrived),reserve);return{active:8,reserve:b.enemyReserve.length,arrivalStats:stats(arrived),probe:'capacity-only actor copies, not a native authored encounter or victory'};});
 check('geo_summons_use_final_owner_hp_attack_level_and_fixed_three_slots',()=>{const spec=specs.find(s=>s.source==='FB_GEO_HYPOSTASIS'),config=env.api.adminBalance.emptyConfig();config.enemies[spec.source]={hp:100000,atk:4000};const r=env.api.adminBalance.createRuntime(env.db,copy(prepared(env,spec).s),{revision:850,config});enter(r,spec);const b=r.s.runtime,owner=boss(r,spec);for(let n=0;n<5;n++)r.fbSummon(b,owner,'FB_SUMMON_PILLAR');const summoned=[...b.actors,...b.enemyReserve].filter(a=>a.fbSummon?.owner===owner.id);assert(summoned.length>=5);for(const a of summoned){assert.equal(a.level,45);assert.equal(a.maxHp,6364);assert.equal(a.atk,0);assert.equal(a.def,1360);assert(a.growthScaled);}assert.equal(b.actors.filter(a=>a.side==='ENEMY'&&a.fbSummon&&a.hp>0).length,3);const saved=JSON.parse(r.serialize()),loaded=env.api.adminBalance.createRuntime(env.db,copy(saved),{revision:850,config});assert.deepEqual(copy(loaded.s.runtime),copy(saved.runtime));return{owner:stats(owner),summons:summoned.map(a=>({id:a.id,stats:stats(a)})),activeLimit:3,storedAndReservedStatsPreserved:true};});
 check('actual_shared_db_objects_and_authored_file_remain_unchanged',()=>{assert.equal(sha(JSON.stringify(env.db)),hashes.current);assert.equal(sha(JSON.stringify(beforeEnv.db)),hashes.before);assert.equal(sha(fs.readFileSync(path.join(env.root||ROOT,'content/db.json'))),AUTHORED_DB_SHA256);return{unchanged:true,rawDbSHA256:AUTHORED_DB_SHA256};});
 return{version:'0.16.27',scope:'Native projection/construction, public EQUIP and constellation, exact operator precedence, genuine 0.16.26 saved-battle replay, initial effective speed, reserves and summons. No difficulty, clear-rate or population claim.',currentFingerprint:env.fingerprint,beforeFingerprint:beforeEnv.fingerprint,rawDbSHA256:AUTHORED_DB_SHA256,total:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length,checks};
}
module.exports={run,loadBefore,productionBootstrap,specifications,BEFORE_ANCHORS,FINAL_ANCHORS,AUTHORED_DB_SHA256};
if(require.main===module){const arg=k=>{const i=process.argv.indexOf(k);return i<0?undefined:process.argv[i+1];},baseline=arg('--baseline-root'),env=H.load(ROOT),beforeEnv=baseline?H.load(path.resolve(baseline)):loadBefore();env.rawDbSHA256=sha(fs.readFileSync(path.join(ROOT,'content/db.json')));const anchors=JSON.parse(fs.readFileSync(arg('--anchors')||path.join(ROOT,'docs/data/balance_v01627/final_anchors.json'),'utf8'));assert.equal(anchors.enemyBalanceRevision,1,'new enemy policy is pinned to revision1');const result=run({env,beforeEnv,finalAnchors:anchors.bosses,expectedRevision:anchors.enemyBalanceRevision});if(arg('--out')){const file=path.resolve(arg('--out'));fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(result,null,2)+'\n');}for(const c of result.checks)if(!c.passed)console.error('FAIL '+c.id+' '+c.error);console.log(JSON.stringify({total:result.total,passed:result.passed,failed:result.failed}));if(result.failed)process.exitCode=1;}
