import assert from 'node:assert/strict';
import {onlineFixture,R,DB} from './helpers_online.mjs';
const f=onlineFixture();await f.start();
function fresh(){const r=new R(DB);r.newGame({name:'서버 검증',route:'ROUTE_ISEKAI',seed:71247,saveId:'online-local141'});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:'MAP_MOND_CITY',STORY_MENU_POLICY:'',WORLD_TIME:'12:00',MORA:3000});delete r.s.storyJourney;delete r.s.storyBreak;r.prepareStory();return r;}
async function action(type,params={}){const x=await f.action(type,params);assert.equal(x.status,200,JSON.stringify(x));return x;}
async function once(type,params={}){const requestId=crypto.randomUUID(),revision=f.read().revision;let x=await f.action(type,params,{requestId,revision});assert.equal(x.status,200,JSON.stringify(x));const saved=f.read();x=await f.action(type,params,{requestId,revision});assert.equal(x.status,200);assert.equal(f.read().state,saved.state);assert.equal(f.read().revision,saved.revision);return new R(DB,JSON.parse(saved.state));}
let r=fresh();r.adminApply({op:'recruit',char:'MOND_AMBER'});r.action('PARTY',{char:'MOND_AMBER',slot:2});r.giveItem('MAT_CHAR_EXP_WANDERER',30);f.seed(r.s);const books=r.itemCount('MAT_CHAR_EXP_WANDERER');r=await once('USE_ITEM',{item:'MAT_CHAR_EXP_WANDERER',quantity:5,owner:'MOND_AMBER'});assert.equal(r.itemCount('MAT_CHAR_EXP_WANDERER'),books-5);
await action('TUTORIAL_ACK',{dismissed:false});
r=new R(DB,JSON.parse(f.read().state));r.action('PLACE_ENTER',{place:'EVT_SCHEDULE_NPC_MOND_KATHERYNE',mode:'TALK'});/* Native prerequisite bootstrap before the historical pin/retry scenario. */r.action('COMMISSION_ACCEPT',{quest:'Q_TASK_LEARN_01'});r.action('CLAIM_QUEST',{quest:'Q_TASK_LEARN_01'});r.action('COMMISSION_ACCEPT',{quest:'Q_MOND_EXP_PLAINS_CART'});r.action('PLACE_LEAVE');f.seed(r.s);r=await once('OBJECTIVE_PIN',{kind:'COMMISSION',objective:'Q_MOND_EXP_PLAINS_CART'});assert.equal(r.navigationGoal(),'MAP_MOND_PLAINS');await action('OBJECTIVE_CLEAR');r=new R(DB,JSON.parse(f.read().state));assert(!r.s.pinnedObjective);
r.action('PLACE_ENTER',{place:'EVT_SCHEDULE_NPC_MOND_KATHERYNE',mode:'TALK'});r.questState('Q_MOND_EXP_PLAINS_CART').node='READY_TO_CLAIM';const before=r.s.chars.MOND_AMBER.xp,level=r.s.chars.MOND_AMBER.level;f.seed(r.s);r=await once('CLAIM_QUEST',{quest:'Q_MOND_EXP_PLAINS_CART'});assert(r.s.chars.MOND_AMBER.xp>before||r.s.chars.MOND_AMBER.level>level);
r=fresh();r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';r.startBattle('EG_MOND_SLIME_SMALL','RANDOM');r.action('COMBAT_BEGIN');r.s.runtime.round=10;f.seed(r.s);r=await once('COMBAT_FLEE');assert(!r.s.runtime);assert.equal(JSON.parse(r.s.global.LAST_BATTLE_RESULT_JSON).result,'ESCAPED');
console.log('PASS isolated Worker + SQLite: bulk books, tutorial, pin/clear, party quest XP and escape; duplicate requests settle exactly once');

