'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),root=path.resolve(__dirname,'..'),db=JSON.parse(fs.readFileSync(path.join(root,'content/db.json')));let now=1900000000000,id=0;
const c=vm.createContext({console,Date:class extends Date{static now(){return now;}}});for(const [,f]of fs.readFileSync(path.join(root,'source/index.html'),'utf8').matchAll(/<script src="(runtime[^"]*\.js)"/g))vm.runInContext(fs.readFileSync(path.join(root,'source',f),'utf8'),c,{filename:f});const R=c.CRPGRuntime.Runtime;
const copy=x=>JSON.parse(JSON.stringify(x)),results=[];
function fresh(map='MAP_MOND_PLAINS',route='ROUTE_TRAVELER'){const r=new R(db);r.newGame({name:'생활 검증',route,seed:74219,saveId:'LIFE10-'+(++id)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,STORY_MENU_POLICY:'',WORLD_TIME:'12:00',ENCOUNTER_COOLDOWN:0,MORA:5000});r.prepareStory();return r;}
function rejected(r,type,p={}){const s=r.serialize();assert.throws(()=>r.action(type,p));assert.equal(r.serialize(),s);}
function test(name,f){try{f();results.push({name,ok:true});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function work(r,kind){r.action('LIFE_START',{kind});now+=10000;return r.action('LIFE_FINISH',{job:r.s.lifeJob.id}).result;}
function fish(r){r.giveItem('TRPG_FISHING_ROD',1);r.giveItem(c.CRPGRuntime.lifeCatalog.bait,4);r.action('LIFE_START',{kind:'FISH'});return copy(r.s.lifeJob);}
function optimal(job){const controls=[];let held=false,state;for(let t=2000;t<=job.duration;t+=100){state=c.CRPGFishing.simulate(job,controls,t);if(state.caught)return {controls,elapsed:t};const next=state.cursor<state.target;if(next!==held){controls.push({at:t,hold:next});held=next;}}return {controls,elapsed:job.duration};}
test('all maps expose at most one kind and new dedicated sites have return routes',()=>{const r=fresh();for(const m of r.rows('32_MAP_DB')){r.s.global.CURRENT_MAP_ID=m[0];assert(r.lifeEntries().length<=1,m[0]);}for(const s of c.CRPGRuntime.lifeCatalog.sites){assert(r.tables['32_MAP_DB'].has(s.id));assert(r.rows('47_MAP_EDGE_DB').some(e=>e[1]===s.parent&&e[2]===s.id));assert(r.rows('47_MAP_EDGE_DB').some(e=>e[1]===s.id&&e[2]===s.parent));}assert.equal(db['32_MAP_DB'].some(r=>r[0]==='MAP_CRPG_CIDER_BANK'),false);});
test('gathering no longer permits mining; quarry permits only mining',()=>{const r=fresh();rejected(r,'LIFE_START',{kind:'MINE'});r.s.global.CURRENT_MAP_ID='MAP_CRPG_MOND_QUARRY';assert.equal(r.lifeEntries()[0].kind,'MINE');rejected(r,'LIFE_START',{kind:'GATHER'});});
test('old in-flight mining save migrates safely with its spent quotas carried to quarry',()=>{const r=fresh(),s=JSON.parse(r.serialize());delete s.lifeRevision;s.lifeResources={'MAP_MOND_PLAINS:MINE':{day:1,used:4}};s.lifeJob={id:s.global.SAVE_ID+':L1',kind:'MINE',map:'MAP_MOND_PLAINS',day:1,startedAt:now,duration:10000};const restored=new R(db,s);assert(!restored.s.lifeJob);restored.s.global.CURRENT_MAP_ID='MAP_CRPG_MOND_QUARRY';assert.equal(restored.lifeEntries()[0].remaining,2);new R(db,JSON.parse(restored.serialize()));});
test('gathering supplies two bundles, eggs are obtainable and high encounter roll stays peaceful',()=>{const r=fresh();r.random=()=>.999;r.die=()=>100;const result=work(r,'GATHER');assert.equal(result.items.ING_BIRD_EGG,10);assert.equal(r.itemCount('ING_BIRD_EGG'),10);assert(!r.s.runtime);assert.equal(r.lifeEntries()[0].remaining,3);});
test('hunt and gather encounter chance is one exact 5% roll and opens before any attack',()=>{for(const [map,kind]of [['MAP_MOND_PLAINS','GATHER'],['MAP_CRPG_WHISPER_HUNT','HUNT']])for(const roll of [5,6]){const r=fresh(map);let first=true;r.die=()=>{if(first){first=false;return roll;}return 1;};const hp=r.s.global.PLAYER_HP_CURRENT;work(r,kind);assert.equal(!!r.s.runtime,roll===5,map+' '+roll);if(r.s.runtime){assert.equal(r.s.runtime.opening.state,'PENDING');assert.equal(r.s.global.PLAYER_HP_CURRENT,hp);}}});
test('mining and fishing never trigger additional life encounters',()=>{const r=fresh('MAP_CRPG_MOND_QUARRY');r.die=()=>{throw Error('unexpected encounter roll');};work(r,'MINE');assert(!r.s.runtime);});
test('regional mining retains Starsilver and standard Mond ore intervals',()=>{const r=fresh('MAP_DRAGONSPINE');r.random=()=>0;const out=work(r,'MINE');assert.equal(out.items.ORE_STARSILVER,1);r.s.global.CURRENT_MAP_ID='MAP_CRPG_MOND_QUARRY';const basic=work(r,'MINE');assert.equal(basic.items.ORE_IRON,1);});
test('rod and bait enforced, bait spent exactly once, cancelling keeps rod and grants no fish',()=>{const r=fresh('MAP_CRPG_CIDER_BANK');rejected(r,'LIFE_START',{kind:'FISH'});r.giveItem('TRPG_FISHING_ROD',1);rejected(r,'LIFE_START',{kind:'FISH'});r.giveItem(c.CRPGRuntime.lifeCatalog.bait,2);r.action('LIFE_START',{kind:'FISH'});assert.equal(r.itemCount(c.CRPGRuntime.lifeCatalog.bait),1);r.action('LIFE_CANCEL');assert.equal(r.itemCount('TRPG_FISHING_ROD'),1);assert.equal(r.itemCount('ING_FISH'),0);assert.equal(r.lifeEntries()[0].remaining,4);});
test('fishing timing, future inputs, dishonest success flags and repeated completions cannot grant fish',()=>{const r=fresh('MAP_CRPG_CIDER_BANK'),j=fish(r);rejected(r,'LIFE_FINISH',{job:j.id,elapsed:0,controls:[],success:true});rejected(r,'LIFE_FINISH',{job:j.id,elapsed:1000,controls:[{at:10000,hold:true}]});now+=20000;r.action('LIFE_FINISH',{job:j.id,elapsed:20000,controls:[],success:true});assert.equal(r.itemCount('ING_FISH'),0);assert.equal(r.lifeEntries()[0].remaining,3);rejected(r,'LIFE_FINISH',{job:j.id,elapsed:20000,controls:[]});});
test('actual tension controls catch fish, persist save and do not consume extra bait',()=>{let r=fresh('MAP_CRPG_CIDER_BANK'),j=fish(r),input=optimal(j);assert(c.CRPGFishing.simulate(j,input.controls,input.elapsed).caught);r=new R(db,JSON.parse(r.serialize()));now+=input.elapsed;const out=r.action('LIFE_FINISH',{job:j.id,...input}).result;assert(out.caught);assert(out.items.ING_FISH>=2&&out.items.ING_FISH<=4);assert.equal(r.itemCount(c.CRPGRuntime.lifeCatalog.bait),3);assert.equal(r.lifeEntries()[0].remaining,3);assert(!r.s.runtime);new R(db,JSON.parse(r.serialize()));});
test('level increases fully heal protagonist and companion, non-level XP does not',()=>{const r=fresh();r.s.global.PLAYER_HP_CURRENT=1;r.addXp('PLAYER_CUSTOM',1);assert.equal(r.s.global.PLAYER_HP_CURRENT,1);r.addXp('PLAYER_CUSTOM',299);assert.equal(r.s.global.PLAYER_LEVEL_STATE,2);assert.equal(r.s.global.PLAYER_HP_CURRENT,r.s.global.PLAYER_HP_MAX);r.unlockCharacter('MOND_AMBER');r.s.chars.MOND_AMBER.hp=1;r.addXp('MOND_AMBER',300);assert.equal(r.s.chars.MOND_AMBER.hp,r.character('MOND_AMBER').maxHp);});
test('XP book action levels and heals its active owner',()=>{const r=fresh();r.giveItem('MAT_CHAR_EXP_WANDERER',1);r.s.global.PLAYER_HP_CURRENT=1;r.s.global.PLAYER_XP_STATE=299;r.action('USE_ITEM',{item:'MAT_CHAR_EXP_WANDERER',quantity:1,owner:'PLAYER_CUSTOM'});assert(r.s.global.PLAYER_LEVEL_STATE>1);assert.equal(r.s.global.PLAYER_HP_CURRENT,r.s.global.PLAYER_HP_MAX);});
test('Sara offers authored gated legends without accepting general commissions or other routes',()=>{const r=fresh('MAP_MOND_CITY');r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;r.action('PLACE_ENTER',{place:c.CRPGRuntime.lifeCatalog.sara});assert(r.legendContactEntries().some(e=>e.id==='LEG_MOND_BENNETT'));r.action('LEGEND_REGISTER',{quest:'LEG_MOND_BENNETT'});assert(r.legendRegistered('LEG_MOND_BENNETT'));rejected(r,'LEGEND_REGISTER',{quest:'LEG_MOND_BENNETT'});rejected(r,'COMMISSION_ACCEPT',{quest:'Q_MOND_EXP_PLAINS_CART'});rejected(r,'LEGEND_REGISTER',{quest:'LEG_ISK_MOND_AMBER'});rejected(r,'LEGEND_REGISTER',{quest:'LEG_MOND_VENTI'});});
test('Angel Share is a new scoped facility and keeps old smith identity for saves',()=>{const r=fresh('MAP_MOND_CITY');r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;r.action('PLACE_ENTER',{place:c.CRPGRuntime.lifeCatalog.tavern});assert.equal(r.currentPlace().entry.name,'천사의 몫 · 찰스');assert(r.legendContactEntries().some(e=>e.id==='LEG_MOND_DILUC'));r.action('LEGEND_REGISTER',{quest:'LEG_MOND_DILUC'});rejected(r,'LEGEND_ENTER',{quest:'LEG_MOND_DILUC'});assert(r.placeCatalog().some(e=>e.merchant==='MRC_BLACKSMITH_COMMON'));new R(db,JSON.parse(r.serialize()));});
test('contact registration obeys story/combat locks',()=>{const r=fresh('MAP_MOND_CITY');r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;r.action('PLACE_ENTER',{place:c.CRPGRuntime.lifeCatalog.sara});r.s.global.STORY_WAITING=false;r.s.global.STORY_MENU_POLICY='SAVE_LOAD_ONLY';rejected(r,'LEGEND_REGISTER',{quest:'LEG_MOND_BENNETT'});});
fs.writeFileSync(path.join(root,'reports/life-v010-tests.json'),JSON.stringify({total:results.length,passed:results.filter(r=>r.ok).length,results},null,2));if(results.some(r=>!r.ok))process.exitCode=1;
