'use strict';
// Isolated synthetic saves. Product code and player storage are read-only.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),src=process.env.CRPG_SOURCE||path.join(base,'source');
const db=JSON.parse(fs.readFileSync(process.env.CRPG_DB||path.join(base,'content/db.json')));
const ctx=vm.createContext({console}),index=fs.readFileSync(path.join(src,'index.html'),'utf8');
const files=[...index.matchAll(/<script\s+src="([^"]+)"/g)].map(x=>x[1]).filter(x=>/^runtime[^/]*\.js$/.test(x));
const candidate=process.env.PARTY_CANDIDATE||(fs.existsSync(path.join(__dirname,'runtime_party.js'))?path.join(__dirname,'runtime_party.js'):path.join(src,'runtime_party.js'));
for(const file of files)vm.runInContext(fs.readFileSync(file==='runtime_party.js'?candidate:path.join(src,file),'utf8'),ctx,{filename:file});
ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db)});
const R=ctx.CRPGRuntime.Runtime,copy=x=>JSON.parse(JSON.stringify(x)),results=[];let seq=0;
function fresh(free=true,route='ROUTE_TRAVELER'){const r=new R(db);r.newGame({name:'활성 파티 검증',route,seed:7317,saveId:'PARTY-ACTIVE-'+(++seq)});if(free)Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'HUB',STORY_CURSOR_NODE_ID:'HUB',SCREEN_MODE:'LOCATION',CURRENT_MAP_ID:'MAP_MOND_CITY',STORY_WAITING:true,STORY_MENU_POLICY:'',PENDING_CHOICE_GROUP_ID:''});return r;}
function own(r,id,state='JOINED',extra={}){const e=JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON||'{}');e[id]={state,...extra};r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(e);}
function join(r,id,slot,state='JOINED',extra={}){own(r,id,state,extra);r.action('PARTY',{char:id,slot});}
function gear(r,id='MOND_AMBER',equip='EQ_ARMOR_TRAVEL_COAT'){const slot=r.giveEquipment(equip);r.action('EQUIP',{slot,owner:id});return slot;}
function inv(r,slot){return r.s.inventory.find(i=>i.slot===slot);}
function reject(r,type,params,code){const before=JSON.stringify(r.s);assert.throws(()=>r.action(type,params),e=>e.code===code,code);assert.equal(JSON.stringify(r.s),before,'failed action changed state');}
function test(name,run){try{run();results.push({name,ok:true});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function goto(r,node){Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:node,STORY_CURSOR_NODE_ID:node,PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',SCREEN_MODE:'STORY',STORY_WAITING:false});r.prepareStory();return r;}
function preparation(r){const row=db['51_EVENT_DB'].slice(1).find(row=>{try{const p=JSON.parse(row[13]);return p.handler==='isk_m04_combat'&&p.kind==='battle_result'&&p.config.guest_char_ids.length;}catch{return false;}}),p=JSON.parse(row[13]),cfg=p.config;Object.assign(r.s.global,{STORY_ROUTE_ID:'ROUTE_ISEKAI',CURRENT_STORY_NODE_ID:cfg.node_id,STORY_CURSOR_NODE_ID:cfg.node_id,CURRENT_MAP_ID:cfg.map_id,SCREEN_MODE:'COMBAT_PREP',STORY_WAITING:false});r.s.battlePreparation={group:p.group_id,node:cfg.node_id,origin:'STORY:'+cfg.node_id};return cfg;}

test('ownership and active targeting remain distinct; unowned and inactive targets cannot equip',()=>{const r=fresh();own(r,'MOND_AMBER');own(r,'MOND_KAEYA','TEMPORARY');own(r,'MOND_LISA','DEPARTED');assert.deepEqual(copy(r.ownedActors()).map(a=>a.id),['PLAYER_CUSTOM','MOND_AMBER']);assert.deepEqual(copy(r.activePartyActors()).map(a=>a.id),['PLAYER_CUSTOM']);const slot=r.giveEquipment('EQ_ARMOR_TRAVEL_COAT');for(const owner of ['MOND_AMBER','MOND_KAEYA','MOND_LISA'])reject(r,'EQUIP',{slot,owner},'OWNER');join(r,'MOND_AMBER',2);r.s.chars.MOND_AMBER.hp=17;r.action('EQUIP',{slot,owner:'MOND_AMBER'});assert.equal(r.s.chars.MOND_AMBER.hp,17);assert.equal(r.partyTargetReason('MOND_AMBER'),'');});

test('growth books reject inactive owners without consumption, XP, HP, clock or revision changes',()=>{const r=fresh();own(r,'MOND_AMBER');r.giveItem('MAT_CHAR_EXP_WANDERER',3);reject(r,'USE_ITEM',{item:'MAT_CHAR_EXP_WANDERER',owner:'MOND_AMBER'},'OWNER');assert.throws(()=>r.useItem('MAT_CHAR_EXP_WANDERER',1,'MOND_AMBER'),e=>e.code==='OWNER');join(r,'MOND_AMBER',2);r.action('USE_ITEM',{item:'MAT_CHAR_EXP_WANDERER',owner:'MOND_AMBER'});assert.equal(r.s.chars.MOND_AMBER.xp,50);assert.equal(r.itemCount('MAT_CHAR_EXP_WANDERER'),2);r.action('USE_ITEM',{item:'MAT_CHAR_EXP_WANDERER'});assert.equal(r.s.global.PLAYER_XP_STATE,50);});

test('inactive food and mixed batch reject atomically while active party meals work',()=>{const r=fresh();join(r,'MOND_AMBER',2);own(r,'MOND_KAEYA');r.s.chars.MOND_AMBER.hp=1;r.s.chars.MOND_KAEYA.hp=1;r.s.global.PLAYER_HP_CURRENT=1;r.giveItem('FOOD_TEA_BREAK_PANCAKE',4);reject(r,'USE_ITEM',{item:'FOOD_TEA_BREAK_PANCAKE',owner:'MOND_KAEYA'},'OWNER');reject(r,'MEAL_BATCH',{meals:[{item:'FOOD_TEA_BREAK_PANCAKE',owner:'PLAYER_CUSTOM'},{item:'FOOD_TEA_BREAK_PANCAKE',owner:'MOND_KAEYA'}]},'OWNER');r.action('MEAL_BATCH',{meals:[{item:'FOOD_TEA_BREAK_PANCAKE',owner:'PLAYER_CUSTOM'},{item:'FOOD_TEA_BREAK_PANCAKE',owner:'MOND_AMBER'}]});assert.equal(r.s.chars.MOND_AMBER.hp,91);assert.equal(r.itemCount('FOOD_TEA_BREAK_PANCAKE'),2);});

test('internal story/combat XP rewards are not restricted by consumable target policy',()=>{const r=fresh();own(r,'MOND_AMBER');r.addXp('MOND_AMBER',50);assert.equal(r.s.chars.MOND_AMBER.xp,50);assert.equal(r.s.party.some(p=>p.active&&p.source==='MOND_AMBER'),false);});

test('removal returns every equipment category and preserves instance identity/enhancement with no healing',()=>{const r=fresh();join(r,'MOND_AMBER',2);const max=r.character('MOND_AMBER').maxHp;const slots=[gear(r),gear(r,'MOND_AMBER','EQ_BOW_SLINGSHOT'),gear(r,'MOND_AMBER','EQ_SPECIAL_FIELD_PACK')];inv(r,slots[0]).enhance=3;const before=copy(r.s.inventory);r.s.chars.MOND_AMBER.hp=r.character('MOND_AMBER').maxHp;const result=r.action('PARTY_REMOVE',{slot:2});assert.deepEqual(copy(result.result.returnedEquipment).sort(),slots.sort());for(const slot of slots){assert.equal(inv(r,slot).owner,'공용');assert.equal(inv(r,slot).equipped,false);for(const k of ['slot','equip','quantity','enhance','instanceRevision'])assert.equal(inv(r,slot)[k],before.find(x=>x.slot===slot)[k]);}assert.equal(r.s.chars.MOND_AMBER.hp,max);assert.ok(r.ownedActors().some(a=>a.id==='MOND_AMBER'));join(r,'MOND_AMBER',2);assert.equal(r.s.inventory.some(i=>i.owner==='MOND_AMBER'),false);assert.equal(r.s.chars.MOND_AMBER.hp,max);});

test('successful replacement releases only the departing member; failed replacement rolls back gear and HP',()=>{const r=fresh();join(r,'MOND_AMBER',2);join(r,'MOND_KAEYA',3);own(r,'MOND_LISA');const amber=gear(r),kaeya=gear(r,'MOND_KAEYA');r.s.chars.MOND_AMBER.hp=19;reject(r,'PARTY_REPLACE',{slot:2,char:'MOND_NOELLE'},'COMPANION');reject(r,'PARTY_REPLACE',{slot:2,char:'MOND_KAEYA'},'DUPLICATE');r.action('PARTY_REPLACE',{slot:2,char:'MOND_LISA'});assert.equal(inv(r,amber).owner,'공용');assert.equal(inv(r,kaeya).owner,'MOND_KAEYA');assert.equal(r.s.chars.MOND_AMBER.hp,19);});

test('same-member replacement and active slot swaps retain all gear, tactics and wounded HP',()=>{const r=fresh();join(r,'MOND_AMBER',2);join(r,'MOND_KAEYA',3);const a=gear(r),k=gear(r,'MOND_KAEYA');r.action('PARTY_TACTIC',{slot:2,tactic:'지원우선'});r.s.chars.MOND_AMBER.hp=23;const inventory=JSON.stringify(r.s.inventory);r.action('PARTY_REPLACE',{slot:2,char:'MOND_AMBER'});r.action('PARTY_SWAP',{from:2,to:3});r.action('PARTY_SWAP',{from:3,to:4});assert.equal(JSON.stringify(r.s.inventory),inventory);assert.equal(r.s.party[3].source,'MOND_AMBER');assert.equal(r.s.party[3].tactic,'지원우선');assert.equal(r.s.chars.MOND_AMBER.hp,23);assert.equal(inv(r,a).owner,'MOND_AMBER');assert.equal(inv(r,k).owner,'MOND_KAEYA');});

test('direct removeParty applies the same departure rule',()=>{const r=fresh();join(r,'MOND_AMBER',2);const slot=gear(r);r.removeParty(2);assert.equal(inv(r,slot).owner,'공용');});

test('authored story separation retains ownership and returns deselected equipment',()=>{const r=fresh(true,'ROUTE_ISEKAI');join(r,'MOND_AMBER',2);const slot=gear(r);r.s.chars.MOND_AMBER.hp=17;Object.assign(r.s.flags,{FLAG_ISK_META_KNOWLEDGE:'UNKNOWN',FLAG_ISK_MOND_BRANCH:'EXPEDITION'});r.s.quests.Q_ISK_MOND_02={state:'진행중',node:'ACTIVE',claimed:false};goto(r,'ISK_M03_A_086');r.action('STORY_NEXT',{node:'ISK_M03_A_086'});assert.ok(r.storyEventReceipt('EVT_ISK_M03_A_AMBER_SPLIT'));assert.equal(JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON).MOND_AMBER.state,'JOINED');assert.equal(inv(r,slot).owner,'공용');assert.equal(r.s.chars.MOND_AMBER.hp,17);});

test('temporary eligibility cannot grant a party slot',()=>{const r=fresh();own(r,'MOND_AMBER','TEMPORARY',{expires:'NEXT_COMBAT_END'});reject(r,'PARTY',{char:'MOND_AMBER',slot:2},'COMPANION');assert.equal(r.ownedActors().some(x=>x.id==='MOND_AMBER'),false);});

test('general battle selection returns deselected gear before saving retry checkpoint',()=>{const r=fresh();join(r,'MOND_AMBER',2);join(r,'MOND_KAEYA',3);const a=gear(r),k=gear(r,'MOND_KAEYA');goto(r,'TRV_M02_N123');r.action('STORY_NEXT',{node:'TRV_M02_N123'});assert.equal(r.playPhase(),'PREPARATION');r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:['MOND_KAEYA']});assert.ok(r.s.runtime);assert.equal(inv(r,a).owner,'공용');assert.equal(inv(r,k).owner,'MOND_KAEYA');assert.equal(r.s.storyBattleCheckpoint.inventory.find(i=>i.slot===a).owner,'공용');assert.equal(r.s.runtime.actors.some(a=>a.source==='MOND_AMBER'),false);});

test('legacy inactive-owner gear migrates to shared inventory; original save, XP and RNG remain intact',()=>{const r=fresh();join(r,'MOND_AMBER',2);const base=r.character('MOND_AMBER').maxHp,slot=gear(r);inv(r,slot).enhance=6;const raw=copy(r.s);raw.party[1]={slot:'PARTY_2',active:false};raw.chars.MOND_AMBER.hp=r.character('MOND_AMBER').maxHp;raw.chars.MOND_AMBER.xp=17;const original=JSON.stringify(raw),loaded=new R(db,raw);assert.equal(JSON.stringify(raw),original);assert.equal(inv(loaded,slot).owner,'공용');assert.equal(inv(loaded,slot).equipped,false);assert.equal(inv(loaded,slot).enhance,6);assert.equal(loaded.s.chars.MOND_AMBER.hp,base);assert.equal(loaded.s.chars.MOND_AMBER.xp,17);for(const key of ['PRNG_STATE','SAVE_REVISION','WORLD_DAY','WORLD_TIME'])assert.equal(loaded.s.global[key],raw.global[key]);const again=new R(db,copy(loaded.s));assert.equal(JSON.stringify(again.s),JSON.stringify(loaded.s));});

test('equipped player transfer and pure preview update both owners without healing',()=>{const r=fresh();join(r,'MOND_AMBER',2);const base=r.player().maxHp,slot=gear(r,'PLAYER_CUSTOM');r.s.global.PLAYER_HP_CURRENT=r.player().maxHp;r.s.chars.MOND_AMBER.hp=17;const before=JSON.stringify(r.s),preview=r.equipmentPreview(slot,'MOND_AMBER');assert.equal(preview.reason,'');assert.equal(JSON.stringify(r.s),before);assert.equal(preview.displacedOwner,'PLAYER_CUSTOM');r.action('EQUIP',{slot,owner:'MOND_AMBER'});assert.equal(r.player().hp,base);assert.equal(r.player().maxHp,base);assert.equal(r.s.chars.MOND_AMBER.hp,17);assert.equal(preview.after.maxHp,r.character('MOND_AMBER').maxHp);own(r,'MOND_KAEYA');const state=JSON.stringify(r.s),invalid=r.equipmentPreview(slot,'MOND_KAEYA');assert.equal(invalid.code,'OWNER');assert.equal(JSON.stringify(r.s),state);});

test('level and weapon category restrictions remain enforced for active companions',()=>{const r=fresh();join(r,'MOND_AMBER',2);const high=r.giveEquipment('EQ_ARMOR_IRON_GUARD'),sword=r.giveEquipment('EQ_SWORD_HARBINGER'),story=r.giveEquipment('EQ_STORY_PYRO_GNOSIS');reject(r,'EQUIP',{slot:high,owner:'MOND_AMBER'},'LEVEL');reject(r,'EQUIP',{slot:sword,owner:'MOND_AMBER'},'PROFICIENCY');reject(r,'EQUIP',{slot:story},'EQUIP_CATEGORY');});

test('story locks remain and preparation permits only actual active targets',()=>{const r=fresh(false);const slot=r.giveEquipment('EQ_ARMOR_TRAVEL_COAT');r.giveItem('MAT_CHAR_EXP_WANDERER',1);for(const [type,p]of [['EQUIP',{slot}],['USE_ITEM',{item:'MAT_CHAR_EXP_WANDERER'}],['PARTY_SWAP',{from:2,to:3}]])reject(r,type,p,'ACTION_LOCK');const p=fresh(true,'ROUTE_ISEKAI'),cfg=preparation(p);own(p,'MOND_AMBER');const eq=p.giveEquipment('EQ_ARMOR_TRAVEL_COAT');reject(p,'EQUIP',{slot:eq,owner:'MOND_AMBER'},'OWNER');p.action('PARTY',{char:'MOND_AMBER',slot:2});p.action('EQUIP',{slot:eq,owner:'MOND_AMBER'});p.action('UNEQUIP',{slot:eq,owner:'MOND_AMBER'});assert.equal(p.playPhase(),'PREPARATION');});

test('authored guest selection requires permanent ownership',()=>{const r=fresh(true,'ROUTE_ISEKAI'),cfg=preparation(r),guest=cfg.guest_char_ids[0];reject(r,'PREP_SELECT',{group:cfg.group_id,companions:[guest]},'OWNER');own(r,guest);r.action('PREP_SELECT',{group:cfg.group_id,companions:[guest]});const loaded=new R(db,JSON.parse(r.serialize()));assert.deepEqual(copy(loaded.s.battlePreparation.selectedCompanions),[guest]);loaded.action('COMBAT_PREPARE',{group:cfg.group_id});assert.ok(loaded.s.runtime.actors.some(a=>a.source===guest&&!a.guest));});

test('active category replacement and unequip preserve wounded HP and instance enhancement',()=>{const r=fresh();join(r,'MOND_AMBER',2);const first=gear(r),second=r.giveEquipment('EQ_ARMOR_TRAVEL_COAT');inv(r,second).enhance=3;r.s.chars.MOND_AMBER.hp=13;r.action('EQUIP',{slot:second,owner:'MOND_AMBER'});assert.equal(inv(r,first).owner,'공용');assert.equal(r.s.inventory.filter(i=>i.equipped&&i.owner==='MOND_AMBER'&&i.category==='ARMOR').length,1);r.action('UNEQUIP',{slot:second,owner:'MOND_AMBER'});assert.equal(inv(r,second).enhance,3);assert.equal(inv(r,second).owner,'공용');assert.equal(r.s.chars.MOND_AMBER.hp,13);reject(r,'UNEQUIP',{slot:second},'EQUIP_EMPTY');});

test('active equipment secondary modifiers still reach displayed actor stats',()=>{const r=fresh();join(r,'MOND_KAEYA',2);const before=r.character('MOND_KAEYA');gear(r,'MOND_KAEYA','EQ_SWORD_HARBINGER');gear(r,'MOND_KAEYA');const after=r.character('MOND_KAEYA');assert.equal(after.crit-before.crit,3);assert.equal(after.critDmg-before.critDmg,6);assert.equal(after.eva-before.eva,1);});

test('legacy running battle loads without rerolling or rewriting its actor snapshot',()=>{const r=fresh();join(r,'MOND_AMBER',2);const slot=gear(r);Object.assign(r.s.global,{CURRENT_MAP_ID:'MAP_DRAGONSPINE',PLAYER_BASE_HP:100000});r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.player().maxHp;r.startBattle('EG_DRAGON_MITA','TEST');const raw=copy(r.s);raw.party[1]={slot:'PARTY_2',active:false};const battle=JSON.stringify(raw.runtime),loaded=new R(db,raw);assert.equal(JSON.stringify(loaded.s.runtime),battle);assert.equal(loaded.s.global.PRNG_STATE,raw.global.PRNG_STATE);assert.equal(inv(loaded,slot).owner,'공용');loaded.finishBattle(false);assert.ok(loaded.s.chars.MOND_AMBER.hp<=loaded.character('MOND_AMBER').maxHp);});

fs.writeFileSync(path.join(__dirname,'../reports/party-tests.json'),JSON.stringify({candidate:process.env.PARTY_CANDIDATE||'runtime_party.js',loaded:files,total:results.length,passed:results.filter(r=>r.ok).length,results},null,2));
if(results.some(r=>!r.ok))process.exitCode=1;
