'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const config=fs.readFileSync(path.join(root,'source/online_config.js'),'utf8');
const online=fs.readFileSync(path.join(root,'source/app_online.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'source/sw.js'),'utf8');
const html=fs.readFileSync(path.join(root,'source/index.html'),'utf8');
const api='https://genshin-crpg-online.jungsan765.workers.dev';
assert(config.includes(api),'production API URL missing from online_config.js');
assert(online.includes("productionApi='"+api+"'"),'production fallback API missing from app_online.js');
assert(online.includes("configuredApi||(!isLocal?productionApi:'')"),'production fallback is not wired into base resolution');
assert(sw.includes("new URL('online_config.js',scopeURL).pathname"),'service worker does not special-case online_config.js');
assert(sw.includes("fetch(event.request,{cache:'no-store'})"),'online config is not fetched outside stale cache');
assert(html.indexOf('online_config.js')<html.indexOf('app_online.js'),'online config must load before online account UI');
assert(!online.includes('await localBegin(name,route)'),'logged-out begin must not fall back to a local journey');
assert(online.includes("if(!O.account||!O.token){game=null;O.active=false;persist();auth(false,true);return;}"),'begin/load guards must require an authenticated account');
assert(online.includes("busy||!loggedIn"),'title Game Start must stay disabled while logged out');
assert(online.includes("if(!O.token||!O.account){game=null;O.active=false;activeSaveSlot=null;}"),'logged-out boot must discard any in-memory local journey');
console.log('PASS production signup stays connected and gameplay requires login before start');
