'use strict';
// Native actions cover successful work, start snapshots, atomic reports and receipt replays.
// Explicit pre-earned quota/save fixtures isolate period migration and all-complete bookkeeping.
const assert=require('node:assert/strict');
const {fresh,R,db,c,advance}=require('./helpers_v011.cjs');
const copy=x=>JSON.parse(JSON.stringify(x)),DAY=86400000,T=c.CRPGRuntime.tasksV0169,C=c.CRPGTaskCatalogV0168;
let passed=0;
function check(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){process.exitCode=1;console.error('FAIL '+name+'\n'+e.stack);}}
function leave(r){if(r.s.placeVisit)r.action('PLACE_LEAVE');}
function guild(r){leave(r);r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';r.s.global.WORLD_TIME='12:00';r.action('PLACE_ENTER',{place:'EVT_SCHEDULE_NPC_MOND_KATHERYNE',mode:'TALK'});}
function level(r,n=60){r.adminApply({op:'level',target:'ALL',value:n});}
function own(r,ids){const o={};for(const id of ids)o[id]={state:'JOINED'};r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(o);r.s.party=[{slot:'PARTY_1',source:'PLAYER_CUSTOM',type:'PLAYER',control:'PLAYER',active:true,tactic:'균형'},...ids.slice(0,3).map((id,i)=>({slot:'PARTY_'+(i+2),source:id,type:'CHAR',control:'AI',active:true,tactic:'균형'}))];r.s.formation=r.s.party.map(x=>x.source);for(const id of ids)r.s.chars[id].hp=r.character(id).maxHp;}
function win(r){leave(r);r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';r.action('MENU',{screen:'LOCATION'});r.startBattle('EG_MOND_HILI_PATROL','RANDOM');const battle=r.s.runtime.id;for(const a of r.s.runtime.actors)if(a.side==='ENEMY')a.hp=0;const action={id:r.s.global.SAVE_ID+':'+(r.s.global.LAST_COMMITTED_ACTION_SEQ+1),revision:r.s.global.SAVE_REVISION,type:'COMBAT_BEGIN',battle};const out=r.transact(action);assert(r.s.combatReceipts[battle].victory);return {action,out};}
function gather(r){leave(r);r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';r.action('LIFE_START',{kind:'GATHER'});const j=r.s.lifeJob,scene=r.lifeScene(j);advance(j.duration+100);return r.action('LIFE_FINISH',{job:j.id,elapsed:j.duration,inputs:scene.nodes.map((n,i)=>({at:600+i*300,node:i}))}).result;}
function completeBoard(r,scope){r.tasksBox(true);for(const [id,d]of Object.entries(r.s.tasks[scope+'Definitions'])){(r.s.tasks[scope+'Progress']??={})[id]=d.goal;r.s.tasks[scope][d.kind]=Math.max(r.s.tasks[scope][d.kind]||0,d.goal);}}
function legacyBox(r){const day=c.CRPGRuntime.tasksV0167.dayOf(r.tasksNow()),week=c.CRPGRuntime.tasksV0167.weekOf(r.tasksNow());r.s.tasks={version:1,day,week,daily:{win:2,ley:1,domain:1,life:2},weekly:{win:10,boss:2,domain:3,bonus:4},claimed:{D_DOMAIN:1},dailyIds:['D_WIN','D_LEY','D_DOMAIN','D_LIFE'],weeklyIds:['W_WIN','W_V168_CRYO_VINE','W_DOMAIN','W_BONUS']};}

check('daily farming objectives are generic and preserve the original four-slot board',()=>{const r=fresh();assert.equal(r.taskView().daily.length,4);for(const t of T.daily.filter(t=>['ley','domain'].includes(t.kind))){assert.equal(t.minLevel||1,1);assert(!t.filter?.minStage&&!t.filter?.minTier&&!t.filter?.party&&!t.filter?.stages);}const g=T.daily.find(t=>t.id==='D_V168_APPLE');assert.equal(g.goal,3);assert.equal(g.countMode,'actions');assert(!g.filter?.resources&&!g.filter?.maps);});

check('new weekly assignment contains twenty eligible objectives and honours definition Primogems',()=>{const r=fresh();level(r);own(r,['MOND_AMBER','MOND_KAEYA','MOND_LISA','MOND_BARBARA']);const v=r.taskView();assert.equal(v.weekly.length,20);assert(v.weekly.every(t=>!t.lock));assert.equal(new Set(v.weekly.map(t=>t.id)).size,20);assert.equal(v.weeklyBonus.id,'W_ALL');assert.equal(v.weeklyBonus.reward.primogem,200);for(const t of v.weekly){assert.equal(t.reward.primogem||0,T.weekly.find(x=>x.id===t.id).reward.primogem||0);}new R(db,copy(r.s));});

check('every unlocked weekly core objective survives rotation across distinct accounts',()=>{const r=fresh();level(r);own(r,['MOND_AMBER','MOND_KAEYA','MOND_LISA']);for(let n=0;n<24;n++){r.s.global.SAVE_ID='V169_CORE_'+n;delete r.s.tasks;const ids=r.taskView().weekly.map(t=>t.id);for(const id of ['W_WIN','W_BOSS','W_DOMAIN','W_BONUS','W_V168_TALENT30','W_V168_ASCENSION','W_V168_EXPERIENCE','W_V168_WEALTH','W_V168_DOMAIN_CIRCUIT','W_V168_LIFE_SUPPLY'])assert(ids.includes(id),id+' cannot rotate out');assert.equal(ids.length,20);}});

check('same-period legacy assignments preserve goals, progress, payouts and boss-slot Primogems',()=>{let r=fresh();level(r);own(r,['MOND_AMBER','MOND_KAEYA','MOND_LISA']);legacyBox(r);const money=r.s.global.MORA,primo=r.s.global.PRIMOGEM;const v=r.taskView();assert.equal(v.daily[0].goal,3);assert.equal(v.daily[0].progress,2);assert.equal(v.daily[2].claimed,true);assert.equal(v.weekly[1].goal,3);assert.equal(v.weekly[1].reward.primogem,30);assert.equal(v.weekly[2].progress,3);assert.equal(v.weekly.length,20);assert(v.weekly.slice(4).every(t=>t.progress===0),'added objectives do not inherit old aggregate wins');assert.equal(r.s.global.MORA,money);assert.equal(r.s.global.PRIMOGEM,primo);r=new R(db,copy(r.s));assert(r.taskView().daily[2].claimed);assert.throws(()=>r.action('TASK_CLAIM',{task:'D_DOMAIN'}),/이미/);});

check('next day adopts new definitions and increasing level cannot rewrite the assigned reward',()=>{const r=fresh();legacyBox(r);r.taskView();advance(DAY);const v=r.taskView();assert(v.daily.every(t=>!t.claimed));assert.equal(v.daily.find(t=>t.id==='D_V168_PYRO_HYDRO').goal,5);const ids=copy(r.s.tasks.dailyIds),rewards=v.daily.map(t=>t.reward);level(r);assert.deepEqual(copy(r.taskView().daily.map(t=>t.reward)),copy(rewards));assert.deepEqual(copy(r.s.tasks.dailyIds),ids);new R(db,copy(r.s));});

check('owned elemental daily varies by day and excludes dead, loan and remote characters',()=>{const r=fresh();level(r);own(r,['MOND_AMBER','MOND_KAEYA','MOND_LISA']);r.s.chars.MOND_LISA.hp=0;const o=JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON);o.MOND_BARBARA={state:'JOINED',tutorialLoan:true};r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(o);r.s.chars.MOND_BARBARA.hp=r.character('MOND_BARBARA').maxHp;const options=copy(T.elementalChoices(r));assert(options.length>=2);assert(options.every(es=>!es.includes('ELECTRO')&&!es.includes('HYDRO')));delete o.MOND_BARBARA;r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify(o);let previous;for(let n=0;n<10;n++){const x=r.taskView().daily.find(t=>t.id==='D_V168_PYRO_HYDRO'),d=r.s.tasks.dailyDefinitions[x.id];assert(!d.filter.party.full);assert(options.some(es=>JSON.stringify(es)===JSON.stringify(d.selectedElements)));const key=JSON.stringify(d.selectedElements);if(previous)assert.notEqual(key,previous);previous=key;new R(db,copy(r.s));advance(DAY);}});

check('daily elemental assignment avoids yesterday even when the owned roster changes',()=>{const r=fresh();level(r);let previous;for(let i=0;i<18;i++){own(r,i%2?['MOND_AMBER','MOND_KAEYA','MOND_BARBARA']:['MOND_AMBER','MOND_KAEYA']);const v=r.taskView(),id=v.daily.find(t=>t.id==='D_V168_PYRO_HYDRO').id,es=copy(r.s.tasks.dailyDefinitions[id].selectedElements),key=JSON.stringify(es);if(previous)assert.notEqual(key,previous);previous=key;advance(DAY);}});

check('native victory advances snapshot objectives exactly once after transaction reload',()=>{let r=fresh();level(r);own(r,['MOND_AMBER','MOND_KAEYA','MOND_LISA']);guild(r);r.action('COMMISSION_ACCEPT',{quest:'Q_TASK_MOND_PATROL_01'});assert.equal(r.s.quests.Q_TASK_MOND_PATROL_01.taskObjective.version,2);const {action,out}=win(r);assert.equal(r.s.quests.Q_TASK_MOND_PATROL_01.taskObjective.progress,1);const saved=r.serialize();assert.deepEqual(copy(r.transact(action)),copy(out));assert.equal(r.serialize(),saved);r=new R(db,JSON.parse(saved));guild(r);const before=r.s.global.MORA,paid=r.action('CLAIM_QUEST',{quest:'Q_TASK_MOND_PATROL_01'}).result;assert.equal(paid.rewards.mora,1000);assert.equal(r.s.global.MORA,before+1000,'absolute objective payout has no Lv.60 multiplier');assert(r.questVisible('Q_TASK_MOND_PATROL_02'));const claimed=r.serialize();assert.throws(()=>r.action('CLAIM_QUEST',{quest:'Q_TASK_MOND_PATROL_01'}),/이미/);assert.equal(r.serialize(),claimed);});

check('three successful native gathers count actions independently of resource type/quantity',()=>{const r=fresh();r.taskView();const id='D_V168_APPLE',d=T.daily.find(x=>x.id===id);r.s.tasks.dailyIds[3]=id;r.s.tasks.dailyIds=[...new Set(r.s.tasks.dailyIds)];if(r.s.tasks.dailyIds.length<4)r.s.tasks.dailyIds.push('D_LIFE');r.s.tasks.dailyDefinitions=Object.fromEntries(r.s.tasks.dailyIds.map(x=>[x,r.s.tasks.dailyDefinitions[x]||{...copy(d),reward:T.rewardAt(d,1),assignedLevel:1,revision:169,individual:true}]));r.s.tasks.dailyProgress[id]=0;for(let i=1;i<=3;i++){const out=gather(r);assert(Object.keys(out.items).length);assert.equal(r.taskView().daily.find(t=>t.id===id).progress,i);}assert(r.taskView().daily.find(t=>t.id===id).done);});

check('locked daily quotas never produce a free all-complete reward',()=>{const r=fresh();legacyBox(r);const box=r.tasksBox(true);box.daily.win=3;box.daily.life=2;box.daily.domain=1;box.daily.ley=0;const v=r.taskView();assert(v.daily.find(t=>t.id==='D_LEY').lock);assert.equal(v.bonus.goal,4);assert.equal(v.bonus.progress,3);assert(!v.bonus.done);guild(r);assert.throws(()=>r.action('TASK_CLAIM',{task:'D_BONUS'}),/아직/);});

check('daily all-complete and weekly all-complete pay separately once through real reports',()=>{let r=fresh();level(r);r.taskView();completeBoard(r,'daily');completeBoard(r,'weekly');guild(r);const before=Number(r.s.global.PRIMOGEM)||0;const d=r.action('TASK_CLAIM',{task:'D_BONUS'}).result,w=r.action('TASK_CLAIM',{task:'W_ALL'}).result;assert.equal(d.primogem,20);assert.equal(w.primogem,200);assert.equal(r.s.global.PRIMOGEM,before+220);assert.equal(r.s.tasks.weekly.bonus,6);r=new R(db,copy(r.s));guild(r);assert.throws(()=>r.action('TASK_CLAIM',{task:'W_ALL'}),/이미/);assert.throws(()=>r.action('TASK_CLAIM',{task:'D_BONUS'}),/이미/);new R(db,copy(r.s));});

check('five simultaneous legacy/new commissions include ready work and completed reports free slots',()=>{const r=fresh();level(r);own(r,['MOND_AMBER','MOND_KAEYA','MOND_LISA']);guild(r);const ids=['Q_TASK_MOND_PATROL_01','Q_TASK_SLIME_01','Q_TASK_HILICHURL_01','Q_TASK_BANDITS_01','Q_CRPG_MOND_FIRST_FIELD'];for(const id of ids)r.action('COMMISSION_ACCEPT',{quest:id});assert.equal(r.taskAcceptedCount(),5);const before=r.serialize();assert.throws(()=>r.action('COMMISSION_ACCEPT',{quest:'Q_TASK_MOND_GATHER_01'}),/5개/);assert.equal(r.serialize(),before);win(r);assert.equal(r.s.quests.Q_TASK_MOND_PATROL_01.node,'READY_TO_CLAIM');guild(r);assert.equal(r.taskAcceptedCount(),5);assert.throws(()=>r.action('COMMISSION_ACCEPT',{quest:'Q_TASK_MOND_GATHER_01'}),/5개/);r.action('CLAIM_QUEST',{quest:'Q_TASK_MOND_PATROL_01'});assert.equal(r.taskAcceptedCount(),4);r.action('COMMISSION_ACCEPT',{quest:'Q_TASK_MOND_GATHER_01'});assert.equal(r.taskAcceptedCount(),5);new R(db,copy(r.s));});

check('old accepted/paid chain records keep their original finite reward and multiplier',()=>{let r=fresh();level(r);const legacy=C.legacyChains.find(t=>t.id==='Q_TASK_MOND_PATROL_01');r.s.global.LAST_COMMITTED_ACTION_SEQ=1;r.s.quests[legacy.id]={guildAccepted:true,claimed:false,node:'READY_TO_CLAIM',state:'진행중',taskObjective:{version:1,progress:legacy.goal,acceptedSeq:1}};r=new R(db,copy(r.s));assert.equal(r.s.quests[legacy.id].taskObjective.definition.revision,168);guild(r);const before=r.s.global.MORA,out=r.action('CLAIM_QUEST',{quest:legacy.id}).result;assert.equal(out.rewards.mora,125*6);assert.equal(r.s.global.MORA,before+750);new R(db,copy(r.s));assert.equal(r.s.quests[legacy.id].taskObjective.primogemPaid,0);});

check('grandfathered six accepted old objectives survive load but cannot add another',()=>{let r=fresh();level(r);const defs=C.legacyChains.filter(t=>t.tier===1&&t.map==='MAP_MOND_CITY').slice(0,6);r.s.global.LAST_COMMITTED_ACTION_SEQ=6;for(const [i,t]of defs.entries())r.s.quests[t.id]={guildAccepted:true,claimed:false,node:'INVESTIGATE',state:'진행중',taskObjective:{version:1,progress:0,acceptedSeq:i+1}};r=new R(db,copy(r.s));assert.equal(r.taskAcceptedCount(),6);guild(r);assert.throws(()=>r.action('COMMISSION_ACCEPT',{quest:'Q_TASK_COOKING_01'}),/5개/);assert.equal(r.taskAcceptedCount(),6);});

check('real borrowed story companion cannot satisfy owned squad or elemental objectives; generic victory remains credited',()=>{
 // An explicitly accepted historical objective is carried into a real authored first-fight fixture.
 // Both branches use native loan preparation, character acquisition, combat settlement and reload.
 const accepted=fresh();level(accepted,30);own(accepted,['MOND_AMBER','MOND_KAEYA','MOND_LISA']);guild(accepted);accepted.action('COMMISSION_ACCEPT',{quest:'Q_TASK_MOND_SQUADS_01'});const quest=copy(accepted.s.quests.Q_TASK_MOND_SQUADS_01);
 let seed=new R(db);seed.newGame({route:'ROUTE_TRAVELER',name:'소유 조건 시험',seed:27});seed.s.global.ENCOUNTER_COOLDOWN=100;
 for(let i=0;i<180&&!seed.s.battlePreparation;i++){if(seed.s.storyJourney){const j=seed.s.storyJourney;if(seed.s.global.CURRENT_MAP_ID===j.target)seed.action('JOURNEY_RESUME');else seed.action('MOVE',{edge:seed.navigationRoute(j.target).edges[0][0]});continue;}const n=seed.storyNode(),cs=seed.storyChoices();seed.action(cs.length?'STORY_CHOICE':n[5]==='INPUT_TEXT'?'STORY_NAME':'STORY_NEXT',cs.length?{node:cs[0][4]}:n[5]==='INPUT_TEXT'?{name:'소유 조건 시험'}:{node:n[4]});}
 assert(seed.s.tutorialV2.loan);level(seed,30);for(const id of ['MOND_KAEYA','MOND_LISA','LIYUE_XIANGLING'])seed.wishGrant({kind:'char',id,rarity:4});seed.s.quests.Q_TASK_MOND_SQUADS_01=quest;seed.s.global.LAST_COMMITTED_ACTION_SEQ=Math.max(seed.s.global.LAST_COMMITTED_ACTION_SEQ,quest.taskObjective.acceptedSeq);Object.assign(seed.tutorialState().done,{combatAttack:true,combatGuard:true,combatSkill:true,combatBurst:true});
 for(const permanentlyOwned of [false,true]){let r=new R(db,copy(seed.s));if(permanentlyOwned)r.wishGrant({kind:'char',id:'MOND_AMBER',rarity:4});r.action('PARTY',{char:'MOND_AMBER',slot:2});r.action('PARTY',{char:'MOND_KAEYA',slot:3});r.action('PARTY',{char:'MOND_LISA',slot:4});const weapon=r.s.tutorialV2.loan?.weaponSlot||r.s.inventory.find(i=>i.equip==='EQ_BOW_SLINGSHOT').slot;r.action('EQUIP',{slot:weapon,owner:'MOND_AMBER'});
  for(let n=0;n<20;n++){r.taskView();if(JSON.stringify(r.s.tasks.dailyDefinitions.D_V168_PYRO_HYDRO?.selectedElements)==='["PYRO"]')break;advance(DAY);}assert.deepEqual(copy(r.s.tasks.dailyDefinitions.D_V168_PYRO_HYDRO.selectedElements),['PYRO']);r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:['MOND_AMBER','MOND_KAEYA','MOND_LISA']});assert.equal(r.s.runtime.actors.filter(a=>a.side==='ALLY').length,4,'borrowed companion still fights normally');assert.equal(r.s.runtime.taskSnapshot.party.find(m=>m.id==='MOND_AMBER').owned,permanentlyOwned);
  if(!permanentlyOwned){const oldSave=copy(r.s);for(const m of oldSave.runtime.taskSnapshot.party)delete m.owned;r=new R(db,oldSave);assert(!('owned' in r.s.runtime.taskSnapshot.party.find(m=>m.id==='MOND_AMBER')),'old in-flight snapshots remain loadable');}
  for(const a of r.s.runtime.actors)if(a.side==='ENEMY')a.hp=0;r.s.runtime.enemyReserve=[];r.action('COMBAT_BEGIN');assert(!r.s.runtime);assert.equal(r.s.tasks.daily.win,1,'generic victory includes tutorial loan fights');assert.equal(r.s.quests.Q_TASK_MOND_SQUADS_01.taskObjective.progress,permanentlyOwned?1:0);assert.equal(r.taskView().daily.find(t=>t.id==='D_V168_PYRO_HYDRO').progress,permanentlyOwned?1:0);new R(db,copy(r.s));
 }
});

check('snapshot tampering cannot inflate goal, currency reward or accepted time',()=>{const r=fresh();level(r);guild(r);r.action('COMMISSION_ACCEPT',{quest:'Q_TASK_MOND_PATROL_01'});r.taskView();for(const mutate of [s=>s.quests.Q_TASK_MOND_PATROL_01.taskObjective.definition.reward.mora=999999,s=>s.quests.Q_TASK_MOND_PATROL_01.taskObjective.definition.goal=0,s=>s.quests.Q_TASK_MOND_PATROL_01.taskObjective.acceptedSeq=Number.MAX_SAFE_INTEGER,s=>s.tasks.dailyDefinitions[s.tasks.dailyIds[0]].reward.primogem=9999,s=>s.tasks.weeklyIds.push(s.tasks.weeklyIds[0]),s=>s.tasks.weeklyDefinitions[s.tasks.weeklyIds[0]].individual=false]){const bad=copy(r.s);mutate(bad);assert.throws(()=>new R(db,bad),/임무 기록/);}});
console.log(JSON.stringify({ok:!process.exitCode,checks:passed}));
