'use strict';
// Native actor/skill tests for the narrow 0.16.18 support tuning; no monster/stat fixture patches.
const assert=require('node:assert/strict'),{load,setup}=require('../tools/audit_protagonist_v01618.cjs'),env=load();
const PLAYER='PLAYER_CUSTOM',IE='PLAYER_ISEKAI_E',IQ='PLAYER_ISEKAI_Q',EXPOSED='STATUS_ISEKAI_EXPOSED';
const cp=x=>JSON.parse(JSON.stringify(x)),results=[];
function test(name,fn){try{results.push({name,ok:true,evidence:fn()});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);process.exitCode=1;}}
function battle({route='ROUTE_ISEKAI',team=['MOND_FISCHL','LIYUE_XIANGLING','MOND_BARBARA'],level=50}={}){const r=setup(env,{route,team,level,enhance:10,talent:8,map:'MAP_LIYUE_GOLDEN_HOUSE'});r.startBattle('EG_BOSS_TARTAGLIA','EXPLICIT');r.action('COMBAT_BEGIN');return r;}
function cast(r,a,id,t){const c=r.actorCards(a).find(x=>x.id===id);assert(c,id);assert.equal(r.cardReason(a,c),'');return r.executeCard(a,c,t.id);}
const actor=r=>r.s.runtime.actors.find(a=>a.source===PLAYER),foe=r=>r.s.runtime.actors.find(a=>a.side==='ENEMY'&&a.hp>0);

test('support coefficients retain personal stats, four-person enemy difficulty, cooldowns and 60% ceiling',()=>{
 const cfg=env.api.isekaiRework;assert.deepEqual(cp(cfg.profile),{BASE_HP:560,BASE_ATK:62,BASE_DEF:30,BASE_SPD:63});assert.equal(cfg.e.coefficient,1.5);assert.equal(cfg.e.rounds,2);assert.equal(cfg.e.cooldown,2);assert.equal(cfg.e.vulnerable_pct,30);assert.equal(cfg.e.boss_pct,18);assert.equal(cfg.q.cooldown,3);assert.equal(cfg.q.cap_pct,60);
 const i=battle(),t=battle({route:'ROUTE_TRAVELER'}),pro=i.protagonistConfig();assert.deepEqual(cp(pro.traveler),cp(t.protagonistConfig().traveler));const enemies=r=>r.s.runtime.actors.filter(a=>a.side==='ENEMY').map(a=>[a.source,a.level,a.maxHp,a.atk,a.def,a.spd]);assert.deepEqual(enemies(i),enemies(t));assert(i.combatStat(actor(i),'atk')<t.combatStat(actor(t),'atk'));for(const level of[1,10,30,60]){const r=setup(env,{level,team:[]});const bonus=r.protagonistJointBonus(r.player());assert(Number.isFinite(bonus)&&bonus>=0&&bonus<=60);}return{enemy:enemies(i),personalAtk:[i.combatStat(actor(i),'atk'),t.combatStat(actor(t),'atk')]};
});

test('one live mark strengthens existing attacks, replaces itself and expires without stacking',()=>{
 const r=battle(),a=actor(r),t=foe(r),ally=r.s.runtime.actors.find(x=>x.source==='MOND_FISCHL'),base=r.combatDamageMultiplier(ally,t,'번개',{});cast(r,a,IE,t);const m=t.statuses.find(s=>s.id===EXPOSED);assert(m&&m.rounds===2&&m.pct===18&&m.caster===a.id);assert.equal(Math.round(r.combatDamageMultiplier(ally,t,'번개',{})/base*100),118);assert.equal(a.cooldowns[IE],2);a.cooldowns[IE]=0;cast(r,a,IE,t);assert.equal(t.statuses.filter(s=>s.id===EXPOSED).length,1);assert.equal(Math.round(r.combatDamageMultiplier(ally,t,'번개',{})/base*100),118);for(let n=0;n<4&&t.statuses.some(s=>s.id===EXPOSED);n++)r.roundEnd();assert(!t.statuses.some(s=>s.id===EXPOSED));return{pct:m.pct,originalRounds:m.rounds};
});

test('protagonist death immediately removes exposure; no healing resurrection or saved support remains',()=>{
 const r=battle(),a=actor(r),t=foe(r),ally=r.s.runtime.actors.find(x=>x.source==='MOND_FISCHL');cast(r,a,IE,t);const hp=a.hp;r.applyDamage(t,a,a.hp+(a.shields||[]).reduce((n,s)=>n+s.value,0)+1,{element:'물리',sourceKind:'TEST_FINAL_PACKET'});assert.equal(a.hp,0);assert(!t.statuses.some(s=>s.id===EXPOSED));const off=r.combatDamageMultiplier(ally,t,'번개',{});assert.equal(r.heal(a,a.maxHp,'동료'),0);assert.equal(a.hp,0);assert(!t.statuses.some(s=>s.id===EXPOSED));
 // Re-load a legal boundary snapshot, retaining the dead caster and surviving companions.
 const restored=new env.R(env.db,cp(r.s));const rt=restored.s.runtime.actors.find(x=>x.id===t.id),ra=restored.s.runtime.actors.find(x=>x.id===ally.id);assert(!rt.statuses.some(s=>s.id===EXPOSED));assert.equal(restored.combatDamageMultiplier(ra,rt,'번개',{}),off);return{hpBefore:hp,hpAfter:a.hp,remainingAllies:r.s.runtime.actors.filter(x=>x.side==='ALLY'&&x.hp>0).length};
});

test('joint strike preserves personal coefficient, attacks once per companion and consumes no companion turns or cooldowns',()=>{
 const r=battle(),a=actor(r),t=foe(r),members=r.protagonistJointMembers(),before=members.map(x=>({id:x.id,turns:x.turns,cooldowns:cp(x.cooldowns)})),damage=r.damage,packets=[];r.damage=function(x,y,k,e,o){if(o?.card===IQ)packets.push({id:x.id,source:x.source,k,element:e});return damage.call(this,x,y,k,e,o);};const bonus=r.protagonistJointBonus(a),start=r.s.runtime.log.length;cast(r,a,IQ,t);assert.equal(packets.length,members.length);assert.equal(packets.filter(x=>x.source===PLAYER).length,1);assert.equal(packets.find(x=>x.source===PLAYER).k,.65*(1+bonus/100));for(const x of packets.filter(x=>x.source!==PLAYER))assert.equal(x.k,.85*(1+bonus/100));assert.deepEqual(packets.filter(x=>x.source!==PLAYER).map(x=>x.element),['번개','불','물']);
 for(const b of before){const x=members.find(m=>m.id===b.id);assert.equal(x.turns,b.turns);if(x.source!==PLAYER)assert.deepEqual(cp(x.cooldowns),b.cooldowns);}assert.equal(a.cooldowns[IQ],3);assert.equal(r.s.runtime.log.slice(start).filter(x=>x.participants).length,1);assert(r.cardReason(a,r.actorCards(a).find(x=>x.id===IQ)));return{bonus,packets};
});

test('dead, incapacitated and preparing companions do not join; a solo protagonist cannot use Q',()=>{
 const r=battle(),a=actor(r),t=foe(r),dead=r.s.runtime.actors.find(x=>x.source==='MOND_FISCHL'),charging=r.s.runtime.actors.find(x=>x.source==='LIYUE_XIANGLING'),locked=r.s.runtime.actors.find(x=>x.source==='MOND_BARBARA');r.applyDamage(t,dead,dead.hp+100,{element:'물리',sourceKind:'TEST_FINAL_PACKET'});charging.charging={card:'LIYUE_XIANGLING_Q',remaining:1};r.applyCombatControl(t,locked,'FREEZE',{bossImmune:false,element:'얼음'});assert(r.protagonistMemberReason(dead));assert(r.protagonistMemberReason(charging));assert(r.protagonistMemberReason(locked));assert(r.cardReason(a,r.actorCards(a).find(x=>x.id===IQ)));const solo=battle({team:[]}),sa=actor(solo);assert(solo.cardReason(sa,solo.actorCards(sa).find(x=>x.id===IQ)));return{unavailable:r.protagonistJointMembers().map(x=>({id:x.id,reason:r.protagonistMemberReason(x)}))};
});

test('invalid legacy basic-attack metadata keeps the personal .65 joint fallback',()=>{
 const r=battle(),a=actor(r),t=foe(r),row=r.row('08_SKILL_CARD_DB','PLAYER_BASIC_ATTACK').slice();row[36]='invalid legacy metadata';r.tables['08_SKILL_CARD_DB'].set('PLAYER_BASIC_ATTACK',row);const damage=r.damage,packets=[];r.damage=function(x,y,k,e,o){if(o?.card===IQ)packets.push({source:x.source,k});return damage.call(this,x,y,k,e,o);};const bonus=r.protagonistJointBonus(a);cast(r,a,IQ,t);assert.equal(packets.find(x=>x.source===PLAYER).k,.65*(1+bonus/100));for(const x of packets.filter(x=>x.source!==PLAYER))assert.equal(x.k,.85*(1+bonus/100));return{packets};
});

test('existing injured saves and profiles reload without healing, repeat stat migration or altered equipment',()=>{
 const r=setup(env,{route:'ROUTE_ISEKAI',level:30,team:['MOND_AMBER','MOND_KAEYA','MOND_LISA']});r.s.global.PLAYER_HP_CURRENT=Math.floor(r.s.global.PLAYER_HP_MAX*.4);for(const p of r.s.party.filter(x=>x.active&&x.source!==PLAYER))r.s.chars[p.source].hp=Math.floor(r.character(p.source).maxHp*.6);const before=cp(r.s),after=new env.R(env.db,cp(r.s));assert.equal(after.s.global.PLAYER_HP_CURRENT,before.global.PLAYER_HP_CURRENT);for(const k of ['BASE_HP','BASE_ATK','BASE_DEF','BASE_SPD'])assert.equal(after.s.global['PLAYER_'+k],before.global['PLAYER_'+k]);assert.deepEqual(cp(after.s.inventory),before.inventory);for(const p of r.s.party.filter(x=>x.active&&x.source!==PLAYER))assert.equal(after.s.chars[p.source].hp,before.chars[p.source].hp);return{hp:after.s.global.PLAYER_HP_CURRENT,maxHp:after.s.global.PLAYER_HP_MAX};
});

test('an already saved old exposure keeps its original percentage and cooldown through reload',()=>{
 const previous=load(undefined,{normal:20,boss:12,jointCoefficient:.65}),r=setup(previous,{route:'ROUTE_ISEKAI',level:50,team:['MOND_FISCHL','LIYUE_XIANGLING','MOND_BARBARA'],map:'MAP_LIYUE_GOLDEN_HOUSE',enhance:10,talent:8});r.startBattle('EG_BOSS_TARTAGLIA','EXPLICIT');r.action('COMBAT_BEGIN');const a=actor(r),t=foe(r);cast(r,a,IE,t);const before=cp(r.s),restored=new env.R(env.db,before),rt=restored.s.runtime.actors.find(x=>x.id===t.id),ra=restored.s.runtime.actors.find(x=>x.id===a.id);assert.equal(rt.statuses.find(s=>s.id===EXPOSED).pct,12);assert.equal(ra.cooldowns[IE],a.cooldowns[IE]);assert.equal(rt.hp,t.hp);assert.equal(ra.hp,a.hp);assert.deepEqual(cp(restored.s.inventory),cp(r.s.inventory));return{savedPct:12,currentNewCastPct:env.api.isekaiRework.e.boss_pct,savedCooldown:ra.cooldowns[IE]};
});

test('a native shield counter that kills the E caster cannot add a new orphaned exposure',()=>{
 const r=setup(env,{route:'ROUTE_ISEKAI',level:5,team:['MOND_AMBER'],map:'MAP_MOND_FOREST',enhance:0,talent:1});r.startBattle('EG_FATUI_PATROL','EXPLICIT');r.action('COMBAT_BEGIN');const a=actor(r),t=r.s.runtime.actors.find(x=>x.source==='MON_FATUI_ANEMO');assert(t);cast(r,t,'ECARD_FATUI_ANEMO_GUARD',t);const sh=t.shields.find(x=>x.source==='ECARD_FATUI_ANEMO_GUARD');assert(sh);r.applyDamage(a,t,sh.value-1,{element:'물리',sourceKind:'TEST_PRIOR_PACKET'});assert.equal(sh.value,1);r.applyDamage(t,a,a.hp+(a.shields||[]).reduce((n,s)=>n+s.value,0)-1,{element:'물리',sourceKind:'TEST_PRIOR_PACKET'});assert.equal(a.hp,1);const start=r.s.runtime.log.length;cast(r,a,IE,t);assert.equal(a.hp,0);assert(t.hp>0);assert(r.s.runtime.log.slice(start).some(x=>x.sourceKind==='COUNTER'));assert(!t.statuses.some(s=>s.id===EXPOSED));const restored=new env.R(env.db,cp(r.s));assert(!restored.s.runtime.actors.find(x=>x.id===t.id).statuses.some(s=>s.id===EXPOSED));return{casterHp:a.hp,targetHp:t.hp,orphanedMark:false};
});

test('fresh routes and the first joined companion keep actual early story and skill locks',()=>{
 const evidence=[];for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI']){const r=new env.R(env.db);r.newGame({name:'초기 기술 검증',route,seed:27,saveId:'EARLY-SUPPORT-'+route});const gates=['FLAG_TRV_MON_CH1_CLEAR','FLAG_TRV_MON_CH2_CLEAR','FLAG_ISK_M03_CLEAR','FLAG_ISK_M05_CLEAR','FLAG_ACCESS_REGION_LIYUE'];for(const id of gates)assert(![true,'TRUE'].includes(r.s.flags[id]));assert.equal(r.protagonistUnlocked(),false);assert.deepEqual(cp(r.protagonistAllowedIds()),route==='ROUTE_ISEKAI'?[IE,IQ]:[]);
  // Exact first 4-star ownership is a declared fixture; it uses the native grant/party projection,
  // without advancing chapters, ascensions, resonance or the tutorial-completion flags.
  r.wishGrant({kind:'char',id:'MOND_AMBER',rarity:4});r.s.party[1]={slot:'PARTY_2',type:'CHAR',source:'MOND_AMBER',control:'AI',active:true,tactic:'균형'};r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';r.startBattle('EG_MOND_HILI_PATROL','RANDOM');const a=actor(r),cards=r.actorCards(a);if(route==='ROUTE_TRAVELER')assert(!cards.some(c=>/PLAYER_TRAVELER_ANEMO_(E|Q)$/.test(c.id)));else{assert(cards.some(c=>c.id===IE));assert(cards.some(c=>c.id===IQ));assert.equal(r.protagonistJointMembers().length,2);}for(const id of gates)assert(![true,'TRUE'].includes(r.s.flags[id]));assert(!r.tutorialState().done.combatSkill&&!r.tutorialState().done.combatBurst);evidence.push({route,level:a.level,party:r.protagonistJointMembers().map(x=>({source:x.source,level:x.level})),futureGates:gates.map(id=>({id,value:r.s.flags[id]??null})),allowedSkills:cp(r.protagonistAllowedIds())});}return evidence;
});

if(process.env.CRPG_PROTAGONIST_TEST_OUT){require('node:fs').writeFileSync(process.env.CRPG_PROTAGONIST_TEST_OUT,JSON.stringify({version:'0.16.18',fingerprint:env.fingerprint,results},null,2)+'\n');}
