'use strict';
// Independent gate over recorded native combats: this proves the sampled timing
// envelope, not an infinite-run/any-party guarantee. Failed campaigns are kept.
const assert=require('node:assert/strict'),zlib=require('node:zlib');
const {c,fs,path,root}=require('./helpers_v011.cjs');
const G=c.CRPGRuntime.growthV01522,cp=x=>JSON.parse(JSON.stringify(x));
const P=path.join(root,'docs/data/balance_v01622/growth'),old=path.join(root,'docs/data/full_balance_v01621/growth');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),rows=[];
// The 0.16.22 ledger proves its recorded source, not an unchanged future file.
// A future module may change unrelated boss rules; verify the exact sealed
// published source while current payout/requirement checks above remain live.
function historicalProductHash(file,expected){
 const hash=p=>require('node:crypto').createHash('sha256').update(fs.readFileSync(p)).digest('hex');
 const current=path.join(root,'source',file);if(hash(current)===expected)return expected;
 const sealed=path.join(root,'docs/data/balance_v01624/source_before/source',file);
 assert(fs.existsSync(sealed),'Missing sealed historical source: '+file);
 const actual=hash(sealed);assert.equal(actual,expected,'Sealed historical source hash: '+file);
 console.log(JSON.stringify({historicalSource:file,sealed:path.relative(root,sealed),sha256:actual,currentSha256:hash(current)}));
 return actual;
}
let checks=0;const check=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
for(const x of read(path.join(old,'ascension_final_comparison.json')).rows){const a=x.after;rows.push({key:'old:'+JSON.stringify(Object.fromEntries(Object.entries(x.condition).filter(([k])=>k!=='stage').sort())),stage:x.condition.stage,kind:'ASCENSION',...a,limit:x.condition.limit});}
for(const label of ['maximum_party_baseline','pressure_candidate_native','talent_pressure_native','representative_before_final_rules_native'])for(const x of read(path.join(P,label,'summary.json')).rows){const keys=['level','element','kind','team','teamName','constellations','seed','limit','restBelow','enhance','talent'];rows.push({...x,key:label+':'+JSON.stringify(Object.fromEntries(keys.filter(k=>k in x).map(k=>[k,x[k]]).sort()))});}
for(const x of read(path.join(old,'talent_comparison.json')).rows)rows.push({...x.after,kind:'TALENT',limit:3,stage:x.stage,key:'oldtalent:'+JSON.stringify([x.team,x.constellations,x.seed])});
const groups=new Map();for(const row of rows){if(!groups.has(row.key))groups.set(row.key,new Map());groups.get(row.key).set(row.stage,row);}
function compare(kind,rewards){let successful=0,blocked=0,min=Infinity,top=Infinity;for(const stages of groups.values())for(const [low,a]of stages)for(const [high,b]of stages){if(low>=high||a.kind!==kind||b.kind!==kind||rewards[low]===undefined||rewards[high]===undefined)continue;if(a.wins!==a.limit||b.wins!==b.limit||a.losses||b.losses){blocked++;continue;}const factor=(rewards[high]/(b.seconds/b.wins))/(rewards[low]/(a.seconds/a.wins));successful++;min=Math.min(min,factor);if(high===Math.max(...Object.keys(rewards).map(Number)))top=Math.min(top,factor);}return{successful,blocked,min,top};}
check('eight elements share the selected table and future 25/50-win final payments',()=>{const expected={5:1,10:2,15:3,20:10,25:32,30:47,35:105,40:153,45:318,50:642,55:1932,60:5400};for(const e of ['NEUTRAL','PYRO','HYDRO','ANEMO','ELECTRO','CRYO','GEO','DENDRO']){assert.deepEqual(cp(G.domainAscensionGems[e]),expected);assert.deepEqual(cp(G.ascensionGemCosts[e]),[3,6,94,765,5136,135000]);assert.equal(G.ascensionGemCosts[e][5]/G.domainAscensionGems[e][60],25);}assert.equal(G.ascensionRewardVersion,4);assert.equal(G.talentRewardVersion,3);});
check('projected current quantities avoid reversal over 1866 candidate observations, with highest at least five percent',()=>{const x=compare('ASCENSION',G.domainAscensionGems.NEUTRAL);assert.equal(x.successful,1866);assert.equal(x.blocked,42);assert(x.min>=1-1e-10,JSON.stringify(x));assert(x.top>=1.05-1e-10,JSON.stringify(x));console.log(JSON.stringify({ascensionObserved:x}));});
check('regional talent currencies retain 63 highest wins and every successful observation has at least five percent',()=>{for(const [reg,total]of [['MOND',2016],['LIYUE',5040]]){const pay=G.domainTalentBooks[reg],x=compare('TALENT',pay);assert.equal(G.talentBookCosts[reg].reduce((n,x)=>n+3*x,0),total);assert.equal(total/pay[Math.max(...Object.keys(pay).map(Number))],63);assert(x.min>=1.05-1e-10,JSON.stringify({reg,...x}));console.log(JSON.stringify({region:reg,talentObserved:x}));}});
check('eight K25 candidate native samples prove growth-only payouts preserve exact combat timings, HP and recovery bills',()=>{const before=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(P,'representative_before_native.json.gz')))),after=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(P,'representative_final_native/native.json.gz'))));assert.equal(before.rows.length,8);assert.equal(after.rows.length,8);for(let i=0;i<8;i++){const a=before.rows[i],b=after.rows[i];assert.equal(b.seconds,a.seconds);assert.deepEqual(b.final,a.final);assert.equal(b.lodgingMora,a.lodgingMora);assert.equal(b.wins,a.wins);assert.equal(b.losses,a.losses);const pay=b.kind==='ASCENSION'?after.catalog.ascensionGems[b.element][b.stage]:after.catalog.talentBooks[b.stage<=25?'MOND':'LIYUE'][b.stage];assert.equal(b.materials,b.wins*pay);for(const fight of b.battles){assert.equal(fight.materials,pay);assert.equal(fight.growthDomain[b.kind==='ASCENSION'?'ascensionRewardVersion':'talentRewardVersion'],b.kind==='ASCENSION'?4:3);}}});
check('preserved B K35 samples verify their historical payout table and source snapshot',()=>{const x=read(path.join(P,'release_final_assessment.json')),historical=read(path.join(P,'release_final_native/summary.json')).catalog;assert.equal(x.selectedCounts.conditions,16);assert.equal(x.selectedCounts.nativeBattles,47);assert.equal(x.selectedCounts.wins,46);assert.equal(x.selectedCounts.losses,1);assert.equal(x.ascension.successful,10);assert.equal(x.ascension.blocked,1);assert(x.ascension.minimumFactor>=1);assert(x.ascension.highestMinimumFactor>=1.1);assert(x.talent.minimumFactor>=1.05);for(const row of x.selectedRows){const pay=row.kind==='ASCENSION'?historical.ascensionGems[row.element][row.stage]:historical.talentBooks[row.stage<=25?'MOND':'LIYUE'][row.stage];assert.equal(row.materials,row.wins*pay);for(const fight of row.battles)if(fight.result.victory){assert.equal(fight.materials,pay);assert.equal(fight.promised.items[row.item],pay);}}assert.equal(x.productHashes['runtime_growth_v01522.js'],require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(P,'cash_cost_adjustment/before_runtime_growth_v01522.js'))).digest('hex'));assert.equal(x.productHashes['runtime_rules.js'],require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(root,'source/runtime_rules.js'))).digest('hex'));console.log(JSON.stringify({finalK35:x.ascension,talent:x.talent,blocked:x.blockedCondition}));});
check('cash-margin selected quantities survive declared legal-wealth120-second sensitivity and fresh native settlement',()=>{const m=read(path.join(P,'cash_cost_adjustment/cash_model.json')),x=read(path.join(P,'cash_cost_adjustment/assessment.json'));assert.deepEqual(cp(G.domainAscensionGems.NEUTRAL),m.selected);assert.deepEqual(cp(G.ascensionGemCosts.NEUTRAL),m.costs4);assert.equal(m.total4,141004);assert.equal(m.total5,282008);assert.equal(m.cashAdjusted.successful,1876);assert.equal(m.cashAdjusted.blocked,43);assert.equal(m.cashAdjusted.noInversion,1876);assert(m.cashAdjusted.minFactor>=1.005);assert(m.cashAdjusted.topMinimum>=1.05);assert.equal(m.cashModel.sameAccountActualWealthMeasured,false);assert.equal(m.cashModel.secondsPerLegalWealthClaim,120);assert.equal(x.selectedCounts.conditions,16);assert.equal(x.selectedCounts.nativeBattles,47);assert.equal(x.selectedCounts.wins,46);assert.equal(x.selectedCounts.losses,1);for(const row of x.selectedRows){const pay=row.kind==='ASCENSION'?G.domainAscensionGems[row.element][row.stage]:G.domainTalentBooks[row.stage<=25?'MOND':'LIYUE'][row.stage];assert.equal(row.materials,row.wins*pay);for(const fight of row.battles)if(fight.result.victory)assert.equal(fight.materials,pay);}for(const d of x.comparisonToB)for(const key of ['exactSeconds','exactHpGrowth','exactLodgingMora','exactWallet','exactWinsLosses'])assert.equal(d[key],true);for(const file of ['runtime_growth_v01522.js','runtime_rules.js'])assert.equal(x.productHashes[file],historicalProductHash(file,x.productHashes[file]));for(const input of m.sources)assert.equal(input.sha256,require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(root,input.path))).digest('hex'));console.log(JSON.stringify({cashAdjustedMinimum:m.cashAdjusted.minFactor,highest:m.cashAdjusted.topMinimum,successful:1876,blocked:43,fresh:x.selectedCounts,scope:m.scope}));});
console.log(JSON.stringify({checks,ok:true,scope:'historical envelope/current payout tables; not fresh all farming'}));
