/* Isolated actual-DB integration tests; fixture state setup is explicit. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const source=process.env.CRPG_SOURCE||path.resolve(__dirname,'../source'),dbPath=process.env.CRPG_DB||path.resolve(__dirname,'../content/db.json');
const ctx=vm.createContext({console}),hashes={},files=[...fs.readFileSync(path.join(source,'index.html'),'utf8').matchAll(/<script\s+src="(runtime[^/]*\.js)"/g)].map(x=>x[1]);
for(const file of files){const p=file==='runtime_places.js'?path.join(source,file):path.join(source,file),text=fs.readFileSync(p,'utf8');hashes[file]=crypto.createHash('sha256').update(text).digest('hex');vm.runInContext(text,ctx,{filename:file});}
const db=JSON.parse(fs.readFileSync(dbPath,'utf8')),Runtime=ctx.CRPGRuntime.Runtime;
ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});
const copy=x=>JSON.parse(JSON.stringify(x)),results=[];let seq=0;
function fresh(route='ROUTE_TRAVELER'){const r=new Runtime(db);r.newGame({name:'시설검증',route,seed:74219,saveId:'PLACE-'+(++seq)});return r;}
function free(map='MAP_MOND_CITY',time='08:00'){const r=fresh();Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,WORLD_TIME:time,STORY_MENU_POLICY:''});r.prepareStory();return r;}
function rejected(r,type,params,code='ACTION_LOCK'){const before=r.serialize();assert.throws(()=>r.action(type,params),e=>!code||e.code===code);assert.equal(r.serialize(),before,'rejected action mutated save');}
function enter(r,merchant,mode='SHOP'){if(merchant==='MRC_BLACKSMITH_COMMON'&&r.s.global.CURRENT_MAP_ID==='MAP_MOND_CITY')merchant='MRC_MOND_EQUIP';const e=r.placeEntries().find(e=>e.merchant===merchant||e.entity===merchant||e.id===merchant);assert.ok(e,'fixture place '+merchant);r.action('PLACE_ENTER',{place:e.id,mode});return e;}
function fundRecipe(r,id,count=1){const c=r.recipeCost(r.recipeDefinition(id),count);r.s.global.MORA+=c.mora;for(const [id,n]of Object.entries(c.items))r.giveItem(id,n);}
function test(name,f){try{const evidence=f();results.push({name,ok:true,evidence:evidence||null});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:{code:e.code,message:e.message,stack:e.stack}});console.error('FAIL '+name+'\n'+e.stack);}}
test('catalog uses all actual schedule definitions and DB labels',()=>{const r=free(),c=r.placeCatalog(),s=r.db['51_EVENT_DB'].filter(x=>x[1]==='NPC_SCHEDULE'&&x[11]==='Y');assert.equal(c.filter(x=>x.kind==='FACILITY').length,s.length);for(const e of c.filter(x=>x.kind==='FACILITY'))assert.equal(e.name,JSON.parse(s.find(x=>x[0]===e.id)[13]).label);assert.equal(r.placeBossEntries().length,0);return{facilities:s.length,bossRoutes:c.filter(x=>x.kind==='BOSS').length,mond:r.placeEntries().map(x=>({name:x.name,modes:x.modes}))};});
test('story locks entry and transaction shortcuts with zero mutation',()=>{const r=fresh();rejected(r,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP',mode:'SHOP'});rejected(r,'BUY',{stock:'STK_CRPG_MOND_WORN_SWORD'});rejected(r,'CRAFT',{recipe:'REC_FOOD_EGG_FRY'});});
test('free world has no global SHOP/CRAFT/BOSS screen or BUY authorization',()=>{const r=free();for(const screen of ['SHOP','CRAFT','BOSS_INTRO'])rejected(r,'MENU',{screen});rejected(r,'BUY',{stock:'STK_CRPG_MOND_WORN_SWORD'});rejected(r,'CRAFT',{recipe:'REC_ARMOR_TRAVEL'});assert.equal(r.view().stocks.length,0);});
test('entering one merchant restricts purchases to that merchant',()=>{const r=free();enter(r,'MRC_MOND_GENERAL');r.action('BUY',{stock:'STK_MOND_FOOD_001',quantity:1});assert.equal(r.itemCount('ING_MILK'),1);rejected(r,'BUY',{stock:'STK_CRPG_MOND_WORN_SWORD'});rejected(r,'BUY',{stock:'STK_INN_MOND'});assert.ok(r.placeStocks().every(x=>x.row[1]==='MRC_MOND_GENERAL'));enter(r,'MRC_MOND_EQUIP');r.action('BUY',{stock:'STK_CRPG_MOND_WORN_SWORD'});assert.ok(r.s.inventory.some(x=>x.equip==='EQ_CRPG_WORN_SWORD'));});
test('TALK to an actual NPC does not authorize neighboring shops or kitchens',()=>{const r=free();const sara=enter(r,'NPC_MOND_KATHERYNE','TALK');assert.equal(sara.name,'캐서린');rejected(r,'BUY',{stock:'STK_MOND_FOOD_001'});rejected(r,'CRAFT',{recipe:'REC_FOOD_EGG_FRY'});assert.deepEqual(copy(sara.modes),['TALK']);});
test('system save/load keeps entrance, while hidden purchases require returning to SHOP',()=>{const r=free();enter(r,'MRC_MOND_EQUIP');r.action('MENU',{screen:'SYSTEM'});rejected(r,'BUY',{stock:'STK_CRPG_MOND_WORN_SWORD'});const loaded=new Runtime(db,JSON.parse(r.serialize()));assert.equal(loaded.currentPlace().merchant,'MRC_MOND_EQUIP');loaded.action('MENU',{screen:'SHOP'});loaded.action('BUY',{stock:'STK_CRPG_MOND_WORN_SWORD'});assert.equal(loaded.s.global.MORA,70);});
test('leaving, changing map, or visiting another NPC clears merchant authorization',()=>{for(const kind of ['PLACE_LEAVE','MOVE','NPC','MENU']){const r=free();enter(r,'MRC_MOND_GENERAL');if(kind==='MOVE')r.action(kind,{edge:'EDGE_MOND_CITY_TO_PLAINS'});else if(kind==='NPC')r.action(kind,{entity:'NPC_MOND_KATHERYNE'});else if(kind==='MENU')r.action(kind,{screen:'LOCATION'});else r.action(kind);assert.equal(r.s.placeVisit,null);rejected(r,'BUY',{stock:'STK_MOND_FOOD_001'});}});
test('real opening hours reject outside intervals and invalidate a visit at closure',()=>{for(const time of ['05:59','22:00']){const r=free('MAP_MOND_CITY',time);rejected(r,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP',mode:'SHOP'});}const r=free('MAP_MOND_CITY','21:59');enter(r,'MRC_MOND_EQUIP');r.action('WAIT',{minutes:1});assert.equal(r.s.placeVisit,null);assert.equal(r.s.global.SCREEN_MODE,'LOCATION');rejected(r,'BUY',{stock:'STK_CRPG_MOND_WORN_SWORD'});const dawn=free('MAP_MOND_CITY','06:00');enter(dawn,'MRC_MOND_EQUIP');});
test('all entrances enforce actual map and reject forged facility modes',()=>{const r=free('MAP_MOND_PLAINS');rejected(r,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP',mode:'SHOP'});const city=free();rejected(city,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_GENERAL',mode:'CRAFT'});rejected(city,'PLACE_ENTER',{place:'made-up',mode:'SHOP'});});
test('cooking works only after explicit cooking entrance',()=>{const r=free();fundRecipe(r,'REC_FOOD_EGG_FRY');enter(r,'MRC_MOND_GENERAL');rejected(r,'CRAFT',{recipe:'REC_FOOD_EGG_FRY'});enter(r,'SERVICE_MOND_COOK','CRAFT');assert.ok(r.placeRecipes().some(x=>x.row[0]==='REC_FOOD_EGG_FRY'));r.action('CRAFT',{recipe:'REC_FOOD_EGG_FRY'});assert.equal(r.itemCount('FOOD_TEA_BREAK_PANCAKE'),1);rejected(r,'CRAFT',{recipe:'REC_ARMOR_TRAVEL'});});
test('smith and alchemy recipes do not borrow each other\'s city-wide permissions',()=>{const r=free();fundRecipe(r,'REC_ARMOR_TRAVEL');fundRecipe(r,'REC_ALCH_HEALING_POTION');enter(r,'MRC_ALCHEMY_COMMON','CRAFT');rejected(r,'CRAFT',{recipe:'REC_ARMOR_TRAVEL'});r.action('CRAFT',{recipe:'REC_ALCH_HEALING_POTION'});assert.equal(r.itemCount('TRPG_HEALING_POTION'),1);enter(r,'MRC_BLACKSMITH_COMMON','CRAFT');rejected(r,'CRAFT',{recipe:'REC_ALCH_HEALING_POTION'});r.action('CRAFT',{recipe:'REC_ARMOR_TRAVEL'});assert.ok(r.s.inventory.some(x=>x.equip==='EQ_ARMOR_TRAVEL_COAT'));});
test('enhancement requires the entered smith, not merely another smith in the same city',()=>{const r=free(),slot=r.giveEquipment('EQ_ARMOR_TRAVEL_COAT');r.s.global.MORA=1000;r.giveItem('ORE_IRON',3);enter(r,'SERVICE_MOND_COOK','CRAFT');rejected(r,'ENHANCE',{slot});enter(r,'MRC_MOND_EQUIP','CRAFT');r.action('ENHANCE',{slot});assert.equal(r.s.inventory.find(x=>x.slot===slot).enhance,3);});
test('craft begun before closing completes once, then expires closed visit',()=>{const r=free('MAP_MOND_CITY','21:50');fundRecipe(r,'REC_ARMOR_TRAVEL');enter(r,'MRC_MOND_EQUIP','CRAFT');r.action('CRAFT',{recipe:'REC_ARMOR_TRAVEL'});assert.equal(r.s.global.WORLD_TIME,'22:20');assert.equal(r.s.placeVisit,null);assert.equal(r.s.global.SCREEN_MODE,'LOCATION');assert.ok(r.s.inventory.some(x=>x.equip==='EQ_ARMOR_TRAVEL_COAT'));});
test('joint facility recipes cannot finish before explicit preparation at both facilities',()=>{const r=free(),ids=['REC_CATALYST_MAPPA','REC_CATALYST_AMBER'];for(const facility of ['MRC_BLACKSMITH_COMMON','MRC_ALCHEMY_COMMON']){enter(r,facility,'CRAFT');for(const recipe of ids){assert.match(r.actionReason('CRAFT',{recipe}),/준비/);rejected(r,'CRAFT',{recipe});}}});
test('same merchant in another city cannot bypass recipe-specific location',()=>{const r=free('MAP_LIYUE_HARBOR');enter(r,'MRC_BLACKSMITH_COMMON','CRAFT');rejected(r,'CRAFT',{recipe:'REC_ARMOR_TRAVEL'});assert.match(r.actionReason('CRAFT',{recipe:'REC_ARMOR_TRAVEL'}),/장소/);});
test('malformed or cross-save entrance cannot be imported',()=>{const r=free();enter(r,'MRC_MOND_GENERAL');for(const patch of [{merchant:'MRC_MOND_EQUIP'},{map:'MAP_LIYUE_HARBOR'},{saveId:'someone-else'},{entity:'NPC_MOND_WAGNER'},{mode:'BOSS'}]){const s=JSON.parse(r.serialize());Object.assign(s.placeVisit,patch);assert.throws(()=>new Runtime(db,s),{code:'PLACE_SAVE'});}});
test('old saves with no entrance remain loadable but get no implicit service permission',()=>{const r=free();r.s.global.SCREEN_MODE='SHOP';const loaded=new Runtime(db,JSON.parse(r.serialize()));assert.equal(loaded.currentPlace(),null);rejected(loaded,'BUY',{stock:'STK_MOND_FOOD_001'});loaded.action('MENU',{screen:'LOCATION'});enter(loaded,'MRC_MOND_GENERAL');});
test('closed imported visits lose entrance without discarding the whole save',()=>{const r=free();enter(r,'MRC_MOND_EQUIP');const s=JSON.parse(r.serialize());s.global.WORLD_TIME='23:00';const loaded=new Runtime(db,s);assert.equal(loaded.currentPlace(),null);assert.equal(loaded.s.global.SCREEN_MODE,'LOCATION');});
test('boss routes are current-map-only and require explicit entrance',()=>{const r=free();rejected(r,'PLACE_ENTER',{place:'BOSS:BRT_ANDRIUS'});rejected(r,'BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});const arena=free('MAP_WOLF_ARENA');assert.equal(arena.placeBossEntries()[0].route,'BRT_ANDRIUS');rejected(arena,'BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});enter(arena,'BOSS:BRT_ANDRIUS','BOSS');rejected(arena,'BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});arena.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});assert.equal(arena.s.runtime.origin,'BOSS:BRT_ANDRIUS');assert.equal(arena.s.global.CURRENT_MAP_ID,'MAP_WOLF_ARENA');});
test('unsupported boss declarations are displayed as unavailable without invented combat or travel',()=>{const r=free('MAP_AZHDAHA_DOMAIN'),e=r.placeBossEntries()[0];assert.equal(e.name,r.row('35_BOSS_ROUTE_DB','BRT_AZHDAHA')[1]);assert.ok(e.reason);rejected(r,'PLACE_ENTER',{place:e.id});assert.equal(r.s.global.CURRENT_MAP_ID,'MAP_AZHDAHA_DOMAIN');});
test('boss continuation also requires matching local entrance',()=>{const r=free('MAP_WOLF_ARENA');r.s.bossRouteProgress={route:'BRT_ANDRIUS',step:2,phase:'RETRY',entry:'DIRECT',placeEntrySchema:1};rejected(r,'BOSS_CONTINUE');enter(r,'BOSS:BRT_ANDRIUS','BOSS');r.action('BOSS_CONTINUE');assert.equal(r.s.runtime.origin,'BOSS:BRT_ANDRIUS');});
test('Dvalin has no standalone entrance or public replay from any map',()=>{const r=free('MAP_STORMTERROR_LAIR');assert.equal(r.placeBossEntries().length,0);assert.match(r.actionReason('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'}),/이야기 진행/);rejected(r,'BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});rejected(r,'PLACE_ENTER',{place:'BOSS:BRT_DVALIN'});});
test('authored traveler Dvalin combat still starts through its actual story gate',()=>{const r=free('MAP_STORMTERROR_LAIR');Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'TRV_M02_N371',STORY_CURSOR_NODE_ID:'TRV_M02_N371',SCREEN_MODE:'STORY'});r.prepareStory();r.action('STORY_NEXT',{node:'TRV_M02_N371'});assert.equal(r.playPhase(),'PREPARATION');r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});assert.equal(r.s.runtime.origin,'STORY:TRV_M02_N371');assert.equal(r.s.runtime.group,'EG_BOSS_DVALIN');});
test('completed challenge cannot restart even when authored repeat field is Y',()=>{const r=free('MAP_WOLF_ARENA');assert.equal(r.row('35_BOSS_ROUTE_DB','BRT_ANDRIUS')[14],'Y');r.s.flags.FLAG_BOSS_ANDRIUS_CLEAR=true;assert.match(r.placeBossEntries()[0].reason,/이미 완료/);rejected(r,'PLACE_ENTER',{place:'BOSS:BRT_ANDRIUS'});rejected(r,'BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});});
test('legacy in-progress boss saves may continue locally, including Dvalin, without opening a replay catalog',()=>{for(const route of ['BRT_DVALIN','BRT_ANDRIUS']){const r=free(route==='BRT_DVALIN'?'MAP_STORMTERROR_LAIR':'MAP_WOLF_ARENA'),row=r.row('35_BOSS_ROUTE_DB',route),step=r.bossSteps(route).at(-1);r.s.bossRouteProgress={route,step:step[2],phase:'RETRY',entry:'DIRECT'};r.s.flags[row[13]]=true;const restored=new Runtime(db,JSON.parse(r.serialize()));assert.equal(restored.placeBossContinuation().reason,'');restored.action('BOSS_CONTINUE');assert.equal(restored.s.runtime.origin,'BOSS:'+route);rejected(restored,'BOSS_ROUTE',{route,entry:'DIRECT'});}});
test('legacy continuation never teleports from another map',()=>{const r=free();r.s.bossRouteProgress={route:'BRT_DVALIN',step:3,phase:'RETRY',entry:'DIRECT'};assert.ok(r.placeBossContinuation().reason);rejected(r,'BOSS_CONTINUE');assert.equal(r.s.global.CURRENT_MAP_ID,'MAP_MOND_CITY');});
test('duplicate entrance and purchase receipts stay idempotent',()=>{const r=free(),g=r.s.global,a={id:g.SAVE_ID+':1',revision:0,type:'PLACE_ENTER',place:'EVT_SCHEDULE_MRC_MOND_GENERAL',mode:'SHOP'},x=r.transact(a),before=r.serialize();assert.deepEqual(copy(r.transact(a)),copy(x));assert.equal(r.serialize(),before);const buy={id:g.SAVE_ID+':2',revision:1,type:'BUY',stock:'STK_MOND_FOOD_001'},receipt=r.transact(buy),after=r.serialize();assert.deepEqual(copy(r.transact(buy)),copy(receipt));assert.equal(r.serialize(),after);assert.equal(r.itemCount('ING_MILK'),1);});
test('actual isekai tutorial still performs its exact authored starter purchase',()=>{const r=fresh('ROUTE_ISEKAI');let steps=0;while(r.playPhase()!=='FREE'&&steps++<400){const choices=r.storyChoices();if(choices.length)r.action('STORY_CHOICE',{node:choices[0][4]});else{const n=r.storyNode();r.action(n[5]==='INPUT_TEXT'?'STORY_NAME':'STORY_NEXT',n[5]==='INPUT_TEXT'?{name:r.s.global.PLAYER_NAME}:{node:n[4]});}}assert.ok(steps<400);assert.equal(r.s.flags.FLAG_ISK_STARTER_KIT_BOUGHT,true);assert.equal(r.s.flags.FLAG_ISK_MON_PROLOGUE_CLEAR,true);assert.equal(r.currentPlace(),null);rejected(r,'BUY',{stock:'STK_CRPG_MOND_WORN_SWORD'});return{steps,mora:r.s.global.MORA,node:r.storyActiveNodeId()};});
const summary={source,dbPath,loaded:files,hashes,total:results.length,passed:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length,results};fs.writeFileSync(path.join(__dirname,'../reports/place-tests.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify({total:summary.total,passed:summary.passed,failed:summary.failed}));process.exitCode=summary.failed?1:0;
