'use strict';
const assert=require('node:assert/strict'),h=require('./helpers_v011.cjs'),{fresh,R,db,c,advance}=h;
const copy=x=>JSON.parse(JSON.stringify(x)),passed=[];
function test(name,fn){fn();passed.push(name);console.log('PASS '+name)}
function rejected(r,type,args){const before=JSON.stringify(r.s);assert.throws(()=>r.action(type,args));assert.equal(JSON.stringify(r.s),before)}
function smith(r){r.action('PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP'})}
test('expanded stock is usable at level one, comparisons are pure, sales preserve exact equipment instances',()=>{const r=fresh();smith(r);assert.ok(r.placeStocks().filter(s=>s.row[2]==='EQUIP'&&!s.reason).length>=15);const before=JSON.stringify(r.s),preview=r.shopEquipmentPreview('EQ_CRPG_WORN_SWORD');assert.ok(preview.after.atk>preview.before.atk);assert.equal(JSON.stringify(r.s),before);r.action('BUY',{stock:'STK_CRPG_MOND_WORN_SWORD',quantity:2});const items=r.s.inventory.filter(i=>i.equip==='EQ_CRPG_WORN_SWORD');r.action('EQUIP',{slot:items[0].slot});rejected(r,'SELL',{slot:items[0].slot,quantity:1});const mora=r.s.global.MORA;r.action('SELL',{slot:items[1].slot,quantity:1});assert.equal(r.s.global.MORA,mora+10);assert.ok(r.s.inventory.some(i=>i.slot===items[0].slot));assert.ok(!r.s.inventory.some(i=>i.slot===items[1].slot));rejected(r,'SELL',{slot:items[1].slot,quantity:1});});
test('item sales validate quantity, protected items, merchant presence and save roundtrip',()=>{const r=fresh();r.giveItem('ORE_IRON',8);r.giveItem('KEY_CRPG_ANEMOCULUS',1);r.s.global.LAST_COMMITTED_ACTION_SEQ=1;r.s.exploration.visitedMaps.MAP_MOND_PLAINS=true;r.s.exploration.oculi.ANEMO_PLAINS_CART={map:'MAP_MOND_PLAINS',day:1,action:r.s.global.SAVE_ID+':1'};rejected(r,'SELL',{item:'ORE_IRON',quantity:1});smith(r);for(const quantity of [0,-1,1.5,9])rejected(r,'SELL',{item:'ORE_IRON',quantity});rejected(r,'SELL',{item:'KEY_CRPG_ANEMOCULUS',quantity:1});const p=r.saleUnitPrice({item:'ORE_IRON'}),before=r.s.global.MORA;r.action('SELL',{item:'ORE_IRON',quantity:3});assert.equal(r.itemCount('ORE_IRON'),5);assert.equal(r.s.global.MORA,before+3*p);const loaded=new R(db,JSON.parse(r.serialize()));assert.equal(loaded.itemCount('ORE_IRON'),5);assert.equal(loaded.s.global.MORA,r.s.global.MORA);});
test('new map edges and staged content do not silently unlock new story regions',()=>{const r=fresh();for(const m of c.CRPGWorldContent.newMaps){assert.ok(r.tables['32_MAP_DB'].has(m.id));assert.ok(r.rows('47_MAP_EDGE_DB').some(e=>e[1]===m.id));}assert.ok(r.storyChapterEntries().every(e=>!String(e.id).includes('_L0')));});
test('timed oculus grants once and earlier locations retain completed receipts',()=>{const point=c.CRPGWorldContent.oculi[0],r=fresh(point.map);for(const step of point.steps){r.action('WORLD_WORK_START',{kind:'OCULUS',point:point.id});rejected(r,'WORLD_WORK_FINISH',{job:r.s.worldJob.id});advance(step.duration);r.action('WORLD_WORK_FINISH',{job:r.s.worldJob.id});}assert.equal(r.itemCount('KEY_CRPG_ANEMOCULUS'),1);const loaded=new R(db,JSON.parse(r.serialize()));assert.ok(!loaded.oculusEntries().some(p=>p.id===point.id));rejected(loaded,'WORLD_WORK_START',{kind:'OCULUS',point:point.id});});
test('three-stage letter work consumes time and reports to guild exactly once',()=>{const r=fresh(),q=c.CRPGWorldContent.letterCommission.quest,guild='EVT_SCHEDULE_NPC_MOND_KATHERYNE';r.action('PLACE_ENTER',{place:guild});r.action('COMMISSION_ACCEPT',{quest:q});r.action('PLACE_LEAVE');for(const stage of c.CRPGWorldContent.letterCommission.newStages){if(stage.requiresPlace)r.action('PLACE_ENTER',{place:guild});r.action('WORLD_WORK_START',{kind:'COMMISSION',quest:q});if(stage.duration){assert.ok(r.s.worldJob);rejected(r,'MOVE',{edge:'invalid'});const loaded=new R(db,JSON.parse(r.serialize()));assert.equal(loaded.s.worldJob.id,r.s.worldJob.id);advance(stage.duration);r.action('WORLD_WORK_FINISH',{job:r.s.worldJob.id});}}assert.equal(r.s.quests[q].node,'READY_TO_CLAIM');r.action('CLAIM_QUEST',{quest:q});rejected(r,'CLAIM_QUEST',{quest:q});});
test('story pauses preserve the cursor through training and exact save reload',()=>{const r=fresh();Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'TRV_M02_N169',STORY_CURSOR_NODE_ID:'TRV_M02_N169',STORY_WAITING:false,SCREEN_MODE:'STORY'});r.prepareStory();r.action('STORY_NEXT',{node:'TRV_M02_N169'});assert.ok(r.s.storyBreak);r.action('PLACE_ENTER',{place:'EVT_SCHEDULE_NPC_MOND_KATHERYNE'});r.action('WORLD_WORK_START',{kind:'TRAIN'});const loaded=new R(db,JSON.parse(r.serialize()));assert.ok(loaded.s.storyBreak);advance(10000);loaded.action('WORLD_WORK_FINISH',{job:loaded.s.worldJob.id});loaded.action('PLACE_LEAVE');loaded.action('JOURNEY_RESUME');assert.ok(!loaded.s.storyBreak);});
test('every inserted temple node is linked and opens a real preparation gate',()=>{for(const x of c.CRPGWorldContent.journey.combatInsertions){const r=fresh(x.node.MAP_ID,'ROUTE_ISEKAI');Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:x.node.NODE_ID,STORY_CURSOR_NODE_ID:x.node.NODE_ID,STORY_WAITING:false,SCREEN_MODE:'STORY'});const row=r.storyIndex().nodes.get('ROUTE_ISEKAI:'+x.afterNode);assert.equal(row[13],x.node.NODE_ID);r.prepareStory();if(!r.s.battlePreparation)r.action('STORY_NEXT',{node:x.node.NODE_ID});assert.ok(r.s.battlePreparation||r.s.runtime);}});
test('permanent ownership is required for combat; field pressure does not change HP or repeat on load',()=>{const r=fresh('MAP_MOND_PLAINS');const entry=r.rows('33_ENCOUNTER_GROUP_DB').find(g=>g[0]==='EG_MOND_SLIME_SMALL');assert.ok(entry);const a=fresh('MAP_MOND_PLAINS'),baseCtx=h.vm.createContext({console});for(const [,f]of h.fs.readFileSync(h.path.join(h.root,'source/index.html'),'utf8').matchAll(/<script src="((?:world_content|runtime[^" ]*)\.js)"/g))if(!['runtime_journey.js','runtime_market.js','runtime_geography.js','runtime_encounter.js'].includes(f))h.vm.runInContext(h.fs.readFileSync(h.path.join(h.root,'source',f),'utf8'),baseCtx);const b=new baseCtx.CRPGRuntime.Runtime(db,copy(a.s));a.startBattle(entry[0],'RANDOM');b.startBattle(entry[0],'RANDOM');const enemies=a.s.runtime.actors.filter(a=>a.side==='ENEMY'),base=b.s.runtime.actors.filter(a=>a.side==='ENEMY');assert.ok(a.s.runtime.fieldPressure);enemies.forEach((e,i)=>{assert.equal(e.maxHp,base[i].maxHp);assert.equal(e.atk,Math.round(base[i].atk*1.35));});const raw=JSON.parse(a.serialize()),loaded=new R(db,raw);assert.deepEqual(copy(loaded.s.runtime.actors),copy(a.s.runtime.actors));});
h.fs.writeFileSync(h.path.join(h.root,'reports/release-v011-tests.json'),JSON.stringify({passed:passed.length,tests:passed},null,2));
