/* Production-code runtime + DOM fixture checks. No browser, external service, or persisted player save. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(process.env.CRPG_GAME||path.join(__dirname,'..')),sourceDir=process.env.CRPG_SOURCE||path.join(root,'source');
const db=JSON.parse(fs.readFileSync(process.env.CRPG_DB||path.join(root,'content/db.json'))),source=name=>fs.readFileSync(path.join(sourceDir,name),'utf8');
const runtimeFiles=[...source('index.html').matchAll(/<script\s+src="(runtime[^/]*\.js)(?:\?[^\"]*)?"/g)].map(m=>m[1]);const ctx=vm.createContext({console});for(const filename of runtimeFiles)vm.runInContext(source(filename),ctx,{filename});
ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});
const Runtime=ctx.CRPGRuntime.Runtime,presenter=require(path.join(sourceDir,'inventory_presenter.js')).create(db);let seq=0;const results=[];
function test(name,fn){try{results.push({name,ok:true,evidence:fn()||null});}catch(e){results.push({name,ok:false,error:e.stack});console.error(name,e.stack);}}
function fresh(map='MAP_MOND_CITY',level=1){const r=new Runtime(db);r.newGame({name:'상점검증',route:'ROUTE_TRAVELER',seed:321,saveId:'SHOP09-'+(++seq)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,WORLD_TIME:'08:00',STORY_MENU_POLICY:'',MORA:999999});r.prepareStory();while(r.s.global.PLAYER_LEVEL_STATE<level)r.addXp('PLAYER_CUSTOM',Number(r.row('26_LEVEL_RULES',r.s.global.PLAYER_LEVEL_STATE)[2]));return r;}
function enter(r,merchant,mode='SHOP'){const e=r.placeEntries().find(e=>e.merchant===merchant);assert.ok(e,merchant);r.action('PLACE_ENTER',{place:e.id,mode});return e;}
function reject(r,type,args,pattern){const before=JSON.stringify(r.s);assert.throws(()=>r.action(type,args),pattern);assert.equal(JSON.stringify(r.s),before);}
test('Mondstadt has one entered smith with all 15 canonical stock IDs; other cities retain common smith',()=>{const r=fresh(),entries=r.placeEntries();assert.equal(entries.filter(e=>r.placeCanEnhance(e)).length,1);enter(r,'MRC_MOND_EQUIP');const stocks=r.placeStocks();assert.equal(stocks.length,15);assert.ok(stocks.find(s=>s.row[0]==='STK_SMITH_002'));assert.ok(stocks.find(s=>s.row[0]==='STK_CRPG_MOND_WORN_SWORD'));assert.equal(fresh('MAP_LIYUE_HARBOR').placeEntries().filter(e=>e.merchant==='MRC_BLACKSMITH_COMMON').length,1);return stocks.map(s=>s.row[0]);});
test('hidden generic Mond entrance rejects direct action without mutation',()=>reject(fresh(),'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_BLACKSMITH_COMMON'},/바그너/));
test('Wagner merged ore uses original receipt, level, affordability, quantity and stock rules',()=>{const r=fresh();enter(r,'MRC_MOND_EQUIP');const id='STK_SMITH_002',row=r.row('19_SHOP_STOCK_DB',id),before=r.s.global.MORA;const receipt=r.action('BUY',{stock:id,quantity:3});assert.equal(receipt.result.cost,225);assert.equal(r.itemCount('ORE_WHITE_IRON'),3);assert.equal(r.s.global.MORA,before-225);assert.equal(r.stockRemaining(row),3);assert.equal(JSON.parse(r.s.global.SHOP_STOCK_USAGE_STATE)[id+'|'+r.period(row)],3);reject(r,'BUY',{stock:id,quantity:4},/재고/);for(const quantity of [0,-1,1.5])reject(r,'BUY',{stock:id,quantity},/수량/);r.s.global.MORA=10;reject(r,'BUY',{stock:id,quantity:1},/모라/);reject(r,'BUY',{stock:'STK_SMITH_003',quantity:1},/레벨/);});
test('merged stock authorization never leaks into other shops, CRAFT, or after leaving',()=>{const r=fresh();enter(r,'MRC_MOND_GENERAL');reject(r,'BUY',{stock:'STK_SMITH_002',quantity:1},/현재 들어온 상점/);enter(r,'MRC_MOND_EQUIP','CRAFT');reject(r,'BUY',{stock:'STK_SMITH_002',quantity:1},/서비스/);r.action('PLACE_LEAVE');reject(r,'BUY',{stock:'STK_SMITH_002',quantity:1});});
test('Wagner keeps 06:00–22:00 hours even for merged ore',()=>{for(const time of ['05:59','22:00']){const r=fresh();r.s.global.WORLD_TIME=time;reject(r,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP'},/닫았습니다/);}for(const time of ['06:00','21:59']){const r=fresh();r.s.global.WORLD_TIME=time;enter(r,'MRC_MOND_EQUIP');assert.equal(r.stockReason(r.row('19_SHOP_STOCK_DB','STK_SMITH_002')),'');}});
test('bulk equipment makes separate instances and exact charge',()=>{const r=fresh();enter(r,'MRC_MOND_EQUIP');const before=r.s.inventory.length,money=r.s.global.MORA;r.action('BUY',{stock:'STK_CRPG_MOND_WORN_SWORD',quantity:2});assert.equal(r.s.inventory.length,before+2);const gear=r.s.inventory.filter(x=>x.equip==='EQ_CRPG_WORN_SWORD');assert.equal(gear.length,2);assert.notEqual(gear[0].slot,gear[1].slot);assert.equal(r.s.global.MORA,money-160);});
test('Wagner inherits exact common recipe facilities and joint stages without bypassing unlocks',()=>{const r=fresh();enter(r,'MRC_MOND_EQUIP','CRAFT');const recipes=r.placeRecipes();for(const id of ['REC_SWORD_RANCOUR','REC_ARMOR_IRON','REC_SPECIAL_GRAPPLE','REC_CATALYST_MAPPA'])assert.ok(recipes.some(x=>x.row[0]===id),id);const joint=r.jointCraftStatus('REC_CATALYST_MAPPA');assert.deepEqual(Array.from(joint.stages[0].facilities,f=>f.id),['EVT_SCHEDULE_MRC_MOND_EQUIP']);r.action('CRAFT_STAGE',{recipe:'REC_CATALYST_MAPPA'});enter(r,'MRC_ALCHEMY_COMMON','CRAFT');r.action('CRAFT_STAGE',{recipe:'REC_CATALYST_MAPPA'});assert.equal(r.jointCraftStatus('REC_CATALYST_MAPPA').ready,true);assert.ok(r.craftReason(r.recipeDefinition('REC_CATALYST_MAPPA')));});
test('old smith visits migrate while legacy joint preparation remains loadable',()=>{const r=fresh();enter(r,'MRC_MOND_EQUIP','CRAFT');r.action('CRAFT_STAGE',{recipe:'REC_CATALYST_MAPPA'});const s=JSON.parse(r.serialize());Object.assign(s.placeVisit,{place:'EVT_SCHEDULE_MRC_BLACKSMITH_COMMON',merchant:'MRC_BLACKSMITH_COMMON',entity:'SERVICE_BLACKSMITH_COMMON'});s.craftPreparations.REC_CATALYST_MAPPA.stages[0].place='EVT_SCHEDULE_MRC_BLACKSMITH_COMMON';const restored=new Runtime(db,s);assert.equal(restored.currentPlace().merchant,'MRC_MOND_EQUIP');assert.equal(restored.jointCraftStatus('REC_CATALYST_MAPPA').stages[0].prepared,true);const closed=JSON.parse(JSON.stringify(s));closed.global.WORLD_TIME='23:00';const later=new Runtime(db,closed);assert.equal(later.currentPlace(),null);assert.equal(later.s.global.SCREEN_MODE,'LOCATION');});
test('Sara is a food-only restaurant with valid named items, existing prices and matching hours',()=>{const r=fresh(),e=enter(r,'MRC_MOND_RESTAURANT');assert.equal(e.entity,'NPC_MOND_SARA');assert.match(e.name,/식당/);assert.deepEqual(Array.from(e.modes),['SHOP']);const stocks=r.placeStocks();assert.equal(stocks.length,3);for(const {row}of stocks){const item=r.row('14_ITEM_DB',row[3]);assert.equal(item[2],'음식');assert.equal(row[4],item[1]);assert.equal(row[5],item[15]);r.action('BUY',{stock:row[0],quantity:2});assert.equal(r.itemCount(row[3]),2);}assert.ok(r.placeEntries().find(e=>e.id==='EVT_SCHEDULE_SERVICE_MOND_COOK'));return stocks.map(s=>s.row.slice(0,7));});
test('legacy Sara TALK visit migrates to the same restaurant safely',()=>{const r=fresh();enter(r,'MRC_MOND_RESTAURANT');const s=JSON.parse(r.serialize());Object.assign(s.placeVisit,{mode:'TALK',merchant:null});s.global.SCREEN_MODE='DIALOGUE';const restored=new Runtime(db,s);assert.equal(restored.currentPlace().valid,true);assert.equal(restored.currentPlace().merchant,'MRC_MOND_RESTAURANT');assert.equal(restored.s.global.SCREEN_MODE,'SHOP');});
test('all four quest items expose exact existing quest titles without altering names',()=>{for(const row of db['14_ITEM_DB'].slice(1).filter(r=>r[19]==='Y')){const d=presenter.itemDetail({item:row[0],quantity:1});assert.equal(d.name,row[1]);assert.ok(d.relatedQuests.length,row[0]);assert.equal(d.fields.find(f=>f.label==='관련 임무').value,d.questLabel);for(const q of d.relatedQuests)assert.equal(db['22_QUEST_DB'].find(r=>r[0]===q.id)[1],q.name);}return presenter.itemDetail({item:'KEY_ISK_MYSTERY_ORB',quantity:1}).questLabel;});
// Minimal DOM fixture executes production shop handlers without a browser or network.
class Node{constructor(tag,cls='',text=''){this.tag=tag;this.className=cls;this.textContent=text;this.children=[];this.dataset={};this.disabled=false;this.classList={toggle(){}};}append(...n){this.children.push(...n);}setAttribute(k,v){this[k]=v;}focus(){}close(){this.open=false;}get text(){return this.textContent+this.children.map(c=>c.text||'').join(' ');}}
let r=fresh(),modal,modalTitle,notices=[],actions=[];const ui={console,game:r,itemPresenter:presenter,presenterDB:r.db,busy:false,lastResult:null,el:(...a)=>new Node(...a),button:(label,fn,disabled=false)=>Object.assign(new Node('button','',label),{onclick:fn,disabled}),showModal:(title,box)=>{modalTitle=title;modal=box;},document:{getElementById:()=>({close(){}})},placeHeader:()=>r.currentPlace().entry,isInn:()=>false,contactStories:()=>{},discoveryCards:()=>{},render:()=>{},ownerName:id=>id};ui.actionButton=(label,type,args)=>ui.button(label,()=>ui.act(type,args),!!r.actionReason(type,args));ui.act=(type,args)=>{actions.push({type,args});ui.lastResult=r.action(type,args);return ui.lastResult;};const uiCtx=vm.createContext(ui),experience=source('app_experience.js');vm.runInContext(experience.slice(experience.indexOf('function shopStockDetail'),experience.indexOf('function costBlock')),uiCtx);const adventure=source('app_adventure.js');vm.runInContext(adventure.slice(adventure.indexOf('function receivedLoot'),adventure.indexOf('async function playTravel')),uiCtx);uiCtx.itemGlyph=()=>new Node('span');uiCtx.itemSummary=()=>'';uiCtx.safeName=()=>'';vm.runInContext(source('app_market.js'),uiCtx,{filename:'app_market.js'});
function walk(n){return [n,...n.children.flatMap(walk)];}
test('shop renders separately named one/bulk actions, stats and meaningful groups',()=>{r=fresh();uiCtx.game=r;uiCtx.itemPresenter=require(path.join(sourceDir,'inventory_presenter.js')).create(r.db);uiCtx.presenterDB=r.db;enter(r,'MRC_MOND_EQUIP');const p=new Node('main');uiCtx.shop(p);const text=p.text;for(const value of ['기본 무기','한손검','양손검','장병기','활','법구','방어구','장신구','특수','제작 재료','공격력','구매 Lv. 3 이상','장착 Lv. 1 이상'])assert.ok(text.includes(value),value);const stock=walk(p).find(n=>n.dataset.stockId==='STK_CRPG_MOND_WORN_SWORD');assert.deepEqual(walk(stock).filter(n=>n.tag==='button').map(n=>n.textContent),['1개 구매','여러 개 구매']);});
test('bulk dialog validates total, available funds, stock and selected quantity',()=>{r=fresh();uiCtx.game=r;enter(r,'MRC_MOND_RESTAURANT');r.s.global.MORA=200;uiCtx.showPurchaseQuantity('STK_MOND_SARA_EGG');assert.match(modalTitle,/여러 개 구매/);const input=walk(modal).find(n=>n.tag==='input'),confirm=walk(modal).find(n=>n.tag==='button');assert.equal(input.max,'3');assert.match(modal.text,/총 금액 · 120 모라/);input.value='4';input.oninput();assert.equal(confirm.disabled,true);assert.match(modal.text,/모라가 부족/);input.value='1.5';input.oninput();assert.equal(confirm.disabled,true);input.value='3';input.oninput();assert.equal(confirm.disabled,false);confirm.onclick();assert.deepEqual(JSON.parse(JSON.stringify(actions.at(-1).args)),{stock:'STK_MOND_SARA_EGG',quantity:3});assert.equal(r.s.global.MORA,20);});
test('successful BUY yields named quantity/cost receipt and modal; nonpurchase actions do not',()=>{r=fresh();uiCtx.game=r;enter(r,'MRC_MOND_RESTAURANT');const before={inventory:JSON.parse(JSON.stringify(r.s.inventory)),mora:r.s.global.MORA,level:r.growth(),relations:Object.fromEntries(Object.entries(r.s.relations).map(([id,x])=>[id,x.BOND_SCORE??x.heart*20])),completed:[]};uiCtx.lastResult=r.action('BUY',{stock:'STK_MOND_SARA_EGG',quantity:2});const loot=uiCtx.receivedLoot(before,'BUY');assert.equal(loot.title,'구매 완료');assert.equal(loot.purchase.cost,120);uiCtx.showReceivedLoot(loot);assert.match(modal.text,/티바트 달걀 프라이 2개 구매 완료 · 120 모라 사용/);assert.equal(uiCtx.receivedLoot(before,'MENU'),null);});
const report={total:results.length,passed:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length,results};fs.writeFileSync(process.env.CRPG_REPORT||path.resolve(__dirname,'../reports/shops-v09.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({total:report.total,passed:report.passed,failed:report.failed}));process.exitCode=report.failed?1:0;
