'use strict';
const assert=require('node:assert/strict');
const {fresh,R,db,c,advance,fs,root}=require('./helpers_v011.cjs');
const api=c.CRPGRuntime,cp=x=>JSON.parse(JSON.stringify(x)),checks=[];
function check(name,fn){try{const evidence=fn();checks.push({name,ok:true,evidence});console.log('PASS '+name);}catch(e){checks.push({name,ok:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);process.exitCode=1;}}
function restore(r){return new R(db,cp(r.s));}
function rejected(r,type,args){const s=r.serialize();assert.throws(()=>r.action(type,args));assert.equal(r.serialize(),s);}
function once(r,type,args={}){const g=r.s.global,a={id:g.SAVE_ID+':'+(g.LAST_COMMITTED_ACTION_SEQ+1),revision:g.SAVE_REVISION,type,...args};const result=r.transact(a),s=r.serialize();assert.deepEqual(cp(r.transact(a)),cp(result));assert.equal(r.serialize(),s);return result;}
function gates(r){for(const k of ['FLAG_TRV_MON_CH1_CLEAR','FLAG_TRV_MON_CH2_CLEAR','FLAG_ISK_M03_CLEAR','FLAG_ISK_M05_CLEAR'])r.s.flags[k]=true;for(const kind of ['TRV','ISK'])for(const region of ['MOND','LIYUE'])for(let n=1;n<=3;n++){const id='Q_'+kind+'_'+region+'_0'+n;if(r.tables['22_QUEST_DB'].has(id))r.questState(id).claimed=true;};}
function payReady(r,cost){r.s.global.MORA=Math.max(r.s.global.MORA,cost.mora);for(const [id,n]of Object.entries(cost.items))r.giveItem(id,n);}
check('both untouched prologues first teach the route to the actual story destination',()=>{for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI']){const r=new R(db);r.newGame({route,name:'첫걸음',seed:27});for(let i=0;i<100&&!r.s.storyJourney;i++){assert(!r.s.runtime&&!r.s.battlePreparation,'movement is introduced before the first combat');const n=r.storyNode(),cs=r.storyChoices();if(cs.length)r.action('STORY_CHOICE',{node:cs[0][4]});else{assert(n);r.action(n[5]==='INPUT_TEXT'?'STORY_NAME':'STORY_NEXT',n[5]==='INPUT_TEXT'?{name:'첫걸음'}:{node:n[4]});}}assert(r.s.storyJourney);const d=r.tutorialDirective();assert.equal(d.id,'move');assert.equal(d.destination,r.s.storyJourney.target);assert(!r.tutorialState().done.move);const edge=r.navigationRoute(d.destination).edges[0];r.s.global.ENCOUNTER_COOLDOWN=100;r.action('MOVE',{edge:edge[0]});assert(r.tutorialState().done.move);assert.equal(r.s.global.CURRENT_MAP_ID,d.destination);assert.equal(r.tutorialDirective().command,'resume');}});
check('movement comes before facilities, wishes or fighting, and only an arrival advances it',()=>{for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI']){let r=fresh('MAP_MOND_CITY',route);assert.equal(r.tutorialDirective().id,'move');once(r,'MENU',{screen:'LOCATION'});assert.equal(r.tutorialDirective().id,'move');r.s.global.ENCOUNTER_COOLDOWN=2;const e=r.view().edges.find(e=>e.row[2]==='MAP_MOND_PLAINS'&&!e.reason);once(r,'MOVE',{edge:e.row[0]});assert.equal(r.tutorialState().done.move,true);r=restore(r);assert.equal(r.tutorialDirective().id,'firstTown');assert(!r.tutorialState().done.facility);}});
check('regional enemy stats and bodies are fixed across levels and one to four allies',()=>{const seen=[];for(const level of [1,30,60])for(const n of [1,4]){const r=fresh('MAP_MOND_PLAINS');r.adminApply({op:'level',target:'ALL',value:level});if(n===4)for(const [i,id]of ['MOND_AMBER','MOND_KAEYA','MOND_NOELLE'].entries()){r.adminApply({op:'recruit',char:id});r.action('PARTY',{char:id,slot:i+2});}Object.assign(r.s.global,{SAVE_ID:'FIXED-BALANCE',LAST_COMMITTED_ACTION_SEQ:0,PRNG_STATE:714});r.startBattle('EG_MOND_HILI_PATROL','RANDOM');seen.push(cp(r.s.runtime.actors.filter(a=>a.side==='ENEMY').map(a=>[a.source,a.level,a.hp,a.atk,a.def])));}for(const a of seen)assert.deepEqual(a,seen[0]);assert(seen[0].every(a=>a[1]===2));return seen[0];});
check('books work for an owned bench companion and stop at each cap with no extra consumption',()=>{let r=fresh();r.wishGrant({kind:'char',id:'MOND_AMBER',rarity:4});r.giveItem('MAT_CHAR_EXP_HERO',100);once(r,'USE_ITEM',{item:'MAT_CHAR_EXP_HERO',quantity:2,owner:'MOND_AMBER'});assert(r.s.chars.MOND_AMBER.level>1);assert(!r.s.party.some(x=>x.active&&x.source==='MOND_AMBER'));r.addXp('MOND_AMBER',10000000);assert.equal(r.growth('MOND_AMBER').level,10);assert.equal(r.growth('MOND_AMBER').next,0);rejected(r,'USE_ITEM',{item:'MAT_CHAR_EXP_HERO',quantity:1,owner:'MOND_AMBER'});rejected(r,'USE_ITEM',{item:'MAT_CHAR_EXP_HERO',quantity:1,owner:'MOND_LISA'});r=restore(r);assert.equal(r.growth('MOND_AMBER').cap,10);});
check('all six ascensions spend once, heal, open the correct cap and preserve progress after reload',()=>{let r=fresh();gates(r);const points=[];for(let phase=0;phase<6;phase++){r.addXp('PLAYER_CUSTOM',100000000);const d=r.ascensionInfo();assert.equal(d.level,api.growthV01522.caps[phase]);assert.equal(d.phase,phase);payReady(r,d.cost);const money=r.s.global.MORA,hp=r.s.global.PLAYER_HP_MAX;once(r,'CHAR_ASCEND',{owner:'PLAYER_CUSTOM'});assert.equal(r.s.global.MORA,money-d.cost.mora);assert(r.s.global.PLAYER_HP_MAX>hp);assert.equal(r.s.global.PLAYER_HP_CURRENT,r.s.global.PLAYER_HP_MAX);r=restore(r);points.push({level:r.growth().level,cap:r.growth().cap,hp:r.s.global.PLAYER_HP_MAX});}r.addXp('PLAYER_CUSTOM',100000000);assert.equal(r.growth().level,60);assert.equal(r.growth().next,0);rejected(r,'CHAR_ASCEND',{});return points;});
check('story locks and talent caps are authoritative; five-star growth costs more',()=>{let r=fresh();r.addXp('PLAYER_CUSTOM',1000000);payReady(r,r.ascensionInfo().cost);rejected(r,'CHAR_ASCEND',{});r.s.flags.FLAG_TRV_MON_CH1_CLEAR=true;once(r,'CHAR_ASCEND',{});payReady(r,r.talentUpgradeInfo('PLAYER_CUSTOM','na').cost);once(r,'TALENT_UPGRADE',{kind:'na'});assert.equal(r.talentLevels('PLAYER_CUSTOM').base.na,2);rejected(r,'TALENT_UPGRADE',{kind:'na'});rejected(r,'TALENT_UPGRADE',{kind:'unknown'});for(const id of ['MOND_AMBER','MOND_DILUC']){r.wishGrant({kind:'char',id,rarity:id==='MOND_DILUC'?5:4});r.addXp(id,1000000);}assert.equal(r.ascensionInfo('MOND_DILUC').cost.items.GROWTH_GEM_PYRO,r.ascensionInfo('MOND_AMBER').cost.items.GROWTH_GEM_PYRO*2);restore(r);});
check('legacy level-20 ownership migrates once without granting the new-game fates twice',()=>{const r=fresh();r.adminApply({op:'level',target:'ALL',value:20});r.adminApply({op:'recruit',char:'MOND_AMBER'});const s=cp(r.s);delete s.growthVersion;delete s.ascensions;delete s.rosterVersion;s.global.ACQUAINT_FATE=7;let x=new R(db,s);assert.equal(x.growth().cap,20);assert.equal(x.growth().phase,1);assert(x.premiumOwns('MOND_AMBER'));x=restore(x);assert.equal(x.s.global.ACQUAINT_FATE,7);const bad=cp(x.s);bad.ascensions.PLAYER_CUSTOM=6;assert.throws(()=>new R(db,bad));});
check('a story acquaintance stays unowned; the first wish joins at player level minus five; duplicates preserve level',()=>{const r=fresh();r.adminApply({op:'level',target:'ALL',value:30});r.unlockCharacter('MOND_AMBER');r.storySetCompanion('MOND_AMBER','JOINED');assert(!r.premiumOwns('MOND_AMBER'));rejected(r,'PARTY',{char:'MOND_AMBER',slot:2});const first=r.wishGrant({kind:'char',id:'MOND_AMBER',rarity:4});assert(first.joined&&!first.stella);assert.equal(r.s.chars.MOND_AMBER.level,25);const second=r.wishGrant({kind:'char',id:'MOND_AMBER',rarity:4});assert(second.stella);assert.equal(r.s.chars.MOND_AMBER.level,25);restore(r);});
check('each domain starts real enemies, reloads, grants the selected reward once, and consumes bonuses only on wins',()=>{let r=fresh();r.adminApply({op:'level',target:'ALL',value:10});for(const [index,kind]of ['EXP','ASCENSION','TALENT','GEAR'].entries()){r.s.global.SCREEN_MODE='LOCATION';once(r,'DOMAIN_START',{domain:kind+':5',element:'PYRO'});assert(r.s.runtime.actors.some(a=>a.side==='ENEMY'&&a.level===5));r=restore(r);const b=r.s.runtime;for(const a of b.actors.filter(x=>x.side==='ENEMY'))a.hp=0;const out=r.finishBattle(true);assert.equal(out.domain.bonus,index<3);assert(Object.values(out.domain.items).every(n=>n===(index<3?2:1)));const save=r.serialize();r.finishBattle(true);assert.equal(r.serialize(),save);r=restore(r);}assert.equal(r.s.domainDaily.wins,4);r.s.global.SCREEN_MODE='LOCATION';r.action('DOMAIN_START',{domain:'EXP:5'});r.finishBattle(false);assert.equal(r.s.domainDaily.wins,4);return cp(r.s.lastGrowthDomain);});
check('domain locality, stage, element and in-flight metadata cannot be forged',()=>{const r=fresh('MAP_MOND_PLAINS');rejected(r,'DOMAIN_START',{domain:'EXP:5'});r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';rejected(r,'DOMAIN_START',{domain:'EXP:60'});rejected(r,'DOMAIN_START',{domain:'ASCENSION:5',element:'FAKE'});r.action('DOMAIN_START',{domain:'ASCENSION:5',element:'HYDRO'});for(const patch of [{level:60},{region:'리월'},{map:'MAP_MOND_PLAINS'},{element:'FAKE'}]){const s=cp(r.s);Object.assign(s.runtime.growthDomain,patch);assert.throws(()=>new R(db,s));}});
check('gathering and mining replay timed inputs, reject forged logs atomically and grant one resource use',()=>{for(const [kind,map]of [['GATHER','MAP_MOND_PLAINS'],['MINE','MAP_CRPG_MOND_QUARRY']]){let r=fresh(map);r.action('LIFE_START',{kind});const job=cp(r.s.lifeJob),inputs=[0,1,2].map(round=>({round,at:1700+3000*round,choice:api.lifeMinigame.target(job.minigame.seed,round)}));r=restore(r);rejected(r,'LIFE_FINISH',{job:job.id,inputs,elapsed:job.duration});advance(job.duration);rejected(r,'LIFE_FINISH',{job:job.id,inputs:[inputs[0],inputs[0]],elapsed:job.duration});r.die=()=>100;once(r,'LIFE_FINISH',{job:job.id,inputs,elapsed:job.duration});assert.equal(r.s.lifeResources[map+':'+kind].used,1);assert(r.tutorialState().done[kind==='MINE'?'mine':'gather']);rejected(r,'LIFE_FINISH',{job:job.id,inputs,elapsed:job.duration});restore(r);}});
check('eight enemy slots refill from reserves without discarding rewards or allowing an early victory',()=>{let r=fresh('MAP_MOND_PLAINS');r.startBattle('EG_MOND_HILI_PATROL','RANDOM');let b=r.s.runtime;const base=b.actors.find(a=>a.side==='ENEMY');for(let n=0;n<10;n++)b.actors.push({...cp(base),id:'CAPACITY_'+n});r.limitBattleEnemies();assert.equal(b.actors.filter(a=>a.side==='ENEMY'&&a.hp>0).length,8);const count=b.actors.filter(a=>a.side==='ENEMY').length+b.enemyReserve.length;assert(b.enemyReserve.length>0);r=restore(r);b=r.s.runtime;assert.throws(()=>r.finishBattle(true),/증원/);const a=b.actors.find(a=>a.side==='ENEMY');a.hp=0;r.limitBattleEnemies();assert.equal(b.actors.filter(a=>a.side==='ENEMY'&&a.hp>0).length,8);while(b.enemyReserve.length){b.actors.filter(a=>a.side==='ENEMY').forEach(a=>a.hp=0);r.limitBattleEnemies();}b.actors.filter(a=>a.side==='ENEMY').forEach(a=>a.hp=0);const expected=r.mondRewardPlan(b).xp;assert.equal(b.actors.filter(a=>a.side==='ENEMY').length,count);assert.equal(r.finishBattle(true).xp,expected);});
check('a fourth summon replaces the oldest on each side, leaving three separate slots',()=>{const r=fresh('MAP_MOND_PLAINS');r.startBattle('EG_MOND_HILI_PATROL','RANDOM');const b=r.s.runtime;for(const side of ['ALLY','ENEMY']){const owner=b.actors.find(a=>a.side===side);for(const kind of ['BUNNY','OZ','GOU_BA','PHANTOM'])r.addField(kind,owner,3,{hp:100,maxHp:100});const fields=b.fields.filter(f=>f.side===side&&api.battleCapacity.fieldKinds.includes(f.kind)&&!f.done&&f.rounds>0);assert.equal(fields.length,3);assert(!fields.some(f=>f.kind==='BUNNY'));}restore(r);});
check('Bennett field heals below 70%, buffs above it, C1 removes the HP gate, and stun blocks action',()=>{const r=fresh('MAP_MOND_PLAINS');r.startBattle('EG_MOND_HILI_PATROL','RANDOM');const b=r.s.runtime,a=b.actors.find(a=>a.side==='ALLY'),e=b.actors.find(a=>a.side==='ENEMY');a.hp=a.maxHp;const atk=r.combatStat(a,'atk');const f=r.addField('ENCOURAGEMENT',a,2,{attack:100,sourceMaxHp:1000,c1:false});assert.equal(r.combatStat(a,'atk'),atk+40);a.hp=Math.floor(a.maxHp*.4);assert.equal(r.combatStat(a,'atk'),atk);const hp=a.hp;r.tickFields('END');assert.equal(a.hp,hp+60);f.c1=true;f.rounds=2;assert.equal(r.combatStat(a,'atk'),atk+60);r.addCombatStatus(e,'STATUS_STUN',1,{caster:a.id});assert.equal(b.log.at(-1).actorId,a.id);assert(r.combatActionLocked(e));assert(b.log.some(x=>x.targetId===e.id&&x.statusApplied?.id==='STATUS_STUN'));});
check('native Anemo swirls incoming elements without retaining them; Geo is not a reverse crystallize reagent',()=>{const r=fresh();r.startBattle('EG_FB_ANEMO_HYPOSTASIS','EXPLICIT');const a=r.s.runtime.actors.find(x=>x.source==='FB_ANEMO_HYPOSTASIS');assert.equal(r.reactionFor(a,'PYRO')[0],'RX_SWIRL');r.setAura(a,'불');assert.deepEqual(cp(r.auraList(a).map(x=>x.element)),['바람']);a.source='FB_GEO_HYPOSTASIS';r.setAura(a,'불');assert(r.auraList(a).some(x=>x.element==='바위'));assert(r.auraList(a).some(x=>x.element==='불'));assert(!r.reactionFor(a,'PYRO'));});
check('the combat lesson waits for the Traveler element and Bennett keeps base attack in a guest snapshot',()=>{const r=fresh();rejected(r,'TUTORIAL_DRILL',{});r.s.flags.FLAG_TRV_ANEMO_UNLOCKED=true;r.action('TUTORIAL_DRILL');assert.equal(r.s.runtime.tutorialDrill.step,'guard');r.finishBattle(false);const g=fresh();g.adminApply({op:'level',target:'ALL',value:20});g.adminApply({op:'recruit',char:'MOND_BENNETT'});const a=g.character('MOND_BENNETT'),snap=g.coopSnapshot('MOND_BENNETT');assert.equal(snap.actor.baseAttack,a.baseAttack);const legacy=cp(snap);delete legacy.actor.baseAttack;assert(g.coopCheckSnapshot(legacy),'older snapshots remain readable');});
fs.mkdirSync(root+'/evidence/v01522',{recursive:true});fs.writeFileSync(root+'/evidence/v01522/growth.json',JSON.stringify(checks,null,2));
