'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=process.env.CRPG_SOURCE||(fs.existsSync(path.join(__dirname,'runtime.js'))?__dirname:path.resolve(__dirname,'../source'));
const data=process.env.CRPG_DB||(fs.existsSync(path.join(base,'db_latest.json'))?path.join(base,'db_latest.json'):path.resolve(__dirname,'../content/db.json'));
const context=vm.createContext({console});
for(const name of ['runtime.js','runtime_extensions.js','runtime_story.js'])vm.runInContext(fs.readFileSync(path.join(base,name),'utf8'),context,{filename:name});
vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../source/runtime_nodes.js'),'utf8'),context,{filename:'runtime_nodes.js'});
const {Runtime,StoryParser}=context.CRPGRuntime,db=JSON.parse(fs.readFileSync(data,'utf8'));
if(process.env.CRPG_TEST_RELATIONSHIPS){const rel=process.env.CRPG_RELATIONSHIPS||(fs.existsSync(path.join(__dirname,'runtime_relationships.js'))?path.join(__dirname,'runtime_relationships.js'):path.resolve(__dirname,'../source/runtime_relationships.js'));vm.runInContext(fs.readFileSync(rel,'utf8'),context,{filename:'runtime_relationships.js'});context.CRPGRuntime=context.CRPGRelationships.install(context.CRPGRuntime,{events:context.CRPGRelationships.catalogFromDB(db)});}
let count=0;function test(name,fn){try{fn();count++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name,e);process.exitCode=1;}}
function fresh(route='ROUTE_TRAVELER'){const r=new Runtime(db);r.newGame({name:'검증',route,seed:72832,saveId:'TEST-'+route});return r;}
function goto(r,node){r.s.global.STORY_CURSOR_NODE_ID=node;r.s.global.CURRENT_STORY_NODE_ID=node;r.s.global.PENDING_CHOICE_GROUP_ID='';r.s.global.PENDING_INPUT_JSON='{}';r.s.global.SCREEN_MODE='STORY';r.prepareStory();}
test('both routes start independent and hidden META is skipped',()=>{let a=fresh(),b=fresh('ROUTE_ISEKAI');assert.notEqual(a.storyNode()[5],'META');assert.notEqual(b.storyNode()[5],'META');a.s.flags.FLAG_TRV_AVATAR='MALE';assert.notEqual(b.s.flags.FLAG_TRV_AVATAR,'MALE');assert.equal(a.s.global.STORY_CURSOR_NODE_ID,a.s.global.CURRENT_STORY_NODE_ID);});
test('all current active node effects have explicit typed grammar',()=>{const errors=[];for(const tab of ['55_MAIN_STORY_DB','57_MOND_STORY_SCENE_DB'])for(const [idx,row]of db[tab].entries()){if(idx&&row?.[18]==='ACTIVE'){try{StoryParser.parseEffects(row[12]);}catch(e){errors.push([tab,idx+1,row[4],e.message]);}}}assert.deepEqual(errors,[]);});
test('all current active node conditions parse without eval',()=>{const errors=[];for(const tab of ['55_MAIN_STORY_DB','57_MOND_STORY_SCENE_DB'])for(const [idx,row]of db[tab].entries()){if(idx&&row?.[18]==='ACTIVE'){try{StoryParser.parseCondition(row[11]);}catch(e){errors.push([tab,idx+1,row[4],e.message]);}}}assert.deepEqual(errors,[]);});
test('unknown condition is error and FALSE is false',()=>{const r=fresh();assert.equal(r.storyCondition('FALSE'),false);assert.throws(()=>r.storyCondition('TYPO_FUNCTION(X)'),{code:'CONDITION_FUNCTION'});assert.throws(()=>r.storyCondition('TYPO_VARIABLE=TRUE'),{code:'CONDITION_UNKNOWN'});assert.throws(()=>StoryParser.parseCondition('TRUE;process.exit()'),{code:'CONDITION_SYNTAX'});});
test('FLAG colon regression actual TRV_M01_Z003 atomically completes',()=>{const r=fresh();goto(r,'TRV_M01_Z003');const receipt=r.action('STORY_NEXT',{node:'TRV_M01_Z003'});assert.equal(receipt.ok,true);assert.equal(r.s.flags.FLAG_TRV_MON_PROLOGUE_CLEAR,true);assert.equal(r.s.quests.Q_TRV_MOND_01.state,'완료');assert.equal(r.s.global.CURRENT_STORY_NODE_ID,r.s.global.STORY_CURSOR_NODE_ID);assert.equal(r.s.global.STORY_WAITING,true);assert.doesNotThrow(()=>r.serialize());assert.ok(r.storyChapterEntries().some(x=>x.id==='TRV_M02_N001'));});
test('latest traveler prologue traverses authored choices and only chosen branch',()=>{const r=fresh();let steps=0;while(!r.s.global.STORY_WAITING&&steps++<500){const choices=r.storyChoices();if(choices.length){const selected=choices[0];r.action('STORY_CHOICE',{node:selected[4]});}else {const n=r.storyNode();assert.ok(n);r.action('STORY_NEXT',{node:n[4]});}}assert.ok(steps<500);assert.equal(r.s.flags.FLAG_TRV_MON_PROLOGUE_CLEAR,true);assert.equal(r.s.flags.FLAG_TRV_AVATAR,'MALE');assert.ok(!Object.keys(JSON.parse(r.s.global.STORY_NODE_EFFECTS_JSON)).some(x=>/FEMALE/.test(x)));});
test('choice requires explicit click and menu restores pending selection',()=>{const r=fresh();goto(r,'CHOICE_GROUP:TRV_M01_G_AVATAR');let choices=r.storyChoices();if(!choices.length){const node=r.storyIndex().byTable['55_MAIN_STORY_DB'].find(x=>x[0]==='ROUTE_TRAVELER'&&x[5]==='CHOICE');goto(r,'CHOICE_GROUP:'+node[14]);choices=r.storyChoices();}assert.ok(choices.length);const frame=JSON.stringify(r.storyFrame());r.action('MENU',{screen:'INVENTORY'});r.action('MENU',{screen:'STORY'});const after=r.storyFrame();assert.equal(after.choice,JSON.parse(frame).choice);assert.equal(after.main,JSON.parse(frame).main);assert.throws(()=>r.action('STORY_NEXT',{node:choices[0][4]}));});
test('SAVE_LOAD_ONLY blocks menu and direct economic bypass without changes',()=>{const r=fresh();r.s.global.STORY_MENU_POLICY='SAVE_LOAD_ONLY';const before=r.serialize();assert.throws(()=>r.action('MENU',{screen:'LOCATION'}),{code:'MENU_LOCK'});assert.throws(()=>r.action('WAIT',{minutes:30}),{code:'MENU_LOCK'});assert.equal(r.serialize(),before);r.action('MENU',{screen:'SYSTEM'});});
test('55 to56/57 entry preserves canonical cursor and exact pending choice return',()=>{const r=fresh();r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';const main=r.storyNode()[4],def=r.storyDefinition('LEG_MOND_ALBEDO');assert.equal(r.storyEntryReason(def),'');r.action('LEGEND_ENTER',{quest:def.id});assert.equal(r.storyNode().table,'57_MOND_STORY_SCENE_DB');assert.equal(r.s.global.STORY_CURSOR_NODE_ID,main);assert.equal(r.s.global.CURRENT_STORY_NODE_ID,main);assert.doesNotThrow(()=>r.serialize());r.action('STORY_RETURN');assert.equal(r.storyNode()[4],main);});
test('legend cost commits only at authored accept, refusal leaves inventory unchanged',()=>{const r=fresh();r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';r.action('LEGEND_ENTER',{quest:'LEG_MOND_ALBEDO'});let def=r.storyDefinition('LEG_MOND_ALBEDO');const before=r.s.global.MORA;r.giveItem('ORE_CRYSTAL',1);r.giveItem('MAT_SLIME_CONDENSATE',2);r.s.storyContext.node=def.COST_COMMIT_NODE_ID;r.s.global.PENDING_CHOICE_GROUP_ID=r.storyNode()[14];const n=r.storyNode();r.action('STORY_CHOICE',{node:n[4]});assert.equal(r.s.global.MORA,before);assert.equal(r.itemCount('ORE_CRYSTAL'),0);assert.equal(r.itemCount('MAT_SLIME_CONDENSATE'),0);assert.ok(r.s.storyCostReceipts[def.QUEST_ID]);});
test('legend insufficient materials rolls back cost cursor and receipts',()=>{const r=fresh();r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';r.action('LEGEND_ENTER',{quest:'LEG_MOND_ALBEDO'});const def=r.storyDefinition('LEG_MOND_ALBEDO');r.s.storyContext.node=def.COST_COMMIT_NODE_ID;r.s.global.PENDING_CHOICE_GROUP_ID=r.storyNode()[14];const before=r.serialize();assert.throws(()=>r.action('STORY_CHOICE',{node:def.COST_COMMIT_NODE_ID}));assert.equal(r.serialize(),before);});
test('general B110 legacy sixth-heart gate maps to five hearts without adult mode',()=>{const r=fresh(),def=r.storyDefinition('AFF_MOND_AMBER_B110');r.s.relations[def.PROFILE_ID]={heart:5,BOND_SCORE:120,events:{},firstContact:1,unlocked:[]};r.s.flags.FLAG_LEG_MOND_AMBER_CLEAR=true;r.s.storyEventReceipts={AFF_MOND_AMBER_H05:{turn:1,day:1}};r.s.quests[def.REQUIRED_QUEST_ID]={state:'완료',claimed:true};r.s.global.CURRENT_MAP_ID=def.MAP_ID;r.s.storyEventReceipts[def.PREV_EVENT_ID]={turn:1,day:1};assert.equal(r.storyEntryReason(def),'');});
test('current mature definitions stay locked without verified policy',()=>{const r=fresh();for(const def of r.storyIndex().affections.values()){if(/ADULT/.test(def.RELATION_KIND)&&def.ROUTE_SCOPE==='ROUTE_TRAVELER'){r.s.global.CURRENT_MAP_ID=def.MAP_ID;assert.notEqual(r.storyEntryReason(def),'');}}});
test('unknown effect aborts complete transaction with no preceding flag applied',()=>{const r=fresh();const row=r.storyNode(),original=row[12];row[12]='FLAG:FLAG_TRV_MON_PROLOGUE_CLEAR=TRUE;UNKNOWN_OP:X';const before=r.serialize();assert.throws(()=>r.action('STORY_NEXT',{node:row[4]}),{code:'STORY_EFFECT'});assert.equal(r.serialize(),before);row[12]=original;});
test('same action receipt never reapplies node effect',()=>{const r=fresh();goto(r,'TRV_M01_Z003');const action={type:'STORY_NEXT',node:'TRV_M01_Z003',id:r.s.global.SAVE_ID+':1',revision:r.s.global.SAVE_REVISION};const first=r.transact(action),before=r.serialize(),second=r.transact(action);assert.equal(JSON.stringify(first),JSON.stringify(second));assert.equal(r.serialize(),before);});
test('all authored traveler Mond legend routes complete accept/cost/reward/join/return',()=>{const probe=fresh();for(const def of probe.storyIndex().legends.values()){if(def.ROUTE_SCOPE!=='ROUTE_TRAVELER'||def.REGION!=='몬드')continue;const r=fresh();r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;r.s.flags.FLAG_MOND_MIKA_RETURNED=true;r.s.flags.FLAG_MOND_MONA_PRESENT=true;r.s.global.CURRENT_MAP_ID=def.MAP_ID;r.s.global.MORA=100000;for(const [id,n]of Object.entries(JSON.parse(def.COST_ITEMS_JSON||'{}')))r.giveItem(id,n);const main=r.storyActiveNodeId();r.action('LEGEND_ENTER',{quest:def.id});let steps=0;while(r.s.storyContext&&steps++<180){const cs=r.storyChoices();if(cs.length){const selected=cs.find(n=>String(n[12]).includes('LEGEND_ACCEPT_AND_PAY'))||cs.find(n=>String(n[12]).includes('UNLOCK_CARD_ONCE'))||cs[0];r.action('STORY_CHOICE',{node:selected[4]});}else{const n=r.storyNode();assert.ok(n,def.id);r.action('STORY_NEXT',{node:n[4]});}}assert.ok(steps<180,def.id);assert.equal(r.storyActiveNodeId(),main,def.id);assert.equal(r.s.quests[def.QUEST_ID].state,'완료',def.id);assert.equal(r.s.flags[def.COMPLETE_FLAG_ID],true,def.id);assert.equal(r.s.relations[def.PROFILE_ID].BOND_SCORE,10,def.id);assert.equal(r.s.relations[def.PROFILE_ID].heart,0,def.id);assert.doesNotThrow(()=>r.serialize());}});
test('all traveler Mond H01-H05 scenes execute their actual authored branches',()=>{const probe=fresh();for(const def of probe.storyIndex().affections.values()){if(def.ROUTE_SCOPE!=='ROUTE_TRAVELER'||def.id.includes('LIYUE')||!/H0[1-5]$/.test(def.id))continue;const r=fresh();r.s.global.CURRENT_MAP_ID=def.MAP_ID;r.s.global.MORA=100000;r.s.flags.FLAG_MOND_MIKA_RETURNED=true;r.s.flags.FLAG_MOND_MONA_PRESENT=true;for(const flag of JSON.parse(def.REQUIRED_FLAGS||'[]'))r.s.flags[flag]=true;r.s.quests[def.REQUIRED_QUEST_ID]={state:'완료',claimed:true};r.s.storyEventReceipts={};if(def.PREV_EVENT_ID)r.s.storyEventReceipts[def.PREV_EVENT_ID]={turn:1,day:1};r.s.relations[def.PROFILE_ID]={firstContact:1,heart:Math.floor(Number(def.BOND_SCORE_MIN)/20),BOND_SCORE:Number(def.BOND_SCORE_MIN),events:{},unlocked:[],lastDailyTurn:2};r.action('AFFECTION_ENTER',{event:def.id});let steps=0;while(r.s.storyContext&&steps++<100){const cs=r.storyChoices();if(cs.length)r.action('STORY_CHOICE',{node:cs[0][4]});else{const n=r.storyNode();assert.ok(n,def.id);r.action('STORY_NEXT',{node:n[4]});}}assert.ok(steps<100,def.id);assert.equal(r.storyDone(def.id),true,def.id);assert.ok(r.s.relations[def.PROFILE_ID].heart<=5,def.id);assert.doesNotThrow(()=>r.serialize());}});
test('personal save/reload restores exact scene and return stack',()=>{const r=fresh();r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';const main=r.storyActiveNodeId();r.action('LEGEND_ENTER',{quest:'LEG_MOND_ALBEDO'});const id=r.storyActiveNodeId();const restored=new Runtime(db,JSON.parse(r.serialize()));assert.equal(restored.storyActiveNodeId(),id);assert.equal(restored.s.global.STORY_CURSOR_NODE_ID,main);restored.action('STORY_RETURN');assert.equal(restored.storyActiveNodeId(),main);});
test('imported unverified mature cursor suspends before any scene is displayed',()=>{const r=fresh(),def=r.storyDefinition('AFF_MOND_JEAN_H110'),save=JSON.parse(r.serialize());save.storyReturnStack=[r.storyFrame()];save.storyContext={kind:'AFFECTION',entry:def.id,node:def.ENTRY_NODE_ID,table:'57_MOND_STORY_SCENE_DB'};save.storyEventReceipts={[def.id]:{turn:1,day:1}};const restored=new Runtime(db,save);assert.equal(restored.s.storyContext,null);assert.equal(restored.s.global.SCREEN_MODE,'SYSTEM');assert.ok(restored.s.storySuspendedContext);assert.ok(restored.s.storyEventReceipts[def.id]);assert.notEqual(restored.storyNode()?.[4],def.ENTRY_NODE_ID);});
console.log(JSON.stringify({tests:count,passed:!process.exitCode}));
