'use strict';
/* Regression driver comparing legacy and current geography.
   Legacy fixtures are created from current installed runtime
   with geography excluded; they deliberately start at bounded story boundaries. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const ROOT=process.env.CRPG_ROOT||path.resolve(__dirname,'..'),OUT=path.resolve(__dirname,'../reports');
const copy=x=>JSON.parse(JSON.stringify(x)),db=JSON.parse(fs.readFileSync(path.join(ROOT,'content/db.json')));
let skew=0;// lets a test skip the 60 second defeat lock without waiting
function load(geography){const c=vm.createContext({console,Date:class extends Date{static now(){return super.now()+skew;}},setTimeout,clearTimeout});const files=[...fs.readFileSync(path.join(ROOT,'source/index.html'),'utf8').matchAll(/<script src="((?:world_content|runtime[^" ]*)\.js)"/g)].map(m=>m[1]);if(geography&&!files.includes('runtime_geography.js'))throw Error('runtime_geography.js not installed in index.html yet');for(const f of files)if(geography||f!=='runtime_geography.js')vm.runInContext(fs.readFileSync(path.join(ROOT,'source',f),'utf8'),c,{filename:f});return {R:c.CRPGRuntime.Runtime,c};}
let seq=0;const legacy=load(false);
function base({route='ROUTE_ISEKAI',branch='K',node='END',map='MAP_DRAGONSPINE',policy=''}={}){const r=new legacy.R(db);r.newGame({name:'지리검증',route,seed:612321,saveId:'GEO-LEGACY-'+(++seq)});Object.assign(r.s.global,{CURRENT_MAP_ID:map,CURRENT_STORY_NODE_ID:node,STORY_CURSOR_NODE_ID:node,PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',SCREEN_MODE:'STORY',STORY_WAITING:false,STORY_NEXT_PREPARED:'',STORY_MENU_POLICY:policy,WORLD_TIME:'12:00',MORA:1500});for(const k of ['storyJourney','storyBreak','storyArrival','storyMenuFrame','storyContext','battlePreparation','storyRecovery'])delete r.s[k];Object.assign(r.s.flags,{FLAG_ISK_META_KNOWLEDGE:branch==='K'?'KNOWN':'UNKNOWN',FLAG_ISK_MOND_BRANCH:branch==='B'?'GUILD':'EXPEDITION',FLAG_ISK_EXPEDITION_FORK:branch==='AA'?'RIDE':'RETURN'});r.s.quests.Q_ISK_MOND_02={state:'진행중',node:'ACTIVE',claimed:false};return r;}
function materials(s){const g=s.global;return copy({mora:g.MORA,level:g.PLAYER_LEVEL_STATE,xp:g.PLAYER_XP_STATE,hp:g.PLAYER_HP_CURRENT,rng:g.PRNG_STATE,day:g.WORLD_DAY,time:g.WORLD_TIME,inventory:s.inventory,relations:s.relations,quests:s.quests,combatReceipts:s.combatReceipts||{},effects:g.STORY_NODE_EFFECTS_JSON,events:g.EVENT_PROGRESS_JSON});}
function raw(r){return JSON.parse(r.serialize());}
function assertLoadDoesNotReward(before,after){assert.deepEqual(materials(after),materials(before),'load must preserve costs, rewards, RNG, clock and already committed story receipts');assert.equal(after.global.CURRENT_MAP_ID,before.global.CURRENT_MAP_ID,'load must not teleport');}
function loadRaw(R,s){const before=copy(s),r=new R(db,s);assertLoadDoesNotReward(before,r.s);return r;}
function migrate(R,r){return loadRaw(R,raw(r));}
function physicalWalk(r,target){r.rollEncounter=()=>null;let guard=0;while(r.s.global.CURRENT_MAP_ID!==target){assert.ok(++guard<25,'route loop');let q=[[r.s.global.CURRENT_MAP_ID,[]]],seen=new Set(q.map(a=>a[0])),found;while(q.length){const [at,steps]=q.shift();if(at===target){found=steps;break;}for(const e of r.rows('47_MAP_EDGE_DB').filter(e=>e[1]===at&&e[11]==='ACTIVE'&&e[8]==='Y')){if(e[6])continue;if(!seen.has(e[2])){seen.add(e[2]);q.push([e[2],[...steps,e[0]]]);}}}assert.ok(found?.length,'reachable target '+target);assert.equal(r.actionReason('MOVE',{edge:found[0]}),'','travel must be available');r.action('MOVE',{edge:found[0]});}return r;}
function gateFixture(branch){const gate='ISK_M04_'+branch+'_END',next='ISK_M05_'+branch+'_001',event=branch==='K'?'EVT_ISK_M04_K_K_BATTLE_RESULT_WAIT':'EVT_ISK_M04_B_B_PURIFIED_CAMP_END';const r=base({branch,node:gate,policy:branch==='K'?'SAVE_LOAD_ONLY':''}),g=r.s.global;Object.assign(g,{STORY_WAITING:true,STORY_NEXT_PREPARED:next,SCREEN_MODE:'STORY_WAIT'});const result=branch==='K'?'SUBDUED_RESULT_PENDING':'ALIVE_PURIFIED',bid='LEGACY-BOUNDED-BATTLE';const boss={resolvedNode:'ISK_M04_'+branch+'_COMBAT',gate:'ISK_M04_'+branch+'_COMBAT',branch,saveId:g.SAVE_ID,battleId:bid,group:'EG_ISK_M04_'+branch+'_DVALIN',victory:true,result,turn:1,day:1};const receipt={event,resolvedNode:gate,saveId:g.SAVE_ID,route:g.STORY_ROUTE_ID,quest:'Q_ISK_MOND_02',branch,kind:'chapter_gate',turn:1,day:1};g.EVENT_PROGRESS_JSON=JSON.stringify({[event]:receipt,['EVT_ISK_M04_'+branch+'_BATTLE_RESULT']:boss,Q_ISK_MOND_02:{events:{[event]:receipt},m04:{[branch]:{battle_result:boss,world_fact:{dvalin_life:branch==='K'?'ALIVE_RESURRECTED':'ALIVE_PURIFIED'}}}}});g.STORY_NODE_EFFECTS_JSON=JSON.stringify({['ROUTE_ISEKAI:'+gate]:true});r.s.flags['FLAG_ISK_M04_'+branch+'_BATTLE_WON']=true;if(branch==='B'){r.giveItem('KEY_ISK_MYSTERY_ORB',1);r.s.flags.FLAG_ISK_ORB_OWNED=true;r.s.quests.Q_ISK_MOND_02={state:'완료',node:'COMPLETE',claimed:true,completedTurn:1};}return r;}
function activeBossFixture(branch='K'){const node='ISK_M04_'+branch+'_COMBAT',r=base({branch,node});if(branch==='B'){r.giveItem('KEY_ISK_MYSTERY_ORB',1);r.s.flags.FLAG_ISK_ORB_OWNED=true;}r.prepareStory();r.startBattle('EG_ISK_M04_'+branch+'_DVALIN','STORY:'+node,{confirmed:true,companions:[]});assert.ok(r.s.runtime,'legacy active boss');return r;}
function run(){const {R}=load(true),results=[];const test=(name,fn)=>{try{fn();results.push({name,pass:true});console.log('PASS '+name);}catch(e){results.push({name,pass:false,error:e.stack});console.log('FAIL '+name+' '+e.message);}};
 test('legacy aggregate map retains a physical exit without direct plains bypass',()=>{const r=migrate(R,base());assert.equal(r.s.global.CURRENT_MAP_ID,'MAP_DRAGONSPINE');const exit=r.rows('47_MAP_EDGE_DB').find(e=>e[1]==='MAP_DRAGONSPINE'&&e[2]==='MAP_CRPG_DRAGONSPINE_CAMP'&&e[11]==='ACTIVE');assert.ok(exit);r.s.global.STORY_WAITING=true;r.s.global.SCREEN_MODE='LOCATION';r.rollEncounter=()=>null;r.action('MOVE',{edge:exit[0]});assert.equal(r.s.global.CURRENT_MAP_ID,'MAP_CRPG_DRAGONSPINE_CAMP');assert.ok(!r.rows('47_MAP_EDGE_DB').some(e=>e[0]==='EDGE_CRPG_MOND_PLAINS_TO_DRAGONSPINE'&&e[11]==='ACTIVE'&&e[8]==='Y'));});
 test('pending travel refreshes old target while preserving cost and cursor',()=>{const o=base({node:'ISK_M03_B_218',branch:'B',map:'MAP_MOND_CITY'});o.s.storyJourney={node:'ISK_M03_B_218',route:'ROUTE_ISEKAI',from:'MAP_MOND_CITY',target:'MAP_DRAGONSPINE',event:'EVT_ISK_M03_B_ARRIVE_TRAVEL',special:null,minutes:180,policy:''};o.s.global.STORY_WAITING=true;o.s.global.SCREEN_MODE='LOCATION';const r=migrate(R,o);assert.equal(r.s.storyJourney.target,'MAP_CRPG_DRAGONSPINE_CAMP');assert.equal(r.storyActiveNodeId(),'ISK_M03_B_218');assert.deepEqual(copy(new R(db,raw(r)).s),copy(r.s),'repeat load is idempotent');});
 test('old acknowledged travel is not accepted at the wrong detailed map',()=>{const o=base({node:'ISK_M04_K_079'});o.s.storyArrival={node:'ISK_M04_K_079',route:'ROUTE_ISEKAI',from:'MAP_MOND_CITY',target:'MAP_DRAGONSPINE',event:'EVT_ISK_M04_K_TRAVEL_06',special:null,minutes:180,policy:''};const r=migrate(R,o);assert.ok(!r.s.storyArrival);assert.equal(r.s.storyJourney.target,'MAP_CRPG_DRAGONSPINE_CAMP');});
 test('choice-group cursor and all peers remain together at camp',()=>{const group='ISK_M03_G_238',node='CHOICE_GROUP:'+group,o=base({node,branch:'B'});o.s.global.PENDING_CHOICE_GROUP_ID=group;o.s.global.PENDING_INPUT_JSON=JSON.stringify({group,node});const r=migrate(R,o);assert.ok(r.s.storyJourney,'old choice group needs a reachable arrival gate');assert.equal(r.s.storyJourney.target,'MAP_CRPG_DRAGONSPINE_CAMP');assert.equal(r.s.storyJourney.choiceGroup,node);physicalWalk(r,r.s.storyJourney.target);r.action('JOURNEY_RESUME');assert.equal(r.s.global.PENDING_CHOICE_GROUP_ID,group);assert.ok(r.storyChoices().length);assert.ok(r.storyChoices().every(n=>n[8]==='MAP_CRPG_DRAGONSPINE_CAMP'));});
 for(const branch of ['K','B'])test(branch+' completed chapter gate migrates without a policy deadlock or replay',()=>{const r=migrate(R,gateFixture(branch)),target=branch==='K'?'MAP_CRPG_SKYFROST_NAIL':'MAP_CRPG_DRAGONSPINE_CAMP';assert.equal(r.s.global.STORY_MENU_POLICY,'','travel must be possible from old chapter map');assert.ok(r.s.storyJourney||r.s.storyBreak,'chapter saved at old map needs travel');assert.equal(r.playPhase(),'FREE');if(r.s.storyJourney)assert.equal(r.s.storyJourney.target,target);physicalWalk(r,target);if(r.s.storyJourney||r.s.storyBreak)r.action('JOURNEY_RESUME');if(r.s.global.STORY_NEXT_PREPARED)r.action('STORY_RESUME');assert.equal(r.s.global.CURRENT_MAP_ID,target);assert.ok(r.s.quests.Q_ISK_MOND_03?.state==='진행중','existing M05 guard should still admit the exact branch');assert.equal(r.itemCount('KEY_ISK_MYSTERY_ORB'),branch==='K'?0:1);});
 for(const branch of ['K','B'])test(branch+' active legacy boss loads intact and a defeat remains recoverable',()=>{const o=activeBossFixture(branch),before=raw(o),r=loadRaw(R,before);assert.deepEqual(copy(r.s.runtime),copy(before.runtime),'no midfight map, combat config or actor mutation');assert.ok(!r.s.storyJourney,'active battle must not begin travel');assert.equal(r.s.global.CURRENT_MAP_ID,'MAP_DRAGONSPINE');const twice=new R(db,raw(r));assert.deepEqual(copy(twice.s.runtime),copy(before.runtime),'repeat load retains legacy encounter');twice.finishBattle(false);assert.ok(twice.s.storyRecovery||twice.s.storyBreak||twice.s.battlePreparation,'defeated save preserves retry');new R(db,raw(twice));if(twice.s.storyRecovery){assert.throws(()=>twice.action('STORY_RETRY'),/정신을 차리는 중/);skew+=60000;twice.action('STORY_RETRY');}assert.ok(twice.s.storyJourney||twice.s.storyBreak,'old checkpoint retry needs corrected return destination');const target=branch==='K'?'MAP_CRPG_SKYFROST_NAIL':'MAP_CRPG_SNOW_COVERED_PATH';physicalWalk(twice,target);twice.action('JOURNEY_RESUME');assert.ok(twice.s.battlePreparation||twice.storyNode()?.[5]==='COMBAT_GATE');new R(db,raw(twice));});
 test('legacy preparation becomes a same-node return goal instead of map-source failure',()=>{const node='ISK_M04_K_COMBAT',o=base({node});o.prepareStory();o.startBattle('EG_ISK_M04_K_DVALIN','STORY:'+node);assert.ok(o.s.battlePreparation);const r=migrate(R,o);assert.ok(!r.s.battlePreparation);assert.ok(r.s.storyBreak||r.s.storyJourney);assert.equal(r.storyActiveNodeId(),node);physicalWalk(r,'MAP_CRPG_SKYFROST_NAIL');r.action('JOURNEY_RESUME');if(!r.s.battlePreparation)r.action('STORY_NEXT',{node});assert.ok(r.s.battlePreparation);r.action('COMBAT_PREPARE',{group:'EG_ISK_M04_K_DVALIN',companions:[]});assert.ok(r.s.runtime);assert.equal(r.s.runtime.storyConfig.map_id,'MAP_CRPG_SKYFROST_NAIL');});
 fs.writeFileSync(path.join(OUT,'geography-regression-results.json'),JSON.stringify({scope:'Bounded migration/arrival/legacy combat fixtures; not full-route completion',results},null,2));return results;}
module.exports={load,base,gateFixture,activeBossFixture,physicalWalk,materials,raw,run};if(require.main===module){const results=run();process.exitCode=results.some(t=>!t.pass)?1:0;}
