'use strict';
const assert=require('node:assert/strict');
const {R,db,fresh,advance}=require('./helpers_v011.cjs');
const cp=x=>JSON.parse(JSON.stringify(x)),AMBER='MOND_AMBER';let passed=0;
function check(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name,e);process.exitCode=1;}}
function prologue(owned=false){let r=new R(db);r.newGame({route:'ROUTE_TRAVELER',name:'첫걸음',seed:27});if(owned)r.wishGrant({kind:'char',id:AMBER,rarity:4});r.s.global.ENCOUNTER_COOLDOWN=100;
 for(let i=0;i<180&&!r.s.battlePreparation;i++){if(r.s.storyJourney){const j=r.s.storyJourney;if(r.s.global.CURRENT_MAP_ID===j.target)r.action('JOURNEY_RESUME');else r.action('MOVE',{edge:r.navigationRoute(j.target).edges[0][0]});continue;}const n=r.storyNode(),cs=r.storyChoices();assert(n||cs.length);r.action(cs.length?'STORY_CHOICE':n[5]==='INPUT_TEXT'?'STORY_NAME':'STORY_NEXT',cs.length?{node:cs[0][4]}:n[5]==='INPUT_TEXT'?{name:'첫걸음'}:{node:n[4]});}
 assert.equal(r.s.battlePreparation?.node,'PRO_TRVM01_평원_028');return r;
}
function ready(r){if(!r.s.party.some(x=>x.active&&x.source===AMBER))r.action('PARTY',{char:AMBER,slot:2});const slot=r.s.inventory.find(x=>x.equip==='EQ_BOW_SLINGSHOT').slot;r.action('EQUIP',{slot,owner:AMBER});r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[AMBER]});}
function play(r){if(r.combatOpening())r.action('COMBAT_BEGIN');for(let i=0;r.s.runtime&&i<60;i++){const card=r.combatCards().find(x=>!x.reason&&x.id==='PLAYER_BASIC_ATTACK');assert(card);r.action('COMBAT',{card:card.id,target:card.targets[0]?.id});}assert(!r.s.runtime);assert(JSON.parse(r.s.global.LAST_BATTLE_RESULT_JSON).victory);}
check('authored first Traveler fight requires Amber selection and a real equip action',()=>{const r=prologue(),t=r.tutorialState();assert.equal(r.tutorialDirective().actor,AMBER);assert(t.loan);assert.throws(()=>r.action('COMBAT_PREPARE',{group:t.loan.group,companions:[]}),/엠버/);r.action('PARTY',{char:AMBER,slot:2});assert.equal(r.tutorialDirective().id,'equip');assert(!r.s.inventory.some(x=>x.owner===AMBER&&x.equipped));assert(!r.s.starterKit.companions[AMBER]);assert.throws(()=>r.action('COMBAT_PREPARE',{group:t.loan.group,companions:[AMBER]}),/무기/);r.action('EQUIP',{slot:t.loan.weaponSlot,owner:AMBER});assert.equal(r.tutorialDirective().id,'prepare');});
check('save/reload preserves each first-fight preparation step',()=>{let r=prologue();r=new R(db,cp(r.s));assert.equal(r.tutorialDirective().id,'party');r.action('PARTY',{char:AMBER,slot:2});r=new R(db,cp(r.s));assert.equal(r.tutorialDirective().id,'equip');r.action('EQUIP',{slot:r.tutorialState().loan.weaponSlot,owner:AMBER});r=new R(db,cp(r.s));assert.equal(r.tutorialDirective().id,'prepare');ready(r);r=new R(db,cp(r.s));assert.equal(r.tutorialDirective().id,'combatStart');assert(r.s.runtime.actors.some(x=>x.source===AMBER));});
check('actual first victory releases only borrowed Amber and her borrowed bow',()=>{let r=prologue();const slot=r.tutorialState().loan.weaponSlot;ready(r);assert.equal(r.tutorialDirective().id,'combatStart');r.action('COMBAT_BEGIN');assert.equal(r.tutorialDirective().card,'PLAYER_BASIC_ATTACK');play(r);assert(r.tutorialState().done.combatAttack);assert(r.tutorialState().done.amberIntro);assert(!r.tutorialState().loan);assert(!r.premiumOwns(AMBER));assert(!r.s.inventory.some(i=>i.slot===slot));assert(!r.s.party.some(i=>i.active&&i.source===AMBER));assert(!r.s.starterKit.companions[AMBER]);r=new R(db,cp(r.s));r.wishGrant({kind:'char',id:AMBER,rarity:4});assert(r.premiumOwns(AMBER));assert(r.s.starterKit.companions[AMBER]);});
check('owned Amber remains owned after the same first story fight',()=>{let r=prologue(true);assert(!r.tutorialState().loan);assert.equal(r.tutorialDirective().actor,AMBER);ready(r);play(r);assert(r.premiumOwns(AMBER));assert(r.s.inventory.some(i=>i.owner===AMBER&&i.equipped));new R(db,cp(r.s));});
check('first fight defeat and retry keep the scoped companion usable',()=>{let r=prologue();ready(r);r.action('COMBAT_FORFEIT');assert(r.s.storyRecovery);r=new R(db,cp(r.s));assert(r.tutorialState().loan);advance(180000);r.action('STORY_RETRY');assert(r.s.battlePreparation);assert(r.premiumOwns(AMBER));r=new R(db,cp(r.s));r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[AMBER]});play(r);assert(!r.premiumOwns(AMBER));new R(db,cp(r.s));});
check('first permanent wish during a loan is an acquisition, not a duplicate',()=>{const r=prologue();const out=r.wishGrant({kind:'char',id:AMBER,rarity:4});assert(out.joined&&!out.stella);assert(!r.tutorialState().loan);ready(r);play(r);assert(r.premiumOwns(AMBER));});
check('loan metadata cannot claim another companion or escape the authored fight',()=>{const r=prologue();for(const change of [s=>s.tutorialV2.loan.id='MOND_DILUC',s=>s.tutorialV2.intro.node='END',s=>delete s.battlePreparation,s=>delete s.tutorialV2.loan,s=>s.tutorialV2.loan.previous={state:'JOINED'}]){const s=cp(r.s);change(s);assert.throws(()=>new R(db,s));}});
check('unrelated free play does not demand wishes, a training room, domains or ascension',()=>{for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI']){const r=fresh('MAP_MOND_CITY',route);assert.equal(r.tutorialDirective(),null);r.s.tutorialV2.done={move:true,arrival:true};assert.equal(r.tutorialDirective(),null);r.s.flags.FLAG_TRV_ANEMO_UNLOCKED=true;r.startBattle('EG_MOND_HILI_PATROL','RANDOM');assert.equal(r.tutorialDirective().id,'combatStart');}});
check('only successful actual actions teach combat and later first-use life activities',()=>{const r=fresh('MAP_MOND_PLAINS');r.startBattle('EG_MOND_HILI_PATROL','RANDOM');assert.throws(()=>r.action('TUTORIAL_GUIDE',{enabled:false}),/안내/);assert(!r.tutorialState().done.combatAttack);r.action('COMBAT_BEGIN');assert.throws(()=>r.action('COMBAT',{card:'NO_CARD'}));assert(!r.tutorialState().done.combatAttack);for(const kind of ['GATHER','MINE','HUNT']){const x=fresh(kind==='MINE'?'MAP_CRPG_MOND_QUARRY':kind==='HUNT'?'MAP_CRPG_WHISPER_HUNT':'MAP_MOND_PLAINS');x.action('LIFE_START',{kind});assert.equal(x.tutorialDirective().id,'life'+kind);x.s.tutorialV2.done['life'+kind]=true;assert.equal(x.tutorialDirective(),null);}});
check('the old later switch migrates without replaying completed combat lessons or granting rewards',()=>{const r=fresh();const s=cp(r.s);delete s.tutorialV2.style;s.tutorialV2.enabled=false;s.tutorialV2.done={move:true,drill:true};const x=new R(db,s);assert(x.tutorialState().enabled);assert(x.tutorialState().done.combatAttack&&x.tutorialState().done.combatGuard&&x.tutorialState().done.combatSkill);assert.equal(x.s.global.MORA,r.s.global.MORA);assert.deepEqual(cp(x.s.inventory),cp(r.s.inventory));new R(db,cp(x.s));});
check('an older save already waiting at the first preparation receives the scoped lesson once',()=>{const r=prologue(),s=cp(r.s),slot=s.tutorialV2.loan.weaponSlot;s.inventory=s.inventory.filter(i=>i.slot!==slot);s.global.COMPANION_ELIGIBILITY_JSON='{}';s.tutorialV2={version:2,enabled:false,done:{move:true}};let x=new R(db,s);assert.equal(x.tutorialDirective().id,'party');const n=x.s.inventory.length;x=new R(db,cp(x.s));assert.equal(x.s.inventory.length,n);ready(x);play(x);assert(!x.premiumOwns(AMBER));});
check('an unattended failed minigame does not mark its controls as learned',()=>{const r=fresh('MAP_MOND_PLAINS');r.action('LIFE_START',{kind:'GATHER'});const job=cp(r.s.lifeJob);advance(job.duration);r.die=()=>100;const out=r.action('LIFE_FINISH',{job:job.id,inputs:[],elapsed:job.duration});assert(!r.tutorialState().done.lifeGATHER);r.action('LIFE_START',{kind:'GATHER'});assert.equal(r.tutorialDirective().id,'lifeGATHER');});
console.log(passed+' tutorial regression checks passed');
module.exports={prologue,ready,play};
