// Exercise authoritative growth costs and settlement through saved balance
// profiles. Victories below are injected only to isolate reward settlement;
// this is not a measurement of domain combat difficulty or farming speed.
import assert from 'node:assert/strict';
import {LiveRegionStore} from '../server/fixed-region-live.mjs';
import {DB} from '../server/generated/engine.mjs';

const store=new LiveRegionStore(':memory:',{pepper:'balance-growth-test-'.padEnd(64,'p')}),clone=x=>structuredClone(x);
let checks=0;const check=(v,m)=>{assert(v,m);checks++;};
function free(r){Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',STORY_MENU_POLICY:'',SCREEN_MODE:'LOCATION',MORA:1000000});r.s.flags.FLAG_TRV_MON_CH1_CLEAR=true;delete r.s.storyJourney;delete r.s.storyBreak;r.s.storyContext=null;r.prepareStory?.();return r;}
try{
 const api=globalThis.CRPGRuntime.adminBalance,base=store.runtimeFactory(DB);base.newGame({name:'육성 수치 검사',route:'ROUTE_TRAVELER',saveId:'BALANCE-GROWTH-NATIVE',seed:717});free(base);base.adminApply({op:'level',target:'PLAYER_CUSTOM',value:10});const state=clone(base.s),catalog=store.balance.catalog();
 check(Array.isArray(catalog.growth)&&catalog.growth.length>0,'growth catalog is available');
 const domainRow=catalog.growth.find(row=>row.subtitle==='특성 비경'&&row.name.includes('Lv. 5')&&row.fields.some(f=>f.path?.at(-1)==='materialQuantity')),material=domainRow?.fields.find(f=>f.path?.at(-1)==='materialQuantity'),xp=domainRow?.fields.find(f=>f.path?.at(-1)==='xp');check(!!material&&!!xp,'actual early material domain catalog');
 const ascension=catalog.growth.flatMap(row=>row.fields).find(f=>f.path?.[0]==='ascension'&&f.path?.[1]==='0'),talent=catalog.growth.flatMap(row=>row.fields).find(f=>f.path?.[0]==='talents'&&f.path?.[1]==='MOND'&&f.path?.[2]==='1');check(!!ascension&&!!talent,'future ascension and talent requirement catalog');
 const id=material.path[1],key=id.split(':')[0],map=globalThis.CRPGRuntime.growthV01522.domains[key].map,config=api.emptyConfig();config.growth.domains[id]={materialQuantity:material.base+7,xp:xp.base+10};config.growth.ascension['0']=ascension.base+3;config.growth.talents.MOND={'1':talent.base+2};
 const profileBefore=store.balance.currentRevision(),preview=store.balance.preview({expectedRevision:0,config});check(preview.changes.some(c=>c.path==='growth/domains/'+id+'/materialQuantity'&&c.before===material.base&&c.after===material.base+7&&!c.label.startsWith('growth/')),'growth preview uses Korean labels and concrete baseline values');check(store.balance.currentRevision()===profileBefore,'growth preview does not publish a profile');
 const invalid=api.emptyConfig();invalid.growth.domains.NOT_A_DOMAIN={materialQuantity:1};assert.throws(()=>store.balance.preview({expectedRevision:0,config:invalid}),e=>e.status===400);checks++;
 store.balance.apply({expectedRevision:0,config,note:'육성 비용·보상 실제 검증'},'QA','local');const r=free(store.runtimeFactory(DB,clone(state),true)),asc=r.ascensionInfo('PLAYER_CUSTOM'),gem=Object.keys(asc.cost.items).find(k=>k.startsWith('GROWTH_GEM_'));check(asc.cost.items[gem]===ascension.base+3,'actual future ascension quote uses the configured common gem quantity');for(const[item,n]of Object.entries(asc.cost.items))r.giveItem(item,n);const gemBefore=r.itemCount(gem),moraBefore=r.s.global.MORA;r.action('CHAR_ASCEND',{owner:'PLAYER_CUSTOM'});check(r.s.ascensions.PLAYER_CUSTOM===1&&gemBefore-r.itemCount(gem)===ascension.base+3&&moraBefore-r.s.global.MORA===asc.cost.mora,'actual ascension action pays the configured materials and native Mora once');
 const tal=r.talentUpgradeInfo('PLAYER_CUSTOM','na');check(tal.cost.items.GROWTH_TALENT_MOND===talent.base+2,'actual talent quote uses configured future books');for(const[item,n]of Object.entries(tal.cost.items))r.giveItem(item,n);const booksBefore=r.itemCount('GROWTH_TALENT_MOND'),trainedMora=r.s.global.MORA;r.action('TALENT_UPGRADE',{owner:'PLAYER_CUSTOM',kind:'na'});check(r.talentLevels('PLAYER_CUSTOM').base.na===2&&booksBefore-r.itemCount('GROWTH_TALENT_MOND')===talent.base+2&&trainedMora-r.s.global.MORA===tal.cost.mora,'actual talent action pays the configured books and native Mora once');
 const run=free(store.runtimeFactory(DB,clone(state),true));run.s.global.CURRENT_MAP_ID=map;const entry=run.growthDomainEntries().find(d=>d.id===id);check(!!entry&&!entry.reason,'selected native material domain is actually accessible');const quoted=run.growthDomainRewards(entry,'NEUTRAL');check(Object.values(quoted.items).reduce((n,v)=>n+v,0)===(material.base+7)*2&&quoted.xp===xp.base+10,'native preview retains first-three double materials and the specified XP');const beforeEntry=clone(run.s);run.action('DOMAIN_START',{domain:id});check(run.s.runtime.adminBalanceRevision===1,'real domain entry freezes the balance revision');const domainSaved=clone(run.s);
 const next=api.emptyConfig();next.growth.domains[id]={materialQuantity:material.base+11,xp:xp.base+20};store.balance.apply({expectedRevision:1,config:next,note:'전투 도중 다음 판'},'QA','local');const resumed=store.runtimeFactory(DB,clone(domainSaved),true);check(store.balance.runtimeRevision(resumed)===1,'saved domain keeps the original configuration after an apply');const held=resumed.growthDomainRewards(resumed.s.runtime.growthDomain,'NEUTRAL');check(Object.values(held.items).reduce((n,v)=>n+v,0)===(material.base+7)*2&&held.xp===xp.base+10,'pinned domain reward quote keeps its original material and XP promise');const item=Object.keys(held.items)[0],beforeWin=resumed.itemCount(item),result=resumed.finishBattle(true);check(resumed.itemCount(item)-beforeWin===held.items[item]&&result.xp===xp.base+10&&result.domain.items[item]===held.items[item],'native domain victory settlement pays the original profile exactly');
 const fresh=store.runtimeFactory(DB,clone(beforeEntry),true),newEntry=fresh.growthDomainEntries().find(d=>d.id===id),newQuote=fresh.growthDomainRewards(newEntry,'NEUTRAL');check(store.balance.runtimeRevision(fresh)===2&&Object.values(newQuote.items).reduce((n,v)=>n+v,0)===(material.base+11)*2&&newQuote.xp===xp.base+20,'the next domain entry uses the current material and XP settings');
 const restoration=store.balance.changes(next,api.emptyConfig());check(restoration.some(c=>c.path==='growth/domains/'+id+'/materialQuantity'&&c.after===material.base&&c.resetToDefault),'growth rollback shows the concrete restored baseline');store.balance.rollback({expectedRevision:2,targetRevision:0,note:'기본 수치 복원'},'QA','local');const reset=store.runtimeFactory(DB,clone(beforeEntry),true),resetEntry=reset.growthDomainEntries().find(d=>d.id===id),resetQuote=reset.growthDomainRewards(resetEntry,'NEUTRAL');check(store.balance.currentRevision()===3&&Object.values(resetQuote.items).reduce((n,v)=>n+v,0)===material.base*2&&resetQuote.xp===xp.base,'rollback restores future domain rewards as a new revision');check(store.balance.profile(1).config.growth.domains[id].materialQuantity===material.base+7,'growth history remains immutable after rollback');
 console.log(JSON.stringify({ok:true,checks,domain:id,categories:['growth catalog and readable preview','invalid growth identifier','actual ascension material and Mora payment','actual talent book and Mora payment','native domain entry and double materials','saved battle profile and victory settlement','future domain current profile','growth rollback']}));
}finally{store.close();}
