'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),db=JSON.parse(fs.readFileSync(path.join(root,'content/db.json')));let now=1900000000000;
const ctx=vm.createContext({console,Date:class extends Date{static now(){return now;}}});
for(const [,file]of fs.readFileSync(path.join(root,'source/index.html'),'utf8').matchAll(/<script src="(runtime[^"]*\.js)"/g))vm.runInContext(fs.readFileSync(path.join(root,'source',file),'utf8'),ctx,{filename:file});
const Runtime=ctx.CRPGRuntime.Runtime,copy=x=>JSON.parse(JSON.stringify(x));ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db)});
const results=[];let id=0;
function fresh(map='MAP_MOND_PLAINS'){const r=new Runtime(db);r.newGame({name:'검증',route:'ROUTE_TRAVELER',seed:74219,saveId:'ADVENTURE-'+(++id)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,STORY_MENU_POLICY:''});r.prepareStory();return r;}
function reject(r,type,a={}){const before=r.serialize();assert.throws(()=>r.action(type,a));assert.equal(r.serialize(),before);}
function test(name,fn){try{fn();results.push({name,ok:true});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name+' '+e.stack);}}
function guild(r){r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';const entry=r.placeEntries().find(e=>e.entity==='NPC_MOND_KATHERYNE');r.action('PLACE_ENTER',{place:entry.id});}
function mine(r){r.action('LIFE_START',{kind:'MINE'});const job=r.s.lifeJob.id;now+=10000;r.action('LIFE_FINISH',{job});}
test('ordinary defeat blocks world actions and survives load before explicit recovery',()=>{let r=fresh();r.startBattle('EG_MOND_SLIME_SMALL','RANDOM');r.s.runtime.actors.filter(a=>a.side==='ALLY').forEach(a=>a.hp=0);r.finishBattle(false);assert.equal(r.playPhase(),'DOWNED');for(const type of ['WAIT','MOVE','LIFE_START','PLACE_ENTER'])reject(r,type,{minutes:60,kind:'MINE'});r=new Runtime(db,JSON.parse(r.serialize()));assert.equal(r.playPhase(),'DOWNED');reject(r,'RECOVER');now+=60000;r.action('RECOVER');assert.equal(r.s.global.CURRENT_MAP_ID,'MAP_MOND_CITY');assert.equal(r.s.global.PLAYER_HP_CURRENT,r.s.global.PLAYER_HP_MAX);assert.equal(r.s.global.WORLD_TIME,'09:00');assert.equal(r.playPhase(),'FREE');});
test('legacy HP zero save and protagonist down after victory cannot roam',()=>{let r=fresh();r.s.global.PLAYER_HP_CURRENT=0;r=new Runtime(db,JSON.parse(r.serialize()));assert.equal(r.playPhase(),'DOWNED');reject(r,'WAIT',{minutes:60});r.action('RECOVER');assert.ok(r.s.global.PLAYER_HP_CURRENT>0);});
test('story defeat keeps checkpoint retry instead of permitting recovery bypass',()=>{const r=fresh();r.s.global.PLAYER_HP_CURRENT=0;r.s.storyRecovery={node:'test'};assert.equal(r.playPhase(),'RECOVERY');reject(r,'RECOVER');reject(r,'MOVE',{edge:'x'});});
test('rest requires a paid lodging facility in safe areas too',()=>{const r=fresh();reject(r,'REST');r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';r.s.global.PLAYER_HP_CURRENT=10;reject(r,'REST');assert.equal(r.s.global.PLAYER_HP_CURRENT,10);});
test('10 second work timer rejects early completion and navigation without consuming resources',()=>{const r=fresh('MAP_CRPG_MOND_QUARRY');r.action('LIFE_START',{kind:'MINE'});const job=copy(r.s.lifeJob);assert.equal(r.playPhase(),'LIFE');reject(r,'LIFE_FINISH',{job:job.id});reject(r,'WAIT',{minutes:60});reject(r,'LIFE_START',{kind:'MINE'});reject(r,'MOVE',{edge:'x'});assert.equal(r.lifeEntries()[0].remaining,6);now+=9999;reject(r,'LIFE_FINISH',{job:job.id});now++;r.action('LIFE_FINISH',{job:job.id});assert.equal(r.lifeEntries()[0].remaining,5);assert.equal(r.s.global.WORLD_TIME,'08:10');reject(r,'LIFE_FINISH',{job:job.id});});
test('saved work resumes once and cancelling grants no item or extra use',()=>{let r=fresh('MAP_CRPG_MOND_QUARRY');r.action('LIFE_START',{kind:'MINE'});r=new Runtime(db,JSON.parse(r.serialize()));const job=r.s.lifeJob.id;now+=10000;r.action('LIFE_FINISH',{job});const inventory=copy(r.s.inventory);r.action('LIFE_START',{kind:'MINE'});r.action('LIFE_CANCEL');assert.deepEqual(copy(r.s.inventory),inventory);assert.equal(r.lifeEntries()[0].remaining,5);});
test('daily quotas are local and reset on next game day, including loading after midnight',()=>{let r=fresh('MAP_CRPG_MOND_QUARRY');for(let i=0;i<6;i++)mine(r);assert.equal(r.lifeEntries()[0].remaining,0);reject(r,'LIFE_START',{kind:'MINE'});r.s.global.CURRENT_MAP_ID='MAP_DRAGONSPINE';assert.equal(r.lifeEntries()[0].remaining,6);r.s.global.CURRENT_MAP_ID='MAP_CRPG_MOND_QUARRY';r.s.global.WORLD_TIME='23:50';r.s.global.ENCOUNTER_COOLDOWN=1;r.action('WAIT',{minutes:60});r=new Runtime(db,JSON.parse(r.serialize()));assert.equal(r.s.global.WORLD_DAY,2);assert.equal(r.lifeEntries()[0].remaining,6);});
test('ore intervals are exactly iron65 white30 crystal5 with one unit per successful work',()=>{for(const [roll,item]of [[0,'ORE_IRON'],[.64999,'ORE_IRON'],[.65,'ORE_WHITE_IRON'],[.94999,'ORE_WHITE_IRON'],[.95,'ORE_CRYSTAL'],[.99999,'ORE_CRYSTAL']]){const r=fresh('MAP_CRPG_MOND_QUARRY');r.random=()=>roll;mine(r);assert.equal(r.itemCount(item),1);}});
test('unsupported/safe zones deny mining; daily save records reject tampering',()=>{const r=fresh('MAP_MOND_CITY');reject(r,'LIFE_START',{kind:'MINE'});const s=JSON.parse(r.serialize());s.lifeResources={'MAP_MOND_PLAINS:MINE':{day:1,used:7}};assert.throws(()=>new Runtime(db,s));});
test('waiting rolls once in hostile zones and never in safe zones, respects cooldown',()=>{const r=fresh();r.s.global.ENCOUNTER_COOLDOWN=0;let rolls=0;r.die=()=>{rolls++;return 100;};r.action('WAIT',{minutes:60});assert.equal(rolls,1);assert.ok(!r.s.runtime);r.s.global.ENCOUNTER_COOLDOWN=1;r.action('WAIT',{minutes:60});assert.equal(rolls,1);r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';r.action('WAIT',{minutes:60});assert.equal(rolls,1);});
test('low waiting roll creates an opening, high roll and cooldown do not autoattack',()=>{const r=fresh();r.s.global.ENCOUNTER_COOLDOWN=0;r.die=()=>1;r.action('WAIT',{minutes:60});assert.equal(r.s.runtime.origin,'RANDOM');assert.equal(r.s.runtime.opening.state,'PENDING');assert.equal(r.s.global.PLAYER_HP_CURRENT,r.s.global.PLAYER_HP_MAX);});
test('commissions require actual guild acceptance then persist across remote objectives',()=>{const r=fresh(),qid='Q_MOND_EXP_PLAINS_CART';reject(r,'COMMISSION_ACCEPT',{quest:qid});reject(r,'QUEST_CHOICE',{quest:qid,choice:'careful'});guild(r);r.action('COMMISSION_ACCEPT',{quest:qid});reject(r,'COMMISSION_ACCEPT',{quest:qid});r.action('PLACE_LEAVE');assert.ok(r.commissionEntries().find(q=>q.row[0]===qid).accepted);r.s.global.CURRENT_MAP_ID='MAP_MOND_PLAINS';r.action('QUEST_CHOICE',{quest:qid,choice:'careful'});const before=r.s.global.MORA;reject(r,'CLAIM_QUEST',{quest:qid,equipment:'EQ_SWORD_FAVONIUS'});r.action('CLAIM_QUEST',{quest:qid});assert.ok(r.s.global.MORA>before);assert.equal(r.s.global.SCREEN_MODE,'LOCATION');reject(r,'CLAIM_QUEST',{quest:qid});});
test('already active legacy commissions retain progress without repeated guild acceptance',()=>{const r=fresh(),qid='Q_MOND_EXP_PLAINS_CART';r.s.quests[qid]={state:'진행중',attempts:1,node:'INVESTIGATE',claimed:false};r.action('QUEST_CHOICE',{quest:qid,choice:'careful'});assert.equal(r.s.quests[qid].node,'READY_TO_CLAIM');});
test('imported life work cannot bypass story locks, and downed read menus respect them',()=>{const r=fresh('MAP_CRPG_MOND_QUARRY');r.action('LIFE_START',{kind:'MINE'});const s=JSON.parse(r.serialize());s.global.STORY_MENU_POLICY='SAVE_LOAD_ONLY';assert.throws(()=>new Runtime(db,s));const down=fresh();down.s.global.PLAYER_HP_CURRENT=0;down.s.global.STORY_MENU_POLICY='SAVE_LOAD_ONLY';reject(down,'MENU',{screen:'QUEST'});down.action('RECOVER');assert.ok(down.s.global.PLAYER_HP_CURRENT>0);assert.equal(down.playPhase(),'STORY_LOCKED');});
const report={total:results.length,passed:results.filter(x=>x.ok).length,results};fs.writeFileSync(path.join(root,'reports/adventure-tests.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({total:report.total,passed:report.passed}));process.exitCode=report.passed===report.total?0:1;
