'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),ctx=vm.createContext({console}),results=[];
const modules=['runtime.js','runtime_extensions.js','runtime_story.js','runtime_nodes.js','runtime_events.js','runtime_relationships.js','runtime_combat.js','runtime_mond_cards.js','runtime_economy.js','runtime_passives.js','runtime_rules.js'];
for(const name of modules)vm.runInContext(fs.readFileSync(path.join(base,'source',name),'utf8'),ctx,{filename:name});
vm.runInContext(fs.readFileSync(path.join(base,'source/runtime_andrius.js'),'utf8'),ctx,{filename:'research/runtime_andrius.js'});
for(const name of ['runtime_flow.js','save_adapter.js'])vm.runInContext(fs.readFileSync(path.join(base,'source',name),'utf8'),ctx,{filename:name});
const R=ctx.CRPGRuntime.Runtime,db=JSON.parse(fs.readFileSync(path.join(base,'content/db.json')));
function test(name,fn){try{fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.stack});}}
function fresh(){const r=new R(db);r.newGame({name:'보스 회귀 검증',route:'ROUTE_TRAVELER',seed:293144,saveId:'ANDRIUS-REGRESSION'});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'HUB',STORY_CURSOR_NODE_ID:'HUB',SCREEN_MODE:'LOCATION',STORY_MENU_POLICY:'FULL',PENDING_CHOICE_GROUP_ID:'',CURRENT_MAP_ID:'MAP_WOLF_ARENA',PLAYER_BASE_HP:100000});r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;return r;}
function fixture(count=1,fixed=true){const r=fresh();r.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});const b=r.s.runtime,a=b.actors.find(a=>a.source==='BOSS_ANDRIUS'),p=r.combatActor();
  Object.assign(a,{atk:100,def:0,crit:0,critDmg:0,hp:10000,maxHp:10000,hit:95,eva:0,statuses:[],shields:[],cooldowns:{},spd:1,turns:0,andrius:{phase:1,runResolved:false,phase3Resolved:false,rageStacks:0,lastRageRound:1,lastStormRound:0,runResolving:false}});
  Object.assign(p,{atk:100,def:0,crit:0,critDmg:0,hp:100000,maxHp:100000,hit:95,eva:0,resist:0,statuses:[],shields:[],auras:[],aura:null,guard:false,spd:100,position:{x:2,y:0}});
  b.actors=[p,a];for(let i=1;i<count;i++){const t=JSON.parse(JSON.stringify(p));Object.assign(t,{id:'MOND_TEST_'+i,source:['MOND_AMBER','MOND_NOELLE','MOND_BARBARA'][i-1],name:'대상'+i,control:'AI',position:{x:2,y:i},slot:i+1});b.actors.push(t);}
  a.position={x:3,y:0};Object.assign(b,{round:1,fields:[],log:[],order:[{id:p.id,score:100},{id:a.id,score:1}],cursor:0,phase:'WAIT_PLAYER',turnStarted:'1:'+p.id});
  r.s.global.COMBAT_ACTION_PHASE='WAIT_PLAYER';if(fixed){r.die=()=>50;r.random=()=>0.5;}
  return{r,b,a,p,targets:b.actors.filter(x=>x.side==='ALLY'),cast:id=>r.executeCard(a,r.andriusCard(id),p.id)};
}
test('all ten exact READY source scripts are supported; drift is rejected',()=>{const r=fresh();assert.equal(ctx.CRPGRuntime.andriusCapabilities.supported.length,10);for(const id of ctx.CRPGRuntime.andriusCapabilities.supported){const c=r.andriusCard(id);assert.equal(r.cardSupport(c),'');assert.notEqual(r.cardSupport({...c,script:c.script+';CHANGED'}),'');}});
test('public boss entry initializes authored Andrius passive and ordinary Dragonspine group initializes ice shield',()=>{const r=fresh();r.action('BOSS_ROUTE',{route:'BRT_ANDRIUS',entry:'DIRECT'});assert.equal(r.s.runtime.actors.find(a=>a.source==='BOSS_ANDRIUS').andrius.phase,1);const ice=fresh();ice.s.global.CURRENT_MAP_ID='MAP_DRAGONSPINE';ice.startBattle('EG_DRAGON_MITA','TEST');const a=ice.s.runtime.actors.find(x=>x.source==='MON_MITACHURL_ICE'),shield=a.shields.find(s=>s.source==='ECARD_MITA_ICE_SHIELD');assert.equal(shield.value,Math.round(a.maxHp*.30));const hp=a.hp,value=shield.value;ice.applyDamage(ice.combatActor(),a,100,{element:'불'});assert.equal(shield.value,value-150);assert.equal(a.hp,hp);});
test('ice charge uses source1.10 and CE020 slow, then rejects broken shield',()=>{const{r,a,p}=fixture();Object.assign(a,{source:'MON_MITACHURL_ICE',grade:'정예',level:5,andrius:undefined,mondIceShieldInitialized:false});r.initializeMondEnemy(a);const card=r.andriusCard('ECARD_MITA_ICE_CHARGE'),hp=p.hp;r.executeCard(a,card,p.id);assert.equal(hp-p.hp,110);assert(p.statuses.some(s=>s.id==='STATUS_SLOW'));assert.equal(a.cooldowns[card.id],2);a.shields=[];assert.notEqual(r.cardReason(a,card),'');assert.throws(()=>r.executeCard(a,card,p.id),e=>e.code==='ICE_SHIELD');});
test('Cryo/Anemo direct, reaction, aura and control immunity spend no hit RNG',()=>{const{r,a,p}=fixture();let rolls=0;r.die=()=>{rolls++;return50;};r.random=()=>{rolls++;return.5;};const hp=a.hp;assert.equal(r.damage(p,a,1,'CRYO'),false);assert.equal(r.damage(p,a,1,'바람'),false);assert.equal(r.applyDamage(p,a,300,{element:'얼음',sourceKind:'REACTION'}),0);r.applyCombatAura(p,a,'CRYO');assert.equal(r.applyCombatControl(p,a,'LIFT',{element:'ANEMO'}),false);assert.equal(a.hp,hp);assert.equal(r.auraList(a).length,0);assert.equal(a.statuses.length,0);assert.equal(rolls,0);});
test('round4 START rage precedes forced charge and repeated newRound does not stack rage again',()=>{const{r,b,a,p}=fixture();b.round=4;a.andrius.lastRageRound=3;const hp=p.hp;r.tickFields('START');assert(Math.abs(a.atk-110)<1e-10);assert.equal(a.andrius.phase,2);assert.equal(hp-p.hp,337);r.newRound();assert(Math.abs(a.atk-110)<1e-10);assert.equal(a.andrius.rageStacks,1);});
test('claw splash is60percent of final pre-shield primary, without double outgoing modifier',()=>{const{r,a,p,targets,cast}=fixture(2);r.addCombatStatus(a,'BOSS_CONTROL',1);r.addCombatStatus(p,'OMEN',2);const before=targets.map(t=>t.hp);cast('ECARD_ANDRIUS_CLAW');assert.equal(before[0]-targets[0].hp,129);assert.equal(before[1]-targets[1].hp,77);assert.equal(p.nextScorePenalty,10);assert.equal(targets[1].nextScorePenalty,10);});
test('nested Mona bubble damage does not overwrite claw primary capture',()=>{const{r,a,p,targets,cast}=fixture(2);r.addCombatStatus(p,'ILLUSORY_BUBBLE',1,{actor:a.id});const hp=targets[1].hp;cast('ECARD_ANDRIUS_CLAW');assert.equal(hp-targets[1].hp,98);});
test('sweep preserves1.05, pre-existing slow1.20 and applies new slow only through status roll',()=>{const{r,targets,cast}=fixture(2);r.addCombatStatus(targets[0],'STATUS_SLOW',1,{value:-10});const hp=targets.map(x=>x.hp);cast('ECARD_ANDRIUS_SWEEP');assert.equal(hp[0]-targets[0].hp,126);assert.equal(hp[1]-targets[1].hp,105);assert(targets[1].statuses.some(s=>s.id==='STATUS_SLOW'));});
test('leap chooses at most two controlled targets and preserves final1.25 modifier',()=>{const{r,targets,cast}=fixture(3);r.addCombatStatus(targets[0],'STATUS_SLOW',1,{value:-10});r.addCombatStatus(targets[1],'STATUS_FREEZE',1);const hp=targets.map(x=>x.hp);cast('ECARD_ANDRIUS_LEAP');assert.deepEqual(hp.map((n,i)=>n-targets[i].hp),[206,206,0]);});
test('one threshold crossing executes phase2 then3 once and restores their saved state',()=>{const{r,b,a}=fixture();a.hp=4500;assert.equal(r.resolveEnemyPhases(),true);assert.equal(a.andrius.phase,3);assert.equal(r.combatActionsPerTurn(a),2);assert.equal(r.resolveEnemyPhases(),false);for(const id of ['ECARD_ANDRIUS_RUN_PHASE','ECARD_ANDRIUS_PHASE3'])assert.equal(b.log.filter(e=>e.card===id&&e.cardName).length,1);const restored=new R(db,JSON.parse(r.serialize()));assert.equal(restored.s.runtime.actors.find(x=>x.source==='BOSS_ANDRIUS').andrius.phase,3);});
test('wind blade fires3 packets with max2per target and EVA debuff only next round',()=>{const{r,b,a,targets,cast}=fixture(2);Object.assign(a.andrius,{phase:3,runResolved:true,phase3Resolved:true});const hp=targets.map(x=>x.hp);cast('ECARD_ANDRIUS_WIND_BLADE');assert.deepEqual(hp.map((n,i)=>n-targets[i].hp),[150,75]);assert.equal(r.combatStat(targets[0],'eva'),0);b.round=2;assert.equal(r.combatStat(targets[0],'eva'),-10);b.round=3;assert.equal(r.combatStat(targets[0],'eva'),0);});
test('roar creates2R wolves; existing field refresh has immediate proc and END proc once',()=>{const{r,b,a,targets,cast}=fixture(2);a.hp=1900;Object.assign(a.andrius,{phase:3,runResolved:true,phase3Resolved:true,lastStormRound:1});let hp=targets.reduce((n,x)=>n+x.hp,0);cast('ECARD_ANDRIUS_ROAR');assert.equal(hp-targets.reduce((n,x)=>n+x.hp,0),270);const field=b.fields.find(f=>f.kind==='ANDRIUS_GHOST_WOLVES');assert.equal(field.rounds,2);hp=targets.reduce((n,x)=>n+x.hp,0);r.tickFields('END');assert.equal(hp-targets.reduce((n,x)=>n+x.hp,0),90);hp=targets.reduce((n,x)=>n+x.hp,0);r.tickFields('END');assert.equal(hp-targets.reduce((n,x)=>n+x.hp,0),0);b.round=3;a.andrius.lastStormRound=3;field.rounds=1;for(const t of targets){t.auras=[];t.aura=null;}a.cooldowns.ECARD_ANDRIUS_ROAR=0;hp=targets.reduce((n,x)=>n+x.hp,0);cast('ECARD_ANDRIUS_ROAR');assert.equal(hp-targets.reduce((n,x)=>n+x.hp,0),360);assert.equal(field.rounds,2);assert.equal(field.createdRound,3);});
test('run phase50percent reduction applies once to direct and independent reaction packets',()=>{const{r,a,p}=fixture();a.andrius.runResolving=true;let hp=a.hp;r.damage(p,a,1,'PHYSICAL',{sureHit:true,noCrit:true});assert.equal(hp-a.hp,50);hp=a.hp;r.applyDamage(p,a,100,{element:'물리',sourceKind:'REACTION'});assert.equal(hp-a.hp,50);});
test('public COMBAT phase3 executes two AI cards but advances owner turn and cooldown only once',()=>{const{r,b,a}=fixture();Object.assign(a.andrius,{phase:3,runResolved:true,phase3Resolved:true});a.hp=4500;Object.assign(a.cooldowns,{ECARD_ANDRIUS_WIND_BLADE:10,ECARD_ANDRIUS_LEAP:10,ECARD_ANDRIUS_SWEEP:10,SENTINEL:7});r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});const current=r.s.runtime,boss=current.actors.find(x=>x.source==='BOSS_ANDRIUS');assert.equal(boss.turns,1);assert.equal(boss.cooldowns.SENTINEL,6);assert.equal(current.log.filter(e=>e.card==='ECARD_ANDRIUS_CLAW'&&e.cardName).length,2);assert.equal(current.round,2);});
test('public actions and phase3 fields are identical after serialized resume',()=>{const{r,a}=fixture(1,false);a.hp=4500;r.resolveEnemyPhases();const saved=new R(db,JSON.parse(r.serialize()));for(let i=0;i<4;i++){assert.equal(JSON.stringify(r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'})),JSON.stringify(saved.action('COMBAT',{card:'PLAYER_BASIC_GUARD'})));assert.equal(r.serialize(),saved.serialize());}});
fs.writeFileSync(path.join(__dirname,'andrius-test-results.json'),JSON.stringify({modules,tests:results},null,2));console.log(JSON.stringify(results,null,2));if(results.some(t=>!t.ok))process.exitCode=1;
