'use strict';const assert=require('node:assert/strict'),{fresh,R,db,advance}=require('./helpers_v011.cjs');
function guild(r){r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';r.action('PLACE_ENTER',{place:'EVT_SCHEDULE_NPC_MOND_KATHERYNE',mode:'TALK'});}
// 0.14.12: 5★ companions (알베도·클레·모나) also need the Mond story cleared and six Anemoculi collected.
// 0.15.25: a chapter's end brings its 4★ (runtime_story_companions_v01525.js, tests/test_v01525.cjs); these flags are set by hand
// here, so the chapters count as handed out and the personal mission alone is what is checked (it never joins).
function fiveStarReady(r){r.s.storyCompanions={version:1,steps:{AMBER:true,MOND_START:true,MOND_END:true},joined:{}};r.s.flags.FLAG_ISK_M05_CLEAR=true;if(r.s.global.PLAYER_LEVEL_STATE<10){r.s.global.PLAYER_LEVEL_STATE=10;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;}r.s.flags.FLAG_TRV_MON_CH2_CLEAR=true;const e=r.ensureExplorationState();for(const p of require('./helpers_v011.cjs').c.CRPGWorldContent.oculi.slice(0,6)){e.visitedMaps[p.map]=true;e.oculi[p.id]={map:p.map,day:1,action:r.s.global.SAVE_ID+':1'};r.giveItem('KEY_CRPG_ANEMOCULUS',1);}}
// Both stuck commissions, including wait jobs, guild handoff, and one-time claims.
let r=fresh();guild(r);const letters='Q_CRPG_MOND_EXP_BRIDGE_PARCEL';r.action('COMMISSION_ACCEPT',{quest:letters});r.action('PLACE_LEAVE');for(let n=0;n<2;n++){r.action('WORLD_WORK_START',{kind:'COMMISSION',quest:letters});assert.throws(()=>r.action('WORLD_WORK_FINISH',{job:r.s.worldJob.id}));advance(20000);r.action('WORLD_WORK_FINISH',{job:r.s.worldJob.id});r=new R(db,JSON.parse(r.serialize()));}assert(r.letterStage().requiresPlace);assert.throws(()=>r.action('WORLD_WORK_START',{kind:'COMMISSION',quest:letters}));guild(r);r.action('WORLD_WORK_START',{kind:'COMMISSION',quest:letters});r.action('CLAIM_QUEST',{quest:letters});assert(r.s.quests[letters].claimed);
const supply='Q_MOND_XP_SUPPLY';r.action('COMMISSION_ACCEPT',{quest:supply});assert(r.commissionFieldEntries().some(x=>x.row[0]===supply));r.action('QUEST_CHOICE',{quest:supply,choice:'submit'});const mora=r.s.global.MORA;r.action('CLAIM_QUEST',{quest:supply});assert.equal(r.s.global.MORA,mora+100);assert.throws(()=>r.action('CLAIM_QUEST',{quest:supply}));console.log('PASS mail search/sort/delivery and beginner supply through native actions');
// Each formerly abbreviated legend: acceptance cost, branch A/B, saved middle, completion and opt-in join.
const ids=['ALBEDO','BARBARA','BENNETT','DIONA','DAHLIA','KAEYA','KLEE','MIKA','MONA','NOELLE','FISCHL','LISA','RAZOR','ROSARIA','SUCROSE'];
for(const id of ids)for(const branch of ['A','B']){let r=fresh('MAP_MOND_CITY','ROUTE_ISEKAI'),key='LEG_ISK_MOND_'+id;const d=r.storyDefinition(key);r.s.flags.FLAG_ISK_MON_PROLOGUE_CLEAR=true;fiveStarReady(r);Object.assign(r.s.global,{MORA:100000,PLAYER_LEVEL_STATE:20,PLAYER_BASE_HP:100000,PLAYER_BASE_ATK:10000});r.s.ascensions.PLAYER_CUSTOM=1;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;for(const [item,n]of Object.entries(JSON.parse(d.COST_ITEMS_JSON||'{}')))r.giveItem(item,n);const place=r.legendIntroductionPlaces(d)[0];r.s.global.CURRENT_MAP_ID=place.maps[0];r.action('PLACE_ENTER',{place:place.id,mode:place.modes[0]});r.action('LEGEND_REGISTER',{quest:key});r.action('PLACE_LEAVE');r.action('LEGEND_ENTER',{quest:key});let decisions=0,first=null;for(let n=0;r.s.storyContext&&n<200;n++){if(r.s.runtime){if(r.s.runtime.opening?.state==='PENDING')r.action('COMBAT_BEGIN');else{const e=r.s.runtime.actors.find(x=>x.side==='ENEMY'&&x.hp>0);r.action('COMBAT',{card:'PLAYER_BASIC_ATTACK',target:e.id});}continue;}if(r.s.storyJourney){const j=r.s.storyJourney;if(j.scripted)r.action('STORY_SCRIPTED_TRAVEL');else if(r.s.global.CURRENT_MAP_ID===j.target)r.action('JOURNEY_RESUME');else{const path=r.navigationRoute(j.target);assert(path?.edges.length,j.target);r.action('MOVE',{edge:path.edges[0][0]});}continue;}if(r.s.storyBreak){r.action('JOURNEY_RESUME');continue;}const choices=r.storyChoices(),field=x=>/_V143_FIELD_\d+[AB]$/.test(x[4]);if(choices.length){const c=choices.find(x=>field(x)&&x[4].endsWith(branch))||choices.find(x=>x[4].endsWith('_PREP_ACCEPT'))||choices.find(x=>x[4].endsWith('_JOIN_ACCEPT'))||choices[0];if(field(c))decisions++;r.action('STORY_CHOICE',{node:c[4]});}else{const node=r.storyNode();if(!first&&node[5]==='DIALOGUE')first=node;r.action('STORY_NEXT',{node:node[4]});}if(n===7)r=new R(db,JSON.parse(r.serialize()));}assert.equal(decisions,1,id);assert(first&&first[6]===d.PROFILE_ID&&/_V143_FIRST_/.test(first[4]),id+' greets on a first meeting');assert(r.storyDone(d.QUEST_ID),id);assert.equal(JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON)[d.CHAR_ID].state,'ELIGIBLE',id);assert(r.s.storyCostReceipts[d.QUEST_ID]);}
console.log('PASS all 15 rewritten personal quests × 2 choice paths, first-meeting greeting, save/reload, original cost and recruitment');
// v0.14.3: a save paused inside the older incident nodes still reaches the check, completion and join.
for(const id of ['BARBARA','KLEE']){let r=fresh('MAP_MOND_CITY','ROUTE_ISEKAI'),key='LEG_ISK_MOND_'+id;const d=r.storyDefinition(key);r.s.flags.FLAG_ISK_MON_PROLOGUE_CLEAR=true;fiveStarReady(r);r.s.global.MORA=100000;for(const [item,n]of Object.entries(JSON.parse(d.COST_ITEMS_JSON||'{}')))r.giveItem(item,n);const place=r.legendIntroductionPlaces(d)[0];r.s.global.CURRENT_MAP_ID=place.maps[0];r.action('PLACE_ENTER',{place:place.id,mode:place.modes[0]});r.action('LEGEND_REGISTER',{quest:key});r.action('PLACE_LEAVE');r.action('LEGEND_ENTER',{quest:key});for(let n=0;r.storyActiveNodeId()!==key+'_WORK'&&!String(r.storyActiveNodeId()).includes('_V143_FIELD')&&!r.s.storyJourney&&n<60;n++){const c=r.storyChoices();if(c.length)r.action('STORY_CHOICE',{node:(c.find(x=>x[4].endsWith('_PREP_ACCEPT'))||c[0])[4]});else r.action('STORY_NEXT',{node:r.storyNode()[4]});}assert(r.s.storyCostReceipts[d.QUEST_ID],id+' paid');delete r.s.storyJourney;r.s.storyContext.node=key+'_CRISIS';r.s.global.CURRENT_MAP_ID=r.storyIndex().nodes.get('ROUTE_ISEKAI:'+key+'_CRISIS')[8];r=new R(db,JSON.parse(r.serialize()));r.prepareStory();for(let n=0;r.s.storyContext&&n<80;n++){if(r.s.storyJourney){const j=r.s.storyJourney;if(r.s.global.CURRENT_MAP_ID===j.target)r.action('JOURNEY_RESUME');else{const path=r.navigationRoute(j.target);r.action('MOVE',{edge:path.edges[0][0]});}continue;}const c=r.storyChoices();if(c.length)r.action('STORY_CHOICE',{node:(c.find(x=>x[4].endsWith('_JOIN_ACCEPT'))||c[0])[4]});else r.action('STORY_NEXT',{node:r.storyNode()[4]});}assert(r.storyDone(d.QUEST_ID),id+' legacy save finishes');assert.equal(JSON.parse(r.s.global.COMPANION_ELIGIBILITY_JSON)[d.CHAR_ID].state,'ELIGIBLE',id);}
console.log('PASS saves paused inside the older incident nodes finish and recruit');
