'use strict';
const assert=require('node:assert/strict');
const {R,db,c}=require('./helpers_v011.cjs');
const {setup,G,PLAYER}=require('../tools/audit_balance_v01522.cjs');
const {REFERENCE_TEAM}=require('../tools/audit_balance_v0161.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));let checks=0;
function check(name,run){run();checks++;console.log('PASS '+name);}
function prepare(domain='LIANSHAN_FORMULA:60',element='HYDRO',options={}){const spec=G.domains[domain.split(':')[0]],r=setup({level:55,route:'ROUTE_TRAVELER',team:REFERENCE_TEAM,map:spec.map,gear:'craft',enhance:6,talent:'mid',...options});r.s.domainDaily={day:G.dayOf(r.leyLineNow()),wins:3};r.s.global.PRNG_STATE=717;return {r,domain,element};}
function start(domain,element,options){const x=prepare(domain,element,options);x.r.action('DOMAIN_START',{domain:x.domain,element:x.element});return x.r;}
const enemyStats=r=>copy(r.s.runtime.actors.filter(a=>a.side==='ENEMY').map(a=>({source:a.source,hp:a.hp,maxHp:a.maxHp,atk:a.atk,def:a.def,spd:a.spd,shields:a.shields})));
check('new material starts carry fixed budgets; displayed opening HP is current',()=>{const x=prepare();const receipt=x.r.action('DOMAIN_START',{domain:x.domain,element:x.element}),b=x.r.s.runtime;assert.equal(b.growthDomain.materialBudgetVersion,1);assert.deepEqual(copy(b.materialBudget),{version:1,durability:48000,pressure:6920});for(const turn of receipt.result.order){const a=b.actors.find(a=>a.id===turn.id);assert.equal(turn.maxHp,a.maxHp);assert.equal(turn.hp,a.hp);}assert(b.actors.filter(a=>a.side==='ENEMY').reduce((n,a)=>n+a.maxHp,0)<182413);});
check('enemy budgets are independent of party size, route, rarity, level and missing HP',()=>{const snapshots=[];for(const options of [{level:55},{level:55,team:[]},{level:55,team:['MOND_DILUC','MOND_MONA','MOND_JEAN']},{level:60,route:'ROUTE_ISEKAI'}]){const {r,domain,element}=prepare(undefined,undefined,options);r.s.global.PLAYER_HP_CURRENT=Math.max(1,Math.round(r.s.global.PLAYER_HP_MAX*.2));r.action('DOMAIN_START',{domain,element});snapshots.push(enemyStats(r));}for(const stat of snapshots)assert.deepEqual(stat,snapshots[0]);});
check('native foes, DEF, SPD and enemy cards are retained; protection scales with its owner',()=>{const x=prepare(),native=x.r.tuneMaterialDomain;x.r.tuneMaterialDomain=function(b,d){delete d.materialBudgetVersion;};x.r.action('DOMAIN_START',{domain:x.domain,element:x.element});const before=enemyStats(x.r),y=start();const after=enemyStats(y);assert.deepEqual(after.map(a=>[a.source,a.def,a.spd]),before.map(a=>[a.source,a.def,a.spd]));for(const [i,a]of after.entries())for(const [j,s]of (a.shields||[]).entries()){const old=before[i].shields[j];assert.equal(s.source,old.source);assert(Math.abs(s.value/a.maxHp-old.value/before[i].maxHp)<.006);assert(Math.abs(s.initialValue/a.maxHp-old.initialValue/before[i].maxHp)<.006);}assert(y.s.runtime.actors.find(a=>a.source==='MON_ABYSS_MAGE_HYDRO').enemySkillsInitialized);x.r.tuneMaterialDomain=native;});
check('new material battles reload without HP, shield, order or reward changes',()=>{const r=start(),a=r.s.runtime.actors.find(a=>a.side==='ENEMY');a.hp=Math.floor(a.hp*.7);for(const shield of a.shields||[])shield.value=Math.floor(shield.value*.6);const before=copy(r.s.runtime),loaded=new R(db,copy(r.s));assert.deepEqual(copy(loaded.s.runtime),before);assert.deepEqual(copy(new R(db,copy(loaded.s)).s.runtime),before);});
check('old in-flight version-4 stats and 12-gem promises stay untouched',()=>{const x=prepare();x.r.tuneMaterialDomain=function(b,d){delete d.materialBudgetVersion;};x.r.action('DOMAIN_START',{domain:x.domain,element:x.element});x.r.s.runtime.growthDomain.ascensionRewardVersion=0;const before=copy(x.r.s.runtime),r=new R(db,copy(x.r.s));assert.deepEqual(copy(r.s.runtime),before);assert.equal(r.s.runtime.actors.filter(a=>a.side==='ENEMY').reduce((n,a)=>n+a.maxHp,0),182413);assert.equal(r.growthDomainRewards(r.s.runtime.growthDomain,'HYDRO').items.GROWTH_GEM_HYDRO,12);});
check('legacy versions 1, 2 and 3 do not acquire new material budgets',()=>{const plans=[{id:'TALENT:10',kind:'TALENT',level:10,region:'몬드',map:'MAP_MOND_CITY',element:'NEUTRAL',day:0},{version:2,id:'FORSAKEN_RIFT:2',key:'FORSAKEN_RIFT',stage:2,kind:'TALENT',level:10,region:'몬드',map:'MAP_MOND_SPRINGVALE',element:'NEUTRAL',day:0},{version:3,id:'FORSAKEN_RIFT:TALENT',key:'FORSAKEN_RIFT',name:'잊혀진 협곡',kind:'TALENT',level:5,region:'몬드',map:'MAP_MOND_SPRINGVALE',element:'NEUTRAL',day:0}];for(const d of plans){const {r}=prepare('FORSAKEN_RIFT:10');r._growthDomain=d;r.startBattle(r.growthDomainGroup(d,'NEUTRAL'),'DOMAIN:'+d.id);delete r._growthDomain;const before=copy(r.s.runtime);assert.equal(before.materialBudget,undefined);assert.deepEqual(copy(new R(db,copy(r.s)).s.runtime),before);}});
check('EXP and ordinary field stats do not receive material budgets',()=>{const exp=start('MIDSUMMER_COURTYARD:10');assert.equal(exp.s.runtime.materialBudget,undefined);assert.equal(exp.s.runtime.growthDomain.materialBudgetVersion,undefined);assert.equal(exp.s.runtime.actors.filter(a=>a.side==='ENEMY').reduce((n,a)=>n+a.maxHp,0),11200);const r=setup({level:55,team:REFERENCE_TEAM,map:'MAP_LIYUE_PLAINS'});r.startBattle('EG_LIYUE_HILI_ROCK','RANDOM');assert.equal(r.s.runtime.materialBudget,undefined);assert.equal(r.s.runtime.growthDomain,undefined);});
check('forged, missing and misplaced budget markers are rejected',()=>{const r=start();for(const mutate of [s=>s.runtime.growthDomain.materialBudgetVersion=2,s=>delete s.runtime.materialBudget,s=>s.runtime.materialBudget.pressure=1,s=>delete s.runtime.growthDomain.materialBudgetVersion,s=>s.runtime.materialBudget.version=2]){const saved=copy(r.s);mutate(saved);assert.throws(()=>new R(db,saved),/재료 비경/);}const exp=start('MIDSUMMER_COURTYARD:10');const saved=copy(exp.s);saved.runtime.growthDomain.materialBudgetVersion=1;assert.throws(()=>new R(db,saved),/재료 비경/);});
check('32 ascension gems, talent books and material XP are unchanged and paid once',()=>{for(const [domain,element,item,count]of [['LIANSHAN_FORMULA:60','HYDRO','GROWTH_GEM_HYDRO',32],['TAISHAN_MANSION:60','NEUTRAL','GROWTH_TALENT_LIYUE',12],['FORSAKEN_RIFT:20','NEUTRAL','GROWTH_TALENT_MOND',4]]){const r=start(domain,element),level=r.s.runtime.growthDomain.level;for(const a of r.s.runtime.actors.filter(a=>a.side==='ENEMY'))a.hp=0;const out=r.finishBattle(true);assert.equal(out.domain.items[item],count);assert.equal(out.xp,G.domainMaterialXp[level]);const saved=r.serialize();r.finishBattle(true);assert.equal(r.serialize(),saved);}});
console.log(JSON.stringify({checks,ok:true}));
