const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=require('path').resolve(__dirname,'..');
require(root+'/source/runtime_story.js');
const api=require('../source/runtime_combat.js');
const db=JSON.parse(fs.readFileSync(root+'/content/db.json'));
const {Runtime}=api,results=[];
function test(name,f){try{f();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.stack});}}
function fresh(route='ROUTE_ISEKAI'){const r=new Runtime(db);r.newGame({name:'검증용',route,seed:74219,saveId:'COMBAT-TEST'});return r;}
function bossFixture(branch='AA'){const r=fresh();const cfg=r.combatStoryConfig(`EG_ISK_M04_${branch}_DVALIN`);r.s.global.CURRENT_STORY_NODE_ID=cfg.node_id;r.s.global.STORY_CURSOR_NODE_ID=cfg.node_id;r.s.global.CURRENT_MAP_ID=cfg.map_id;r.s.quests.Q_ISK_MOND_02={state:'진행중',node:'ACTIVE',claimed:false};if(cfg.orb_action){r.giveItem(cfg.orb_action.requires_item,1);r.s.flags[cfg.orb_action.requires_flag]=true;}return r;}
function plainBossFixture(){const r=fresh();r.s.global.CURRENT_MAP_ID='MAP_STORMTERROR_LAIR';r.s.global.CURRENT_STORY_NODE_ID='HUB';r.s.global.STORY_CURSOR_NODE_ID='HUB';r.s.global.SCREEN_MODE='LOCATION';return r;}
function questFixture(){const r=fresh();const q=db['22_QUEST_DB'].find(row=>row[0]==='Q_MOND_EXP_PLAINS_CAMP');const p=JSON.parse(q[10]);r.s.global.CURRENT_MAP_ID=p.conditions.map_id;r.s.global.CURRENT_STORY_NODE_ID='HUB';r.s.global.STORY_CURSOR_NODE_ID='HUB';r.s.global.SCREEN_MODE='LOCATION';return {r,q,p};}
function publicQuestStart(r,p){const c=p.choices.find(c=>c.combat_group);return r.action('QUEST_CHOICE',{quest:'Q_MOND_EXP_PLAINS_CAMP',choice:c.id});}
function pickAttack(r){const c=r.combatCards().find(c=>!c.reason&&c.id==='PLAYER_BASIC_ATTACK');if(c)return {card:c.id,target:c.targets[0]?.id};return {card:'PLAYER_BASIC_GUARD'};}
function run(r,max=100){for(let i=0;r.s.runtime&&i<max;i++){if(r.s.runtime.interlude){r.resumeCombatInterlude();continue;}const orb=r.combatCards().find(c=>c.id==='ACT_ISK_ORB_PURIFY'&&!c.reason);r.action('COMBAT',orb?{card:orb.id,target:orb.targets[0].id}:pickAttack(r));}return r;}
test('public quest starts, legal targets shown, invalid target atomic rollback',()=>{const {r,p}=questFixture();publicQuestStart(r,p);assert(r.s.runtime);const c=r.combatCards().find(x=>x.id==='PLAYER_BASIC_ATTACK');assert(c.targets.length);const save=r.serialize();assert.throws(()=>r.action('COMBAT',{card:c.id,target:'FAKE'}));assert.equal(r.serialize(),save);});
test('same seed, completed public actions and serialization resume stay identical',()=>{const {r,p}=questFixture();publicQuestStart(r,p);r.action('COMBAT',pickAttack(r));const resumed=new Runtime(db,JSON.parse(r.serialize()));for(let i=0;i<40&&r.s.runtime;i++){const input=pickAttack(r);assert.deepEqual(r.action('COMBAT',input),resumed.action('COMBAT',input));assert.equal(r.serialize(),resumed.serialize());}assert(!r.s.runtime);});
test('legacy active battle is rejected without mutating the original save',()=>{const {r,p}=questFixture();publicQuestStart(r,p);const legacy=JSON.parse(r.serialize());delete legacy.runtime.combatVersion;const original=JSON.stringify(legacy);assert.throws(()=>new Runtime(db,legacy),e=>e.code==='COMBAT_VERSION');assert.equal(JSON.stringify(legacy),original);const outside=fresh();assert.equal(new Runtime(db,JSON.parse(outside.serialize())).s.runtime,null);});
test('duplicate action receipt does not repeat inventory/cost/turn',()=>{const {r,p}=questFixture();publicQuestStart(r,p);const input=pickAttack(r),a={id:r.s.global.SAVE_ID+':'+(r.s.global.LAST_COMMITTED_ACTION_SEQ+1),revision:r.s.global.SAVE_REVISION,type:'COMBAT',...input};const receipt=r.transact(a),saved=r.serialize();assert.deepEqual(r.transact(a),receipt);assert.equal(r.serialize(),saved);});
test('enemy dedicated axe/mage cards execute from public boss route',()=>{const r=plainBossFixture();r.s.global.PLAYER_LEVEL_STATE=20;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'GAUNTLET'});run(r);const log=r.s.lastCombatLog||r.s.runtime.log;assert(log.some(x=>x.card?.startsWith('ECARD_MITA_AXE')));});
test('Dvalin airborne denies ordinary melee; guard consumes action and never grounds boss',()=>{const r=plainBossFixture();r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});assert(r.s.runtime);assert(r.combatCards().find(c=>c.id==='PLAYER_BASIC_ATTACK').reason);assert(r.s.runtime.actors.find(a=>a.source==='BOSS_DVALIN').airborne);r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});assert(r.s.runtime?.actors.find(a=>a.source==='BOSS_DVALIN').airborne||!r.s.runtime);});
test('prepared levitator uses one shared charge and makes melee targets legal',()=>{const r=plainBossFixture();r.giveItem('TRPG_TACTICAL_LEVITATOR',1);r.s.preparedTools=['TRPG_TACTICAL_LEVITATOR'];r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});r.action('COMBAT',{card:'TOOL:TRPG_TACTICAL_LEVITATOR'});assert.equal(r.itemCount('TRPG_TACTICAL_LEVITATOR'),1);assert.equal(r.s.runtime.toolCharges.TRPG_TACTICAL_LEVITATOR,2);assert.equal(r.combatCards().find(c=>c.id==='PLAYER_BASIC_ATTACK').reason,'');});
test('combat potion consumes one item once, lock survives resume',()=>{const {r,p}=questFixture();r.giveItem('TRPG_HEALING_POTION',2);r.s.global.PLAYER_HP_CURRENT=500;publicQuestStart(r,p);const a=r.combatActor(),hp=a.hp;r.action('COMBAT',{card:'ITEM:TRPG_HEALING_POTION',target:a.id});assert.equal(r.itemCount('TRPG_HEALING_POTION'),1);assert(r.combatActor().statuses.some(s=>s.id==='STATUS_COMBAT_POTION_LOCK'));const resumed=new Runtime(db,JSON.parse(r.serialize()));assert(resumed.combatCards().find(c=>c.id==='ITEM:TRPG_HEALING_POTION').reason);const before=resumed.serialize();assert.throws(()=>resumed.action('COMBAT',{card:'ITEM:TRPG_HEALING_POTION'}));assert.equal(resumed.serialize(),before);});
test('CE159 requires explicit preparation and never writes guest ownership',()=>{const r=bossFixture();const before=JSON.stringify(r.s.chars.MOND_AMBER),party=JSON.stringify(r.s.party),owned=r.s.global.COMPANION_ELIGIBILITY_JSON;const node=r.storyNode();r.action('STORY_NEXT',{node:node[4]});assert(!r.s.runtime);assert(r.s.battlePreparation);r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:['MOND_AMBER','MOND_DILUC']});assert.equal(r.s.runtime.actors.filter(a=>a.side==='ALLY').length,3);assert.equal(JSON.stringify(r.s.party),party);assert.equal(r.s.global.COMPANION_ELIGIBILITY_JSON,owned);run(r);assert.equal(JSON.stringify(r.s.chars.MOND_AMBER),before);});
test('cooldowns decrease exactly once at each owner turn and use DB duration',()=>{const r=plainBossFixture();r.s.global.COMPANION_ELIGIBILITY_JSON=JSON.stringify({MOND_AMBER:{state:'JOINED'}});r.action('PARTY',{char:'MOND_AMBER',slot:2});r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});const a=r.combatActor('MOND_AMBER');assert.equal(a.cooldowns.MOND_AMBER_Q,3);r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});assert.equal(r.combatActor('MOND_AMBER').cooldowns.MOND_AMBER_Q,2);const save=new Runtime(db,JSON.parse(r.serialize()));assert.equal(save.combatActor('MOND_AMBER').cooldowns.MOND_AMBER_Q,2);});
test('terrain destruction defeats at fourth destruction independent of shield/HP',()=>{const r=plainBossFixture();r.s.global.PLAYER_BASE_HP=100000;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;r.action('BOSS_ROUTE',{route:'BRT_DVALIN',entry:'DIRECT'});for(let i=0;i<10&&r.s.runtime;i++)r.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});const result=JSON.parse(r.s.global.LAST_BATTLE_RESULT_JSON);assert.equal(result.victory,false);assert.equal(result.rounds,8);assert.equal(r.s.global.PLAYER_HP_CURRENT,0);});
test('orb action remains manual at subdued HP0 and crosses both interludes',()=>{const r=bossFixture('AB');r.s.global.PLAYER_BASE_ATK=100000;r.s.global.PLAYER_BASE_HP=100000;r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;r.startCombatInterlude=function(root,scene){this.s.global.SCREEN_MODE='COMBAT_INTERLUDE';};r.action('STORY_NEXT',{node:r.storyNode()[4]});r.action('COMBAT_PREPARE',{group:r.s.battlePreparation.group,companions:[]});r.action('COMBAT',{card:'ACT_ISK_M04_AERIAL_STEP'});r.action('COMBAT',pickAttack(r));assert(r.s.runtime.interlude);const phase1=r.s.runtime.interlude.scene_id;r.resumeCombatInterlude();assert(r.s.runtime.interlude);assert.notEqual(phase1,r.s.runtime.interlude.scene_id);r.resumeCombatInterlude();assert(r.s.runtime.subduedPending);assert(!r.s.runtime.orbChannel);assert(!r.s.flags.FLAG_ISK_M04_AB_BATTLE_WON);const saved=new Runtime(db,JSON.parse(r.serialize()));assert(saved.s.runtime.subduedPending);saved.action('COMBAT',{card:'ACT_ISK_ORB_PURIFY',target:saved.s.runtime.actors.find(a=>a.side==='ENEMY').id});assert(!saved.s.runtime);assert.equal(JSON.parse(saved.s.global.LAST_BATTLE_RESULT_JSON).result,'ALIVE_PURIFIED');assert.equal(saved.itemCount('KEY_ISK_MYSTERY_ORB'),1);assert(saved.s.flags.FLAG_ISK_M04_AB_BATTLE_WON);});
console.log(JSON.stringify(results,null,2));fs.writeFileSync(path.join(__dirname,'combat-test-results.json'),JSON.stringify(results,null,2));if(results.some(r=>!r.ok))process.exitCode=1;
