'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const root=path.resolve(__dirname,'..'),H=require('../tools/audit_food_lodging_v01617.cjs'),env=H.loadEnvironment(root),PLAYER='PLAYER_CUSTOM',cp=x=>JSON.parse(JSON.stringify(x));let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function setup(level=9){return H.setup(env,{levels:level});}
function hp(r,id,value){if(id===PLAYER)r.s.global.PLAYER_HP_CURRENT=value;else r.s.chars[id].hp=value;}
function stock(r,quote){for(const[id,n]of Object.entries(quote.cost.items))r.giveItem(id,n);}
test('living player and companion level gains preserve existing absolute HP deficit',()=>{for(const owner of [PLAYER,'MOND_AMBER']){const r=setup(),before=r.economyOwner(owner);hp(r,owner,before.maxHp-73);r.addXp(owner,r.growth(owner).next);const after=r.economyOwner(owner);assert.equal(r.growth(owner).level,10);assert.equal(after.maxHp-after.hp,73);assert.equal(r.growth(owner).xp,0);}});
test('KO player and companion remain KO when XP causes a level gain',()=>{for(const owner of [PLAYER,'MOND_AMBER']){const r=setup();hp(r,owner,0);r.addXp(owner,r.growth(owner).next);assert.equal(r.growth(owner).level,10);assert.equal(r.economyOwner(owner).hp,0);}});
test('multiple native level gains add only maximum-HP growth and keep the wound',()=>{for(const owner of [PLAYER,'MOND_AMBER']){const r=setup(5),before=r.economyOwner(owner);hp(r,owner,1);let xp=0;for(let l=5;l<9;l++)xp+=env.G.xpNext(l);r.addXp(owner,xp);const after=r.economyOwner(owner);assert.equal(r.growth(owner).level,9);assert.equal(after.maxHp-after.hp,before.maxHp-1);}});
test('non-level XP and capped XP never restore HP',()=>{for(const [level,amount]of [[5,1],[10,99999],[60,99999]])for(const owner of [PLAYER,'MOND_AMBER']){const r=setup(level);hp(r,owner,11);r.addXp(owner,amount);assert.equal(r.economyOwner(owner).hp,11);assert.equal(r.growth(owner).level,level);if(level!==5)assert.equal(r.growth(owner).xp,0);}});
test('healthy living characters remain healthy after native level growth',()=>{for(const owner of [PLAYER,'MOND_AMBER']){const r=setup();r.addXp(owner,r.growth(owner).next);const a=r.economyOwner(owner);assert.equal(a.hp,a.maxHp);}});
test('public XP books preserve KO and exact one-book consumption',()=>{const r=setup(),owner='MOND_AMBER';hp(r,owner,0);r.s.chars[owner].xp=r.growth(owner).next-1;r.giveItem('MAT_CHAR_EXP_WANDERER',1);const result=r.action('USE_ITEM',{item:'MAT_CHAR_EXP_WANDERER',owner,quantity:1}).result;assert.equal(result.xp,50);assert.equal(r.growth(owner).level,10);assert.equal(r.economyOwner(owner).hp,0);assert.equal(r.itemCount('MAT_CHAR_EXP_WANDERER'),0);});
test('public ascension preserves wounds or KO while charging each native quoted item and Mora',()=>{for(const owner of [PLAYER,'MOND_AMBER'])for(const dead of [false,true]){if(owner===PLAYER&&dead)continue;const r=setup(10),before=r.economyOwner(owner);hp(r,owner,dead?0:1);const quote=r.ascensionInfo(owner),wallet=r.s.global.MORA;stock(r,quote);r.action('CHAR_ASCEND',{owner});assert.equal(r.growth(owner).phase,quote.phase+1);assert.equal(r.growth(owner).level,10);const after=r.economyOwner(owner);assert.equal(after.hp===0,dead);if(!dead)assert.equal(after.maxHp-after.hp,before.maxHp-1);assert.equal(wallet-r.s.global.MORA,quote.cost.mora);for(const[id]of Object.entries(quote.cost.items))assert.equal(r.itemCount(id),0);}});
test('current book and ascension receipt replay and save reload never heal or charge again',()=>{for(const operation of ['BOOK','ASCEND']){const r=setup(operation==='BOOK'?9:10),owner='MOND_AMBER';hp(r,owner,0);if(operation==='BOOK'){r.s.chars[owner].xp=r.growth(owner).next-1;r.giveItem('MAT_CHAR_EXP_WANDERER',1);}else stock(r,r.ascensionInfo(owner));const intent={id:r.s.global.SAVE_ID+':'+(r.s.global.LAST_COMMITTED_ACTION_SEQ+1),revision:r.s.global.SAVE_REVISION,...(operation==='BOOK'?{type:'USE_ITEM',item:'MAT_CHAR_EXP_WANDERER',quantity:1,owner}:{type:'CHAR_ASCEND',owner})},receipt=cp(r.transact(intent)),save=r.serialize();assert.deepEqual(cp(r.transact(intent)),receipt);assert.equal(r.serialize(),save);const loaded=new env.R(env.db,JSON.parse(save));assert.deepEqual(cp(loaded.transact(intent)),receipt);assert.equal(loaded.economyOwner(owner).hp,0);assert.equal(loaded.serialize(),save);}});
test('six actually settled 0.16.20 growth saves and receipts keep their historical HP and replay exactly',()=>{const archived=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(root,'docs/data/full_balance_v01621/growth/historical_growth_saves_v01620.json.gz'))));assert.equal(archived.fixtures.length,6);for(const x of archived.fixtures){const r=new env.R(env.db,cp(x.save)),save=r.serialize(),before=r.economyOwner(x.owner);assert.deepEqual(cp(r.transact(x.intent)),x.receipt);assert.equal(r.serialize(),save);assert.equal(r.economyOwner(x.owner).hp,before.hp);}});
test('dead protagonist public book and ascension rejection remain atomic',()=>{for(const type of ['USE_ITEM','CHAR_ASCEND']){const r=setup(type==='USE_ITEM'?9:10);hp(r,PLAYER,0);if(type==='USE_ITEM')r.giveItem('MAT_CHAR_EXP_WANDERER',1);else stock(r,r.ascensionInfo());const save=r.serialize();assert.throws(()=>r.action(type,type==='USE_ITEM'?{item:'MAT_CHAR_EXP_WANDERER',quantity:1}:{owner:PLAYER}),e=>e.code==='ACTION_LOCK');assert.equal(r.serialize(),save);}});
console.log('Growth balance v0.16.21 regression: '+passed+' passed');
