'use strict';
// Read-only actual-runtime regression. Only the optional legacy comparison reads HEAD's node interpreter.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),cpProcess=require('node:child_process'),crypto=require('node:crypto');
const relativeRoot=path.resolve(__dirname,'..'),root=process.env.CRPG_ROOT||(fs.existsSync(path.join(relativeRoot,'source/index.html'))?relativeRoot:'/workspace/scratch/adc1ed75baeb/game'),out=process.env.CRPG_REPORT_DIR||path.join(root,'reports'),db=JSON.parse(fs.readFileSync(path.join(root,'content/db.json')));
const files=[...fs.readFileSync(path.join(root,'source/index.html'),'utf8').matchAll(/<script src="(runtime[^"]*\.js)"/g)].map(x=>x[1]);
const hashes={},baselineCommit='dcea691f88435d579be47ce21ef767905e06b65b';
function load(legacy=false){const ctx=vm.createContext({console});for(const file of files){const code=legacy&&file==='runtime_nodes.js'?cpProcess.execFileSync('git',['show',baselineCommit+':source/runtime_nodes.js'],{cwd:root,encoding:'utf8'}):fs.readFileSync(path.join(root,'source',file),'utf8');if(!legacy)hashes[file]=crypto.createHash('sha256').update(code).digest('hex');vm.runInContext(code,ctx,{filename:file});}ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});return ctx.CRPGRuntime.Runtime;}
const Base=load(true),Candidate=load(),cp=x=>JSON.parse(JSON.stringify(x)),report={source:path.join(root,'source'),baselineCommit,hashes,tests:[]};let actions=0;
function act(r,t,p={}){assert(++actions<1000,'bounded action budget');return r.action(t,p);}
function next(r){if(!['STORY','STORY_WAIT'].includes(r.s.global.SCREEN_MODE))act(r,'MENU',{screen:'STORY'});const choices=r.storyChoices();if(choices.length)return act(r,'STORY_CHOICE',{node:choices[0][4]});const n=r.storyNode();return act(r,n[5]==='INPUT_TEXT'?'STORY_NAME':'STORY_NEXT',n[5]==='INPUT_TEXT'?{name:r.s.global.PLAYER_NAME}:{node:n[4]});}
function reject(r,t,p={}){const before=r.serialize();assert.throws(()=>act(r,t,p));assert.equal(r.serialize(),before);}
function prep(r){let n=0;while(!r.storyChoices().some(x=>x[4].endsWith('_PREP_ACCEPT'))&&!r.storyChoices().some(x=>x[4].endsWith('_PREP_SHORTAGE'))){assert(n++<50);next(r);}return n;}
function exitPrep(r,choice){act(r,'STORY_CHOICE',{node:'LEG_ISK_MOND_AMBER_PREP_'+choice});assert.equal(r.storyActiveNodeId(),'LEG_ISK_MOND_AMBER_PREP_EXIT');next(r);assert(!r.s.storyContext);}
function record(name,fn){const result=fn();report.tests.push({name,passed:true,...result});}
let r=new Candidate(db);r.newGame({name:'재개검증',route:'ROUTE_ISEKAI',seed:74219,saveId:'V08-LEGEND-AUDIT'});
let opening=0;while(r.playPhase()!=='FREE'){assert(opening++<300);next(r);}
record('actual public opening reaches free point with fixed name',()=>({openingActions:opening,node:r.storyActiveNodeId(),playerName:r.s.global.PLAYER_NAME}));
act(r,'PLACE_ENTER',{place:'EVT_SCHEDULE_NPC_MOND_KATHERYNE',mode:'TALK'});act(r,'LEGEND_REGISTER',{quest:'LEG_ISK_MOND_AMBER'});act(r,'PLACE_LEAVE');
const fresh=cp(r.s),main=r.storyFrame();r=new Base(db,cp(fresh));act(r,'LEGEND_ENTER',{quest:'LEG_ISK_MOND_AMBER'});const first=r.storyActiveNodeId(),introActions=prep(r),atPrep=cp(r.s);exitPrep(r,'SHORTAGE');const legacyAfterShortage=cp(r.s);
record('baseline repeats completed introduction after shortage',()=>{act(r,'LEGEND_ENTER',{quest:'LEG_ISK_MOND_AMBER'});assert.equal(r.storyActiveNodeId(),first);return {firstNode:first,extraClicks:prep(r),initialClicks:introActions};});
record('new save still reads introduction and cannot skip by public parameters',()=>{const x=new Candidate(db,cp(fresh));act(x,'LEGEND_ENTER',{quest:'LEG_ISK_MOND_AMBER',node:'LEG_ISK_MOND_AMBER_PREP_ACCEPT'});assert.equal(x.storyActiveNodeId(),first);reject(x,'STORY_NEXT',{node:'LEG_ISK_MOND_AMBER_PREP_ACCEPT'});reject(x,'STORY_CHOICE',{node:'LEG_ISK_MOND_AMBER_PREP_ACCEPT'});reject(x,'STORY_NAME',{name:x.s.global.PLAYER_NAME});reject(x,'STORY_RETURN');return {node:first};});
record('candidate reads existing v0.7 resolved receipts and resumes preparation immediately',()=>{const x=new Candidate(db,cp(legacyAfterShortage));const before=cp({mora:x.s.global.MORA,inv:x.s.inventory,day:x.s.global.WORLD_DAY,time:x.s.global.WORLD_TIME,quests:x.s.quests,name:x.s.global.PLAYER_NAME});act(x,'LEGEND_ENTER',{quest:'LEG_ISK_MOND_AMBER'});assert.equal(x.storyActiveNodeId(),'CHOICE_GROUP:LEG_ISK_MOND_AMBER_G_PREP');assert.equal(x.s.global.STORY_CURSOR_NODE_ID,main.main);assert.deepEqual(cp({mora:x.s.global.MORA,inv:x.s.inventory,day:x.s.global.WORLD_DAY,time:x.s.global.WORLD_TIME,quests:x.s.quests,name:x.s.global.PLAYER_NAME}),before);assert(!x.s.storyCostReceipts?.Q_LEG_ISK_MOND_AMBER);return {node:x.storyActiveNodeId(),main:main.main};});
record('pending preparation save reload preserves exact choices',()=>{const x=new Candidate(db,cp(atPrep));assert.equal(x.storyActiveNodeId(),'CHOICE_GROUP:LEG_ISK_MOND_AMBER_G_PREP');assert(x.storyChoices().some(n=>n[4].endsWith('_PREP_SHORTAGE')));return {};});
record('material purchase, defer, resume, explicit accept, duplicate rejection and paid reload',()=>{let x=new Candidate(db,cp(legacyAfterShortage));const oldMora=x.s.global.MORA;act(x,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_GENERAL',mode:'SHOP'});act(x,'BUY',{stock:'STK_MOND_MAT_002',quantity:1});act(x,'PLACE_LEAVE');act(x,'LEGEND_ENTER',{quest:'LEG_ISK_MOND_AMBER'});assert.equal(x.storyActiveNodeId(),'CHOICE_GROUP:LEG_ISK_MOND_AMBER_G_PREP');exitPrep(x,'DEFER');assert.equal(x.itemCount('TRPG_STURDY_CLOTH'),1);assert.equal(x.s.global.MORA,oldMora-75);assert.equal(x.storyActiveNodeId(),main.main);act(x,'LEGEND_ENTER',{quest:'LEG_ISK_MOND_AMBER'});const a={type:'STORY_CHOICE',node:'LEG_ISK_MOND_AMBER_PREP_ACCEPT',id:x.s.global.SAVE_ID+':'+(x.s.global.LAST_COMMITTED_ACTION_SEQ+1),revision:x.s.global.SAVE_REVISION};const receipt=x.transact(a),after=x.serialize();assert.equal(x.serialize(),after);assert.deepEqual(cp(x.transact(a)),cp(receipt));assert.equal(x.serialize(),after);assert.equal(x.itemCount('TRPG_STURDY_CLOTH'),0);assert.equal(x.s.global.MORA,oldMora-75);assert.equal(x.storyActiveNodeId(),'LEG_ISK_MOND_AMBER_L2_INTRO_N01');reject(x,'STORY_CHOICE',{node:'LEG_ISK_MOND_AMBER_PREP_ACCEPT'});x=new Candidate(db,JSON.parse(x.serialize()));assert.equal(x.storyActiveNodeId(),'LEG_ISK_MOND_AMBER_L2_INTRO_N01');const paid=cp(x.s.storyCostReceipts.Q_LEG_ISK_MOND_AMBER);next(x);assert.deepEqual(cp(x.s.storyCostReceipts.Q_LEG_ISK_MOND_AMBER),paid);assert.equal(x.s.global.STORY_CURSOR_NODE_ID,main.main);return {paidNode:paid.node,itemCost:1,moraCost:75};});
record('all 24 legacy Mond legends retain their exact authored preparation predecessor',()=>{let count=0;for(const d of db['56_MOND_LEGEND_DB'].slice(1).filter(d=>d[4]==='몬드'&&(d[7]==='ROUTE_TRAVELER'||/^LEG_ISK_MOND_(DILUC|AMBER|JEAN|EULA)$/.test(d[0])))){const rows=db['57_MOND_STORY_SCENE_DB'].slice(1),a=rows.find(n=>n[0]===d[7]&&n[4]===d[12]);assert.equal(a[5],'CHOICE');assert.equal(a[12],'LEGEND_ACCEPT_AND_PAY:'+d[5]);assert.equal(rows.filter(n=>n[0]===d[7]&&n[1]===d[5]&&n[2]===d[0]&&n[18]==='ACTIVE'&&n[13]==='CHOICE_GROUP:'+a[14]).length,1);count++;}return {count};});
record('authored lodging costs 120 once, advances 8h across midnight, heals only active party and preserves story',()=>{const x=new Candidate(db,cp(fresh));act(x,'PARTY',{char:'MOND_AMBER',slot:2});x.s.global.PLAYER_HP_CURRENT=13;x.s.chars.MOND_AMBER.hp=11;x.s.chars.MOND_KAEYA.hp=7;x.s.global.WORLD_TIME='20:30';x.s.global.LAST_RECOVERY_MEAL_ITEM_ID='FOOD_TEA_BREAK_PANCAKE';const entry=x.placeEntries().find(e=>e.id==='EVT_SCHEDULE_MRC_MOND_INN');act(x,'PLACE_ENTER',{place:entry.id,mode:'SHOP'});const stock=x.placeStocks().find(s=>s.row[0]==='STK_INN_MOND');assert.equal(stock.row[5],120);const day=x.s.global.WORLD_DAY,mora=x.s.global.MORA,story=cp({main:x.s.global.STORY_CURSOR_NODE_ID,next:x.s.global.STORY_NEXT_PREPARED,flags:x.s.flags,quests:x.s.quests});const a={type:'BUY',stock:'STK_INN_MOND',quantity:1,id:x.s.global.SAVE_ID+':'+(x.s.global.LAST_COMMITTED_ACTION_SEQ+1),revision:x.s.global.SAVE_REVISION},receipt=x.transact(a),after=x.serialize();assert.deepEqual(cp(x.transact(a)),cp(receipt));assert.equal(x.serialize(),after);assert.equal(x.s.global.MORA,mora-120);assert.equal(x.s.global.WORLD_TIME,'04:30');assert.equal(x.s.global.WORLD_DAY,day+1);assert.equal(x.s.global.PLAYER_HP_CURRENT,x.s.global.PLAYER_HP_MAX);assert.equal(x.s.chars.MOND_AMBER.hp,x.character('MOND_AMBER').maxHp);assert.equal(x.s.chars.MOND_KAEYA.hp,7);assert.equal(x.s.global.LAST_RECOVERY_MEAL_ITEM_ID,'FOOD_TEA_BREAK_PANCAKE');assert.deepEqual(cp({main:x.s.global.STORY_CURSOR_NODE_ID,next:x.s.global.STORY_NEXT_PREPARED,flags:x.s.flags,quests:x.s.quests}),story);return {price:120,startTime:'20:30',endTime:'04:30',elapsedMinutes:480,inactiveHp:7};});
record('insufficient lodging funds, remote service, wrong merchant, invalid quantity and free REST roll back',()=>{const x=new Candidate(db,cp(fresh));reject(x,'REST');reject(x,'BUY',{stock:'STK_INN_MOND'});reject(x,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_LIYUE_INN',mode:'SHOP'});act(x,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_GENERAL',mode:'SHOP'});reject(x,'BUY',{stock:'STK_INN_MOND'});act(x,'PLACE_LEAVE');act(x,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_INN',mode:'SHOP'});x.s.global.MORA=1000;reject(x,'BUY',{stock:'STK_INN_MOND',quantity:2});x.s.global.MORA=119;reject(x,'BUY',{stock:'STK_INN_MOND',quantity:1});reject(x,'REST');return {};});
record('legacy inn visit reload remains usable with actual service dispatch',()=>{const old=new Base(db,cp(fresh));act(old,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_INN',mode:'SHOP'});const x=new Candidate(db,JSON.parse(old.serialize())),mora=x.s.global.MORA;assert.equal(x.currentPlace().merchant,'MRC_MOND_INN');act(x,'BUY',{stock:'STK_INN_MOND',quantity:1});assert.equal(x.s.global.MORA,mora-120);return {mode:x.currentPlace()?.mode};});
record('lodging and free recovery cannot bypass an uncompleted main story',()=>{const x=new Candidate(db);x.newGame({name:'잠금검증',route:'ROUTE_ISEKAI',seed:74219,saveId:'V08-LODGING-STORY'});for(const [t,p]of [['REST',{}],['RECOVER',{}],['PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_INN',mode:'SHOP'}],['BUY',{stock:'STK_INN_MOND',quantity:1}],['LEGEND_ENTER',{quest:'LEG_ISK_MOND_AMBER'}]])reject(x,t,p);return {phase:x.playPhase()};});
record('actual lodging renderer shows one service action and no item purchase grid',()=>{const ui=fs.readFileSync(path.join(root,'source/app_experience.js'),'utf8'),adventure=fs.readFileSync(path.join(root,'source/app_adventure.js'),'utf8'),x=new Candidate(db,cp(fresh));act(x,'PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_INN',mode:'SHOP'});const make=(tag,cls='',text='')=>({tag,cls,text,children:[],disabled:false,classList:{toggle(){}},append(...nodes){this.children.push(...nodes);}}),buttons=[];const context=vm.createContext({game:x,el:make,actionButton:(label,type,params={})=>{const b=make('button','',label);Object.assign(b,{type,params});buttons.push(b);return b;},itemPresenter:{itemDetail(){throw Error('Inn renderer invoked item detail');}}});vm.runInContext(ui.slice(ui.indexOf('function isInn('),ui.indexOf('drawLocation='))+ui.slice(ui.indexOf('shop=function('),ui.indexOf('function costBlock(')),context);const p=make('main');context.shop(p);const all=[];(function walk(n){all.push(n);for(const c of n.children)walk(c);})(p);const service=buttons.filter(b=>b.type==='BUY');assert.equal(service.length,1);assert.match(service[0].text,/숙박하기/);assert.deepEqual(cp(service[0].params),{stock:'STK_INN_MOND',quantity:1});assert(!all.some(n=>n.cls.includes('facility-stock')||n.text==='1개 구매'));assert(all.some(n=>n.text.includes('8시간')));assert.match(adventure,/숙박시설/);assert(!adventure.includes("'1시간 휴식 · 파티 HP 회복','REST'"));return {ui:service[0].text,underlyingAction:'BUY SERVICE_INN_REST_8H'};});
report.actions=actions;report.total=report.tests.length;report.passed=report.tests.filter(x=>x.passed).length;fs.writeFileSync(path.join(out,'legend-lodging-v08-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,hashes:undefined},null,2));
