import assert from 'node:assert/strict';
import {durableFixture} from './helpers_durable.mjs';
import {R,DB,ENGINE_FINGERPRINT} from '../server/generated/engine.mjs';
import {splitState,joinState,publicParts,applyParts,decompress} from '../server/state-parts.mjs';
globalThis.__splitState=splitState;
const f=durableFixture(),created=await f.start();assert.equal(created.status,200,JSON.stringify(created));assert(f.token.startsWith('v2.'));
const id=f.account.id,object=()=>f.get(id),read=()=>joinState(object().parts());
let calls=f.d1Calls;
const p={version:'0.14.5',engineVersion:ENGINE_FINGERPRINT,type:'MENU',params:{screen:'SYSTEM'},revision:0,requestId:crypto.randomUUID(),responseMode:'state-parts-v1'};
const first=await f.call('/game/action',p);assert.equal(first.status,200,JSON.stringify(first));assert(first.statePatch);assert.equal(f.d1Calls,calls,'warm action makes no D1 calls');
const merged=joinState(applyParts(splitState(created.state),first.statePatch));assert.deepEqual(merged,joinState(publicParts(object().parts())));
const replay=await f.call('/game/action',p);assert.equal(replay.replayed,true);assert.equal(replay.revision,1);assert.deepEqual(replay.result,first.result);
assert.equal((await f.call('/game/action',{...p,params:{screen:'STORY'}})).code,'REQUEST_ID_REUSED');
assert.equal((await f.call('/game/action',{...p,requestId:crypto.randomUUID()})).code,'REVISION_CONFLICT');
f.restart();assert.deepEqual((await f.call('/game/action',{...p,version:'old-version',engineVersion:'old-version'})).result,first.result);
const duplicate={...p,revision:1,requestId:crypto.randomUUID()};const concurrent=await Promise.all([f.call('/game/action',duplicate),f.call('/game/action',duplicate)]);assert(concurrent.every(x=>x.status===200));assert.equal(object().meta().revision,2);
const racers=await Promise.all([f.call('/game/action',{...p,revision:2,requestId:crypto.randomUUID()}),f.call('/game/action',{...p,revision:2,requestId:crypto.randomUUID()})]);assert.deepEqual(racers.map(x=>x.status).sort(),[200,409]);
const before=JSON.stringify(read()),revision=object().meta().revision;
f.handles.get(id).failSql='INSERT INTO receipts';assert.equal((await f.action('MENU',{screen:'STORY'})).status,500);f.handles.get(id).failSql=null;assert.equal(JSON.stringify(read()),before);assert.equal(object().meta().revision,revision);
const uncertain={...p,revision,requestId:crypto.randomUUID()};f.handles.get(id).failSync=true;const lost=await f.call('/game/action',uncertain);assert.equal(lost.status,500);assert.equal(lost.outcome,undefined);f.restart();assert.equal((await f.call('/game/action',uncertain)).replayed,true);assert.equal(object().meta().revision,revision+1);
assert.equal((await f.action('OPERATOR_DEBUG',{op:'mora',value:999999})).status,403);
assert.equal((await f.call('/me',undefined,f.token.slice(0,-1)+(f.token.endsWith('f')?'e':'f'))).status,401);
const runtime=new R(DB);runtime.newGame({name:'검증',seed:71});runtime.serverAdmin=true;runtime.action('OPERATOR_DEBUG',{op:'travel',map:'MAP_MOND_PLAINS'});f.seed(runtime.s);
const settledBefore=read();const wait=await f.action('WAIT',{minutes:1});assert.equal(wait.status,200,JSON.stringify(wait));assert.equal(wait.state.global.PRNG_STATE,1);
const undo=JSON.parse(object().rows('SELECT undo FROM backups WHERE revision=?',wait.revision-1)[0].undo);assert.deepEqual(joinState(applyParts(object().parts(),undo)),settledBefore);
const combat=new R(DB,read());combat.startBattle('EG_MOND_HILI_PATROL','RANDOM');f.seed(combat.s);assert.equal((await f.action('COMBAT_BEGIN',{battle:combat.s.runtime.id})).status,200);const hit=await f.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});assert.equal(hit.status,200,JSON.stringify(hit));assert((hit.state.runtime?.log||hit.state.lastCombatLog).some(x=>Object.hasOwn(x,'damage')));
await f.flush();const checkpoint=f.sql.prepare('SELECT * FROM game_checkpoints WHERE account_id=?').get(id);assert.equal(checkpoint.revision,object().meta().revision);assert(checkpoint.state_gzip.length>0);
assert.deepEqual((await decompress(checkpoint.state_gzip)).state,read());
assert.equal(Buffer.from(await crypto.subtle.digest('SHA-256',checkpoint.state_gzip)).toString('hex'),checkpoint.checksum);
assert.throws(()=>f.sql.prepare('INSERT INTO games VALUES(?,?,0,?,1,0)').run(id,'{}','legacy'),'legacy writer must be fenced');
// D1 projection failures do not block the next durable action and are retried by an alarm.
const batch=f.env.DB.batch;f.env.DB.batch=async()=>{throw Error('D1 offline');};await f.action('MENU',{screen:'SYSTEM'});await assert.rejects(f.flush());const offline=await f.action('MENU',{screen:'SYSTEM'});assert.equal(offline.status,200);f.env.DB.batch=batch;await f.flush();
f.sql.prepare('INSERT INTO sessions VALUES(?,?,?)').run('revoked-token-hash',id,Date.now()+600000);
object().sql.exec('INSERT INTO sessions VALUES(?,?,1)','revoked-token-hash',Date.now()+600000);
f.env.ADMIN_ACCOUNT_IDS=id;const saved=JSON.stringify(read()),rev=object().meta().revision;const drain=await f.call('/ops/storage/rollback',{accountId:id});assert.equal(drain.status,200,JSON.stringify(drain));assert.equal(drain.drained,true);assert.equal(f.sql.prepare('SELECT state FROM games WHERE account_id=?').get(id).state,saved);assert.equal(f.sql.prepare('SELECT revision FROM games WHERE account_id=?').get(id).revision,rev);
assert.equal(f.sql.prepare('SELECT * FROM sessions WHERE token_hash=?').get('revoked-token-hash'),undefined,'drain must finish a previously failed D1 logout');
const afterDrain=await f.call('/me');assert.equal(afterDrain.status,200,JSON.stringify(afterDrain));assert.equal(afterDrain.revision,rev);
console.log(JSON.stringify({ok:true,checks:['zero D1 warm actions','delta reconstruction','retry','collision','stale revision','restart','parallel duplicate','parallel different actions','SQLite rollback','lost acknowledgement','PRNG privacy','inverse backup','combat','gzip checkpoint','legacy fence','D1 outage','drain rollback']}));
