'use strict';
// Scope/save contracts only. Declared ownership, story access and ordinary gear
// are entry fixtures; no damage, RNG, enemy stats, victories or rewards are forced.
// The old engine is reconstructed from verified published blobs plus before-source
// overlays, or --baseline-root. Missing/mismatched proof is a hard failure.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const H=require('../tools/audit_protagonist_v01618.cjs'),ROOT=path.resolve(__dirname,'..'),copy=x=>JSON.parse(JSON.stringify(x));
const arg=k=>{const i=process.argv.indexOf(k);return i<0?undefined:process.argv[i+1];};
const BEFORE=path.resolve(arg('--before')||path.join(ROOT,'docs/data/balance_v01624/source_before'));
const MANIFEST=path.resolve(arg('--manifest')||path.join(BEFORE,'published_source_manifest.json'));
const BASELINE=arg('--baseline-root')?path.resolve(arg('--baseline-root')):null;
const output=arg('--out'),requireRecordedQa=process.argv.includes('--require-recorded-qa'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const blob=b=>crypto.createHash('sha1').update(Buffer.from('blob '+b.length+'\0')).update(b).digest('hex');
const NOW=1791615600000,FixedDate=class extends Date{constructor(...args){super(...(args.length?args:[NOW]));}static now(){return NOW;}};
const report={version:'0.16.24',scope:'Fresh public boss entry, baseline catalog and exact numeric override precedence; nonchallenge scopes and genuine 0.16.23 PENDING/WAIT_PLAYER saved-battle preservation. No fight difficulty, natural acquisition or full-campaign claim.',fixturePolicy:'One Traveler and three owned 4-star allies, equal native boss level/legal phase/max base talents, ordinary crafted gear +3 below Lv30 or +6 thereafter, base cap10 and no artifacts/exclusive weapons/boss material gear. Story/first-clear flags and initial Mora/HP are declared entry preparation. Old WAIT saves follow native COMBAT_BEGIN and one legal player skill; no forced victory or roll.',checks:[]};
function check(id,fn){try{const evidence=fn();report.checks.push({id,passed:true,evidence});console.log('PASS '+id);}catch(e){report.checks.push({id,passed:false,error:e.stack});console.error('FAIL '+id+' '+e.message);}}
function equal(a,b,label){assert.deepEqual(copy(a),copy(b),label);}
function oldFile(relative){if(BASELINE)return path.join(BASELINE,relative);const overlay=path.join(BEFORE,relative);return fs.existsSync(overlay)?overlay:path.join(ROOT,relative);}
let proof,oldEnv,env,specs,catalog,dbBefore;
const preparedFixtures=new WeakMap();
function load(old){const read=relative=>fs.readFileSync(old?oldFile(relative):path.join(ROOT,relative)),context=vm.createContext({console,Date:FixedDate,setTimeout,clearTimeout}),hash=crypto.createHash('sha256');
 const html=read('source/index.html').toString();for(const[,file]of html.matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)){const text=read('source/'+file).toString();hash.update(file);hash.update(text);vm.runInContext(text,context,{filename:(old?'0.16.23/':'0.16.24/')+file});}
 vm.runInContext(read('source/presentation.js').toString(),context,{filename:'presentation.js'});const rawDb=read('content/db.json');hash.update(rawDb);return{c:context,db:JSON.parse(rawDb),R:context.CRPGRuntime.Runtime,api:context.CRPGRuntime,root:ROOT,fingerprint:hash.digest('hex'),rawDbSHA256:sha(rawDb)};
}
function bossStats(actor){return{level:actor.level,hp:actor.maxHp,atk:actor.atk,def:actor.def,spd:actor.spd,hit:actor.hit,eva:actor.eva,resist:actor.resist};}
function battleBoss(runtime,spec){const boss=runtime.s.runtime?.actors.find(a=>a.side==='ENEMY'&&a.source===spec.source);assert(boss,'native battle contains '+spec.source);return boss;}
function makeSpecs(api){const field=Object.keys(api.fieldBosses.bosses).map(source=>({source,kind:'FIELD',level:api.growthRegionData.bosses[source],map:api.fieldBosses.bosses[source].map,group:api.fieldBosses.group(source),origin:'BOSS:'+api.fieldBosses.route(source)}));
 return [...field,...['BOSS_ANDRIUS','BOSS_DVALIN'].map(source=>({...api.enhancementConfig.bosses[source],source,kind:'MOND',level:api.growthRegionData.bosses[source],origin:'MATERIAL_CHALLENGE:'+source})),...Object.entries(api.liyueArtifactConfig.farm).map(([kind,f])=>({source:kind==='TARTAGLIA'?'BOSS_TARTAGLIA':'BOSS_AZHDAHA',kind:'LIYUE',farmKind:kind,level:api.growthRegionData.bosses[kind==='TARTAGLIA'?'BOSS_TARTAGLIA':'BOSS_AZHDAHA'],map:f.map,group:f.group,origin:'MATERIAL_CHALLENGE:'+f.key}))];
}
function prepare(e,spec){let fixtures=preparedFixtures.get(e);if(!fixtures){fixtures=new Map();preparedFixtures.set(e,fixtures);}if(fixtures.has(spec.source))return new e.R(e.db,copy(fixtures.get(spec.source)));const team=['MOND_AMBER','MOND_KAEYA','MOND_NOELLE'],r=H.setup(e,{level:spec.level,team,route:'ROUTE_TRAVELER',seed:717,map:spec.map,gear:'craft',enhance:spec.level<30?3:6,talent:10});
 for(const inv of r.s.inventory.filter(i=>i.equip)){inv.enhancementCap=10;if(!r.enhancementHasGain(inv))inv.enhance=0;assert(!/^EQ_EX_|^EQ_ARTIFACT_|^EQ_FB_/.test(inv.equip),'ordinary preparation only');}
 if(spec.kind==='MOND'){const flag=r.row('35_BOSS_ROUTE_DB',spec.route)[13];assert(flag,'native Mond clear flag');r.s.flags[flag]=true;}
 if(spec.kind==='LIYUE'&&spec.farmKind==='AZHDAHA'){const flag=r.row('35_BOSS_ROUTE_DB','BRT_AZHDAHA')[13];assert(flag,'native Azhdaha clear flag');r.s.flags[flag]=true;}
 r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;for(const id of team)r.s.chars[id].hp=r.character(id).maxHp;
 assert(r.s.party.filter(p=>p.active).length===4,'fixed four-member preparation');assert(!r.s.inventory.some(i=>/^MAT_FB_|^TRPG_BOSS_|^MAT_AZHDAHA_/.test(i.item||'')),'no injected boss materials');fixtures.set(spec.source,copy(r.s));return r;
}
function enter(r,spec){if(spec.kind==='FIELD'){const route=r.fieldBossCatalog().find(x=>x.id===spec.source).route;r.action('PLACE_ENTER',{place:'BOSS:'+route,mode:'BOSS'});r.action('BOSS_ROUTE',{route,entry:'DIRECT'});}else if(spec.kind==='MOND')r.action('MOND_MATERIAL_CHALLENGE',{boss:spec.source});else r.action('LIYUE_ARTIFACT_CHALLENGE',{kind:spec.farmKind});
 assert.equal(r.s.runtime?.origin,spec.origin,'actual public admission origin');assert.equal(r.s.runtime.opening.state,'PENDING');assert.equal(r.s.runtime.phase,'WAIT_PLAYER');assert(r.s.runtime.actors.every(a=>a.turns===0),'no turn execution during entry');return r;
}
function start(e,spec){return enter(prepare(e,spec),spec);}
function direct(e,spec,origin){const r=prepare(e,spec);r.startBattle(spec.group,origin,{confirmed:true,companions:['MOND_AMBER','MOND_KAEYA','MOND_NOELLE']});assert.equal(r.s.runtime?.origin,origin);return r;}
function mock(e,spec){const r=new e.R(e.db);r.installGrowthContent();const row=r.row('09_MONSTER_DB',spec.source),a={id:spec.source+'#scope',source:spec.source,side:'ENEMY',grade:row[3],hp:+row[6],maxHp:+row[6],atk:+row[7],def:+row[8],level:spec.level,spd:+row[19],hit:+row[20],eva:+row[21],resist:+row[22],shields:[],statuses:[],cooldowns:{}};
 if(spec.kind==='FIELD'){a.fb={};a.atk=Math.round(a.atk*(e.api.formationConfig.enemyAtk??1));}return{r,a};
}

check('genuine_published_baseline_and_qa_db_identity',()=>{proof=JSON.parse(fs.readFileSync(MANIFEST));assert.match(proof.commit,/^[a-f0-9]{40}$/);assert(Array.isArray(proof.entries)&&proof.entries.length>100,'full published source proof');let files=0;
 for(const entry of proof.entries){const at=entry.path.indexOf('/source/');if(at<0||entry.type!=='blob')continue;const relative=entry.path.slice(at+1),content=fs.readFileSync(oldFile(relative));assert.equal(blob(content),entry.sha,'published old blob: '+relative);files++;}
 assert(files>100);equal(fs.readFileSync(oldFile('source/index.html')).toString(),fs.readFileSync(path.join(ROOT,'source/index.html')).toString(),'unchanged engine load order');equal(fs.readFileSync(oldFile('source/presentation.js')).toString(),fs.readFileSync(path.join(ROOT,'source/presentation.js')).toString(),'unchanged presentation');
 oldEnv=load(true);env=load(false);assert.equal(oldEnv.rawDbSHA256,env.rawDbSHA256,'same actual DB for old/new engine comparison');if(requireRecordedQa){assert.equal(oldEnv.rawDbSHA256,proof.qaDbSHA256,'old recorded QA database fixture');assert.equal(env.rawDbSHA256,proof.qaDbSHA256,'current recorded QA database fixture');}equal(oldEnv.db,env.db,'same actual diagnostic DB, not production-authored equality');dbBefore=sha(JSON.stringify(env.db));report.baseline={commit:proof.commit,sourceFiles:files,fingerprint:oldEnv.fingerprint,dbSHA256:env.rawDbSHA256,recordedQADbSHA256:proof.qaDbSHA256,matchesRecordedQA:env.rawDbSHA256===proof.qaDbSHA256,requiresRecordedQA:requireRecordedQa,caveat:'Published source identity is verified. Actual old/new DB equality is required; recorded local QA DB identity is enforced only with --require-recorded-qa. This does not assert authored production DB equals the QA fixture.',mode:BASELINE?'full baseline root':'verified before-source overlay'};report.fingerprint=env.fingerprint;return report.baseline;
});
if(!oldEnv||!env){report.total=report.checks.length;report.failed=report.total;report.passed=0;if(output){fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');}process.exitCode=1;}
else{
 check('challenge_origin_and_profiles_contract',()=>{assert.equal(typeof env.api.growthV01522.bossChallengeOrigin,'function');specs=makeSpecs(env.api);assert.equal(specs.length,13);equal(specs.map(s=>s.source).sort(),makeSpecs(oldEnv.api).map(s=>s.source).sort(),'same thirteen boss species');const profiles=env.api.growthV01522.bossChallengeProfiles;assert(profiles&&typeof profiles==='object'&&!Array.isArray(profiles));assert(Object.keys(profiles).length>0,'selected candidate profiles must be present');
  for(const spec of specs)assert.equal(env.api.growthV01522.bossChallengeOrigin(spec.source),spec.origin,'registered origin '+spec.source);for(const[source,p]of Object.entries(profiles)){assert(specs.some(s=>s.source===source),'profile is existing repeat boss');assert(Number.isInteger(p.level)&&p.level>=1&&p.level<=60);for(const field of ['hpMultiplier','atkMultiplier','defMultiplier'])assert(Number.isFinite(p[field])&&p[field]>0,source+' '+field);}
  for(const source of ['MON_SLIME_PYRO','BOSS_OSIAL','BOSS_ISK_L03_GOLDEN','BOSS_ISK_L04_OSIAL','NOT_A_BOSS'])assert.equal(env.api.growthV01522.bossChallengeOrigin(source),'');const r=new env.R(env.db);r.installGrowthContent();catalog=env.api.adminBalance.catalog(r);report.profiles=copy(profiles);return{species:specs.map(s=>s.source),selected:Object.keys(profiles)};
 });
 if(specs&&catalog){
  for(const[ordinal,spec]of specs.entries()){
   check('public_entry_actual_catalog_and_profile:'+spec.source,()=>{const before=start(oldEnv,spec),current=start(env,spec),a=battleBoss(current,spec),old=battleBoss(before,spec),p=env.api.growthV01522.bossChallengeProfiles[spec.source],entry=catalog.enemies.find(x=>x.id===spec.source);assert(entry);equal(Object.fromEntries(entry.fields.map(f=>[f.key,f.base])),bossStats(a),'catalog equals public fresh repeat stats');
    const expected=bossStats(old);if(p){expected.hp=Math.max(1,Math.round(expected.hp*p.hpMultiplier));expected.atk=Math.round(expected.atk*p.atkMultiplier);expected.def=Math.round(expected.def*p.defMultiplier);assert.equal(a.bossChallengeRevision,1);}else assert.equal(a.bossChallengeRevision,undefined);equal(bossStats(a),expected,'selected multiplication only after shared growth');
    if(p)for(const shield of old.shields||[]){const changed=(a.shields||[]).find(s=>s.source===shield.source);assert(changed,'existing initial shield preserved');assert(Math.abs(changed.value-shield.value*a.maxHp/old.maxHp)<=2,'initial shield follows final boss HP within rounding');if(shield.initialValue)assert(Math.abs(changed.initialValue-shield.initialValue*a.maxHp/old.maxHp)<=2,'initial shield maximum follows final HP');}
    if(spec.kind==='FIELD'){assert.equal(before.s.runtime.fieldBoss.behaviorRevision,4);assert.equal(current.s.runtime.fieldBoss.behaviorRevision,5);assert.equal(current.s.runtime.dailyPressureRevision,undefined);}else{assert.equal(before.s.runtime.dailyPressureRevision,undefined);assert.equal(current.s.runtime.dailyPressureRevision,1);}assert(entry.baselineHint.includes('반복 도전'));return{origin:spec.origin,gearEnhancement:spec.level<30?3:6,before:bossStats(old),after:bossStats(a),initialShields:{before:copy(old.shields||[]),after:copy(a.shields||[])},challengeRevision:a.bossChallengeRevision??null,fieldBehavior:current.s.runtime.fieldBoss?.behaviorRevision??null};
   });
   for(const mode of ['STORY','EXPLICIT','WRONG_BOSS_ORIGIN'])check('excluded_'+mode+':'+spec.source,()=>{const origin=mode==='STORY'?'STORY:TRV_BOSS_SCOPE_BOUNDARY':mode==='EXPLICIT'?'EXPLICIT':specs[(ordinal+1)%specs.length].origin,old=direct(oldEnv,spec,origin),current=direct(env,spec,origin),a=battleBoss(current,spec);equal(bossStats(a),bossStats(battleBoss(old,spec)),'excluded origin retains old stats');equal(a.shields,battleBoss(old,spec).shields,'excluded initial shields');assert.equal(a.bossChallengeRevision,undefined);assert.equal(current.s.runtime.dailyPressureRevision,undefined);if(spec.kind==='FIELD')assert.equal(current.s.runtime.fieldBoss.behaviorRevision,4);return{origin,stats:bossStats(a)};});
   for(const flag of ['abyss','raid'])check('excluded_'+flag+'_growth_probe:'+spec.source,()=>{const old=mock(oldEnv,spec),current=mock(env,spec),oldBattle={actors:[old.a],origin:spec.origin,[flag]:{version:1}},newBattle={actors:[current.a],origin:spec.origin,[flag]:{version:1}};old.r.tuneGrowthEnemy(old.a,oldBattle,spec.level);current.r.tuneGrowthEnemy(current.a,newBattle,spec.level);equal(bossStats(current.a),bossStats(old.a),'existing '+flag+' growth scope unchanged');assert.equal(current.a.bossChallengeRevision,undefined);return{guard:flag,probe:'direct growth guard; not a raid/abyss admission or campaign'};});
   check('admin_exact_final_override:'+spec.source,()=>{const seed=prepare(env,spec),config=env.api.adminBalance.emptyConfig(),hp=654321+ordinal,atk=3210+ordinal,def=456+ordinal;config.enemies[spec.source]={hp,atk,def};const current=env.api.adminBalance.createRuntime(env.db,copy(seed.s),{revision:100+ordinal,config});enter(current,spec);const a=battleBoss(current,spec);equal([a.maxHp,a.hp,a.atk,a.def],[hp,hp,atk,def],'exact override beats candidate and growth');assert.equal(current.s.runtime.adminBalanceRevision,100+ordinal);return{hp,atk,def,revision:100+ordinal};});
   check('admin_level_only_keeps_challenge_curve:'+spec.source,()=>{const seed=prepare(env,spec),config=env.api.adminBalance.emptyConfig(),level=spec.level===60?59:spec.level+1;config.enemies[spec.source]={level};const current=env.api.adminBalance.createRuntime(env.db,copy(seed.s),{revision:200+ordinal,config});enter(current,spec);const a=battleBoss(current,spec),old=mock(oldEnv,spec);old.r.tuneGrowthEnemy(old.a,{actors:[old.a],origin:spec.origin},level);const expected=bossStats(old.a),p=env.api.growthV01522.bossChallengeProfiles[spec.source];if(p){expected.hp=Math.max(1,Math.round(expected.hp*p.hpMultiplier));expected.atk=Math.round(expected.atk*p.atkMultiplier);expected.def=Math.round(expected.def*p.defMultiplier);}equal(bossStats(a),expected,'level-only edit uses altered level curve plus selected candidate, not stale absolute anchor');return{level,stats:bossStats(a)};});
   for(const boundary of ['PENDING','WAIT_PLAYER'])check('genuine_v01623_save_preserved_'+boundary+':'+spec.source,()=>{const old=start(oldEnv,spec);if(boundary==='WAIT_PLAYER'){old.action('COMBAT_BEGIN');const wind=old.combatCards().find(c=>c.id==='SYS_MOND_WIND_ROUTE'&&!c.reason);if(wind)old.action('COMBAT',{card:wind.id,target:wind.targets[0].id});const cards=old.combatCards().filter(c=>!c.reason),card=cards.find(c=>c.id==='PLAYER_TRAVELER_ANEMO_E');assert(card,'native player skill is legal');const foes=old.s.runtime.actors.filter(a=>a.side==='ENEMY'&&a.hp>0),target=card.targets.find(t=>foes.some(a=>a.id===t.id));assert(target,'legal real enemy target');old.action('COMBAT',{card:card.id,target:target.id,branch:'HOLD'});assert(old.s.runtime,'old native fight remains active after one player skill');assert.equal(old.s.runtime.opening.state,'STARTED');assert.equal(old.s.runtime.phase,'WAIT_PLAYER');assert(old.s.runtime.actors.some(a=>Object.values(a.cooldowns||{}).some(n=>n>0)),'real nonzero cooldown preserved');}
    assert.equal(old.s.runtime.dailyPressureRevision,undefined,'published old battle has no daily pressure marker');const saved=JSON.parse(old.serialize()),originalRuntime=copy(saved.runtime),originalRng=saved.global.PRNG_STATE,loaded=new env.R(env.db,copy(saved));equal(loaded.s.runtime,originalRuntime,'HP ATK DEF shields statuses cooldowns behavior and order unchanged on load');assert.equal(loaded.s.global.PRNG_STATE,originalRng,'no RNG on load');const resaved=JSON.parse(loaded.serialize());equal(resaved.runtime,originalRuntime,'resaving keeps complete old battle');assert.equal(resaved.global.PRNG_STATE,originalRng);if(spec.kind==='FIELD'){assert.equal(originalRuntime.fieldBoss.behaviorRevision,4);assert.equal(resaved.runtime.fieldBoss.behaviorRevision,4);}for(const a of resaved.runtime.actors)assert.equal(a.bossChallengeRevision,undefined,'no new profile marker in old fight');
    const legacy=new oldEnv.R(oldEnv.db,copy(saved));equal(JSON.parse(legacy.serialize()),resaved,'full reserialized old/new state identity');if(boundary==='WAIT_PLAYER'){legacy.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});loaded.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});equal(legacy.s.runtime,loaded.s.runtime,'one native resumed action uses old rules');assert.equal(legacy.s.global.PRNG_STATE,loaded.s.global.PRNG_STATE,'resumed native action keeps RNG');}
    return{savedEngine:oldEnv.fingerprint,boundary,prng:originalRng,oldFieldBehavior:originalRuntime.fieldBoss?.behaviorRevision??null,runtimeSHA256:sha(JSON.stringify(originalRuntime)),resumedActionCompared:boundary==='WAIT_PLAYER'};
   });
  }
  for(const spec of specs.filter(s=>s.kind!=='FIELD'))check('new_daily_pressure_pending_started_and_native_guard_replay:'+spec.source,()=>{const first=start(env,spec),pending=JSON.parse(first.serialize()),loaded=new env.R(env.db,copy(pending));assert.equal(pending.runtime.dailyPressureRevision,1);equal(loaded.s.runtime,pending.runtime,'new pinned daily pending save is unchanged');assert.equal(loaded.s.global.PRNG_STATE,pending.global.PRNG_STATE);first.action('COMBAT_BEGIN');loaded.action('COMBAT_BEGIN');equal(loaded.s.runtime,first.s.runtime,'new daily opening replay');assert.equal(loaded.s.global.PRNG_STATE,first.s.global.PRNG_STATE);const waiting=JSON.parse(loaded.serialize()),resumed=new env.R(env.db,copy(waiting));equal(resumed.s.runtime,waiting.runtime,'new daily started save is unchanged');let replayedGuard=false;if(loaded.s.runtime&&loaded.combatCards().some(c=>c.id==='PLAYER_BASIC_GUARD'&&!c.reason)){loaded.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});resumed.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});equal(resumed.s.runtime,loaded.s.runtime,'new pinned daily native action replay');assert.equal(resumed.s.global.PRNG_STATE,loaded.s.global.PRNG_STATE);replayedGuard=true;}equal(JSON.parse(resumed.serialize()),JSON.parse(loaded.serialize()),'daily full save/replay identity');return{origin:spec.origin,marker:1,pendingAndStartedRoundTrip:true,nativeGuardReplayed:replayedGuard,stillActive:!!loaded.s.runtime,prng:loaded.s.global.PRNG_STATE};});
  check('daily_pressure_marker_validation_excludes_wrong_scopes',()=>{const spec=specs.find(s=>s.source==='BOSS_ANDRIUS'),native=JSON.parse(start(env,spec).serialize()),cases=[];for(const value of [2,'1',null]){const s=copy(native);s.runtime.dailyPressureRevision=value;assert.throws(()=>new env.R(env.db,s),/일일보스 공격 정책/);cases.push({marker:value});}for(const origin of ['STORY:TRV_BOSS_SCOPE_BOUNDARY','EXPLICIT',specs.find(s=>s.kind==='FIELD').origin]){const s=copy(native);s.runtime.origin=origin;assert.throws(()=>new env.R(env.db,s),/일일보스 공격 정책/);cases.push({origin});}for(const flag of ['abyss','raid']){const s=copy(native);s.runtime[flag]={version:1};assert.throws(()=>new env.R(env.db,s),/일일보스 공격 정책/);cases.push({scope:flag});}return{rejected:cases,unmarkedOldSavesCoveredSeparately:true};});
  check('nonenemy_and_summon_growth_probes_exclude_profile',()=>{const results=[];for(const spec of specs.filter(s=>env.api.growthV01522.bossChallengeProfiles[s.source]))for(const mode of ['ALLY','SUMMON']){const old=mock(oldEnv,spec),current=mock(env,spec);if(mode==='ALLY'){old.a.side='ALLY';current.a.side='ALLY';}else{old.a.fbSummon={owner:'BOUNDARY_OWNER'};current.a.fbSummon={owner:'BOUNDARY_OWNER'};}old.r.tuneGrowthEnemy(old.a,{actors:[old.a],origin:spec.origin},spec.level);current.r.tuneGrowthEnemy(current.a,{actors:[current.a],origin:spec.origin},spec.level);equal(bossStats(old.a),bossStats(current.a),'only enemy body receives candidate');assert.equal(current.a.bossChallengeRevision,undefined);results.push({source:spec.source,mode});}return results;});
 }
 check('shared_db_and_raw_fixture_remain_unchanged',()=>{assert.equal(sha(JSON.stringify(env.db)),dbBefore,'shared raw DB not mutated');assert.equal(sha(fs.readFileSync(path.join(ROOT,'content/db.json'))),env.rawDbSHA256,'actual raw DB file not mutated');return{dbSHA256:env.rawDbSHA256,recordedQADbSHA256:proof.qaDbSHA256,matchesRecordedQA:env.rawDbSHA256===proof.qaDbSHA256,unchanged:true};});
 report.total=report.checks.length;report.passed=report.checks.filter(c=>c.passed).length;report.failed=report.total-report.passed;
 if(output){fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');}
 console.log(JSON.stringify({ok:report.failed===0,total:report.total,passed:report.passed,failed:report.failed,output:output||null,baselineCommit:proof.commit,limits:report.scope}));if(report.failed)process.exitCode=1;
}
