/* Bounded joint-facility tests against the integrated, read-only game/source. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const source=process.env.CRPG_SOURCE||path.resolve(__dirname,'../source'),dbPath=process.env.CRPG_DB||path.resolve(__dirname,'../content/db.json');
const ctx=vm.createContext({console}),hashes={},files=[...fs.readFileSync(path.join(source,'index.html'),'utf8').matchAll(/<script\s+src="(runtime[^/]*\.js)"/g)].map(x=>x[1]).filter(x=>x!=='runtime_places_joint.js');
if(!files.includes('runtime_places.js'))throw Error('Integrated runtime_places.js was not loaded by index');
for(const file of [...files,'runtime_places_joint.js']){const p=file==='runtime_places_joint.js'?path.join(source,file):path.join(source,file),text=fs.readFileSync(p,'utf8');hashes[file]=crypto.createHash('sha256').update(text).digest('hex');vm.runInContext(text,ctx,{filename:file});}
const db=JSON.parse(fs.readFileSync(dbPath,'utf8')),Runtime=ctx.CRPGRuntime.Runtime;ctx.CRPGRelationships.install(ctx.CRPGRuntime,{events:ctx.CRPGRelationships.catalogFromDB(db),activities:ctx.CRPGRelationships.activitiesFromDB(db),preferences:{adultModeEnabled:false},eligibility:{profiles:{},protagonists:{}}});
const copy=x=>JSON.parse(JSON.stringify(x)),results=[];let seq=0;
function fixture(map='MAP_MOND_CITY',level=5){const r=new Runtime(db);r.newGame({name:'공동제작시험',route:'ROUTE_TRAVELER',seed:74219,saveId:'JOINT-'+(++seq)});Object.assign(r.s.global,{CURRENT_STORY_NODE_ID:'END',STORY_CURSOR_NODE_ID:'END',PENDING_CHOICE_GROUP_ID:'',PENDING_INPUT_JSON:'{}',CURRENT_MAP_ID:map,WORLD_TIME:'08:00',PLAYER_LEVEL_STATE:level});r.recalculate();r.prepareStory();return r;}
function enter(r,merchant,mode='CRAFT'){if(merchant==='MRC_BLACKSMITH_COMMON'&&r.s.global.CURRENT_MAP_ID==='MAP_MOND_CITY')merchant='MRC_MOND_EQUIP';const e=r.placeEntries().find(x=>x.merchant===merchant||x.entity===merchant);assert.ok(e,'missing fixture facility '+merchant);r.action('PLACE_ENTER',{place:e.id,mode});}
function reject(r,type,a){const before=r.serialize();assert.throws(()=>r.action(type,a));assert.equal(r.serialize(),before,'rejection changed save or preparation');}
function stage(r,id,merchant){enter(r,merchant);r.action('CRAFT_STAGE',{recipe:id});}
function both(r,id='REC_CATALYST_MAPPA'){stage(r,id,'MRC_BLACKSMITH_COMMON');stage(r,id,'MRC_ALCHEMY_COMMON');}
function resources(r,id,quantity=1){const c=r.recipeCost(r.recipeDefinition(id),quantity);r.s.global.MORA=c.mora;for(const [id,n]of Object.entries(c.items))r.giveItem(id,n);return c;}
function time(g){const [h,m]=g.WORLD_TIME.split(':').map(Number);return(g.WORLD_DAY-1)*1440+h*60+m;}
function test(name,f){try{const evidence=f();results.push({name,ok:true,evidence:evidence||null});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:{code:e.code,message:e.message,stack:e.stack}});console.error('FAIL '+name+'\n'+e.stack);}}
test('all four actual + recipes appear at each participating facility with local stage metadata',()=>{const ids=db['17_RECIPE_DB'].filter(r=>String(r[17]).includes('+')).map(r=>r[0]);assert.equal(ids.length,4);for(const id of ids){const row=db['17_RECIPE_DB'].find(x=>x[0]===id),map=row[16]==='몬드성'?'MAP_MOND_CITY':'MAP_NODKRAI_NASHA',r=fixture(map,20);for(const merchant of row[17].split('+').map(x=>x.trim())){enter(r,merchant);const e=r.placeRecipes().find(x=>x.row[0]===id);assert.ok(e);assert.equal(e.stages.length,2);assert.equal(e.canStage,true);assert.equal(e.ready,false);assert.ok(e.stages.filter(x=>x.here).length===1);assert.ok(e.stages.every(x=>x.label&&!x.label.includes('MRC_')));r.action('CRAFT_STAGE',{recipe:id});}assert.equal(r.jointCraftStatus(id).ready,true);assert.ok(r.s.craftPreparations[id]);}return{recipes:ids};});
test('stage preparation uses actual entered facility and creates no items or cost/time changes',()=>{const r=fixture(),id='REC_CATALYST_MAPPA';enter(r,'MRC_BLACKSMITH_COMMON');const before={inventory:copy(r.s.inventory),mora:r.s.global.MORA,time:time(r.s.global),xp:r.s.global.PLAYER_XP_STATE};r.action('CRAFT_STAGE',{recipe:id});assert.equal(Object.keys(r.s.craftPreparations[id].stages).length,1);assert.equal(r.s.craftPreparations[id].stages[0].place,r.s.placeVisit.place);assert.deepEqual(copy(r.s.inventory),before.inventory);assert.equal(r.s.global.MORA,before.mora);assert.equal(time(r.s.global),before.time);assert.equal(r.s.global.PLAYER_XP_STATE,before.xp);assert.equal(r.jointCraftStatus(id).ready,false);reject(r,'CRAFT',{recipe:id});});
test('stage rejects outside, unrelated facility, wrong mode, hidden screen, or unsupported recipe',()=>{const r=fixture();reject(r,'CRAFT_STAGE',{recipe:'REC_CATALYST_MAPPA'});enter(r,'MRC_MOND_GENERAL','SHOP');reject(r,'CRAFT_STAGE',{recipe:'REC_CATALYST_MAPPA'});enter(r,'SERVICE_MOND_COOK');reject(r,'CRAFT_STAGE',{recipe:'REC_CATALYST_MAPPA'});enter(r,'MRC_BLACKSMITH_COMMON');reject(r,'CRAFT_STAGE',{recipe:'REC_ARMOR_TRAVEL'});r.action('MENU',{screen:'SYSTEM'});reject(r,'CRAFT_STAGE',{recipe:'REC_CATALYST_MAPPA'});});
test('both final catalyst recipes retain exact DB cost, output and total time once',()=>{for(const id of ['REC_CATALYST_MAPPA','REC_CATALYST_AMBER']){const r=fixture(),row=r.recipeDefinition(id),cost=resources(r,id);both(r,id);const before=time(r.s.global);assert.equal(r.actionReason('CRAFT',{recipe:id}),'');r.action('CRAFT',{recipe:id});assert.equal(r.s.global.MORA,0);for(const item of Object.keys(cost.items))assert.equal(r.itemCount(item),0);assert.equal(time(r.s.global)-before,120);assert.equal(r.s.inventory.filter(x=>x.equip===row[3]).length,1);assert.equal(r.s.craftPreparations,undefined);assert.equal(r.placeRecipes().find(x=>x.row[0]===id).canStage,true);reject(r,'CRAFT',{recipe:id});}});
test('batch crafting keeps original quantity cost/time and consumes preparation for that one batch',()=>{const r=fixture(),id='REC_CATALYST_MAPPA';resources(r,id,2);both(r,id);const before=time(r.s.global);r.action('CRAFT',{recipe:id,quantity:2});assert.equal(r.s.inventory.filter(x=>x.equip==='EQ_CATALYST_MAPPA').length,2);assert.equal(time(r.s.global)-before,240);assert.equal(r.s.global.MORA,0);assert.equal(r.s.craftPreparations,undefined);});
test('resource, currency, level and quantity failures preserve completed preparation atomically',()=>{const id='REC_CATALYST_MAPPA',r=fixture();both(r,id);reject(r,'CRAFT',{recipe:id});assert.equal(r.jointCraftStatus(id).ready,true);resources(r,id);r.s.global.MORA=0;reject(r,'CRAFT',{recipe:id});r.s.global.MORA=220;reject(r,'CRAFT',{recipe:id,quantity:0});r.s.global.PLAYER_LEVEL_STATE=1;r.recalculate();reject(r,'CRAFT',{recipe:id});r.s.global.PLAYER_LEVEL_STATE=5;r.recalculate();r.action('CRAFT',{recipe:id});assert.equal(r.s.craftPreparations,undefined);});
test('save/load preserves partial preparation across actual facility visits',()=>{let r=fixture();resources(r,'REC_CATALYST_MAPPA');stage(r,'REC_CATALYST_MAPPA','MRC_BLACKSMITH_COMMON');r.action('MENU',{screen:'SYSTEM'});r=new Runtime(db,JSON.parse(r.serialize()));assert.equal(r.jointCraftStatus('REC_CATALYST_MAPPA').stages[0].prepared,true);stage(r,'REC_CATALYST_MAPPA','MRC_ALCHEMY_COMMON');r.action('CRAFT',{recipe:'REC_CATALYST_MAPPA'});assert.equal(r.s.inventory.filter(x=>x.equip==='EQ_CATALYST_MAPPA').length,1);});
test('duplicate receipt is idempotent; fresh repeated stage at same facility cannot replace missing stage',()=>{const r=fixture();enter(r,'MRC_BLACKSMITH_COMMON');const g=r.s.global,a={id:g.SAVE_ID+':'+(g.LAST_COMMITTED_ACTION_SEQ+1),revision:g.SAVE_REVISION,type:'CRAFT_STAGE',recipe:'REC_CATALYST_MAPPA'},result=r.transact(a),after=r.serialize();assert.deepEqual(copy(r.transact(a)),copy(result));assert.equal(r.serialize(),after);reject(r,'CRAFT_STAGE',{recipe:'REC_CATALYST_MAPPA'});assert.equal(r.jointCraftStatus('REC_CATALYST_MAPPA').ready,false);});
test('preparation stays map-bound and cannot combine matching common merchant from another continent',()=>{const r=fixture();stage(r,'REC_CATALYST_MAPPA','MRC_BLACKSMITH_COMMON');const record=copy(r.s.craftPreparations);r.action('PLACE_LEAVE');r.s.global.CURRENT_MAP_ID='MAP_LIYUE_HARBOR';enter(r,'MRC_ALCHEMY_COMMON');reject(r,'CRAFT_STAGE',{recipe:'REC_CATALYST_MAPPA'});reject(r,'CRAFT',{recipe:'REC_CATALYST_MAPPA'});assert.deepEqual(copy(r.s.craftPreparations),record);r.action('PLACE_LEAVE');r.s.global.CURRENT_MAP_ID='MAP_MOND_CITY';stage(r,'REC_CATALYST_MAPPA','MRC_ALCHEMY_COMMON');assert.equal(r.jointCraftStatus('REC_CATALYST_MAPPA').ready,true);});
test('single-facility recipes and preserved QUEST/RELATIONS menu returns keep existing behavior',()=>{const r=fixture(),id='REC_ARMOR_TRAVEL';resources(r,id);enter(r,'MRC_BLACKSMITH_COMMON');const before=r.currentPlace().place;for(const screen of ['QUEST','RELATIONS']){r.action('MENU',{screen});assert.equal(r.currentPlace().place,before);r.action('MENU',{screen:'CRAFT'});}r.action('CRAFT',{recipe:id});assert.equal(r.s.inventory.filter(x=>x.equip==='EQ_ARMOR_TRAVEL_COAT').length,1);assert.equal(r.s.craftPreparations,undefined);});
test('cross-save, wrong map/facility, forged action and changed requirement preparations reject import',()=>{const r=fixture();stage(r,'REC_CATALYST_MAPPA','MRC_BLACKSMITH_COMMON');for(const change of [s=>s.craftPreparations.REC_CATALYST_MAPPA.saveId='other',s=>s.craftPreparations.REC_CATALYST_MAPPA.map='MAP_LIYUE_HARBOR',s=>s.craftPreparations.REC_CATALYST_MAPPA.stages[0].place='EVT_SCHEDULE_MRC_ALCHEMY_COMMON',s=>s.craftPreparations.REC_CATALYST_MAPPA.stages[0].action='other:1',s=>s.craftPreparations.REC_CATALYST_MAPPA.signature='changed']){const s=JSON.parse(r.serialize());change(s);assert.throws(()=>new Runtime(db,s),{code:'CRAFT_STAGE_SAVE'});}});
test('original unresolved textual unlock conditions remain enforced on high-tier recipes',()=>{for(const id of ['REC_ACC_RESONANCE','REC_SPECIAL_CORE']){const r=fixture('MAP_NODKRAI_NASHA',20);resources(r,id);stage(r,id,'MRC_NODKRAI_EQUIP');stage(r,id,'MRC_ALCHEMY_COMMON');assert.equal(r.jointCraftStatus(id).ready,true);const why=r.craftReason(r.recipeDefinition(id));assert.match(why,/추가 해금 조건/);reject(r,'CRAFT',{recipe:id});assert.equal(r.jointCraftStatus(id).ready,true);}return {unchangedUnlocks:['LEVEL>=14 / 노드크라이 탐사 해금','LEVEL>=17 / 보스 정수와 다지역 희귀 소재 확보']};});
const report={source,dbPath,loaded:files,hashes,total:results.length,passed:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length,results};fs.writeFileSync(path.join(__dirname,'../reports/joint-tests.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({total:report.total,passed:report.passed,failed:report.failed}));process.exitCode=report.failed?1:0;
