'use strict';
// Native entry, save/END hooks and final settlement. Oversized body/core packets
// establish mechanic boundaries; they are declared probes, not farming timings.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),H=require('../tools/audit_protagonist_v01618.cjs');
const ROOT=path.resolve(__dirname,'..'),env=H.load(ROOT),{R,db}=env,FB=env.api.fieldBosses,cp=x=>JSON.parse(JSON.stringify(x));
const output=process.argv[2]||ROOT+'/../v01623-field-strategy-contracts.json';
const report={version:'0.16.24',scope:'New public revision5 saves/replay, four-END Electro/Geo revival and scoped pillar specification; revision4 recurring Primo/Serpent and older behavior probes remain. Actual 0.16.23 numeric/save preservation is separately tested by test_boss_difficulty_scope_v01624.cjs. Boundary probes are not full-fight manual difficulty proof.',fixturePolicy:'Declared ownedLv60/phase6 four-person party, +6 ordinary crafted gear, talent8, initial funding/fullHP. Fresh native field admission creates revision5; explicit old markers isolate old mechanics on declared current numeric fixtures. Oversized body/core damage and deterministic dice are boundary probes, not native balance outcomes. No forced finishBattle victories.',fingerprint:env.fingerprint,sourceSHA256:crypto.createHash('sha256').update(fs.readFileSync(ROOT+'/source/runtime_field_bosses.js')).digest('hex'),checks:[]};
function check(id,fn){try{report.checks.push({id,passed:true,evidence:fn()});console.log('PASS '+id);}catch(e){report.checks.push({id,passed:false,error:e.stack});console.error('FAIL '+id+' '+e.message);}}
function start(id,revision=4,team=['MOND_AMBER','MOND_NOELLE','MOND_BARBARA'],begin=true){const r=H.setup(env,{level:60,route:'ROUTE_TRAVELER',team,seed:717,map:FB.bosses[id].map,enhance:6,talent:8});r.action('PLACE_ENTER',{place:'BOSS:'+FB.route(id),mode:'BOSS'});r.action('BOSS_ROUTE',{route:FB.route(id),entry:'DIRECT'});assert.equal(r.s.runtime.fieldBoss.behaviorRevision,5);if(revision===undefined)delete r.s.runtime.fieldBoss.behaviorRevision;else r.s.runtime.fieldBoss.behaviorRevision=revision;if(begin)r.action('COMBAT_BEGIN');const b=r.s.runtime,boss=b.actors.find(a=>a.source===id);r.die=()=>50;r.random=()=>.5;const taskCalls=[],nativeCount=r.tasksCount;r.tasksCount=function(kind,n,event){taskCalls.push({kind,n:n??1});return nativeCount.call(this,kind,n,event);};return{r,b,boss,taskCalls,me:b.actors.find(a=>a.source==='PLAYER_CUSTOM')};}
const actor=(f,id)=>f.b.actors.find(a=>a.source===id),summons=f=>f.b.actors.filter(a=>a.fbSummon?.owner===f.boss.id&&a.hp>0);
function bodyKill(f){f.r.applyDamage(f.me,f.boss,f.boss.hp+f.boss.maxHp,{element:'물리'});assert.equal(f.boss.hp,1);assert(f.boss.fb.revival);assert(summons(f).length<=3);}
function expire(f){f.b.fields=[];f.b.hazards=[];f.boss.statuses=[];const expected=f.boss.fb.kind==='CRYO_HYPO'&&[2,3,4,5].includes(f.b.fieldBoss.behaviorRevision)?3:f.boss.fb.revival.rounds,ends=[];for(let n=0;f.boss.fb.revival&&n<5;n++){f.r.roundEnd();ends.push({round:f.b.round,hp:f.boss.hp,revival:cp(f.boss.fb.revival)});}assert.equal(ends.length,expected);assert.equal(f.boss.fb.revival,null);assert.equal(f.boss.hp,Math.round(f.boss.maxHp*(f.boss.fb.kind==='CRYO_HYPO'?.5:.4)));assert(summons(f).length<=3);return ends;}
function counter(f){const kind=f.boss.fb.kind;if(kind==='ANEMO')f.r.applyDamage(actor(f,'MOND_AMBER'),f.boss,f.boss.fb.revival.core,{element:'불'});else if(kind==='CRYO_HYPO')for(let n=0;n<4;n++)f.r.applyDamage(actor(f,'MOND_AMBER'),f.boss,100,{element:'불',sourceKind:'FIELD'});else for(const s of summons(f))f.r.applyDamage(actor(f,kind==='ELECTRO'?'MOND_AMBER':'MOND_NOELLE'),s,s.hp+1,{element:kind==='ELECTRO'?'불':'바위'});assert.equal(f.boss.hp,0);assert.equal(f.boss.fb.revival,null);assert.equal(summons(f).length,0);}
function settle(f){f.r.autoUntilPlayer();assert.equal(f.r.s.runtime,null);const out=JSON.parse(f.r.s.global.LAST_BATTLE_RESULT_JSON);assert.equal(out.victory,true);assert.equal(Object.keys(f.r.s.combatReceipts||{}).length,1);assert.equal(f.r.fieldBossNotes(f.boss.source).wins,1);const saved=f.r.serialize();assert.equal(f.r.finishBattle(true),undefined);assert.equal(f.r.serialize(),saved);return out;}
const BOSSES=['FB_ANEMO_HYPOSTASIS','FB_ELECTRO_HYPOSTASIS','FB_GEO_HYPOSTASIS','FB_CRYO_HYPOSTASIS'];
for(const id of BOSSES)check('new4_two_timeouts_then_real_counter:'+id,()=>{let f=start(id),ends=[];for(let n=0;n<2;n++){bodyKill(f);const raw=f.r.serialize(),loaded=new R(db,JSON.parse(raw));assert.equal(loaded.s.runtime.fieldBoss.behaviorRevision,4);assert.deepEqual(cp(loaded.s.runtime.actors.find(a=>a.source===id).fb.revival),cp(f.boss.fb.revival));loaded.die=()=>50;loaded.random=()=>.5;f={r:loaded,b:loaded.s.runtime,boss:loaded.s.runtime.actors.find(a=>a.source===id),me:loaded.s.runtime.actors.find(a=>a.source==='PLAYER_CUSTOM')};ends.push(expire(f));assert.equal(f.boss.fb.revived,false);assert.equal(Object.keys(f.r.s.combatReceipts||{}).length,0);assert.equal(f.r.fieldBossNotes(id).wins,0);}bodyKill(f);counter(f);const out=settle(f);assert.equal(f.b.log.filter(x=>x.card==='FB_REVIVED').length,2);return{ends,revived:2,successAfterThirdCore:true,aliveSummonsAfter:0,actorCount:f.b.actors.length,receipt:out};});
for(const revision of [2,'unmarked'])for(const id of BOSSES)check('legacy_one_timeout_then_body_kill:'+revision+':'+id,()=>{const f=start(id,revision===2?2:undefined);if(revision==='unmarked')delete f.b.fieldBoss.behaviorRevision;bodyKill(f);const ends=expire(f);assert.equal(f.boss.fb.revived,true);f.r.applyDamage(f.me,f.boss,f.boss.hp+1,{element:'물리'});assert.equal(f.boss.hp,0);assert.equal(f.boss.fb.revival,null);for(const s of summons(f))s.hp=0;const out=settle(f);return{revision:revision==='unmarked'?null:2,ends,oldOneRevivalPreserved:true,receipt:out};});
check('new4_native_air_access_and_typed_delayed_packets',()=>{const f=start('FB_ANEMO_HYPOSTASIS');bodyKill(f);f.me.range='근접';f.me.traits={};f.me.statuses=[];const rows=[];for(const range of ['원거리','전장','대공']){const before=f.boss.fb.revival.core;assert.equal(f.r.hasAirAccess(f.me,{...f.boss,airborne:true},range),true);f.r.damage(f.me,f.boss,.01,'불',{range,sureHit:true,noAura:true});assert(f.boss.fb.revival.core<before);rows.push({range,before,after:f.boss.fb.revival.core});assert.equal(f.r._fieldBossDamagePacket,undefined);}for(const sourceKind of ['FIELD','OBJECT','REACTION','REACTION_DOT']){const before=f.boss.fb.revival.core;f.r.applyDamage(f.me,f.boss,100,{element:'불',sourceKind});assert.equal(f.boss.fb.revival.core,before);}for(const sourceKind of ['FIELD','OBJECT']){const before=f.boss.fb.revival.core;f.r.damage(f.me,f.boss,.01,'불',{range:'대공',sourceKind,sureHit:true,noAura:true});assert(f.boss.fb.revival.core<before);}for(const id of ['LEVITATION','STATUS_TACTICAL_LEVITATION']){f.me.statuses=[{id,rounds:2}];const before=f.boss.fb.revival.core;f.r.damage(f.me,f.boss,.01,'불',{range:'근접',sureHit:true,noAura:true});assert(f.boss.fb.revival.core<before);}f.me.statuses=[];for(const traits of [{AIR_ACCESS:1},{ANTI_AIR:15}]){f.me.traits=traits;const before=f.boss.fb.revival.core;f.r.damage(f.me,f.boss,.01,'불',{range:'근접',sureHit:true,noAura:true});assert(f.boss.fb.revival.core<before);}return{rows,nativeRangedFieldsAndObjects:true,positiveRawDelayedBlockedWithoutAccess:true,statusesAndExistingAntiAirPreserved:true};});
check('new4_range_scope_does_not_leak_into_nested_reaction_or_throw',()=>{const f=start('FB_ANEMO_HYPOSTASIS');bodyKill(f);f.me.range='근접';f.me.traits={};f.me.statuses=[];const original=f.r.applyDamage;let nested=false;f.r.applyDamage=function(a,t,n,d){if(!nested){nested=true;const before=t.fb.revival.core;original.call(this,a,t,100,{element:'불',sourceKind:'REACTION'});assert.equal(t.fb.revival.core,before);}return original.call(this,a,t,n,d);};const before=f.boss.fb.revival.core;f.r.damage(f.me,f.boss,.01,'불',{range:'대공',sureHit:true,noAura:true});assert(nested);assert(f.boss.fb.revival.core<before);assert.equal(f.r._fieldBossDamagePacket,undefined);f.r.applyDamage=original;const stat=f.r.combatStat,prior={sentinel:'outer'};f.r._fieldBossDamagePacket=prior;f.r.combatStat=()=>{throw Error('DECLARED_SCOPE_THROW');};assert.throws(()=>f.r.damage(f.me,f.boss,.01,'불',{range:'대공',sureHit:true,noAura:true}),/DECLARED_SCOPE_THROW/);assert.equal(f.r._fieldBossDamagePacket,prior);f.r.combatStat=stat;delete f.r._fieldBossDamagePacket;const after=f.boss.fb.revival.core;f.r.damage(f.me,f.boss,.01,'불',{range:'근접',sureHit:true,noAura:true});assert.equal(f.boss.fb.revival.core,after);assert.equal(f.r._fieldBossDamagePacket,undefined);return{samePairNestedReactionBlocked:true,priorScopeRestoredOnThrow:true,rejectedNextMeleeBlocked:true};});
check('new4_native_guoba_ranged_field_reaches_anemo_core',()=>{const f=start('FB_ANEMO_HYPOSTASIS',4,['MOND_AMBER','LIYUE_XIANGLING','MOND_BARBARA']),a=actor(f,'LIYUE_XIANGLING'),card=f.r.actorCards(a).find(x=>x.id==='LIYUE_XIANGLING_E');a.traits={};a.statuses=[];a.range='근접';assert.equal(f.r.cardReason(a,card),'');f.r.executeCard(a,card,f.boss.id);bodyKill(f);const before=f.boss.fb.revival.core;assert(before>0);f.r.tickFields('END');const after=f.boss.fb.revival?.core??0;assert(after<before);if(after===0){assert.equal(f.boss.hp,0);assert.equal(f.boss.fb.revival,null);}assert.equal(f.r._fieldBossDamagePacket,undefined);return{nativeCard:card.id,actorRange:a.range,field:'GOU_BA',before,after,normalCounterSuccess:after===0,delayedRange:'원거리',sourceKind:'FIELD'};});
check('legacy2_air_core_gate_stays_unchanged',()=>{const f=start('FB_ANEMO_HYPOSTASIS',2);bodyKill(f);f.me.range='근접';f.me.traits={AIR_ACCESS:1};const before=f.boss.fb.revival.core;f.r.damage(f.me,f.boss,.01,'불',{range:'대공',sureHit:true});assert.equal(f.boss.fb.revival.core,before);assert.equal(f.r._fieldBossDamagePacket,undefined);return{legacyNarrowGatePreserved:true};});
check('repeated_revival_does_not_multiply_final_rewards_or_wins',()=>{function run(n){const f=start('FB_ELECTRO_HYPOSTASIS');for(let i=0;i<n;i++){bodyKill(f);expire(f);assert.equal(f.r.fieldBossNotes(f.boss.source).wins,0);assert.equal(Object.keys(f.r.s.combatReceipts||{}).length,0);assert.equal((f.r.s.fieldBossWindow?.wins||0),0);assert.equal(f.taskCalls.filter(x=>['win','boss'].includes(x.kind)).length,0);}bodyKill(f);counter(f);const receipt=settle(f);return{reward:{xp:receipt.xp,mora:receipt.mora,loot:cp(receipt.loot),firstClear:receipt.firstClear},notes:cp(f.r.fieldBossNotes(f.boss.source)),quota:cp(f.r.s.fieldBossClock),fieldBossWindow:cp(f.r.s.fieldBossWindow),taskCalls:cp(f.taskCalls),receiptCount:Object.keys(f.r.s.combatReceipts||{}).length,receipt,deadSummons:f.b.actors.filter(a=>a.fbSummon&&a.hp<=0).length};}const zero=run(0),two=run(2);assert.deepEqual(two.reward,zero.reward);assert.equal(two.notes.wins,1);assert.equal(two.notes.attempts,1);assert.equal(two.receiptCount,1);assert.equal(Object.keys(two.quota).length,1);assert.deepEqual(two.fieldBossWindow,zero.fieldBossWindow);assert.equal(two.fieldBossWindow.wins,1);for(const kind of ['win','boss']){assert.equal(two.taskCalls.filter(x=>x.kind===kind).reduce((n,x)=>n+x.n,0),1);assert.equal(zero.taskCalls.filter(x=>x.kind===kind).reduce((n,x)=>n+x.n,0),1);}return{zero,two,extraXpMoraLootWinsAndQuota:0};});
check('new_and_saved_behavior_versions_and_cryo_countdown_validation',()=>{assert.equal(FB.behaviorRevision,5);const f=start('FB_CRYO_HYPOSTASIS');bodyKill(f);for(const revision of [undefined,2,3,4,5]){const s=JSON.parse(f.r.serialize());if(revision===undefined)delete s.runtime.fieldBoss.behaviorRevision;else s.runtime.fieldBoss.behaviorRevision=revision;assert.doesNotThrow(()=>new R(db,s));}for(const revision of [0,1,6,'3',null]){const s=JSON.parse(f.r.serialize());s.runtime.fieldBoss.behaviorRevision=revision;assert.throws(()=>new R(db,s),/필드 보스 전투/);}for(const revision of [2,3,4,5]){const s=JSON.parse(f.r.serialize());s.runtime.fieldBoss.behaviorRevision=revision;s.runtime.actors.find(a=>a.fb).fb.revival.startedRound=s.runtime.round+1;assert.throws(()=>new R(db,s),/냉기 핵/);}return{accepted:['unmarked',2,3,4,5],rejected:[0,1,6,'3',null],allModernCountdownVersionsValidated:true};});
// Loading an older battle never upgrades its repeating revival policy.
for(const id of BOSSES)check('saved3_repeated_revival_preserved:'+id,()=>{let f=start(id,3);bodyKill(f);const loaded=new R(db,JSON.parse(f.r.serialize()));assert.equal(loaded.s.runtime.fieldBoss.behaviorRevision,3);loaded.die=()=>50;loaded.random=()=>.5;f={r:loaded,b:loaded.s.runtime,boss:loaded.s.runtime.actors.find(a=>a.source===id),me:loaded.s.runtime.actors.find(a=>a.source==='PLAYER_CUSTOM')};const ends=expire(f);assert.equal(f.boss.fb.revived,false);bodyKill(f);counter(f);const out=settle(f);return{revision:3,ends,repeatedCounterRetained:true,receipt:out};});

for(const revision of [5,4,3,2,'unmarked'])check('primo_counter_window:'+revision,()=>{
 const f=start('FB_PRIMO_GEOVISHAP',revision==='unmarked'?undefined:revision),{r,b,boss,me}=f;
 if(revision==='unmarked')delete b.fieldBoss.behaviorRevision;
 // Declared phase-boundary probes; these shields do not model an acquired party.
 assert(r.fieldBossBarrierReason(me,boss,'물리','근접'));
 boss.fb.beamReflected=true;boss.fb.exposedUntil=b.round+2;
 const finalOpenRound=boss.fb.exposedUntil;b.round=finalOpenRound;
 assert.equal(r.fieldBossBarrierReason(me,boss,'물리','근접'),'');
 let before=boss.hp;r.applyDamage(me,boss,100,{element:'물리',sourceKind:'FIELD'});assert(boss.hp<before);
 b.round=finalOpenRound+1;before=boss.hp;
 r.damage(me,boss,.01,'물리',{sureHit:true,noAura:true});r.applyDamage(me,boss,100,{element:'물리',sourceKind:'REACTION_DOT'});
 if([4,5].includes(revision)){assert.equal(boss.hp,before);assert(r.fieldBossBarrierReason(me,boss,'물리','근접'));}
 else {assert(boss.hp<before);assert.equal(r.fieldBossBarrierReason(me,boss,'물리','근접'),'');}
 const loaded=new R(db,JSON.parse(r.serialize())),lb=loaded.s.runtime,la=lb.actors.find(a=>a.source===boss.source),lm=lb.actors.find(a=>a.source==='PLAYER_CUSTOM');
 assert.equal(lb.fieldBoss.behaviorRevision,revision==='unmarked'?undefined:revision);
 assert.equal(!!loaded.fieldBossBarrierReason(lm,la,'물리','근접'),[4,5].includes(revision));
 loaded.die=()=>50;loaded.random=()=>.5;
 const shielded=lb.actors.filter(a=>a.side==='ALLY'&&a.hp>0).slice(0,2);assert.equal(shielded.length,2);
 for(const a of shielded)loaded.shield(a,1000000,'DECLARED_REFLECTION_PROBE',5);
 loaded.fbMove(la,'BEAM');assert.equal(la.fb.beamReflected,true);assert.equal(la.fb.exposedUntil,lb.round+2);
 assert.equal(loaded.fieldBossBarrierReason(lm,la,'물리','근접'),'');
 return{revision:revision==='unmarked'?null:revision,lastOpenRoundInclusive:true,expiredWindowClosed:[4,5].includes(revision),savedBehaviorPreserved:true,secondNativeBeamReflectionReopens:true,shieldFixtureOnly:true};
});

for(const revision of [5,4,3,2,'unmarked'])check('serpent_next_burrow_closes_armor:'+revision,()=>{
 const f=start('FB_RUIN_SERPENT',revision==='unmarked'?undefined:revision),{r,b,boss,me}=f;if(revision==='unmarked')delete b.fieldBoss.behaviorRevision;
 me.traits={...me.traits,ARMOR_BREAK:25};boss.fb.burrowed=false;boss.fb.armorOpened=false;boss.fb.exposedUntil=0;
 assert(r.fieldBossBarrierReason(me,boss,'물리','근접'));
 r.fbMove(boss,'CHARGE');assert.equal(r.fieldBossBarrierReason(me,boss,'물리','근접'),'');assert.equal(boss.fb.armorOpened,true);
 const priorHeadWindow=boss.fb.exposedUntil;r.fbMove(boss,'BURROW');assert.equal(boss.fb.burrowed,true);
 if([4,5].includes(revision)){assert.equal(boss.fb.armorOpened,false);assert.equal(boss.fb.exposedUntil,0);assert.equal(boss.bossExposed,false);}
 else{assert.equal(boss.fb.armorOpened,true);assert.equal(boss.fb.exposedUntil,priorHeadWindow);}
 const before=boss.hp;r.applyDamage(me,boss,100,{element:'물리',sourceKind:'OBJECT'});
 // Unmarked applyDamage behavior deliberately retains the historical contract.
 if(revision!=='unmarked')assert.equal(boss.hp,before);
 const loaded=new R(db,JSON.parse(r.serialize())),lb=loaded.s.runtime,la=lb.actors.find(a=>a.source===boss.source),lm=lb.actors.find(a=>a.source==='PLAYER_CUSTOM');loaded.die=()=>50;loaded.random=()=>.5;
 assert.equal(lb.fieldBoss.behaviorRevision,revision==='unmarked'?undefined:revision);loaded.fbMove(la,'EMERGE');
 assert.equal(la.fb.burrowed,false);assert.equal(!!loaded.fieldBossBarrierReason(lm,la,'물리','근접'),[4,5].includes(revision));
 if([4,5].includes(revision)){const hp=la.hp;loaded.applyDamage(lm,la,100,{element:'물리',sourceKind:'FIELD'});assert.equal(la.hp,hp);loaded.fbMove(la,'CHARGE');assert.equal(loaded.fieldBossBarrierReason(lm,la,'물리','근접'),'');assert.equal(la.fb.armorOpened,true);loaded.applyDamage(lm,la,100,{element:'물리'});assert(la.hp<hp);}
 return{revision:revision==='unmarked'?null:revision,closedAtNextBurrow:[4,5].includes(revision),oldPermanentOpeningPreserved:![4,5].includes(revision),savedBurrowPreserved:true,nextNativeChargeReopens:true,heavyTraitBoundaryFixture:true};
});
check('saved3_air_range_scope_preserved',()=>{const f=start('FB_ANEMO_HYPOSTASIS',3);bodyKill(f);f.me.range='근접';f.me.traits={};f.me.statuses=[];const loaded=new R(db,JSON.parse(f.r.serialize())),b=loaded.s.runtime,boss=b.actors.find(a=>a.source==='FB_ANEMO_HYPOSTASIS'),me=b.actors.find(a=>a.source==='PLAYER_CUSTOM');loaded.die=()=>50;loaded.random=()=>.5;const before=boss.fb.revival.core;loaded.damage(me,boss,.01,'불',{range:'대공',sourceKind:'FIELD',sureHit:true,noAura:true});assert(boss.fb.revival.core<before);assert.equal(loaded._fieldBossDamagePacket,undefined);return{revision:3,typedDelayedAirAccessRetained:true};});
check('new4_cryo_hit_count_and_deadline_not_tightened',()=>{const f=start('FB_CRYO_HYPOSTASIS');bodyKill(f);assert.equal(f.boss.fb.revival.need,4);assert.equal(f.boss.fb.revival.rounds,2);const started=f.boss.fb.revival.startedRound;for(let n=1;n<=3;n++){f.r.damage(actor(f,'MOND_AMBER'),f.boss,.01,'불',{sourceKind:'FIELD',sureHit:true});assert.equal(f.boss.fb.revival.hits,n);}f.r.damage(actor(f,'MOND_AMBER'),f.boss,.01,'불',{sourceKind:'FIELD',sureHit:true});assert.equal(f.boss.fb.revival,null);assert.equal(f.boss.hp,0);return{need:4,rounds:2,startedRound:started,sameActionDelayedPacketsRetained:true,noNewDistinctAttackRequirement:true};});
// New behavior5 uses real public PENDING entry and native PRNG for save/replay.
for(const id of Object.keys(FB.bosses))check('new5_pending_started_and_native_guard_replay:'+id,()=>{const f=start(id,5,undefined,false);delete f.r.die;delete f.r.random;const pending=JSON.parse(f.r.serialize());assert.equal(pending.runtime.opening.state,'PENDING');const loaded=new R(db,cp(pending));assert.deepEqual(cp(loaded.s.runtime),cp(pending.runtime));assert.equal(loaded.s.global.PRNG_STATE,pending.global.PRNG_STATE);f.r.action('COMBAT_BEGIN');loaded.action('COMBAT_BEGIN');assert.deepEqual(cp(loaded.s.runtime),cp(f.r.s.runtime));assert.equal(loaded.s.runtime.fieldBoss.behaviorRevision,5);const waiting=JSON.parse(loaded.serialize()),resumed=new R(db,cp(waiting));assert.deepEqual(cp(resumed.s.runtime),cp(waiting.runtime));loaded.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});resumed.action('COMBAT',{card:'PLAYER_BASIC_GUARD'});assert.deepEqual(cp(resumed.s.runtime),cp(loaded.s.runtime));assert.equal(resumed.s.global.PRNG_STATE,loaded.s.global.PRNG_STATE);return{behavior:5,pendingAndStartedRoundTrip:true,nativeGuardReplay:true,prng:loaded.s.global.PRNG_STATE};});
for(const id of BOSSES)check('new5_timeout_window_save_and_repeat_counter:'+id,()=>{let f=start(id,5),ends=[];for(let n=0;n<2;n++){bodyKill(f);if(['FB_ELECTRO_HYPOSTASIS','FB_GEO_HYPOSTASIS'].includes(id))assert.equal(f.boss.fb.revival.rounds,4);const saved=JSON.parse(f.r.serialize()),loaded=new R(db,cp(saved));assert.deepEqual(cp(loaded.s.runtime),cp(saved.runtime));loaded.die=()=>50;loaded.random=()=>.5;f={r:loaded,b:loaded.s.runtime,boss:loaded.s.runtime.actors.find(a=>a.source===id),me:loaded.s.runtime.actors.find(a=>a.source==='PLAYER_CUSTOM')};const sequence=expire(f);if(['FB_ELECTRO_HYPOSTASIS','FB_GEO_HYPOSTASIS'].includes(id))assert.equal(sequence.length,4);ends.push(sequence);assert.equal(f.boss.fb.revived,false);assert.equal(f.r.fieldBossNotes(id).wins,0);}bodyKill(f);counter(f);const receipt=settle(f);assert.equal(f.b.log.filter(x=>x.card==='FB_REVIVED').length,2);return{behavior:5,ends,receipt,actualVictorySettlementAfterBoundaryCounter:true};});
const originalSummonSpecs=cp(FB.summons);
for(const revision of [4,5])check('geo_pillar_spec_initial_growth_and_saved:'+revision,()=>{const f=start('FB_GEO_HYPOSTASIS',revision);bodyKill(f);const spec=f.r.fieldBossSummonSpec(f.b,'FB_SUMMON_PILLAR');assert.equal(spec.hp,revision===5?.07:.1);assert.equal(spec.def,revision===5?75:150);const pillars=summons(f);assert.equal(pillars.length,3);for(const p of pillars){assert.equal(p.maxHp,Math.max(1,Math.round(f.boss.maxHp*spec.hp)));assert.equal(p.atk,0);assert.equal(p.def,Math.round(spec.def*env.api.growthV01522.adCurve(f.boss.level)));assert.equal(p.growthScaled,true);}const saved=JSON.parse(f.r.serialize()),loaded=new R(db,cp(saved));assert.deepEqual(cp(loaded.s.runtime),cp(saved.runtime));assert.equal(loaded.fieldBossSummonSpec(loaded.s.runtime,'FB_SUMMON_PILLAR').hp,spec.hp);assert.equal(loaded.fieldBossSummonSpec(loaded.s.runtime,'FB_SUMMON_PILLAR').def,spec.def);return{revision,ownerHp:f.boss.maxHp,spec:cp(spec),pillars:pillars.map(p=>({hp:p.maxHp,def:p.def})),saveUnchanged:true};});
check('ocean_mimic_fixed_hp_and_owner_atk_initial_later_saved',()=>{const f=start('FB_OCEANID',5,undefined,false),growth=env.api.growthV01522,verify=(r,b)=>{const owner=b.actors.find(a=>a.source==='FB_OCEANID'),forms=b.actors.filter(a=>a.fbSummon?.owner===owner.id);for(const form of forms){const spec=r.fieldBossSummonSpec(b,form.source);assert.equal(form.maxHp,Math.max(1,Math.round(spec.hp/5*growth.hpCurve(owner.level)*(1+.16*growth.phaseFor(owner.level)))));assert.equal(form.atk,Math.round(owner.atk*(spec.atk||0)));assert.equal(form.def,Math.round(spec.def*growth.adCurve(owner.level)));assert.equal(form.growthScaled,true);}return forms.map(a=>({source:a.source,hp:a.maxHp,atk:a.atk,def:a.def}));};const initial=verify(f.r,f.b);assert.equal(initial.length,2);const saved=JSON.parse(f.r.serialize()),loaded=new R(db,cp(saved));assert.deepEqual(cp(loaded.s.runtime),cp(saved.runtime));loaded.action('COMBAT_BEGIN');const b=loaded.s.runtime,owner=b.actors.find(a=>a.source==='FB_OCEANID');loaded.fbSummon(b,owner,'FB_MIMIC_FROG');const later=verify(loaded,b);assert.equal(later.length,3);assert.equal(b.actors.filter(a=>a.side==='ENEMY'&&a.fbSummon&&a.hp>0).length,3);const again=new R(db,JSON.parse(loaded.serialize()));assert.deepEqual(cp(again.s.runtime),cp(b));return{initial,later,ownerAtk:owner.atk,fixedHpCurve:true,initialAndLaterShareOwnerAtk:true,saveUnchanged:true};});
check('scoped_pillar_spec_does_not_mutate_global_table',()=>{assert.deepEqual(cp(FB.summons),originalSummonSpecs);assert.equal(FB.summons.FB_SUMMON_PILLAR.hp,.1);assert.equal(FB.summons.FB_SUMMON_PILLAR.def,150);return{defaultHp:.1,defaultDef:150,globalSpecUnchanged:true};});
for(const revision of [4,5])check('all_ocean_mimic_hp_spec_scoped_spawn_and_save:'+revision,()=>{const f=start('FB_OCEANID',revision,undefined,false),g=env.api.growthV01522,expected={FB_MIMIC_BOAR:1015,FB_MIMIC_CRANE:700,FB_MIMIC_FROG:840,FB_MIMIC_CRAB:875,FB_MIMIC_FALCON:735},rows=[];for(const[id,newHp]of Object.entries(expected)){for(const a of f.b.actors.filter(a=>a.fbSummon))a.hp=0;const spec=f.r.fieldBossSummonSpec(f.b,id),baseHp=revision===5?newHp:FB.summons[id].hp;assert.equal(spec.hp,baseHp);const form=f.r.fbSummon(f.b,f.boss,id);assert(form,'native summon '+id);assert.equal(form.maxHp,Math.max(1,Math.round(baseHp/5*g.hpCurve(f.boss.level)*(1+.16*g.phaseFor(f.boss.level)))));assert.equal(form.atk,Math.round(f.boss.atk*(spec.atk||0)));assert.equal(form.def,Math.round(spec.def*g.adCurve(f.boss.level)));rows.push({source:id,baseHp,maxHp:form.maxHp,atk:form.atk,def:form.def});}const saved=JSON.parse(f.r.serialize()),loaded=new R(db,cp(saved));assert.deepEqual(cp(loaded.s.runtime),cp(saved.runtime));return{revision,rows,initialDefinitionUnchanged:cp(FB.summons),allFiveSpawnedViaNativeHelper:true,saveUnchanged:true};});
report.total=report.checks.length;report.passed=report.checks.filter(x=>x.passed).length;report.failed=report.total-report.passed;fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({output,total:report.total,passed:report.passed,failed:report.failed}));if(report.failed)process.exitCode=1;
