'use strict';
// Executes product renderers with a minimal DOM, and metadata with native combat.
// This is a DOM unit regression, not a real-browser or visual-layout check.
const assert=require('node:assert/strict');
const {fs,path,vm,root,fresh,c}=require('./helpers_v011.cjs');
const source=f=>fs.readFileSync(path.join(root,'source',f),'utf8');
const between=(text,from,to)=>{const start=text.indexOf(from),end=text.indexOf(to,start+from.length);assert(start>=0&&end>start,from);return text.slice(start,end);};
const cp=x=>JSON.parse(JSON.stringify(x));
class Node{
 constructor(tag,cls='',text=''){this.tagName=tag.toUpperCase();this.className=cls;this._text=String(text);this.children=[];this.dataset={};this.style={setProperty(k,v){this[k]=v;}};this.attrs={};this.parentNode=null;this.open=false;this.disabled=false;this.listeners={};this.classList={contains:n=>this.className.split(/\s+/).includes(n),add:(...xs)=>this.className=[...new Set([...this.className.split(/\s+/),...xs])].filter(Boolean).join(' '),remove:(...xs)=>this.className=this.className.split(/\s+/).filter(n=>!xs.includes(n)).join(' '),toggle:(n,on)=>{on=on===undefined?!this.classList.contains(n):on;on?this.classList.add(n):this.classList.remove(n);return on;}};}
 get textContent(){return this._text+this.children.map(n=>n.textContent).join('');}set textContent(s){this._text=String(s);for(const n of this.children)n.parentNode=null;this.children=[];}
 get isConnected(){return this.tagName==='BODY'||!!this.parentNode?.isConnected;}get parentElement(){return this.parentNode;}get nextSibling(){const p=this.parentNode;return p?.children[p.children.indexOf(this)+1]||null;}get childElementCount(){return this.children.length;}
 append(...nodes){for(let n of nodes){if(typeof n==='string')n=new Node('span','',n);n.remove();n.parentNode=this;this.children.push(n);}}prepend(...ns){for(const n of ns.reverse()){n.remove();n.parentNode=this;this.children.unshift(n);}}
 replaceChildren(...nodes){for(const n of this.children)n.parentNode=null;this.children=[];this._text='';this.append(...nodes);}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(n=>n!==this);this.parentNode=null;}
 insertBefore(n,before){n.remove();n.parentNode=this;const i=this.children.indexOf(before);this.children.splice(i<0?this.children.length:i,0,n);}after(n){this.parentNode?.insertBefore(n,this.nextSibling);}before(n){this.parentNode?.insertBefore(n,this);}
 setAttribute(k,v){this.attrs[k]=String(v);if(k==='id')this.id=String(v);}getAttribute(k){return this.attrs[k]??null;}removeAttribute(k){delete this.attrs[k];}
 matches(s){return s.split(',').some(sel=>{sel=sel.trim();if(sel.includes(':disabled')){if(!this.disabled)return false;sel=sel.replace(':disabled','');}if(sel.includes(':not('))return false;const at=[...sel.matchAll(/\[([^=\]]+)(?:="([^"]*)")?\]/g)];for(const [,k,v]of at){const value=k.startsWith('data-')?this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]:this.getAttribute(k);if(value===undefined||value===null||v!==undefined&&String(value)!==v)return false;}sel=sel.replace(/\[[^\]]+\]/g,'');const tag=sel.match(/^[a-z]+/i)?.[0];if(tag&&tag.toUpperCase()!==this.tagName)return false;for(const [,cls]of sel.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(cls))return false;return true;});}
 querySelectorAll(s){if(s.includes(','))return [...new Set(s.split(',').flatMap(sel=>this.querySelectorAll(sel.trim())))];if(s.startsWith(':scope > '))return this.children.filter(n=>n.matches(s.slice(9)));if(s.includes(' ')){const parts=s.split(/\s+/),last=parts.pop(),prior=parts.join(' ');return this.querySelectorAll(last).filter(n=>n.parentNode?.closest(prior));}const out=[];for(const n of this.children){if(n.matches(s))out.push(n);out.push(...n.querySelectorAll(s));}return out;}querySelector(s){return this.querySelectorAll(s)[0]||null;}
 closest(s){for(let n=this;n;n=n.parentNode)if(n.matches(s))return n;return null;}contains(n){return n===this||this.children.some(c=>c.contains(n));}
 addEventListener(type,fn,options){(this.listeners[type]??=[]).push({fn,once:options?.once});}emit(type,e={}){for(const x of [...this.listeners[type]||[]]){x.fn({target:this,...e});if(x.once)this.listeners[type]=this.listeners[type].filter(y=>y!==x);}}
 click(){this.emit('click');this.onclick?.({target:this});}showModal(){this.open=true;}close(){this.open=false;this.emit('close');}focus(){}getBoundingClientRect(){return {left:50,right:300,top:150,bottom:400,width:250,height:250};}
}
function harness(r=fresh()){
 const el=(...xs)=>new Node(...xs),body=el('body'),modal=el('dialog'),modalBody=el('div');modal.id='modal';modalBody.id='modal-body';modal.append(modalBody);body.append(modal);const calls=[],listeners=new Set();let visible=null;
 const context={console,game:r,root:el('main'),busy:false,showArt:false,selectedTarget:null,selectedCard:'PLAYER_BASIC_ATTACK',selectedBranch:'',el,mk:el,actions:(p,ns)=>{const row=el('div','actions');row.append(...ns);p.append(row);},button:(label,fn,disabled=false)=>{const n=el('button','',label);n.onclick=fn;n.disabled=disabled;return n;},act:(...xs)=>calls.push(xs),safeName:(table,id,col=1)=>r.tables[table]?.get(id)?.[col]||'알 수 없는 항목',parseUI:s=>{try{return JSON.parse(s||'{}');}catch{return{};}},CRPGRuntime:c.CRPGRuntime,STATUS_ELEMENT:{},NAV:{},S:{},icon:()=>el('i'),returnScreen:()=>r.actionReason('MENU',{screen:'LOCATION'})?'STORY':'LOCATION',navButton:()=>({disabled:true}),openScreen:()=>calls.push(['open']),mapBackground:()=>null,setBackdrop(){},sound(){},render:()=>calls.push(['render']),combat(){},battleActorRow:()=>el('div'),CombatFX:{pause:()=>{throw Error('inspection paused effects');}},GameEffects:{active:true,paused:false,generation:1,reschedule:()=>{throw Error('inspection rescheduled playback');},cancel(){},showAction(){}},matchMedia:()=>({matches:false}),CSS:{escape:s=>s},requestAnimationFrame:fn=>fn(),settings:{combatSpeed:1},innerHeight:900,clearTimeout(){},setTimeout(){},addEventListener(){},document:{body,createElement:tag=>el(tag),addEventListener(){},getElementById:id=>id==='modal'?modal:id==='modal-body'?modalBody:null,querySelector:s=>body.querySelector(s),querySelectorAll:s=>body.querySelectorAll(s)},showModal:(title,box)=>{modalBody.replaceChildren(el('h1','',title),box);modal.showModal();}};
 context.root.id='root';body.append(context.root);context.window=context;context.ActorPlayback={active:false,currentActor:id=>visible?.id===id?cp(visible):null,subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);}};
 context.actionButton=(label,type,params)=>{const n=context.button(label,()=>context.act(type,params),!!r.actionReason(type,params));n.crpgAction={type,params};return n;};
 context.recoveryCard=p=>p.append(el('section','recovery-card'),context.actionButton('회복하고 다시 출발','RECOVER',{}));context.bossProgressControls=()=>{};context.rewardPreview=()=>{};
 const ctx=vm.createContext(context);return {ctx,r,el,body,modal,modalBody,calls,listeners,visible:a=>{visible=a;context.ActorPlayback.active=!!a;for(const fn of listeners)fn();},run:text=>vm.runInContext(text,ctx),panel:()=>el('section','panel')};
}
let passed=0;function check(name,fn){fn();passed++;console.log('PASS '+name);}
const labels=p=>p.querySelectorAll('button').map(b=>b.textContent);
const canonical=between(source('app_adventure.js'),'reward=function(p){','let saveListTab=');
const shellHead=between(source('app_shell.js'),'const BACK_LABELS=','S.pageHead=pageHead;');
const rewardLayout=between(source('app_shell.js'),'function layoutReward(','function layoutGeneric(');
const statuses=between(source('app_experience.js'),'const STATUS_KIND=','// The formation tag');
check('native field defeat recovery renderer and generic reward header offer no story return',()=>{
 const h=harness(fresh('MAP_MOND_PLAINS'));h.r.startBattle('EG_MOND_HILI_PATROL','EXPLICIT');for(const a of h.r.s.runtime.actors.filter(a=>a.side==='ALLY'))a.hp=0;h.r.finishBattle(false);assert(h.r.needsRecovery());h.run(canonical+shellHead);const p=h.panel();h.ctx.reward(p);const head=h.ctx.pageHead('REWARD',p);p.append(head.head);assert(!labels(p).some(l=>l.includes('이야기')));assert(labels(p).includes('회복하고 다시 출발'));
});
check('story defeat offers retry; missing legacy recovery marker cannot expose story continuation',()=>{
 for(const recovery of [true,false]){const h=harness();h.r.s.global.LAST_BATTLE_RESULT_JSON=JSON.stringify({id:'D',victory:false,origin:'STORY:N'});if(recovery)h.r.s.storyRecovery={node:'N'};h.run(canonical);const p=h.panel();h.ctx.reward(p);assert(!labels(p).some(l=>l.includes('이야기')));assert(labels(p).includes(recovery?'전투 직전부터 다시 준비':'메인 화면으로'));}
});
check('legacy renderer removes defeated story navigation but preserves victory navigation',()=>{
 for(const win of [false,true]){const h=harness();h.ctx.lastResult=null;h.r.s.global.LAST_BATTLE_RESULT_JSON=JSON.stringify({id:'L',victory:win,rounds:1,xp:0});const line=source('app_legacy.js').split('\n').find(x=>x.startsWith('function reward('));h.run(line);const p=h.panel();h.ctx.reward(p);assert.equal(labels(p).includes('이야기로 돌아가기'),win);}
});
check('result shell filters late-added legacy story actions only on defeat',()=>{
 for(const win of [false,true]){const h=harness();h.r.s.global.LAST_BATTLE_RESULT_JSON=JSON.stringify({id:'R',victory:win});h.run(rewardLayout);const p=h.panel(),content=h.el('div');p.append(h.el('h1','','결과'),h.ctx.button('이야기로 돌아가기',()=>{}),h.ctx.button('이야기 계속',()=>{}),h.ctx.button('전투 직전부터 다시 준비',()=>{}));h.ctx.layoutReward(content,p);assert.equal(labels(p).some(l=>l.startsWith('이야기')),win);assert(labels(p).includes('전투 직전부터 다시 준비'));}
});
check('victorious story continuation stays available after canonical and result-shell render',()=>{
 const h=harness();h.r.s.global.LAST_BATTLE_RESULT_JSON=JSON.stringify({id:'W',victory:true,origin:'STORY:N'});h.run(canonical+rewardLayout);const p=h.panel();h.ctx.reward(p);h.ctx.layoutReward(h.el('div'),p);assert(labels(p).includes('이야기 계속'));
});
check('native buffs and debuffs inspect displayed snapshots while committed future state stays untouched',()=>{
 const h=harness(fresh('MAP_MOND_PLAINS'));h.r.startBattle('EG_MOND_HILI_PATROL','EXPLICIT');const actor=h.r.combatActor();h.r.addCombatStatus(actor,'DILUC_INFUSION',2);h.r.addCombatStatus(actor,'STATUS_DEF_DOWN',2,{value:15});const displayed=cp(actor);actor.statuses=[];h.visible(displayed);h.ctx.busy=true;h.run(statuses);const stored=h.r.serialize(),row=h.ctx.battleStatusChips(displayed);assert.equal(row.dataset.battleInspection,'status');h.body.append(row);row.onclick();assert(h.modal.open);assert.match(h.modalBody.textContent,/불 원소 부여/);assert.match(h.modalBody.textContent,/일반 공격이 불 원소/);assert.match(h.modalBody.textContent,/방어/);assert(!h.modalBody.textContent.includes('알 수 없는 항목'));assert.equal(h.ctx.GameEffects.paused,false);assert.equal(h.r.serialize(),stored);assert.equal(h.calls.length,0);
 const next=cp(displayed);next.statuses.find(s=>s.id==='DILUC_INFUSION').rounds=1;h.visible(next);assert.match(h.modalBody.textContent,/1라운드 남음/);next.statuses=[];h.visible(next);assert.match(h.modalBody.textContent,/현재 적용된 효과가 없습니다/);h.modal.close();assert.equal(h.listeners.size,0);
});
check('reopening effect inspection drops old subscription and synthetic legacy chips remain readable',()=>{
 const h=harness();h.run(statuses);const actor={id:'OLD',name:'전투원'},entries=[{id:'OLD_STATUS',name:'기존 효과',text:'기존 저장 효과',rounds:null,kind:'buff'}];h.ctx.battleStatusDetails(actor,entries);assert.match(h.modalBody.textContent,/기존 저장 효과/);h.ctx.battleStatusDetails(actor,[]);assert.equal(h.listeners.size,1);assert.match(h.modalBody.textContent,/현재 적용된 효과가 없습니다/);h.modal.close();assert.equal(h.listeners.size,0);
});
check('enemy info opens without pausing and follows current visible HP, shields and statuses',()=>{
 const h=harness(fresh('MAP_MOND_PLAINS'));h.r.startBattle('EG_MOND_HILI_PATROL','EXPLICIT');const enemy=h.r.s.runtime.actors.find(a=>a.side==='ENEMY'),shown=cp(enemy);shown.hp=77;shown.maxHp=100;shown.shields=[{value:15,element:'얼음',damageMultipliers:{'불':2}}];shown.statuses=[{id:'STATUS_DEF_DOWN',rounds:2,value:15}];h.visible(shown);h.run(statuses+source('app_enemy_intel.js')+'\n globalThis.Intel=EnemyIntel;');h.ctx.Intel.capture();const stored=h.r.serialize();h.ctx.Intel.open(enemy.id);assert(h.ctx.Intel.dialog.open);assert.equal(h.ctx.GameEffects.paused,false);assert.match(h.ctx.Intel.dialog.textContent,/77 \/ 100/);assert.match(h.ctx.Intel.dialog.textContent,/방어/);assert.match(h.ctx.Intel.dialog.textContent,/얼음 보호막 15/);assert.match(h.ctx.Intel.dialog.textContent,/불 ×2/);shown.hp=55;shown.shields=[];shown.statuses=[];h.visible(shown);assert.match(h.ctx.Intel.dialog.textContent,/55 \/ 100/);assert.equal(h.ctx.Intel.dialog.querySelectorAll('.intel-shield').length,0);assert.match(h.ctx.Intel.dialog.textContent,/현재 적용된 효과가 없습니다/);h.ctx.Intel.dialog.close();assert.equal(h.listeners.size,0);assert.equal(h.r.serialize(),stored);assert.equal(h.calls.length,0);
});
check('recipient status updates never announce an enemy skill or replace its last native cast',()=>{
 const h=harness(fresh('MAP_MOND_PLAINS'));h.r.startBattle('EG_MOND_HILI_PATROL','EXPLICIT');const enemy=h.r.s.runtime.actors.find(a=>a.side==='ENEMY');h.run(statuses+source('app_enemy_intel.js')+'\n globalThis.Intel=EnemyIntel;');h.ctx.Intel.capture();const last={id:enemy.id,card:'ECARD_MOND_HILI_FIGHTER_SPECIAL'};h.ctx.Intel.lastSkill=last;
 for(const kind of [null,'STATUS_APPLY']){h.ctx.Intel.showSkill({kind:'action',actorId:enemy.id,sourceKind:kind,cardName:'장미의 뇌광',events:[{kind:'status',statusApplied:{id:'STATUS_DEF_DOWN'}}]});assert.equal(h.ctx.Intel.toast,null);assert.equal(h.ctx.Intel.lastSkill,last);}assert.equal(h.ctx.GameEffects.paused,false);assert.equal(h.calls.length,0);
});
check('target selection stays locked while inspection is allowed, and resumes after playback',()=>{
 const h=harness();h.run(statuses+between(source('app_experience.js'),'function battleActorRow(','function battleSummons('));h.ctx.meter=()=>{};const a={id:'E',name:'적',side:'ENEMY',hp:1,maxHp:1,statuses:[],shields:[]},row=h.ctx.battleActorRow(a,{targets:[{id:'E'}]},0),other=h.ctx.battleActorRow({...a,id:'OTHER'},{targets:[{id:'E'}]},0);let prevented=0;const key=(target,key='Enter')=>row.emit('keydown',{target,key,preventDefault(){prevented++;}});
 h.ctx.busy=true;row.click();key(row);assert.equal(h.ctx.selectedTarget,null);assert.equal(h.calls.length,0);h.ctx.busy=false;h.visible(a);row.click();key(row,' ');assert.equal(h.ctx.selectedTarget,null);assert.equal(h.calls.length,0);h.visible(null);
 for(const tag of ['button','a','select','input','summary','details']){const control=h.el(tag),child=h.el('span');control.append(child);row.append(control);row.emit('click',{target:child});key(child);assert.equal(h.ctx.selectedTarget,null);assert.equal(h.calls.length,0);}other.click();assert.equal(h.ctx.selectedTarget,null);assert.equal(other.classList.contains('targetable'),false);
 key(row);assert.equal(h.ctx.selectedTarget,'E');assert.equal(h.calls.length,1);key(row,' ');row.click();assert.equal(h.calls.length,1);assert.equal(prevented,4);
});
check('status modal close restores playback inspection input; normal save remains inert',()=>{
 const h=harness();h.ctx.modalInert=new Map([[h.ctx.root,true]]);h.ctx.modalRoot=h.modal;h.ctx.modalReturn=null;h.ctx.topOverlay=()=>null;h.ctx.focusOverlay=()=>{};h.ctx.inertBackground=()=>{};h.ctx.S={};h.run(between(source('app_shell.js'),'function syncOverlay(){','try{let queued=false;'));h.ctx.busy=true;h.ctx.GameEffects.active=true;h.ctx.syncOverlay();assert.equal(h.ctx.root.inert,false);h.ctx.modalInert.set(h.ctx.root,false);h.ctx.modalRoot=h.modal;h.ctx.GameEffects.active=false;h.ctx.syncOverlay();assert.equal(h.ctx.root.inert,true);
});
check('actual playback capture permits status inspection while command and navigation controls stay blocked',()=>{
 const h=harness();h.run(statuses);h.ctx.busy=true;const shown={id:'A',name:'아군',statuses:[{id:'DILUC_INFUSION',rounds:2}]};h.visible(shown);
 const row=h.ctx.battleStatusChips(shown),command=h.ctx.button('실행',()=>h.calls.push(['command'])),nav=h.ctx.button('메인',()=>h.calls.push(['nav']));h.ctx.root.append(row,command,nav);
 const av=source('app_av.js'),lock=av.split('\n').find(x=>x.trim().startsWith('lockCommands(){')).trim().replace(/^lockCommands\(\)/,'function()').replace(/,$/,'');
 h.ctx.GameEffects.lockedControls=new Map();h.run('GameEffects.lockCommands='+lock+';'+av.split('\n').find(x=>x.startsWith("root.addEventListener?.('click'")));h.ctx.GameEffects.lockCommands();
 assert.equal(h.ctx.root.inert,false);assert.equal(row.disabled,false);assert.equal(command.disabled,true);assert.equal(nav.disabled,true);
 let stopped=false;const press=target=>{stopped=false;h.ctx.root.emit('click',{target,preventDefault(){stopped=true;},stopImmediatePropagation(){stopped=true;}});};
 press(row.children[0]);assert.equal(stopped,false);row.onclick();assert(h.modal.open);assert.equal(h.ctx.GameEffects.paused,false);assert.equal(h.calls.length,0);
 press(command);assert(stopped);press(nav);assert(stopped);press(h.ctx.root);assert(stopped);h.modal.close();
});
check('real shield bubble and status overlays update the visible single fighter without reading future state',()=>{
 const h=harness(),fx=source('app_battle_fx_v01521.js');h.run(fx.split('\n').filter(x=>x.startsWith('const STATUS=')||x.startsWith('const SHIELD=')).join('\n')+between(fx,'function span(cls){','const actorOf=')+between(fx,'function decorate(p,shownActor){','// ---- the playback'));
 const row=h.el('div','combatant-row'),shown={id:'A',hp:100,aura:'번개',statuses:[{id:'STATUS_FREEZE',rounds:1}],shields:[{value:50,source:'MOND_NOELLE_E'}]};row.dataset.actorId='A';h.ctx.root.append(row);h.ctx.decorate(row,shown);assert(row.querySelector('.shield-fx'));assert(row.querySelector('.st-freeze'));assert.equal(row.dataset.aura,'electro');
 h.run(source('app_skill_fx_v0162.js'));shown.statuses=[{id:'DILUC_INFUSION',rounds:2}];h.ctx.CRPGSkillFX.decorateBoard(row,shown);assert(row.querySelector('.sfx-status-look'));shown.statuses=[];shown.shields=[];shown.aura=null;h.ctx.decorate(row,shown);h.ctx.CRPGSkillFX.decorateBoard(row,shown);assert.equal(row.querySelector('.shield-fx'),null);assert.equal(row.querySelector('.st-freeze'),null);assert.equal(row.querySelector('.sfx-status-look'),null);assert.equal(row.dataset.aura,undefined);
});
check('status notifications cannot create extra actor turns or action counts',()=>{
 const h=harness(fresh('MAP_MOND_PLAINS'));h.r.startBattle('EG_MOND_HILI_PATROL','EXPLICIT');h.r.s.runtime.round=2;const fx=source('app_battle_fx_v01521.js');h.run(between(fx,'let playFrames=[];','function summonEntry(')+'\nplayFrames=[{kind:"action",round:1,action:1,actorId:"LISA",sourceKind:null},{kind:"action",round:1,action:1,actorId:"LISA",sourceKind:"STATUS_APPLY"},{kind:"action",round:1,action:1,actorId:"ENEMY",sourceKind:"STATUS_APPLY"},{kind:"action",round:1,action:1,actorId:"LISA",sourceKind:"FIELD",periodic:true}];');assert.deepEqual(cp(h.ctx.roundTimes(1)),{LISA:1});assert.deepEqual(cp(h.ctx.roundOrder(1)),['LISA']);h.run(between(fx,'function turnTo(','// 0.15.21 (user: 「위에 적혀있는 순서'));let moved=0;h.ctx.CRPGShell={turnBadge(){moved++;}};h.ctx.turnTo({kind:'action',sourceKind:'STATUS_APPLY',actorId:'ENEMY'}, {actorNode(){throw Error('status update must not request turn actor');}});assert.equal(moved,0);
});
check('installed override order keeps canonical reward path and marks only read-only combat controls',()=>{
 const html=source('index.html'),at=f=>html.indexOf('<script src="'+f+'"');assert(at('app_adventure.js')>at('app_revision.js'));assert(at('app_shell.js')>at('app_adventure.js'));assert(at('app_battle_layout_v01522.js')>at('app_shell.js'));assert(at('app_enemy_intel.js')>at('app_experience.js'));assert(source('app_battle_fx_v01521.js').includes("if(!e.presentationActorsAfter?.length)liveStatus"));assert(source('app_battle_fx_v01521.js').includes("id:node.dataset.actorId"));
});
console.log(JSON.stringify({passed,nativeDefeatCases:1,domUnitChecks:passed,realBrowser:false}));
