'use strict';
// Native contract checks for boss-only shield depletion. Numerical fixtures do not measure fight difficulty.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),H=require('../tools/audit_protagonist_v01618.cjs'),env=H.load(ROOT),R=env.R,DB=env.db,cp=x=>JSON.parse(JSON.stringify(x));
const watched=[...fs.readFileSync(ROOT+'/source/index.html','utf8').matchAll(/<script src="((?:world_content|liyue_card_content|runtime[^" ]*)\.js)"/g)].map(m=>'source/'+m[1]);watched.push('source/index.html','content/db.json','tools/audit_protagonist_v01618.cjs');const hashes=()=>Object.fromEntries(watched.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(ROOT+'/'+f)).digest('hex')])),inputBefore=hashes();
const output=process.argv[2]||ROOT+'/reports/daily_pressure_v01624/runtime-tests.json';
const report={scope:'Fresh public daily entry/PENDING save; old battle continuity; exact-origin/card/side gating; existing shield depletion, HP absorption and Zhongli C6 healing. Numerical fixtures are separate from full-fight balance.',fingerprint:env.fingerprint,checks:[]};
function test(name,fn){try{const evidence=fn();report.checks.push({name,passed:true,evidence:evidence??null});console.log('PASS '+name);}catch(e){report.checks.push({name,passed:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
const specs=[
 {boss:'BOSS_ANDRIUS',level:25,map:'MAP_WOLF_ARENA',action:'MOND_MATERIAL_CHALLENGE',args:{boss:'BOSS_ANDRIUS'},prefix:'ECARD_ANDRIUS_',origin:'MATERIAL_CHALLENGE:BOSS_ANDRIUS',group:'EG_BOSS_ANDRIUS'},
 {boss:'BOSS_DVALIN',level:28,map:'MAP_STORMTERROR_LAIR',action:'MOND_MATERIAL_CHALLENGE',args:{boss:'BOSS_DVALIN'},prefix:'ECARD_DVALIN_',origin:'MATERIAL_CHALLENGE:BOSS_DVALIN',group:'EG_BOSS_DVALIN'},
 {boss:'BOSS_TARTAGLIA',level:50,map:'MAP_LIYUE_GOLDEN_HOUSE',action:'LIYUE_ARTIFACT_CHALLENGE',args:{kind:'TARTAGLIA'},prefix:'ECARD_TARTAGLIA_',origin:'MATERIAL_CHALLENGE:LIYUE_TARTAGLIA_FARM',group:'EG_BOSS_TARTAGLIA'},
 {boss:'BOSS_AZHDAHA',level:60,map:'MAP_AZHDAHA_DOMAIN',action:'LIYUE_ARTIFACT_CHALLENGE',args:{kind:'AZHDAHA'},prefix:'ECARD_AZHDAHA_',origin:'MATERIAL_CHALLENGE:LIYUE_AZHDAHA_FARM',group:'EG_BOSS_AZHDAHA'}
];
function fresh(spec=specs[2],cons=0){const r=H.setup(env,{level:spec.level,team:['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN'],route:'ROUTE_TRAVELER',seed:717,map:spec.map,gear:'none',talent:1});for(const f of ['FLAG_BOSS_ANDRIUS_CLEAR','FLAG_BOSS_DVALIN_CLEAR'])r.s.flags[f]=true;const ar=r.tables['35_BOSS_ROUTE_DB'].get('BRT_AZHDAHA');if(ar?.[13])r.s.flags[ar[13]]=true;if(cons){r.giveItem('STELLA_LIYUE_ZHONGLI',cons);for(let n=0;n<cons;n++)r.action('CONSTELLATION_UNLOCK',{char:'LIYUE_ZHONGLI'});}return r;}
function entered(spec=specs[2],cons=0){const r=fresh(spec,cons);assert.equal(r.actionReason(spec.action,spec.args),'');r.action(spec.action,spec.args);assert.equal(r.s.runtime.origin,spec.origin);return r;}
function actors(r){const b=r.s.runtime;return {b,a:b.actors.find(a=>a.side==='ENEMY'&&specs.some(s=>s.boss===a.source)),t:b.actors.find(a=>a.source==='PLAYER_CUSTOM')};}
function packet(r,{pool=1200,extra=[],amount=300,details={},actorPatch={},targetSide,clearMarker=false}={}){const {b,a,t}=actors(r);b.round=5;if(clearMarker)delete b.dailyPressureRevision;for(const x of b.actors){x.statuses=[];x.traits={};x.traitState={};x.aura=null;x.auras=[];x.nativeAura=null;}Object.assign(a,actorPatch);t.hp=5000;t.maxHp=10000;if(targetSide)t.side=targetSide;t.shields=[...(pool?[{source:'LIYUE_ZHONGLI_E',value:pool,initialValue:pool,rounds:2,createdRound:5}]:[]),...extra.map(([source,value])=>({source,value,initialValue:value,rounds:2,createdRound:5}))];const before=cp(t.shields),start=b.log.length,own=specs.find(s=>s.boss===a.source)||specs[2],card=r.combatRows('12_ENEMY_CARD_DB').find(c=>c[1]===a.source&&String(c[0]).startsWith(own.prefix))?.[0]||own.prefix+'READONLY_PACKET';const returned=r.applyDamage(a,t,amount,{element:'PHYSICAL',card,...details}),logs=cp(b.log.slice(start)),dmg=logs.find(l=>Object.hasOwn(l,'damage'));return{before,after:cp(t.shields),hp:t.hp,returned,damage:dmg?.damage,absorbed:dmg?.absorbed,multiplier:dmg?.shieldDamageMultiplier??1,healing:logs.reduce((n,l)=>n+(l.heal||0),0),logs};}
assert.equal(env.api.growthV01522.dailyPressure.BOSS_TARTAGLIA.shieldDamageMultiplier,3,'Selected Tartaglia pressure is part of this numerical fixture contract');
for(const spec of specs){
 test(spec.boss+' public fresh entry marks PENDING before enemy damage and save/reload keeps marker',()=>{const r=fresh(spec),observed=[],old=r.applyDamage;r.applyDamage=function(a,t,n,d){if(a.side==='ENEMY')observed.push({marker:this.s.runtime?.dailyPressureRevision,card:d?.card});return old.call(this,a,t,n,d);};r.action(spec.action,spec.args);const b=r.s.runtime;assert.equal(b.dailyPressureRevision,1);assert.equal(b.opening?.state,'PENDING');assert.equal(observed.length,0);const saved=JSON.parse(r.serialize()),reloaded=new R(DB,saved);assert.deepEqual(cp(reloaded.s.runtime),cp(saved.runtime));assert.equal(reloaded.s.runtime.dailyPressureRevision,1);assert.equal(reloaded.s.runtime.opening.state,'PENDING');reloaded.action('COMBAT_BEGIN',{battle:b.id});assert.equal(reloaded.s.runtime?.dailyPressureRevision,1);const expected=env.api.growthV01522.dailyPressure[spec.boss].shieldDamageMultiplier,got=packet(reloaded);assert.equal(got.multiplier,expected);assert.equal(got.damage,0);assert.equal(got.after[0].value,1200-300*expected);return{origin:b.origin,opening:b.opening?.state,initialEnemyPackets:observed.length,pressure:got.multiplier};});
 test(spec.boss+' old unmarked active save does not receive retroactive pressure',()=>{const r=entered(spec),s=JSON.parse(r.serialize());delete s.runtime.dailyPressureRevision;const before=cp(s.runtime),again=new R(DB,s);assert.deepEqual(cp(again.s.runtime),before);const got=packet(again);assert.equal(got.multiplier,1);assert.equal(got.damage,0);assert.equal(got.after[0].value,900);return{hpUnchanged:true,remainingShield:900};});
}
test('fresh/story or other explicit origins do not acquire repeat marker',()=>{const rows=[];for(const origin of ['EXPLICIT','STORY:READONLY_SCOPE','BOSS:BRT_TARTAGLIA']){const r=fresh();r.startBattle('EG_BOSS_TARTAGLIA',origin);if(r.s.battlePreparation)r.action('COMBAT_PREPARE',{group:'EG_BOSS_TARTAGLIA',companions:['LIYUE_ZHONGLI','MOND_DILUC','MOND_JEAN']});assert.equal(r.s.runtime.dailyPressureRevision,undefined);const got=packet(r);assert.equal(got.multiplier,1);rows.push({origin,remainingShield:got.after[0].value});}return rows;});
test('ordinary current domain remains outside pressure contract',()=>{const r=fresh(),site=env.api.growthV01522.domains.PEAK_OF_VINDAGNYR;r.s.global.CURRENT_MAP_ID=site.map;r.action('DOMAIN_START',{domain:'PEAK_OF_VINDAGNYR:20'});assert.equal(r.s.runtime.dailyPressureRevision,undefined);assert.equal(r.s.runtime.growthDomain.kind,'EXP');return{origin:r.s.runtime.origin,marker:false};});
test('invalid new marker versions/origins/boss presence are rejected by native save validation',()=>{const saved=JSON.parse(entered().serialize()),variants=[s=>{s.runtime.dailyPressureRevision=2;},s=>{s.runtime.origin='STORY:READONLY_SCOPE';},s=>{s.runtime.actors=s.runtime.actors.filter(a=>a.side!=='ENEMY');},s=>{s.runtime.abyss={};},s=>{s.runtime.raid={};}];for(const edit of variants){const s=cp(saved);edit(s);assert.throws(()=>new R(DB,s),e=>e.code==='DAILY_PRESSURE_SAVE');}return{rejected:variants.length};});
test('exact boss origin, attacker side and matching card are required; basic/reaction/DoT/hazard excluded',()=>{const jobs=[{details:{card:null}},{details:{card:'ECARD_ANDRIUS_READONLY'}},{details:{sourceKind:'REACTION'}},{details:{sourceKind:'REACTION_DOT'}}, {details:{card:null,sourceKind:'ENEMY_DOT'}},{details:{card:null,sourceKind:'HAZARD'}},{actorPatch:{side:'ALLY'}}];const evidence=[];for(const opts of jobs){const got=packet(entered(),opts);assert.equal(got.multiplier,1);assert.equal(got.after[0].value,900);evidence.push({opts,remainingShield:900});}return evidence;});
test('enemy targets and arbitrary cross-boss attacker cannot trigger ally-only pressure',()=>{for(const opts of [{targetSide:'ENEMY'},{actorPatch:{source:'BOSS_DVALIN'}}]){const got=packet(entered(),opts);assert.equal(got.multiplier,1);}return{excluded:2};});
test('existing packet shieldDamageMultiplier is multiplied once',()=>{const got=packet(entered(),{pool:3000,details:{shieldDamageMultiplier:2}});assert.equal(got.multiplier,6);assert.equal(got.damage,0);assert.equal(got.after[0].value,1200);return got;});
test('sufficient Jade shield absorbs HP packet while only its pool depletion increases',()=>{const got=packet(entered(),{pool:1200});assert.equal(got.damage,0);assert.equal(got.absorbed,300);assert.equal(got.hp,5000);assert.equal(got.after[0].value,300);return got;});
test('partially destroyed shield absorbs pool divided by pressure and spills only remainder into HP',()=>{const got=packet(entered(),{pool:600});assert.equal(got.damage,100);assert.equal(got.absorbed,200);assert.equal(got.hp,4900);assert.equal(got.after.length,0);return got;});
test('concurrent character shields take one original packet each and absorption pools are not added',()=>{const got=packet(entered(),{pool:600,extra:[['MOND_NOELLE_E',450]]});assert.equal(got.damage,100);assert.equal(got.absorbed,200);assert.equal(got.hp,4900);assert.equal(got.after.length,0);return got;});
test('bare HP damage stays unchanged with fresh pressure marker',()=>{const freshHit=packet(entered(),{pool:0}),oldHit=packet(entered(),{pool:0,clearMarker:true});assert.equal(freshHit.damage,300);assert.equal(freshHit.hp,4700);assert.equal(oldHit.damage,freshHit.damage);assert.equal(oldHit.hp,freshHit.hp);return{fresh:freshHit.damage,unmarked:oldHit.damage};});
test('only marked boss dedicated card coefficients change native outgoing attack; old snapshots keep old coefficient',()=>{const evidence=[];for(const [card,factor]of Object.entries(env.api.growthV01522.dailyCardDamage)){const spec=specs.find(s=>card.startsWith(s.prefix));assert(spec);const values=[];for(const marked of [false,true]){const r=entered(spec),{b,a,t}=actors(r);b.round=5;if(!marked)delete b.dailyPressureRevision;for(const x of b.actors){x.statuses=[];x.traits={};x.traitState={};x.aura=null;x.auras=[];x.nativeAura=null;}t.hp=t.maxHp=1000000;t.shields=[];r.die=()=>50;r.random=()=>.5;const hp=t.hp;r.damage(a,t,.3,'PHYSICAL',{range:'전장',card,sureHit:true,noCrit:true,noAura:true});values.push(hp-t.hp);}assert.ok(Math.abs(values[1]-values[0]*factor)<=2,card+': coefficient is applied once');evidence.push({card,factor,old:values[0],fresh:values[1]});}return evidence;});
test('native Zhongli C6 heals based on consumed Jade pool; sufficient/partial/overlap and cap stay active',()=>{const sufficient=packet(entered(specs[2],6),{pool:1200}),partial=packet(entered(specs[2],6),{pool:600}),overlap=packet(entered(specs[2],6),{pool:600,extra:[['MOND_NOELLE_E',450]]}),cap=packet(entered(specs[2],6),{pool:12000,amount:3000});assert.equal(sufficient.healing,360);assert.equal(sufficient.hp,5360);assert.equal(partial.healing,240);assert.equal(partial.hp,5140);assert.equal(overlap.healing,240);assert.equal(overlap.hp,5140);assert.equal(cap.healing,800);return{sufficient,partial,overlap,cap};});
const inputAfter=hashes();report.inputSHA256=inputBefore;report.inputDrift=Object.keys(inputBefore).filter(f=>inputBefore[f]!==inputAfter[f]);test('runtime inputs stay unchanged throughout contract checks',()=>{assert.deepEqual(report.inputDrift,[]);return{inputs:watched.length,drift:0};});
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');const failed=report.checks.filter(c=>!c.passed);console.log(JSON.stringify({checks:report.checks.length,passed:report.checks.length-failed.length,failed:failed.length,fingerprint:report.fingerprint,output}));if(failed.length)process.exitCode=1;
