'use strict';
// Import states generated by the actual released v0.12 runtime, never user data.
const assert=require('node:assert/strict'),cp=require('node:child_process');
const {fs,path,vm,root,c,db,R}=require('./helpers_v011.cjs');
const {SaveAdapter}=require('../source/save_adapter.js');
const baseline='193b9b906eb300200c4e8b210606d2735a463282';
const read=p=>cp.execFileSync('git',['show',baseline+':'+p],{cwd:root,maxBuffer:64*1024*1024,encoding:'utf8'});
const old=vm.createContext({console,Date,setTimeout,clearTimeout});
for(const [,file]of read('source/index.html').matchAll(/<script src="((?:world_content|runtime[^" ]*)\.js)"/g))vm.runInContext(read('source/'+file),old,{filename:file});
const oldDB=JSON.parse(read('content/db.json')),oldMeta=JSON.parse(read('dist/asset-manifest.json'));
const currentMeta=JSON.parse(fs.readFileSync(path.join(root,'dist/asset-manifest.json')));
assert(currentMeta.compatibleSaveVersions.includes(oldMeta.saveCompatibilityVersion),'released v0.12 compatibility key is present');
const adapter=new SaveAdapter({indexedDB:null,contentVersion:currentMeta.saveCompatibilityVersion,compatibleContentVersions:currentMeta.compatibleSaveVersions,migrate:c.CRPGRelationships.migrateState,validate:s=>new R(db,s).s});
const results=[];
try{
 for(const route of ['ROUTE_TRAVELER','ROUTE_ISEKAI']){
  const r=new old.CRPGRuntime.Runtime(oldDB);r.newGame({name:'이전 저장 호환',route,seed:75409,saveId:'V012-COMPAT-'+route});
  r.addXp('PLAYER_CUSTOM',350);r.giveItem('ORE_IRON',3);r.s.global.MORA=7654;
  r.unlockCharacter('MOND_AMBER');r.s.flags.V013_COMPAT_SENTINEL=true;
  const original=JSON.parse(r.serialize()),input=JSON.stringify({envelopeSchema:1,contentVersion:oldMeta.saveCompatibilityVersion,state:original});
  const parsed=adapter.parseImport(input),loaded=new R(db,parsed.state),after=JSON.parse(loaded.serialize());
  for(const field of ['SAVE_ID','STORY_ROUTE_ID','PRNG_STATE','MORA','PLAYER_XP_STATE','PLAYER_LEVEL_STATE','CURRENT_STORY_NODE_ID','STORY_CURSOR_NODE_ID','COMPANION_ELIGIBILITY_JSON'])assert.deepEqual(after.global[field],original.global[field],field);
  for(const field of ['inventory','party','quests','relations','processed'])assert.deepEqual(after[field],original[field],field);
  assert.equal(after.flags.V013_COMPAT_SENTINEL,true);assert.equal(after.geoOculi.tiers.length,0);assert.equal(Object.keys(after.liyue.events).length,0);
  assert.equal(JSON.stringify(original),JSON.stringify(JSON.parse(input).state),'input remains unchanged');
  results.push({route,ok:true,sourceVersion:oldMeta.saveCompatibilityVersion,bytes:Buffer.byteLength(input)});
 }
}finally{adapter.close();}
fs.writeFileSync(path.join(root,'reports/save-v013-results.json'),JSON.stringify({baseline,results},null,2));
console.log(JSON.stringify({passed:results.length,results}));
