'use strict';
// Read-only confirmation of the existing +12 Abyss benchmark. No combat rerun,
// enemy edits, product edits, forced victory, or natural acquisition claim.
const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const H=require('./audit_protagonist_v01618.cjs'),N=require('../tests/test_enemy_balance_v01627.cjs');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'reports/abyss_difficulty_v01627/true_cap12_confirmation'),P='PLAYER_CUSTOM',team=['MOND_DILUC','MOND_JEAN','LIYUE_ZHONGLI'];
const cp=v=>JSON.parse(JSON.stringify(v)),sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const before=N.productionBootstrap(N.loadBefore(ROOT)),env=N.productionBootstrap(H.load(ROOT));env.c.Date=before.c.Date;
const datasets={};for(const c of ['c0','c2','c6']){const p=path.join(ROOT,'reports/abyss_difficulty_v01627/baseline_mastery_'+c+'_final/native.json.gz');datasets[c]={path:path.relative(ROOT,p),sha256:sha(fs.readFileSync(p)),...JSON.parse(zlib.gunzipSync(fs.readFileSync(p)))};assert.equal(datasets[c].fingerprint,before.fingerprint);}
const inspect=H.setup(env,{level:60,team,enhance:10,talent:10});
const equipmentStats=[...new Set(datasets.c0.rows.flatMap(r=>r.equipment.filter(i=>!i.artifact).map(i=>i.equip)))].map(id=>{const inv=datasets.c0.rows[0].equipment.find(i=>i.equip===id),native=inspect.enhancementHasGain(inv),stats0=cp(inspect.enhancementStatsAt(inv,0)),stats10=cp(inspect.enhancementStatsAt(inv,10)),stats12=cp(inspect.enhancementStatsAt(inv,12));assert(native,'every non-artifact equipped item has an actual legal enhancement gain');assert.equal(inspect.enhancementCap(inv),12);return{equip:id,name:inspect.row('16_EQUIP_DB',id)[1],supported:inspect.isMondEnhanceable(id),hasGain:native,cap:12,stats0,stats10,stats12,delta12vs10:Object.fromEntries([...new Set([...Object.keys(stats10),...Object.keys(stats12)])].map(k=>[k,(stats12[k]||0)-(stats10[k]||0)]))};});
// Actual public cap ascension with declared, granted prerequisite equipment and
// materials. This verifies eligibility, payment and cap transition, not farming.
const asc=H.setup(env,{level:60,team,gear:'none',talent:10}),ascensions=[];
for(const row of equipmentStats){const historical=datasets.c0.rows[0].equipment.find(i=>i.equip===row.equip),slot=asc.giveEquipment(row.equip),inv=asc.s.inventory.find(i=>i.slot===slot);inv.enhance=10;inv.enhancementCap=10;asc.action('EQUIP',{slot,owner:historical.owner});}
asc.action('PLACE_ENTER',{place:'EVT_SCHEDULE_MRC_MOND_EQUIP',mode:'CRAFT'});
for(const inv of asc.s.inventory.filter(i=>i.equip&&i.enhance===10&&i.enhancementCap===10)){const quote=cp(asc.enhancementQuote(inv.slot,'ASCEND'));assert(quote.supported);for(const [item,n]of Object.entries(quote.cost.items))asc.giveItem(item,n);const mora=asc.s.global.MORA,result=asc.action('EQUIP_ASCEND',{slot:inv.slot,expectedLevel:10,expectedCap:10}),after=asc.s.inventory.find(i=>i.slot===inv.slot);assert.equal(after.enhancementCap,12);assert.equal(mora-asc.s.global.MORA,quote.cost.mora);assert.equal(after.enhance,10);const next=asc.enhancementQuote(inv.slot);assert(next.supported);assert.equal(next.target,11);for(const [item,n]of Object.entries(next.cost.items))asc.giveItem(item,n);assert.equal(asc.enhancementQuote(inv.slot).reason,'');ascensions.push({equip:inv.equip,quote,result:cp(result.result),actualCap:after.enhancementCap,actualMoraPaid:mora-asc.s.global.MORA,nextPublicQuote:cp(asc.enhancementQuote(inv.slot))});}
const rows=[];
for(const c of ['c0','c2','c6'])for(const row of datasets[c].rows){assert.equal(row.enh,12);for(const i of row.equipment.filter(i=>!i.artifact)){assert.equal(i.enhance,12);assert.equal(i.enhancementCap,12);assert(inspect.enhancementHasGain(i));}for(const i of row.equipment.filter(i=>i.artifact)){assert.equal(i.artifact.level,5);assert.equal(i.enhance,0);}const companion=datasets.c0.rows.find(r=>r.seed===row.seed);assert.deepEqual(row.equipment,companion.equipment);assert.deepEqual(row.artifacts,companion.artifacts);assert.deepEqual(Object.fromEntries(Object.entries(row.talents).map(([id,t])=>[id,t.base])),Object.fromEntries(Object.entries(companion.talents).map(([id,t])=>[id,t.base])));rows.push({policy:c.toUpperCase(),seed:row.seed,enhance:row.enh,cap:12,state:row.state,totalRounds:row.rounds,rooms:row.rooms.map(v=>({chamber:v.chamber,state:v.state,rounds:v.rounds,ko:v.ko,minHpBySource:v.metrics.minHpBySource,hpDamage:v.metrics.hpDamage,shieldSpent:v.metrics.shieldSpent,healActual:v.metrics.healActual})),artifacts:row.artifacts.map(a=>({owner:a.owner,attempts:a.attempts,level:a.instance.artifact.level,quality:a.instance.artifact.quality,stats:a.stats})),sameEquipmentArtifactsAndBaseTalentsAsC0:true});}
// Replay only public first-room construction, not an already measured full
// battle. Native before/current actors, order, gates and RNG must match.
function entry(e,row){const r=H.setup(e,{level:60,team,seed:row.seed,map:'MAP_V141_MUSK_REEF',gear:'none',talent:10});r.s.inventory=cp(row.equipment);r.s.global.NEXT_INVENTORY_INSTANCE_SEQ=Math.max(...row.equipment.map(i=>Number(i.slot.replace(/^EQI_/,''))))+1;r.s.constellations=cp(row.constellations);r.s.talents=cp(Object.fromEntries(Object.entries(row.talents).map(([id,t])=>[id,t.base])));r.action('FORMATION_SET',{formation:'DOUBLE_LINE'});['연계우선','공격우선','지원우선'].forEach((t,i)=>r.action('PARTY_TACTIC',{slot:i+2,tactic:t}));const ab=r.ensureAbyss();for(let n=1;n<12;n++)ab.clears[n]={rounds:1,chambers:[1,1,1],party:[],run:ab.run};r.recalculate();r.s.global.PLAYER_HP_CURRENT=r.s.global.PLAYER_HP_MAX;for(const id of team)r.s.chars[id].hp=r.character(id).maxHp;r.s.global.PRNG_STATE=row.seed;assert.equal(r.abyssFloorReason(12),'');r.action('ABYSS_ENTER',{floor:12});return r;}
const nativeEntries=[];for(const c of ['c0','c2'])for(const row of datasets[c].rows){const a=entry(before,row),b=entry(env,row);assert.deepEqual(cp(b.s.runtime.actors),cp(a.s.runtime.actors));assert.deepEqual(cp(b.s.runtime.order),cp(a.s.runtime.order));assert.equal(b.s.global.PRNG_STATE,a.s.global.PRNG_STATE);assert.equal(b.s.runtime.enemyBalanceRevision,undefined);assert(b.abyssMasteryReady());nativeEntries.push({policy:c.toUpperCase(),seed:row.seed,actors:cp(b.s.runtime.actors),order:cp(b.s.runtime.order),rng:b.s.global.PRNG_STATE,mastery:true,beforeAndFinalNativeEntryEqual:true});}
const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,'docs/data/balance_v01627/before/source_manifest.json'))),protectedPaths=['source/runtime_abyss.js','source/runtime_enhancement.js','source/runtime_liyue_artifacts.js','source/runtime_gear_traits.js','source/runtime_combat_v0148.js'],sourceHashes={};for(const p of protectedPaths){const old=manifest.entries.find(e=>e.path===p);sourceHashes[p]=sha(fs.readFileSync(path.join(ROOT,p)));assert.equal(sourceHashes[p],old.sha256);}
assert.equal(H.load(ROOT).fingerprint,env.fingerprint,'source stable for whole read-only review');
const data={scope:'Existing genuine 0.16.26 full +12 benchmark verified, plus final 0.16.27 native first-room entry and public cap-ascension proof. No new full battle runs.',beforeFingerprint:before.fingerprint,currentFingerprint:env.fingerprint,archives:Object.fromEntries(Object.entries(datasets).map(([k,v])=>[k,{path:v.path,sha256:v.sha256,fingerprint:v.fingerprint}])),sourceHashes,equipmentStats,publicAscensions:ascensions,rows,nativeEntries,limitations:['Preparation grants acquired ownership, grown stats, naturally generated artifacts, equipment and finite items; it does not prove complete natural account procurement.','12F artifacts use the first naturally gate-qualified roll, up to 4000 per owner, not fixed best-of-80. Actual sample attempts are reported.','Three seeds per constellation with the fixed native roster/control policy are observational cases, not a population win-rate estimate.','Final source retains native Abyss combat policies; earlier complete combat results are preserved separately and not counted as new runs.']};
fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,'proof.json'),JSON.stringify(data,null,2)+'\n');fs.copyFileSync(__filename,path.join(OUT,'runner.cjs'));console.log(JSON.stringify({status:'PASS',beforeFingerprint:before.fingerprint,currentFingerprint:env.fingerprint,priorFullBattleConditions:rows.length,newFullBattleRuns:0,firstRoomComparisons:nativeEntries.length,publicAscensionActions:ascensions.length,equipmentStats}));
